### ISSUE TITLE
Modify register -1 input error

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#100]
![error](https://cloud.githubusercontent.com/assets/18622105/18090068/fb718cc0-6efd-11e6-9632-8de55ec4d7a1.png)

32bit process register  -1 input => reopen data error 

No Error -> FF FF FF FF
Error(Long data 8byte) FF FF FF FF FF FF FF FF

**Comment by cheat-engine** [comment]
Not a big issue as a 32-bit register will only get the lower bits anyhow

**Comment by kitty8904** [comment]
Changing registers , no problem

Just be only a matter of displaying the register information error
