### ISSUE TITLE
(1000th issue :)) Cheat engine 7.0 won't open, neither will previous versions

### ISSUE THREAD

**Issue by vaughngaminghd** [cheat-engine/cheat-engine#1001]
this is for speedhacking on geometry dash (((((for fun)))))

**Comment by TheGoldenCdr** [comment]
I am having the same problem. I'm using a Windows 10 64 Bit OS. In task manager, the cheat engine opens, then immediately closes. I've been having this problem since September of this year.

**Comment by cheat-engine** [comment]
https://github.com/cheat-engine/cheat-engine/issues/958

**Comment by TRYTONSE213** [comment]
it dont works for me

**Comment by vaughngaminghd** [comment]
oh, i uninstalled badlion. it works now, thanks! any idea why badlion deactivates cheat engine?

**Comment by TheK0tYaRa** [comment]
Because it has an anticheat that probably installs it's nasty driver
