### ISSUE TITLE
Memory Viewer -> Tools -> Scan For Patches - dont work

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#1002]
Using the "Scan For Patches" finds nothing if a module got patched by external. If this is not a bug then a better name would be "Scan For Own Patches" or "Show Own Patches" to make it clear.

**Comment by cheat-engine** [comment]
Make sure you select all the modules you are interested in

also, you have better results on 64 bit targets

**Comment by Symbai** [comment]
You are right. I was doing some things wrong. Please forgot what I said then

**Comment by Symbai** [comment]
Seems to be missing in source. Did you removed it intentionally?
