### ISSUE TITLE
DBVM "Find what accesses this address" break everytime

### ISSUE THREAD

**Issue by KSbread** [cheat-engine/cheat-engine#1004]
when i try to use DBVM "Find what accesses this address",  cheat engine just break on the address which access the data and not add the instruction to list... when i use hardware breakpoint to do same things , it works well.....
 
sometimes i cant choose dbvm like this
![image](https://user-images.githubusercontent.com/23270597/69652109-79b0a980-10b4-11ea-8b9e-ecafe1f280a3.png)
![image](https://user-images.githubusercontent.com/23270597/69652155-8e8d3d00-10b4-11ea-85a8-79a172a86629.png)

and sometime i can choose it...

and sry for my poor english..

**Comment by cheat-engine** [comment]
Which debugger interface do you use ?

**Comment by KSbread** [comment]
> Try doing this without a debugger attached (Also which debugger interface do you use ? (windows, veh ?) ) 

i used kernel mode debugger... i tried without attached,but seems it just show instruction which write data and not show read...

**Comment by KSbread** [comment]
![image](https://user-images.githubusercontent.com/23270597/69654404-16287b00-10b8-11ea-939f-d3fd37726853.png)
![image](https://user-images.githubusercontent.com/23270597/69654443-29d3e180-10b8-11ea-86f0-1b6f088ac7b0.png)

**Comment by cheat-engine** [comment]
What it's showing looks like the read of CE so that might be valid.

**Comment by KSbread** [comment]
> What it's showing looks like the read of CE so that might be valid.

thanks for your answer. i'll try later

**Comment by KSbread** [comment]
> What it's showing looks like the read of CE so that might be valid.

hey, is there any function that can hide ce process or hide dbk driver ?

**Comment by cheat-engine** [comment]
Not automatically,  butbyou can use memory cloaking of dbvm to patch the kernel without pathguard crashing you
Use that to hide CE
