### ISSUE TITLE
Additional Software Installation - Antivirus+

### ISSUE THREAD

**Issue by hydrogen2oxygen** [cheat-engine/cheat-engine#1005]
How is it possible that an open source software promotes Adware or "AntiVirus" still in the year 2019. Please remove this stuff! Else it seems that you are not at all trustworthy and then people will begin to flag you as "adware installer". Never ever install such stuff. It ruins your credibility.

**Comment by TheK0tYaRa** [comment]
Installer has a box to untick. Program has source code that you can compile. there is literally more than 50% chance of you not installing it if you look before clicking `Next`
