### ISSUE TITLE
debug detect

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1006]
I searched for anticheat breakpoint detection

debuggera.asm

call interrupt1_centry

return eax,1

cmp al,1

je skip_original_int1 <-here

--skip_original_int1 delete

if you don't jump to skip_original_int1

Not detected

//////////////////////////////

Not a global debug detection

1. Load DBVM and attach processes

2.Game Load

3.Read the interrupt1_centry function area 50 ~ 100 times

Deleting skip_original_int1 reads less than 10 times and is not detected

Is it timing detection?

Non-global debug

If you load the DBVM and attach a process at least once

Is detected

//////////////////////////////////////////////////////////////////

without calling the f5, f6 debug function

Just load the DBVM and attach the process once
(Even if the target process is not a game detect)

Is detected

I don't know how it is detected

Do you have a detour idea?

**Comment by cheat-engine** [comment]
Sounds like the driver handles breakpoints it shouldn't
Is your option to "override existing breakpoints" checked? in settings?
If so, uncheck it and see how that goes

**Comment by kitty8904** [comment]
> Sounds like the driver handles breakpoints it shouldn't
> Is your option to "override existing breakpoints" checked? in settings?
> If so, uncheck it and see how that goes
> 
> And it could be stack corruption. When you say "Detected" do you mean a message shows up, or does it instantly close ?

override existing breakpoints -> no check

Is detection possible in ring3?

There is no drive load but it seems to be detected

Detection is found immediately within 10 seconds

Continue to detect until the drive is unloaded or rebooted

1. Disable global debug

2. F5 & F6 Debug no execute

3.Load DBVM and only attach process
