### ISSUE TITLE
Production configuration is missing

### ISSUE THREAD

**Issue by JennyQAQ** [cheat-engine/cheat-engine#1007]
Because I cannot open CE installer on MacOS, so I typed this "sudo codesign -f -s - --deep /Applications/cheatengine-i386.app" into terminal and then it could be open. But as I opened it, it says "product configuration is missing", is there any method that I could solve this?
<img width="824" alt="Screen Shot 2019-11-27 at 12 20 04 PM" src="https://user-images.githubusercontent.com/54223867/69693892-e8702000-1111-11ea-9c08-5fff88f4a29f.png">
<img width="581" alt="Screen Shot 2019-11-27 at 12 30 01 PM" src="https://user-images.githubusercontent.com/54223867/69693895-ec03a700-1111-11ea-8af4-19989de597a2.png">

**Comment by TheK0tYaRa** [comment]
Something similliar happens on Windows, except it's solved by changing build type to `release`
