### ISSUE TITLE
images.res missing?

### ISSUE THREAD

**Issue by CryptXor** [cheat-engine/cheat-engine#101]
After the last few commits, building fails continually?
```
cheatengine.lpr(271,1) Error: Can't open resource file "<blablabla>\cheat-engine\Cheat Engine\images.res"
```

**Comment by CryptXor** [comment]
```delphi
//{$R images.res}
{$R Sounds.res}          
```

Commenting out that file fixes the build, but I suspect it has been inadvertently deleted?

**Comment by rzndsa** [comment]
Just change it to
{$R Sounds.rc}
{$R images.rc}
//{$R images.res}
//{$R Sounds.res}

**Comment by cheat-engine** [comment]
images.res is added
