### ISSUE TITLE
Minor: Override group config

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#1010]
I understand that some table creators change group config to hide children when deactivated to avoid table consumers getting spammed with lots of items. I however find this quite annoying as I have to change it back all the time when trying to view the children either without activating at all but especially when not attached to a process but just viewing the table items.

It would be great if there is an option to override this for advanced users. Or at least expand when not attached to a process.

**Comment by mgrinzPlayer** [comment]
To mass remove this option you can open CT file inside text editor and find&replace all
`<Options moHideChildren="1"/>`
with empty string then save.

Also, you can expand those "hide children when deactivated". You have to tick both:
- "allow left and right arrow keys to collapse and expand"
- "manual expand/collapse"

Again you can do it with external text editor find&replace all
`<Options moHideChildren="1"/>`
with
`<Options moHideChildren="1" moManualExpandCollapse="1" moAllowManualCollapseAndExpand="1"/>`
then save.

**Comment by Symbai** [comment]
I know I can do it myself with some afford but I would appreciate CE doing this for me so I don't have to do this all myself when I notice a CE author using that option ( which happens after loading a CE table so doing search and replace force me to reopen).

Would be nice to gain more control if desired since these options are clearly for "consumers" and there are good reasons to not behave like this when opening and browsing a table without even attaching to game.

**Comment by mgrinzPlayer** [comment]
You can write an extension for this.
```Lua
local function addMenuItem(parent,caption)
  if parent==nil then return nil end
  local newItem = createMenuItem(parent); parent.add(newItem)
  newItem.Caption = caption
  return newItem
end

local menuItem_help = getMainForm().miHelp

addMenuItem(menuItem_help,'Reveal "expandable" memory records...').setOnClick(
  function ()
    local al = getAddressList()
    for i=0,al.Count-1 do
      local mr = al[i]
      if mr.Count>=1 and mr.Options:match("moHideChildren") then
         mr.Options = mr.Options:sub(1,-2)..",moManualExpandCollapse,moAllowManualCollapseAndExpand]"
      end
    end
  end)
```

**Comment by Symbai** [comment]
Possible to autorun this function every time I open a cheat engine table?

**Comment by mgrinzPlayer** [comment]
Not easy because there's no "on cheat table loaded" event exposed to CE Lua. Yes, possible.
Wait.

**Comment by mgrinzPlayer** [comment]
here

```Lua
local script
if cheatEngineIs64Bit() then
script = [[
aobscanmodule(LoadXML_Epilogue,400000,55 48 89 CD 48 8D 64 24 E0 48 8D 0D xx xx xx xx E8 xx xx xx xx 48 83 BD xx xx xx xx 00) // should be unique
alloc(newmem,$1000,400000)
label(return)
label(timerObjectAddress)
registersymbol(timerObjectAddress)

newmem:
  push rbp

  mov rbp,[timerObjectAddress]
  cmp rbp,0
  jz @f

  mov [rbp+28],1 // set Tag field to one

@@:
  mov rbp,rcx
  lea rsp,[rsp-20]
  jmp return

timerObjectAddress:
dq 0

LoadXML_Epilogue:
  jmp newmem
  nop
  nop
  nop
  nop
return:
]]
else
script = [[
aobscanmodule(LoadXML_Epilogue,400000,B8 xx xx xx xx E8 xx xx xx xx 83 BD xx xx xx xx 00) // should be unique
alloc(newmem,$1000)
label(return)
label(timerObjectAddress)
registersymbol(timerObjectAddress)

newmem:
  mov eax,[timerObjectAddress]
  cmp eax,0
  jz @f

  mov [eax+14],1 // set Tag field to one

@@:
  readmem(LoadXML_Epilogue,5)
  jmp return

timerObjectAddress:
dq 0

LoadXML_Epilogue:
  jmp newmem
return:
]]
end

local function dostuff(timer)
  if timer.Tag == 0 then return end

  -- force moManualExpandCollapse and moAllowManualCollapseAndExpand for all memrec with children and moHideChildren
  local al = getAddressList()
  for i=0,al.Count-1 do
    local mr = al[i]
    if mr.Count>=1 and mr.Options:match("moHideChildren") then
       mr.Options = mr.Options:sub(1,-2)..",moManualExpandCollapse,moAllowManualCollapseAndExpand]"
    end
  end

  timer.Tag = 0
end

if autoAssemble(script,true) then
  local timerObject = createTimer(MainForm,true)
  timerObject.Interval = 500
  timerObject.OnTimer = dostuff

  local timerObject_address = userDataToInteger(timerObject)
  writeQwordLocal("timerObjectAddress", timerObject_address)
end
```

**Comment by Symbai** [comment]
Hmmm this might break on CE updates. Sounds like a good API request #1023

**Comment by mgrinzPlayer** [comment]
Since CE7.1, you can use this as autorun script:
```Lua
local function RevealExpandableMemoryRecords()
  -- force moManualExpandCollapse and moAllowManualCollapseAndExpand for all memrec with children and moHideChildren
  for i=0,AddressList.Count-1 do
    local mr = AddressList[i]
    if mr.Count>=1 and mr.Options:match("moHideChildren") then
       mr.Options = mr.Options:sub(1,-2)..",moManualExpandCollapse,moAllowManualCollapseAndExpand]"
    end
  end
end

local previousOnTableLoad = onTableLoad

function onTableLoad(before)
  if previousOnTableLoad then previousOnTableLoad(before) end
  if before==false then RevealExpandableMemoryRecords() end
end
```
