### ISSUE TITLE
Assembler fails on "test ecx,[rax+12345]"

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#1013]
![image](https://user-images.githubusercontent.com/14368203/69887560-72b9af00-12df-11ea-972a-8e65a3dfd16f.png)

**Comment by mgrinzPlayer** [comment]
Correct.
There's no 
**TEST  r32 ,r/m32**
or
**TEST r64 ,r/m64**

|Opcode |Instruction |Op/En |64-Bit Mode |Compat/Leg Mode |Description|
|---|---|---|---|---|---|
|A8 ib |TEST AL, imm8 |I |Valid |Valid |AND imm8 with AL; set SF, ZF, PF according to result.|
|A9 iw |TEST AX, imm16 |I |Valid |Valid |AND imm16 with AX; set SF, ZF, PF according to result.|
|A9 id |TEST EAX, imm32 |I |Valid |Valid |AND imm32 with EAX; set SF, ZF, PF according to result.|
|REX.W + A9 id |TEST RAX, imm32 |I |Valid |N.E. |AND imm32 sign-extended to 64-bits with RAX; set SF, ZF, PF according to result.|
|F6 /0 ib |TEST r/m8, imm8 |MI |Valid |Valid |AND imm8 with r/m8; set SF, ZF, PF according to result.|
|REX + F6 /0 ib |TEST r/m8*, imm8 |MI |Valid |N.E. |AND imm8 with r/m8; set SF, ZF, PF according to result.|
|F7 /0 iw |TEST r/m16, imm16 |MI |Valid |Valid |AND imm16 with r/m16; set SF, ZF, PF according to result.|
|F7 /0 id |TEST r/m32, imm32 |MI |Valid |Valid |AND imm32 with r/m32; set SF, ZF, PF according to result.|
|REX.W + F7 /0 id |TEST r/m64, imm32 |MI |Valid |N.E. |AND imm32 sign-extended to 64-bits with r/m64; set SF, ZF, PF according to result.|
|84 /r |TEST r/m8, r8 |MR |Valid |Valid |AND r8 with r/m8; set SF, ZF, PF according to result.|
|REX + 84 /r |TEST r/m8*, r8* |MR |Valid |N.E. |AND r8 with r/m8; set SF, ZF, PF according to result.|
|85 /r |TEST r/m16, r16 |MR |Valid |Valid |AND r16 with r/m16; set SF, ZF, PF according to result.|
|85 /r |TEST r/m32, r32 |MR |Valid |Valid |AND r32 with r/m32; set SF, ZF, PF according to result.|
|REX.W + 85 /r |TEST r/m64, r64 |MR |Valid |N.E. |AND r64 with r/m64; set SF, ZF, PF according to result.|

**Comment by Symbai** [comment]
Then most popular assemblers, keystone for example, are wrong, because they can assemble it. Or they can because it doesn't matter if `test ecx,[rax+12345]` or `test [rax+12345],ecx`

**Comment by mgrinzPlayer** [comment]
Newest x64dbg also doesn't recognize "test ecx,[rax+12345]"

Which disassembly-flavor keystone uses? AT&T or Intel?

**Comment by Symbai** [comment]
x64dbg uses XEDParse which development stopped 4 years ago. No idea about keystone but its in active development. What does CE use? masm? nasm? Seems like a custom one. Are there any other assemblers to quickly test it on?

**Comment by mgrinzPlayer** [comment]
iirc, DarkByte uses Intel documentation.

Official Intel document, updated October 2019:
https://software.intel.com/sites/default/files/managed/39/c5/325462-sdm-vol-1-2abcd-3abcd.pdf#G32.260326

There's no _m32_ or _m64_ second operand for _test_ instruction.

**Comment by Symbai** [comment]
So Lazarus itself is wrong?

**Comment by cheat-engine** [comment]
Assembling `test [rax + 12345], ecx` assembles into `85 88 39 30 00 00`
But ifbyou disassemble that it says `test ecx,[rax+12345]`

which means it didn't assemble what you wanted, so in a way a bug

**Comment by Symbai** [comment]
So weird... 🤔

**Comment by mgrinzPlayer** [comment]
yes, 85 88 39 30 00 00 disassembled in:
- CE gives: test [rax+00003039],ecx
- x64dbg gives: test dword ptr ds:[rax+0x3039], ecx
