### ISSUE TITLE
installer does not launch on Mac

### ISSUE THREAD

**Issue by exekutive** [cheat-engine/cheat-engine#1017]
Installer quit unexpectedly.
Can't we just use the app without an installer?

Process:               Ascabart [45235]
Path:                  /Users/USER/Downloads/CheatEngineMacInstaller.app/Contents/MacOS/Ascabart
Identifier:            com.unrebuttableness.basiparaplastin
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Ascabart [45235]
User ID:               501

Date/Time:             2019-12-01 00:04:49.503 -0800
OS Version:            Mac OS X 10.14.6 (18G1012)
Report Version:        12
Anonymous UUID:        C88196BE-8787-4591-AE0A-1144D45176B0

Sleep/Wake UUID:       9A44D905-8863-49AC-B3B8-C5C9555F9A4E

Time Awake Since Boot: 360000 seconds
Time Since Wake:       28000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 000000010c7bc000-000000010c80f000 [  332K] r-x/rwx SM=COW  

Thread 0 Crashed:
0                                 	0x000000011c781000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee3443bd0
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x000000011c781000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0

Binary Images:
       0x10c7bc000 -        0x10c80efff + (???) <361075F1-D756-3D8C-9378-F3069220346E> 
       0x11c780000 -        0x11c7ea70f + (655.1.1) <615654D5-B6C5-3D83-A146-34A3EA6D3A80> 

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 233809
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=948K resident=0K(0%) swapped_out_or_unallocated=948K(100%)
Writable regions: Total=8400K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8400K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             236K        3 
__LINKEDIT                         188K        2 
__TEXT                             760K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             65.2M       11 

Model: MacBookPro11,2, BootROM 156.0.0.0.0, 4 processors, Intel Core i7, 2.2 GHz, 16 GB, SMC 2.18f15
Graphics: kHW_IntelIrisProItem, Intel Iris Pro, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (7.77.61.3 AirPortDriverBrcmNIC-1305.9)
Bluetooth: Version 6.0.14d3, 3 services, 27 devices, 1 incoming serial ports
Network Service: iPhone, Ethernet, en4
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0256F, 251 GB
USB Device: USB 3.0 Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: iPhone
Thunderbolt Bus:

**Comment by cheat-engine** [comment]
apple revoked the signature because CE is dangerous.

But i'll bring out a version without signature soon. But might be a patreon only thing for a while as this means there's currently no ad-revenue to be made from the mac install (and no fan of having ads in the main program)

**Comment by exekutive** [comment]
I thought SIP protects system files from being modified. Does CE modify system files?

**Comment by exekutive** [comment]
Also, I hope there will still be a way to try out the program before having to pay for it.

**Comment by cheat-engine** [comment]
Here's the current build. 
Memory scanning works, debugging kinda works on the tutorial
Saving and loading tables probably won't work if you're on the latest Mac version and running as privileged, but earlier may work.

Debugging likely requires SIP to be disabled (or perhaps even running CE in the first place)

[ce 64-bit unsigned extremely unstable.zip](https://github.com/cheat-engine/cheat-engine/files/3910630/ce.64-bit.unsigned.extremely.unstable.zip)

**Comment by exekutive** [comment]
CE and tutorial launch for me. The first tutorial dialog isn't readable in dark mode though. Will let you know how it goes ...

**Comment by cheat-engine** [comment]
Let me know if saving works. I'm not sure if it's my mac that needs a reinstall or if it's a thing apple has done on purpose

**Comment by exekutive** [comment]
A few things:

- asks for my password on every launch
- button text doesn't fit
- Settings menu text is upside down
- "access violation" error every time I quit
- Saving doesn't produce any errors, but then writes a file with headers but no data:
<?xml version="1.0" encoding="utf-8"?>
<CheatTable CheatEngineTableVersion="10">
  <CheatEntries/>
  <UserdefinedSymbols/>
</CheatTable>


<img width="532" alt="Screen Shot 2019-12-04 at 20 57 24" src="https://user-images.githubusercontent.com/4755215/70205447-e6412f00-16d8-11ea-8670-9b651adee61b.png">
<img width="1254" alt="Screen Shot 2019-12-04 at 20 56 49" src="https://user-images.githubusercontent.com/4755215/70205448-e6412f00-16d8-11ea-92cf-b4a8bb49e56e.png">
<img width="1080" alt="Screen Shot 2019-12-04 at 20 56 22" src="https://user-images.githubusercontent.com/4755215/70205449-e6412f00-16d8-11ea-83b0-d9d81e030882.png">

**Comment by cheat-engine** [comment]
which mac version is this? Catalina? 
Did you have addresses in the addresslist when you saved?

**Comment by exekutive** [comment]
yes Mojave.
OK going through the tutorial now ... now that I have an address in the bottom list it is showing up in the save

```
<?xml version="1.0" encoding="utf-8"?>
<CheatTable CheatEngineTableVersion="10">
  <CheatEntries>
    <CheatEntry>
      <ID>0</ID>
      <Description>"No description"</Description>
      <Color>80000008</Color>
      <VariableType>4 Bytes</VariableType>
      <Address>1005ACEA0</Address>
    </CheatEntry>
  </CheatEntries>
  <UserdefinedSymbols/>
</CheatTable>
```

For user friendliness, I think there should be a button and menu item to drill down on an address, in addition to the double-click.

**Comment by cheat-engine** [comment]
drill down?  Do you mean like rightclicking ? (ctrl+click I guess if you have an original mac mouse)

**Comment by exekutive** [comment]
I mean add a search result to the bottom list.

Right-clicking only gives me 3 options: browse, disassemble and remove. "Add" could be added here too.

**Comment by exekutive** [comment]
It's really time consuming to find the process you want. I would help to have better sorting here.

<img width="419" alt="Screen Shot 2019-12-06 at 04 10 28" src="https://user-images.githubusercontent.com/4755215/70322217-60a7a700-17de-11ea-9d7f-29ba4081f2c9.png">

**Comment by cheat-engine** [comment]
rightclick and choose filter

**Comment by exekutive** [comment]
Thanks that helps.

I just noticed you can add addresses with the red arrow, but it only seems to work sometimes.

**Comment by exekutive** [comment]
the debugger window is a bit screwy too

<img width="864" alt="Screen Shot 2019-12-06 at 18 00 07" src="https://user-images.githubusercontent.com/4755215/70367159-4dceba00-1852-11ea-8e38-ff2ab369ac1d.png">

**Comment by cheat-engine** [comment]
fixed now that the mac version is merged with the main trunk
