### ISSUE TITLE
is "Ability to step through kernel code" avaliable?

### ISSUE THREAD

**Issue by KSbread** [cheat-engine/cheat-engine#1019]
How to use "Ability to step through kernel code"? when i set a breakpoint in kernel code , nothing happened....

**Comment by cheat-engine** [comment]
half half
It only works if the instruction is triggered if the cpu is in a interrupt enabled passive level irq state.
And even then you can still crash if you enter a place that enters a mutex
For real kernelmode stepping you'll need a serial port and another system (as the GUI is often unreachable)

**Comment by KSbread** [comment]
> half half
> It only works if the instruction is triggered if the cpu is in a interrupt enabled passive level irq state.
> And even then you can still crash if you enter a place that enters a mutex
> For real kernelmode stepping you'll need a serial port and another system (as the GUI is often unreachable)
> 
> Also, only DBVM breakpoints or when global debug is used can be set for kernelmode memory. Setting breakpoints the normal way won't work as windows removes them

Thanks for your awnser....

the "dbvm find out what access this address" --- the "address" means physical address or virtualaddress？ if target process use mapviewofsection , does it still work?

**Comment by cheat-engine** [comment]
physical memory. if you do it after the view has mapped yes, it will show.
