### ISSUE TITLE
unable to activate script

### ISSUE THREAD

**Issue by exekutive** [cheat-engine/cheat-engine#1024]
CE isn't letting me activate this script. Pressing space or right-click->Toggle does nothing. Any idea why?

<img width="705" alt="Screen Shot 2019-12-06 at 19 14 12" src="https://user-images.githubusercontent.com/4755215/70368244-00a41580-185d-11ea-8bd6-9194ff89016e.png">

the table file: https://fearlessrevolution.com/download/file.php?id=2752

**Comment by cheat-engine** [comment]
It may have trouble finding the guac.exe memory region
Or the game used a different compiler and the aob is different

**Comment by exekutive** [comment]
> the game isn't running on your computer and you're just looking at a video of the game

Thanks but I'm not an imbecile

**Comment by Symbai** [comment]
There is a previous discussion how this can be improved in which mrgrinzPlayer gave some hints on what users currently have to do to see why its failing: https://github.com/cheat-engine/cheat-engine/issues/1009

**Comment by exekutive** [comment]
right clicking doesn't show any errors. If I open the script and click 'OK' I get
<img width="532" alt="Screen Shot 2019-12-07 at 13 07 01" src="https://user-images.githubusercontent.com/4755215/70380600-bec5ae80-18f2-11ea-9a23-4f16b13c5ec7.png">

**Comment by cheat-engine** [comment]
i misread and thought the processname was gameStream

anyhow, check if the aobscan lines in the script can be found by doing a normal aob scans (set all options to gray when scanning)
it is very likely that the windows version has different byte code than the mac build

**Comment by exekutive** [comment]
You're right. AOB not found.
