### ISSUE TITLE
Disassembling functions on Cheat Engine 6.2 for Mac 64bit

### ISSUE THREAD

**Issue by asinel** [cheat-engine/cheat-engine#1025]
Hi, I tried experimental 64 bit version of CE, it successfully launched and attached to process, but disassembling functions such "Dissect code", "Referenced strings", "Search memory" are not working.
I tried it on free game from Steam - Crusader Kings II.

How can I make it work, or maybe I need to try another version of CE?

**Comment by cheat-engine** [comment]
Those functions haven't been ported yet but will be in the future

**Comment by asinel** [comment]
I mean searching assembly code, like on the screenshot (windows version)

![](https://i.gyazo.com/607f85c616f72cd296c2f06b1308f5bd.png)

**Comment by cheat-engine** [comment]
ah that window. Yeah, will be added as well

**Comment by asinel** [comment]
What is a roadmap for these features?
Will it be added in a month or in a year? Thank you

**Comment by asinel** [comment]
Any updates on this?

**Comment by cheat-engine** [comment]
I haven't fully tested it but it should work

**Comment by asinel** [comment]
It works, thank you
