### ISSUE TITLE
cheat engine 7.1

### ISSUE THREAD

**Issue by frustreated** [cheat-engine/cheat-engine#1028]
![image](https://user-images.githubusercontent.com/5463104/70602974-927e9a80-1c30-11ea-8847-6e66b953464d.png)

personally compiled as above result
the same two results addrs

**Comment by mgrinzPlayer** [comment]
Already reported here: https://github.com/cheat-engine/cheat-engine/issues/1018

**Comment by frustreated** [comment]
i have to say that this new version corrected the above issue, yes it is truely this version.
