### ISSUE TITLE
auto assemble off set to big bug

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1030]
x64process target autoassemble off set to big error

globalalloc(Read,1024)

Read:
mov rax,[ntdll.dll]
mov rbx,[ntdll.dll]
mov rcx,[ntdll.dll]
mov rdx,[ntdll.dll]
mov rsp,[ntdll.dll]
mov rbp,[ntdll.dll]
mov rsi,[ntdll.dll]
mov rdi,[ntdll.dll]
mov r9,[ntdll.dll]
mov r10,[ntdll.dll]
mov r11,[ntdll.dll]
mov r12,[ntdll.dll]
mov r13,[ntdll.dll]
mov r14,[ntdll.dll]
mov r15,[ntdll.dll]
ret

mov rax,[ntdll.dll] -> read ok

mov rbx~~mov r15 -> offset too big error message

I get an error except for rax

**Comment by cheat-engine** [comment]
That is correct. x86_64 only supports mov rax,[64bitvalue]  , no other register can do a memory reference like that
What you can do is 
```
mov rbx,ntdll.dll 
mov rbx,[rbx]
```
for a similar effect for other registers

**Comment by kitty8904** [comment]
Is this a cheat engine error?

Or is it the intended design?

I found it when writing a game memory copy script

**Comment by cheat-engine** [comment]
intended design. the CPU itself can not encode this

**Comment by frustreated** [comment]
> That is correct. x86_64 only supports mov rax,[64bitvalue] , no other register can do a memory reference like that
> What you can do is
> 
> ```
> mov rbx,ntdll.dll 
> mov rbx,[rbx]
> ```
> 
> for a similar effect for other registers

a new lesson for me, @cheat-engine
