### ISSUE TITLE
the selection of language's index

### ISSUE THREAD

**Issue by frustreated** [cheat-engine/cheat-engine#1034]
![image](https://user-images.githubusercontent.com/5463104/70840680-dcdd6280-1e4e-11ea-8e85-8ce316bea8e2.png)
the newest version ,when change language to the last index , will pop up error index.
![image](https://user-images.githubusercontent.com/5463104/70840699-03030280-1e4f-11ea-8ae8-67f4d328911a.png)

if you change the second choice ,it is the third choice selected.

**Comment by frustreated** [comment]
translaltion of Chinese duplicated, picture as follows
![image](https://user-images.githubusercontent.com/5463104/70847663-c01e4a80-1ea1-11ea-8edb-b6cac3b21038.png)

**Comment by BlankUserLing** [comment]
第一个是数组越界 -1 就行 
第2个是翻译文件的问题跟换一个翻译文件即可，或者自己翻译一下
