### ISSUE TITLE
Failure injecting the MonoDatacollector dll

### ISSUE THREAD

**Issue by AGlezB** [cheat-engine/cheat-engine#1036]
CE 7.0, Win 10 Pro 1909.
This started after updating to Windows 10 1909.
Tested with several GOG Unity games that where injecting correctly before the update.

**Comment by Taiwendo** [comment]
Same Problem here
Version 6.8.3 no Problems with WIndows 10 Build 1909
Version 7.0 call error in LUA console: Failure injecting the MonoDatacollector.dll

**Comment by AGlezB** [comment]
> Same Problem here
> Version 6.8.3 no Problems with WIndows 10 Build 1909
> Version 7.0 call error in LUA console: Failure injecting the MonoDatacollector.dll

Good to know I can go back to 6.8.3

**Comment by cheat-engine** [comment]
try https://github.com/cheat-engine/cheat-engine/blob/master/Cheat%20Engine/bin/autorun/dlls/MonoDataCollector64.dll?raw=true

**Comment by AGlezB** [comment]
Works fine the the new DLL.

**Comment by Madpixel6** [comment]
> try https://github.com/cheat-engine/cheat-engine/blob/master/Cheat%20Engine/bin/autorun/dlls/MonoDataCollector64.dll?raw=true

New link to the dll, as the previous one is broken:
[64bit](https://github.com/cheat-engine/cheat-engine/blob/9bc05a8374102566f2ef1d9f84adf1e56a623fe0/Cheat%20Engine/bin/autorun/dlls/MonoDataCollector64.dll)
[32bit](https://github.com/cheat-engine/cheat-engine/blob/9bc05a8374102566f2ef1d9f84adf1e56a623fe0/Cheat%20Engine/bin/autorun/dlls/MonoDataCollector32.dll)
