### ISSUE TITLE
Disassembler makes no difference between NOP rm16/rm32/rm64

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#1039]
Disassembler makes no real difference between NOP r/m16 and NOP r/m32 and NOP r/m64:
![image](https://user-images.githubusercontent.com/14368203/71308570-29e4aa00-23f6-11ea-8e05-e6545a3b6bfb.png)

Disassembler.io output:
![image](https://user-images.githubusercontent.com/14368203/71308519-9612de00-23f5-11ea-9d4f-e59615c0cb8b.png)

This can be a problem for the assembler always taking NOP r/m32 on the disassembled output and therefore lead to bytes mismatch on script injections.

//edit: Cleaned issue from missing NOP r/m16 part.

**Comment by cheat-engine** [comment]
should be better now

**Comment by Symbai** [comment]
Thank you
