### ISSUE TITLE
pointer scan result have duplicate results

### ISSUE THREAD

**Issue by frustreated** [cheat-engine/cheat-engine#1044]
![image](https://user-images.githubusercontent.com/5463104/71323475-918e1880-250e-11ea-8101-501cd3d22c9f.png)

**Comment by frustreated** [comment]
i scan the pointers 3 times
so the first time have no duplicate answers maybe , and once again whith some times, duplicates occured maybe.

**Comment by TheK0tYaRa** [comment]
It's a bug, reccomend adding it to title.

**Comment by cheat-engine** [comment]
Do you perhaps have another pointerwindow open with these results visible?
If a secondary ptr file can't be deleted because it's in use it will become part of the total pointerscan result set

**Comment by frustreated** [comment]
honestly not
i only add 2 pointers to the result ,and the picutre(above) says there are 3 duplicate answers

**Comment by frustreated** [comment]
honestly not
i only add 2 pointers to the result ,and the picutre(above) says there are 3 duplicate answers

**Comment by cheat-engine** [comment]
Is this the released build or a selfcompiled build?

**Comment by frustreated** [comment]
> Is this the released build or a selfcompiled build?

the newest self compiled build including the driver.
i signed it personaly with company signature.

**Comment by cheat-engine** [comment]
try the release version and see if it happens there as well (could be a recent bug so I know where to look)

**Comment by frustreated** [comment]
> try the release version and see if it happens there as well (could be a recent bug so I know where to look)

i replay again but did not reproduce the issue ,if time admits , i am going to reproduce again.
