### ISSUE TITLE
speedhack main2.pas byte hotkey 

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1047]
if reg.ValueExists('Binary Hotkey') then
            {$ifdef windows}
            reg.ReadBinaryData('Binary Hotkey',temphotkeylist[11][0],10);
            {$else}
            HexToBin(pchar(reg.ReadString('Binary Hotkey')),pchar(@temphotkeylist[11][0]),10);
            {$endif}

          if reg.ValueExists('Binary Hotkey') then
            {$ifdef windows}
            reg.ReadBinaryData('Binary Hotkey',temphotkeylist[12][0],10);
            {$else}
            HexToBin(pchar(reg.ReadString('Binary Hotkey')),pchar(@temphotkeylist[12][0]),10);
            {$endif}  

//////////////////////////////////////////////////////////////////

          if reg.ValueExists('Byte Hotkey') then
            {$ifdef windows}
            reg.ReadBinaryData('Byte Hotkey',temphotkeylist[12][0],10);
            {$else}
            HexToBin(pchar(reg.ReadString('Byte Hotkey')),pchar(@temphotkeylist[12][0]),10);
            {$endif}  

Byte hotkey is missing commit

**Comment by kitty8904** [comment]
reg.WriteBinaryData('Set Speedhack speed 5 Hotkey',frameHotkeyConfig.newhotkeys[8][0],10);

formsettings speed 5 missing commit

 reg.{$ifdef windows}WriteBinaryData{$else}WriteString{$endif}('Set Speedhack speed 5 Hotkey',{$ifndef windows}bintohexs({$endif}frameHotkeyConfig.newhotkeys[8][0],10){$ifndef windows}){$endif};

**Comment by cheat-engine** [comment]
should be fixed now

**Comment by frustreated** [comment]
so quickly！！！！！！！
