### ISSUE TITLE
custom listview detect chaged?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1057]
foundlist3 TlistView

Classname SysListView32

Detect 'SysListView32' in anti-cheat program

////////////////////////////////////////////////////////////
win32wscustomlistview.inc

class function TWin32WSCustomListView.CreateHandle(const AWinControl: TWinControl;

pClassName := 'SysListView32';  -> Changed 
pClassName := 'SysListView33

But

win32wscontrols. pp

FinishCreateWindow(AWinControl, Params, false);

procedure FinishCreateWindow(const AWinControl: TWinControl; var Params: TCreateWindowExParams;

 Window := CreateWindowExW(FlagsEx, PWideChar(WideString(pClassName)),
        PWideChar(UTF8ToUTF16(WindowTitle)), Flags,
        Left, Top, Width, Height, Parent, 0, HInstance, @NCCreateParams);     

DebugLn(['Failed to create win32 control, error: ', AErrorCode, ' : ', GetLastErrorText(AErrorCode)]); 

Failed to create win32 control -> error

Changing the class name in the Lazarus structure

Failed to create win32 control error

How to create a custom listview to change the class name

I ask because I don't know

Does anyone know?

**Comment by mgrinzPlayer** [comment]
I think such questions should be asked in CE forum, here: https://forum.cheatengine.org/viewforum.php?f=6

**Comment by kitty8904** [comment]
> I think such questions should be asked in CE forum, here: https://forum.cheatengine.org/viewforum.php?f=6

Can't rename Lazarus class?

I can't figure out why I get an error

There are no articles about Lazarus classes in the Cheat Engine forums.

**Comment by mgrinzPlayer** [comment]
Changing something like this would require recompiling whole FPC and Lazarus. Not an easy task.

So, you say this "anti-cheat program" detects any EXE file created with Lazarus, if there's TListView control placed in the form? Are you sure?

**Comment by kitty8904** [comment]
> Changing something like this would require recompiling whole FPC and Lazarus. Not an easy task.
> 
> So, you say this "anti-cheat program" detects any EXE file created with Lazarus, if there's TListView control placed in the form? Are you sure?

yes 

<img width="589" alt="xxx" src="https://user-images.githubusercontent.com/18622105/71546926-44aeb400-29de-11ea-814e-5e6558b0d97f.png">

syslistview32
msctls_progress32
sysheader32

Detects the reversing

1.While the window is at the top

2.Detect if there is a class in Lazarus that doesn't change

3.And a few more conditional statements

The bottom line is that changing the Lazarus class name bypasses detection.

**Comment by mgrinzPlayer** [comment]
Well, I think you will have to download FPC source, search&replace syslistview32 with syslistview69
compile FPC, download Lazarus source, search&replace syslistview32 with syslistview69, compile Lazarus with previously compiled FPC.

More or less.

**Comment by kitty8904** [comment]
Thank you for your reply

1. FPC compilation

2. Lazarus compilation

Isn't it possible without a redesign after all?

If so this is the problem

/////////////////////////////////

ex)
syslistview32-> syslistview42 all changed fpc or lazarus build

1. anticheat update syslistview42 detect  

2. syslistview42 ...-> all chaged fpc or lazarus build...

3. 1~2 loop

If it's impossible to design random class names

You have to repeat 1 ~ 2 infinitely

Another way is to change it to # 32770

Coding that can change classname is the best

Is Lazarus an impossible structure(fpc & lazarus rebuild)?

**Comment by mgrinzPlayer** [comment]
Just checked where I can find this "SysListView32". It is standard class name you pass to CreateWindowExW. So, you can not change it.

**Comment by kitty8904** [comment]
tlistview-> syslistview32 name impossible change?

If so, is there no answer other than custom listbox?

custom Tlistbox is in the BGRA package

There is no tlistview in the BGRA package

**Comment by mgrinzPlayer** [comment]
That anti-cheat doesn't detect SysListView32. Probably it detects other properties of foundlist3 object, like position, size, captions, header height and more...

**Comment by kitty8904** [comment]
I've changed the structure of position, size, captions, header height.

But detected

Fixed class names like SysListView32 can't be detected ?

Are properties of the SysListView32 class not detected?

<img width="212" alt="aqewrg" src="https://user-images.githubusercontent.com/18622105/71547719-0a95e000-29e7-11ea-91c9-cced3bd3a8ce.png">

**Comment by mgrinzPlayer** [comment]
Try this. Remove every TListView object from CE source, keep trying to compile CE project (you have to comment every compile error line). Then try this "castrated CE". If it still detected, you know...

**Comment by kitty8904** [comment]
If I remove tlistview it is not detected

The reason I thought was the classname

But you said classname is impossible

I'm thinking about the remaining detection vectors

I'm thinking about what can be detected more in the tlistview structure

**Comment by mgrinzPlayer** [comment]
Don't know. Rename classes which start with TLCL*****  with   TLOL*****.

**Comment by cheat-engine** [comment]
have you thought about changing the headers of the listview?

**Comment by kitty8904** [comment]
<img width="310" alt="qqw" src="https://user-images.githubusercontent.com/18622105/71548073-35cefe00-29ec-11ea-80c1-b54a82085426.png">

columns? -> fix -> detect

Unknown GUI detection

Another idea is

I suspect the class list array order

Suspected class inheritance(panel5->foundlist3->???)

**Comment by kitty8904** [comment]
<img width="580" alt="777" src="https://user-images.githubusercontent.com/18622105/71552032-afd8a480-2a37-11ea-931b-9312f9cc698f.png">

Memory reversing results class name detection is correct

Instead, it refers to all classes that do not change Lazarus.

Also check the list of loaded DLLs

Can't I change a fixed Lazarus class name?
