### ISSUE TITLE
is there any consideration to add x64 assembly language patched on the memory

### ISSUE THREAD

**Issue by frustreated** [cheat-engine/cheat-engine#1064]
because windbg is not going to add this feature for a long time ,and if there need to patch something on a x64 program, we have to add one compiled asm another and press the button a lot of times.
if there is a function like x86 windbg ,we just need to add asm sentences , all is over and well done.

**Comment by frustreated** [comment]
really need the x64 assembly Feature to assemble multisentences for binary code. because command of 'a' for windbg  can not used in x64 mod.
now people have to use CE to assemble multisentences one by one to patch the program.

**Comment by cheat-engine** [comment]
Do you mean the auto assembler ?  (ctrl+alt+a, or memview->tools->auto assembler)

**Comment by frustreated** [comment]
> Do you mean the auto assembler ? (ctrl+alt+a, or memview->tools->auto assembler)

sorry ，i wanna to say the function of this
![image](https://user-images.githubusercontent.com/5463104/72663668-13029900-3a30-11ea-8d34-1fa6fdb3c1f5.png)

**Comment by cheat-engine** [comment]
open the autoassembler window and type in this:
```
7ff637b71952:
int3
int3
mov eax,eax
mov eax,eax
```

and hit execute

**Comment by frustreated** [comment]
> open the autoassembler window and type in this:
> 
> ```
> chrome.exe+f1952:
> int3
> int3
> mov eax,eax
> mov eax,eax
> ```
> 
> and hit execute

OKOK
what a pity for my sily
