### ISSUE TITLE
Changing title/caption of all forms and controls

### ISSUE THREAD

**Issue by bugproof** [cheat-engine/cheat-engine#1068]
There's getFormCount() and getForm(i) but it works only for top forms, It's not possible to change e.g. button names using Lua. Correct me if I'm wrong.

![image](https://user-images.githubusercontent.com/3116731/71694782-7cd43f00-2db0-11ea-9e76-462438530c1e.png)

```lua
for i=0,getFormCount()-1 do
    local form = getForm(i)
    form.Caption='Bla'
end
```

e.g. "Check for updates when Cheat Engine starts." button can be easily detected because "Cheat Engine" is in the string.

**Comment by cheat-engine** [comment]
Buttons aren't windows but WinControls

try this

```lua
function renameComponents(c)
  local i
  if c.Component then
    for i=0,c.ComponentCount-1 do
      renameComponents(c.Component[i])
    end
  end

  if c.Caption then
    c.Caption='WTF'
  end
end


for i=0,getFormCount()-1 do
    local form = getForm(i)
    for j=0,form.ControlCount-1 do
      renameComponents(form)
    end

    form.Caption='Bla'
end

registerFormAddNotification(function(f)
  f.registerCreateCallback(function(frm)
    renameComponents(f)
  end)
end)
```

And perhaps add some onshow handlers as well to update objects named after create

**Comment by bugproof** [comment]
Thanks, I also figured out there's another way:

```
for j=0, form.getComponentCount()-1 do
  form.getComponent(j).Caption="ha"
end
```

**Comment by bugproof** [comment]
I've noticed it doesn't change everything. e.g. https://github.com/cheat-engine/cheat-engine/blob/acc6cefd0f18d9dd97040e6cc0a5339e9f056e2e/Cheat%20Engine/bin/autorun/versioncheck.lua#L140 remains unchanged... I'm trying to understand why
