### ISSUE TITLE
shall we change it better?

### ISSUE THREAD

**Issue by frustreated** [cheat-engine/cheat-engine#1069]
![image](https://user-images.githubusercontent.com/5463104/71730260-ab1f5080-2e7c-11ea-9792-29b1e8510334.png)

**Comment by cheat-engine** [comment]
Which window is this?

**Comment by frustreated** [comment]
> Which window is this?

in disassembly window ,press Ctrl+G

**Comment by cheat-engine** [comment]
should be better now
