### ISSUE TITLE
Cheat Engine color scheme doesn't respond to Windows 10 dark theme

### ISSUE THREAD

**Issue by overflow-byte** [cheat-engine/cheat-engine#1073]
Cheat engine's colors are suppose to respond to user's windows 10 color preferences however this is not the case currently.

**Comment by overflow-byte** [comment]
High contrast solution worked, thanks

**Comment by SinOfSins** [comment]
@overflow-byte i agree to your statement "Cheat engine's colors are suppose to respond to user's windows 10 color preferences however this is not the case currently." because currently in 2021 june, it still hasn't worked
