### ISSUE TITLE
scan for patch

### ISSUE THREAD

**Issue by frustreated** [cheat-engine/cheat-engine#1074]
look at the following picture, i think patch scan function only scan the memory in the scope of the length of execute memory.
after add some other bin codes to the end of the memory where were zeros, ce could not scan them.
![image](https://user-images.githubusercontent.com/5463104/71961312-0614c700-3232-11ea-9ca5-b500fe632b8f.png)

**Comment by Symbai** [comment]
CE only scans within executable code. This is by design, it makes no sense to show bytes that do nothing. Also appending bytes to the end of the file won't work because CE parses the PEB information and retrieve the original bytes from the file comparing it against what is in memory.

**Comment by frustreated** [comment]
OKOK， thanks for  your answer！！
