### ISSUE TITLE
il2cpp: Dump module

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#1077]
Is it possible to dump the module from memory on an il2cpp game now that has CE support for it? Speaking about the "Mono dissect" => images. Makes it easier (or possible at all) to use dnSpy on them.

**Comment by cheat-engine** [comment]
I doubt it as there is no raw metadata or IL code,  only assembler code and classes and types

**Comment by Symbai** [comment]
No, it would need to know the module start / end address and it needs to have a valid PE header at least. I thought it would still exist but not visible as module (i.e. loaded using manual map or something) but if that's not the case we're out of luck.
