### ISSUE TITLE
il2cpp - Failure to launch (possibly false detection)

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#1078]
Trying to enable mono features on Enter the Gungeon (W10 Game Pass) results in "Failure to launch" error. The game has an UnityPlayer.dll and "Enter The Gungeon.dll" (guess that's the GameAssembly.dll) and unity files but no il2cpp folder so it might be not using il2cpp at all or CE fails on something else. Injecting speedhack works fine so it's no an injection problem.

![image](https://user-images.githubusercontent.com/14368203/72095958-38492600-3311-11ea-8195-9dd05abdbab1.png)

**Comment by cheat-engine** [comment]
That's ok. "Failure to launch" is the actual result that it didn't find anything it recognized from the dll side.

**Comment by Symbai** [comment]
There is no mono or il2cpp export on this game. Maybe it shouldn't check for UnityPlayer.dll but just for GameAssembly.dll then? Or do you know about a case where it IS using il2cpp and no GameAssembly.dll exists?

**Comment by cheat-engine** [comment]
It always helps to check, it's no requirement that GameAssembly.dll has to have that name

**Comment by Symbai** [comment]
If it absolutely depends on mono / ilc2pp exports why not checking for them instead of module names? I think more people with ask question about such a generic error "Failure to launch" which could mean anything like failed to inject the dll.
