### ISSUE TITLE
MD5 mismatch on website and other websites

### ISSUE THREAD

**Issue by i-cant-git** [cheat-engine/cheat-engine#108]
| url | md5 | virustotal |
| --- | --- | --- |
| [github](https://github.com/cheat-engine/cheat-engine/releases/download/6.5.1/CheatEngine651.exe) | `BD28368392C836A4AF897707FB8AFA41` | [analysis](https://www.virustotal.com/file/cd0125b73b4a58f973087c9b385ec50e9e4ef4ceef4cb51eb8a7aa0a0459a8d7/analysis/1474149897/) |
| [presentfuncontent.com](http://www.presentfuncontent.com/TC9_LB_dWpjis+rPMog5xR9Z9Fp9pinTn7uUVROYtIN5V9nfw5i5rgWNRcH8EPgKCdY4AvNv5cF+bqwj20AbMXWc3eCrvqtwcEBtyo787xATJzT9s_mErX11qt56L54vte8Q39VQReLfO4S+U4tO1q6vsj4nQ+ZnN2DzOnWqHDvvKsLdK6F3kvCKvo5tRp7TKYGe2PZozZlI1jyOBdFD9d2Gwcdf+cT_LqWRixbErHnjUIo3UJNUCxiV3NiXnlzguWqchbi067YeOTLCoSuXeG77lV0+Bax1TVcbd5K55_EjiiK2zzH2kp5nNuK0QP1fHiMLduB+SoWIbuoT0AIOIqORx7bSA7jSBmYhTbcTfUNkEPgFa14=-G1YAAETdFpMbD38oYirC8TbBCTrlwKFFaWse4G_Hg4esqKrNHkQt6Uxira16EwVHFKuxPyZbLnsPAw5jD2pohhvyJw==-e) | `03923F0ACE1D97C8492A89B3D34E9120` | [analysis](https://www.virustotal.com/file/3998750545dff8c1165420d735ab31224950c6e1c708396e7a9697b58e180673/analysis/1474165036/) |
- `http://www.cheatengine.org/downloads.php` leads to website `presentfuncontent.com`
- The build from official website is suspicious, this build will allocate 5 gigabytes of your RAM capacity (16 GB in this case) if you enable speedhack for a process. This doesn't happen with the build from github.

**Comment by cheat-engine** [comment]
Both files are valid. They are the same, but the cheatengine.org one (the one the website links to and therefore has the MD5 given) has a cheatengine.org tag, and the github has a github.com tag.  That way the advertiser network can distinguish between where the download came from. (download portal (CE) or secondary download (github, chip, etc...)

as for the speedhack taking 5GB ram, are you sure you didn't do an unkown initial value scan before enabling it ? (It makes a copy of the game's memory inside CE) Symbol Loading could eat a bit as well if the game has .PDB files

Date: Sat, 17 Sep 2016 20:49:20 -0700

**Comment by i-cant-git** [comment]
It was a Firefox process and had 1.3 GB memory in task manager, that's all I know…
