### ISSUE TITLE
Deleted issue 1041?

### ISSUE THREAD

**Issue by SpaceRacet5w2A6l0I** [cheat-engine/cheat-engine#1080]
I just noticed that the repository owner deleted issue https://github.com/cheat-engine/cheat-engine/issues/1041... WHY?

Here is the content of the issue:

<details>
<summary>Click to expand</summary><br/>

The issue itself complains about official installer crashing starting from version 7.0, but was working before. Here are the issue comments:

Comment by: @cheat-engine

>i'munable to reproduce
>check your antivirus and anti-cheat drivers running on your system

Comment by: @frustreated

>recompile the newest cheatengine and driver ，signed and use kernel model， but cannot enter in debug mode

Comment by: @TheK0tYaRa

>Looks like some breakpoint occured, it may be anticheat software or antivirus.

Comment by: @patheticcockroach

> Same here, installer for version 7.0 crashes on Win 10 x64. The crash seems to occur right after I block an outgoing connection attempt.

Comment by: @cheat-engine

>Try allowing the outgoing connection attempt and see how that goes

Comment by: @SpaceRacet5w2A6l0I

>Same for me. All previous installers before 7.0 work, but 7.0 does not work. And yes I have blocked outgoing connections in my firewall for all programs by default and I don't want to change it. Why the new installer requires internet connection?
>
>@cheat-engine Did you add usage reporting or anonymous data sharing in the new installer? I don't really see any other reason why would cheat engine new installer require internet connection and crashes if firewall blocks it... If that is true (sharing anonymous usage info), then it can be considered as endangered user privacy and license violation, since it don't say anything about it in the license agreement.
>
>Can you please remove whatever you added in 7.0 and allow users to install and run cheat engine even if firewall blocks outgoing connections?

</details>

My understanding is that the last comment I posted on the deleted issue is correct and that the owner @cheat-engine is afraid of legal issue they may experience due to malware/spyware/payload/keyloger or whatevr they injected into the new binary and now they are trying to hide it from being known publicly.

@cheat-engine Can you please be so kind to explain why the issue is deleted and why exactly does the installer require the internet connection and what addresses is it trying to access? Thanks.

**Comment by patheticcockroach** [comment]
I've installed lots of bundleware in the past. Even if they complain more or less loudly about being deprived of an Internet connection, _none_ of them ever refused to install (or crashed their installer) when ran offline.

Considering EAC is software that by nature triggers antiviruses, and as a consequence has the privilege of being considered a false negative and given a free AV pass, requiring in addition a free firewall pass is... most inappropriate at best. And hiding the issue in addition to dismissing it really takes the cake

**Comment by cheat-engine** [comment]
I did not delete it, I can't even delete issues even if I wanted to . 
![image](https://user-images.githubusercontent.com/12006555/72155276-0be5e600-33b3-11ea-8621-4ace0fdf5fb0.png)
at most I can edit, but still no delete.

Anyhow, the name of the person posting the initial issue was is "jsdhbtv8548rf" and according to https://github.com/jsdhbtv8548rf that account doesn't exist anymore, so I guess that deleting your account also deletes the issues you've created

As for your question, the installer downloads a script that shows an installer page during installation, likely something goes wrong there

**Comment by metroid112** [comment]
https://help.github.com/en/github/managing-your-work-on-github/deleting-an-issue

Deleting an issue is possible, but Github shows the issue was deleted if one tried to access its URL, so he didn't.

**Comment by SpaceRacet5w2A6l0I** [comment]
> deleting your account also deletes the issues you've created

Deleted users become @ghost and their issues and PRs remain visible, see [#1832 (comment)](https://github.com/nodejs/help/issues/1832#issuecomment-507669762)

But if the installer is only downloading installer page, I guess it is safe then. Sorry for the inconvenience. Assuming good intentions.
