### ISSUE TITLE
Assembly scan is not comparing end of assembly string

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#1082]
Consider this string as scan for assembly code:

`*word ptr [*+1C]`

My assumption is that it shows me results that start with `anything`, contains `word ptr [`, follows by `anything` and ends with `+1C]`

But I got many results like this one that ends with more than my assembly string and I didn't put a wildcard char at the end.

`mov qword ptr [rbx+1C],00000000`

In case you might say it's intended although I believe its a bug, how can I mark the end of the assembly string so it won't match with anything further then?

**Comment by mgrinzPlayer** [comment]
Assembly scan in CE (version up to 7.0) does regular expression on whole disassembled line.
(* are not needed at the beginning of line)

Line is constructed this way:
```Pascal
    result:=inttohex(LastDisassembleData.address,8)+' - '+getLastBytestring;
    result:=result+' - ';
    result:=result+LastDisassembleData.prefix+LastDisassembleData.opcode;
    result:=result+' ';
    result:=result+LastDisassembleData.parameters;

   //inside other unit:
    result:=result+'  ';   // add two space chars
```
Unfortunately search text is "RegEx Escaped". So we can not use \s or other character classes.
Only simple "*" (which is replaced with ".*")

So if you want to find something which ends with "word ptr [*+1C]" you will have to use this text:
`word ptr [*+1C]{twospacecharhere}`

**Comment by Symbai** [comment]
Ah okay I didn't know this. You say up to 7.0, I'm using 7.1 is there anything different on that one regarding this?

**Comment by mgrinzPlayer** [comment]
Recent commit:
https://github.com/cheat-engine/cheat-engine/pull/1038/files (and issue https://github.com/cheat-engine/cheat-engine/issues/1033)

Previously it was **d** string (whole disassembled line) with added two spaces).
Now it will try to match on opcode string:
```Pascal
opcode: string;
...
splitDisassembledString(d,true,ignore,ignore,opcode,ignore);
...
ok:=regexpressions[i].Exec(opcode);
```

Opcode is constructed this way:
```Pascal
    result:=result+LastDisassembleData.prefix+LastDisassembleData.opcode;
    result:=result+' ';
    result:=result+LastDisassembleData.parameters;
```

it can be fixed. We can add a checkbox "must match with end"

**Comment by Symbai** [comment]
Such a checkbox would be appreciate. And while we are at it may also a "must match with start"?

**Comment by mgrinzPlayer** [comment]
RegExpr unit used in Lazarus is this one: [Regexpr by Sorokin](https://regex.sorokin.engineer/en/latest/index.html)

It is a subset of Perl's regular expressions:
https://regex.sorokin.engineer/en/latest/regular_expressions.html

Start and end of line in are: ^ and $. Don't know.
Maybe we do not have to escape them. Opcode string probably doesn't have those chars.

We can change this [line](https://github.com/supMarco/cheat-engine/blob/c300fc84963465319c55caf7fbe6925a810f8baa/Cheat%20Engine/frmDisassemblyscanunit.pas#L276):
```
stringstofind[i]:=StringReplace(EscapeStringForRegEx(stringstofind[i]), '\*','.*',[rfReplaceAll]);
```
to this:
```
//escape
stringstofind[i]:=EscapeStringForRegEx(stringstofind[i]);

// change * to .*
stringstofind[i]:=StringReplace(stringstofind[i], '\*','.*',[rfReplaceAll]);
// restore start line
stringstofind[i]:=StringReplace(stringstofind[i], '\^','^',[rfReplaceAll]);
// restore end line
stringstofind[i]:=StringReplace(stringstofind[i], '\$','$',[rfReplaceAll]);

```

**Comment by Symbai** [comment]
Sounds like a good idea to me. Do you want to create a pull request for this one?

**Comment by mgrinzPlayer** [comment]
What you think about this one:
![obraz](https://user-images.githubusercontent.com/9157726/72275071-84f07200-362d-11ea-838e-4f5be7a2c605.png)

**Comment by Symbai** [comment]
This one might even better so we don't have to remember how its written. I only discovered it has wildcard support when I tried it out. If you haven't looked into the source code you probably wouldn't know either so this text might be much more helpful.

**Comment by mgrinzPlayer** [comment]
For now "Assembly scan" only supports * wildcard.
I want to add "?",  "^" and "$" support.


With this:
```
      stringstofind[i]:=StringReplace(EscapeStringForRegEx(stringstofind[i]), '\*','.*',[rfReplaceAll]);
```
changed to:
```
      s:=EscapeStringForRegEx(stringstofind[i]);
      s:=StringReplace(s, '\*','.*',[rfReplaceAll]); //zero or more chars
      s:=StringReplace(s, '\^','^',[rfReplaceAll]);  //start of line
      s:=StringReplace(s, '\$','$',[rfReplaceAll]);  //end of line
      s:=StringReplace(s, '\?','.',[rfReplaceAll]);  //exactly one char
      stringstofind[i]:=s;
```

**Comment by Symbai** [comment]
Maybe a checkbox to switch between your implementation and a full regex too? I remember some situations where I searched for an assembly string doing anything with a specific offset like `F0`. But writing `*F0*` causes a lot of unwanted results with offsets like `3F0`. With full regex I could define that the character before and after `F0` can be anything but NOT number / alphabetical.

I would want this to be optional because in most of the cases you don't need and don't want to a full regex yourself. But in situations where you would want to, you currently cannot. And because it's using regex itself in code it could just take the string as a full regex.

**Comment by mgrinzPlayer** [comment]
Sent PR #1086
