### ISSUE TITLE
Il2cpp - CE freezes (Fails to enumerate classes)

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#1095]
Other il2cpp games I've tried works fine but Computer Tycoon on steam CE fails to enumerate the classes of the first assembly. 

```
function mono_image_enumClasses(image)
  --if debug_canBreak() then return nil end

  monopipe.lock()
  monopipe.writeByte(MONOCMD_ENUMCLASSESINIMAGE)
  monopipe.writeQword(image)
  local classcount=monopipe.readDword() -- <---------------------  Classcount == nil  
  if (classcount==nil) or (classcount==0) then return nil end
```

And there is a bug with that because it does not release the monopipe lock which results in CE freezes forever.

The important question is however, why does the enumeration fails? Even when I change the lua script to ignore the first assembly, it fails again the second. Also third, fourth etc.

**Comment by cheat-engine** [comment]
mostly il2cpp games have no anti debug so you can attach visual studio to the process  and then break at the enumClasses function and see why it fails

**Comment by Symbai** [comment]
Game does not have an il2cpp_image_get_class_count export 😮 That sucks.... I guess there is no workaround? Wonder if this is something developers can easily switch on or if this is caused by some kind of obfuscation / protection.

Because if this easily switchable we will run into this more often.

**Comment by cheat-engine** [comment]
does it still have il2cpp_image_get_class? 
if so you could try brutegorcing till it fails

perhaps there is a similar export you can use. Check enum symbols in ce and search for il2cpp_

as for figuring out the parameters look at the assembler code

**Comment by Symbai** [comment]
No it does not, only these:

```
il2cpp_image_get_assembly
il2cpp_image_get_entry_point
il2cpp_image_get_filename
il2cpp_image_get_name
```

Btw. where do you find all the infos about the exports? When I google for il2cpp_image_get_class_count I find nothing. Is there a documentation somewhere?

**Comment by cheat-engine** [comment]
often they have the same parsmeters as the mono_ versions, but other times you just have to guess by the name snd the parameters the functions use

**Comment by Symbai** [comment]
Ah okay, i thought it might be documented or source is on github (I believe mono is)

**Comment by cheat-engine** [comment]
try the current monoscript.lua

**Comment by Symbai** [comment]
Good news, we're back:
![image](https://user-images.githubusercontent.com/14368203/72672426-bf08ac00-3a51-11ea-87e8-49efad449024.png)

Bad news, some symbol address seems to be wrong. It brings me to different places. Even those who usually are expected to be "valid" (i.e. these Class:Update methods) jits to something completely different. But I cannot say if this is a bug or just the way it works as I cannot compare it with a working enumeration.

CTGPUClass:get_BaseClock => CTComputerclass:get_DiscountRich
DemoGUI:Update => EmptyInternalEnumerator´1.System.Collection.IEnumerator.Reset

Maybe some JIT address symbols overwrites another...
