### ISSUE TITLE
luapipe.pas(227,41) Error: Identifier not found "ifthen"

### ISSUE THREAD

**Issue by frustreated** [cheat-engine/cheat-engine#1099]
have you encountered this message?
![image](https://user-images.githubusercontent.com/5463104/72673423-43d0e580-3aa5-11ea-87c0-37a16fff35a0.png)
![image](https://user-images.githubusercontent.com/5463104/72673427-4fbca780-3aa5-11ea-86c4-5b202b0bbb84.png)

**Comment by Symbai** [comment]
https://github.com/cheat-engine/cheat-engine/issues/1087#issuecomment-574633406

**Comment by frustreated** [comment]
> [#1087 (comment)](https://github.com/cheat-engine/cheat-engine/issues/1087#issuecomment-574633406)

so special thanks for your reply
