### ISSUE TITLE
CE is missing some string references

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#1105]
Considering the progress takes long anyway CE should look a bit closer/deeper for string references as it's missing string references x64dbg for example finds. Accuracy is more important than speed as we search probably only once per session for references, if at all.

#### CE:
![image](https://user-images.githubusercontent.com/14368203/72851773-7563cf80-3ca4-11ea-87a9-4ff814a1f8e0.png)
![image](https://user-images.githubusercontent.com/14368203/72851791-87de0900-3ca4-11ea-89e0-ff6ee04574d1.png)
![ezgif-3-076792352b10](https://user-images.githubusercontent.com/14368203/72852140-a2fd4880-3ca5-11ea-80e1-6e2eb26b6ed9.gif)

#### x64dbg:
![image](https://user-images.githubusercontent.com/14368203/72851787-83195500-3ca4-11ea-9e13-4a43e4c2141d.png)
![image](https://user-images.githubusercontent.com/14368203/72851927-df7c7480-3ca4-11ea-83f4-506d107de387.png)

**Comment by cheat-engine** [comment]
is the address that x64dbg found in the range you specified dissect code to scan?

**Comment by Symbai** [comment]
Yes `mov rcx,[Frostpunk.exe+2A2E518]` (first screenshot in both cases) points to: `7FF769B60BC0` which is inside the same module
![image](https://user-images.githubusercontent.com/14368203/72853659-f96c8600-3ca9-11ea-8eb5-2ab1f6065224.png)

CE only needs to see if Frostpunk.exe+2A2E518 => string, which it does already. If not then check if the address it points to contains a string instead, which it currently does not.

Which line does your second question relate to?

**Comment by cheat-engine** [comment]
ah ok, i thought it missed it because of disassembler misalignment due to picking a wrong start

**Comment by cheat-engine** [comment]
should find it now
