### ISSUE TITLE
Kernel mode debugger is not available

### ISSUE THREAD

**Issue by Cardroid** [cheat-engine/cheat-engine#1109]
## Current Status
![image](https://user-images.githubusercontent.com/25889754/72957803-4ce4ee00-3de8-11ea-95e6-9d316891d27e.png)
![image](https://user-images.githubusercontent.com/25889754/72957841-64bc7200-3de8-11ea-80ff-fd1043dde0d0.png)

#### Why isn't it active?

**Comment by cheat-engine** [comment]
Is this the 64 bit version of ce?
did you restart your system after clicking make possible?

**Comment by Cardroid** [comment]
yes

**Comment by Cardroid** [comment]
Both 32-bit and 64-bit versions do not work

**Comment by cheat-engine** [comment]
try restarting again using start->power->restart  (Make sure you DO NOT click shutdown, actually restart)

**Comment by Cardroid** [comment]
### yes! you did it, thanks
