### ISSUE TITLE
some ideas for the "scan type" dropdown

### ISSUE THREAD

**Issue by LastExceed** [cheat-engine/cheat-engine#111]
1: The dropdown of scan type feels kinda long and messy, and I had some ideas for how to clean it up: 
1a: now that scan type NOT is an official part of CE, why not remove the scan option "unchanged" and add NOT to "changed" instead?
1b: i'd remove "increased by" from the dropdown and add it as checkbox to "increased" right below the NOT checkbox instead, same for "decreased by"
1c: having the "compare to first scan" setting in that dropdown always confused me because its not directly a scan type. I'd use a checkbox instead.
I know that this would result in lots of checkboxes in that area when float or double is selected but I feel like it would be better that way.

2: and now that we have some room for new scan types
2a: whenever i do fuzzy search (increased/decreased/changed/unchanged) I often get frustrated because as soon as i get distracted for a few seconds i forgot what my last scan was (whether i have to do changed or unchanged next and whatnot) so I have to start all over. maybe a new scan type "whatever" (or just a button) that simply updates the comparison values of all addresses.
EDIT: I just realized that this doesn't actually require scanning and therefore doesn't belong into the scan type dropdown. so maybe just a button instead

**Comment by cheat-engine** [comment]
increased by/decreased by not sure, but the rest is done. (I moved the hidden forgot value scan to an actual scantype now)
