### ISSUE TITLE
kernel memory safe read search?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1120]
https://www.unknowncheats.me/forum/anti-cheat-bypass/314342-read-unknown-kernel-address-safe.html

I asked a long time ago

I want to do a kernel memory search

but BSOD occurs when reading unknown kernel memory

MmCopyVirtualMemory seems to be valid only in user mode

I want to implement a secure memory lookup of the kernel in queryvirtualmemory

FFFFF80000000000~FFFFFF0000000000 safe search possible?

Blue screen does not occur in Windows 7

It occurs in Windows 8 ~ Windows 10

////////////////////

MmCopyMemory MmCopyVirtualMemory Is it different?

Is MmCopyMemory safe for kernel searching?

**Comment by cheat-engine** [comment]
check out https://github.com/cheat-engine/cheat-engine/blob/master/DBKKernel/noexceptions.c

**Comment by kitty8904** [comment]
NTSTATUS NTAPI MmCopyVirtualMemory
(
	PEPROCESS SourceProcess,
	PVOID SourceAddress,
	PEPROCESS TargetProcess,
	PVOID TargetAddress,
	SIZE_T BufferSize,
	KPROCESSOR_MODE PreviousMode,
	PSIZE_T ReturnSize
);


BOOLEAN ReadProcessMemory(DWORD PID, PEPROCESS PEProcess, PVOID Address, DWORD Size, PVOID Buffer)
{
	PEPROCESS selectedprocess = PEProcess;
	//KAPC_STATE apc_state;
	NTSTATUS ntStatus = STATUS_UNSUCCESSFUL;

	PEPROCESS TargetProcess = PsGetCurrentProcess();

	SIZE_T Result = 0;


	if (PEProcess == NULL)
	{
		if (!NT_SUCCESS(PsLookupProcessByProcessId((PVOID)(UINT_PTR)PID, &selectedprocess)))
			return FALSE; //couldn't get the PID

	}

	//selectedprocess now holds a valid peprocess value
	__try
	{
		KeAttachProcess((PEPROCESS)selectedprocess);



		__try
		{
			char* target = NULL;
			char* source = NULL;
			//DWORD TempSize = Size;
			int i = 0;


			if ((IsAddressSafe((UINT_PTR)Address)) && (IsAddressSafe((UINT_PTR)Address + Size - 1)))
			{



				target = Buffer;
				source = Address;

				if (loadedbydbvm) //add a extra security around it
				{
					disableInterrupts();
					vmx_disable_dataPageFaults();
				}


				if ((loadedbydbvm) || ((UINT_PTR)source < 0x8000000000000000ULL)) //original
				
				//if (((UINT_PTR)source < 0x8000000000000000ULL) && (!loadedbydbvm)) //fix
				{
					
					
					//DbgPrint("target::%llx",target);
					//DbgPrint("source::%llx",source);
					//DbgPrint("source2::%llx",&source);
					if (NT_SUCCESS(MmCopyVirtualMemory(selectedprocess, source, TargetProcess, target, Size, KernelMode, &Result)))
					{
						ntStatus = STATUS_SUCCESS;
					}
					else
					{
						ntStatus = STATUS_UNSUCCESSFUL;
					}

				}
				else
				{
					//PEPROCESS TargetProcess;
					//SIZE_T Result;
					//TargetProcess = PsGetCurrentProcess();
					//MmCopyVirtualMemory(selectedprocess, source, TargetProcess, target, Size, KernelMode, &Result);
					//ntStatus = STATUS_SUCCESS;
					
					i = NoExceptions_CopyMemory(target, source, Size);
					if (i != (int)Size)
					{
						ntStatus = STATUS_UNSUCCESSFUL;
					}
					else
					{
						ntStatus = STATUS_SUCCESS;
					}
					
				}



				if (loadedbydbvm)
				{
					UINT_PTR lastError;
					lastError = vmx_getLastSkippedPageFault();
					vmx_enable_dataPageFaults();

					enableInterrupts();

					//DbgPrint("lastError=%p\n", lastError);
					if (lastError)
						ntStatus = STATUS_UNSUCCESSFUL;
				}


			}

		}
		__finally
		{

			KeDetachProcess();
		}
	}
	__except (1)
	{
		//DbgPrint("Error while reading: ReadProcessMemory(%x,%p, %p, %d, %p\n", PID, PEProcess, Address, Size, Buffer);

		ntStatus = STATUS_UNSUCCESSFUL;
	}

	if (PEProcess == NULL) //no valid peprocess was given so I made a reference, so lets also dereference
		ObDereferenceObject(selectedprocess);

	return NT_SUCCESS(ntStatus);
}

MmCopyVirtualMemory -> kernel search bsod


NoExceptions_CopyMemory -> ?? 

Not enough for kernel searching

I don't know how to fix

sorry,db
