### ISSUE TITLE
usemono() error: Handler failing to initialize

### ISSUE THREAD

**Issue by RyanB2112** [cheat-engine/cheat-engine#1123]
I'm not the most savvy of coders, but I've been trying to figure out why a table released in May 2019 would have stopped working by the time I pulled it off of FearLess today. When checking why the scripts won't activate, it gave me the following error:

<<Error in Line 3(usemono()):The mono handler failed to initialize>>

Using CheatEngine 7.0 release, and I've tried restarting everything, doing a clean install of CheatEngine, and using an alternate .dll recommended in issue #1036 .

**Comment by cheat-engine** [comment]
Are you attached to the correct process?
After attaching, do you see a menu item at top called "mono"  ?

**Comment by RyanB2112** [comment]
Definitely attaching to the right process, but no "mono" option up top.

**Comment by cheat-engine** [comment]
that means that it switched from mono to a different runtime.  Perhaps il2cpp (works on git) or microsoft .net

Try getting an older version of the game, or request a new table

**Comment by RyanB2112** [comment]
There have been no version changes since before the table was reported no
longer working.

I think the problem may be it's a game I'm playing through the Windows
GamePass. Some checking around, and it seems there have been similar issues
from other games after one particular Windows Update went through.

**Comment by cheat-engine** [comment]
ah, you got the windows app version instead of the steam version, those are very different versions.
windows app can't use mono

**Comment by RyanB2112** [comment]
Good to know. Thanks for clarifying!
