### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1126]
r:=WaitForSingleObject(o^.hEvent, ifthen<DWORD>(ftimeout=0, 1000, ftimeout));

luapipe.pas(227,41) Error: Identifier not found "ifthen"
luapipe.pas(227,65) Fatal: Syntax error, ")" expected but "," found

lazarus 2.0.6
fpc 3.0.4

**Comment by mgrinzPlayer** [comment]
use FPC3.2.0

or

change line 68 to this:
`uses LuaObject, LuaByteTable, math;`

and line 227 to this
`r:=WaitForSingleObject(o^.hEvent, ifthen(ftimeout=0, 1000, ftimeout));`

**Comment by wangyujie96** [comment]
> use FPC3.2.0
> 
> or
> 
> change line 68 to this:
> `uses LuaObject, LuaByteTable, math;`
> 
> and line 227 to this
> `r:=WaitForSingleObject(o^.hEvent, ifthen(ftimeout=0, 1000, ftimeout));`

where can i download FPC3.2.0 ? i cant find one

**Comment by mgrinzPlayer** [comment]
https://github.com/cheat-engine/cheat-engine/issues/822#issuecomment-535610613
