### ISSUE TITLE
How to use kernelmode debugger

### ISSUE THREAD

**Issue by HeIp** [cheat-engine/cheat-engine#1131]
Hello, How do get kernelmode debugger to work ?
How would I compile my own dbk64.sys?
I heard you have to make your own dbk64 to get it to work.

**Comment by cheat-engine** [comment]
make sure you have an intel cpu
then make kernelmode debugging possible and use it (don't forget to restart after enabling it) 

this won't work if you have edited your CE

**Comment by HeIp** [comment]
Have amd cpu, system supports DBVM though. Would it work?

**Comment by cheat-engine** [comment]
on widnows 7 on an older ce build yes, windows 10 is a bit more problematic at the moment

**Comment by HeIp** [comment]
On Windows 10, newest CE version. Not an option then ?
