### ISSUE TITLE
Mono Jitter goes crazy

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#1136]
Honestly, no idea how to title this bug. Jitting a method via mono dissect works fine but accessing the method anywhere does not. Makes absolutely no sense to me. Game: Escape The Pacific (Steam).
Happens on some methods and on others it works but it's reproducable.

![ezgif com-optimize](https://user-images.githubusercontent.com/14368203/74538160-82867e00-4f33-11ea-8a18-c4bd714d8224.gif)

**Comment by cheat-engine** [comment]
what is the full classname according to the mono dissect window ?

**Comment by Symbai** [comment]
namespace = empty
Classname = Inventory
Methodname= CalculateShowItemsWeight

![image](https://user-images.githubusercontent.com/14368203/74573823-a53b8580-4f79-11ea-9f73-25cc97d0b8f5.png)

![image](https://user-images.githubusercontent.com/14368203/74573845-b71d2880-4f79-11ea-9d54-54e6325b43e4.png)

**Comment by cheat-engine** [comment]
How many Inventory classes are there ?

and try running this code (after being attached with mono)
```lua
count=0
a=mono_enumImages(function(img)
  cl=mono_image_enumClasses(img)

  local i=1
  for i=1,#cl do
    if cl[i].classname=='Inventory' then
      count=count+1
      if count>=2 then
        print("Error: Same classname multiple times")
      end
    end
  end
end)

if count==1 then
  print("ok")
else
  print("Error: not found")
end
```

**Comment by Symbai** [comment]
```
Error: Same classname multiple times 
Error: not found 
```

Must be a bug?
![image](https://user-images.githubusercontent.com/14368203/74574396-8211d580-4f7b-11ea-891c-504b101e374b.png)

**Comment by cheat-engine** [comment]
then try:
```lua
count=0
a=mono_enumImages(function(img)
  cl=mono_image_enumClasses(img)

  local name=mono_image_get_name(img)

  local i=1
  for i=1,#cl do
    if cl[i].classname=='Actor' then
      print("Found one in the image :"..name)
      count=count+1
    end
  end
end)


if count==0 then
  print("Error: not found")
elseif count==1 then
  print("ok")
else
  print("Found too many")
end
```

likely you have another image with the same classname

**Comment by Symbai** [comment]
```
Found one in the image :Assembly-UnityScript 
Found one in the image :Assembly-CSharp 
```
Yup, that's the reason. But this still can be improved the way that when CE is not possible finding a method in one class, search for another class and use this. Not super urgent however...
