### ISSUE TITLE
dear master，really want o know how to solve this problem.

### ISSUE THREAD

**Issue by frustreated** [cheat-engine/cheat-engine#1138]
ptrace attach failed (pid=2932). This system might not be properly rooted
[vdso]
ptrace attach failed (pid=2932). This system might not be properly rooted
/lib/i386-linux-gnu/ld-2.27.so
ptrace attach failed (pid=2932). This system might not be properly rooted
/lib/i386-linux-gnu/ld-2.27.so
ptrace attach failed (pid=2932). This system might not be properly rooted

in Ubuntu 16, I opened CE server as root user.'
But no memory can be displayed. 
picture as follows:

![捕获](https://user-images.githubusercontent.com/5463104/74639969-c1256e00-51a9-11ea-8219-a635ae5709eb.PNG)

**Comment by cheat-engine** [comment]
set selinux to permisive

**Comment by frustreated** [comment]
> set selinux to permisive

still cannot got it .changed scanmem without gui.
thanks a lot

**Comment by suqiernb** [comment]
![1](https://user-images.githubusercontent.com/49021696/142432314-3fc28494-9136-41d8-aea2-52d2889cf73f.jpg)

![2](https://user-images.githubusercontent.com/49021696/142432325-e23f675e-860c-469c-be23-d68a293f4f28.jpg)

**Comment by cheat-engine** [comment]
you did launch ceserver with su/sudo as well?

If so, then not sure.  What linux kernel version is it running? And have you tried a different one?
