### ISSUE TITLE
No start on windows 10

### ISSUE THREAD

**Issue by Marty42780** [cheat-engine/cheat-engine#1151]
Cheat engine don't start when I start it with admin ?

**Comment by cheat-engine** [comment]
uninstall badlion and restart your computer (not shut down and back on, actual restart)

**Comment by uzervlad** [comment]
how is badlion related to cheat engine?

**Comment by cheat-engine** [comment]
Badlion infects your computer so that even when it's not running it can see everything you execute and decide for you if you should be allowed to execute it or not. 

Cheat Engine is one of those it doesn't want you to tun
