### ISSUE TITLE
Memory Viewer - Changing opcode turns BYTE ptr into DWORD ptr

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#1153]
Using 7.1 Beta, notice the first byte gets changed turning BYTE ptr into DWORD ptr for no reason:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/14368203/76657442-d0f65f00-6569-11ea-9445-763e95184394.gif)

**Comment by cheat-engine** [comment]
already fixed in rc1

**Comment by kusalux** [comment]
Is that the same source for the bug as mine? (memory viewer problem with bytes)

![cebug-lb](https://user-images.githubusercontent.com/9304166/76808389-f42e4200-67e7-11ea-883b-17d83dc91b05.png)
[CE_BUG_LB.zip](https://github.com/cheat-engine/cheat-engine/files/4340837/CE_BUG_LB.zip)

**Comment by cheat-engine** [comment]
I don't see the bug so I doubt it
#255 gets converted to FF 
FF is -1 in a signed operation

**Comment by kusalux** [comment]
So that's intended? Why is 1-byte signed dec then, while the rest is hex?

**Comment by cheat-engine** [comment]
if it's not signed it's FF, if it is sign extended, the most significant byte determines if it's going to be a negative value or not
By adding 0's you can steer it

e.g look at 
`cmp dx,a8`
it will be assembled as `66 83 FA A8           - cmp dx,-58`
which is the equivalent as `cmp dx,ffa8`

but if you do
`cmp dx,00a8`
it will be assembled as 
`66 81 FA A800         - cmp dx,00A8`

So if you need the non-signed version, use the second notation

**Comment by kusalux** [comment]
That does work with word+ only. Not with 1bytes.  I guess you could take a look at the bytes too, not only opcodes. But if there would be a way to force 1byte hex - would be nice too.
