### ISSUE TITLE
speed hack ept hook kernel32 error?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1154]
1. First DBVM Target API Address EPT HOOK ON
kernel32.GetTickCount
kernel32.GetTickCount64
ntdll.RtlQueryPerformanceCounter

2.SPEED HACK Button Click (Hook Memory)

3.But all process crash exit

kernel32.dll memory ept hook -> all process chaged?

Does changing EPT HOOK in kernel32.dll part affect all processes?

Bypassing API address to EPT, hooking attempt-> seems to be affected by all processes

Is this fixed?

no dbvm speed hack 

dll injection speed hack -> hooking memory detect ( no dll file detect)

///////////////// ///////////////// /////////////////

kernel32.dll memory -> EPT HOOKING -> memory fix -> all process memory changed?

Is there a command or method to modify EPT only for target process kernel32.dll?

**Comment by cheat-engine** [comment]
you must trigger a copy on write in the target process fuesr

**Comment by kitty8904** [comment]
> you must trigger a copy on write in the target process first (e.g write the same bytes)

1.tar get process go to address kernel32.GetTickCount - EB 05                 - jmp kernel32.GetTickCount+7 { ->->KERNELBASE.GetTickCount }
2.memory viewer dbvm active clock (you e.g write the same bytes?)

3.cheat engine speed hack button on ->  hooking address jmp 287F000

4. but no target process crash & die

In my opinion, isn't another process referring to the address of the jump location?

kernel32.dll is shared memory, so maybe?

**Comment by cheat-engine** [comment]
no, dbvm watch and cloak do not initiate a COW

You must first write bytes to the memory to cause windows to trigger a COW and then you can do a cloak on the new physical address

**Comment by kitty8904** [comment]
I don't understand

Any examples?

I don't understand why other processes are affected when modifying the memory of kernel32.dll

I'm curious why modifying kernel32.dll in dbvm_active clock state causes an error in another process

**Comment by cheat-engine** [comment]
To save memory when a module is loaded in a process, and another process also has that module loaded windows will give it the same physical address as that other process.
In the case of kernel32 and ntll that means all processes will have the same physical memory

To prevent 'issues' when a process writes to this memory a pagefault happens (as internally it's still read only in the pate table entry) and then windows will copy the memory to a new physical address and change the pagetable entry to point to that address instead.

When using cloaked memory CE will not trigger a COW when writing, as the writes go to the physical memory directly bypassing the page protection.
This is similar as using dbk_writesIgnoreWriteProtection() and use kernelmode writes to change memory

Easiest way to trigger a COW is use the disassembler in CE, go to the address and press enter twice (first one to bring up the assembler, second one to write the new instruction unchanged)

**Comment by kitty8904** [comment]
thank you db!

my test assembler enter -> no fix instruct enter -> ept active -> fix -> no error

I understood the explanation, but from disassembler to enter

I don't understand

What behavior fixed the problem?(source ?)

https://youtu.be/VbGc19Q1uTk

**Comment by cheat-engine** [comment]
If you showed the address of gettickcount in the hexview at the bottom, you'd have seen that after assembling the physical address would have changed.
And that physical address is then private to that one process only

**Comment by kitty8904** [comment]
oh, hexview -> physical memory changed ok

what the source code?

How does the physical memory change?

I wonder

**Comment by cheat-engine** [comment]
it happens inside windows

as I mentioned windows sets the pagetable entry describing the virtual address to read only
when something tries to write to the virtual address a pagefault interrupt is triggered
The pagefault interrupt in windows then sees that the page is marked as a copy-on-write page, it will then allocate a new 4KB block, copy the contents of the memory to that new block, change the pointer of the virtual address to that new physical address and continue

**Comment by kitty8904** [comment]
Thank you for studying new information today

It was very helpful
