### ISSUE TITLE
DBVM lags system when using igpu

### ISSUE THREAD

**Issue by HiImNewb** [cheat-engine/cheat-engine#1156]
I have a i7 6700k that has a igpu that I use for my second monitor and a gtx 1080 but when I enable dbvm my pc lags alot. Is their anyway I can stop this from happening?

**Comment by cheat-engine** [comment]
try lua command `dbvm_setTSCAdjust(false,0)`
it will disable the anti detect code of dbvm based on rdtsc

**Comment by HiImNewb** [comment]
That fixed it thank you!
