### ISSUE TITLE
can't install without 3rd party apps

### ISSUE THREAD

**Issue by dstN** [cheat-engine/cheat-engine#1157]
why does the installer for 6.8.1 doesn't let me install the programm WITHOUT a 3rd party app?...

i can't uncheck anything...
![image](https://user-images.githubusercontent.com/960879/76870287-cbe72780-6869-11ea-9f75-cdf99148f81e.png)

**Comment by cheat-engine** [comment]
disconnect from the internet when you install 6.8.1 it doesn't support the new decline/accept buttons

**Comment by dstN** [comment]
sadly i need to use 6.8.1. It's recommended from a Table-Distributor.

thanks anyway. will try.

**Comment by FearGannicus** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/33dd5e8f-cc39-4cc1-af24-e49c70b17dc9-e5d7686e-135e-4a01-8a81-7babb1a6d643-v1.png?transparent=1&palette=1&width=128)

Telling someone to install without internet isnt a good fix, why dont we just create an installer that doesnt have bundled in 3rd party bs?

**Comment by cheat-engine** [comment]
6.8.1 is end of life, there won't be a new version. Get 7.0 or later

**Comment by VasiliPupkin256** [comment]
@cheat-engine have you just confirmed that your project installer installs malware and bloatware?
