### ISSUE TITLE
RTTI Reverse Lookup

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#1159]
Is it possible to reverse lookup class pointers so it list up all memory addresses and class names? This would be incredible useful

**Comment by cheat-engine** [comment]
do a memoryscan for the text `.?AV` the text after it is the classname
it only gives a list of classnames though with no links or elements

**Comment by Symbai** [comment]
That only give me class names but the instances are what I'm mostly interested in and these are not findable by text searches. Looking how you get the RTTI info its the other way around. First class instance and then lookup for text inside its sub structure.

**Comment by cheat-engine** [comment]
find the classname
0x10 bytes is the rtti descriptor
in 64-bit convert that address to a modulebase relative address 
then do a 4 byte scan for that address
convert all results in back to an address (if in 64-bit)
decrease all addresses by 12 (both 32 and 64-bit) and confirm that the memory they point at starts with a 1 for 64-bit or a 0 for 32-bit
If correct do a pointersize scan for that address
then for the result(s hopefully 1) increase the address by pointersize which gets yopu to the vtable of the class
then do a pointersize scan for that address to find instances of that class

**Comment by Symbai** [comment]
That sounds so complicated that it should be done in code rather than by hand.

**Comment by cheat-engine** [comment]
this may help:
```lua
s=createMemScan()

s.firstScan(soExactValue, vtString, rtRounded, '.?AV', '', getAddress(process) ,getAddress(process)+getAddress(getModuleSize(process)) ,"*W*X*C" ,fsmNotAligned ,'1' ,false ,true, false, true);
s.waitTillDone()

fl=createFoundList(s)

names={}
fl.initialize()

sll=createStringList()
for i=1,fl.Count do
  local a=tonumber(fl[i-1],16)
  names[i]={}
  names[i].name=readString(tonumber(fl[i-1],16)+4)
  names[i].address=a-0x10
  sll.add(names[i].name)
end

r,selstring=showSelectionList('RTTI Classes','Select the class to find instances of',sll)
if (r==-1) then return end
sll.destroy()

print("You picked "..selstring)
a=names[r+1].address
if targetIs64Bit() then
  a=a-getAddress(process)
end

fl.deinitialize()
--print(string.format("Scanning for %x", a))
s.firstScan(soExactValue, vtDword, rtRounded, string.format("%x",a), '', getAddress(process) ,getAddress(process)+getAddress(getModuleSize(process)) ,"*W*X*C" ,fsmNotAligned ,'1' ,true ,true, false, true);
s.waitTillDone()
fl.initialize()
--print("found "..fl.Count.." results")

RTTIInfo={}
for i=1,fl.Count do
  local a=tonumber(fl[i-1],16)
  a=a-12
  if readBytes(a,1)==1 then
    table.insert(RTTIInfo,a)
  end
end

--print("after checking only "..#RTTIInfo.." left")

if targetIs64Bit() then
  scantype=vtQword
  pointersize=8
else
  scantype=vtDword
  pointersize=4
end

vtables={}

for i=1,#RTTIInfo do
  a=RTTIInfo[i]
  fl.deinitialize()
  --print(string.format("Scanning for %x", a))
  s.firstScan(soExactValue, scantype, rtRounded, string.format("%x",a), '', getAddress(process) ,getAddress(process)+getAddress(getModuleSize(process)) ,"*W*X*C" ,fsmNotAligned ,'1' ,true ,true, false, true);
  s.waitTillDone()
  fl.initialize()

  for j=1,fl.Count do
    table.insert(vtables, tonumber(fl[j-1],16)+pointersize)
  end
end

--print(#vtables.." vtables found")

--scan instances

instances={}

for i=1,#vtables do
  a=vtables[i]
  fl.deinitialize()
  print(string.format("Scanning for %x", a))
  s.firstScan(soExactValue, scantype, rtRounded, string.format("%x",a), '', 0 ,0xffffffffffffffff ,"*W*X*C" ,fsmNotAligned ,'1' ,true ,true, false, true);
  s.waitTillDone()
  fl.initialize()

  for j=1,fl.Count do
    table.insert(instances, tonumber(fl[j-1],16))
  end
end

print("The following instances of the class "..selstring.." where found")
for i=1,#instances do
  print(string.format("%x",instances[i]))
end
```

**Comment by Symbai** [comment]
This works, although it's unstable (selecting the wrong class can freeze CE after printed thousands of instance addresses). But it's definitely something I can work with.

**Comment by r3sus** [comment]
Thanks a lot for the script.
There are modified versions based on it:
https://github.com/r3sus/CE_RTTI_Scanner
Altho reverse lookup is very slow, for more information read:
https://github.com/GrandpaGameHacker/ClassDumper#about-classdumper
The described algo would be nice to be implemented as CE script.

**Comment by FindMuck** [comment]
Small follow-up for anyone who finds this thread later:

I turned this RTTI reverse lookup workflow into a small **Cheat Engine Lua tool** with more convenient searchable class picker, RTTI/COL/vtable resolution, quick (just in less of a second*) candidate instance lookup, and optional broader scanning.

Repo:
- [FindMuck/CE_RTTI_Reverse_Lookup](https://github.com/FindMuck/CE_RTTI_Reverse_Lookup)

It targets **MSVC-style RTTI**, is **x64-first**, and **x86 is best-effort**.  
Main credit goes to Dark Byte and the ideas outlined in this issue and CE forum. I mainly wrapped it into a more practical user-friendly CE workflow.
