### ISSUE TITLE
Missing Value Type "Decimal"

### ISSUE THREAD

**Issue by TheLinthus** [cheat-engine/cheat-engine#117]
Missing value for a common variable type "Decimal", is a floating point is a data type with high precission, ussing 128bits (16 bytes) in memory.
Double use 64bits and Float use 32bits, both already avaliable in Cheat Engine.
Due to the large memory capacity of current computer systems, it is increasingly common to use Decimal in place of other floating points due the decimal type has more precision and a smaller range, which makes it appropriate for financial and monetary calculations.

**Comment by mgrinzPlayer** [comment]
You meant "fixed point"?

**Comment by TheLinthus** [comment]
Decimal values are diferent from fractional floating points.
It consist in:
19 bits - for non porpouse
05 bits - for decimal point, it max value is 11100 (0x1C), mean 28 numbers after the decimal point
04 bits - for non porpouse
01 bit  - for sign bit
03 bits - for non porpouse
32 bits - for UInt32 (multiply by 18'446'744'073'709'551'616 (UInt64 Max Value))
64 bits - for UInt64

In HEX:
00 00 1C 08 00 00 00 00 00 00 00 00 00 00 00 00 
\\____/ \\\_/ \\\_/ \\__________/ \\________________________/
&emsp;-&emsp; Dec Sig&emsp;UInt32&emsp;&emsp;&emsp;&emsp;UInt64

For example:

00 00 **03** 00 ' 00 00 00 00 ' 10 99 02 00 ' 00 00 00 00 = 170.256
00 00 **06** 00 ' 00 00 00 00 ' 10 99 02 00 ' 00 00 00 00 = 0.170256

00 00 **09** 00 ' 00 00 00 00 ' **00 CA 9A 3B ' 00 00 00 00** = 1.000000000
&emsp;&emsp;&emsp;^ 9 decimal points of ^ 1'000'000'000

00 00 00 **08** ' 00 00 00 00 ' FF B0 8E F0 ' 1B 00 00 00 = -120'000'000'255
&emsp;&emsp;&emsp;&emsp; ^0000 **1**000
00 00 04 08 ' 00 00 00 00 ' FF B0 8E F0 ' 1B 00 00 00 = -12'000'000.0255

00 00 00 00 ' **01 00 00 00** ' 00 00 00 00 ' 00 00 00 00 = 18'446'744'073'709'551'616
00 00 00 00 ' **01 00 00 00** ' **01** 00 00 00 ' 00 00 00 00 = 18'446'744'073'709'551'61**7**
00 00 00 00 ' **02 00 00 00** ' 00 00 00 00 ' 00 00 00 00 = 36'893'488'147'419'103'232
00 00 **06** 00 ' **01 00 00 00** ' 00 00 00 00 ' 00 00 00 00 = 18.446744073709551616
