### ISSUE TITLE
Hiding dissect code results

### ISSUE THREAD

**Issue by Wuups** [cheat-engine/cheat-engine#1171]
Would it be possible to have a checkbox or something similar to show/hide dissect code results?
These:
![image](https://user-images.githubusercontent.com/38836940/77871039-90a10d00-7208-11ea-9de0-29a7497daca1.png)
Thank you.

**Comment by cheat-engine** [comment]
`getDissectCode().clear()` will 'hide' it (permanently)
but you can combine it with `getDissectCode().saveToFile([[pathtofile]])` and when you want it back do `getDissectCode() .loadFromFile([[pathtofile]])`

**Comment by Wuups** [comment]
Perfect, thank you.
