### ISSUE TITLE
Unable to Compile (Multiple LuaInternet.pas compile errors)

### ISSUE THREAD

**Issue by NiceMemeBoi** [cheat-engine/cheat-engine#1177]
Lazarus Version 2.0.7 (FPC 2.3.0 Beta)

Attempted to build to recieve compiler errors.

Source is untouched aside from form editing. 

> LuaInternet.pas(319,24) Error: method identifier expected
LuaInternet.pas(321,6) Error: Identifier not found "internet"
LuaInternet.pas(322,16) Error: Identifier not found "internet"
LuaInternet.pas(324,3) Error: Identifier not found "internet"
LuaInternet.pas(324,13) Error: Identifier not found "TFPHTTPClient"
LuaInternet.pas(325,3) Error: Identifier not found "internet"
LuaInternet.pas(325,35) Error: Identifier not found "fname"
LuaInternet.pas(326,3) Error: Identifier not found "internet"
LuaInternet.pas(434,6) Error: Identifier not found "TRegistry"
LuaInternet.pas(434,15) Error: Error in type definition
LuaInternet.pas(439,3) Error: Identifier not found "macPortFixRegPath"
LuaInternet.pas(440,6) Error: Identifier not found "tregistry"
LuaInternet.pas(441,5) Error: Illegal qualifier
LuaInternet.pas(441,14) Error: Identifier not found "HKEY_CURRENT_USER"
LuaInternet.pas(443,10) Error: Illegal qualifier
LuaInternet.pas(448,11) Error: Illegal qualifier
LuaInternet.pas(452,13) Error: Illegal qualifier
LuaInternet.pas(453,11) Error: Identifier not found "cookies"
LuaInternet.pas(463,5) Error: Illegal qualifier
LuaInternet.pas(468,6) Error: Identifier not found "TRegistry"
LuaInternet.pas(468,15) Error: Error in type definition
LuaInternet.pas(471,6) Error: Identifier not found "PStringHashItem"
LuaInternet.pas(471,21) Error: Error in type definition
LuaInternet.pas(474,6) Error: Identifier not found "TRegistry"
LuaInternet.pas(475,5) Error: Illegal qualifier
LuaInternet.pas(475,14) Error: Identifier not found "HKEY_CURRENT_USER"
LuaInternet.pas(477,8) Error: Illegal qualifier
LuaInternet.pas(479,17) Error: Identifier not found "cookies"
LuaInternet.pas(481,10) Error: Identifier not found "cookies"
LuaInternet.pas(482,11) Error: Operator is not overloaded: "<erroneous type>" = "Pointer"
LuaInternet.pas(484,17) Error: Illegal qualifier
LuaInternet.pas(485,11) Error: Illegal qualifier
LuaInternet.pas(485,46) Error: Illegal qualifier
LuaInternet.pas(491,5) Error: Illegal qualifier
LuaInternet.pas(495,3) Error: Identifier not found "cookies"
LuaInternet.pas(495,12) Error: Identifier not found "TStringHashList"

**Comment by cheat-engine** [comment]
get the latest source from github  again

**Comment by NiceMemeBoi** [comment]
That did it, confused on why the version I had wasn't able to be compiled but all is now well.
