### ISSUE TITLE
No access to Warcraft III Reforge process.

### ISSUE THREAD

**Issue by 2020karaulov2020** [cheat-engine/cheat-engine#1178]
No access to Warcraft III Reforge process. I can't patch memory via Cheat Engine.

**I also tried patch memory via c++, using WriteProcessMemory, but VirtualProtectEx not change memory protection of this process :(**

**Comment by 2020karaulov2020** [comment]
Cheat engine version latest (7.0). Windows 10 x64.

**Comment by 2020karaulov2020** [comment]
Target process paused.

**Comment by cheat-engine** [comment]
is the option to never use virtualprotectex disabled in settings?

else use kernelmode openprocess/ write process memory and use lua command 
dbk_writesIgnoreWriteProtection(true)

**Comment by 2020karaulov2020** [comment]
> is the option to never use virtualprotectex disabled in settings?
> 
> else use kernelmode openprocess/ write process memory and use lua command
> dbk_writesIgnoreWriteProtection(true)

I tried using 'cheat engine' process access option, same problem. I can give remove access to my PC if you need test it.

**Comment by 2020karaulov2020** [comment]
@cheat-engine new video https://www.mediafire.com/file/r2lfszez0llx527/19-45-35.mp4/file

**Comment by 2020karaulov2020** [comment]
@cheat-engine i found this game uses SEC_NOCHANGE, how to bypass it ?

**Comment by cheat-engine** [comment]
have you executed `dbk_writesIgnoreWriteProtection(true)` ?

**Comment by 2020karaulov2020** [comment]
i tried it on video https://www.mediafire.com/file/r2lfszez0llx527/19-45-35.mp4/file but nothing help!

**Comment by cheat-engine** [comment]
dbk_writesIgnoreWriteProtection() only works with kernelmode read/write memory enabled and a process opened with kernelmode openprocess

**Comment by 2020karaulov2020** [comment]
What did I do wrong on the video?

**Comment by cheat-engine** [comment]
You disabled kernelmode read/write and only THEN executed dbk_writesIgnoreWriteProtection.

You need to execute it with it enabled

**Comment by 2020karaulov2020** [comment]
Yes it works!

**Comment by 2020karaulov2020** [comment]
@cheat-engine you can't add autocheck memory if not changed then disable this option automatically ?

**Comment by cheat-engine** [comment]
no, because it is a dangerous way of editing memory. If you use writeprotect bypass on other memory like a windows DLL, you'll affect all processes that have that dll loaded

you can add it in a script. 
e.g a memoryrecord,  or even a tablefile
