### ISSUE TITLE
Symbol load crash

### ISSUE THREAD

**Issue by DarkAsm** [cheat-engine/cheat-engine#1182]
Set environment variable "NT" symbolpath "
After that, CE will not work normally, no matter whether the display symbol is selected or not, it will be stuck
![QQ图片20200404151143](https://user-images.githubusercontent.com/62586194/78421164-2cf36580-7688-11ea-8687-718670d0e229.png)
![QQ截图20200404152332](https://user-images.githubusercontent.com/62586194/78421185-48f70700-7688-11ea-9617-54ae96bfb19a.png)

**Comment by cheat-engine** [comment]
You have to wait till the symbols are loaded.
Right now it's downloading all pdb's to d:\symbols and then they will be loaded

**Comment by DarkAsm** [comment]
> You have to wait till the symbols are loaded.
> Right now it's downloading all pdb's to d:\symbols and then they will be loaded

It is possible that Microsoft has shut down the server access right of Chinese access to storage symbols

**Comment by DarkAsm** [comment]
> You have to wait till the symbols are loaded.
> Right now it's downloading all pdb's to d:\symbols and then they will be loaded

Thank you very much. It should be caused by my network problem
