### ISSUE TITLE
Cheat Engine 7.0 won't open

### ISSUE THREAD

**Issue by banana-man95** [cheat-engine/cheat-engine#1196]
I'm on Windows 10 and I downloaded CE 7.0 and when i tried to open it, it wouldn't open at all.  I need help because I want to use Cheat Engine.

**Comment by cheat-engine** [comment]
Did the installer run properly? or just after the install?

If after, uninstall badlion and restart windows

**Comment by WilPermenter** [comment]
Same Issue here... Windows Defender was picking something up but that is allowed now. If I open the installer and even just let it sit there it will just close.

**Comment by cheat-engine** [comment]
check if your firewall is blocking the installer

**Comment by banana-man95** [comment]
I'll try uninstalling badlion, ive done it before without restarting and it didnt work. so ill try with restarting the computer. will close the topic if it works

**Comment by banana-man95** [comment]
didnt work, also why do you need to download additional applications on older CE versions?

**Comment by banana-man95** [comment]
yes, the installer worked properly

**Comment by cheat-engine** [comment]
Are you sure you restarted windows and didn't shutdown and back on? (windows 10 fakes shutdown, restart is the one you need)

**Comment by yBlackZz** [comment]
what is badlion?

**Comment by banana-man95** [comment]
forgot about this issue. cheat engine 7.3 is working.
