### ISSUE TITLE
AV detected Trojan.GenericKD.42721976

### ISSUE THREAD

**Issue by Nijaansh** [cheat-engine/cheat-engine#1197]
Guessing this is a false positive but Anti-Virus sent me: "\AppData\Local\Temp\is-V0NE0.tmp\dsmwiluivxs.dll has been detected as potentially malicious and was moved to quarantine" just wanted any confirmation ty

**Comment by cheat-engine** [comment]
It's the advertising dll. It shows an ad during install and asks if you want to download it .
It's safe

**Comment by Nijaansh** [comment]
> It's the advertising dll. It shows an ad during install and asks if you want to download it .
> It's safe

Thank you!
