### ISSUE TITLE
Convert to lua 5.3

### ISSUE THREAD

**Issue by mgrinzPlayer** [cheat-engine/cheat-engine#12]
current v1.6.2 LFS dll files are too old.

Version 1.6.3 [15/Jan/2015]
   Lua 5.3 support.
   Assorted bugfixes.
http://github.com/keplerproject/luafilesystem/releases/tag/v_1_6_3

--
regular expr in savesession.lua could be:
```Lua
local ext=files[i].name:match("%.([^%.]+)$")
```

--
All OnResize, OnTimer, OnSomething are broken in 32bit CE.

Example, it throws "Error:attempt to call a nil value"
```Lua
createTimer(nil,true).OnTimer = function (timer)
  print('timer working')
end
```

**Comment by mgrinzPlayer** [comment]
Why there is "bin\lua_extra" folder with other files?
Aren't lua53-32 and lua53-64 dlls enough?

**Comment by cheat-engine** [comment]
the extras is for people that wish to compile lua extensions that can be used by CE

I can't test this right now as I don't have a 32-bit build environment setup, but see if this works
```Lua
getMainForm().Caption="works"
```

**Comment by mgrinzPlayer** [comment]
That line works.

**Comment by cheat-engine** [comment]
does this work?:
```lua
timer = createTimer(nil,false)
timer.OnTimer = "timerFunc"

function timerFunc(t)
  print('test')
end

timer.Interval=1000
timer.Enabled=true
```

**Comment by mgrinzPlayer** [comment]
yes

**Comment by cheat-engine** [comment]
should be fixed

**Comment by mgrinzPlayer** [comment]
**All OnResize, OnTimer, OnSomething are now fixed on both 32 and 64 bit.**

Now the only thing we need is newer lfs.dll files

and in savesession.lua  this one
local ext=files[i].name:match("%.([^%.]+)$")

**Comment by mgrinzPlayer** [comment]
Also, lua_rawseti has *lua_Integer* instead of *int*.

**Comment by cheat-engine** [comment]
should both be resolved now

**Comment by yosaf055** [comment]
> current v1.6.2 LFS dll files are too old.
> 
> Version 1.6.3 [15/Jan/2015]
>    Lua 5.3 support.
>    Assorted bugfixes.
> [http://github.com/keplerproject/luafilesystem/releases/tag/v_1_6_3](https://github.com/keplerproject/luafilesystem/releases/tag/v_1_6_3)
> 
> regular expr in savesession.lua could be:
> 
> ```lua
> local ext=files[i].name:match("%.([^%.]+)$")
> ```
> 
> All OnResize, OnTimer, OnSomething are broken in 32bit CE.
> 
> Example, it throws "Error:attempt to call a nil value"
> 
> ```lua
> createTimer(nil,true).OnTimer = function (timer)
>   print('timer working')
> end
> ```
