### ISSUE TITLE
IsAddressSafe issue

### ISSUE THREAD

**Issue by dummy0stud** [cheat-engine/cheat-engine#120]
What kind of safety IsAddressSafe is, and how it differs from MmIsAddressValid?

Can you give me some tip to implement my own IsAddressSafe2Read and IsAddressSafe2Write?

**Comment by cheat-engine** [comment]
I believe MmIsAddressValid reads the address inside a try/except block, and on exception returns false.
The problem with this is that if it happens inside the paged memory region area it will cause windows to BSOD regardless of the try/except

ce's IsAddressSafe looks up the page table entry, and makes sure all parent page entries are present. if not, return false.
(windows 10 makes it slightly more cumbersome but still workable. but if it fails i will just resort to cli/stidt/ldidt my custom one/read/ldidt orig/sti)

safe to read just check if the present bit is there, or use try/except and stay out of nonpaged memory
safe to write, check the writable bit in the page entry (or write the same value as you read in a try/except)

**Comment by dummy0stud** [comment]
I tested MmIsAddressValid with nonpaged mem region and it did not BSOD'd, I am looking for a better MmIsAddressValid, because it works fine for x86, but when I compile my driver to x64 it is failing if memory is not writable

Is current version(master branch) of IsAddressSafe working on windows 10?

**Comment by cheat-engine** [comment]
It should work in windows 10, for reads at least
