### ISSUE TITLE
Virustotal results

### ISSUE THREAD

**Issue by baxandrei** [cheat-engine/cheat-engine#1200]
LINK: https://www.virustotal.com/gui/file/19ee4ee5e919bc00091180409db00b34c80011e335e371b7955798990181c20a/detection (28 / 69)

Also, when I installed it, I saw a page with some additional steps and a loading bar, then install started to copy files but before finishing , window disappeared but files are located in destination folder. Another thing is that the program don`t apear as installed in Add or remove a program.

So, I can trust it?

**Comment by cheat-engine** [comment]
yes, just read the text properly and watch the text on the next/back buttons

**Comment by baxandrei** [comment]
But installation wizard closed before let me view Finish window

**Comment by baxandrei** [comment]
Update: I think I found issue 
![image](https://user-images.githubusercontent.com/12484505/79042416-66841d80-7c00-11ea-8fbb-2a196ed57169.png)

That is the reason why I saw this page: 
![image](https://user-images.githubusercontent.com/12484505/79042435-7e5ba180-7c00-11ea-98cc-71fdc67ec337.png)
 and then installer exited without any error (also files was copied)

**Comment by cheat-engine** [comment]
yeah, there is an issue where if that virustotal is ok, it's all either cheat engine, installcore(the advertisement), or outdated detections for opencandy (just proof that those AV's don't actually check the file content)

anyhow, it's a known issue that the installer fails if the internet connection is bad to download the ad.

**Comment by baxandrei** [comment]
Thank you!
