### ISSUE TITLE
amd support?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1202]
https://github.com/Zero-Tang/NoirVisor

Stealth SSDT Hook (NtOpenProcess Hook) on 64-bit Windows, both Intel VT-x and AMD-V

Software-Level Code Integrity Enforcement

Hardware-Level Code Integrity Enforcement, both Intel EPT and AMD NPT

Does Cheat Engine have a future amd support?

**Comment by cheat-engine** [comment]
someday
