### ISSUE TITLE
dbvm stack view ?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1204]
<img width="636" alt="stackview" src="https://user-images.githubusercontent.com/18622105/79063842-411a1100-7cdf-11ea-87d2-4be3e827c1f2.png">

dbvm extra info

s => stack view possible?
f => possible

**Comment by cheat-engine** [comment]
if you tick the record stack option in dbvm watch yes

**Comment by kitty8904** [comment]
log stack? 

thank you 

Global debugging is not possible on my computer

but dbvmbreakpoint possible

It is sad that high-speed target breakpoint resolution is impossible
