### ISSUE TITLE
dbvm stack view error 2

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1205]
<img width="809" alt="777777777777" src="https://user-images.githubusercontent.com/18622105/79065824-32872600-7cee-11ea-954f-439bace432d1.png">

1. memorybroswer
2. dbvm find out
3. register stack view( not extra info view)
(frmRegistersunit.pas)
4. log stack check
5. stack view click -> no information 

////////////and stack view pointer////////////

TRegisters.sbShowStackClick(Sender: TObject); 

stackview.SetContextPointer(context, stack.stack, stack.savedsize);  

stackview.SetContextPointer(@context, stack.stack, stack.savedsize);  

context -> @context fix?

**Comment by cheat-engine** [comment]
no, I think it's becaused savedsize was not set
