### ISSUE TITLE
SymbolListHandler bug

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1207]
function TSymbolListHandler.AddSymbol(module: string; searchkey: string; address: qword; size: integer; skipaddresstostringlookup: boolean=false; extradata: TExtraSymbolData=nil): PCESymbolInfo;
var new: PCESymbolInfo;
  n: TAvgLvlTreeNode;
  prev, next: TAvgLvlTreeNode;
begin

  exit; <- here

  new:=getmem(sizeof(TCESymbolInfo))

exit -> ex) getaddress kernel32.sleep and symbol list error

**Comment by cheat-engine** [comment]
should be fixed now
