### ISSUE TITLE
windows dbvm build?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1209]
https://chocolatey.org/install

powershell.exe

1.Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

2.choco install make
3.choco install yasm
4.choco install nasm
5. cd c:/dbvm 
6. make clean cdimage
----------------------------
error
make[1]: Entering directory 'C:/dbvm/imagemaker'
process_begin: CreateProcess(NULL, rm -f *.o, ...) failed.
Makefile error make (e=2): The system cannot find the file specified
make[1]: *** [Makefile:9: clean] Error 2
make[1]: Leaving directory 'C:/dbvm/imagemaker'
make: *** [Makefile:85: clean] Error 2

///////////////////////////////////////////////////////////////

I tried to compile dbvm on Windows10

Do you know how to fix this error?

Linux builds normally

**Comment by cheat-engine** [comment]
powershell doesn't know how to do the -f flag for rm

**Comment by kitty8904** [comment]
c:\dbvm>make
make -C vmm -f mkx all SERIALPORT=0  DISPLAYDEBUG=0
make[1]: Entering directory 'c:/dbvm/vmm'
The specified path was not found.
"Assembling vmma.asm"
"Compiling main.c"
process_begin: CreateProcess(NULL, gcc -MT main.o -MMD -MP -MF .d/main.Td -O0 -W -Wall -DSERIALPORT=0 -DDISPLAYDEBUG=0 -DSUPPORT_64BIT_OFFSET -DDARKBYTESFUCKEDUPCROSSCOMPILER -fno-builtin-floor -fno-builtin-ceil -fno-builtin-strspn -fno-builtin-memcpy -fno-builtin-strcpy -fno-builtin-strlen -fno-builtin-strcat -fno-builtin-malloc -fno-builtin-snprintf -fno-builtin-memset -fno-stack-protector -g main.c -c -o main.o, ...) failed.
Makefile error make (e=2): The system cannot find the file specified
make[1]: *** [mkx:53: main.o] Error 2
make[1]: Leaving directory 'c:/dbvm/vmm'
make: *** [Makefile:17: all] Error 2

//////////////////////////////

make -C vmm -f mkx all SERIALPORT=${SERIALPORT} DISPLAYDEBUG=${DISPLAYDEBUG}

-f mkx error?

-rm error?

On Windows then compiling is not possible?

**Comment by cheat-engine** [comment]
I guess not

**Comment by HiImNewb** [comment]
is their anywhere that show steps for install latest dbvm? can't find anything when research it

**Comment by cheat-engine** [comment]
linux (i myself use mint 19) gcc, yasm, nasm

and then `make clean install` to build a vmdisk.img

**Comment by HiImNewb** [comment]
I was able to just run the "Makefile" and it installed dbvm after installing gcc, yasm, nasm. Can you tell me which file is the main one for dbvm I want to add dbvm_setTSCAdjust(false,0) so I don't to manually start do it every time I start dbvm.

**Comment by heniunaidebaobao** [comment]
Ubuntu(64)
error
make[1]: *** [mkx:72：all] 错误 1
make[1]: 离开目录“/home/niunai/repos/cheat-engine-7.4/dbvm/vmm”
make: *** [Makefile:17：all] 错误 2

mkx:72：@${LD} ${LDFLAGS} $(FILES) $(DISTORMFILES) $(LUAFILES) -o ../vmm.elf -Map ../vmm.map

Makefile:17：make -C vmm -f mkx all SERIALPORT=${SERIALPORT} DISPLAYDEBUG=${DISPLAYDEBUG}

**Comment by cheat-engine** [comment]
don't use all
