### ISSUE TITLE
file "standalonephase1.dat"

### ISSUE THREAD

**Issue by Combine900** [cheat-engine/cheat-engine#1213]
Could this file may get updated? multiple antivirus programs think it can make trouble

"$\Cheat Engine\>standalonephase1.dat<" = PUP.Optional.GameHack

i know it doesnt damage anything but would be cool if someone could do anything about that. online, ppl say its used to generate windows trainers

**Comment by HiImNewb** [comment]
add antivirus exception to the folder

**Comment by cheat-engine** [comment]
It's correct. It is a gamehack, so what can we do about it?

**Comment by Combine900** [comment]
> 
> 
> It's correct. It is a gamehack, so what can we do about it? We can edit it so that some AV's don't detect it, but they just look at the sourcecode here and add the detection back.
> 
> In any case, PUP.Optional.GameHack is not dangerous or bad, it's just to scare people from using it.

okay, i think the AV option you wrote is just a time waste. thanks for the reply :) - Combine
