### ISSUE TITLE
UWP games and mono injections

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#1214]
CE fails to inject mono server into UWP games. I can confirm this is because it's missing the "[ALL APPLICATION PACKAGES](https://www.unknowncheats.me/forum/general-programming-and-reversing/177183-basic-intermediate-techniques-uwp-app-modding.html)" permission. After the mono dll can be injected. However CE still fails to connect. After some research I figure out that UWP games are sandboxed and don't allow named pipes outside UWP.

Maybe we can choose another communication method? Maybe this makes it possible for the linux server to also benefit from this and make mono features available too?

**Comment by cheat-engine** [comment]
CE's installer sets the permission to "ALL APPLICATION PACKAGES"
as for the pipe perhaps duplicatehandle can be used for that.

**Comment by Symbai** [comment]
Ah okay, I've always "installed" CE via archive instead. [Here are some recommendations](https://docs.microsoft.com/en-us/windows/uwp/communication/interprocess-communication) but all of them have restrictions.

Game Pass (Microsoft's NetFlix for games) have several unity games running as UWP such as Long Dark, Wasteland, and so on. Some of them uses il2cpp and others don't.

**Comment by Symbai** [comment]
I can confirm that 65d511ed4c98f26b3195fb1d31304f5ff102d8dd fixes the issue, thank you.
