### ISSUE TITLE
Inaccurate processor capability assessment with Virtualization-based Security enabled

### ISSUE THREAD

**Issue by awuctl** [cheat-engine/cheat-engine#1215]
Cheat Engine, when checking for processor capabilities (such as Intel Processor Trace for Ultimap 2, VT-x for DBVM, etc.) does not take into account Windows' Virtualization-Based Security and the Hyper-V hypervisor (which are since 1903 9D - KB4517211 in use by default). 
This causes incorrect "unsupported CPU" prompts for supported processors.

Cheat Engine could check whether VBS is in use (perhaps by querying Device Guard settings?) or if there is already some other hypervisor in use (in this case Hyper-V) which could hide/mask CPUID fields.
Both features need to be off for Cheat Engine to fully work and either informing the user about them or disabling those features automatically would greatly help.

**Comment by MrPepka** [comment]
I confirm after enabling Hyper-V and virtualization-based security Cheat Engine incorrectly signals that the processor does not support DBVM

**Comment by cheat-engine** [comment]
it's a known issue yes.
Though saying "Your system does not support DBVM" is kinda correct. It doesn't specifically say CPU, just System.  This is also a thing if you disable Intel-VT in the Bios.  The CPU does support it, but has been disabled
