### ISSUE TITLE
CE 7.1 setup crashes if access to ginihehen.com blocked by firewall

### ISSUE THREAD

**Issue by AGlezB** [cheat-engine/cheat-engine#1219]
![image](https://user-images.githubusercontent.com/12277525/80046709-60801d80-84d9-11ea-9d0f-c46ccff67b5e.png)

It just opens and closes.

**Comment by LoZio** [comment]
I don't know if it is because of ginihehen.com (that Fortinet marks as malware), but have the same problem with 7.1.0.6 setup opening and closing with no message.

**Comment by Manimap** [comment]
I can confirm that problem, the silent close is very annoying.

**Comment by washingleavesandthensome23-434** [comment]
yep , just downloaded latest installer , 7.0 setup no issue , this one instant crash after a few seconds into the installer , fucking god damn it , please fix , thanks

**Comment by Uinden** [comment]
I have firewall-related problem too.
Installer `CheatEngine71.exe` drops file `C:\Users\username\AppData\Local\Temp\is-PNF4U.tmp\CheatEngine71.tmp` which trying to access network.
When `CheatEngine71.tmp` blocked by firewall it crashes and installer closes.
![vMWzxSKCPkIU](https://user-images.githubusercontent.com/25625733/82733977-593e7080-9d20-11ea-80d6-758a536e8f57.png)

**Comment by AGlezB** [comment]
7.2 works fine so I'm closing this one.
