### ISSUE TITLE
process label view error

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1225]
<img width="186" alt="label" src="https://user-images.githubusercontent.com/18622105/80303097-06d56700-87e9-11ea-9930-b2456625f7eb.png">

procss label language view error

LazUTF8 add pas

ProcessWindowUnit.pas

old
ProcessLabel.caption:=

fix
ProcessLabel.caption:=WinCPToUTF8()

**Comment by Symbai** [comment]
Encoding is wrong (special characters & unicode characters), see #503
