### ISSUE TITLE
SaveFormPosition Error?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1226]
<img width="586" alt="regerror1" src="https://user-images.githubusercontent.com/18622105/80316449-e2a17680-8838-11ea-991f-ac90ba5be281.png">

Comments Position
D5 00 00 00 02 04 00 00 C6 7d 01 00 4f 25 01 00

Size range overflow in Panel1.SendMoveSizeMessages: Width=97734, Height=43.

An overflow may recording the form reg position

SaveFormPosition overflow Save-> LoadFormPosition Load Error

===============
maybe? form size? and variable zero clean?

**Comment by mgrinzPlayer** [comment]
```
D5 00 00 00 - 213 - top
02 04 00 00 - 1026 - left
C6 7d 01 00 - 97734 - width
4f 25 01 00 - 75087 - height
```

Wild values. What did you do that CE saved this in the registry?

**Comment by kitty8904** [comment]
> Wild values. What did you do that CE saved this in the registry?

Form position value is over 65535 when ce is abnormally terminated

Sometimes the form position value overflows

I don't know why

**Comment by mgrinzPlayer** [comment]
We can add some sanity checks to the CEFuncProc.pas LoadFormPosition and SaveFormPosition

**Comment by kitty8904** [comment]
> We can add some sanity checks to the CEFuncProc.pas LoadFormPosition and SaveFormPosition

Yes, I think I should patch it,

It's not a bug that happens to anyone

**Comment by mgrinzPlayer** [comment]
By the way. @cheat-engine is it correct? 

Adjusted _top_ and _left_ for nearest monitor:
https://github.com/cheat-engine/cheat-engine/blob/19d92d87b2ae1e11feb736c60dd9b0ecf05d4382/Cheat%20Engine/CEFuncProc.pas#L3006-L3007

then again _top_ and _left_:
https://github.com/cheat-engine/cheat-engine/blob/19d92d87b2ae1e11feb736c60dd9b0ecf05d4382/Cheat%20Engine/CEFuncProc.pas#L3010-L3011

For big window it will set negative _top_ and/or negative _left_. Why that way? Maybe changing height and width would be better option?
