### ISSUE TITLE
restoreSeDebugPrivilege BUG?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1227]
function restoreSeDebugPrivilege(L:PLua_State): integer; cdecl;

old
tp.Privileges[0].Attributes := SE_PRIVILEGE_ENABLED;

after:
tp.Privileges[0].Attributes := 0;

Must be 0 if removing SeDebugPrivilege permission

If not, it should be ON / OFF with TRUE FALSE

**Comment by cheat-engine** [comment]
restoreSeDebugPrivilege sets it back on after something else has disabled it

**Comment by kitty8904** [comment]
if GetProcessWorkingSetSize(ownprocesshandle, minworkingsize, maxworkingsize) then
    begin
      SetProcessWorkingSetSize(ownprocesshandle, 16 * 1024 * 1024, 64 * 1024 * 1024);
    end;

 closehandle(tokenhandle); 

tokenhandle not close?

FormCreate tokenhandle not closehandle

and ownprocesshandle not closehandle

**Comment by cheat-engine** [comment]
tokenhandle can be closed I guess, it's not like it's important to close.
And never close ownprocesshandle, it's important
