### ISSUE TITLE
DBVM booting error

### ISSUE THREAD

**Issue by pyj2323** [cheat-engine/cheat-engine#1230]
DBVM booting stops on this screen.
What should I do?

![20200428_074759](https://user-images.githubusercontent.com/32794121/80428736-28d00600-891d-11ea-8e21-3c94171170ba.jpg)

version : CE 7.1
CPU : Intel I9-7980XE

**Comment by cheat-engine** [comment]
did you set the correct drive to boot off of ?
Also, are you using uefi toi boot up windows? if so, you need the uefi bootloader for dbvm

**Comment by pyj2323** [comment]
how to set my disk to 80?

**Comment by cheat-engine** [comment]
it's set to 80 by default, you need to change it to the disk you are using (no idea what it is, try 81, 82, 83, 84, ....)
Use command 2 for that

But again, if possible use the uefi version

**Comment by pyj2323** [comment]
Can you tell me how to make uefi disc?

**Comment by cheat-engine** [comment]
https://github.com/cheat-engine/cheat-engine/issues/521

the last dbvmefi zip might work. You may need to configure your USB disk partition to be a EFI partition for it to work
(and don't forget to place a more up to date vmdisk.img in that drive)

**Comment by pyj2323** [comment]
Thanks
