### ISSUE TITLE
Installer fails, fixed with using a VPN connection

### ISSUE THREAD

**Issue by Peredv** [cheat-engine/cheat-engine#1235]
I couldn't run through the installer, antivirus turned off, no firewall, so I figured my ISP was probably blocking the connection to "rp.ginihehen.com" for getting bloatware suggestions. Turning on my VPN did the trick and the installer worked flawlessly, just putting this out there so people who look at the issues are aware.

**Comment by MellowedMatt** [comment]
Thanks for this, my Pi-Hole was blocking the domain. Had to disable it for the installer to work on my machine as well.

**Comment by AGlezB** [comment]
This is the same issue as #1219
