### ISSUE TITLE
[Question]Cheat Engine for Mac 7.1

### ISSUE THREAD

**Issue by HeIp** [cheat-engine/cheat-engine#1242]
Hello would like to know when Cheat Engine for Mac(v7.1) will officially release to the public?

**Comment by cheat-engine** [comment]
When Apple unblocks my developer ID

**Comment by HeIp** [comment]
Ooof, Eta ?

**Comment by cheat-engine** [comment]
Apple's last reply was "I have forwarded information to our internal teams. As soon as there is an update, I will get in contact again and inform you accordingly." at 10/3/2019 , so expecting a reply any day now.... , it is Apple support after all!

In the meantime the Trial mode still works, and you can always restart CE when it gets too limited, there it no limit on restarts

**Comment by HeIp** [comment]
Sometimes have to run several times pressing 2 or 3 before successful launch

**Comment by cheat-engine** [comment]
There is a text above it stating which button to click

**Comment by HeIp** [comment]
No, I know. But I'm saying it's not always a successful launch. So I launch it multiple times and click 2 or 3 and get a successful launch eventually
