### ISSUE TITLE
High CPU usage with MemRec ByteArray Length 0 in active state

### ISSUE THREAD

**Issue by CJBok** [cheat-engine/cheat-engine#1244]
High CPU usage with MemRec ByteArray Length 0 in active state

Reproduce:
- Attach any process
- Add Address Manually
- Set type to Array of byte and Length 0
- Activate created Memory Record

For me the difference is from 0% CPU usage to 8% CPU usage.
- Freeze Interval: 10ms
- Update Interval: 50ms

**Comment by mgrinzPlayer** [comment]
What address? Readable or not?

**Comment by CJBok** [comment]
Currently I am not able to reproduce the high CPU usage consistently as well. I will close it for now and raise new issue when I have more details.
