### ISSUE TITLE
Initializing a value as float doesn't work properly.

### ISSUE THREAD

**Issue by Xeavin** [cheat-engine/cheat-engine#1246]
I have been having an issue with initializing float values.

This is the code snippet from my script. It works perfectly fine in CE 7.0, but in 7.1 it just spits out _random_ numbers instead. 

```
[enable]
alloc(var,4)
registersymbol(var)

var:
dd (float)1

[disable]
unregistersymbol(var)
dealloc(var)

**Comment by cheat-engine** [comment]
do you have a memoryrecord with as description ```float``` ?

**Comment by Xeavin** [comment]
No, the description is "identifier". The type is obviously float though.

**Comment by Xeavin** [comment]
I just tested the script by attaching CE to itself and it worked. When i attached to the game i was testing it at, it still worked, but when i loaded an older cheat table and used the exact same script just copied over, it did not. I am not sure how my cheat table could interfere with it.

**Comment by mgrinzPlayer** [comment]
He meant any memoryrecord with description **float**. If you have it your table, dd (float)1 will give wild values. (the same problem with "double", "int")

It's the recent feature "You can now use (addresslist description) as an address" which gives this bug. Feature not tested thoroughly.

If you think you have more CT files which can have this problem, and you don't want to check them one by one, you can try this:
https://fearlessrevolution.com/viewtopic.php?p=134978#p134978

**Comment by Xeavin** [comment]
I apologize, yesterday i was able to narrow it down to 3 headers with each having 2 addresses. One of them was called **Float** since it's literally how the status effect is called ingame. What was weird though is that only deleting that header didn't fix it. I had do always delete 2 out of the 3. Maybe it is a timing thing, since i even remember deletting the headers and kept the addresses inside them and it still didn't work, so i was confused. Agan sorry for the inconvenience.

**Comment by mgrinzPlayer** [comment]
This "You can now use (addresslist description) as an address" feature also added some kind of "cache".

For example in previous CE versions (up to 7.0) with this Lua script you can remove all memory records having "temp" description:
```
local mr = getTableEntry"tmp"

while mr~=nil do
  mr.destroy()
  mr = getTableEntry"tmp"
end
```
Now, this script will remove only one memory record.
```
for i=AddressList.Count-1,0,-1 do
  local mr = AddressList[i]
  if mr.Description=='tmp' then mr.destroy() end
end
```
