### ISSUE TITLE
McAfee deletes installer when clicking to install 7.1: EDIT. This version is packed with a Trojan!

### ISSUE THREAD

**Issue by RepoDraghon** [cheat-engine/cheat-engine#1255]
Also, McAfee warns when downloading...

**Comment by RepoDraghon** [comment]
Maybe take the Virus and the virus detector out of the installer! I clicked on accept as I thought it was just a disclosure for use of the cheat device, but it was an exception for your installer to install a trojan into my PC and now I'm being bombarded with ads and questionnaires! Now I have to drive 45 minutes away to take my PC into a shop and get rid of the virus on my PC and I did a workaround to install this without McAfee deleting the installer...

**Comment by cheat-engine** [comment]
All optional software can be uninstalled using the "Apps & Featurss" in windows settings

**Comment by RepoDraghon** [comment]
Yeah, no, when trying to uninstall it isn't lasted in the programs

**Comment by AlexAndHisScripts** [comment]
"Optional software" it's malware, call it what it is. @RepoDraghon windows defender picked up on it for me, if not try malwarebytes.

**Comment by AlexAndHisScripts** [comment]
Additionally, even when it's been uninstalled your installs are still fucked up - just like you, @cheat-engine

**Comment by RepoDraghon** [comment]
that was a little uncalled for
