### ISSUE TITLE
Scripts broken in 7.1 

### ISSUE THREAD

**Issue by AizerMortenort** [cheat-engine/cheat-engine#1256]
A huge mod of mine is broken now with the 7.1 release. Many scripts give errors some wont work and the game lags . Is something important changed with lua/asm syntax or symbols etc? Some scripts also seem to run on their own without me activating them

**Comment by mgrinzPlayer** [comment]
Try narrowing down what stopped working correctly. Prepare CT file with those examples and upload it here.

Don't know why your game started lagging. Does the same things happens when you use your scripts with CE7.0?

**Comment by AizerMortenort** [comment]
No this is why i report it my mod suddenly broke. I tried installing.uninstalling CE7,1 then settings etc no it wont work at all. Gives errors and so . Functions are broken. 
It has too MANY scripts to start checking all WORKED before so its not my fault . 
With 7.0 all is fine

**Comment by Symbai** [comment]
> 
> 
> Gives errors and so .

Why don't you just show us the exact errors it gave to you?

**Comment by AizerMortenort** [comment]
Well i already sent my work to Eric and he already fixed it . So it means something must be changed in the way scripts work now or addresses with CE 7.1 its not something i can fix without knowing exactly what needs to be changed :) 
Errors were like TTreeNods.GetAddressList.Active or something and so.

**Comment by AizerMortenort** [comment]
Issue solved Eric said next version will have this fixed . Its description "float" causing issues.
