### ISSUE TITLE
ManualModuleLoader.pas(149,36) Error: Identifier not found "ifthen"

### ISSUE THREAD

**Issue by vancesereda** [cheat-engine/cheat-engine#1263]
I first encountered the error when downloading lazarus that it doesn't support the 32bit compiler. Then I went and got that one and upon doing run--build I get this. And also this: 

ManualModuleLoader.pas(149,66) Fatal: Syntax error, ")" expected but "," found

Any ideas?

**Comment by nafiz1001** [comment]
what's the solution?
