### ISSUE TITLE
aobscan memory range 

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1264]
procedure aobscans(code: tstrings; syntaxcheckonly: boolean);

            if processhandler.is64Bit then
              aobscanmodules[m].maxaddress:=qword($7fffffffffffffff)
            else
            {$endif}
            begin
              if Is64bitOS then
                aobscanmodules[m].maxaddress:=$ffffffff
              else
                aobscanmodules[m].maxaddress:=$7fffffff;
            end;

            aobscanmodules[m].maxaddress:=qword($ffffffffffffffff);  -> here

aobscan(test,11,22,33,44,55,66,77,88)
registersymbol(test)

1. query memory region check

aobscan -> stop address => kernel memory max range search??

**Comment by cheat-engine** [comment]
aobscan is for casual users and scripts. Some people have kernelmode query memory regions checked because they don't know any better, and would crash their system if they'd do an aobscan and it couldn't be found in the process (or take too long)

if you wish to do a kernel aobscan then create a memscan object and fill in the region manually

**Comment by KimCracks** [comment]
@kitty8904 Can you fuck not opening issues for your personal questions?

Maybe read the code? Maybe Stop fuckin pasting?

코드 분석할 깜냥이 안되면 공부부터 하고 질문해라.

**Comment by kitty8904** [comment]
kimcracks ni ae mi yo

**Comment by KimCracks** [comment]
> kimcracks ni ae mi yo

toxic script kiddy never gonna change. 
stop abusing cheat engine issue tracker to fix your paste.

**Comment by kitty8904** [comment]
KimCracks 

What have you contributed to the cheat engine source?

Ni ae mi die

**Comment by KimCracks** [comment]
> KimCracks
> 
> What have you contributed to the cheat engine source?
> 
> Ni ae mi die

sure, spamming your personal questions to repo counts as contributing, right?

https://github.com/cheat-engine/cheat-engine/issues/1126
to be honest i dont expect much more who cant even compile CE LMFAO

**Comment by KimCracks** [comment]
단순 컴파일도 할줄모르는 지체장애아 능지수쥰 ㅋㅋ

**Comment by KimCracks** [comment]
lets use issue tracker to bag for implementing functions that i cant do!
thats called contributing, right?

skiddy brain:tm:

**Comment by kitty8904** [comment]
KimCracks

Did you contribute 1% to the cheat engine source?

You do nothing

ni ae mi die 

Your mom is a whore

**Comment by KimCracks** [comment]
> KimCracks
> 
> Did you contribute 1% to the cheat engine source?
> 
> You do nothing
> 
> ni ae mi die
> 
> Your mom is a whore

> sure, spamming your personal questions to repo counts as contributing, right?

0 iq.

**Comment by KimCracks** [comment]
@kitty8904 ㄹㅇ 아스퍼거걸린 정신박약아가 해킹한다고 깝치면 이렇게되노 ㅋㅋ

**Comment by kitty8904** [comment]
Your mom pussy is whore

you can die in gas with ur degenerated family zzz
