### ISSUE TITLE
cheat engine dont launch 

### ISSUE THREAD

**Issue by NyWena** [cheat-engine/cheat-engine#1266]
cheat engine just dont launch i dont get any error message or nothing i uninstalled badlion client and disabled AV but nothing seems to work can someone help me ?

**Comment by cheat-engine** [comment]
did you uninstall using their uninstaller?  Also restart windows afterwards (not shut down, actual restart)

**Comment by NyWena** [comment]
i uninstalled it via windows settings and yes i restarted windows after i uninstalled

**Comment by cheat-engine** [comment]
do a `driverquery /v` and check if there's anything left of badlion

**Comment by NyWena** [comment]
yep i found it what do i need to do ?

**Comment by cheat-engine** [comment]
try reinstalling badlion and then uninstall with the uninstaller they provide. 
Or try manually deleting and and reboot. Perhaps windows won't restore it. Again, make sure you restart windows, do NOT shutdown , wait, and then back on, windows 10 fakes that

**Comment by NyWena** [comment]
thanks you it worked
