### ISSUE TITLE
detected cheat engine

### ISSUE THREAD

**Issue by SniffAByte** [cheat-engine/cheat-engine#1273]
when i install cheat engine along with my game then my game doesn't open and it tells me that i've installed cheat engine and i have to uninstall it first. after searching i found that i have to mod the cheat engine source code and then compile it and use the modded one. i think i've to change some names and strings in the source code and that's all. but what strings should I change?

**Comment by eLeCtrOssSnake** [comment]
This issue is not affecting cheat engine directly, so this is probably wrong place to ask, but what game are you using?

**Comment by kolanski** [comment]
mk 11 have this behaviour.

> This issue is not affecting cheat engine directly, so this is probably wrong place to ask, but what game are you using?
