### ISSUE TITLE
Ghost instruction

### ISSUE THREAD

**Issue by nubness** [cheat-engine/cheat-engine#1274]
![ce-bug-report-2020-06-14](https://user-images.githubusercontent.com/66904672/84591133-a35cd280-ae44-11ea-8bc7-d8f01968d5e0.png)

As you can see from the attached screenshot, line 47 is empty, but somehow it compiled as "nop dword ptr [eax+00]".

**Comment by mgrinzPlayer** [comment]
"nop dword ptr [eax+00]" is just multibyte nop.
Earlier CE versions will just produce 4 nops. New CE versions use multibyte nops.

use "jl short" if you are sure target is in [-128,127] range.
