### ISSUE TITLE
Assembler generates wrong instruction when leading zeros are missing

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#1277]
When removing the leading zeros from this instruction:
`imul rdx,rax,00000088`
CE generates this instruction instead:
`imul rdx,rax,-78`

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/14368203/84884988-eeaff480-b081-11ea-9f33-00d8b578efcc.gif)

**Comment by cheat-engine** [comment]
that's by design. Because you left only 2 digits, you explicitly ask for the 1 byte version

**Comment by Symbai** [comment]
Ah okay
