### ISSUE TITLE
Cheat Engine searches for one array of bytes but not other

### ISSUE THREAD

**Issue by KulaGGin** [cheat-engine/cheat-engine#1278]
Cheat Engine finds the `48 83 F8 10 72 54 48 8B 4C 24 20 48 FF C0 48 3D 00 10 00 00` array of bytes, but can't find `48 8B 7C 24 70 48 8B 74 24 68 48 8B 44 24 38 48 83 F8 10 72 54 48 8B 4C 24 20 48 FF C0 48 3D 00 10 00 00` arrray of bytes right next to it in the same process. Here's a video with the problem: https://streamable.com/1akbuo

Looks like a scanner's search algorithm bug or something?

**Comment by cheat-engine** [comment]
Your video shows that the first AOB (which is at tekkengame-win64-shipping.exe+540c29d) also isn't found.

Anyhow, as shown in the hexadecimal view of the memoryviewer, the protection is "Execute/Write Copy"
You are scanning with "Write copy" disabled, so you will not find it.  Enable or grey out write copy and you should be able to find it

**Comment by KulaGGin** [comment]
Thanks. Sorry, I missed that. I did try to check copy on write and it didn't find it for me when I tried it last time, but it works now. Probably because I unchecked executable or writable in the past.
