### ISSUE TITLE
debughelper.pas(2194,25) Error: Identifier not found "ifthen"

### ISSUE THREAD

**Issue by theunknownm** [cheat-engine/cheat-engine#1286]
Would someone be so nice to help me out at that point? I am traying to make a 64bit compiled CE for my self and i am failing even with the guide i do have.

//32 bit: check if it has noexecute support
      if assigned(GetProcessDEPPolicy) and assigned(SetProcessDEPPolicy) then
      begin
        ph:=OpenProcess(ifthen<dword>(GetSystemType<=6,$1f0fff, process_all_access),false,processid);    //the debuggerhandle does not get this properly
        try
          if GetProcessDEPPolicy(ph, @depflags, @perm) then
          begin
            if (depflags and 1=0) then
            begin
              //dep is not on             

ideoptiondefs.pas(304,37) Warning: Function result variable does not seem to initialized
MainUnit.pas(5518,32) Warning: Symbol "AppHandle" is not portable
debughelper.pas(1712,15) Warning: Conversion between ordinals and pointers is not portable
debughelper.pas(2194,25) Error: Identifier not found "ifthen"
debughelper.pas(2194,55) Fatal: Syntax error, ")" expected but "," found

**Comment by mgrinzPlayer** [comment]
You have to patch lines with compile error yourself. Recent CheatEngine releases (CE7.0 and CE7.1) were compiled with FPC3.2.0-beta.

https://github.com/cheat-engine/cheat-engine/issues?q=is%3Aissue+ifthen+sort%3Aupdated-desc

**Comment by theunknownm** [comment]
> FPC3.2.0-beta.

i did actually manage to fix that but i did use a older verson.. 3.0.2 and gave up after the 7 or 8 error i got, i will try it now again ty very much :)
