### ISSUE TITLE
Cheat engine doesnt open.

### ISSUE THREAD

**Issue by Kikis2006playz** [cheat-engine/cheat-engine#1287]
When i install cheat engine on my pc it isnt opening. I had CE 7.0 and i unistalled it. Now when i want to install CE 7.1 i cant open it. It crashes when i open it. Even 7.0 refuses to install. I dissabled all windows security and it still didnt open. I ran it as admin as well. How can i fix this.    P.S sorry for bad english

**Comment by itsDARK768** [comment]
me to

**Comment by xFlakezZz** [comment]
m2

**Comment by cheat-engine** [comment]
uninstall badlion and restart windows.

If you're talking about the installer, allow CE access to the internet

**Comment by Kikis2006playz** [comment]
how do i give it access to internet?
