### ISSUE TITLE
Cheat Engine Error “the application was unable to start correctly 0xc00007b windows 10 64 bit” fix

### ISSUE THREAD

**Issue by Hunter1212** [cheat-engine/cheat-engine#129]
I have been getting this error, on windows 10 Enterprise x64 bit. Previously it was working correctly but after two or three days, I have been getting this error “the application was unable to start correctly 0xc00007b windows 10 64 bit”. The log file found using Dependency Walker is [https://drive.google.com/open?id=0Bzgcv08b7F8kcHN2OHZBNmJWODA](here).

EDIT: I am able to use the x86 version of the cheat engine, it's only the x64 version. Also in dependency walker the x86 version of cheat engine gives the same errors. So I think it's not about these errors, that is preventing the x64 version of CE. Hope this helps.

EDIT: I am able to run all programs x86 version, but not x64 version on a x64 bit windows. Certainly that isn't just a cheat engine issue, so might close this issue as solved. Thanks

**Comment by zmir79** [comment]
I also have this problem, i have Win-10-x64, simply clicking in CE icon on desktop gets the error 0xc000007b with process "cheatengine-x86_64.exe" but running the 32 bit CE works just fine on 32 bit games. cannot do anything about 64 bit games though.
![ce-x86-64-error-](https://cloud.githubusercontent.com/assets/29063554/26584881/d625f856-4563-11e7-9eac-91a5d5fd5afd.jpg)
