### ISSUE TITLE
Cheat Engine displaying wrong float value

### ISSUE THREAD

**Issue by Kartonfalter101** [cheat-engine/cheat-engine#1291]
When changing the type of pointer to array-of-bytes and then back to float, cheatengine not displaying the correct float value anymore. faulty internal casting?

I also tried restarting the program and reopening the saved pointers, it still displays wrong values.

[heres a video](https://www.youtube.com/watch?v=c2WUSAM4p_w&feature=youtu.be)

**Comment by cheat-engine** [comment]
Rightclick the address and uncheck show as hexadecimal. 
Array of byte sets that by default as most people expect it that way
