### ISSUE TITLE
CEShare: keeps returning "Wrong password", but I'm entering the correct password for my FRF account...

### ISSUE THREAD

**Issue by jungletek** [cheat-engine/cheat-engine#1294]
It includes non-alphanumeric characters, could that be the issue?

Let me know if you need more info (debug stuff), or need to know what my password is (obviously over private channels) for testing.

Thanks Eric.

**Comment by cheat-engine** [comment]
CEShare isn't hosted by me and depends on the config of the server.
Assuming you're talking about fearless revolution i'll notify the owner (seeing they switch between forum software about every month something may have been forgotten to update there)

**Comment by jungletek** [comment]
Understood, I'll try it out later today, and yell at STN if it's still not working ;)

Thanks for the response.
