### ISSUE TITLE
[Request] Structure Dissect - Freeze (selected) column values

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#1295]
Sometimes it is necessary to compare between two different moments in the game against the same structure. For example player structure inside a building vs player structure outside of a building. Currently when the player leaves the building the game shows up a loading screen, the player structure becomes a new address and all values of the player structure in the dissect windows of the old address become invalid. I have to make a screenshot and compare values this way.

Would be nice if we can just right click -> `freeze values` to stop CE updating values for this specific column. Then add a new column with the new player address and compare both against each other.

**Comment by FreeER** [comment]
![image](https://user-images.githubusercontent.com/2312577/87880006-e1a16080-c9b3-11ea-9cb9-b7115c2aa741.png)

**Comment by Symbai** [comment]
🤣👍
