### ISSUE TITLE
android ceserver module write memory 

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1296]
<img width="1174" alt="and" src="https://user-images.githubusercontent.com/18622105/87889545-1f15f480-ca6d-11ea-8077-bd2fecde448f.png">

1. https://cheatengine.org/download/ceserver_android_x86.zip
2. root mode
3. get find out memory address 
4. data@app@com.PinballGame.oatexec+5CB9C6 - mov ebx,[edx+000004C0]
(mov ebx,[edx+000004C0] -> NOP FIX -> NO FIX
5.Execute /Read Only module memory?

//////////////////////////////////////////////

Is it an old ceserver file?

Is the latest ceserver able to modify the module memory?

I can't change the address value after debugging

(test tool: nox player ,ce 7.1 , ceserver_android_x86.zip(https://cheatengine.org/download/ceserver_android_x86.zip)

**Comment by cheat-engine** [comment]
It is a bit older but shouldn't matter with this issue.
Can you change the value after restarting the game without debugging?

**Comment by kitty8904** [comment]
no debug attack process-> memory fix possbile
debug attack process -> memory not fix

////////////////////////

1.auto assembler jmp hook , alloc not support?

2.cheat engine advanced option button nop,restore not fix

3.cheat engine memory view single line nop bug( assmbler nop size error)
(mov ebx,[edx+000004C0] -> nop -> 90 9A C0 04) -> error
(mov ebx,[edx+000004C0] -> nop -> 90 90 90 90) -> not error

4.find out what access (f5) -> find list 5 -> debug stop -> re find out -> find list 1 -> find list error?
(F5 debug and count does not increase when used again)
(re find out access(f5) -> count 1 stop)

5.release new ce_android_x86 file?
