### ISSUE TITLE
7.1 wont open, i tried windowsrepair, i tried restarting, idk

### ISSUE THREAD

**Issue by dumbcuck** [cheat-engine/cheat-engine#1298]

**Comment by dumbcuck** [comment]
im using it for geometry dash

**Comment by cheat-engine** [comment]
uninstall badlion and restart windows

**Comment by solidssss** [comment]
Same for me.
I don't have badlion installed

**Comment by cheat-engine** [comment]
"I don't have badlion installed" is the same as this guy here posted: https://forum.cheatengine.org/viewtopic.php?t=614841  , he did have it installed

anyhow, do a
```driverquery /v >bla.txt``` and upload the bla.txt here so we can see what else can be interfering

**Comment by solidssss** [comment]
> "I don't have badlion installed" is the same as this guy here posted: https://forum.cheatengine.org/viewtopic.php?t=614841 , he did have it installed
> 
> anyhow, do a
> `driverquery /v >bla.txt` and upload the bla.txt here so we can see what else can be interfering

You must be high af bruh. I'm not the one you linked

**Comment by cheat-engine** [comment]
I'm not saying it's you, i'm just saying that I often see the "I don't have badlion installed" reply when I tell them to uninstall it.

anyhow, `driverquery /v >bla.txt` and upload the bla.txt here so we can see what else can be interfering

also, are you talking about the installer after installing?  If installer, allow internet

**Comment by solidssss** [comment]
Alright. Here is the [log](http://www.filedropper.com/bla).
Thanks for helping.

**Comment by cheat-engine** [comment]
Besides windows defender firewall I don't really see the issue. Do you maybe have a hardware filewall blocking access to servers ?

**Comment by solidssss** [comment]
> Besides windows defender firewall I don't really see the issue. Do you maybe have a hardware filewall blocking access to some servers ?

Oh, I had to disable Adguard Home in my Raspberry dns server, and now it's working! Thanks

**Comment by dumbcuck** [comment]
![Screenshot 2020-07-21 08 31 01](https://user-images.githubusercontent.com/68575774/88074678-91014300-cb2c-11ea-8b50-4d47afedaf70.png)
?

**Comment by dumbcuck** [comment]
for some reason that worked, thanks

**Comment by dumbcuck** [comment]
wait now when i start a level it kicks me out after a few seconds

**Comment by dumbcuck** [comment]
nevermind i just had to ad a 1 to the value
