### ISSUE TITLE
Debugger - Break on unexpected exceptions does not work properly

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#1306]
I attached the debugger to an unreal engine game, then I enabled break on unexpected exceptions. Then I raised such an exception by creating faulty script injection. Usually the memory viewer would break there and show me all the registers and such but instead, the game freezes up completely and a messagebox appears from CE:

![image](https://user-images.githubusercontent.com/14368203/89103983-5db09500-d405-11ea-9116-81e4503aaaa5.png)

I can reproduce this all the time, only happens on unexpected exception. Otherwise debugging the game just works fine.

**Comment by cheat-engine** [comment]
Do you have any debugger_onBreakpoint or other breakpoints set ?

**Comment by Symbai** [comment]
No breakpoints set, here is what I do:

1. Run game and attach CE
2. Set to break on unexpected exceptions
3. Open memory viewer click on first address and set a breakpoint to attach debugger, afterwards remove the breakpoint (breakpoint did not hit)
4. Inject faulty code and wait till it get executed
5. Messagebox appears

**Comment by Symbai** [comment]
Nevermind, I did a clean installation of CE and now it works. Guess all the custom compilation and copy over to my existing CE installation screwed somethign up.
