### ISSUE TITLE
Successfully compiled 32 bit Version but can't compile the 64 bit version

### ISSUE THREAD

**Issue by argosptr** [cheat-engine/cheat-engine#1308]
I need a modified 64 bit version to use dbvm.
Successfully compiled 32bit version of CE 7.1 with lazarus v2.0.1.0 64bit FPC 3.2.0
But, when I tried to compiled the 64bit version, got this error:

PEInfounit.pas(247,42) Error: identifier idents no member "BaseOfData"
PEInfounit.pas(449,91) Error: identifier idents no member "BaseOfData"
PEInfounit.pas(453,108) Error: identifier idents no member "BaseOfData"

Please help!

**Comment by mdouchement** [comment]
Got the same error with
```
lazarus-2.0.10-fpc-3.2.0-win64.exe
lazarus-2.0.10-fpc-3.2.0-cross-i386-win32-win64.exe
```

Then I tried with the one I used for compiling the CE7.0 and it compiles the CE7.1 too
```
lazarus-2.0.6-62131-fpc-3.2.0-beta-43271-win64.exe
lazarus-2.0.6-62131-fpc-3.2.0-beta-43271-cross-i386-win32-win64.exe
```

**Comment by mgrinzPlayer** [comment]
@argosptr Try the other way around, install 32bit Lazarus with 64bit add-on.

**Comment by argosptr** [comment]
> Be sure you are using updated CE source code.

@mgrinzPlayer Thanks it worked. Instead of the one in release section, I use the updated latest one.
