### ISSUE TITLE
one ceshare BUG.  When the cheatengine-x86_64.po - mainunit2.cename - "Cheat Engine 7.1" was changed to “123” other string,the three functions of the cehare will be invalid

### ISSUE THREAD

**Issue by HeiDaShuai666** [cheat-engine/cheat-engine#1313]
When the cheatengine-x86_64.po - mainunit2.cename - "Cheat Engine 7.1" was changed to “123” other string,the three functions of the cehare will be invalid.
![image](https://user-images.githubusercontent.com/42376695/90151020-d8d85a80-ddb8-11ea-9bb7-c39e7b5e8173.png)

Modify and save, then restart CE.
![image](https://user-images.githubusercontent.com/42376695/90151115-f7d6ec80-ddb8-11ea-9935-9516abfe6906.png)
Show "Server did not respond".When the translation file is "Cheat Engine 7.1", CE is used normally

**Comment by cheat-engine** [comment]
Just call it Cheat Engine.  It's a name,  it doesn't need a translation
