### ISSUE TITLE
Enabling mono while CE is currently debugging a thread freezes CE

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#1317]
On game break while CE is currently debugging, CE freezes when trying to enable mono. The freeze is infinite until I either kill CE or game process.

**Comment by cheat-engine** [comment]
Did you adjust your mono_timeout variable in monoscript.lua ?

**Comment by cheat-engine** [comment]
should be fixed now

**Comment by Symbai** [comment]
> as in, it's not going to work, but ce won't freeze

Cannot test it as I dont have Lazarus installed anymore. But yes, its fine if it doesn't work, it just shouldnt freeze CE.
