### ISSUE TITLE
Structure Dissect - Expand all pointers should expand pointers in child notes too

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#1328]
I'm searching for the new offsets of a pointer, pointing to my ammunition, which is in player class. Previously it was: `[[player+700]+2A0]+50`
I got the player base open in structure dissect. And I got the new address of my ammunition. What I now need is the pointers path from player to ammunition.

When I would be able to expand all pointers in player class twice (and the second time it expands pointers in child notes). I could simply hit CTRL+F and search for the ammunition address. However expanding all pointers only work once because it only expand the top level pointers.

**Comment by cheat-engine** [comment]
go to view->settings and set the max auto-expand level you like
1 is main structure
2 is main structure and all child structures
3 is main structure and all child structures and all their child structures...
