### ISSUE TITLE
ShellExecuteEx Failed, Access denied

### ISSUE THREAD

**Issue by lilcarrotcake** [cheat-engine/cheat-engine#1330]
Everytime i go to click on the installer it comes up with this error message

**Comment by benny215** [comment]
I get the same error when i tried to run it. Then when I run as administrator is changes to "windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item."

**Comment by Shchvova** [comment]
So... Any solutions to this?

**Comment by cheat-engine** [comment]
tell your anti virus to allow it

**Comment by Shchvova** [comment]
I don't have an antivirus. It's clean Windows 10 professional installation. I only installed Steam and tried to install Cheat Engine but it fails on installation with this errors.

**Comment by cheat-engine** [comment]
windows 10 defender is counted as an AV (crappy one) disable reputation based protection

**Comment by fade2gray** [comment]
@Shchvova 

> I don't have an antivirus

Not even Windows Defender?

**Comment by Shchvova** [comment]
![image](https://user-images.githubusercontent.com/130387/100550930-3e782600-3286-11eb-96ab-b0bb3cb0ebfc.png)
![image](https://user-images.githubusercontent.com/130387/100550936-4a63e800-3286-11eb-9d69-5888f519f5b8.png)

**Comment by Shchvova** [comment]
OK. Thanks for helping me out. For a while clicking around I found that windows blocked cheat engine based on reputation. It is in different section than antivirus
![image](https://user-images.githubusercontent.com/130387/100551004-b2b2c980-3286-11eb-98f3-affb5821cc46.png)
