### ISSUE TITLE
Cheat Engine not opening when I open or run as administrator

### ISSUE THREAD

**Issue by MangoHD** [cheat-engine/cheat-engine#1332]
Hi, I was trying to open Cheat Engine but it doesn't run. I checked task manager and it didn't show up either in the Background Processes or the other thing. I've read the Badlion Malware complaint and I don't really understand it well. I need help with this.
(Sorry for bad English)

**Comment by cheat-engine** [comment]
Uninstall badlion using their uninstaller  and restart windows (Not shut down and back on, actual restart)

**Comment by MangoHD** [comment]
I did that, and still it cant open.

**Comment by cheat-engine** [comment]
how did you restart windows? As you're still infected by badlion

**Comment by MangoHD** [comment]
I restarted windows with the normal way, start button, power, restart.
Not shut down then turn on again.
And yeah I think I'm still infected with Badlion.

**Comment by cheat-engine** [comment]
did you uninstall using the uninstaller that came with badlion or did you delete the files yourself?

**Comment by MangoHD** [comment]
I used the badlion uninstaller.

**Comment by cheat-engine** [comment]
execute this in a command prompt that is running with administrator privileges
```
sc delete BadlionAntic
sc delete BadlionAnticheat
shutdown /r
```

**Comment by MangoHD** [comment]
Thanks, I did exactly that and now it works!
I appreciate it.

**Comment by HeIp** [comment]
@cheat-engine you can close this
