### ISSUE TITLE
Need Help With Speedhack Problem.

### ISSUE THREAD

**Issue by mm132** [cheat-engine/cheat-engine#1334]
I use Cheat Engine for speeding up tasks in Disney's Magic Kingdoms and recently there has been an update and I need to be able to use this in order to get all of Pacha's (a character in the game) tokens.  Recently enable speedhack doesn't seem to work with this new update and I have tried going on the Cheat Engine forum and on Tenforums, please help.

**Comment by HeIp** [comment]
Game patched speed hack, not associated with software.

**Comment by mm132** [comment]
> Game patched speed hack, not associated with software.

I don't think that's the case though, since the hack was never detected.

**Comment by HeIp** [comment]
Your case is game related, this is not related to the program.

**Comment by mm132** [comment]
> Your case is game related, this is not related to the program.

I think contacting support should probably do the trick in that case.

**Comment by HeIp** [comment]
Support... for the game? You'd probably get banned for cheating...
