### ISSUE TITLE
Rescan type list is too small

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#1335]
I've downloaded the source code and compiled it and the rescan type list has become extremely small and now I need to scroll all the time. It should show all elements at once, there is enough space.

![image](https://user-images.githubusercontent.com/14368203/91656936-483e9180-eabd-11ea-903f-1d20ab4d06b6.png)

**Comment by cheat-engine** [comment]
Try a different version of lazarus. Lazarus svn revision 62129 does show it with the proper length

**Comment by Symbai** [comment]
I've installed the version which is linked in the build instructions: https://github.com/cheat-engine/cheat-engine#build-instructions if the version is buggy, could you please update it by providing the links to the correct version?

**Comment by mgrinzPlayer** [comment]
Lazarus 2.0.10 bug. Official Lazarus 2.0.8 doesn't have FPC3.2.0

**Comment by mgrinzPlayer** [comment]
I submitted this issue to the freepascal bug tracker:
https://bugs.freepascal.org/view.php?id=37670

It is related with this bug and changes they made here:
https://bugs.freepascal.org/view.php?id=37129

For Lazarus 2.0.10, you can replace file **win32wsstdctrls.pp** inside lcl\interfaces\win32

[win32wsstdctrls.zip](https://github.com/cheat-engine/cheat-engine/files/5151353/win32wsstdctrls.zip)

**Comment by mgrinzPlayer** [comment]
OK, I made more digging with other reporter _jamie philbrook_.

Instead of replacing the file with version with reverted changes (revision fixing bug 37129), you can just change one line.

Close Lazarus.
Open file from this location *pathToLazarus2.0.10\lcl\interfaces\win32\win32wsstdctrls.pp*

go to line number 996 and replace this line:
```Pascal
  if (CBS_SIMPLE and Params.flags) <> 0 Then
```

into this:
```Pascal
  if (Params.flags and CBS_DROPDOWNLIST) = CBS_SIMPLE Then
```

**Comment by Symbai** [comment]
> go to line number 996 and replace this line:

Confirmed, that fixed it.

**Comment by mgrinzPlayer** [comment]
Developer [wp](https://bugs.freepascal.org/view.php?id=37670#c125258) came with different, possibly better solution.

After line 1117 (win32wsstdctrls.pp from Lazarus 2.0.10):
```
SendMessage(ACustomComboBox.Handle, CB_SETMINVISIBLE, NewCount, 0);
```

add this:
```
if not (ACustomComboBox.Style in [csSimple, csDropDown, csOwnerDrawEditableFixed]) then
  RecreateWnd(ACustomCombobox);
```
