### ISSUE TITLE
Speedhack Issue.

### ISSUE THREAD

**Issue by mm132** [cheat-engine/cheat-engine#1338]
I thought I might as well as post a third issue, basically Enable Speedhack used to work with Magic Kingdoms but I cannot get it to work with the update and I really really really need it,  all it does is disable online mode and the time doesn't change, please help...I don't want to have to find another solution.
![Disney Magic Kingdoms 31_08_2020 2_51_34 PM](https://user-images.githubusercontent.com/42290332/91764041-b5236a00-ec2a-11ea-8f12-202a08055685.png)

**Comment by HeIp** [comment]
Sounds like the game found out the hack, and now prevents it. Doesn't sound like cheat engine itself broke.
This is not an issue to post here.

**Comment by mm132** [comment]
> Sounds like the game found out the hack, and now prevents it. Doesn't sound like cheat engine itself broke.
> This is not an issue to post here.
I tried the actual Cheat Machine forum but I didn't get any response.  Also for the record, it didn't have this problem before and it ran smoothly before and the 'hack' was never detected.
