### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by benni347** [cheat-engine/cheat-engine#1342]
Hello when i try to open the cheat engine 7.1 installer windows say acces denied what cou i do?

**Comment by Tiger-Tank** [comment]
same here

**Comment by cheat-engine** [comment]
disable windows defender

**Comment by ZenMasta** [comment]
Thanks! Just in case OP needs help. See this screenshot in windows 10.
![current-threats](https://user-images.githubusercontent.com/823528/93016886-41ae2080-f579-11ea-80f6-71074d1da19e.jpg)
