### ISSUE TITLE
taonga island

### ISSUE THREAD

**Issue by jonnyjonboy49** [cheat-engine/cheat-engine#1348]
Hi can anyone help , i cant get cheat engine to work on Taonga island !!

**Comment by AbdielSouza2005** [comment]
> Hi can anyone help , i cant get cheat engine to work on Taonga island !! 
> 

I dont't have this access either. I don't know what the problem is.

**Comment by AbdielSouza2005** [comment]
> Hi can anyone help , i cant get cheat engine to work on Taonga island !!

Can you delete your publication? I'm br and also new in Github.

**Comment by HeIp** [comment]
We do not give help here to cheat on games. This is only for programs with the program.

**Comment by SuperYi-chen2** [comment]
how do i cheat energy on Taonga island. Anyone can guide me step by step?
