### ISSUE TITLE
20H1 BSOD

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1349]
global debug on
f5 find read /write out  
f6 write breakpoint

19H1?,19H2?  20H1 OS -> BSOD

If F5&f6 debug breakpoint in 20H1(19041) version,
Computer reboots with pagefalut error

///////////////////////////////////////////

Even when global debug is off, the computer bsod

It seems to be a problem due to recent debug source and DBVM modification

ept break point -> No bsod
nomal break point -> bsod

exe :ce 7.2 Commits on Sep 9, 2020
sys :Commits on Sep 2, 2020
dbvm:Commits on Sep 7, 2020

///////////////////////////
cheat engine 7.0 -> BSOD
cheat engine 7.1 -> BSOD
cheat engine 7.2 -> BSOD

I recently updated to 20H1

20H1 seems to be unable to debug bsod
(EPT debug works)

**Comment by cheat-engine** [comment]
Are you sure you didn't add any new dbgprint's to the driver ?

**Comment by kitty8904** [comment]
> Are you sure you didn't add any new dbgprint's to the driver ?

1. dbgprint off
DBKFunc.h
#define DbgPrint(...)

2.global debug off

3.Tutorial-x86_64.exe step 2 100 hit value -> f5 break point -> 5~20 repeat -> bsod

**Comment by cheat-engine** [comment]
what is the CR3 value of thew target process?  After opening the process, rightclick on the processname

**Comment by kitty8904** [comment]
<img width="518" alt="777" src="https://user-images.githubusercontent.com/18622105/92602316-f4b41b00-f2e8-11ea-9483-691debc985d7.png">

CR3 AF7ED000

I just installed the latest version while format

If it doesn't work, I'm thinking of going back to the previous window

**Comment by cheat-engine** [comment]
I updated my testsystem to windows version 2004 (19041.508)
Without global debug: OK
With global debug: OK

**Comment by kitty8904** [comment]
i9 9900k
19041.508

debug option
override check
stack size 4096
use global debug check(on)
ability to step check(on)

f5~f6 repeat Tutorial-x86_64 breakpoint hit record (100value->0) -> BSOD

Should I install the English version of Windows?

I don't know why it doesn't work

EPT works normally

**Comment by cheat-engine** [comment]
Are you sure you have compiled the latest version of the driver and are using it?
First unload the old driver, delete it, burn it, make sure it's gone.
Reboot windows after deleting just to be sure

Then build the driver from the source

**Comment by kitty8904** [comment]
[7.2.zip](https://github.com/cheat-engine/cheat-engine/files/5198386/7.2.zip)

file only new source compile

But bsod

I am currently trying to download and test the English Windows version.

**Comment by cheat-engine** [comment]
Instead of "release without sig" , see of the "debug" version works

**Comment by kitty8904** [comment]
Attached file was compiled with debug build

//#ifdef RELEASE
#define DbgPrint(...)
//#endif

remove dbgprint only and original driver source

**Comment by cheat-engine** [comment]
There is no need to change any code (or add any code) just set the "Configuration" field to "Debug" and "Platform" to x64
Perhaps set some sign options for that config mode like testsign and then try with that.

The way the code is in github works, including the DbgPrint at the points that they currently are located

**Comment by kitty8904** [comment]
<img width="720" alt="7777" src="https://user-images.githubusercontent.com/18622105/92667386-c06f4780-f346-11ea-8a97-1f5838778db6.png">

Debug build, 64-bit nothing modified

But it stops on hitting the breakpoint recore(repeat)

Unknown cause
