### ISSUE TITLE
It does not run Cheat engine and it does not say any error

### ISSUE THREAD

**Issue by hanjud** [cheat-engine/cheat-engine#1371]
as I said in the title I can't run CE I don't have badlion I uninstalled it from the control panel and the file called BadLionAntycheat.sys is missing
postscript help

**Comment by cheat-engine** [comment]
Are you sure it's not in c:\windows\system32\drivers\BadlionAntiCheat.sys ?
Or do you have malwarebytes or other anti virus?

Anyhow, do a `driverquery /v >bla.txt` and upload the generated bla.txt file here so we can see what else it can be

**Comment by hanjud** [comment]
sorry, but i don't know how to do that

**Comment by cheat-engine** [comment]
press winkey+r
type in `cmd` in the run window
press ok

note down the path it shows in the prompt.  e.g: `c:\users\hanjud>`

type in `driverquery /v >bla.txt`
when it's done you will have a file called bla.txt in the location where you executed it.  (e.g `c:\users\hanjud`)
upload that file here

**Comment by hanjud** [comment]
[bla.txt](https://github.com/cheat-engine/cheat-engine/files/5319320/bla.txt)

**Comment by cheat-engine** [comment]
you are still infected by badlion
`BadlionAntic BadlionAnticheat       BadlionAnticheat       Kernel        System         Running    OK         TRUE                 FALSE            4.096                   3.813.376      0           26-05-2020 8:58:48     \??\C:\WINDOWS\system32\drivers\BadlionAnticheat 4.096       `

try doing a `shutdown /r` inside a command prompt

**Comment by hanjud** [comment]
ok I'll see if it works

**Comment by hanjud** [comment]
it didn't work

**Comment by hanjud** [comment]
what do I do now

**Comment by cheat-engine** [comment]
Easiest is ask badlion to help you, or report it to an anti virus company. Perhaps they can write a tool to disinfect you

Alternatively, find the command prompt in the start menu,  rightclick it and choose "Run as administrator" or equivalent in your language

then execute this code
```
net stop BadlionAntic
net stop BadlionAnticheat
sc delete BadlionAntic
sc delete BadlionAnticheat
shutdown /r
```

**Comment by hanjud** [comment]
IT WORKS SO MUCH THANKS!
