### ISSUE TITLE
ultimap2 can't work on somewindows version?

### ISSUE THREAD

**Issue by BlackLuny** [cheat-engine/cheat-engine#1373]
I am using ultimap2 on windows 10 1909 (18363.1110), and ultimap2 can't work.Machine is surface pro6 with i5 8250U, Ultimap2 works fine in the last year.But now maybe due to the windows update.
Now it only generated a very smalle size trace winipt packets in "d:\lotsofspace".And filted by "Code has been executed" results no result.It seems Pt config is ok,But can't generate any effect result?
CE version: 7.1
settings: usermode; process data later; Don't delete trace files; Do not trigger interrupts when full;

**Comment by cheat-engine** [comment]
In settings->debug options, see if there is a button right of the kerneldebugger.  Does it have the text "Make possible" ?  If so, click it and restart windows.  Else it's possible ultimap2 can only filter out kernelmode ranges and not the usermode ranges. 
Spectre protection causes non-admin processes to get split up into 2 memory ranges. One for the usermode part, and one for kernelmode.  When CE gets the memory region identifier, it gets the kernelmode region one

**Comment by BlackLuny** [comment]
It works now after disable Spectre protection.But I don't know why. I think may be the PT write to another physical address?

**Comment by cheat-engine** [comment]
as i said, with spectre protection enabled a process exists as 2 processes
process1: usermode memory and a little stub for kernel calls which switch to process2
process 2: usermode memory and kernelmode memory

when the program executes usermode,  it's in process1, but when CE gets the process it gets process2 
PT uses that process identifier to only record when in the correct process

**Comment by BlackLuny** [comment]
Thanks！Because the usermode cr3 is not the cr3 set for PT！So most of the usermode packet will not record！
