### ISSUE TITLE
Does the CE change the  hypervisor bit？

### ISSUE THREAD

**Issue by lyciumlee** [cheat-engine/cheat-engine#1376]
is dbvm a hypervisor？If it is a hypervisor，when I use cpuid instruction，I can not get the hypervisor bit.(eax=1, cpuid) the ecx contain the hypervisor bit equaling 0. I think the source should contain the operation, but I can not find it. Where is it?

**Comment by cheat-engine** [comment]
dbvm is a hypervisor yes but it does not set that bit

If you want that bit to be set you'll have to do that yourself. You can register a dbvm extension that hooks dbvm's cpuid handler and then modify the result (like setting that bit)
or edit it in ce's sourcecode

**Comment by lyciumlee** [comment]
I  have got it. Thanks, I just want to learn some program skills from Cheat engine source code. the source code is too long. I do not find the cheat engine hook cpuid result. So I am confused about it. By the way, Cheat engine is a very fantastic tool!
