### ISSUE TITLE
i can't open Cheat Engine 

### ISSUE THREAD

**Issue by XiEndST** [cheat-engine/cheat-engine#1380]
i cannot open cheat engine 7.1. when i start it, nothing happens. i have tried everything the cheat engine forums told me to do. nothing helped. please help me.

**Comment by XiEndST** [comment]
behold 
[bla.txt](https://github.com/cheat-engine/cheat-engine/files/5396900/bla.txt)

**Comment by cheat-engine** [comment]
Does the installer work?

**Comment by XiEndST** [comment]
Windows
Defender is off, no ad blocker!

**Comment by XiEndST** [comment]
found ad blocker removed and everything works thanks!)

**Comment by XiEndST** [comment]
everything is working!)
