### ISSUE TITLE
Compiling DBK with self-signed Certificate

### ISSUE THREAD

**Issue by MPNull** [cheat-engine/cheat-engine#1382]
Wiki lacks a lot of information about a compilation of DBKKernel and usage of DBVM bootdisk/EFI disk.

**Shouldn't I be able to sign DBKKernel with a self-signed Certificate?**

I'm on Windows 10 Test Mode and I'm trying to compile DBKKernel, but it says that:
`EXEC : SignTool error : No certificates were found that met all the given criteria.`

I have selected a "Create Test Certificate" in Signing options on x64 - Release. I'm not complete sure should unsigned DBKKernel version work with a self-compiled version of Cheat Engine but the self-compiled version says that DBVM is not supported because it is already in a VM.

Without signing I get successful results when compiling DBKKernel but I'm not sure should it work with my Cheat Engine. At least my Cheat Engine says that we're already in VM. What might be the issue?

**Comment by cheat-engine** [comment]
use the release-nosig or debug to build DBK else the driver will refuse to listen if CE has been edited

You do have to turn off signing or testsign with your own testsign certificate


As for DBVM efi disk, look into REFIND and build the dbvm efi image .  Then boot up refind, let it load DBVM and when it returns back tobrefind start your OS

**Comment by MPNull** [comment]
> use the release-nosig or debug to build DBK else the driver will refuse to listen if CE has been edited
> 
> You do have to turn off signing or testsign with your own testsign certificate
> 
> As for DBVM efi disk, look into REFIND and build the dbvm efi image . Then boot up refind, let it load DBVM and when it returns back tobrefind start your OS

Thank you for your response. According to your reply I can make the assumption that the driver and Cheat Engine should work together without signing in Test Mode.

About DBVM. If I compile Cheat Engine by myself and driver without signature I do get a message in DBVM "menu" that my OS is running already in VM. I know you catch what I mean. If I open your release it shows DBVM is supported and I can enable it without problems. (dbk64.sys) was moved into the same folder.

About the disk, I don't get it where I should find the image from but I will try to figure it out soon.
