### ISSUE TITLE
[Question]How can i change XMM value?

### ISSUE THREAD

**Issue by CRC32EX** [cheat-engine/cheat-engine#1389]
# What I want to do
```txt
144F984C0 - F3 0F10 3D E0EC4202   - movss xmm7,[1473C71A8] { [0.01] }
144F984C8 - F3 0F59 F7            - mulss xmm6,xmm7
```

`xmm7` is enemy HP multiplier.
So, set `0.0` means, enemy die immediately.
It was already tested and working by manual breakpoint.

I want change `xmm7` value to `0.0` automatically, using Lua script.

# Question
How can i change `xmm7` value?
I wrote this code but enemy do not die.

```lua
addressOfEnemyHPMultiplier = 0x144F984C8

function debugger_onBreakpoint()
  if (RIP == addressOfEnemyHPMultiplier) then
    debug_getContext(true)
    print(byteTableToFloat(XMM7))
    x = floatToByteTable(0.0)
    XMM7[1] = x[1]
    XMM7[2] = x[2]
    XMM7[3] = x[3]
    XMM7[4] = x[4]

    debug_setContext(true)
    print(byteTableToFloat(XMM7))
  end
  return 1
end

debug_setBreakpoint(addressOfEnemyHPMultiplier)
```

<b>Output</b>
```txt
0.0099999997764826
0.0
```

# Environment
|||
|:--|:--|
|OS|Windows 10 Pro 1903 64bit|
|CheatEngine|Version 7.1|
|DBVM|enabled|
|Target game|64bit Game|

# Reference
- https://forum.cheatengine.org/viewtopic.php?t=614531&sid=ba07194a0ef1eb3c77fe0e3b30530985

**Comment by cheat-engine** [comment]
That should work. But perhaps enemies don't die at 0 health, but at <0 health
try ```x = floatToByteTable(-0.1)```

**Comment by CRC32EX** [comment]
I'm sorry, it's my fault.
The game updated silently...
When i set breakpoint correct address, successfully working.
