### ISSUE TITLE
amd cpu tsc hook bsod

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1393]
dbvm_enableTSCHook()

dbvm_enableTSCHook function doesn't work on amd cpu Will it be patched in the future?

/////////////////////////////////////////////////////////////////////
//20H2 break point bsod//

Global debugging f5 or f6 break point not working in 20H2(bsod)
(page fault in nonpaged area)

nomal global debug break point -> not work bsod
ept break point -> work

test cpu :: intel 9900k or amd 3200

**Comment by cheat-engine** [comment]
Did you unload the old driver before installing 7.2?

**Comment by kitty8904** [comment]
> Did you unload the old driver before installing 7.2?

yes test 7.2 version(dbvm new version , dbk newversion , lua new version , cheat engine rc2 -> new version change)

page fault in nonpaged area message blue screen

**Comment by cheat-engine** [comment]
upload the memory.dmp somewhere and i'll check it out

**Comment by kitty8904** [comment]
https://www.dropbox.com/s/q0zs6z3ybdx1f4z/DUMP.zip?dl=0

**Comment by kitty8904** [comment]
> https://www.dropbox.com/s/q0zs6z3ybdx1f4z/DUMP.zip?dl=0

dbgprint remove sys file test dump2

->https://www.dropbox.com/s/mob01ix2w94tfpg/dump2.zip?dl=0

**Comment by cheat-engine** [comment]
This is a custom compiled driver. You'll also have to upload the sourcecode and the .PDB somewhere

**Comment by kitty8904** [comment]
[DBK64.zip](https://github.com/cheat-engine/cheat-engine/files/5474138/DBK64.zip)
[DBKKernel.zip](https://github.com/cheat-engine/cheat-engine/files/5474139/DBKKernel.zip)

dbk64.pdb + dbkkernel source => dump2.zip file

**Comment by cheat-engine** [comment]
You seem to be crashing on IoCompleteRequest but I'm not sure why that'd happen in relation to debugging

**Comment by kitty8904** [comment]
amd windows 1809 version no bsod crash(vmware test)

19H1~20H2 meltdown spectre other patch?

https://answers.microsoft.com/en-us/windows/forum/all/how-do-i-disable-all-the-spectre-and-meltdown/100daa1f-39b3-4d9c-904f-f62e1c8df26b

2 things are disabled by the registry

Another meltdown protection?

There seems to be a debugging problem starting from 19H1
(tested with vmware)

In some cases, win32kbase.sys is a crash sys file on a blue screen(f5 debug bsod)

**Comment by jewfuck** [comment]
holy fuck this skid still helping for spoonfeed

**Comment by jewfuck** [comment]
asians have small brain

**Comment by kitty8904** [comment]
You need to attach to process in session that has win32k in address space

Sometimes the blue screen is win32k.sys

And when I look up on Google, the session causes a blue screen

Could this be the cause?

Currently, the best I know is to use a version earlier than Windows 1809
