### ISSUE TITLE
cheat engine 7.2 setup not support dbvm

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1398]
![7 2](https://user-images.githubusercontent.com/18622105/98040994-9462d500-1e64-11eb-9f1c-680034a97b0f.png)

The released version 7.2 has dbvm disabled (amd cpu)

Was it disabled for modification?

**Comment by cheat-engine** [comment]
You may be running inside a virtual machine already, or have disabled SVM in bios

**Comment by kitty8904** [comment]
https://cheatengine.org/download/CheatEngine7.2_MissingSetup.rar

test pc no vmware , enable svm bios 

CheatEngine7.2_MissingSetup.rar -> error

cheat engine source build -> no error

i dont' know error

**Comment by cheat-engine** [comment]
Execute this code:
```lua
c=cpuid(0x80000001).ECX

printf("CPUID80000001_ECX=%8x", c)

if (c & (1<<2))~=0 then
  print("It should work")
else
  print("This is why it won't work")
end
```

**Comment by kitty8904** [comment]
SSE4-AVX2 support file -> dbvm check error

nomal ce file -> dbvm check not error

**Comment by cheat-engine** [comment]
Are you sure it's not your anti virus?  It's possible you've whitelisted cheatengine-x86_64.exe, but not cheatengine-SSE4-AVX2.exe

Is this the result of the AVX2 version ?

**Comment by kitty8904** [comment]
antivirus disable 

![error](https://user-images.githubusercontent.com/18622105/98042997-db9e9500-1e67-11eb-8502-544cd5b11392.png)

left cheatengine-x86_64.exe
right cheatengine-x86_64-SSE4-AVX2.exe

**Comment by cheat-engine** [comment]
so `CPUID80000001_ECX=35c233ff` came from the avx version ?

**Comment by kitty8904** [comment]
cheatengine-x86_64.exe 

CPUID80000001_ECX=35c233ff 
It should work 

cheatengine-x86_64-SSE4-AVX2.exe

CPUID80000001_ECX=35c233ff 
It should work

**Comment by kitty8904** [comment]
cheatengine-i386 .exe -> error -> DBVMFORAMDISWORKING 32bit release 32 define add
