### ISSUE TITLE
7.2 DBVM Debugger BSOD on conditional hwbp

### ISSUE THREAD

**Issue by skiddyfree** [cheat-engine/cheat-engine#1399]
This always happens to me.

Intel CPU, 2004(19041.572)

Condition itself is very simple, RAX == 0x1234.

All extra options are enabled including process watcher.
also using Global Debug routines since anti-debug routines watchs for DRx registers.

**Comment by skiddyfree** [comment]
using -SSE4-AVX2 build btw.

**Comment by skiddyfree** [comment]
I can confirm CE with kernel debugger is extreamly unstable at least on 2004.

Mostly, it returns Nonpaged BSOD error on win32kfull.sys on continued debugging (Ex. Quickly resuming program after BP triggered, or just randomly.

But still, it also returns Nonpaged BSOD error at DBK64.sys too on that conditional BP, on program exit etc.

**Comment by cheat-engine** [comment]
Try windows version 19xx or earlier.  Windows  20xx has some anti debugging code here and there (especially if glibal debug is used)

alternatively, limit to EPT based things like DBVM breakpoints and DBVM find what writes/access

**Comment by skiddyfree** [comment]
> 
> 
> Try windows version 19xx or earlier. Windows 20xx has some anti debugging code here and there (especially if global debug is used)
> 
> alternatively, limit to EPT based things like DBVM breakpoints and DBVM find what writes/access

Yeah bit expected. thanks for replying.
Also, EPT Based thigns still crashes shits (at least DBVM tracing doesnt crashes but BP does)

**Comment by skiddyfree** [comment]
alright, reporting some more thigns.
-1909 With DBVM BP(Conditional) doesnt works at all. it just BP ignoring condition.
-DBVM BP is highly unstable. after some quick resuming it BSOD with CLOCK_WATCHDOG_TIMEOUT.

**Comment by skiddyfree** [comment]
Guess its time to use W7 with VMware?

**Comment by kitty8904** [comment]
win 1809 or down ver not bsod 
19h1-20h2 bsod
My Computer works on versions below 1809

**Comment by cheat-engine** [comment]
Does it bsod without global debug or only with?

And is stepping through kernelmode code enabled? Because you should never check that one

**Comment by kitty8904** [comment]
Blue screen occurs in 19H1 or higher like skiddyfree.

My computer EPT is working fine

i don't know mainboard has a POST hex display

global debug is off -> bsod(page falut blue screen)
global debug is on -> bsod(page falut blue screen)
ept break point -> not bsod

**Comment by skiddyfree** [comment]
> win 1809 or down ver not bsod

Hey, Thanks for info!

**Comment by skiddyfree** [comment]
> Does it bsod without global debug or only with?
I tested only with global debug since it constantly checks DRx registers. if you want me to test that, i'll do it.

> And is stepping through kernelmode code enabled? Because you should never check that one
No, i didnt. Since target that im looking at is doing jobs in R3 mainly.
so i dont need to analyze any complicated syscalls etc.

> And if your mainboard has a POST hex display, what is the value shown during a freeze/clock_watchdog_timeout ?
Im not sure what does this means. my mainboard doesnt displays HEX value.(I have another one that does tho)
you mean after the BSOD?

**Comment by skiddyfree** [comment]
i can confirm every features works on 1809.

Closing issue since its, well, internal issues that can't be solved that quick :>
