### ISSUE TITLE
How i can use buildsigs.bat?

### ISSUE THREAD

**Issue by ZikesGT** [cheat-engine/cheat-engine#1401]
i just open it but doesn't build the Cheat Engine.exe  , i want make it auto like the released one

**Comment by ZikesGT** [comment]
![image](https://user-images.githubusercontent.com/54455705/98364730-e45bba80-2063-11eb-901f-b43a8901b898.png)
i did build this things..

**Comment by ZikesGT** [comment]
![image](https://user-images.githubusercontent.com/54455705/98364874-1f5dee00-2064-11eb-94a7-803c28a8c31b.png)
but i want make it like this..

**Comment by cheat-engine** [comment]
You can't make like the released one, but you can compile it in debug mode and release-nosig mode.  You don't need a .sig then

**Comment by ZikesGT** [comment]
how i can make the "Cheat Engine.exe" sir?

**Comment by ZikesGT** [comment]
![image](https://user-images.githubusercontent.com/54455705/98365325-d3f80f80-2064-11eb-9984-2390aec4cc2a.png)
oh this one ,.. thanks for reply sir!..
