### ISSUE TITLE
View Changed Values in Dissect Structure | Question

### ISSUE THREAD

**Issue by HeIp** [cheat-engine/cheat-engine#1404]
Hello I was wondering if there is a way to view the new values changed in dissect structure when it is open?
For example
![image](https://user-images.githubusercontent.com/31706214/98456228-01b68480-2149-11eb-966f-e16d6294ff2a.png)
let's say these are my current values for a structure, and I do something In game. 
Would there be a way to view changes in real time?

**Comment by cheat-engine** [comment]
add the address a 2nd time, and then rightclick one of them and choose "lock"
The lines that shows in different colors have been changed

**Comment by HeIp** [comment]
Is there a plugin to make the process easier or more intuitive ? 
Not that I didn't like your answer, very smart thinking about it
