### ISSUE TITLE
CE 7.2 - Focus is no longer on STOP button by default

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#1405]
The focus for "Find out what" windows is no longer on STOP button by default. In CE 7.1 and earlier we could immediately hit the space key to stop the breakpoint. This is necessary on some multithreaded functions where lots of adresses are running through, CE debugger can cause a crash if its too slow.

Now in CE 7.2 you added the code address textbox at the top, this takes the default focus now.

**Comment by skiddyfree** [comment]
Seriously? you opens this as "Issue"?

**Comment by Symbai** [comment]
Dude, what is your problem that you need to comment other people issues with your nonsense? Just ignore it like everyone else, move along and have a nice life. Author (Dark Byte) can close the issue if its an invalid issue.

But if you just need a hug and some attention, here is it ❤🤗 Let me know whenever you feel lonely again.
