### ISSUE TITLE
CE 7.2 dbvm for amd not working

### ISSUE THREAD

**Issue by HeIp** [cheat-engine/cheat-engine#1408]
Hello Just here to say that dbvm doesn't work for me. And using amd cpu.
![image](https://user-images.githubusercontent.com/31706214/98621350-1031a700-22d5-11eb-9d64-fcfc7d228b19.png)
![image](https://user-images.githubusercontent.com/31706214/98621365-14f65b00-22d5-11eb-8d28-a6e39c01efad.png)

**Comment by kitty8904** [comment]
If the process list is cheatengine-x86_64-SSE4-AVX2.exe, it will not work

Run the cheatengine-x86_64.exe file in the cheat engine folder

**Comment by HeIp** [comment]
Same status/result

**Comment by cheat-engine** [comment]
if you are using the x86_64 and not the AVX2 build, then make sure core isolation is disabled in windows, and you're not running windows inside a VM, like avira

**Comment by HeIp** [comment]
![image](https://user-images.githubusercontent.com/31706214/98704978-3e51ce00-234b-11eb-9255-35ec07fbe2e1.png)
is this showing core isolation disabled ?

**Comment by cheat-engine** [comment]
check your AV if you're in a VM or not. (as I said, avira does that)

Also, run this lua code
```lua
local cpuid0=cpuid(0)
local cpuid1=cpuid(1)

s1=byteTableToString(dwordToByteTable(cpuid0.EBX))
s2=byteTableToString(dwordToByteTable(cpuid0.EDX))
s3=byteTableToString(dwordToByteTable(cpuid0.ECX))

s=s1..s2..s3

if s=='AuthenticAMD' then
  print("AMD")
  local cpuid80000001=cpuid(0x80000001)
  if (cpuid80000001.ECX & (1<<2))~=0 then
    print("dbvm should work")
  else
    print(string.format("dbvm can not work. no SVM.  cpuid1.ECX=%.8x cpuid80000001.ECX=%.8x",cpuid1.ECX, cpuid80000001.ECX ))
  end

elseif s=='GenuineIntel' then
  print("Intel")

  if (cpuid1.ECX & (1<<5))~=0 then
    print("dbvm should work")
  else
    print(string.format("dbvm can not work. no VT.  cpuid1.ECX=%.8x",cpuid1.ECX))
  end

else
  print("unsupported CPU:"..s)
end
```
and tell us the results

**Comment by HeIp** [comment]
Only have windows defender, no avira AV.
Output
`AMD 
dbvm can not work. no SVM.  cpuid1.ECX=fed83203 cpuid80000001.ECX=004023f3 
`

**Comment by kitty8904** [comment]
Check if booting motherboard cpu SVM is ON

https://youtu.be/qKIcbKNI-g0

**Comment by HeIp** [comment]
![image](https://user-images.githubusercontent.com/31706214/98722969-bc1fd480-235f-11eb-9d58-cd48726d7a0d.png)
![image](https://user-images.githubusercontent.com/31706214/98722997-c510a600-235f-11eb-83a2-e48ef5972887.png)

**Comment by cheat-engine** [comment]
cpuid1.ecx has bit 31 set to 1 which vm vendors have agreed on is a flag to indicate a virtual machine

this means you are already inside a virtual machine. 
Find a way to exit that state. (perhaps it's a bios setting for expra security)

**Comment by HeIp** [comment]
Not sure how to do that. 
Might be related, might not be.: I have some vm's and work with docker but none are running.

**Comment by kitty8904** [comment]
https://docs.microsoft.com/en-us/troubleshoot/windows-client/application-management/virtualization-apps-not-work-with-hyper-v

hyper-v running check

**Comment by HeIp** [comment]
@kitty8904 Method 1 was disabled when I checked.
Method 2 did nothing even when running that command and powershell as admin.
Performed the following In Method 3 :
1)From the Group Policy Management Console, go to Computer Configuration -> Administrative Templates -> System -> Device Guard.
2)Double-click Turn On Virtualization Based Security, and then click the Enabled option.

**Comment by kitty8904** [comment]
Last is to format your computer

I don't know which virtualization program is causing the problem

Or test Windows installation on a new hard disk

**Comment by HeIp** [comment]
I believe it is a program. As not to long ago CE said it supported dbvm for me

**Comment by dustinlieu** [comment]
@HeIp Run `bcdedit /set hypervisorlaunchtype off` to disable hypervisor

**Comment by HeIp** [comment]
@dustinlieu with restart?

**Comment by vyshky** [comment]
Your problem was in docker, I also faced this problem. You need to disable
containers, hyper-v, sandbox windows,windows subsystem for linux. 

Sorry, I have it all in another language and maybe I translated it incorrectly into English.
