### ISSUE TITLE
 Cheat Engine not starting

### ISSUE THREAD

**Issue by babyxclayzen** [cheat-engine/cheat-engine#1409]
I recently downloaded this software, everything was fine and everything started, but a couple of hours ago, when I tried to start it, nothing worked.

CE version - 7.2
64bit windows7

**Comment by cheat-engine** [comment]
Have you ever touched a program called "badlion" ?

**Comment by babyxclayzen** [comment]
No, but I only have Badlion Client - Minecraft Launcher.
This program works like a roulette for me. Launches today - not tomorrow (Google Translator)

**Comment by cheat-engine** [comment]
uninstall the badlion client and anti cheat and restart windows

**Comment by babyxclayzen** [comment]
> uninstall the badlion client and anti cheat and restart windows

How? Badlion Client - this famous Minecraft launcher.

**Comment by cheat-engine** [comment]
https://github.com/cheat-engine/cheat-engine/issues/1310

**Comment by babyxclayzen** [comment]
> #1310

thank u, now I will install another launcher
