### ISSUE TITLE
CE 7.2 DBVM won't work due to kernel module

### ISSUE THREAD

**Issue by dustinlieu** [cheat-engine/cheat-engine#1412]
I'm trying to use DBVM on an AMD CPU.

When I go to the about menu it says "Your system supports DBVM", but when I click on it it says "The driver couldn't be opened! It's not loaded or not responding. I recommend to reboot your system and try again".

These are the things I checked:
1. Windows is not running on a hypervisor. I ran "(gcim Win32_ComputerSystem).HypervisorPresent" in PowerShell and it returned False
2. I ran the Lua script from issue #1408 to make sure that DBVM can run. It returned "AMD dbvm should work".
3. Hyper-V is disabled
4. Windows Subsystem for Linux is disabled
5. AMD SVM is enabled in the BIOS
6. I am running cheatengine-x86_64.exe and it has a valid signature (downloaded from https://cheatengine.org/)
7. Core isolation is disabled
8. I don't have any anti virus software other than one built into Windows. I tried disabling it and DBVM still doesn't work.
9. Secure boot is disabled
10. This is a recent fresh install of Windows 10 (about 7 days old) and I haven't installed anything other than basic programs like web browser

I've tried to unload kernel module, uninstall, reboot, and reinstall but nothing works.

Any help would be appreciated. Thanks!

Specs:
AMD Ryzen 5 5600x
Windows 10 20H2 build 19042.572
Cheat Engine 7.2

Screenshots:
![](https://user-images.githubusercontent.com/18184165/99041191-52f6b780-253f-11eb-9701-80efd58aeffc.png)
![](https://user-images.githubusercontent.com/18184165/99040541-28582f00-253e-11eb-93ad-76f3c16f3f70.png)
![](https://user-images.githubusercontent.com/18184165/99040575-373ee180-253e-11eb-9cf3-06646a9b1b44.png)
![](https://user-images.githubusercontent.com/18184165/99041283-7b7eb180-253f-11eb-924a-66077a3d223c.png)
![](https://user-images.githubusercontent.com/18184165/99040807-a3214a00-253e-11eb-8306-fbfe73ce11eb.png)
![](https://user-images.githubusercontent.com/18184165/99040888-c77d2680-253e-11eb-8aa5-3b2c49ae8008.png)

**Comment by cheat-engine** [comment]
What folder did you install CE to ?
Is there a proper .sig file in the same folder ?

Try getting https://docs.microsoft.com/en-us/sysinternals/downloads/debugview and make it record kernel debug output (including verbose)

then load the driver/use the driver(settings->extra, or load ce when it's checked). There should be a part where it says :"CheckSignatureOfFile:"

Try running the kernelmodule unloader and then restart windows (not shut down and back on, actual restart)

Try running this command as admin
```secedit /configure /cfg %windir%\inf\defltbase.inf /db defltbase.sdb /verbose```  it should restore windows protections to default

**Comment by kitty8904** [comment]
temp:='\??\'+widestring(applicationpath)+'vmdisk.img';

WinCPToUTF8

in my opinion, dbvm.img cannot be loaded if the folder path is not English but Chinese, Korean, Japanese, etc.

etc)
‪C:\ce\vmdisk.img -> path load ok dbvm load
c:\日本フォルダ\vmdisk.img-> path load error not dbvm load
c:\中文文件夹\vmdisk.img -> path load error not dbvm load
c:\한국어폴더\vmdisk.img -> path load error not dbvm load

**Comment by HeIp** [comment]
Have you tried testing on folder path that is english ? Or placing it in root directory of C:\

**Comment by dustinlieu** [comment]
I fixed it by uninstalling Riot Games Vanguard (the anti-cheat kernel driver for Valorant).

**Comment by yslin** [comment]
I played "Ragnarok Online" protected by "nProtect GameGuard", then encounter the same error.
This command works fine.
Thanks a lot.

> Try running this command as admin `secedit /configure /cfg %windir%\inf\defltbase.inf /db defltbase.sdb /verbose` it should restore windows protections to default

**Comment by kingdone1** [comment]
> 我通过卸载 Riot Games Vanguard（Valorant 的反作弊内核驱动程序）来修复它。

what?Do you uninstall a program to start dbvm? Because I have the same problem, but unlike you I have an NVIDIA graphics card and I don't know what to do now

**Comment by XBOX360VERSUCHONE** [comment]
kingdone1 ***@***.***> schrieb am Sa., 15. Apr. 2023, 19:30:
