### ISSUE TITLE
CE 7.2 Cannot attach debugger

### ISSUE THREAD

**Issue by FMotalleb** [cheat-engine/cheat-engine#1413]
I used CE for a long time now I have an issue after updating to 7.2 it seems that cannot attach Debugger to some processes like Metro Exodus and when I used CE 7.1 it worked fine it won't show any errors just say it takes a while to attach debugger I waited for about 30mins and didn't work.
sry for my bad English if anyone knows where is the issue plz help me or fix this problem

**Comment by crest1993** [comment]
i have the same issues, i think it’s because CE failed to load symbol so it takes forever. Happens only with 7.2 version

**Comment by cheat-engine** [comment]
check your antivirus.  It may be too busy looking at/blocking what CE does

**Comment by FMotalleb** [comment]
> check your antivirus. It may be too busy looking at/blocking what CE does

I have no AV at all and no protection of any kind just some monitoring tools and I am sure they won't  interrupt CE

**Comment by crest1993** [comment]
> check your antivirus. It may be too busy looking at/blocking what CE does

i have only windows defender, tried to add exclusion to folder and then process, still the same result. I even tried to turn it off completely, same. Is there any log file generated from this that i could provide maybe?

**Comment by cheat-engine** [comment]
dbgview from wininternals may show something

also,  try the tutorial. See if it works on there

and how did you install CE? Which installer did you use?  Patreon, public, github or .rar package?
If .rar package, did you add execute permission to all files in the ce folder for the app_user account? (has to be set specifically as it's not part of 'everyone')
If installer, did you block it access to icacls.exe ?

**Comment by FMotalleb** [comment]
sry for being late 
I installed CE from Github
and I think the issue cant be from somewhere else it's from CE 7.2 itself when CE 7.1 works fine

**Comment by Karlos007** [comment]
7.2 was a nice update but it's true that has now freezes when attaching to specific applications, in my case Ryujinx (written in C#).
Once attached appears a new "**.NET info**" menu, but clicking that or enabling any script hangs Cheat Engine (even if script is empty with just the template).
Search works fine, and memory viewer works (although it always shows "**Symbols are being loaded (0 %)**").

7.1 works fine.

In both cases I added Windows Defender Folder Exclusions and the .exe was from github precompiled releases.

**Comment by cheat-engine** [comment]
which debugger interface

**Comment by Karlos007** [comment]
At least for me the % is always 0 no matter how much you wait.
Using all 3 the same (VEH / windows / kernelmode).
I suppose it should happen on other computers too.
Anyone can try it with Ryujinx, doesn't require installation.
Just delete the downloaded folder and this AppData after use
C:\Users\\%UserName%\AppData\Roaming\Ryujinx

**Comment by cheat-engine** [comment]
works for me.
have you allowed the dotnetdatacollector to function uninhibited ?

**Comment by Karlos007** [comment]
Damm bro you are good,  thanks :)
installing **.NET 5.0 Runtime** did the trick, no need to reboot, just reopen CE 7.2.

Mind if I share the link, maybe it solves OP error.

https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.0-windows-x64-installer

**Comment by FMotalleb** [comment]
yeah it fixed mine too so I think its time to close this anyway tanks to 
@cheat-engine and @Karlos007 
I love CE and Assembly
