### ISSUE TITLE
CE 7.2 DBVM Kernel Mode AMD - Cannot Find Any Physical Address for any process

### ISSUE THREAD

**Issue by HeIp** [cheat-engine/cheat-engine#1414]
![image](https://user-images.githubusercontent.com/31706214/99099741-dbf60900-25a8-11eb-858e-eca3a452b2d2.png)
This is just one example I was testing on the tutorial

**Comment by cheat-engine** [comment]
Have you opened the process with kernelmode openprocess enabled?

**Comment by HeIp** [comment]
Yes

**Comment by cheat-engine** [comment]
what is the physical address shown in the hexview field if you display the address there?

**Comment by HeIp** [comment]
DBVM doesnt seem to function with amd at all, just crashes gave for any dbvm action.
