### ISSUE TITLE
amd cpu dbvm find out 32bit not result

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1421]
![32bit](https://user-images.githubusercontent.com/18622105/99637750-a2ca0700-2a88-11eb-8812-a8c730887b97.png)

test ce : cheat engine 7.2

target : tutorial-i386 .exe

dbvm find out access break point -> but address not result

target:: tutorial-x64.exe -> address result ok

Address value does not appear in case of 32-bit process target

**Comment by cheat-engine** [comment]
global debug on or off ?

**Comment by kitty8904** [comment]
global debug on

and 64bit target result ok

![64](https://user-images.githubusercontent.com/18622105/99638733-06086900-2a8a-11eb-95d5-72b42edd3117.png)

**Comment by cheat-engine** [comment]
Just to confirm, this is the "DBVM find out what writes or accesses this address" menu option, and NOT "find out what writes/access" menu options

for 32-bit, is the physical address filled in properly before starting ?

**Comment by kitty8904** [comment]
not f5 find out access

dbvm find out write or access button

![error](https://user-images.githubusercontent.com/18622105/99639617-2c7ad400-2a8b-11eb-90e4-9e0beffb8faf.png)

Physical address is no problem
