### ISSUE TITLE
luacall() always executed in AA ? Bug or feature ?

### ISSUE THREAD

**Issue by reaper790815** [cheat-engine/cheat-engine#1422]
Hi,

is this a bug or a feature ?

`[ENABLE]`
`{$lua}`
  `  if syntaxcheck then return end`
  `  print('Hello') -- is only printed if script is activated -> OK`
`{$asm}`
  `  luacall(print(type(syntaxcheck))) // is always executed and syntaxcheck is always nil`
`[DISABLE]`

Would be nice if you could check for "syntaxcheck" in a function called by luacall...

**Comment by reaper790815** [comment]
I tried some things, and came up with an idea....
Actually i dont know how to use github / forks etc. so i post it here.

if you change following in Cheat Engine Source Code:

autoassembler.pas:
LINE 1249 //s.add('local syntaxcheck,memrec=...');
LINE 1250 s.add('syntaxcheck,memrec=...');

I don't know if it breaks some other functions if you change the variable to global, but after new compiling and testing the script, you can check for syntaxcheck in luacall() called function...

**Comment by cheat-engine** [comment]
instead of that you can of course do
```
{$lua}
_G.syntaxcheck=syntaxcheck
{$asm}
```

**Comment by reaper790815** [comment]
Ok, thanks for the clarification, think this can be closed now.
