### ISSUE TITLE
driver wdk 7600 build error

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#143]
path contains nonexistant c:\winddk\7600.16385.1\tools\sdv\bin, removing
BUILD: Compile and Link for AMD64
BUILD: Start time: Thu Jan 12 15:02:05 2017
BUILD: Examining c:\users\administrator\desktop\cheat-engine-master\cheat-engine
-master\dbkkernel directory for files to compile.
    c:\users\administrator\desktop\cheat-engine-master\cheat-engine-master\dbkkI
nvalidating OACR warning log for 'root:amd64chk'
BUILD: Compiling and Linking c:\users\administrator\desktop\cheat-engine-master\
cheat-engine-master\dbkkernel directory
Configuring OACR for 'root:amd64chk' - <OACR on>
Assembling - amd64\dbkfunca.asm
Assembling - amd64\vmxhelpera.asm
Assembling - amd64\debuggera.asm
Assembling - amd64\vmxoffloada.asm
Assembling - amd64\ultimapa.asm
Assembling - amd64\noexceptionsa.asm
1>errors in directory c:\users\administrator\desktop\cheat-engine-master\cheat-e
ngine-master\dbkkernel
1>NMAKE : fatal error U1073: don't know how to make 'c:\users\administrator\desk
top\cheat-engine-master\cheat-engine-master\dbkkernel\objchk_win7_amd64\amd64\no
exceptions.obj'
1>nmake.exe /nologo BUILDMSG=Stop. -i BUILD_PASS=PASS2 LINKONLY=1 NOPASS0=1 MAKE
DIR_RELATIVE_TO_BASEDIR= failed - rc = 2

BUILD: Finish time: Thu Jan 12 15:02:05 2017
BUILD: Done

    6 files compiled - 2 Warnings - 2 Errors

error. Check the compile log

C:\Users\Administrator\Desktop\cheat-engine-master\cheat-engine-master\DBKKernel
>

1>NMAKE : fatal error U1073: don't know how to make 'c:\users\administrator\desk
top\cheat-engine-master\cheat-engine-master\dbkkernel\objchk_win7_amd64\amd64\no
exceptions.obj'
1>nmake.exe /nologo BUILDMSG=Stop. -i BUILD_PASS=PASS2 LINKONLY=1 NOPASS0=1 MAKE
DIR_RELATIVE_TO_BASEDIR= failed - rc = 2

windows7 x64 checked build Environment -> Ce.bat Run

noexcetion.asm build error why?

**Comment by kitty8904** [comment]
Looking at sources.ce, there are no files noexceptions.c noexceptions.h

**Comment by cheat-engine** [comment]
check if your sources.ce is up to date.
it should reference noexceptiona.asm not, noexception.asm

**Comment by cheat-engine** [comment]
should be fixed now. the repository was missing noexceptions.c/.h
