### ISSUE TITLE
Run on Mac with SIP?

### ISSUE THREAD

**Issue by Mila432** [cheat-engine/cheat-engine#1437]
Is it possible to run cheat engine on the latest M1 with SIP enabled ? I could disable SIP , but then it's not possible to run iOS apps. (https://forums.macrumors.com/threads/if-you-disable-sip-all-you-ios-apps-will-stop-working-on-your-m1.2269661/)

**Comment by cheat-engine** [comment]
Perhaps if you modify the target app to allow debugging

Or you could try hacking the iOS launcher on Mac to allow it after all (fake that SIP is enabled, or bypass encryption, or whatever else might work)
