### ISSUE TITLE
unsigned driver INTEGRITYCHECK & KernelView Error?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#144]
sources
LINK=/INTEGRITYCHECK -> LINKER_FLAGS=/integritycheck(LINK->LINKER_FLAGS fix?)

ces.bat set LINKER_FLAGS=/INTEGRITYCHECK -> ok(sign driver)

ce.bat  set LINKER_FLAGS=/INTEGRITYCHECK -> add(unsign driver)

KernelView Error?

![kernel](https://cloud.githubusercontent.com/assets/18622105/21889137/c4335bf4-d90a-11e6-88bc-6a9b630da2b2.png)

noexception delete Test(I did not have the code and I compiled it)
(Noexception.c. & noexception.h Delete and compiles)

**Comment by cheat-engine** [comment]
no idea, I tried looking around for a sources linker_flags parameter but couldn't find it. So I resorted to the .bat build.

Seems to work as well
