### ISSUE TITLE
in android ,ceserver can not enum all processes

### ISSUE THREAD

**Issue by frustreated** [cheat-engine/cheat-engine#1449]
for example ,we use ps to filter process as following:

```
adb>adb shell ps | findstr com.tencent.mm
u999_a145    10569   949 4892528  94772 SyS_epoll_wait 7aaec1ca54 S com.tencent.mm:push
u999_a145    10778   949 5250736 161644 SyS_epoll_wait 7aaec1ca54 S com.tencent.mm
u0_a145      27919   949 5125232 380256 SyS_epoll_wait 7aaec1ca54 S com.tencent.mm
u0_a145      28051   949 4725308 129376 SyS_epoll_wait 7aaec1ca54 S com.tencent.mm:push
u0_a145      28202   949 9367776 249336 SyS_epoll_wait 7aaec1ca54 S com.tencent.mm:appbrand0
u0_a145      28216   949 9031296 186724 SyS_epoll_wait 7aaec1ca54 S com.tencent.mm:appbrand1
u0_a145      28489   949 9106980 181040 SyS_epoll_wait 7aaec1ca54 S com.tencent.mm:tools
u0_a145      28707   949 5166912 245856 SyS_epoll_wait 7aaec1ca54 S com.tencent.mm:toolsmp
```

but in ce is as followings:
![image](https://user-images.githubusercontent.com/5463104/103507364-f1492e80-4e99-11eb-9fd5-cbabf0e7fd3d.png)

**Comment by frustreated** [comment]
process of Chrome is also cannot display ALL processes 
 etc as followings 
![image](https://user-images.githubusercontent.com/5463104/103519286-3a0be200-4eb0-11eb-8429-f43b3f3c28e2.png)

**Comment by cheat-engine** [comment]
rightclick and choose "enter pid manually"  See if that works

And is the process in /proc/#pid  ?

**Comment by frustreated** [comment]
> rightclick and choose "enter pid manually" See if that works
> 
> And is the process in /proc/#pid ?

tried , ce will crash the process

**Comment by frustreated** [comment]
> rightclick and choose "enter pid manually" See if that works
> 
> And is the process in /proc/#pid ?

sorry to have another ans and you are right!
bug the input processid mustbe hex num !!!
