### ISSUE TITLE
win7 darkmode view error

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1452]
<img width="502" alt="103106836-27a5d300-467c-11eb-8a4f-8c7a75824990" src="https://user-images.githubusercontent.com/18622105/103752893-9fe1a080-504d-11eb-851a-5934faa44a7b.png">

<img width="601" alt="103423938-03527500-4bed-11eb-8f62-0a485c36007c" src="https://user-images.githubusercontent.com/18622105/103752904-a5d78180-504d-11eb-84a5-ce3264257b0c.png">

<img width="596" alt="103418715-3daf1880-4bd3-11eb-88ce-231c4235b7d8" src="https://user-images.githubusercontent.com/18622105/103752914-a96b0880-504d-11eb-84d2-21e7d3d9e9f4.png">

1.windows7 darkmode icon view error
2.windows7 darkmode hint view error
3.font default setting error

**Comment by cheat-engine** [comment]
reset your registry for the font name.  the control likely can't draw your currently configured fontname
