### ISSUE TITLE
windows7 speedbutton error

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1453]
<img width="470" alt="dark" src="https://user-images.githubusercontent.com/18622105/104043746-9871f100-521f-11eb-9d2c-cf8dda35025f.png">

windows7 speedbutton View Error And Load Access violation Error

**Comment by cheat-engine** [comment]
what is the stacktrace?

**Comment by kitty8904** [comment]
cedebug.txt not create

cheat engine load table icon save table icon (speedbutton) click -> Access violation Error

**Comment by kitty8904** [comment]
[log.zip](https://github.com/cheat-engine/cheat-engine/files/5788860/log.zip)

I updated the log where the error occurred and ce

load table button click -> cedebug.text

**Comment by cheat-engine** [comment]
when you compile it also generated a .dbg file
add that as well when you run CE

**Comment by kitty8904** [comment]
I deleted dbg for fast compilation

The error log generated by addition is as follows.

|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

First log message: 2021-01-09
TAutoSizeCtrlData.FixControlProperties :TCECheckBox a=akTop old=:TEdit new=nil
Exception Access violation
  Stack trace:
  $0000000000410815
  $000000000092D334  SHOWMODAL,  line 995 of win32wsdialogs.pp
  $0000000000480C2A  DOEXECUTE,  line 152 of include/commondialog.inc
  $0000000000481C42  DOEXECUTE,  line 409 of include/filedialog.inc
  $00000000004807EB  EXECUTE,  line 41 of include/commondialog.inc
  $00000000004ABE13  ACTOPENEXECUTE,  line 8742 of MainUnit.pas
  $00000000007C0AFC
  $00000000008DC5D4  EXECUTE,  line 98 of include/containedaction.inc
  $00000000008DE45C  EXECUTE,  line 246 of include/customaction.inc
  $00000000007C089B
  $000000000043DD4D  CLICK,  line 2914 of include/control.inc
  $00000000007FB409  CLICK,  line 114 of include/speedbutton.inc
  $00000000007FD63A  WMLBUTTONUP,  line 978 of include/speedbutton.inc
  $0000000000410F81
  $000000000043C9DF  WNDPROC,  line 2241 of include/control.inc
  $000000000043B2A8  PERFORM,  line 1581 of include/control.inc
  $000000000042E803  ISCONTROLMOUSEMSG,  line 4755 of include/wincontrol.inc
