### ISSUE TITLE
2020 M1 MBA Cheat Engine 7.2 OSX issue

### ISSUE THREAD

**Issue by sneaky-nerd** [cheat-engine/cheat-engine#1458]
I'm using 2020 M1 MacBook Air(Big Sur 11.1). Cheat Engine requires to disable SIP(System Integrity Protection) to open a process. If I disable SIP, it doesn't let me open any iOS apps with an error message(cannot be opened because Security Policy is set to Permissive Security.) Is this something for apple's end and I just have to wait or any solution for this?

**Comment by cheat-engine** [comment]
Edit the ios launcher so it think sip is enabled

or don't use ios apps

**Comment by SGprooo** [comment]
And how exactly do you edit the iOS launcher?
I'm trying to debug an iOS application, and I have not heard of spoofing the iOS launcher.

**Comment by DuIslingr** [comment]
If you have a jailbroken device you can crack and dump iOS apps to then resign with appdb and use rickpactor to install them and they function with sip disabled. iOS apps don't run by default with sip disabled because it disables fairplay from working which uncracked apps need to run.
