### ISSUE TITLE
autoassemblercode 0x add?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1464]
case parameters[j].contextitem of  //todo: add 32-bit support 
      0: s:=s+'readPointer(readPointer(parameters+0x228))'; //RAX
      1..15: s:=s+'readPointer(parameters+0x'+inttohex($200+(parameters[j].contextitem-1)*8,1)+')'; //RBX..R15
      16: s:=s+'readFloat(readPointer(parameters+0x228))'; //RAX as float
      17..31: s:=s+'readFloat(parameters+0x'+inttohex($200+(parameters[j].contextitem-17)*8,1)+')'; //RBX..R15 as float
      32..47: s:=s+'readBytes(parameters+'+inttohex($a0+(parameters[j].contextitem-32)*16,1)+',16,true)';
      48..111: s:=s+'readFloat(parameters+'+inttohex($a0+(parameters[j].contextitem-48)*4,1)+')';
      112..143: s:=s+'readDouble(parameters+'+inttohex($a0+(parameters[j].contextitem-112)*8,1)+')';

32..47 parameters+ ----> parameters+0x Fix?
48.111 parameters+ ----> parameters+0x Fix?
112.143 parameters+ ----> parameters+0x Fix?

**Comment by cheat-engine** [comment]
yes
