### ISSUE TITLE
Application Is Not User friendly Even Though Its Been In Development For Years!

### ISSUE THREAD

**Issue by dr-NHA** [cheat-engine/cheat-engine#1472]
**Outdated And Worthless Application, This Only Gets Used For Unknown Value Scans But At A Cost Of 8+Gb Of Temp Storage Taken Up In The Temp Directory!
AoB's Break The Tool: If You Scan Or Change The Output Of An Array of Bytes Over 2k Cheat Engine Will Massively Fail And You Wont Be Able To Close Any Windows Without Force Closing The Whole Tool!

Aye I Have Been Using Cheat Engine For Years Now, But Im Slowly Replacing The Sluggish Tool**

**Comment by cheat-engine** [comment]
Yeah, CE isn't going to replace every start of a word with a capital.

**Comment by dr-NHA** [comment]
> Yeah, CE isn't going to replace every start of a word with a capital.

well my tool can and can do alot more without clogging shit up
