### ISSUE TITLE
vmware vmdisk img freeze

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1474]
![error0](https://user-images.githubusercontent.com/18622105/106337525-b38ec880-62d4-11eb-99c0-ad2c3ca9e2c3.png)
![error1](https://user-images.githubusercontent.com/18622105/106337526-b4bff580-62d4-11eb-94d0-d79f25fb1af1.png)
![error2](https://user-images.githubusercontent.com/18622105/106337527-b5588c00-62d4-11eb-9e31-a9a87685cb74.png)

Windows 10 20h2 vmware boot tried to load vmdisk.img

But it doesn't work at the Windows boot freeze

amd dbvm find out can't find address value in 32 bit process
(64bitprocess work,32bitprocess no result address)

Also, global debugging F5,F6 does not work with amd cpu in windows 1809 and later versions

Windows security update winver 1809 high version -> bsod (maybe)

/////////////////////////////////////////////////////////////

Intel CPU when there is an address that is countered 200 times per second during f5 global debugging bsod
(is this still impossible to solve?)

I remember that it was difficult because I had to completely change the debug interface

thank you

**Comment by cheat-engine** [comment]
Does it boot when you press b ?  If not, try the UEFI build with rEFInd
If it does, try debugging it.  Compile vmdisk in debug mode and then step through the boot sequence with a virtual serial port and a pipe


AMD debug still works on 190x with global debug.  Just make sure you do NOT add any dbgprint in your code.  Also use the same compiler I do (best just use the driver I released with ce 7.2 , not a selfcompiled one )

**Comment by kitty8904** [comment]
b push -> boot success 

f5 gobal debug -> page fault in nonpaged area bsod

dbvm find out -> not bsod (success, but 32bit process not result address)= 64bit process possible

Installed in bios, not uefi mode

////////////////////////////////////////////

The test file is the full version of the cheat engine.

It is not a compiled file

https://cheatengine.org/download/CheatEngine7.2_MissingSetup.rar

**Comment by kitty8904** [comment]
video1 : bsod
https://youtu.be/ejrVkYtgqWk

**Comment by kitty8904** [comment]
7.3 Beta version test results

video 2 32-bit result is output normally

But

video 1 bsod is impossible to solve

ntfs.sys page falut bsod message is also displayed

This does not happen on Windows versions prior to 1809

**Comment by kitty8904** [comment]
amd execute access no address

Execute function does not work on image address

In Intel, the address value comes out when run

doesn't work on amd

video:

https://youtu.be/hMsUIcQia60
