### ISSUE TITLE
7.2 doesn't install as 64 bit

### ISSUE THREAD

**Issue by hexpo35** [cheat-engine/cheat-engine#1475]
For some reason when I try to build 7.2 Lazarus keeps on giving me this error
![ss](https://user-images.githubusercontent.com/78651807/107121797-b6db1300-68d7-11eb-804c-e83e4c9fe898.PNG)
which means that I installed the 32 bit version of Cheat Engine, I've tried downloading multiple times and opening it on Lazarus but I keep on getting the same error, is there a direct link to get the 64 bit version of cheat engine?

**Comment by cheat-engine** [comment]
go to project->project options->compiler options
under build modes select a 64-bit target

**Comment by hexpo35** [comment]
Thanks, so just to clarify this option?
![ssd](https://user-images.githubusercontent.com/78651807/107122999-7763f500-68de-11eb-8a08-22fa20e5ac74.PNG)
Not the O4 one?

**Comment by cheat-engine** [comment]
Both will work if you have a cpu with AVX2, but otherwise go for the default..  (or even the debug ones if you like to debug CE)

**Comment by hexpo35** [comment]
Alright thanks, and will I need to do this when I build a new version of Cheat Engine? Or is there a permanent fix?

**Comment by cheat-engine** [comment]
it stores the last build mode

**Comment by hexpo35** [comment]
Wait I'm getting this error
![ssds](https://user-images.githubusercontent.com/78651807/107123252-d9712a00-68df-11eb-9914-6966524978d8.PNG)
Also when I built it, it worked, but there were 11 warnings?

**Comment by hexpo35** [comment]
Wait now it's working, but it loads really slowly

**Comment by cheat-engine** [comment]
do not run it with the play button as that will run it under the debugger, which is slow

**Comment by hexpo35** [comment]
Oh no no, I ran it from cheat-engine-7.2 > Cheat Engine > bin > cheatengine-x86_64
and it's working fine now, I hope, also do I keep the exe in that folder and not move it?

**Comment by cheat-engine** [comment]
it's fine there.

as long as your AV doesn't cause a huge slowdown it should be fine

**Comment by hexpo35** [comment]
Alright thanks so much, have a good one!

**Comment by hexpo35** [comment]
Wait, sorry, I installed the installer from the cheat engine website and installed that version since I couldn't build it, now that I did, do you know how to completely uninstall that Cheat Engine? Is it the same as any other application or is there any hidden folders I should look for?

**Comment by cheat-engine** [comment]
just run the uninstaller.
But I do recommend you copy over the files from that install folder that you haven't compiled yet(missing) to your current bin folder first, as it will save you some time compiling the additional DLL's and images (depending on your needs)

**Comment by hexpo35** [comment]
So copy the files from C:\Program Files\Cheat Engine 7.2 and paste it into C:\Users\Jaewa\Downloads\cheat-engine-7.2\Cheat Engine\bin and skip if the file already exits?

**Comment by cheat-engine** [comment]
pretty much yes

**Comment by hexpo35** [comment]
Alright, also do you know how to get rid of the adware that came with the installer? I turned off the internet when I installed but I'm worried in case it bundled it with it

**Comment by cheat-engine** [comment]
Run the uninstaller of that adware.

Also, it doesn't install if you don't agree to it during install

**Comment by hexpo35** [comment]
And once I paste in the files, should I use the Cheat Engine.exe that came from the original install from now on or still use the cheatengine-x86_64.exe I built? And yeah I know, but just worried in case the adware came bundled with the installer, I didn't see any options to accept or deny for adware since I turned off the internet when I installed, and when you mean uninstaller of that adware do you mean run my antivirus? Sorry for so many questions at once

**Comment by cheat-engine** [comment]
Up to you. cheat engine.exe will run either cheatengine-x86_64.exe or the AVX2 version depending on your CPU capabilities, so if you want to selfcompile the avx2 version as well you can

The advertised application will register as a normal application that you can uninstall with the uninstaller program that comes with it.  It can be found in the start folder, or in the control panel for uninstalling software.

**Comment by hexpo35** [comment]
Okay, all working now, thanks so much for your help and time, have a good day!
