### ISSUE TITLE
Can't open cheat engine (HELP)

### ISSUE THREAD

**Issue by bubblegump30** [cheat-engine/cheat-engine#1479]
I dont have badlion on my pc never have and its still not opening up i Uninstalled cheat engine to see if that worked and downloaded it again to see if it work still getting this issue.. and it always worked before never had this issue before tell now. Also i don't have any anti-virus so

**Comment by cheat-engine** [comment]
open a command prompt and type `driverquery /v >bla.txt` which will create a bla.txt file in the directory you execute this. Then upload bla.txt here so we can see what else could be the issue

Also, windows defender is an anti virus, have you removed that as well ?

**Comment by bubblegump30** [comment]
No idea how to remove windows defender

**Comment by bubblegump30** [comment]
[My bla.txt](https://drive.google.com/file/d/1C1KUaxUrpJvE82tuDES4WFcCwZmCL92d/view?usp=drivesdk)

**Comment by bubblegump30** [comment]
?

**Comment by cheat-engine** [comment]
i don't have access to that  file

**Comment by bubblegump30** [comment]
You should be able to now sorry about that

**Comment by cheat-engine** [comment]
mediafire is blocked here.  You can drag the file into your post here when you reply

Anyhow, check your anti virus or malware protection logs/settings.  I'm almost certain your windows defender reputation protection is protecting you.

**Comment by bubblegump30** [comment]
Its all good bro I got it working I done a troubleshooting and it works now
