### ISSUE TITLE
Amd LogStack Bsod

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1482]
![log](https://user-images.githubusercontent.com/18622105/108135271-2b455b80-70fb-11eb-9568-3a9d3688f031.png)

dbvm write and read/write access 

amd cpu log stack function check -> BSOD

**Comment by cheat-engine** [comment]
bsod or freeze ?

**Comment by kitty8904** [comment]
freeze 

////////////

cheatengine.lpr

LuaCECustomButton.pas file is missing

**Comment by cheat-engine** [comment]
Does your mainboard have a POST display?  If so, what is it (that saves me time debugging)

**Comment by kitty8904** [comment]
![POST-codes-display-LED](https://user-images.githubusercontent.com/18622105/108136279-1d90d580-70fd-11eb-8228-70a82df4c27e.jpg)

I don't know because the motherboard doesn't have the same function as the picture.

Click on the debugging function and immediately BSOD

**Comment by cheat-engine** [comment]
should work now

**Comment by kitty8904** [comment]
no bsod success work

///////////////////////////////////////////////////

There's another feature that doesn't work

amd memory view dbvm find out no result address

![no](https://user-images.githubusercontent.com/18622105/108139402-62b80600-7103-11eb-8486-04c9e99c6180.png)

**Comment by kitty8904** [comment]
amd dbvm_enableTSCHook(true) -> bsod

bsod TSC hooking in amd

there is no function

**Comment by kitty8904** [comment]
![time](https://user-images.githubusercontent.com/18622105/108279902-b3d9ff80-71c0-11eb-88d8-edf12874b980.png)

pafish link
https://github.com/a0rtega/pafish/archive/v0.5.8.zip

amd cpu dbvm load pafish rdtsc time check error

1.
amd cpu dbvm_enableTSCHook(true) -> rdtsc time error
2.
amd cpu dbvm_enableTSCHook(false) -> rdtsc time error

intel cpu dbvm_enableTSCHook(true) -> rdtsc time no error

//////////////////////////////////////////////////////////////////////

amd dbvm execute access no address(image execute address)

**Comment by cheat-engine** [comment]
it's `dbvm_disableTSCHook()`

also, since many systems these days are running inside a virtual machine thanks to microsoft's security, this is going to be a non-issue soon enough
