### ISSUE TITLE
android ceserver breakpoint not function?

### ISSUE THREAD

**Issue by avboy1337** [cheat-engine/cheat-engine#1484]
when using aarch64 ceserver to set breakpoint , the gui display no red breakpoints

**Comment by cheat-engine** [comment]
not even a message that you're out of breakpoints ?

**Comment by avboy1337** [comment]
i think its my fault ,sorr

**Comment by avboy1337** [comment]
![image](https://user-images.githubusercontent.com/5463104/109652169-62efe100-7b9a-11eb-934d-e67c223e72c8.png)

as the picture above , i cannot make breakpoint work . when breakpoint is setted , it is not enabled.
and the host is aarch64 xiaomi
running CE in winserver2019

**Comment by avboy1337** [comment]
> not even a message that you're out of breakpoints ?

is there something i did wrong ,and i wanna to know why i cannot enable the breakpoint .

**Comment by cheat-engine** [comment]
I'm not sure. What is the ceserver log output ?
