### ISSUE TITLE
zwclose hook error

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#149]
newkernelhander.pas

 ntdll:=loadlibrary('ntdll.dll');
 zwc:=GetProcAddress(ntdll,'NtClose');
 old:=@oldZwClose;
 olds:=inttohex(ptruint(old),8);
 generateAPIHookScript(nthookscript,IntToHex(ptruint(zwc),8),IntToHex(ptruint(@ZC),8),IntToHex(ptruint(@oldZwClose),8),'0',true);
 clipboard.AsText:=nthookscript.Text;

  autoassemble(nthookscript, false, true, false, true);

cheat engine run(driver load) -> crash cheat engine

ntdll.NtClose Api hooking error

**Comment by cheat-engine** [comment]
try now

**Comment by kitty8904** [comment]
thank you fixed not error
