### ISSUE TITLE
Cheat engine installation problem

### ISSUE THREAD

**Issue by SenpaiNeo** [cheat-engine/cheat-engine#1492]
When I download cheat engine and go to install it, it says "Error occured while installing CheatEngine."
I cant find anything on the forum.(Probably looking in the wrong place)

**Comment by cheat-engine** [comment]
Is internet working?
check your anti virus if you're being protected (look up reputation based protection)

**Comment by SenpaiNeo** [comment]
I have turned off my anti-virus and I am still getting the same issue. I can open the .exe but after it asks my language and I hit next on the Welcome to CheatEngine Installer page thats when I get the error.

**Comment by SenpaiNeo** [comment]
Its fixed, even though I turned the antivirus it was still blocking the file I had downloaded previously. I had to download a new version of it.
