### ISSUE TITLE
the address of code may be seems not ok?

### ISSUE THREAD

**Issue by avboy1337** [cheat-engine/cheat-engine#1500]
envirment is arm android process is Chrome render 
u0_i0         22238  22177 1529100 120392 SyS_epoll_wait      0 S com.android.chrome:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0

![image](https://user-images.githubusercontent.com/5463104/109903422-b9fad080-7cd6-11eb-8096-1d8d7e70912e.png)

sorry to bother you and if there is no problem please just consider me as a mistake

**Comment by cheat-engine** [comment]
looks like a rendering issue on the address
press ctrl+g to see the actual address

**Comment by avboy1337** [comment]
> looks like a rendering issue on the address
> press ctrl+g to see the actual address

thanks for your ans and its yes that Ctrl+g will show the actual address!!!
are we going to patch this master?

**Comment by avboy1337** [comment]
> looks like a rendering issue on the address
> press ctrl+g to see the actual address

Yes and you are totally right!!
ctrl+g will show the actual address.

as another problem has been found that some process id can not show when opening processes for android and is there any possible for us to patch this problem and the not showing pid ?

**Comment by avboy1337** [comment]
> looks like a rendering issue on the address
> press ctrl+g to see the actual address

anothoer issue is that when we wanna to go to a special address by Ctrl+G
CE will go to a wrong address 
![bug](https://user-images.githubusercontent.com/5463104/110214107-006e4c00-7ede-11eb-848a-9b2030d7d177.gif)

**Comment by cheat-engine** [comment]
the address looks correct(- the rendering issue). you go from 374b5000 to to 374b410c 
It just seems like that address is currently not allocated

**Comment by avboy1337** [comment]
> the address looks correct(- the rendering issue). you go from 374b5000 to to 374b410c
> It just seems like that address is currently not allocated

i think you are right !!

**Comment by cheat-engine** [comment]
maybe a libc version issue
