### ISSUE TITLE
the newest ceserver armv7a pops error as follows

### ISSUE THREAD

**Issue by avboy1337** [cheat-engine/cheat-engine#1503]
end:
i=1
output is not NULL (0xb6bda400)
Sending 1026 bytes
CMD_GETSYMBOLLISTFROMFILE
symbolpath=/system/lib/arm/xstdata
GetSymbolListFromFile(/system/lib/arm/xstdata)
Invalid address 0xb637f700 passed to free: value not allocated

**Comment by avboy1337** [comment]
> end:
> i=1
> output is not NULL (0xb6bda400)
> Sending 1026 bytes
> CMD_GETSYMBOLLISTFROMFILE
> symbolpath=/system/lib/arm/xstdata
> GetSymbolListFromFile(/system/lib/arm/xstdata)
> Invalid address 0xb637f700 passed to free: value not allocated

i think the reason does not belong ce, may be it is the problem of phone
because using realPhone is ok and using Genymotion is OK
but use another VM is not OK

**Comment by avboy1337** [comment]
i test some emulators and some emulators is ok but some are not . I think may be this need us to have a check.

**Comment by avboy1337** [comment]
output is not NULL (0xf0525580)
Sending 2560 bytes
CMD_GETSYMBOLLISTFROMFILE
symbolpath=/system/lib/libmemunreachable.so
GetSymbolListFromFile(/system/lib/libmemunreachable.so)
end:
i=1
output is not NULL (0xf0514280)
Sending 6711 bytes
CMD_GETSYMBOLLISTFROMFILE
symbolpath=/system/lib/arm/xstdata
GetSymbolListFromFile(/system/lib/arm/xstdata)
Invalid address 0xf077f770 passed to free: value not allocated
Aborted

**Comment by DoranekoSystems** [comment]
For Android Emulator, x86 ceserver is recommended.
If it does not work on x86, please let me know what environment you are in.

**Comment by avboy1337** [comment]
ceserver compiled to arm32 and in genymotion 7.1 is ok , but when running environment of number more than 7.1 is not OK
after opened pid , for a while maybe 30 sececonds and the process is crashed.

**Comment by DoranekoSystems** [comment]
Emulators such as Genymotion, Nox, Bluestack, etc. are internally running on x86, and even if you run arm32 ceserver, you should not be able to use hardware breakpoints.
Therefore, if you want to do memory search, it is safer to use x86 ceserver.
If you use a memory access breakpoint, you may find a program emulated from arm to x86.

**Comment by DoranekoSystems** [comment]
I encountered the same bug in my environment and was able to identify the cause.
/system/lib/arm/xstdata is a small file, less than 40 bytes.
The bug occurs in the ELF32 function in symbol.c.

https://github.com/cheat-engine/cheat-engine/blob/c31abc92216795973e1433ebea6e50c1727c6dab/Cheat%20Engine/ceserver/symbols.c#L102-L110

The error seems to occur in free(output) above.

```
int ELF32(int f, Elf32_Ehdr *b, unsigned char **output)
/*
Caller must free output manually
*/
{
  Elf32_Shdr check;
  if (pread(f, &check, b->e_shentsize*b->e_shnum, b->e_shoff)==-1)
  {
    return -1;
  }
```
In my environment, I was able to avoid the error by adding the above check process first in the ELF32 function.

**Comment by cheat-engine** [comment]
Should probable initialize *output first 
```*output=NULL```

and in the free code free *output instead of output

**Comment by DoranekoSystems** [comment]
Thanks!
There is the same bug within Elf64. Please fix it.

**Comment by cheat-engine** [comment]
fixed it

**Comment by avboy1337** [comment]
i tried x86  arm and close it now ,thanks for your attention!!
