### ISSUE TITLE
may be ceserver have a toooo long address scope 

### ISSUE THREAD

**Issue by avboy1337** [cheat-engine/cheat-engine#1504]
look at the following picutre
![image](https://user-images.githubusercontent.com/5463104/110240019-d4f26c80-7f84-11eb-8941-3e99b9ae9e9a.png)

**Comment by avboy1337** [comment]
by the way ,address 0x25b073ba0 have the same contents with 0x5b073ba0 
is this a confused problem?

**Comment by cheat-engine** [comment]
look at memory regions

**Comment by avboy1337** [comment]
> look at memory regions

![image](https://user-images.githubusercontent.com/5463104/110284281-84c6e900-801c-11eb-830f-80720f32c2a9.png)

Here is memory regions and the right rolloing bar located at bottom
may be there is an integer xxx?

**Comment by cheat-engine** [comment]
view-memory regions

**Comment by avboy1337** [comment]
> view-memory regions

i dont know if i am right ,and this is the memory regions
![image](https://user-images.githubusercontent.com/5463104/110293550-ada1ab00-8029-11eb-96e6-a9ca60510176.png)

**Comment by cheat-engine** [comment]
The regions marked Commit are the regions scanned.  So that's ok.  That you can use notations like 2xxxxxxxx and 3xxxxxxxx is because 32-bit targets strip the upper bits of an address

**Comment by avboy1337** [comment]
> The regions marked Commit are the regions scanned. So that's ok. That you can use notations like 2xxxxxxxx and 3xxxxxxxx is because 32-bit targets strip the upper bits of an address
> 
> but it does show an issue for some regions, like 1223a000 to 1223d000

however CE is my only love tool its my best ! wish a better one
