### ISSUE TITLE
GUI always displays XMM register as 0 on @ 7.2 /w 1809.

### ISSUE THREAD

**Issue by moohyun69** [cheat-engine/cheat-engine#1505]
Using DBVM debugger. am im the only one experiencing this issue?

![xmm](https://user-images.githubusercontent.com/79583741/110265091-1b37e200-7ffe-11eb-860b-e0d26babaa95.PNG)

**Comment by cheat-engine** [comment]
that's fixed.  You just need to compile the driver from the latest source

**Comment by moohyun69** [comment]
> that's fixed. You just need to compile the driver from the latest source

alright, thanks for heads up.
