### ISSUE TITLE
dbvm crash

### ISSUE THREAD

**Issue by apple4567** [cheat-engine/cheat-engine#1513]
hello, dark byte
some fixes here and there
 master  7.2 7.1
@cheat-engine
cheat-engine committed on 10 Mar 2020
dbvmversion=13; dbvmversion=14;
DBVM doesn't work on my old laptop i7-4700HQ
Cheat Engine 7.0 DBVM 13 works without problems
Cheat Engine 7.1, Cheat Engine 7.2 DBVM14 Blue screen
One core or all process cores will crash the computer when loading the DBVM image
All BlueStacks and other virtualization programs have been removed
DBVM14,DBVM15 does not work on my laptop
My friend also says it doesn't work on Haswell PC
How can I solve this problem?

**Comment by cheat-engine** [comment]
execute this lua code and post the results here
```lua
local procbased_ctls2=nil
local procbased_ctls=nil

print(string.format("efer=%x", dbk_readMSR(0xc0000080)))
print(string.format("CR0=%.8x", dbk_getCR0()))
print(string.format("CR4=%.8x", dbk_getCR4()))


print(string.format("VMX_BASIC=%.16x", dbk_readMSR(0x480)))
print(string.format("VMX_PINBASED_CTLS=%.16x", dbk_readMSR(0x481)))
if (dbk_readMSR(0x480)&(1<<55))~=0 then
  print(string.format("REAL VMX_PINBASED_CTLS=%.16x", dbk_readMSR(0x48d)))
end


procbased_ctls=dbk_readMSR(0x482)

print(string.format("VMX_PROCBASED_CTLS=%.16x", procbased_ctls))
if (dbk_readMSR(0x480)&(1<<55))~=0 then
  procbased_ctls=dbk_readMSR(0x48e)
  print(string.format("REAL VMX_PROCBASED_CTLS=%.16x", procbased_ctls))
end

if (procbased_ctls & (1<<63))~=0 then
  procbased_ctls2=dbk_readMSR(0x48b)
  print(string.format("VMX_PROCBASED_CTLS2=%.16x", procbased_ctls2))
end

print(string.format("VMX_EXIT_CTLS=%.16x", dbk_readMSR(0x483)))
if (dbk_readMSR(0x480)&(1<<55))~=0 then
  print(string.format("REAL VMX_EXIT_CTLS=%.16x", dbk_readMSR(0x48f)))
end

print(string.format("VMX_ENTRY_CTLS=%.16x", dbk_readMSR(0x484)))
if (dbk_readMSR(0x480)&(1<<55))~=0 then
  print(string.format("REAL VMX_ENTRY_CTLS=%.16x", dbk_readMSR(0x490)))
end


print(string.format("VMX_MISC=%.16x", dbk_readMSR(0x485)))


print(string.format("VMCS_ENUM=%.16x", dbk_readMSR(0x48a)))

if procbased_ctls2 then
  if (procbased_ctls & (1<<33))~=0 then
    print(string.format("VPID_EPT_CAP=%.16x", dbk_readMSR(0x48c)))
  else
    print("This system does not support EPT.  Won't work")
  end
else
  print("No secondary procbased ctrls. This system will not work")
end
```

**Comment by apple4567** [comment]
efer=d01 
CR0=80050033 
CR4=001506f8 
VMX_BASIC=00da040000000012 
VMX_PINBASED_CTLS=0000007f00000016 
REAL VMX_PINBASED_CTLS=0000007f00000016 
VMX_PROCBASED_CTLS=fff9fffe0401e172 
REAL VMX_PROCBASED_CTLS=fff9fffe04006172 
VMX_PROCBASED_CTLS2=00003cff00000000 
VMX_EXIT_CTLS=007fffff00036dff 
REAL VMX_EXIT_CTLS=007fffff00036dfb 
VMX_ENTRY_CTLS=0000ffff000011ff 
REAL VMX_ENTRY_CTLS=0000ffff000011fb 
VMX_MISC=00000000300481e5 
VMCS_ENUM=000000000000002a 
VPID_EPT_CAP=00000f0106334141 

epthandler.c

Error in void sanitizeMemoryRegions() function

//if (left.size)
//{
//  addToMemoryRanges(left.startaddress, left.size, left.memtype);
//  sendstringf("    Left becomes (%6 - %6):%d\n", left.startaddress, left.startaddress+left.size-1, left.memtype);
//}
//else
//  sendstringf("    Left is empty\n");
//
//
//if (right.size)
//{
//  addToMemoryRanges(right.startaddress, right.size, right.memtype);
//  sendstringf("    Right becomes (%6 - %6):%d\n", right.startaddress, right.startaddress+right.size-1, right.memtype);
//}
//else
//  sendstringf("    Right is empty\n");


//adjust the current entry
//memoryranges[i].startaddress=overlap.startaddress;
//memoryranges[i].size=overlap.size;
//memoryranges[i].memtype=overlap.memtype;
//sendstringf("    This becomes (%6 - %6):%d\n", memoryranges[i].startaddress, //memoryranges[i].startaddress+memoryranges[i].size-1, memoryranges[i].memtype);


//mark as handled
//int k;
//for (k=j; k<memoryrangesPos-1; k++)
//  memoryranges[k]=memoryranges[k+1];
//
//memoryrangesPos--;

//continue; 

Deleting the line below in the sanitizeMemoryRegions function
not freeze the computer
How do I fix the code?
