### ISSUE TITLE
Cheat Engine Launch Error : c

### ISSUE THREAD

**Issue by MineBlack** [cheat-engine/cheat-engine#1518]
Hello everyone,
when i try to launch Cheat Engine, the only thing i see is that 
![image](https://user-images.githubusercontent.com/80829400/111467052-4b7d3000-8724-11eb-8a6f-6fd846145a6e.png)
Is there a unpatched bug or a solution exists ?
(sorry for my horrible english, i'm a french guy)

Thanks !

**Comment by cheat-engine** [comment]
Your cheatengine-x86_64.exe or the avx version is missing or you're being blocked from opening it
