### ISSUE TITLE
createapc x32

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#152]
Tutorial-i386.exe,teamviewer.exe,skype.exe -> createAPC(0x5858000) NO Crash

notepad++x86.exe ->createAPC -> Fail Thread Die
(https://notepad-plus-plus.org/download/v7.3.1.html)
Is it my computer problem? (certain processes are terminated)
(windows7 ultimate x64)
(intel(R) Core(TM) i5-2500 CPU @ 330GHZ)
(GTX980)
(samsung SSD -> Virtual Page Memory 0MB)

cheat engine debug_setBreakpoint trace
ntdll.NtTerminateThread+B- 64 FF 15 C0000000 - call fs:[000000C0]

call fs:[C0] Code Death in routine

**Comment by cheat-engine** [comment]
Some processes just will not work.
It may be because they are programmed without keeping in mind that some functions can return before the wait is finished

**Comment by kitty8904** [comment]
okay last debug trace fix?

bla:
ret [esp+0] -> ntdll.KiUserApcDispatcher+25 - mov ecx,[edi+000002CC] =>

ntdll.KiUserApcDispatcher+35 - call ntdll.ZwContinue =>

ntdll.ZwContinue - mov eax,00000040 { 64 }
ntdll.NtContinue+5- xor ecx,ecx
ntdll.NtContinue+7- lea edx,[esp+04]
ntdll.NtContinue+B- call fs:[000000C0] =>

wow64cpu._CpuSuspendLocalThread+8A8 - jmp 0033:wow64cpu._CpuSimulate+16E =>

72E42770 - call qword ptr [72E41080] { ->wow64._Wow64SystemServiceEx } =>

wow64._Wow64SystemServiceEx+D4 - call r12 =>

wow64._Wow64EmulateAtlThunk+D5C6 - call qword ptr [72EB1028] { ->ntdll._NtContinue } =>

ntdll._NtContinue - mov r10,rcx
ntdll._ZwContinue+3- mov eax,00000040 { 64 }
ntdll._ZwContinue+8- syscall 
ntdll._ZwContinue+A- ret 
ntdll._ZwContinue+B- nop [rax+rax+00]

But EIP Change : 7767BF60(Ntdll._Ntcontinue) ->7767BF6A(ntdll._ZwContinue+A- ret)
(EIP change does not terminate process)

No Crash application Die

syscall -> Crash Dead!

**Comment by kitty8904** [comment]
https://github.com/DarthTon/Blackbone/blob/e59f720e802ee83cc2c292361057595223ace247/src/BlackBoneDrv/Loader.c#L510

Any other way than APC?

**Comment by kitty8904** [comment]
i found an error

 You are right

CreateRemoteAPC(getathreadid(processid), pointer(address));

1) frmProcessWatcher ON -> APC index mismatch BSOD(blue screen)
CEFuncProc(line 658) -> Blue Screen

2)Threadlist Main Dead
![threadlist](https://cloud.githubusercontent.com/assets/18622105/22174213/23e2db0c-e01c-11e6-8a7e-c910f0b292e9.png)

(ths:=CreateToolhelp32Snapshot(TH32CS_SNAPTHREAD,0); 
2E0 -> MainThread 
15D8 ->sub
354 ->sub
15FC ->sub

CreateRemoteAPC($02E0, pointer(address)); ->Fail Thread Dead

CreateRemoteAPC($15D8, pointer(address)); ->No Dead Thread APC Success

Are you getting the threads at random?

Does APC require a running thread ID?

Will only be terminated on certain threads

Is it impossible to create a new thread or a virtual thread number?

3) After the target process is terminated -> Run the script by mistake
   CreateAPC(address) RUN  -> APC BAD bluescreen(No Thread INFO BSOD?)

**Comment by kitty8904** [comment]
![threadinfo](https://cloud.githubusercontent.com/assets/18622105/22175124/3f2484b8-e032-11e6-84b5-d471da550670.png)

I found one

MainThread EIP value 7301FE9A(wow64windll+3FE9A) -> Crash Thread Dead

MainThread EIP value 72FD2E09(wow64cpu.dll+2E09) -> APC Thread Success

Is this information helpful?

**Comment by kitty8904** [comment]
No Thread ID blue screen Patch == target process terminate -> createAPC Code execute
============================
Function CreateRemoteAPC(threadid: dword; lpStartAddress: TFNAPCProc): THandle; stdcall;
var
    br,cc: dword;
    x:record
      threadid: uint64;
      addresstoexecute: uint64;
    end;

begin
  result:=0;
  if hdevice<>INVALID_HANDLE_VALUE then
  begin
    x.addresstoexecute:=ptrUint(lpStartAddress);
    x.threadid:=threadid;
    if x.threadid = 0 then //Thread ID check
    begin
    messagebox(0,'APC injection failed because there is No thread ID','APC',MB_ICONERROR or mb_ok);
    exit;
    end
    else
    begin
    cc:=IOCTL_CE_CREATEAPC;
    if deviceiocontrol(hdevice,cc,@x,sizeof(x),nil,0,br,nil) then
      result:=666 //sorry dude, no threadid returned, and no way of checking if it succeeded or not
    else
      result:=0;
    end;
  end;
end;
