### ISSUE TITLE
dbvm handle

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#153]
obtain handles check on(No Handle Create)
No Handle -> DBVM Debugging -> Crash Program
kernel source fix? or delphi code fix?
DebugHelper.pas  fix?
I do not know where to fix it
I want to use DBVM in protected processes!(obregistercallbacks Protect process)

**Comment by cheat-engine** [comment]
Have you tried with the global debug flag ?

**Comment by kitty8904** [comment]
![1](https://cloud.githubusercontent.com/assets/18622105/22331382/8370cf0c-e40e-11e6-98a0-066db7b57128.gif)
gif image 4MB

global debug routine check on(Obregistercallbacks Protect Process Crash)

AND NoObregistercallbacks(obtain handler check on) -> Debug -> Crash

**Comment by cheat-engine** [comment]
turn of kernelmode stepping

also, for dbvm: once you start it, close ce and run the kernelmodule unloader

then start ce again, attach to the target process and then try to debug it

**Comment by kitty8904** [comment]
ok testing 
1. ce run -> DBVM LOAD -> close ce -> kernelunload.exe -> run ce -> debuging -> but crash app
