### ISSUE TITLE
DBVM sanitizeMemoryRegions

### ISSUE THREAD

**Issue by apple4567** [cheat-engine/cheat-engine#1534]
I asked a question two weeks ago
efer=d01
CR0=80050033
CR4=001506f8
VMX_BASIC=00da040000000012
VMX_PINBASED_CTLS=0000007f00000016
REAL VMX_PINBASED_CTLS=0000007f00000016
VMX_PROCBASED_CTLS=fff9fffe0401e172
REAL VMX_PROCBASED_CTLS=fff9fffe04006172
VMX_PROCBASED_CTLS2=00003cff00000000
VMX_EXIT_CTLS=007fffff00036dff
REAL VMX_EXIT_CTLS=007fffff00036dfb
VMX_ENTRY_CTLS=0000ffff000011ff
REAL VMX_ENTRY_CTLS=0000ffff000011fb
VMX_MISC=00000000300481e5
VMCS_ENUM=000000000000002a
VPID_EPT_CAP=00000f0106334141

My computer is an Intel 4th generation Haswell CPU
Computer does not freeze when deleting DBVM sanitizeMemoryRegions function
Is there any problem without the sanitizeMemoryRegions function?
If you have time,Please answer my question

**Comment by cheat-engine** [comment]
execute this code and post the results here so I'll be able to see what sanitizeMemoryRegions does 
```
dbk_initialize()

MTRRCAP=dbk_readMSR(0xfe)
print(string.format("IA32_MTRRCAP=%x",MTRRCAP))


varcount=MTRRCAP & 0xff
print("Variable count is "..varcount)
local i
if varcount>0 then
  print("base - mask")
  for i=0,varcount-1 do
    print(string.format("%.16x - %.16x", dbk_readMSR(0x200+i*2),dbk_readMSR(0x201+i*2)))
  end
end

if ((cpuid(1).EDX & (1 << 12))~=0) and ((MTRRCAP & (1<<8))~=0) then
  print("\nFixed range MTRR's supported")
  print(string.format("FIX64K_00000=%.16x", dbk_readMSR(0x250)))
  print(string.format("FIX16K_80000=%.16x", dbk_readMSR(0x258)))
  print(string.format("FIX16K_A0000=%.16x", dbk_readMSR(0x259)))
  print(string.format("FIX4K_C0000=%.16x", dbk_readMSR(0x268)))
  print(string.format("FIX4K_C8000=%.16x", dbk_readMSR(0x269)))
  print(string.format("FIX4K_D0000=%.16x", dbk_readMSR(0x26a)))
  print(string.format("FIX4K_D8000=%.16x", dbk_readMSR(0x26b)))
  print(string.format("FIX4K_E0000=%.16x", dbk_readMSR(0x26c)))
  print(string.format("FIX4K_E8000=%.16x", dbk_readMSR(0x26d)))
  print(string.format("FIX4K_F0000=%.16x", dbk_readMSR(0x26e)))
  print(string.format("FIX4K_F8000=%.16x", dbk_readMSR(0x26f)))
else
  print("\nNo fixed range MTRR's supported")
end
```

**Comment by apple4567** [comment]
This is the test result

IA32_MTRRCAP=d0a 
Variable count is 10 
base - mask 
0000000000000006 - 0000007c00000800 
0000000400000006 - 0000007fe0000800 
0000000420000006 - 0000007ff0000800 
00000000e0000000 - 0000007fe0000800 
00000000d0000000 - 0000007ff0000800 
00000000ce000000 - 0000007ffe000800 
00000000cd000000 - 0000007fff000800 
000000042fe00000 - 0000007fffe00800 
0000000000000000 - 0000000000000000 
0000000000000000 - 0000000000000000 

Fixed range MTRR's supported 
FIX64K_00000=0606060606060606 
FIX16K_80000=0606060606060606 
FIX16K_A0000=0000000000000000 
FIX4K_C0000=0505050505050505 
FIX4K_C8000=0505050505050505 
FIX4K_D0000=0000000000000000 
FIX4K_D8000=0000000000000000 
FIX4K_E0000=0505050505050505 
FIX4K_E8000=0505050505050505 
FIX4K_F0000=0505050505050505 
FIX4K_F8000=0505050505050505

**Comment by cheat-engine** [comment]
should be fixed now

**Comment by apple4567** [comment]
I received a reply to the email and confirmed it.
DBVM compiled and tested
DBVM works!
