### ISSUE TITLE
Cheat Engine Wont open !

### ISSUE THREAD

**Issue by truckingMaro** [cheat-engine/cheat-engine#1550]
I just dowloaded it, but when i double click on it to open it doesnt open, it send me like a message saying like i dont have the autorisation, and then it just delete itself, Please help

**Comment by GH-Rake** [comment]
Make sure you're an admin user on your PC
Make sure no kernel anticheats are running
Uninstall BadLion if it's installed (then reboot)
Add exceptions to antivirus
Uninstall Cheat Engine
Hard Reboot
Reinstall it
Run windowsrepair.exe from the main CE folder
Run this in powershell:
-driverquery /v | Select-String "Badlion"
-if it appears, then it's still not uninstalled

**Comment by truckingMaro** [comment]
> Make sure you're an admin user on your PC
> Make sure no kernel anticheats are running
> Uninstall BadLion if it's installed (then reboot)
> Add exceptions to antivirus
> Uninstall Cheat Engine
> Hard Reboot
> Reinstall it
> Run windowsrepair.exe from the main CE folder
> Run this in powershell:
> -driverquery /v | Select-String "Badlion"
> -if it appears, then it's still not uninstalled

Oh Thanks a lot bro
