### ISSUE TITLE
Incorrect x86 instructions in Memory Viewer

### ISSUE THREAD

**Issue by keisuke112** [cheat-engine/cheat-engine#1551]
![incorrect assemble](https://user-images.githubusercontent.com/56597371/115967897-75045500-a535-11eb-93a3-5f3332518296.png)
I have noticed that the same memory addresses show different x86 instructions from the ones shown in x32dbg. I have attached a screenshot. I think Cheat Engine is showing them wrong.

**Comment by cheat-engine** [comment]
You have a int3 breakpoint in x32dbg set so ce can not see the original byte
