### ISSUE TITLE
Saving a Break and Trace to file adds a lot of garbage to the file

### ISSUE THREAD

**Issue by keisuke112** [cheat-engine/cheat-engine#1552]
![1000 break and trace](https://user-images.githubusercontent.com/56597371/115968025-e93ef880-a535-11eb-8e3e-1f03d90de187.png)
I saved a Break and Trace to file and noticed that a lot of garbage was being added after the content. I have attached a screenshot.

**Comment by cheat-engine** [comment]
You're not supposed to open the trace in a text editor. The data after the treeinfo is the data associated with each line
