### ISSUE TITLE
csrss handle

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#156]
https://www.unknowncheats.me/forum/1092938-post4.html

Do not use open processes

Csrss has the handle of every process?

The security process detects an openprocess handle

Can not you get the handle without direct access?(openprocess)

I want to bypass the handle or debug without detection(obregistercallback & DBVM)
(Is it impossible to debug without removing the callback?)

If you force the callback to be removed, it will be debugged

If it's impossible, I won't ask you any more questions

**Comment by cheat-engine** [comment]
ZwDuplicateObject is blocked by obregistercallback so that won't work.

I can of course make threads work, but if the target has any kind of decent protection, then debugging is not going to happen.
If all the debug registers are used up  then breakpoints won't work, and overriding them will crash the game.

At best you could implement some pagefault breakpoint method with the help of dbvm

**Comment by kitty8904** [comment]
It's possible?

I do not know more about the kernel

I know how to register and bypass callbacks(reversing) but I do not know how to add core functionality of the DBVM feature

Is it possible to add DBVM functionality when the time comes(DBVM bypass)?

**Comment by buraktamturk** [comment]
@kitty8904 I wrote an hack for a game that does exactly what you want, but it runs entirely on kernel mode (no user mode helper tool). I can't share the code my whole software (even compiled version is not published anywhere else), but I can inspire you. 

What I did is to hook interrupt1 (via DBVM, or you'll be victim of PatchGuard), then enable global debug, I copied CE's global debug implementation, but it was broken, therefore, I wrote my own implementation (inspired some of CE's implementation). I was able to place breakpoints; hook/control/modify them. And belive me, there is nothing you can't do in game with this breakpoints ;). Your interrupt1 hook will be called on the context of triggered thread, so you can modify registers of that thread, which allows you to call another functions on breakpoint. For example, I place a breakpoint on the beginning of the render function (which is called every frame ~1/60s), in there, I am able to call the function that sends data to server. And I don't see a frame drop.

When you enable Global Debug mode, you control whatever OS or any user mode software access or write DRx registers, so hiding the **real** debug registers or faking write becomes easier. However, you can only place 4 breakpoints as hardware breakpoints is restricted by that. Thus, If the game places breakpoint itself and handles them via VEH (or etc.) as a security measure, your hack may not work at all.

However, you're not limited to x86 debug registers, when you virtualize the system via DBVM or similiar. You can switch pages on read or execute via EPT tables. Allowing you to put read/write/execute breakpoints limitlessly. It's undetected and even you can change game's code without broking it's hash check. (I mean, the code will be show as "xor eax, eax", but it will executed as "inc eax", allowing you to change code without broking anyting). DBVM does not support Split-TLB, however, you can find a lot of alternative VM engines that support EPT. You can also hook kernel mode calls.

Good luck!

**Comment by kitty8904** [comment]
Are you saying that you can use registers without restrictions?

I know of page-exception hooking with stealthedit.dll

I do not understand the kernel and It's a good idea, but I can not implement it.

It does not matter if you debug, read, write, or thread in a simple but simple CE

Thank you for your reply buraktamturk

**Comment by buraktamturk** [comment]
Yes, this is like page-exception handler hooking, but this is undetectable (both global debug and ept table switching). You can modify registers without restrictions. When you use VirtualProtect, it modifies page structures that the game can check, but if you do EPT table switching, the entire table switching operation done by VM at ring -1 and it is invisible even for the OS.

Also, when you hook exception handler in user mode, you inject some kind of code (this could be direct code injection or dll injection) to user mode process which can also be detected by the game. But when you develop kernel mode driver and hook interrupt 1 (typically, it is fired when breakpoints hit on any process) or interrupt14 (page fault), you don't have to inject code to the process. For example, if your page-exception hook in user-mode gets detected, hook them in kernel (via DBVM) and do whatever you want to do in your kernel driver. 

About debugging matter, when you enable GD flag in DR7 register, int1 handler will be called every read/write acess to DRx (mov eax, drX or mov drX, eax), **just like you have placed breakpoints every DRx access**, and in int1 handler, you are able to set eax to = 0 and incrase eip by 2 (whatever the size of mov eax, dr0), so the operating system (and the game) won't know the original dr register. Your hook will be undetectable thanks to DBVM, and your breakpoints will be undetectable thanks to your handler. You can find a lot about this technique in CE's source code.

**Comment by kitty8904** [comment]
https://github.com/tandasat/DdiMon

Ept hooking is invisible hooking?

I found the source used by the patch guard

Using this approach, you can debug, read, write, and create threads even if you target a protected process?

But I do not know how to actually apply this to the normal process because there is a lack of learning

Honestly, I lack my ability

Process protection (obregistercallbacks) ->I wanted to debug, write, read, and create threads.

Darkbyte, buraktamturk Do not you ever want to upload these examples or add features?

If we can not update the policy, we will no longer reply the commit

**Comment by kitty8904** [comment]
process write (dbk_writesIgnoreWriteProtection) patch?(virtualprotect kernel)
https://github.com/DarthTon/Blackbone/blob/60c7e35b06d1960dfc9d2263c019d213291b5b19/src/BlackBoneDrv/Routines.c#L480

handle access change? (0x1f1fff (Query information, Set information, Set quotas, Set session ID, Create threads, Create processes, VM operation, VM read, VM write, Duplicate handles, Suspend/resume, Terminate, Synchronize, Delete, Read control, Write DAC, Write owner)

https://github.com/DarthTon/Blackbone/blob/60c7e35b06d1960dfc9d2263c019d213291b5b19/src/BlackBoneDrv/Routines.c#L144

I'm looking for a way to fix it in a protected process, but I do not know anymore.

**Comment by cheat-engine** [comment]
the problem is that ZwProtectVirtualMemory is not exported so i have to use a hardcoded callnumber which is something i try to prevent.

but why not call an apc that calls virtualProtect from inside the game.  (or if an apc crashes, do  a codeinjection on a often executed windows api where you call virtualprotect once)

**Comment by kitty8904** [comment]
Execute / read only page problem

The problem of using virtualprotect is solved with dbk_writesIgnoreWriteProtection

but  dbk_writesIgnoreWriteProtection -> ALL process code change 
(Ex) target 1.exe api KERNELBASE.Sleep+8 - C3 - ret) -> target2.exe (Target 2 process is also modified)

Fixed without modifying target 2

Is blocking the permissions of the dark byte handle difficult to bypass?

The current cheat engine allows read / write
For threads, you can use createapc
Is there a way to debug it?

**Comment by cheat-engine** [comment]
don't use dbk_writesIgnoreWriteProtection but call virtualprotect from within the target.
memory alloc works fine

**Comment by kitty8904** [comment]
createapc or use jmp location hooking?

procedure TMemoryBrowser.Makepagewritable1Click(Sender: TObject);
VirtualProtectEx(hProcess,pointer(memoryaddress),4096,PAGE_EXECUTE_READWRITE,x);
//VirtualProtect(lpAddress: Pointer; dwSize, flNewProtect: DWORD; var OldProtect: DWORD): BOOL; stdcall;

VirtualProtect(pointer(memoryaddress),4096,PAGE_EXECUTE_READWRITE,x);

Is it impossible to call a normal function? Should I call from somewhere else?
