### ISSUE TITLE
Deactivation of AA scripts works incorrectly

### ISSUE THREAD

**Issue by ucwr** [cheat-engine/cheat-engine#1561]
I mean fresh revisions.

Let's see, for example, the following pseudo-AA-code:
```
define(A1, <game address 1>)
define(B1, ...)

define(A2, <game address 2>)
define(B2, ...)
...
define(AN, <game address n>)
define(BN, ...)

[ENABLE]

A1:
  <some code 1>
A2:
  <some code 2>
...
AN:
  <some code n>

[DISABLE]

A1:
  db B1
A2:
  db B2
  ...
AN:
  db BN
```
During deactivation, at A1 will be written BN instead of B1, at A2 will be low byte of A3 address (not B3 sequence!), and so on. The memory at AN will be left untouched.
When we have only one injection point, it's kind of works: A1 == AN and B1 == BN in this case and at A1 will be written B1, so we don't notice the bug.

**Comment by kitty8904** [comment]
Is it cheat engine version 7.2?

Version 7.3 currently has a bug

Some features such as dealloc, unregistersymbol don't work

**Comment by ucwr** [comment]
It's 7.3. For me, the last revision where AA-scripts worked more or less flawlessly was  [a99a6ab](https://github.com/cheat-engine/cheat-engine/commit/a99a6ab2efaa9ad1447880ff363b6f21bf0ed231).

**Comment by kitty8904** [comment]
As far as I know the 7.3 disable script currently has an error

Version 7.2 probably has maybe no errors

**Comment by ucwr** [comment]
Sorry, some idiot just blew up a cracker and I accidentely clicked the "close issue" button.

**Comment by ucwr** [comment]
> 
> 
> As far as I know the 7.3 disable script currently has an error
> 
> Version 7.2 probably has maybe no errors

Yes, agree. I tried 7.3 mostly out of curiosity

**Comment by kitty8904** [comment]
Darkbyte has patched disable

Please confirm it

If it works, just close the issue.

**Comment by ucwr** [comment]
Yes, it works. Thanks!
