### ISSUE TITLE
HexView behavior. A bug or a feature?

### ISSUE THREAD

**Issue by ucwr** [cheat-engine/cheat-engine#1562]
Can you add a function that could reset "editing mode" in the HexView area, or change its behavior algorithm. I constantly forget to press ESC to cancel that mode that activates automatically when I click the RMB for using of the pop-up menu. Because of this, when I press any key, the ```THexView.RefocusIfNeeded()``` function returns the area back to the previous address, so it will be at the upper or lower bound of the area. Of course this rewrites the current address by the other, useless one. For personal using I added at the beginning of the ```THexView.update()``` function a code that checks, if the previous address is beyound visible area (I borrowed the code from the ```RefocusIfNeeded()```) and then does the assign ```isEditing := true```. It's a hack, not a solution, I know. Perhaps it breaks something in the algorithm flow. But at least now I can be sure that I open the "Dissect data/structures" window with the right address, not a random one.
Or maybe I am just reinventing the wheel and there is already some setting for this?

**Comment by ucwr** [comment]
> and then does the assign ```isEditing := true```.
I meant the opposite: ```isEditing := false```

**Comment by kitty8904** [comment]
<img width="542" alt="never" src="https://user-images.githubusercontent.com/18622105/117099355-e781fa00-adab-11eb-8198-f14dc7fed7a9.png">

If you want to prevent module memory change

Use never chage memory protection

esc key focus release problem

https://github.com/cheat-engine/cheat-engine/blob/master/Cheat%20Engine/hexviewunit.pas#L913
VK_ESCAPE:
begin
//isEditing:=false;
//update;
end;

Or is it another problem?

**Comment by ucwr** [comment]
No, it's not about preventing memory change. And yes, I know about ESC key and wrote about it. But besides the fact that I have to constantly remember about necessity of pressing that key, I have a lua script that adds a command to the menu that allows me to go to an address in the clipboard. It would be great to be able to programmatically (in lua) reset the input focus. I really often have to use "Dissect data" window.
Now I think a key handler would be a more suitable place to add such a reset : I mean, where it most logically fits.
BTW, I do not insist on such changes in the code. Perhaps many will not like it. That is why I asked: is this a bug or a feature.

**Comment by ucwr** [comment]
I close this issue and am going to open it anew, with more correct description.
