### ISSUE TITLE
globalalloc dealloc error

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1563]
[ENABLE]
globalalloc(error,4096)
error:
[DISABLE]
unregistersymbol(error) -> ok
dealloc(error), -> fail

Symbols declared as globalalloc cannot be freed with dealloc

alloc(error,4096), registersymbol(error) -> unregistersymbol -> noerror dealloc -> no error
globalalloc(error,4096)-> unregistersymbol -> no error  , dealloc -> fail

Add unglobalalloc ?

///////////////////////////////////////////////////////////////////////////////////////

<img width="499" alt="113493830-f744bf00-951d-11eb-9257-ef486dc6ec0b" src="https://user-images.githubusercontent.com/18622105/117138504-11f0a900-ade6-11eb-841e-5016d5db1386.png">

alloc ,registersymbol do not have the symbol address and size in the symbol list

**Comment by cheat-engine** [comment]
No.  GlobalAlloc shall never be freed. Do not use globalAlloc if you wish to ever free it

**Comment by kitty8904** [comment]
I understand

thankyou
