### ISSUE TITLE
Debugger attack timeout

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1564]
<img width="322" alt="113034957-a8b9bc80-91cd-11eb-9f6a-df8ee0579674" src="https://user-images.githubusercontent.com/18622105/117141967-23d44b00-adea-11eb-96c7-d65cb41df28b.png">

I know it was patched recently?

But the synchronization operation is long delayed
(x64process , process memory 4-8GB , process thread Count 30~40)

32-bit process threads, synchronization is completed within 10 seconds.

64-bit process many threads,big size memory client -> 40sec ~ 1min 10~20sec long time wait

If there is a lot of memory or threads, it is impossible to resolve the time delay?

Do I have to wait?

It's a uncomfortable because of the waiting long time

**Comment by kitty8904** [comment]
<img width="400" alt="two" src="https://user-images.githubusercontent.com/18622105/117144837-621f3980-aded-11eb-9627-fcc73643b9d8.png">

add symbol button click ->The symbol is added two

**Comment by kitty8904** [comment]
Processes with a lot of memory and threads synchronize for a long period of time

Do I have to wait unconditionally?

////////////////////////////////////

Found the cause of crash ntdll,kernel32.dll,kernelbase64

Trigger cow check on
(Activate cow to apply different physical memory to other processes)

1. Run the process
2.Set first breakpoint on kernel32.sleep 10 seconds
3.F5-F9 repeat
4.Process Crash

///////////////////////////////
1.Process execution
2. Set first breakpoint 400000,or 401000
3.set second breakpoint in kernel32.sleep
4.F5-F9 repeat
5. No Process Crash

**Comment by kitty8904** [comment]
video:
https://youtu.be/kGhorM79eq0

**Comment by cheat-engine** [comment]
Intel or AMD ? And can you reproduce this on the tutorial or only this game ?

**Comment by kitty8904** [comment]
intel cpu test

amd not test

i9 9900k

This is a game protected by obregistercallbacks
(private build ce)

8 GB of game memory and 40 threads are used

Crash in the case of a process with a of big memory and many threads

**Comment by kitty8904** [comment]
One of several threads ends the game

Are you ever anti-debugging detection?

dbvm break point no error

dbvm level break point is all error

I don’t know what the difference is crash

**Comment by kitty8904** [comment]
crash video:
https://youtu.be/BgGVgC9d-FI
test file:
[test.zip](https://github.com/cheat-engine/cheat-engine/files/6460872/test.zip)

test api
KERNELBASE.SleepEx - push 38 { 56 }
KERNELBASE.SleepEx+2- push KERNELBASE.lstrcmpiA+76E8 { 76A45998 }
KERNELBASE.SleepEx+7- call KERNELBASE.SetProcessDynamicEnforcedCetCompatibleRanges+8C

KERNELBASE.SetProcessDynamicEnforcedCetCompatibleRanges+8C - push KERNELBASE.invalid_parameter+F0 { (-1957298293) }
KERNELBASE.SetProcessDynamicEnforcedCetCompatibleRanges+91 - push fs:[00000000] { 0 }
KERNELBASE.SetProcessDynamicEnforcedCetCompatibleRanges+98 - mov eax,[esp+10]
KERNELBASE.SetProcessDynamicEnforcedCetCompatibleRanges+9C - mov [esp+10],ebp 
KERNELBASE.SetProcessDynamicEnforcedCetCompatibleRanges+A0 - lea ebp,[esp+10] 

lea ebp,[esp+10] <-here test

dbvm find out -> no error
dbvm level find out -> crash

I found the cause of a similar error with a game with small memory

The cow trigger was activated and the physical memory address was different.

And when I start and finish the game I get an error

Intel CPU
