### ISSUE TITLE
ceserver compile Error

### ISSUE THREAD

**Issue by avboy1337** [cheat-engine/cheat-engine#1567]
in directory of 
cheat-engine/CheatEngine/ceserver/Debug-linux

type command make 
then output is 

> Building target: ceserver
Invoking: GCC C Linker
gcc  -o "ceserver"  ./api.o ./ceserver.o ./ceservertest.o ./context.o ./extensionfunctions.o ./extensionloader.o ./porthelp.o ./symbols.o ./threads.o   -lpthread -lz -ldl
./ceserver.o: In function `DispatchCommand':
/mnt/c/Users/Administrator/Desktop/cheat-engine/CheatEngine/ceserver/Debug-linux/../ceserver.c:977: undefined reference to `AOBScan'
collect2: error: ld returned 1 exit status
makefile:30: recipe for target 'ceserver' failed
make: *** [ceserver] Error 1

**Comment by DoranekoSystems** [comment]
in directory of
cheat-engine/CheatEngine/ceserver/gcc

Modify the makefile slightly.
```
COMPILER  = gcc
CFLAGS    =  -g -MMD -MP -Wall -Wextra -Winit-self -Wno-missing-field-initializers -Doff64_t=__off64_t 
ifeq "$(shell getconf LONG_BIT)" "64"
  LDFLAGS = -lz -ldl -pthread
else
  LDFLAGS = -lz -ldl -pthread
endif
LIBS      =
INCLUDE   = -I../
TARGET    = ./ceserver
SRCDIR    = ../
...
```

```
$ make
```
The ceserver will be compiled.

This is due to the fact that I added an extra file (native-api.c) in the past.
One of these days, it might be better to remove this file.

**Comment by avboy1337** [comment]
bro you checked so quick！
you are really smart！！
