### ISSUE TITLE
x64 kernel stack bug ?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#158]
![1](https://cloud.githubusercontent.com/assets/18622105/22739775/802fe46c-ee50-11e6-80bb-fd4caf57a12c.png)
![2](https://cloud.githubusercontent.com/assets/18622105/22739776/803276d2-ee50-11e6-8966-d9449640e793.png)

obprecallback stack break point return value bug

When you exit the return, you return to the correct return position

However, in the cheat engine kernel stack display window, rsp values point to strange places

Is the error in the kernel stack notation value? A regular PE program will return the correct rsp value

**Comment by cheat-engine** [comment]
probably a bug in the kernelmode debugger.
that is also why i don't recommend using the step in kernelmode feature, it will always crash

**Comment by cheat-engine** [comment]
but try doing a single step after that ret and see what happens

**Comment by kitty8904** [comment]
FFFFF88010A53E0F -> ret -> FFFFF8000387B046 

RSP stack value problem

I know RSP == ret 

Exit to return is accurate

I do not know why the rsp problem
