### ISSUE TITLE
DBVM supported on i7 9700 cpu?

### ISSUE THREAD

**Issue by UrGrannyTranny** [cheat-engine/cheat-engine#1583]
Virtualization based security = disabled
Hyper V = disabled
uninstalled bluestacks
intel vt is enabled
dont have avast
disabled signature enforcement
safe mode allows me to use DBVM 64 so my cpu is supported but idk what is putting my pc into a vm 
anyone help?

**Comment by kitty8904** [comment]
![99040888-c77d2680-253e-11eb-8aa5-3b2c49ae8008](https://user-images.githubusercontent.com/18622105/118326169-90b0b900-b53f-11eb-9955-4b06517893fe.png)

windows defender virtualization check -> disable

**Comment by UrGrannyTranny** [comment]
its off

**Comment by kitty8904** [comment]
cmd.exe administrator run -> bcdedit /set hypervisorlaunchtype off to disable hypervisor

reboot

**Comment by UrGrannyTranny** [comment]
alr doing

**Comment by UrGrannyTranny** [comment]
also mind sending discord?

**Comment by UrGrannyTranny** [comment]
and just if that doesnt work can you send more fixes? rlly want to use DBK64

**Comment by kitty8904** [comment]
happykitty#7752

I can't help you for a long time

**Comment by UrGrannyTranny** [comment]
?

**Comment by avboy1337** [comment]
Try to compile it and dbvm is ok 
I test it on win server 2022 . cpu is 10900k,
It'sok but may be amd is not ok

**Comment by cheat-engine** [comment]
to use dbk64 you need to uninstall vanguard

**Comment by UrGrannyTranny** [comment]
uh its fixed had to go through a bunch of hoops

**Comment by RealIndica** [comment]
> uh its fixed had to go through a bunch of hoops

Mind telling me how you fixed it?

**Comment by ftwftw0** [comment]
> uh its fixed had to go through a bunch of hoops

Hello @sadohat .
I am interested to know how you solved your problem.
