### ISSUE TITLE
With the forum probably staying down, what happens next?

### ISSUE THREAD

**Issue by Zottelchen** [cheat-engine/cheat-engine#159]
There are were of .ct files and many of them are probably no longer maintained, but that doesn't mean that they didn't work. The authors of said tables probably won't be claiming them. Will an archive be provided for all users to download?

For the future maybe the .ct files could be hosted on Github. Everyone could make pull requests to a public repository.
A simple folderstructure like this should be enough: /\<game>/\<author>/ .ct
There would be a new .ct file for every game version. Each author folder would also contain a readme.md which specifies what the tables are going to do.  
At a later point there could also be some sort of system which automatically accepts pull requests of authors in their corresponding folders (which could also check that it only adds/changes .ct or the Readme). 

That would be my idea. Any plans for the future?

**Comment by RayKoopa** [comment]
The fact that forum.cheatengine.org redirects to a non-working GitHub page https://github.com/cheat-engine/cheat-engine is absolutely ridiculous.

**Comment by nolan1989** [comment]
If Darkbyte needs people to help sort through the accumulated CTs, I'd be more than willing to assist.

**Comment by PrinceFroggy** [comment]
I think the forum will go back up soon

**Comment by R1ZL4** [comment]
I've not been on the forums for a while, just tried today, anybody know why they are gone?

**Comment by Zottelchen** [comment]
@PrinceFroggy 
> I think the forum will go back up soon

There is a line in the Readme:
_The forum is down, and may stay down (though I will grant access to people later to get their data)_
It has been there since ~7hours


@R1ZL4 
> I've not been on the forums for a while, just tried today, anybody know why they are gone?

Seems to be mainly a DDOS as well as a Notice of Infringment, as stated by [this tweet](https://twitter.com/_cheatengine/status/836188851722928128). I think there isn't any other statement as of now.

**Comment by Zottelchen** [comment]
The Readme was just updated. Now it states:
*The forum is up/down depending on DDoS attacks and negotiations. In the chance it works, you can read posts at http://174.142.61.111/forum*

**Comment by dmd3** [comment]
go to http://174.142.61.111/forum/viewforum.php?f=4&sid=216b9d435b738f9f2ca845e766abd252 than surch manuly for what you want...it works but its anoying

**Comment by Keith94** [comment]
Forum is back but "Cheat Engine Downloads" section is not available anymore. Any news if it's coming back?

**Comment by Zottelchen** [comment]
@Keith94 from [forum](http://forum.cheatengine.org/viewtopic.php?t=603323):

> With games becoming more and more online and laws are passed constantly to take away your rights to your own possessions, I think it's better to move the tables and trainers section to a place not owned by me.
> 
> Please post suggestions on where.
> Also, cheat tables are pure text, so you should be able to post them anywhere you can post text.
> e.g. : reddit , github, pastebin, facebook
> 
> but someone can also start a new forum, even it's a simple one as freeforums.net
> 
> and if you already have a forum where you can upload tables, that's fine as well
> 
> This is not a topic to complain about it 


@cheat-engine Do you actually read issues?

**Comment by Keith94** [comment]
@Zottelchen Thanks.

There's a new repository with all CT files: https://github.com/Hexorg/CheatEngineTables

**Comment by gabfv** [comment]
It's a bit of a shame that we lost the posts surrounding the tables, there was sometimes quite a bit of information about using the table. The tables for Borderlands were a good example of this. 

However, I think that future tables would be better on github. Just include a readme.md for how to use the table and people can create an issue if they have problems with the table. Tagging commits could be used to specify which game version the table is for. Also, I suppose there could be a way to somewhat translate the forum post into a markdown file or at least a readme.txt file.

All in all, I'm quite glad the tables aren't completely lost though. I wonder, what's @Hexorg's sources for the tables? His own personal backup?

**Comment by cheat-engine** [comment]
the files he has also contains and xml file with the contents of the post of the attachment and other data.
but it looks like he hasn't uploaded that one
________________________________

**Comment by 3dop** [comment]
That repository definitely doesn't have everything. I have at least one Terraria table that I don't see in there.

**Comment by omoikaane** [comment]
How do I download any of the tables?

**Comment by gabfv** [comment]
@omoikaane Assuming you meant [the repository of @Hexorg](https://github.com/Hexorg/CheatEngineTables), you can simply click the green button named **Clone or download** near the top right of the page. It'll open a small window-like widget underneath and there's another button named **Download ZIP**. Do that and it'll contains all the tables of the repository. You'll just need to unzip it somewhere on your computer.

**Comment by Symbai** [comment]
@cheat-engine Since the official forum shut down and redirect to different place I cannot check if my question was answered. What happens to the tables outside of the forum? The tables that we could had downloaded from your main website under the table section? Any chance you can host them somewhere for download?

**Comment by quanturos** [comment]
Anyone know the whereabouts of the .apk? This was previously on the forums, but the link is (obviously) dead now.
