### ISSUE TITLE
Compile error in x64

### ISSUE THREAD

**Issue by mrparag94** [cheat-engine/cheat-engine#1594]
when I press compile it shows this message

frmcr3switcherunit.pas(160,4) Fatal: Cannot open include file "frmCR3SwitcherUnit.lrs"

how to fix that...?

**Comment by cheat-engine** [comment]
move the form and save it

**Comment by mrparag94** [comment]
now having this error... for 32 bit build

tcclib.pas(488,24) Error: Illegal type conversion: "QWord" to "TObject"

**Comment by cheat-engine** [comment]
change it to a ptruint, or compile 64-bit

**Comment by mrparag94** [comment]
Thanks.. It's Solved Now.. 👯

**Comment by avboy1337** [comment]
is there more tips please， i also encountered this

**Comment by avboy1337** [comment]
> move the form and save it

bro , how to move , please i wanna more tips.

**Comment by cheat-engine** [comment]
press f12. move the window.  save

**Comment by avboy1337** [comment]
> press f12. move the window. save

thank you for your generosity
