### ISSUE TITLE
Cheat engine missing path error

### ISSUE THREAD

**Issue by ThatDogGuy** [cheat-engine/cheat-engine#1596]
This comes up when I try to run it, I've uninstalled badlion, and disabled my non existent antivirus, (and also heres bla.txt if you were going to check it) sorry if this is a bad question

[bla.txt](https://github.com/cheat-engine/cheat-engine/files/6546231/bla.txt)

![cheat engine error](https://user-images.githubusercontent.com/84847651/119650284-03e8e380-bdfa-11eb-9f64-fc466fd404f4.PNG)

**Comment by cheat-engine** [comment]
disable `reputation based protection` in windows

**Comment by ThatDogGuy** [comment]
thanks a ton, it worked
