### ISSUE TITLE
Cannot Use

### ISSUE THREAD

**Issue by moestrike** [cheat-engine/cheat-engine#1598]
i dont have badlion and i still cannot use it what do i do?

**Comment by cheat-engine** [comment]
what specific error do you get?

if nothing, it's likely still badlion 
if access denied,  you need to disable `reputation based protection `

**Comment by moestrike** [comment]
> what specific error do you get?
> 
> if nothing, it's likely still badlion
> if access denied, you need to disable `reputation based protection `

i figured it out thank you though
