### ISSUE TITLE
CE installation program cancels download after successful installation

### ISSUE THREAD

**Issue by JustTunerYT** [cheat-engine/cheat-engine#1599]
For some reason, CE install program deletes installed CE data after it downloads them. Pics below show size of available space before/after CheatEngine72.exe

Before CheatEngine72.exe:
![Before CE](https://user-images.githubusercontent.com/63610557/120064484-cef0c100-c085-11eb-9ea5-978ed8cb69a4.png)

CheatEngine72.exe running:
![Program running](https://user-images.githubusercontent.com/63610557/120064492-dadc8300-c085-11eb-8a40-0393f4cab685.png)

Installation completed:
![Installation complete](https://user-images.githubusercontent.com/63610557/120064505-e62fae80-c085-11eb-9944-2d3b57dd55cd.png)

CheatEngine72.exe closed:
![After CE](https://user-images.githubusercontent.com/63610557/120064514-f6e02480-c085-11eb-9180-117b23e7f2eb.png)

**Comment by cheat-engine** [comment]
have you disabled `reputation based protection`?

Do you have an anti virus ?

**Comment by JustTunerYT** [comment]
I don't know, if i have it "reputation based protection"

Built-in Win10 AV says nothing about CE

**Comment by cheat-engine** [comment]
press start and type in reputation based protection  or go to app &  browser control>reputation based protection settings, and disable at least potentially unwanted app blocking, and perhaps the other options as well if it keeps being deleted

**Comment by JustTunerYT** [comment]
Whoops, found it turned on. Disabled now. Turns out, CheatEnigne72.exe didn't even tried, because it was blocked. Installed and works now.
