### ISSUE TITLE
[bug?] Debug registers cleared when VEH is enabled with page exceptions

### ISSUE THREAD

**Issue by BlackBunnyHunter** [cheat-engine/cheat-engine#1600]
the debug registers dr0 dr1....dr7 all get cleared in the debugeventhandler.pas even when page exceptions are used as breakpoints.
Can someone confirm wether this is a bug or not?

**Comment by cheat-engine** [comment]
is the checkbox: override existing breakpoints enabled in settings?

**Comment by BlackBunnyHunter** [comment]
> 
> 
> is the checkbox: override existing breakpoints enabled in settings?

Yes that must be it then
