### ISSUE TITLE
2 symbol cannot resolved __stdio_common_vswprintf and __stdio_common_vswprintf_s

### ISSUE THREAD

**Issue by avboy1337** [cheat-engine/cheat-engine#1606]
1>IOPLDispatcher.obj : error LNK2019: 无法解析的外部符号 __stdio_common_vswprintf，函数 _vsnwprintf_l 中引用了该符号
1>ultimap2.obj : error LNK2019: 无法解析的外部符号 __stdio_common_vswprintf_s，函数 _vswprintf_s_l 中引用了该符号
1>..\Cheat Engine\bin\DBK64.sys : fatal error LNK1120: 2 个无法解析的外部命令

**Comment by avboy1337** [comment]
solved

**Comment by botao1995** [comment]
咋解决的

**Comment by ftwftw0** [comment]
> solved

Hello !
How did you solve it ?
Thanks
