### ISSUE TITLE
cheat engine x64 return value display fix?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#162]
![return](https://cloud.githubusercontent.com/assets/18622105/23639326/6ff2b7de-032a-11e7-84fa-71be0d87a2e3.png)

tutorial i386 return value Display multiple return value address

tutorial x86_x64 only one return value address Display

Only one 64-bit return value is displayed

**Comment by cheat-engine** [comment]
probsbly because the tutorial is not build by a microsoft compiler, and the stackwalk64/ex api in windows doesn't know how to walk that stack

**Comment by kitty8904** [comment]
okay, The use of the stack walk feature is difficult on 64-bit

===========================================
Disable apc, handle, and watch in the latest build version

Is it difficult to add handle bypass?

There is a source that can remove the protected handle

https://github.com/JackBro/ObRegisterCallBacksByPass

In conclusion, it is not possible to circumvent the protected handle state. I'm curious about this.
