### ISSUE TITLE
Can't load DBVM

### ISSUE THREAD

**Issue by mrparag94** [cheat-engine/cheat-engine#1625]
i am having this kind of problem any idea how i can solve it...?

using 7.3 B 3.0.0 Compiled Version

![image](https://user-images.githubusercontent.com/72906386/120793372-9f93f580-c558-11eb-90ca-f4d14e0e9c3c.png)

![image](https://user-images.githubusercontent.com/72906386/120793552-d538de80-c558-11eb-83c8-2d5f9f4707b7.png)

![image](https://user-images.githubusercontent.com/72906386/120793603-e7b31800-c558-11eb-81dc-5aa8cda5e7d8.png)

**Comment by cheat-engine** [comment]
compile ce in release mode or remove the novmx define from the debug build custom options

**Comment by avboy1337** [comment]
应该没啥问题的，我试过了，没这个提示。

**Comment by mrparag94** [comment]
vmdisk.img i don't have it and when I tried to compile it seems to me I can't compile it from the source in windows 10 either... i download eclipse to open the project to compile and it gives me the following cmke error

19:27:32 **** Build of configuration Default for project dbvm ****
make efiusb clean install qemu 
MAKE Version 5.43  Copyright (c) 1987, 2019 Embarcadero Technologies, Inc.
	make -C vmm -f mkx all SERIALPORT=0 DISPLAYDEBUG=0
MAKE Version 5.43  Copyright (c) 1987, 2019 Embarcadero Technologies, Inc.
Incorrect command line argument: -C

**Comment by avboy1337** [comment]
bor , you are going to  compile the dbvm?

**Comment by mrparag94** [comment]
@avboy1337 i can't compile it either ubuntu or debain or any other os... i am having this error... can you explain what could be the problem is...?

https://user-images.githubusercontent.com/72906386/120959613-fe858480-c77b-11eb-89f1-74e612cc36a2.png

**Comment by avboy1337** [comment]
老哥加我微信avboy1337
我给你弄一下

**Comment by avboy1337** [comment]
> @avboy1337 i can't compile it either ubuntu or debain or any other os... i am having this error... can you explain what could be the problem is...?
> 
> https://user-images.githubusercontent.com/72906386/120959613-fe858480-c77b-11eb-89f1-74e612cc36a2.png

bro , if conveniently , use wsl is ok.
beacuse wsl is on win ,a bit more conveniently .
and just one compiling command is ok:

# 进入dbvm目录
sudo apt install yasm nasm mkisofs -y
make clean cdimage
# bootloader.bin 1KB
# vmcd.iso 1796KB
# vmdisk.img 353KB
# vmdisk144.img 1440KB
# vmloader.bin 15KB
# vmloader.map 6KB
# vmm.bin 336KB
# vmm.map 146KB

**Comment by mrparag94** [comment]
@avboy1337 didn't work same message.....

**Comment by avboy1337** [comment]
> @avboy1337 didn't work same message.....

use ubuntu16.04 please

**Comment by mrparag94** [comment]
> > @avboy1337 didn't work same message.....
> 
> use ubuntu16.04 please

It Works.. Thanks.... :)
