### ISSUE TITLE
dbvm level windows api bsod

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1626]
DBVM LEVEL DEBUG

There is an unknown error in F5-F9 repeat

Cow Trigger ON
Targeted Process ON
Kernel Breaks OFF

kernel32.sleep -> F5-F9 Loop -> Go to address KernelBase.Sleep -> F5- F9  Repeat Loop -> Kernel32.sleep F5-F9 Repeat Loop

Kernel32->KernelBase->Kernel32->KernelBase F5-F9 Repeat Loop -> Windows API BSOD

Change address value in Windows API

If you repeat F5-F9, the PC system stops

Looks like an initialization or unknown thread issue

Find What Access works -> No BSOD

The system stops when repeating F5-F9

It doesn't happen 100% If you try several times, BSOD

**Comment by kitty8904** [comment]
no bsod test

1. cow Trigger Physical Address Change kernel32.sleep->kernelbase.sleep->kernelbase.sleepex->ntdll.ZwDelayExecution
2. DBVM Active Clock Page-> kernel32.sleep->kernelbase.sleep->kernelbase.sleepex->ntdll.ZwDelayExecution
3. F5~F9 dbvm level break point repeat -> No Bsod

Change physical address and set memory clock Page -> Breakpoint Test -> Not Blue Screen(clock watchdog Error)

///////////////////////////////////////

windows api not clock page -> kernel32.sleep f5-f9  -> kernelbase.sleep f5,f9 ->BSOD or ntdll.ZwDelayExecution f5,f9 -> BSOD

This is an unknown error

**Comment by cheat-engine** [comment]
best stay away from apc's

**Comment by kitty8904** [comment]
kernel32.dll F5~F9 wait 10sec -> kernelbase.dll F5-f9 -> no bsod

Breakpoints do not bluescreen after delay time

kernel apc? Is there a problem with apc?

unknow bug

///////////////////////////////////////////

Finally, if the kernel windows API blue screen does not occur

No more big bugs in dbvm-level debugging

I hope it gets resolved
