### ISSUE TITLE
Porting to iOS

### ISSUE THREAD

**Issue by DoranekoSystems** [cheat-engine/cheat-engine#1632]
By rewriting ceserver in python, I was able to port it to iOS using frida in a limited way.
Can I publish this on my github?
Of course, I will specify that the original is by dark byte.

![img](https://user-images.githubusercontent.com/56913432/120922062-11f40980-c702-11eb-93fc-52f20a5bd314.png)

**Comment by DoranekoSystems** [comment]
Or I can commit to this project.
Would something like the above be acceptable?

**Comment by cheat-engine** [comment]
sure. you can publish it, or commit here.  ot's good to shiw different ports
