### ISSUE TITLE
Android emulator VT conflicts with DBVM VT

### ISSUE THREAD

**Issue by Cmpote** [cheat-engine/cheat-engine#1638]
Turning both of these on at the same time will shut down the computer.

**Comment by cheat-engine** [comment]
yup. Which CPU.  AMD or Intel?  Intel has a half assed other VM support, AMD has none)

**Comment by Cmpote** [comment]
> 是的。哪个CPU。AMD还是英特尔？Intel dbvm 有一半的其他 VM 支持，AMD dbvm 没有）

AMD CPU .IIt seems that the Android emulator game cannot be modified without opening dbvm.

**Comment by avboy1337** [comment]
老哥用的啥系统？我也测一下。

**Comment by Cmpote** [comment]
> 老哥用的啥系统？我也测一下。

windows 7 x64

**Comment by zzcc1002** [comment]
I have the same problem.
Did you solve it?

**Comment by DarkHex999** [comment]
still facing the same problem , i found a small solution It may replace the use DBVM , its using cheat engine server , but most AAA games detect it

**Comment by cheat-engine** [comment]
also: `It seems that the Android emulator game cannot be modified without opening dbvm.` that line is bullshit. DBVM has no effect here whatsoever

**Comment by DarkHex999** [comment]
> also: `It seems that the Android emulator game cannot be modified without opening dbvm.` that line is bullshit. DBVM has no effect here whatsoever

DBVM is very important if u need make real cheat for android game 
if u connect cheat engine directly for the process
you will never get a  static address or pointer because the emulator remap everything,
but with DBVM you can attach cheat engine with the physical memory isntaed of emulator process

**Comment by towy** [comment]
> still facing the same problem , i found a small solution is might It may replace the use DBVM , its using cheat engine server , but most AAA games detect it

In my region, online games have generally entered a stage of kernel-level confrontation, where conventional memory reading will cause the game to crash.

**Comment by cheat-engine** [comment]
> > also: `It seems that the Android emulator game cannot be modified without opening dbvm.` that line is bullshit. DBVM has no effect here whatsoever
> 
> DBVM is very important if u need make real cheat for android game if u connect cheat engine directly for the process you will never get a static address or pointer because the emulator remap everything, but with DBVM you can attach cheat engine with the physical memory isntaed of emulator process

Have you tried just checking kernelmode read write memory and kernelmode openprocess?  That also makes [Physical Memory] available without the need for DBVM
