### ISSUE TITLE
the newest compile error

### ISSUE THREAD

**Issue by avboy1337** [cheat-engine/cheat-engine#1646]
Compile Project, Mode: Release 64-Bit O4 AVX2, OS: win64, CPU: x86_64, Target: bin\cheatengine-x86_64-SSE4-AVX2.exe: Exit code 1, Errors: 2, Warnings: 2
MainUnit.pas(5612,32) Warning: Symbol "AppHandle" is not portable
MainUnit.pas(5612,32) Warning: Symbol "AppHandle" is not portable
memscan.pas(7609,25) Error: Incompatible types: got "TMemScan" expected "Tscanfilewriter"
memscan.pas(7610,22) Error: Compilation raised exception internally

**Comment by MrSmithr** [comment]
Lazarus is so buggy :(

**Comment by avboy1337** [comment]
> Lazarus is so buggy, I ended up rebuilding the project which removed this error. Shift+F9 to rebuild.

you are totaly right , but may be this time it is different i think.
recompiled many times and failed

**Comment by MrSmithr** [comment]
I've set compilation settings to Release 64-bit O4 AVX2 and it builds/compiles just fine. It's worth trying that.

**Comment by avboy1337** [comment]
Sorry its my fault , i delete all files and recompiled , all is OK

**Comment by Theo1996** [comment]
I am adding this for other people who have issues building. The build instructions are ,I think, incorrect.
 Build instructions. That actually worked. Laz 2.2.2 and the latest 3.0rc does not work.For 32-bit builds add an install of the respective version cross i836
-LAZARUS 2.2.0 and fpc  3.2.2 for 7.5 AND "virtuatreeview "package fron the net! "laz.virtualtreeview" is already installed but is a completely diffferent package!It has laz. in front!
-LAZARUS 2.0.10 and fpc3.2.0  for 7.3 and 7.4
