### ISSUE TITLE
[Feature Request] Trainer Icon + DPI + Detection

### ISSUE THREAD

**Issue by ZuixAlias** [cheat-engine/cheat-engine#1648]
Need to be able to change icon of the trainer shown in task manager via lua/ automatic change to the same icon as in taskbar.

Also, change dpi of the generated trainer/ saved .exe to same as when editing the trainer...as, when it is done using SetProcessDPIAware(), it rescales it to 100%...so if the user is using 125% scaling or any other, the trainer should be able to adjust accordingly (something like form.AutoScaleMode = asmDPI/ form.DPIScaling = true/ something else or anything that works). This one will be incredibly useful + the icon one...!

If possible, not include the files that make antiviruses detect the trainer...like if that detectable package is not needed then exclude it/ if it is needed for trainer to run then maybe try using it as a code file for the generated/ saved .exe trainer.

The above mentioned 3 features, I think, will encourage many people to use celua for making publishable bots/ trainers/ gui apps instead of other languages due its portability, fast work, etc...as for me personally, it would be super super useful!

**Comment by cheat-engine** [comment]
The thing that makes anti viruses detect it is the part that makes it able to run as an standalone executable.
without it you can only distribute it as a .cetrainer

**Comment by ZuixAlias** [comment]
Oh okay, it's fine then...but please look into the icon and dpi stuff...

**Comment by cheat-engine** [comment]
for DPI stuff call the lua function `formname.fixDPI()` it will adjust all controls based on the current DPI  (Don't use this on forms that are designed with different DPI in mind from the start)

**Comment by ZuixAlias** [comment]
Okay, I understand. The method **formname.fixDPI()** is not valid. Am I missing something??
![Screenshot (47)](https://user-images.githubusercontent.com/84643454/121866965-154c4e00-cd1d-11eb-9f06-c01a0d4f116c.png)
![Screenshot (48)](https://user-images.githubusercontent.com/84643454/121866980-18473e80-cd1d-11eb-93f4-e9564fc8f947.png)

**Comment by cheat-engine** [comment]
it's in next version (or if you compile this, or get the 7.3 beta)

**Comment by ZuixAlias** [comment]
Ohh!! That's super cool! Thanks brother...can't wait for it now XD, just saw that it has dark mode too...amazing!

I will close this issue now okay...
