### ISSUE TITLE
show all saved scanresults at the same time bug

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1649]
<img width="529" alt="crash" src="https://user-images.githubusercontent.com/18622105/121968269-f7c6c500-cdac-11eb-97f9-80cedb7f7c3e.png">

target: explorer.exe , cheatengine64bit.exe,lazarus.exe

Scan option
Writable -> Gray
ExecuteTable-> Gray

Fast scan -> un check

Scanvalue : 1

first scan click -> cheat engine crash dead

in some 64-bit processes

If you set the scan option as above, the process error occurs during the first search.

Cheat engine terminate

**Comment by cheat-engine** [comment]
can you provide the cedebug.txt file when the error has occurred?

**Comment by kitty8904** [comment]
> can you provide the cedebug.txt file when the error has occurred?

Exception No first scan data files found
  Stack trace:
  $00000000007DC391
  $00000000007F3C10  DOWINDOWPROC,  line 1992 of win32/win32callback.inc
  $00000000007F5877  WINDOWPROC,  line 2676 of win32/win32callback.inc
  $00007FFA3680E858 ->user32.CallWindowProcW+3F8 
  $00007FFA3680E299 ->user32.DispatchMessageW+259 
  $00000000007F69BE  APPPROCESSMESSAGES,  line 410 of win32/win32object.inc
  $0000000000472207  HANDLEMESSAGE,  line 1280 of include/application.inc
  $00000000004726F7  RUNLOOP,  line 1417 of include/application.inc
  $000000000080725B  APPRUN,  line 54 of include/interfacebase.inc
  $00000000004726C6  RUN,  line 1405 of include/application.inc
  $0000000000404864  main,  line 391 of cheatengine.lpr
  $00000000004048B6
  $000000000041A350
  $0000000000403D27
  $00007FFA358E7034 ->KERNEL32.BaseThreadInitThunk+14 
  $00007FFA36C82651 ->ntdll.RtlUserThreadStart+21
