### ISSUE TITLE
Cheat Engine 7.2 Where installed ?

### ISSUE THREAD

**Issue by LordLutz** [cheat-engine/cheat-engine#1657]
I did the installation of CE 7.2 - and then no automatic start happens. What install path has it ? I can´t find anything, no exe-file, nothing. I use Win10 and want to know how to start it manually. Pls help ! Thanks for any reply !

**Comment by munuc** [comment]
Same thing happened for me. Defender flagged it as dangerous, I let it run, installed it normally, and nothing showed up where it should've.

**Comment by cheat-engine** [comment]
Besides defender also disable reputation based protection

**Comment by LordLutz** [comment]
Now it works. Reason was, I had deactivated only the app protection, it seems to be installed but it only seems to be but the installation was interrupted at start. After I had deactivated every app protection in windows it was installed well and runs perfectly. Thanks to Dark Byte for the help (u r a great 1). Hope this helps everyone !
