### ISSUE TITLE
implementation of the last dbvm bsod

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1659]
100% BSOD error

but there are conditions

BSOD Conditions Unity Sample Game

https://github.com/Unity-Technologies/FontainebleauDemo/releases/tag/v0.0.0

Window Mode 1920 x 1440

Cinematic Mode

Cheat Engine Execute -> DBVM Level Mode Check 
COW Mode ON
Targeted Process Mode ON

KERNELBASE.SleepEx+8F - 48 8D 54 24 20        - lea rdx,[rsp+20] 

KERNELBASE.SleepEx+8F F5 Break Point -> F9 Run -> Repeat -> Delete F5 break Point

-> Less than 3 seconds address -> ntdll.ZwDelayExecution F5 Break Point -> F9 Run -> Repeat -> Delete F5 Breakpoint 

-> Repeat -> KERNELBASE.SleepEx+8F

After several iterations, the system hangs with Watch Dog Time Out.

####################################################

In single-threaded games, the above blue screen problem does not occur

multi-thread game -> maybe BSOD

If I delete the debug, is there a lag on the debug delete Shadow Break Point?

Pending deletion Time?

No more problems other than this while debugging in DBVM -LEVEL mode

Once this is resolved, there will be no more major problems when debugging

#####################################################

After deleting KERNELBASE.SleepEx+8F breakpoint

-> Wait 10 seconds -> ntdll.ZwDelayExecution -> No Bsod?(Not sure)

**Comment by kitty8904** [comment]
100% condition

one single thread break point no blue screen
(threadid only 1040)

Problems in multithreading blue screen
(threadid 1040,2058,6920,5820)

**Comment by cheat-engine** [comment]
I have not been able to reproduce this with the demo yet
what do you mean with F5 Break Point -> F9 Run -> Repeat -> Delete F5 break Point

what is repeat?  Press f9 one more time?

Try this dbvm image. Perhaps it's a compiler issue, or you made a custom modification I don't know about: [vmdisk.zip](https://github.com/cheat-engine/cheat-engine/files/6692065/vmdisk.zip)

**Comment by kitty8904** [comment]
I have not been able to reproduce this with the demo yet

[TEST32BIT.zip](https://github.com/cheat-engine/cheat-engine/files/6692668/TEST32BIT.zip)

It is a program and source reproduced in C+.

100% BSOD on 32bit

kernel32.sleep -> F5 -> F9(32threadloop)-> Delete F5 Breakpoint -> Kernelbase.sleep -> F5 -> F9(BSOD)

**Comment by kitty8904** [comment]
bsod video:
https://youtu.be/3osv-xBbYEw

**Comment by cheat-engine** [comment]
try the last commit and let me know if this works better or not (it's not the  solution, but will help me pinpoint where it could go wrong, e.g could be a threading issue inside CE, or a CPU cache issue, or both)

**Comment by kitty8904** [comment]
[vmdisk.zip](https://github.com/cheat-engine/cheat-engine/files/6703129/vmdisk.zip)

-test-

Temporary test to check if a certain crash github

Doesn't work and causes BSOD the same

Unknown crash bug

**Comment by kitty8904** [comment]
fix brokenthreadlist realloc -> compile

Test result

No blue screen 

Close the issue?
