### ISSUE TITLE
Feature request: Unstable address elimination, reduction mode?

### ISSUE THREAD

**Issue by PlNG** [cheat-engine/cheat-engine#166]
Working with stable address values, it can be difficult to locate the desired address that uses a low number without a lot of changes, meanwhile there are addresses constantly flipping between values and then back to the desired value.

It would really decrease the need to enter searches.

Remove an address after X changes after a search?

**Comment by imm0r** [comment]
Not a bad idea!

**Comment by FreeER** [comment]
Interesting idea, would cause issues if left on for timer searches and the like that are expected to change regularly but it should be useful for most searches.

**Comment by cheat-engine** [comment]
you can also assign a hotkey to unchanged value scans and constantly hold it down while in the game. (or use a lua script that runs a timer that does that scan for you)
