### ISSUE TITLE
dbvm level debug find out bug

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1663]
dbvm level debug 

1. find out what access f5 break point -> result address -> stop debug
2. find out what write f6 break point -> result address fail or Debugging function stops-> stop debug 
3. f5 break point or f6 break point -> no result address or debug function error

F5 Access -> STOP -> F6 Access -> STOP -> F5 or F6 Break point Access Error

There is a problem when using F6 debug after using F5

Debug function does not work normally

**Comment by kitty8904** [comment]
debug error video:
https://youtu.be/2Dt4e3zMnMs

**Comment by kitty8904** [comment]
https://github.com/cheat-engine/cheat-engine/commit/e65926f4d5717fd43c01625c55e2250edaba5ec1

fix breakpoint with children deletion <- maybe Debug Error commit

There seems to be a problem after commit fix breakpoint with children deletion

**Comment by cheat-engine** [comment]
should work better now

**Comment by kitty8904** [comment]
Debug address output now displays properly
