### ISSUE TITLE
Vs2019 building dbvm

### ISSUE THREAD

**Issue by botao1995** [cheat-engine/cheat-engine#1669]
hi, in the current project, how to build dbvm through vs2019？

**Comment by cheat-engine** [comment]
i don't know vs2019 can compile dbvm.  It needs to compile using System V AMD64 ABI while vs2019 uses microsoft ABI

i compile dbvm on linux

**Comment by botao1995** [comment]
> i don't know vs2019 can compile dbvm. It needs to compile using System V AMD64 ABI while vs2019 uses microsoft ABI
> 
> i compile dbvm on linux
Thank you for your reply. Can you support Microsoft ABI in the future? Compiling with vs2019
