### ISSUE TITLE
Enhancement: add ability to name function calls

### ISSUE THREAD

**Issue by keisuke112** [cheat-engine/cheat-engine#1672]
Memory viewer currently shows the names of some functions in the disassembler such as:
   call KERNELBASE.IsDebuggerPresent

I think it would be useful to be able to name a function instead of viewing just the memory address:
From this:
   call 7FFDC64C1F04
To this:
   call gamename.exe.text.AddHealth

**Comment by cheat-engine** [comment]
it already does that. 
if you register a symbol named  gamename.exe.text.AddHealth with address 7FFDC64C1F04
and make sure 'show symbols' is checked, it will show the call instruction like `call gamename.exe.text.AddHealth`
