### ISSUE TITLE
dbvm_ept_reset bsod?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1676]
bsod percent : random??

1. dbvm load

2. target process execute

3. dbvm_cloak_activate

4. dbvm_ept_reset call

5. target process exit

6. target process re execute

7. dbvm_cloak_activate ->  BSOD

Call dbvm_ept_reset function -> call dbvm_cloak_activate function Blue screen

Random percent blue screen

Any errors in dbvm_ept_reset ?

Or is it a dbvm_cloak_activate error?

I don't know the cause

target prcoess: 32, 64 all process error

test os : windows 10 21H1

cpu  : intel

**Comment by kitty8904** [comment]
int ept_cloak_removechangeregonbp(QWORD physicalAddress)

QWORD physicalAddress =physicalAddress & MAXPHYADDRMASKPB; -> add??

In the ept_cloak_removechangeregonbp function
MAXPHYADDRMASKPB variable does not exist?

**Comment by cheat-engine** [comment]
No, change reg on breakpoint is address specific, not page specific .  (there can be more than 1 change reg on bp in the same page)

Only cloak is page specific, but removing a changeregonbp should not remove any cloak

**Comment by kitty8904** [comment]
1.Activate the page cloak with dbvm_cloak_activate

2.Then change the value

3.And when the target process is terminated, dbvm_ept_reset is automatically called

4.target process reload 

5.dbvm_cloak_activate -> BSOD

After re-running the process, if dbvm_cloak_activate is activated, BSOD

active & remove changeregon bp function is not called

EPT pagetable out memory?

NO 100% BSOD, RANDOM BSOD

**Comment by cheat-engine** [comment]
Check the memory pages for dbvm
If the physical address changes, cloaking the page may take cpucount*4 pages to map the memory on 4kb ept pagetables

if this happens frequently and you don't add more memory to dbvm you'll crash

**Comment by kitty8904** [comment]
How do I allocate more add memory to DBVM?

Is there a function to check?

**Comment by cheat-engine** [comment]
dbvm_addMemory(pagecount) adds memory in blocks of 4kb (needs the driver. otherwise you have to set it at loadtime)

It also returns the current amount of free memory for dbvm. (I think you can use 0 to just query how much is left without allocating)

**Comment by kitty8904** [comment]
dbvm_cloak_activate -> reset repeat

count = dbvm_addMemory(0)
print(count)

count = 300  ... 200 ... 100... 50... 10...

100%BSOD

count = -10 > 0

Dark Byte as you say

100% BSOD when the allocation area is less than 0

There is a problem with the allocation area recovery

1.First memory pages 600

2.dbvm_cloak_activate -> Pages 550

3.dbvm_ept_reset ->Pages 553

with dbvm_ept_reset

Only 3 pages have been restored

more repeat -> decrease the of pages

You can increase the page with dbvm_addMemory, but

Is recovery from dbvm_ept_reset impossible?

///////////////////////////////////////////////

The cause of BSOD has been found

check the page count, but

I'm curious for a better solution

**Comment by kitty8904** [comment]
There is a problem with the DBVM-LEVEL Debug structure

1. DBVM LOAD Page count 600

2. DBVM Level F5 Breakpoint and Find out What access -> Page count dec -> 600 -> 550~500

3. Target Process Terminate

4. Target Process ReLoad -> Page count 500~550

5. Repeat Breakpoint and Find out what access -> 400~450

6. Count < 0 -> BSOD

if the allocated memory area becomes less than 0, blue screen 

Check and increase the DBVM page allocation size, or

it must be restored to original Page size

error Alloc Page Size restore?

**Comment by cheat-engine** [comment]
it's correct.  DBVM just doesn't start out with all the memory it needs

Let's say you have 128GB RAM
To map that you can use 1 page (4kb)  with 128 1GB entries and that's it.  (DBVM tries to do that where it can)

but to use find what access/cloak the memory has to be described using a 4KB range

so a 1GB entry then has to point to a page filled with 512 2MB entries, and each one of thise has to point to a page holding 4KB entries

if you want to map 128GB memory as 4KB then you need 1 page for the 1GB entries.  128 pages holding 2MB entries, and 128*512 pages holding the 4KB page entries
so: 1+128+128*512=65665 pages ( so 268.963.840 bytes)

now since ept paging has to be done uniquely for each cpu multiply this by the amount of cpu's you have.
so lets say you have 32 cores, that'd mean 65665*32=2101280 pages (so 8.606.842.880)

so, if you where to preallocate all the memory DBVM needs to fully map all 128GB physical memory you'll have to sacrifice 8GB RAM
(not much if you have 128GB but some people tend to make a fuss about that)

**Comment by kitty8904** [comment]
DBVM-LEVEL must have page table memory check function

Does not automatically increase the current page memory

check page memory and increase page memory?

**Comment by kitty8904** [comment]
Found one more bug

DBVM FIND OUT What Acesss read & write

Log Stack Check -> Page table memory Size Low

1.  500 page Size 
2.  Log Stack Check DBVM FIND OUT What Acesss read & write -> 382 Page Size
3.  page size 150 down
4.  dbvm_ensure_pages_free GetCPUCount*3
5.  8core 16thread -> allocateMemoryForDBVM page count 16 * 3 *  2  -> 96
6.  EX) page size 40 + 96 = 136 < 150 
7.  Computer freezes due to low page memory

allocateMemoryForDBVM(pagecount*2); -> allocateMemoryForDBVM(pagecount*5) ?

16 * 3 * 2 -> 96 <   log stack page size 150
16 * 3 * 5 -> 240 > log stack page size 150

The solution I thought of was because of the log stackview

allocateMemoryForDBVM I think you need to increase the allocated memory

**Comment by kitty8904** [comment]
log stack view ON -> requires a minimum page size of 150

8core 16thread ->16 * 3 * 2  = 96 < 150
4core 8thread -> 8 * 3 * 2  =  48 < 150

allocateMemoryForDBVM(pagecount*2); -> allocateMemoryForDBVM(200+pagecount*2);

Because of the log stack view, you need to declare a minimum size of 150-200 and add the rest of the size after it
