### ISSUE TITLE
Activating Mono features on Vambrance - Cold Soul makes Cheat Engine lock up/freeze

### ISSUE THREAD

**Issue by minkshaman** [cheat-engine/cheat-engine#1677]
I have no idea why this is the case.

A commenter [here](https://fearlessrevolution.com/viewtopic.php?t=11830) said it worked in CE 7.0

I've tried on the GoG version and the EA Desktop version. 
Both have the same issue, with and without any tables already added.

(Yes, I'm aware of the irony of the game name/issue)

Edit:
I forgot to mention, I've waited over 20 mins at one point, still nothing.

**Comment by cheat-engine** [comment]
try deleting dotnetdatacollector64.exe

**Comment by minkshaman** [comment]
That did it!
