### ISSUE TITLE
detecting VMX

### ISSUE THREAD

**Issue by chico-depressive** [cheat-engine/cheat-engine#169]
hi sir, thanks for your tool

how do you detect VMX(dbvm) support AND if is enabled in bios?

**Comment by cheat-engine** [comment]
rightclick the CE logo in cheat engine and the about window will pop up. It will contain text stating if your system supports VMX

to see if it's disabled in the BIOS run this lua script: (assuming you're on Intel)
```
dbk_initialize()
r=dbk_readMSR(0x3a)

if (r & 4 == 4) then print("it should work") else print("no. Disabled in the BIOS") end
```

**Comment by chico-depressive** [comment]
thank you, reading msr register can be done in usermode?

**Comment by cheat-engine** [comment]
i think reading msr's can only be done in kernelmode, (BUT if dbvm is loaded you can do it in usermode as well)

for AMD i'm not sure there is a way to check

and for windows API, none that i know off.
But you can load dbvm at boottime before windows boots. Then you won't need to make a driver
