### ISSUE TITLE
win10 x64 build  DBKKernel x64 release error

### ISSUE THREAD

**Issue by botao1995** [cheat-engine/cheat-engine#1697]
![QQ图片20210714105345](https://user-images.githubusercontent.com/47848566/125553562-a441e5de-25db-4f6f-a806-0c4445e46e9a.png)

**Comment by cheat-engine** [comment]
disable the driver signing option for the driver build process, or adjust it to use your own codesigning certificate

**Comment by botao1995** [comment]
> disable the driver signing option for the driver build process, or adjust it to use your own codesigning certificate

thanks
