### ISSUE TITLE
"Code Filter" Exception Access Violation

### ISSUE THREAD

**Issue by Shroototem** [cheat-engine/cheat-engine#1721]
I seem to not understand how to fix this issue with Code Filter.
When I do the initial scan I use "From disassembler" and save that list to a file. Then start the process and run into a breakpoint. I'm very unsure of what exactly is going wrong here.
![image](https://user-images.githubusercontent.com/47718633/127282938-6dc557b7-2ff6-48f7-97e0-7c2571cd86b9.png)

**Comment by cheat-engine** [comment]
From disassembler isn't the best source.  Unwind info is recommended.

Anyhow, check which of the breakpoints landed inside the instruction that causes an exception  and remove that one.  Then restart the process and try again (keep the list, don't disassemble again)

**Comment by Shroototem** [comment]
Unwind info shows nothing and I'm not really sure what I'm looking for with the breakpoints.

**Comment by Shroototem** [comment]
Issue is too old to continue

**Comment by Ezriral** [comment]
I hope its okay to tag you, with this specfic question. @cheat-engine 
Since i also get this error i thought this is the right place to report and ask.

Is it already available for Android ceserver (no emulator, Anroid 10)

![image](https://user-images.githubusercontent.com/56836301/173187481-ed6b9d6f-66d4-4e32-a31a-a35784f397c9.png)

**Comment by DoranekoSystems** [comment]
Since the software breakpoint for arm is not 0xCC, Code Filter should not work.

**Comment by Ezriral** [comment]
@DoranekoSystems thank you for your answer i can see that you know a bit about android processors, Good point that android doesnt use the same opcodes for it. So while im thinking of changing simply the address in CE (windows) at this position maybe?

`frmcodefilterunit.pas`
`function procedure TWorker.enableAllBreakpoints;`
`code`
`
    //set the bp
    WriteProcessMemory(processhandle, pointer(address), @cc,1,x);
    inc(position);   
`

another question would be is it even available in ceserver?

**Comment by Ezriral** [comment]
@cheat-engine since i didnt get any further help, would it be possible to add this at some point. I guess the function CodeFilter is a really helpful tool. Thank you. Btw im sorry again for tagging but this was the last time i tag you on topic.

**Comment by DoranekoSystems** [comment]
It may be possible to assemble something similar using frida.
Interceptor.attach instead of software breakpoints.
If I create one, I will show it here.
