### ISSUE TITLE
when open process , cheatengine_x86_64_SSE4_AVX2 will exit automatially

### ISSUE THREAD

**Issue by avboy1337** [cheat-engine/cheat-engine#1726]
may be it is crashed , i am going to attach windbg and have a look, it shows as follows:
I am not versure but ce7.2 release version is ok and wont crash
![image](https://user-images.githubusercontent.com/5463104/127940030-fb8cba75-8882-4657-9672-b397b2b7d1b9.png)

**Comment by cheat-engine** [comment]
debug with CE and check the stacktrace as this looks like an invalid code address

**Comment by avboy1337** [comment]
https://drive.google.com/file/d/1wQxq_rsVNAT-kny656AHZDi1zxTpoZBL/view?usp=sharing
this file can crash CE7.3 , the newest i build .

**Comment by cheat-engine** [comment]
delete the pdb
if it doesn't crash then anymore find the dbghelp and imghelp dll's used by your compiler and put them in the win64 folder of CE's bin folder replacing the old dbghelp and see if that works better

**Comment by avboy1337** [comment]
> delete the pdb
> if it doesn't crash then anymore find the dbghelp and imghelp dll's used by your compiler and put them in the win64 folder of CE's bin folder replacing the old dbghelp and see if that works better
> 
> Edit:
> It also doesn't crash on my system. Does your CE have all the files? Including the win64 folder? Is CE running in a path with full ascii characters? (In case it can't find the win64 folder and opt for the one in c:\windows, which WILL crash)
> 
> open Cheat Engine with Cheat Engine, an go to memoryview->view->memoryregions
> In there look up the address of dbghelp.dll and check in the last column that it's using CE's dbghelp dll

thanks for your help and i am going to have a try and make a reply as quick as possible.
