### ISSUE TITLE
Cheat engine problems

### ISSUE THREAD

**Issue by maracita** [cheat-engine/cheat-engine#1731]
I had been using Cheat engine on my Dell PC a couple years when it stopped opening. I have tried downloading it over and over and it is blocked.  I have disabled Firewalls and just completed a tutorial which instructed me to go into Regedit to allow the app.  I need an easily understood repair.  Thank you!

**Comment by cheat-engine** [comment]
search for "Reputation based protection" in windows and turn that off

**Comment by maracita** [comment]
I  still get message it was blocked because it could harm my computer.  I don't understand why I could run it before.

**Comment by cheat-engine** [comment]
Try restarting windows after turning it off. Windows sometimes doesn't let go once it has blocked something.

**Comment by maracita** [comment]
I restarted twice and received a message it was blocked by a "controlled folder".  I disabled that and was able to open the download. Thank you!
