### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Messi2020202** [cheat-engine/cheat-engine#1736]
I cannot open the cheat engine it says ''Windows cannot open this specified device, path or file. You may not have the appropriate permissions to access the item'' .  

<html><body><div class="main-title" id="messageTitle" style="color: rgb(255, 255, 255); direction: ltr; font-family: &amp;quot;Segoe UI light&amp;quot;; font-size: 28px; font-style: normal; font-variant: normal; font-weight: bold; letter-spacing: normal; margin-bottom: 20px; margin-left: 0px; margin-right: 0px; margin-top: 0px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px;">Windows protected your PC</div><span style="display: inline !important; float: none; background-color: rgb(0, 90, 158); color: rgb(255, 255, 255); direction: ltr; font-family: &quot;Segoe UI light&quot;; font-size: 16px; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; overflow-wrap: break-word; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px;">
      </span><div class="main-desc" id="messageBody" style="color: rgb(255, 255, 255); direction: ltr; font-family: &amp;quot;Segoe UI light&amp;quot;; font-size: 15px; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 0px; margin-left: 2px; margin-right: 0px; margin-top: 0px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px;">Microsoft Defender SmartScreen prevented an unrecognised app from starting. Running this app might put your PC at risk.</div><span style="display: inline !important; float: none; background-color: rgb(0, 90, 158); color: rgb(255, 255, 255); direction: ltr; font-family: &quot;Segoe UI light&quot;; font-size: 16px; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; overflow-wrap: break-word; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px;">
      </span><div id="moreBtnContainer" style="color: rgb(255, 255, 255); direction: ltr; font-family: &amp;quot;Segoe UI light&amp;quot;; font-size: 16px; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px;">
        
      </div><span style="display: inline !important; float: none; background-color: rgb(0, 90, 158); color: rgb(255, 255, 255); direction: ltr; font-family: &quot;Segoe UI light&quot;; font-size: 16px; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; overflow-wrap: break-word; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px;">
      </span><div id="moreInfoContainer" style="color: rgb(255, 255, 255); direction: ltr; font-family: &amp;quot;Segoe UI light&amp;quot;; font-size: 15px; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-top: 10px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; width: 75%; word-spacing: 0px;">
        

Application: | CheatEngine72 (3).exe
-- | --
Publisher: | EngineGame

</div></body></html>

**Comment by avboy1337** [comment]
personally speaking may be use win server is more ok 
01-server wont reboot repeatedly night
02-less rubish software 
and maybe server 2022 is my favourate ,then thoughly remove windefender to have the good journey of ce7.3

**Comment by TelosTheWanderer** [comment]
If you're under 14, ignore this, you won't have the mental capacity to understand.
1. Disable Defender. Defender marks any and all injectors as malware, and has automatic flags set up for CE. Add a whitelist yourself, or just disable it. Tons of guides online about this.
2. If that doesn't work, find out which folder CE is installed in. Relatively simple, usually C:\Program Files (x86)\CheatEngine or C:\Program Files\CheatEngine depending on which build you're using.
3. Take ownership of the folder. There are tons of guides on how to do this as well.
