### ISSUE TITLE
I can't compile Cheat Engine

### ISSUE THREAD

**Issue by ngudulalose** [cheat-engine/cheat-engine#1748]
[My Lazarus version](https://prnt.sc/1ott7i6)
When I compile first three modes, I got this Error:
`frmAAEditPrefsUnit.pas(50,16) Error: Identifier not found "TSynEditorOptions"`

**Comment by 9cg** [comment]
Install Lazarus 32-bit instead. Use cross-x86_64-win64 addon if you want to compile as 64-bit.

**Comment by ngudulalose** [comment]
> Install Lazarus 32-bit instead. Use cross-x86_64-win64 addon if you want to compile as 64-bit.

thank you! work perfectly

**Comment by scottmeup** [comment]
I get the same error compiling with Lazarus 32-bit or Lazarus 64-bit under Windows 11

`frmAAEditPrefsUnit.pas(50,16) Error: Identifier not found "TSynEditorOptions"`

**Comment by notcooler** [comment]
I did install the correct versions but still get the same error!

**Comment by fade2gray** [comment]
@notcooler Did you follow the basic build instructions? https://github.com/cheat-engine/cheat-engine#basic-build-instructions

**Comment by lyf-is-coding** [comment]
> I did install the correct versions but still get the same error!
Download the source code then open the readme.md file
The lazarus version you need to install is mentioned in the readme.md file
