### ISSUE TITLE
Cheat engine not working with cryptotab

### ISSUE THREAD

**Issue by musmanchaudhary** [cheat-engine/cheat-engine#1749]
I attach cheat engine with cryptotab browser it s work only one mint and then stop working

**Comment by TelosTheWanderer** [comment]
Not an issue. You're complaining about modifying a value that gets fetched from an external server. You can't just "generate bitcoin" like that, you have to actually mine it.

God, now I understand why Dark puts pupware in the .org installer.

**Comment by TelosTheWanderer** [comment]
@cheat-engine you can close this one, it's just someone getting a reality check.

**Comment by MrNeedHelpHere** [comment]
Accounts have been engaged in illegal activities revert police reports filed
