### ISSUE TITLE
Dash Delimeter Hard to Read for FPU Registers

### ISSUE THREAD

**Issue by zcanann** [cheat-engine/cheat-engine#175]
Using a dash as a delimiter for the FPU register values makes it hard to read, as there are frequently negative values in the registers. Dashes and negative signs are easily confused.

![delimiter](https://cloud.githubusercontent.com/assets/5906208/25786961/b80a3eb4-3351-11e7-9b6b-1a6b48aeeba5.PNG)

**Comment by cheat-engine** [comment]
it's now underscores
