### ISSUE TITLE
I cannot download cheat engine from github.

### ISSUE THREAD

**Issue by Glxckz** [cheat-engine/cheat-engine#1759]
I cannot do it can someone explain how to download cheat engine from github?

**Comment by Symbai** [comment]
https://github.com/cheat-engine/cheat-engine/archive/refs/heads/master.zip

**Comment by Glxckz** [comment]
> https://github.com/cheat-engine/cheat-engine/archive/refs/heads/master.zip

Yes but where is the exe file of cheat engine located exactly.

**Comment by PointVoider** [comment]
this repo contains just the source code of cheat engine.
if you want the exe file, you have to build it yourself.

**Comment by Glxckz** [comment]
> this repo contains just the source code of cheat engine.
> if you want the exe file, you have to build it yourself.

How to build it?

**Comment by fade2gray** [comment]
@Glxckz Perhaps you would be more comfortable with this...

https://www.cheatengine.org/downloads.php

**Comment by Glxckz** [comment]
> @Glxckz Perhaps you would be more comfortable with this...
> 
> https://www.cheatengine.org/downloads.php

33 Detections on virus total..

**Comment by fade2gray** [comment]
@Glxckz  search for "how to compile cheat engine source".
