### ISSUE TITLE
Remove Crapware\PUP from Setup. Portable Release with No Extra Software.

### ISSUE THREAD

**Issue by ghost** [cheat-engine/cheat-engine#176]
Title.

**Comment by crisppY** [comment]
+1

**Comment by Symbai** [comment]
-1

Already exists (since years probably): http://cheatengine.org/downloads.php
But you may have to read one or two sentences to see the link.

**Comment by RaTcHeT302** [comment]
Don't blame the user, that link is way too easy to miss, you know that. 

This adware crap shouldn't have place in open source software such as this one. 
I would rather just pay for Cheat Engine directly.

**Comment by Symbai** [comment]
Dark Byte isn't begging for donations, doesn't have annoying popups, doesn't even have advertising on his site. You get a free outstanding piece of software history without doing anything for it. So if the one and only thing you blame him for is that he's covering his server costs by making money of his installer while providing a portable installer-free version on the same download page. then I wonder how you pay your own bills, with much much love only?

There are a couple of ways you can try to cover server costs and NONE of these ways are 100% satisfying. Paywalls, aggressive donation begging, advertising. He only asks user to read a few lines. Personally I see a problem with infected installers but I dont see a problem the way Dark Byte makes money comparing to what we get (amazing cheat tool for free) and dont get (paywalls, aggressive advertising).

However the reason he put the portable download not that obvious is that the more people download the installer, the easier he can pay his service and some coffee. But you don't really have to search for non installer, all you need is to read a few lines on the same page above the download button.
