### ISSUE TITLE
Location after building.

### ISSUE THREAD

**Issue by amogusman01** [cheat-engine/cheat-engine#1761]
I just finished building it, but I'm not sure where the .exe file is located at, the only one I found was "cheatengine-i386.exe" at Cheat Engine/bin, is it the correct one? If so, do I only need to run it and it will be fine?

**Comment by cheat-engine** [comment]
unless you want the 64 bit verdion, that is the correct one yes

**Comment by amogusman01** [comment]
Thanks.
