### ISSUE TITLE
[linux:ceserver] pointer scan causes memory leak

### ISSUE THREAD

**Issue by ivanstepanovftw** [cheat-engine/cheat-engine#177]
In windows CE keep results of pointer scan in disk (as value search), but CEServer keep results in memory, then write to disk and erase from memory.
Any help? Because I have HDD and when my computer reach full memory, it activates swap and i cant even try to switch to tty1. Sorry for bad skills in english...

**Comment by cheat-engine** [comment]
to ceserver a pointerscan is the same as a normal memory scan.
Are you running the cheat engine GUI inside wine by any chance ? Because that WILL eat up at least 6GB RAM or more depending on the game you've targeted.  (And that is not a memory leak, it actually uses that much by design)

**Comment by AshFTW** [comment]
Yes, in wine. So, where i need to launch cheat engine? Another PC?

**Comment by cheat-engine** [comment]
Just make sure your system has enough RAM
If your system doesn't have enough RAM, then let another system do the work yes.

**Comment by AshFTW** [comment]
Ok, thank you.
Will my system freeze with SSD, when RAM packed?
And second question: all process memory will be transmitted via LAN?

**Comment by cheat-engine** [comment]
Not freeze, but may become slow.
All process memory will be transmitted via LAN if you use ceserver yes.  
Or as I said alternatively,  you can make a pointermap/snapshot of the game, and transfer that to the other PC(the generating of the pointermap will eat your RAM though, but only temporarily) and then just do the scan there without having to worry about connection issues

**Comment by AshFTW** [comment]
Omg, why we just cant send command to ceserver to **find value**, then if done send results to Cheat Engine? Why Cheat Engine downloads a lot of information?

**Comment by cheat-engine** [comment]
ceserver is just an API wrapper in between linux and windows. I suggest you use a gigabit network connection or faster.
Or as I said, pointermaps
