### ISSUE TITLE
I can't compile Cheat Engine at all

### ISSUE THREAD

**Issue by ghost** [cheat-engine/cheat-engine#1771]
Whenever I try to compile Cheat Engine 7.3 the compilation fails and I see in the Messages window the following line:

newbutton.pas(88,25) Error: Identifier not found "clDark"

Whenever I try to compile Cheat Engine 7.2 the compilation fails and I see in the Messages window the following lines:

frmAAEditPrefsUnit.pas(50,16) Error: Identifier not found "TSynEditorOptions"
frmAAEditPrefsUnit.pas(50,33) Error: Error in type definition

Whenever I try to compile Cheat Engine 6.4 the compilation fails and I see in the Messages window a lot of warnings and three errors:

networkInterface.pas(1796,12) Error: identifier idents no member "Family"
networkInterface.pas(1797,12) Error: identifier idents no member "Port"
networkInterface.pas(1798,12) Error: identifier idents no member "Addr"

I did NOT modify the code! I just downloaded it from GitHub and extracted everything by using 7-Zip.

I downloaded and installed the latest version of Lazarus IDE and free pascal compiler.

I don't know why people think that this is alright to upload code that contains errors and warnings and thus it cannot be compiled at all?

Answer me this question!

**Comment by fireword** [comment]
lost resource in 2.2.0RC1-fpc-3.2.2-win64

**Comment by cheat-engine** [comment]
use an older lazarus , so not 2.2.0

**Comment by fireword** [comment]
where do u come from?

> > use win10-64bit platform, thanks
> 
> I am already using win10-64bit platform and the source code of all versions of Cheat Engine still don't compile with "lazarus-2.2.0RC1-fpc-3.2.2-win64"

**Comment by buruto** [comment]
> where do u come from?
> 
> > > use win10-64bit platform, thanks
> > 
> > 
> > I am already using win10-64bit platform and the source code of all versions of Cheat Engine still don't compile with "lazarus-2.2.0RC1-fpc-3.2.2-win64"

I live in Israel.

**Comment by lotsahelp** [comment]
I see this comment about the 2.2.0 RC.  https://forum.lazarus.freepascal.org/index.php?topic=57051.0

**Comment by Theo1996** [comment]
I am adding this for other people who have issues building. The build instructions are ,I think, incorrect.
Build instructions. That actually worked. Laz 2.2.2 and the latest 3.0rc does not work.For 32-bit builds add an install of the respective version cross i836
-LAZARUS 2.2.0 and fpc 3.2.2 for 7.5 AND "virtuatreeview "package fron the net! "laz.virtualtreeview" is already installed but is a completely diffferent package!It has laz. in front!
-LAZARUS 2.0.10 and fpc3.2.0 for 7.3 and 7.4
