### ISSUE TITLE
Memory region bug in mac version

### ISSUE THREAD

**Issue by push0ebp** [cheat-engine/cheat-engine#178]
[http://imgur.com/a/6rllZ](http://imgur.com/a/6rllZ)

all memory regions are No Access. is it OK? 
when I would scan TEXT section. but scanning was not working because of this problem.

**Comment by cheat-engine** [comment]
the important field that CE uses is the Protect field, not the allocation protect field (it's just there for fun on windows to see how it has changed, but the important one is the current protection)
the TEXT section is most likely copy-on-write, so if you scan for that, tick check the copy-on-write checkbox (or at least make it gray)
