### ISSUE TITLE
I can't compile the Cheat Engine'S TUTORIALS at all

### ISSUE THREAD

**Issue by buruto** [cheat-engine/cheat-engine#1781]
Whenever I try to compile the Cheat Engine'S TUTORIALS the compilation fails and then I see the following error in the messages window:

Compile package LCLBase 2.0.12: Exit code 1, Errors: 1

lazfreetypeintfdrawer.pas(10,3) Fatal: Cannot find EasyLazFreeType used by LazFreeTypeIntfDrawer. Check if package LazUtils creates EasyLazFreeType.ppu, check nothing deletes this file and check that no two packages have access to the unit source..

The compilation stops on line number 10 that is:

`Classes, SysUtils, FPimage,`
`// LazUtils`
`EasyLazFreeType,`
`// LCL`
`GraphType, Graphics, IntfGraphics`

I am using the same Lazarus IDE and free pascal compiler that I used to successfully compile the Cheat Engine itself but the Lazarus IDE and free pascal compiler that do compile the Cheat Engine itself don't compile it's tutorials at all!

Do I need an older version of Lazarus IDE and free pascal compiler to successfully compile all the tutorials of Cheat Engine?

If yes then which version exactly?

If no then tell me what I am doing wrong?

Am I missing something?

Do I need to download and install something to make it working?

**Comment by fade2gray** [comment]
This is my first ever attempt to compile CE.

https://youtu.be/gzy1DZEgFZw

**Comment by buruto** [comment]
> This is my first ever attempt to compile CE.
> 
> https://youtu.be/gzy1DZEgFZw

I have successfully compiled Cheat Engine

BUT I am NOT talking about Cheat Engine, but about the TUTORIALS of Cheat Engine.

This is working for me to double click cheatengine.lpi and then build it, BUT when I go into the "Tutorial" folder, double click "tutorial.lpi" and then build it then the build fails with the errors mentioned above.

**Comment by fade2gray** [comment]
@buruto 

...but did you actually compile the tutorials, it's a completely separate procedure - watch the video.

**Comment by buruto** [comment]
> @buruto
> 
> ...but did you actually compile the tutorials, it's a completely separate procedure - watch the video to the end (or at least watch it from 5:25).

The simplest answer and easiest solution is to uninstall the current Lazarus IDE and free pascal compiler and then download and install the following:

lazarus-2.0.10-fpc-3.2.0-cross-x86_64-win64-win32.exe
lazarus-2.0.10-fpc-3.2.0-win32.exe

And then this is possible to open and build both "cheatengine.lpi" and "tutorial.lpi"
