### ISSUE TITLE
Lua Impossible errors

### ISSUE THREAD

**Issue by atul1503** [cheat-engine/cheat-engine#1784]
Sometimes,while  running an edited lua code,unexpected error occurs,which should not occur according to the standard rules of lua.However,these errors are resolved if I write the same code in a new file or from scratch.
for eg for the follwing code:
a=5
function add()
 print(a)
end

If add() function is called ,lua throws the error "attempt to access nil value 'a' ",while outside the function a=5.Scope rules of lua allows the use of global variables inside a function with their global values.However,if I write the same code in a new file or anywhere else it works.

**Comment by cheat-engine** [comment]
Are you sure there isn't another script that sometimes sets a to nil ?

**Comment by atul1503** [comment]
No script at all other than that.I even tried to close cheat engine several times and cleared all the temp files.

**Comment by cheat-engine** [comment]
Editing a table entry with a lua block always executes the code inside the lua block

use `if syntaxcheck then return end` at the start to prevent this
