### ISSUE TITLE
How to disable the very annoying dark mode of Cheat Engine 7.3?

### ISSUE THREAD

**Issue by buruto** [cheat-engine/cheat-engine#1785]
I hate very much the very annoying dark mode of Cheat Engine 7.3.

It is enabled by default and I don't know how to disable it.

While the dark mode is enabled I can't see what I am doing because both the fore and back colors are black!

**Comment by cheat-engine** [comment]
I think you have a custom font set with the fontcolor to black.
You can run the reset settings program that comes with CE to reset all settings if you can't see anything, else you can go to settings and change/disable it there.  There's also an option to disable dark mode

**Comment by buruto** [comment]
> I think you have a custom font set with the fontcolor to black.
> You can run the reset settings program that comes with CE to reset all settings if you can't see anything, else you can go to settings and change/disable it there. There's also an option to disable dark mode

And where exactly is the option to disable dark mode?

**Comment by cheat-engine** [comment]
settings->general settings

disable dark mode support.  It's under the lua script groupbox

**Comment by buruto** [comment]
> settings->general settings
> 
> disable dark mode support. It's under the lua script groupbox

I found it! Thank you! Now I can finally see what I am doing!
