### ISSUE TITLE
There are VERY SERIOUS color problems with Cheat Engine

### ISSUE THREAD

**Issue by buruto** [cheat-engine/cheat-engine#1790]
It seems that there are VERY SERIOUS color problems with Cheat Engine BOTH IN and WITHOUT dark mode.
IN dark mode BOTH FORE and BACK colors are black and WITHOUT dark mode BOTH FORE and BACK colors are white.
The problem with white fore and back colors ALSO happen in version 7.2 TOO!

The texts, paragraphs, sentences, words and letters are invisible and are VERY HARD to read and this is making the application VERY HARD to use!

Why this is happening at all!?

I was using Cheat Engine many years ago and I don't remember that I had these color problems in the past at all!

So what is causing these color problems at all!?

Please help me!

I am begging you!

**Comment by cheat-engine** [comment]
run the reset settings program that comes with CE

**Comment by buruto** [comment]
> run the reset settings program that comes with CE

Thank you very much! This fixed the light mode of cheat engine, but unfortunately this action did NOT fix the dark mode of cheat engine.

In dark mode both fore and back colors are still black!
