### ISSUE TITLE
kernel vqe memory 

### ISSUE THREAD

**Issue by qwer0123456** [cheat-engine/cheat-engine#1807]
[file.zip](https://github.com/cheat-engine/cheat-engine/files/7135925/file.zip)

This happens in certain programs
Enable Kernel VQE in Cheat Engine(7.2~7.3)
Search the array below without ever opening the memory viewer no results found
8B ?? ?? 3B ?? 89 ?? ?? 89 ?? ?? 89 ?? ?? 89 ?? ??
disable kernel vqe writable execute copyonwrite full check result found
Happens on all Windows operating systems
If you read the 007AE0BE page in advance with the memory viewer, the VQE search results
Overvalues are displayed Search values are not displayed before reading in RPM

<img width="604" alt="wcx" src="https://user-images.githubusercontent.com/80979849/132684067-2c729e99-feda-47de-979e-0f27beb591ec.png">

401000 page attribute is weird with WCX if you look at it as a process hacker

Memory scans are ignoring 401000 page

**Comment by cheat-engine** [comment]
VQE only find accessed memory (present)  if something isn't actually loaded in RAM, VQE won't find it.
Normally this is no issue, as you're interested in memory accessed by code, but yeah can be an issue.  
There's nothing that can be done about that

**Comment by qwer0123456** [comment]
If there is no problem, why is this program protect?
If you read 401000~800000 once in RPM, VQE search is done after that.
However, if the memory is not read , the search is not result address
Is it section remapping?

**Comment by cheat-engine** [comment]
It's how windows(and most operating systems) work. If some memory of a process is never or only rarely used it's not loaded in RAM.  Only when it is accessed (read, write or execute) windows will load it into RAM

**Comment by qwer0123456** [comment]
Even if the process is accessed and running normally, it cannot be searched.
Like a video, you have to turn off the VQE function and check CopyOnWrite to find it
https://streamable.com/t9mtaa
