### ISSUE TITLE
Changing scan tab display type only applies to "Value" column

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#1812]
But not previous and first:
4 bytes:
![image](https://user-images.githubusercontent.com/14368203/132947443-78675909-4abb-4248-a0c6-b64d3fd42daf.png)
float:
![image](https://user-images.githubusercontent.com/14368203/132947450-f77f7ea6-bfa1-4353-bdf6-b8b5868fa6e2.png)

**Comment by cheat-engine** [comment]
should work now
