### ISSUE TITLE
Light mode - Selected process text color should be inverted

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#1813]
Since 7.3 the text of the selected process/window is hard to read because it stays black and the selection color is dark blue. Text color should be inverted (white). Please note that in the screenshot below its easier to read because the image is enlarged and I didn't wanted to upload a 4k desktop screenshot.
![image](https://user-images.githubusercontent.com/14368203/132951763-3745c996-acef-46ff-96da-446314fbcf1b.png)
FYI: Everywhere else the text is properly inverted when selected, for example in cheat table:
![image](https://user-images.githubusercontent.com/14368203/132951722-25ccea7f-2db8-4909-9168-e363983d3cc8.png)

**Comment by cheat-engine** [comment]
should be fixed now
