### ISSUE TITLE
[Building] Build mode Release 64-Bit fails with clDark

### ISSUE THREAD

**Issue by vbion** [cheat-engine/cheat-engine#1818]
I downloaded 64-bit lazarus with the [link](https://sourceforge.net/projects/lazarus/files/Lazarus%20Windows%2064%20bits/Lazarus%202.0.10/) specified in the Readme file.  
I have not installed the 32-bit addon.

The `Project->Build` command of Release 64-Bit fails with the following message:
```
Compile Project, Mode: Release 64-Bit, Target: bin\cheatengine-x86_64.exe: Exit code 1, Errors: 1
newbutton.pas(88,28) Error: Identifier not found "clDark"
```
I have found one [mention](https://webcache.googleusercontent.com/search?q=cache:9tWw_VrtJQsJ:https://www.cheatengine.org/forum/viewtopic.php%3Fp%3D5773268%26sid%3D89dfa595caf1d18e7bbb1c9f378a4ffb) of this error.

Source version: Cheat Engine 7.3 Release,
Processor: Ryzen 5 3600,
OS Name: Windows 11 Pro,
OS Version: 10.0.22000 N/A Build 22000.

**Comment by cheat-engine** [comment]
Your lazarus/fpc version might be too new.  CE uses FPC 3.2.0 Lazarus 2.0.6

**Comment by vbion** [comment]
Ok, I'll test it on with the specs you provided and will get back to you.

**Comment by vbion** [comment]
You were correct.
The closest combination that Sourceforge had was FPC 3.2.0 Lazarus 2.0.10.
I installed the x64 version without the x32 addon.
The project successfully compiled for the target Release x64.

**Comment by fade2gray** [comment]
@cheat-engine 

> CE uses FPC 3.2.0 Lazarus 2.0.6

... but the Build Instructions in the README provide links to Lazarus 2.0.10 ???
![BuildInstructions](https://user-images.githubusercontent.com/1332009/136655276-b25f8c71-afd6-4d99-aa1d-9c08017b3b15.PNG)

**Comment by Theo1996** [comment]
I am adding this for other people who have issues building. The build instructions are ,I think, incorrect.
Build instructions. That actually worked. Laz 2.2.2 and the latest 3.0rc does not work.For 32-bit builds add an install of the respective version cross i836
-LAZARUS 2.2.0 and fpc 3.2.2 for 7.5 AND "virtuatreeview "package fron the net! "laz.virtualtreeview" is already installed but is a completely diffferent package!It has laz. in front!
-LAZARUS 2.0.10 and fpc3.2.0 for 7.3 and 7.4
