### ISSUE TITLE
.cesig create?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#182]
cheat engine get folder cansign.txt create

cheat table  Save CT -> .cesig open -> fail

How do I generate a cesig file?

unimplemented?

**Comment by cheat-engine** [comment]
Signatures are pieces of text or an image (or both) at the bottom of your cheat table, showing the table hasn't been tempered with.
Only advantage you get with this is that by default (can be changed by the user), CE will run the lua script in the lua section of a table without asking.

Only I can generate signatures, but not sure yet on how it will be implemented. Only people I trust, everyone that asks and can verify where they live, sell? No idea yet

**Comment by kitty8904** [comment]
I thought I created an encrypted CT file and it was the password verification lock design when I loaded it.

Is it a system that detects corruption of CT files?

Is the shared encryption file of the signature only generated as the original(release6.7) cheat engine?

**Comment by Symbai** [comment]
> it will be only partially safe to share with friends

Or customers... seeing how many people sell CE tables at FR already, this would be the next step. Hopefully this never comes. If you want to share with friends only, only give them your files. If they leak them, then they aren't your friends. But obviously non-friends (customers) may share much more easiler.

**Comment by kitty8904** [comment]
Illegal file collection of security programs is more problematic

security program may collect CT files etc

The security program allows you to search and steal files without permission, with high privileges

If you are programming as you say, it does not matter how you share with your friends.

The important thing is to prevent the illegal transfer of files(Data Protect)

Thank you

**Comment by Symbai** [comment]
Firewall + password protected ZIP/RAR or encrypt the file yourself. Common, like there aren't thosuand of possible solution to YOUR specific case already... but anyway, its Dark Byte's decision at all.

**Comment by kitty8904** [comment]
I solved the problem

true crypt & window bitlocker encrypt & Comodo

Even if you use a firewall, the file is leaked without your knowledge when the security program is allowed to access it.

I asked because I do not want illegal file acquisition of the security program
