### ISSUE TITLE
How to build lua module for ce 73 (problem in 64bit) ?

### ISSUE THREAD

**Issue by wolfoops** [cheat-engine/cheat-engine#1827]
Hi,
I'm trying to build https://github.com/sqmedeiros/lpeglabel for ce.
The tools using is ms build tool, with native 64/32bit command prompt from vs2017.
The commands (inside lpeglabel directory) I use are as follow:
1. cl /MT /O2 /c /I<ce repo's \lua53\lua53\src as header include>  /D < define symbol etc> *.c
2. link /DLL /def:lpl.def /OUT:lpeglabel.dll *.obj <lua.lib>
where lpl.def is to define export of lpeglabel.dll, content as following 3 lines:

LIBRARY lpeglabel
EXPORTS
  luaopen_lpeglabel

I change the <...> according to different targets etc.

I've tried to build for ce 73 32bit, a zerobrane editor's 32bit lua53.dll, a 64 bit lua 5.3.4 dll downloaded from  https://joedf.ahkscript.org/LuaBuilds/ .
They all success to build and loaded and return a table when required. 

So the following ce 73 64bit problem should not caused by trivial mistake like misunderstanding of 32/64 bit or package path etc.

The above success cases use no /D<define symbol> , and <lua.lib> is produce from gendef and dlltool.

In following trials of building ce73 64 bit, if success build, then the following error message show when require inside ce 73 64bit lua:
error loading module 'lpeglabel' from file 'D:\00EXE\CE73\clibs64\lpeglabel.dll':
	The specified procedure could not be found.
Note that the require located the lpeglabel.dll, but seems problem found some 'procedure' in the dll.

failed case 1: <lua.lib> use ce73 installed dir's  \plugins\lua53-64.lib (50k size),
  -> unresolved external symbol for lua_* and luaL_* symbol

failed case 2: <lua.lib> use ce repo's \lua_extra\lua53-64.lib (29k size),
  -> build success, but problem on require.

failed case 3: <lua.lib> use gendef and dlltool of lua53-64.dll, (there is 3 mangled symbols)
  -> unresolved external symbol ( stop at one of the 3 mangled symbols )

failed case 4: <lua.lib> use gendef and dlltool of lua53-64.dll, (alias the mangled symbols)
  -> build success, but problem on require.

The 3 mangled symbols, with alias:
luaL_buffinit=?luaL_buffinit@@YAXPEAUlua_State@@PEAUluaL_Buffer@@@Z
luaL_openlib=?luaL_openlib@@YAXPEAUlua_State@@PEBDPEBUluaL_Reg@@H@Z
luaL_pushmodule=?luaL_pushmodule@@YAXPEAUlua_State@@PEBDH@Z

Then I don't know if there are other option I can try.

I'm appreciate for a guide line or example to build ce 64bit lua module.

Thank you~

**Comment by cheat-engine** [comment]
try building lua53-64 yourself and use the lib you get from that

or instead of static linking use dybamic linking using getprocaddress for what you need

**Comment by wolfoops** [comment]
> try building lua53-64 yourself and use the lib you get from that
build  the *.lib or *.dll, and with whole lua source (not just header file)?

I've tried build *.lib base on respective *.dll using gendef and dlltool as motioned above,
build like this with CE 32bit, non CE 32bit, non CE 64bit are success, but not work for CE 64bit.

> 
> or instead of static linking use dynamic linking using getprocaddress for what you need
> 

I want to make lua module (eg lpeglabel.dll ) so that user (not just me) can use it in normal lua usage (ie. use require, not package.loadlib or ce's special loading method, eg. injectDLL )

> and yoi'ee building using c? so not cpp

The lpeglabel src are all *.c files.
The command is adapted from 64.bat in CE repo's lua53/lua53.src .
And it does success make CE 32 bit and work with lua require.

Thank you.

**Comment by wolfoops** [comment]
Hi,

I think I solve the problem in building lua module lpeglabel for 64bit CE 73.

I search the lpeglabel sources files for the 3 mangled function, there is only 2 place using the *_buffinit function.
I manually replaced the function call with the actual code body from definition of *buffinit which is located at lauxlib.c .
Then *.dll can be built with unmodified lua53-64.def (make from gendef.exe and dlltool ) and properly loaded in CE 73 64bit's with lua require call.

There may be a better way to do so, eg. modify the the lauxlib,h, but I'm rust in this c thing.

That's it.

Thank you~
