### ISSUE TITLE
Dump a mono assembly from dissect view

### ISSUE THREAD

**Issue by Xiloe** [cheat-engine/cheat-engine#1828]
Hi, I would like to dump a mono assembly from the Mono Dissect view. However I do not know how to do that.
I already looked at #337 but I don't know where to find the PE headers to get the size.

That is what I got right now
![image](https://user-images.githubusercontent.com/51050533/133927601-5b1fae30-cd41-4dc9-b226-ccf59e1c7ad4.png)

**Comment by Xiloe** [comment]
Made an assembly dumper with mono_lib.

**Comment by joshfreitas1984** [comment]
@Xiloe did you put your assembly dumper anywhere mate?
