### ISSUE TITLE
Branch tracing on AMD - Ultimap2

### ISSUE THREAD

**Issue by Mi4uric3** [cheat-engine/cheat-engine#1834]
Dark Byte stated the following [here](https://www.cheatengine.org/forum/viewtopic.php?p=5753387#5753387):

> AMD does not contain the "Branch Trace Store" feature used in Ultimap and also not the "Intel process trace" feature used by ultimap2 so right now it's not possible

I found [this](https://www.syssec.ruhr-uni-bochum.de/media/emma/veroeffentlichungen/2012/12/04/TR-HGI-2012-001.pdf) paper from 2012 by Ralf Hund, Carsten Willems, Dennis Felsch, Andreas Fobian & Thorsten Holz, about branch tracing on AMD systems:

Chapter `4.3 Branch Tracing on AMD` mentions the following (probably reverse engineered):

```
MSRs:
- AMD_MSR_BT_BASE (0xC0011007)
- AMD_MSR_BT_PTR (0xC0011008)
- AMD_MSR_BT_LIMIT (0xC0011009)
- AMD_MSR_BT_CONTROL (0xC0011010) - magic value 0x20230340

The format of each BTM differs from the records created on an Intel system. Each message
consists of 96 bits, which contain a 64 bit address value, a 16 bit segment selector, and additional
16 reserved bits.
```

I have no experience in Windows kernel driver development, but in the last years AMD caught up on the market share - I bought a fairly recent AMD CPU. I could test the feature, if Cheat Engine were to implement it, and I think a lot of other CE users would appreciate it as well.

**Comment by cheat-engine** [comment]
If there was more documentation about it perhaps.  Also, from what i gathered AMD removed this feature from their cpu's in 2016

**Comment by Mi4uric3** [comment]
Damn it AMD! Thanks for the reply!
