### ISSUE TITLE
too many scan tabs break form layout

### ISSUE THREAD

**Issue by wolfoops** [cheat-engine/cheat-engine#1835]
Once there is too many scan tabs (8+ in pic) the main form layout is broken even extra scan tabs is removed
![ce_toomanyscantab](https://user-images.githubusercontent.com/22504217/134692080-e0f648b1-630b-483e-89bd-022d9ee18e07.jpg)
.

**Comment by cheat-engine** [comment]
is there anything else you do to cause this ?

**Comment by wolfoops** [comment]
oops, 
I've modified the miAddTab.OnClick function, something like
miAddTab.OnClick = function(...)
 <  spawn a timer to do stuff >
  return <original onClick function>(...)
end
So, it is not a CE problem.
Sorry, I'm closing it.
