### ISSUE TITLE
Update timer Error

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#1839]
<img width="456" alt="thread" src="https://user-images.githubusercontent.com/18622105/134863154-3c81a552-3ad3-4e34-87c0-bffe9bc102ca.png">

<img width="226" alt="thread2" src="https://user-images.githubusercontent.com/18622105/134863774-717d036b-5adb-4a99-9587-384635a6f327.png">

use thread for freeze check

update timer error message

UpdateTimer Error:TTreeNodes; GetnodeFormindex: Consistency Error - Count too Big Error

I don't know when the exact error occurs.

Sometimes an updatetimer error message is printed and an error

maybe thread for free? ir interval time fast?

**Comment by Rixef** [comment]
Wow this error seems very undocumented lol; google search for "cheat engine count too big error" yielded one result which was this one from 2 years ago and no one's got anything on it? Did you ever figure out what causes this error, kitty?

I'm encountering this issue with CE 7.3 beta 2, compiled my own build but the only thing I changed was I made my own dark mode version of CE.

Well I know this much at least; using a lua script with a timer in it seems to be the issue at first speculation and that lines up with the "UpdateTimer Error" obvious enough, but _**why**_ does it happen?
