### ISSUE TITLE
disassembler exception

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#1848]
After opening a second memory browser and closed it I got spammed by disassembler exception error message boxes. It was telling me to open another instance of CE and visit the address and report the bytes. I did that I wasn't sure if it meant the game I was debugging or CE instance. On CE this address pointed to unallocated memory. On game instance (64bit) the bytes were:

`55 48 8B EC 56 57 41 55 41 56 41 57 48 83 EC 18 48 8B F1 F3 0F 11 4D C8 4C 8B 76 10 4D 8B EE 4D 85 F6 74 1B`

**Comment by cheat-engine** [comment]
At any point did you open a secondary memory view window, and then close it?  If so, that issue is fixed now
