### ISSUE TITLE
Should all lpi files be compiled?

### ISSUE THREAD

**Issue by fade2gray** [cheat-engine/cheat-engine#1851]
Until now, I had only been compiling `cheatengine.lpi`, `tutorial.lpi` (CE basic tutorial) and `project1.lpi` (CE mini games tutorial), but on my first few attempts to hack a commercial game I got frustrated with the game crashing when trying to find what writes/accesses a particular address.

I since discovered the need to compile `vehdebug.lpi` and `speedhack.lpi`, but there are a shed load of other lpi files - should I compile them all, or only as an when I might discover the need for them?

```
\Cheat Engine\allochook\allochook.lpi
\Cheat Engine\cecore.lpi
\Cheat Engine\ceregreset\ceregreset.lpi
\Cheat Engine\cheatengine.lpi
\Cheat Engine\launcher\cheatengine.lpi
\Cheat Engine\plugin\DebugEventLog\src\DebugEventLog.lpi
\Cheat Engine\debuggertest\debuggertest.lpi
\Cheat Engine\plugin\example\exampleplugin.lpi
\Cheat Engine\plugin\forcedinjection\forcedinjection.lpi
\Cheat Engine\dbk32\Kernelmodule unloader\Kernelmoduleunloader.lpi
\Cheat Engine\luaclient\luaclient.lpi
\Cheat Engine\luaclient\testapp\luaclienttest.lpi
\Cheat Engine\Tutorial\graphical\project1.lpi
\Cheat Engine\speedhack\speedhack.lpi
\Cheat Engine\speedhack\speedhacktest\speedhacktest.lpi
\Cheat Engine\sfx\level2\standalonephase2.lpi
\Cheat Engine\Tutorial\tutorial.lpi
\Cheat Engine\VEHDebug\vehdebug.lpi
\Cheat Engine\windowsrepair\windowsrepair.lpi
\Cheat Engine\winhook\winhook.lpi
\Cheat Engine\xmplayer\xmplayer.lpi
```

**Comment by cheat-engine** [comment]
mainly just the ones you intend to use
cecore: if you plan on bulding a jni version for android
ceregreset: to reset your ce config
launcher/cheatengine.lpi: to pick for you which .exe to launch
\plugin:  just example plugins
Kernelmoduleunloader.lpi: To unload the driver
**luaclient.lpi**:  You'll need this for {$luacode} blocks
luaclienttest.lpi: Just a small test project
Tutorial\graphical\project1.lpi: If you feel like having the graphical tutorial
speedhack.lpi: If you wish to use the speedhack functionality
standalonephase2.lpi: If you wish to create standalone trainers. and/or want to trigger anti viruses
tutorial.lpi: tutorial.  Build it if you think you'll need it.  Good app to test stuff on
**vehdebug.lpi**: VEH debug.  You'll need this if you with to use the veh debugger
windowsrepair.lpi: Only needed if there's a registry setting that blocks CE from executing
winhook.lpi : Only needed if you wish to intercept windows messages in the target process
xmplayer.lpi: Needed if you wish to play xm files

**Comment by fade2gray** [comment]
Thanks for the heads-up.
