### ISSUE TITLE
about 64 bit jmup

### ISSUE THREAD

**Issue by ragnaroks** [cheat-engine/cheat-engine#1859]
> this is a suggestion not a bug report.

i saw this [post](https://www.patreon.com/posts/cheat-engine-7-3-57174240) just now,maybe use `jmp newmem 32` and `jmp newmem 64` like `nop 3` to decide 32 bit jump or 64 bit jump?

there are both `jmp newmem` now,it's confusing when make AAScript,do not know how much bytes-length to override.

i usually use `alloc(symbol,256,$process)` to make sure that can use 32 bit jump to override 5 bytes for now.

**Comment by cheat-engine** [comment]
jmp far newmem will generate a 14 byte jump every time.

**Comment by ragnaroks** [comment]
clear answer
