### ISSUE TITLE
it is malware to my pc

### ISSUE THREAD

**Issue by mrman690** [cheat-engine/cheat-engine#1861]

**Comment by Qboi123** [comment]
https://www.virustotal.com/gui/file/9b8480581ffd010c93c4504d0bb5dcd8c2eba5c57812e399da8c6c58024a4903

**Comment by Qboi123** [comment]
I tried it, it is bundleware in the installer.

**Comment by Qboi123** [comment]
And I got McAfee Web Advisor bundled with it. I did press decline.

**Comment by lKobi** [comment]
Cheat Engine does include Adware, the only way around it is to recompile it yourself, the developer even removed the portable version on purpose.
