### ISSUE TITLE
Can't open Cheat Engine 7.3

### ISSUE THREAD

**Issue by Yinboy1** [cheat-engine/cheat-engine#1862]
I can't open because computer have not permission to save chaet engine 7.3 file,must contact system administrator to open.I am a Hong Kong people can youput cheat engine add some Chinese language?

**Comment by Y-A-K-E** [comment]
CE7.3  必须要管理员权限才能运行.
CE7.3 有内置的简体中文以及繁体中文,设置中自己选择.

**Comment by Y-A-K-E** [comment]
补充下,可能在线安装的版本没有繁体中文.
需要自己去官方网站下,在了丢languages文件夹即可.
