### ISSUE TITLE
How to use Ultimap in a virtual machine？

### ISSUE THREAD

**Issue by DarkAsm** [cheat-engine/cheat-engine#1870]
How to use Ultimap in a virtual machine, because he keeps crashing in the physical machine？
![image](https://user-images.githubusercontent.com/62586194/137111335-5496e9b7-aeb4-407e-86ab-c6211afdf917.png)
I've tried both win7 and win10, but I still can't capture anything in the virtual machine.

**Comment by DarkAsm** [comment]
@cheat-engine  Can Ultimap run in a virtual machine?

**Comment by cheat-engine** [comment]
It depends on if the virtual machine implements branch trace store.  It's likely it doesn't though

**Comment by avboy1337** [comment]
貌似自己编译，也许有点用，不会崩溃

**Comment by DarkAsm** [comment]
> It depends on if the virtual machine implements branch trace store. It's likely it doesn't though
I got it, thanks

**Comment by DarkAsm** [comment]
> 貌似自己编译，也许有点用，不会崩溃

也许是你的机器或者系统比较适合DBVM，DBVM还是不太稳定，物理机有很大机率蓝屏或者会变得很卡。
