### ISSUE TITLE
Error (Failure enabling speedhack. DLL injecting failed):dllinjectfailed: Failed injecting the DLL Force load module failed:Unable to open file.

### ISSUE THREAD

**Issue by james25567449** [cheat-engine/cheat-engine#1885]
Please help.I can't fix this problem , what should I do?

![Enable_speedhack_problem](https://user-images.githubusercontent.com/85815850/139066080-e04a96c1-8180-4c3d-b198-f60ca84fd933.png)

**Comment by cheat-engine** [comment]
speedhack.lpr , and compile it to 32 bit

**Comment by james25567449** [comment]
What should I do.Compile speedhack.lpr got error
![image](https://user-images.githubusercontent.com/85815850/139486476-37de7d14-1d9e-4371-8311-a3de7053260e.png)
