### ISSUE TITLE
i can't open the cheat engine 7.3, it looks like the pc thinks it is a virus, how do i open it without windows don't show this message instead of the app?

### ISSUE THREAD

**Issue by LighteryBR** [cheat-engine/cheat-engine#1886]
![image](https://user-images.githubusercontent.com/93291257/139149521-6991e624-0b71-47f9-9af3-5804e56b3a4b.png)
i can't open the cheat engine, i open the game and this message instead of the application thinking it's an virus, how do i fix this?
(it's an brazillian language pc, so i couldn't show in english)

**Comment by Gugui322** [comment]
Tecnicamente pode ser considerado um ”vírus” por conter injetores de dll e mapeadores de memoria. Para resolver isso é só ir no antivírus e permitir(ignorar) o arquivo .exe do CE.
