### ISSUE TITLE
Too many detections

### ISSUE THREAD

**Issue by StereoMadnessss** [cheat-engine/cheat-engine#1888]
I know cheat engine is safe but there are way too many detections 11/60?! Seriously.

**Comment by StereoMadnessss** [comment]
it says it is riskware and I downloaded it from here, which is the github. I scanned it with virustotal.

**Comment by cheat-engine** [comment]
You say it like the amount of detections matter .  You can also say that 49 out if 60 av's disagree with with a handful of AV's say

also, some of those detections are duplicate (e.g gamehack and cheat engine) and some of then are harmless (pup, downloader)

**Comment by MrSmithr** [comment]
> I know cheat engine is safe but there are way too many detections 11/60?! Seriously.

Anything that can modify memory is considered riskware by any anti-virus. Cheat Engine is perfectly safe.
