### ISSUE TITLE
about RSP in $CCODE

### ISSUE THREAD

**Issue by ragnaroks** [cheat-engine/cheat-engine#1890]
here is an example registers and stack:
```plain
rax 0020
rbx 0030
rcx 0040
rdx 0050
rsp 4000
rbp 4028

0x4000 (rsp+00) (rbp-28)   (int)1
0x4008 (rsp+08) (rbp-20)   (int)2
0x4010 (rsp+10) (rbp-18)   (int)3
0x4018 (rsp+18) (rbp-10)   (int)4
0x4020 (rsp+20) (rbp-08)   (int)5
0x4028 (rsp+28) (rbp-00)   (int)6
```
### bad script
if give a script like this:
```c
/*{$CCODE refRSP=rsp refRAX=rax}*/
  unsigned long long *ptrRSP=(unsigned long long *)refRSP;
  unsigned int rsp00=*ptrRSP;      // => 32
  unsigned int rsp18=*(ptrRSP+3);  // => 1
/*{$ASM}*/
```
in my opinion `rsp00` should be `(int)1`,but actually it's `(int)32`,the value of `rax` register.

and the `rsp18` should be `(int)4`,actually it's `(int)1`,the value of `rsp+00`.

![opcode1](https://user-images.githubusercontent.com/7598199/139575979-f306bb88-8391-4853-89e6-0a758cbc9f83.png)

as you can see,`*ptrRSP == refRAX`.

### works script
so i make this script that works fine:
```c
/*{$CCODE refRSP=rsp refRAX=rax}*/
  unsigned long long *ptrRSP=(unsigned long long *)(refRSP+0x18);
  unsigned int rsp00=*ptrRSP;      // => 1
  unsigned int rsp18=*(ptrRSP+3);  // => 4
/*{$ASM}*/
```
![opcode2](https://user-images.githubusercontent.com/7598199/139576032-d92b48fd-5358-45f1-b148-1e18cbbfcf95.png)

then the script works,but i do not know why need add 0x18 offset.

### if use `rbp` anything works fine
```c
/*{$CCODE refRBP=rbp refRAX=rax}*/
  unsigned long long *ptrRBP=(unsigned long long *)refRBP;
  unsigned int rsp00=*(ptrRBP-5);  // => 1
  unsigned int rsp18=*(ptrRBP-2);  // => 4
/*{$ASM}*/
```
![opcode3](https://user-images.githubusercontent.com/7598199/139576297-d1570e22-ad8e-437f-8915-45947d756c39.png)

**Comment by cheat-engine** [comment]
This is because before rsp gets saved it does a function call, saves rflags, and rax (3*8=0x18)

I can make rsp more accurate, but it will result in rsp being readonly (Not that changing rsp is a good idea anyhow, as you'd never get back from ccode)

**Comment by ragnaroks** [comment]
got it
