### ISSUE TITLE
ceserver throws errno 104 (ECONNRESET) when trying to pointer scan with Cheat Engine 7.2

### ISSUE THREAD

**Issue by d3suu** [cheat-engine/cheat-engine#1894]
## Problem

ceserver throws errno 104 (ECONNRESET) when trying to connect from "Pointer scan" window on Windows host.

## Hosts

ceserver - Ubuntu 20.04.2 LTS \w 5.11.0-34-generic kernel
Cheat Engine 7.2 - Windows 10 Home 20H2 Build 19042.1288

## Tried
ceserver downloaded from site
ceserver built from 7.2 release tag
libceserver-extension.so built from 7.2 release tag, in same directory as ceserver

## How to reproduce
 - On windows host, start pointer scan for any address
 - In "Pointer scan" window, set IP and Port of host with ceserver listening (problem appears regardless of "Trust stability" check)
 - Click "Add to connection list"
 - ceserver should start throwing errors
 - IP:Port remains in Network->"Connecting to:"

## ceserver log
```
~/Downloads/ce/cheat-engine-7.3/Cheat Engine/ceserver/gcc$ sudo ./ceserver -p 2138
listening on port 2138
&s=0x7ffd5bc61b84
main=0x55ebc732514b
sizeof(off_t)=8
sizeof(off64_t)=8
CEServer. Waiting for client connection
socket=3
bind=0
listen=0
IdentifierThread active
accept=4
recv returned -1
Error during recvall: -1. errno=104
read error on socket 4 (104)
accept=6
recv returned -1
Error during recvall: -1. errno=104
read error on socket 6 (104)
accept=4
recv returned -1
Error during recvall: -1. errno=104
read error on socket 4 (104)
accept=6
recv returned -1
Error during recvall: -1. errno=104
read error on socket 6 (104)
accept=4
recv returned -1
Error during recvall: -1. errno=104
read error on socket 4 (104)
accept=6
recv returned -1
Error during recvall: -1. errno=104
read error on socket 6 (104)
accept=4
recv returned -1
Error during recvall: -1. errno=104
read error on socket 4 (104)
[...]
```

**Comment by d3suu** [comment]
Added "how to reproduce" info

**Comment by cheat-engine** [comment]
The pointerscan server and ip must be a pointerscan server, not a ceserver.  Those are different protocols.

to use pointerscan on ceserver, connect to the ceserver from the processlist,  open the process, and do a pointerscsn and leave the server fields empty
