### ISSUE TITLE
bytes showed maybe need a improvement of mac CE

### ISSUE THREAD

**Issue by avboy1337** [cheat-engine/cheat-engine#1898]
Dear Master , I bought the mac version and may be there is a little improvement of display ：
the last colom of bytes is merged to the right asiic .
![image](https://user-images.githubusercontent.com/5463104/140530459-54fb3a65-87f1-4a83-a0ef-f694af1dea72.png)

**Comment by avboy1337** [comment]
when displaying bytes by double wrods or words , using mouse to pick it by one click , the whole block of double words(or words)is not highlighted as windows .

**Comment by cheat-engine** [comment]
fixed for next version
