### ISSUE TITLE
question..

### ISSUE THREAD

**Issue by divinity76** [cheat-engine/cheat-engine#19]
(sorry, its not an issue, just a question); 
Is it ok to add bugreports to github's bugtracer ("issues"), or should we stick to the mantisdb bugtracker?
does it even make a difference? does anyone care? 

(other than that, awesome that you moved it to github; i find it much better than googlecode :+1:  )

**Comment by cheat-engine** [comment]
I check both places so it doesn't make too much difference

**Comment by divinity76** [comment]
awesome.
