### ISSUE TITLE
Win10/CE7.2: Lost ability to create new folders after creating CETRAINER

### ISSUE THREAD

**Issue by fade2gray** [cheat-engine/cheat-engine#1902]
Is this a known problem?

This is my first attempt at creating a trainer in order to toggle a couple of scripts using Hotkeys.

I used `Generate generic trainer lua script from table`, added the Hotkeys and saved the result as a CETRAINER file. The trainer worked, but I decided to make some modifications and before saving the changes I decide to make a backup of the original file by copying it to a new folder - this is when I discovered that none of the normal methods to create a folder worked except to use the command window or PowerShell.

![MissingFolderOption](https://user-images.githubusercontent.com/1332009/141135458-38fbd48d-8113-4f63-beac-445722df592b.png)

It turns out that a certain registry entry had been change from `Folder` to `CT_auto_file`.

What should have been this...

![RegistryFolder-1](https://user-images.githubusercontent.com/1332009/141137602-d45be61e-b8f7-4f72-8a18-348b5b15e9be.png)

...had been changed to this...

![RegistryFolder-2](https://user-images.githubusercontent.com/1332009/141137617-f6853186-2f11-4159-aed9-6418dec19a1c.png)

**Comment by cheat-engine** [comment]
That"s not something that CE does, but have you ran other people's scripts/tables?

e.g here's a script by someone that does this : https://m.blog.naver.com/noohc0724/221372202263

**Comment by fade2gray** [comment]
Yeah, I come across that link when looking for the solution - beyond my comprehension.

I had been using an old CT for Watch_Dogs (1) that several of the functions didn't work for in my game version, and started modifying it - it was when making the CETRAINER file for just my mods when the Folder problem occurred.

I don't see any code in the original CT that manipulates the registry, and there's definitely none in the table I created.

I just wonder if I inadvertently clicked on something I shouldn't have when creating the CETRAINER - I'll try starting over and see if it recreates the same issue again.

**Comment by fade2gray** [comment]
No further issues, l'll put this down to operator error.
