### ISSUE TITLE
opening file in cheat engine with ct file

### ISSUE THREAD

**Issue by DomLindor0117** [cheat-engine/cheat-engine#1903]
when i try to open the ct file in cheat engine it says to use the newest version of cheat engine even though i have the latest wich is 7.3

**Comment by DomLindor0117** [comment]
![Cheat Engine 7 3 11_10_2021 10_17_13 PM](https://user-images.githubusercontent.com/94093248/141231165-891626f2-09a5-4c1b-a3ca-491f5a25c1e9.png)

**Comment by cheat-engine** [comment]
Perhaps someone compiled their version from github and used that to create the table.  Or you have an early release of 7.3 (E.g. first day download)
