### ISSUE TITLE
Option to choose script discription or hotkey description when creating CT hotkey

### ISSUE THREAD

**Issue by fade2gray** [cheat-engine/cheat-engine#1907]
Would it be possible to add the option to select either the script description or the hotkey description during creation? 

![HotkeyDescription](https://user-images.githubusercontent.com/1332009/141595738-79ccbaed-ede1-4871-9574-bbaaffd11d8b.png)

**Comment by cheat-engine** [comment]
change {MRDescription} to {Description}
