### ISSUE TITLE
Compile error in x64 

### ISSUE THREAD

**Issue by 1210507400** [cheat-engine/cheat-engine#1917]
tcclib.pas(416,71) Error: Incompatible types: got "Empty Set" expected ".{Dynamic} Array Of <record type>"
tcclib.pas(577,56) Error: Incompatible types: got "Empty Set" expected ".{Dynamic} Array Of <record type>"
tcclib.pas(728,17) Error: Incompatible types: got "Empty Set" expected "TSourceCodeInfo.{Dynamic} Array Of <record type>"

**Comment by cheat-engine** [comment]
Wrong compiler version

**Comment by 1210507400** [comment]
lazarus-2.0.6-fpc-3.0.4-win64.exe

**Comment by 1210507400** [comment]
cheat engine  7.3

**Comment by Symbai** [comment]
You can get a compiled nightly build from my repo if thats what you want: https://github.com/Symbai/cheat-engine/releases
