### ISSUE TITLE
Register Rax~r15 Size ? 8 -> 16

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#192]
TfrmTracer.miSaveToDiskClick

z.add(pref+'AX='+inttohex(c.{$ifdef cpu64}Rax{$else}Eax{$endif},8));
z.add(pref+'BX='+inttohex(c.{$ifdef cpu64}Rbx{$else}Ebx{$endif},8));
z.add(pref+'CX='+inttohex(c.{$ifdef cpu64}Rcx{$else}Ecx{$endif},8));
z.add(pref+'DX='+inttohex(c.{$ifdef cpu64}Rdx{$else}Edx{$endif},8));
z.add(pref+'SI='+inttohex(c.{$ifdef cpu64}Rsi{$else}Esi{$endif},8));
z.add(pref+'DI='+inttohex(c.{$ifdef cpu64}Rdi{$else}Edi{$endif},8));
z.add(pref+'BP='+inttohex(c.{$ifdef cpu64}Rbp{$else}Ebp{$endif},8));
z.add(pref+'SP='+inttohex(c.{$ifdef cpu64}Rsp{$else}Esp{$endif},8));
z.add(pref+'IP='+inttohex(c.{$ifdef cpu64}Rip{$else}Eip{$endif},8));

{$ifdef cpu64}
if processhandler.is64bit then
begin
            z.add('R8='+inttohex(c.r8,8));
            z.add('R9='+inttohex(c.r9,8));
            z.add('R10='+inttohex(c.r10,8));
            z.add('R11='+inttohex(c.r11,8));
            z.add('R12='+inttohex(c.r12,8));
            z.add('R13='+inttohex(c.r13,8));
            z.add('R14='+inttohex(c.r14,8));
            z.add('R15='+inttohex(c.r15,8));     
end;
{$endif}
          z.add('');
          z.add('EFLAGS='+inttohex(c.EFlags,8));
          z.add('');
          z.add('-');
      end;
end; 

symbolhandler.pas 2500line
0: tokens[i]:=inttohex(context^.{$ifdef cpu64}rax{$else}eax{$endif},8);

pluginexports.pas 616 line
ce_ChangeRegistersAtAddress

frmthreadlistunit.pas 613line

FoundCodeUnit.pas 586 line

Size Check Code Error?

RAX & R15 + EFLAGS => 8 -> 16 Fix?

Is the Windows 64 bit size short, not the arm code?

It seems that the copy size is 8 instead of 16

Should all be modified? There are a lot of search results (No Arm Code Fix)

**Comment by kitty8904** [comment]
https://github.com/cheat-engine/cheat-engine/commit/ae767873b5a035b2dc46b74f0847ed0aaeec75b3

I searched the source based on the latest commit content

**Comment by cheat-engine** [comment]
that's ok. the frmregister thing is just a special request by someone who prefers 0 in front for visual purpose, but it has no effect otherwise. values that need more than 8 digits will show fine

________________________________

**Comment by kitty8904** [comment]
okay close issue
