### ISSUE TITLE
Lazarus: Fatal: Cannot find projectnameunit used by cheatengine

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#1925]
I'm unable to build CE after this commit (66d2ad3ba7f4de6726f61437300b24fa00c425f5) because Lazarus fails with: `cheatengine.lpr(120,44) Fatal: Cannot find projectnameunit used by cheatengine of the Project Inspector.` It looks like you forgot to upload a unit file.

**Comment by cheat-engine** [comment]
ah ok.  You can remove that reference.  It's an empty unit.  I'll fix that

**Comment by Symbai** [comment]
Thanks!
