### ISSUE TITLE
Issue with 7.3

### ISSUE THREAD

**Issue by dontworrypleasehelp** [cheat-engine/cheat-engine#1933]
Anytime I download Cheat Engine 7.3 this the app states (once I open it) 'Windows cannot access the specified device, path or file . You may not have the appropriate permissions to access them', what should I do?

**Comment by cheat-engine** [comment]
check your notification, it should have a message there saying it was blocked. Allow it anyhow.
Or disable `reputation based protection` and any other protections like AVG ( https://github.com/cheat-engine/cheat-engine/issues/1931 )

**Comment by dontworrypleasehelp** [comment]
> 

Didn't work, same story even with mostly everything turned off in RBP

**Comment by cheat-engine** [comment]
try https://forum.cheatengine.org/viewtopic.php?p=5775275#5775275
