### ISSUE TITLE
mono inject throw dll miss exception

### ISSUE THREAD

**Issue by ragnaroks** [cheat-engine/cheat-engine#1939]
![dialog1](https://user-images.githubusercontent.com/7598199/143973266-bf0de71c-d8be-46e2-90ae-6f1943d32cd6.png)

it's require `MSVCP140D.dll`、`VCRUNTIME140D.dll`、`ucrtbased.dll`,i find and put these files in **CHEAT ENGINE INSTALL PATH**,now it's require `api-ms-win-core.......`

test game is [Brave Furries](https://store.steampowered.com/app/355280/Brave_Furries/)

**Comment by cheat-engine** [comment]
selfcompiled or downloaded? And if downloaded, which version?

**Comment by ragnaroks** [comment]
download from [here](https://www.patreon.com/posts/cheat-engine-7-3-57174240) , **CheatEngine7.3.2P.exe**

**Comment by avboy1337** [comment]
dll injection is truely something not ok ,i think.
also donwload from official link of patro.

**Comment by cheat-engine** [comment]
you'll need to install visual studio 2017 for the 32 bit version dll of 7.3.2 to work

it'll be fixed next releasd
