### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by metalJeebus** [cheat-engine/cheat-engine#1949]
I have tried everything from no security at all to leaving one or 2 bits on and im getting nothing but the following 
"cant find path or directory you might not have permission to access this file"   

"unable to execute this fine in temporary directory. setup aborted 
Error 5: Access is denied"
or the installer tries to open then closes itself down. 

Can anybody assist me with this please?

**Comment by Frede5** [comment]
Having the same issue :[

**Comment by fade2gray** [comment]
[https://github.com/cheat-engine/cheat-engine/issues?q=is%3Aissue+is%3Aopen+cant+open+cheat+engine](https://github.com/cheat-engine/cheat-engine/issues?q=is%3Aissue+is%3Aopen+cant+open+cheat+engine)

**Comment by metalJeebus** [comment]
> https://github.com/cheat-engine/cheat-engine/issues?q=is%3Aissue+is%3Aopen+cant+open+cheat+engine

This just links to the forum list?

**Comment by fade2gray** [comment]
It's a link that is a result of performing a search for all issues using the search term 'cant open cheat engine' - try reading them for their solutions, particularly the Pinned Issue at the very top.

**Comment by metalJeebus** [comment]
I have already read through multiple of them (first thing you do on forums like this before you ask a question as im not entirely braindead) and attempted everything that I have seen advised from the ones I have viewed, pinned post included and still in the same place I was when I started trying to get this to work.

**Comment by fade2gray** [comment]
Most problems arise from whatever antivirus you use, or the fact you may BadLion AntiCheat on your system as a result of playing MineCraft.

Disable `Real-time protection` in `Windows Security > Virus & threat protection`.

Disable `Reputation-based protection` in `Windows security > App & browser control`.

If you have Badlion on your system, try removing it with the advice given [here](https://www.badlion.net/forum/thread/230238).

**Comment by metalJeebus** [comment]
I have already disabled both of those and Ive never installed Minecraft on my PC so dont have BadLion, I have also done a search for BL just on the off change any other game I own has it linked to it and it is not on my PC at all.

**Comment by metalJeebus** [comment]
@fade2gray  If it helps here is the bla.txt  https://pastebin.com/8TrMz5BH

**Comment by cheat-engine** [comment]
restart windows and try again

also check the notification center in windows

**Comment by metalJeebus** [comment]
> restart windows and try again
> 
> also check the notification center in windows

I have lost count of how many restarts I have done...

**Comment by metalJeebus** [comment]
@cheat-engine  Any idea what could be causing this or how I can work around it?
