### ISSUE TITLE
lazarus 1.8 update

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#195]
New version of Lazarus shared
(http://forum.lazarus.freepascal.org/index.php/topic,36907.0.html)

Fixed a bug in 1.6.4 that was updated to 1.8?

Or were there any bugs? (1.6.4)

No Update(1.8) Using version 1.6?

**Comment by cheat-engine** [comment]
for now using my custom build of 1.6.4 which has most of the bugs that affects CE fixed (small stuff like treeview selections, header dragging, etc...)

**Comment by kitty8904** [comment]
ok close
