### ISSUE TITLE
Compiler issue

### ISSUE THREAD

**Issue by Ceivent** [cheat-engine/cheat-engine#1951]
I'm getting an error saying fpc.exe does not support target i386-win32, I've downloaded and installed the cross-x86_64-win64-win32 file. not sure how to fix it.

**Comment by raxcode1** [comment]
Hi, did you solved it?

**Comment by fade2gray** [comment]
Maybe You are using the incorrect version of Lazarus - check the build instructions again.

https://github.com/cheat-engine/cheat-engine#basic-build-instructions

![Screenshot 2024-01-18 164529](https://github.com/cheat-engine/cheat-engine/assets/1332009/f15d44a8-1c6c-49c6-ad29-f8c614b35afe)

(Lazarus 2.2.6 will also work)

**Comment by raxcode1** [comment]
Thanks man! 🙏
