### ISSUE TITLE
Where is PDebugEvent defined?

### ISSUE THREAD

**Issue by TheK0tYaRa** [cheat-engine/cheat-engine#1959]
I can't find it in FPC docs and in the files i only see it in ceserver/api.c
_There is only soup._

**Comment by TheK0tYaRa** [comment]
The context is  possible unixporthelper expansion

**Comment by TheK0tYaRa** [comment]
And yes, i have realized that trying to make a copy in rust just to make a linux port is stupid. And confusing.

**Comment by cheat-engine** [comment]
It's in the windows uses file
for a port in another os you'll have to emulate that structure so internally CE translates it (which happens in the waitfordebugevent function)
