### ISSUE TITLE
x86 x64 stiring view fix

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#196]
frmModifyRegistersUnit.pas

90 line add pref : string

98 line add

  if processhandler.is64bit then
  begin
  pref:='R'
  end
  else
  begin
  pref:='E'
  end;

  label1.Caption:=pref+'AX';
  label2.Caption:=pref+'BX';
  label3.Caption:=pref+'CX';
  label4.Caption:=pref+'DX';
  label5.Caption:=pref+'SI';
  label6.Caption:=pref+'DI';
  label7.Caption:=pref+'BP';
  label8.Caption:=pref+'SP';
  label9.Caption:=pref+'IP';

![fix](https://user-images.githubusercontent.com/18622105/26891694-e967dcb6-4bf0-11e7-8f04-2bd50eb2dc3b.png)

Edit View Target Process Caption Name

I do not know how to request github pull

**Comment by kitty8904** [comment]
and Flags List DF(string) Flag?

**Comment by cheat-engine** [comment]
no DF for now
