### ISSUE TITLE
Where is defined and what means STANDALONEHV

### ISSUE THREAD

**Issue by TheK0tYaRa** [cheat-engine/cheat-engine#1962]
Procedure `copymemory` is hiding behind the `ifdef STANDALONEHV` and is the only definition for it but it being behind the said ifdef makes it unavailable to textrender unit. Should it be rewritten for linux compatibility or am i just confused?

**Comment by cheat-engine** [comment]
it's in project settings custom options as one of the defines.  

Don't use it as standalonehv is a seperate standalone hexview project for file editing, normal use will use readProcessMemory to copy the data

**Comment by TheK0tYaRa** [comment]
So unit textrender function renderFormattedText is not to worry about?

**Comment by cheat-engine** [comment]
no.  At most things will be slow, but for that look at the carbon defines.  
But i recommend first get it working before looking into performance
