### ISSUE TITLE
Changed values don't actually change

### ISSUE THREAD

**Issue by ThatKakiGuy** [cheat-engine/cheat-engine#1967]
Freezing doesn't seem to really do anything either, am I doing something wrong?

Video:
https://youtu.be/S7nlCzaFZ0Q

**Comment by cheat-engine** [comment]
The real value is likely stored differently. 
Could be it's stored clip+total or encoded or something else

**Comment by ThatKakiGuy** [comment]
Oh, yeah, that was the case
