### ISSUE TITLE
I can't download because antivirus found malware in installer. 

### ISSUE THREAD

**Issue by UnrealKaraulov** [cheat-engine/cheat-engine#1976]
Please disable malware in installer, antivirus found one.

I want to download CE without malwares.

**Comment by fade2gray** [comment]
You need to allow an exception in Windows security, and/or 3rd party antivirus, for your downloads folder.

See if this helps. #1954

**Comment by UnrealKaraulov** [comment]
> You need to allow an exception in Windows security, and/or 3rd party antivirus, for your downloads folder.
> 
> See if this helps. #1954

@fade2gray 

I don't like to install malware in my Windows, how to download clean installer?

**Comment by Symbai** [comment]
Join CE's Patreon or build it yourself or download a nightly build from my repo https://github.com/Symbai/cheat-engine/releases (you still must build VEH debugger, monopipe etc. yourself or take them from an existing installation)

**Comment by fade2gray** [comment]
See the video at 2 minutes 30 seconds.
![OptionalOffers](https://user-images.githubusercontent.com/1332009/147760263-0c439f83-2f82-42bf-9e54-5757a37178fa.png)

**Comment by UnrealKaraulov** [comment]
> See the video at 2 minutes 30 seconds. ![OptionalOffers](https://user-images.githubusercontent.com/1332009/147760263-0c439f83-2f82-42bf-9e54-5757a37178fa.png)

THIS IS MALWARE, NEED CLEAN INSTALLER

**Comment by cheat-engine** [comment]
It's not

**Comment by UnrealKaraulov** [comment]
Malware detected by multiple antivirus, if it false, author be report it to antivirus labs. This is really malware.

**Comment by cheat-engine** [comment]
I disagree.  It's safe.  Those AV's aren't worth my time to figure out where to report false detections, that's up to their users.

And keep in mind pup, pua, adware, hacktool and suspicious are not malware, just warnings for stupid users

and if you're worried about artemis (mcafee) even the adfree version has that one (including the others)

also CE is downloaded and succesfully installed over a million times each month, there'd be a lot more posts about damaged systems.

**Comment by UnrealKaraulov** [comment]
This is really malware 
![Screenshot_20211230-192452](https://user-images.githubusercontent.com/88730285/147769964-db6eb4c4-ed78-424b-8a4e-bb07fbe9f154.png)
![Screenshot_20211230-192409](https://user-images.githubusercontent.com/88730285/147769974-13c63297-f1da-410a-85ca-7ca704c0bcc3.png)
![Screenshot_20211230-192359](https://user-images.githubusercontent.com/88730285/147769986-a54b8c89-6071-4b65-ba7f-8a7359899b02.png)
![Screenshot_20211230-192345](https://user-images.githubusercontent.com/88730285/147770004-cb39e87d-3948-43ce-92f5-ed7961939e52.png)
![Screenshot_20211230-192336](https://user-images.githubusercontent.com/88730285/147770010-1405a57a-629b-4909-82d1-e6e6dabd7d89.png)
![Screenshot_20211230-192327](https://user-images.githubusercontent.com/88730285/147770013-3a2059fc-b86c-4c63-9330-76467249ac46.png)

**Comment by cheat-engine** [comment]
That doesn't say anything.  Just that av's detect it and that people cry about their av's detecting it.

There's no proof.  This is one of those typical scareware sites that scare people into buying their product

anyhow, i'm not going to bother convincing you that it's safe.  Get the patreon version if you want (although i'm sure your scareware shit will cry about that as well)

so i'm closing this issue

**Comment by UnrealKaraulov** [comment]
@cheat-engine okay now I report your website to all know sources as malware website.

**Comment by cheat-engine** [comment]
that's fine.  I'll sue you for slander

**Comment by xastrix** [comment]
AHAHAHAHAHA. Perhaps I will save this in my archive of funny and truly incompetent people who don't understand what they're talking about. It's very interesting how this guy writes code.
