### ISSUE TITLE
Feature Request - Automate loading

### ISSUE THREAD

**Issue by Punchin83** [cheat-engine/cheat-engine#1978]
I'd like to see a feature where you can click on the individual loading docks and tell them to load cargo and they will automatically trigger enough to fill 1 car full of their respective product. This would streamline solo loading of long trains a LOT.

**Comment by Symbai** [comment]
![Sigh-Uhhm-Ehm-Yeah-No-Ugh-Ok-Whatever-Neil-Patrick-Harris-GIF-2015](https://user-images.githubusercontent.com/14368203/147813355-05b6ffe2-e92d-42f6-a6d9-33fa351a2217.gif)
