### ISSUE TITLE
Memory View Text Encoding 

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#198]
ascii
utf-8
utf-16
codepage view add?

![bug](https://user-images.githubusercontent.com/18622105/26894107-6a6ef2ac-4bf8-11e7-939e-de9740e9a2dc.png)

**Comment by kitty8904** [comment]
basic search -> utf8?

unicode search ->utf16

code page search -> Memory View Text Encoding Not View

**Comment by kitty8904** [comment]
![stst](https://user-images.githubusercontent.com/18622105/26894808-75a8b3b8-4bfa-11e7-9062-fe31f79bd951.png)

한글
CodePage -> C7 D1 B1 DB
UTF 8 -> ED 95 9C EA B8 80
UTF 16 -> 5C D5 00 AE

**Comment by kitty8904** [comment]
View source search results text There is no code page

**Comment by Adrian-Pop** [comment]
The same happens for Latin characters that are UTF-8. The characters are missing even in the output file.
![chengine](https://user-images.githubusercontent.com/15738293/32544722-fb8b7d08-c481-11e7-994b-0b32b8df8c85.png)
