### ISSUE TITLE
Compile Issue: Identifier not found "TSynEditorOptions"

### ISSUE THREAD

**Issue by N15A8** [cheat-engine/cheat-engine#1995]
Hey there,
I've been trying to compile Cheat Engine but it always gives me the same error (frmAAEditPrefsUnit.pas(50,16) Error: Identifier not found "TSynEditorOptions"). When installing Lazarus I've tried both the 64-bit version + 32 bit addon aswell as the 32 bit version with the 64 bit addon. That is apparently what helped others online to fix it.
All I'm doing after installation:
1. Open cheatengine.lpr in Lazarus
(On startup it says Fppkg config isn't found, I click on start anyway)
2. Click Run and Compile many modes

**Comment by fade2gray** [comment]
Are you using the links provided in the README > Build Instructions, i.e., Lazarus edition 2.0.10?

**Comment by N15A8** [comment]
Wow! Thank you. I've been using the links from the Lazarus page. After trying the provided links it worked.
