### ISSUE TITLE
[ Compile Error ] Identifier not found "TSynEditorOptions"

### ISSUE THREAD

**Issue by xFadedxShadow** [cheat-engine/cheat-engine#1997]
`frmAAEditPrefsUnit.pas(50,16) Error: Identifier not found "TSynEditorOptions"
frmAAEditPrefsUnit.pas(50,33) Error: Error in type definition`

That is the error i get when building!

Just firgured out why please put on the main github page to let users know that they need to install an older version of lazarus

**Comment by fade2gray** [comment]
#1995

**Comment by fade2gray** [comment]
@xFadedxShadow

"Just firgured out why please put on the main github page to let users know that they need to install an older version of lazarus"

Just use the download links in the README > Build Instructions.
