### ISSUE TITLE
6.7 - Editors Do Not Honor Tab Sizes

### ISSUE THREAD

**Issue by atom0s** [cheat-engine/cheat-engine#200]
Editors such as the cheat tables Lua script editor do not honor the tab settings in the preferences. If set to the default 4 spaces per tab, pressing tab only inserts 2 spaces. Also if you tab multiple times, the results seem entirely random. Sometimes it will tab 2 or 4 spaces, other times it can tab over 100 spaces. 

If you code a function such as: 

```lua
function test() 

end 
```

Then place your cursor on the blank line between the function and end, press tab, it will tab about 10 spaces. The tabbing seems to be very inconsistent and very random rather than honoring the users settings. 

Same issues happen while things are highlighted, or the cursor is placed in varying places such as before a word, mid word, etc.

**Comment by atom0s** [comment]
Side note, this happens with Smart Tabs enabled. Seems they are not that smart.

**Comment by mgrinzPlayer** [comment]
Experiment 1:
```
function testthis()            --a comment

end
```
I pressed 1tab2tab3tab4tab5tab6tab7tab8
```
function testthis()            --a comment
1        2                     3   4      5 6   7   8
end
```
-------
Experiment 2 (comment is one char longer): 
```
function testthis()            --a comment2

end
```
I pressed 1tab2tab3tab4tab5tab6tab7tab8
```
function testthis()            --a comment2
1        2                     3   4       5    6   7   8
end
```
-------
Experiment 3:
just type x tab x tab x tab few times
```
x   x   x   x   x   x   x   x   x   x   x   x   x   x   x
```
------
side by side comparison
```
1        2                     3   4      5 6   7   8
1        2                     3   4       5    6   7   8
x   x   x   x   x   x   x   x   x   x   x   x   x   x   x
```

Conclusion:
It detects columns in above line, this is why 1 2 3 4 are at the same position.
5 is placed where previous line ends (prevLineLength+1)
6 7 8 are adjusted to (N*4+1) position.
