### ISSUE TITLE
Can't compile Error: ppc386.exe can't be executed, error message: Failed to execute

### ISSUE THREAD

**Issue by micpitbull** [cheat-engine/cheat-engine#2004]
I have installed a older version of Lazarus 2.0.12 

but still I can't compile Cheat Engine I am getting error 

Error: ppc386.exe can't be executed, error message: Failed to execute ""ppc386.exe"  -B -Twin32 -MObjFPC -Scghi -O1 -g -gl -l -vewnhibq -Fuc:\lazarus\packager\registration\ -FUc:\lazarus\packager\units\i386-win32\ fcllaz.pas

**Comment by skrlst** [comment]
same.

**Comment by fade2gray** [comment]
You need to use 2.2.2 for the latest master source and 2.0.10 for the current 7.4 release source.

**Comment by a0225** [comment]
I'm using lazarus version 2.2.2 and cheat engine version 7.5 and i have the same error.
Error: ppc386 can't be executed, error message: Failed to execute "ppc386", error code: 127

**Comment by fade2gray** [comment]
Did you install the associated Lazarus 2.2.2 32-bit cross-compiler?

Have a look at the build instructions - https://github.com/cheat-engine/cheat-engine#basic-build-instructions
