### ISSUE TITLE
Installator error 5 for version 7.4

### ISSUE THREAD

**Issue by isillo** [cheat-engine/cheat-engine#2006]
Cant install Cheat Engine 7.4. Getting error during installation. It says: "Unable to execute file in the temporary directory. Setup aborted. Error 5: Access is denied.". Dont have that problem with version 7.3. Please advise.

**Comment by cheat-engine** [comment]
Have you tried what's explained at https://github.com/cheat-engine/cheat-engine/issues/1954  ?
