### ISSUE TITLE
6.7 - Autoassembler Executes Lua Immediately (Ignores ENABLE/DISABLE tags.)

### ISSUE THREAD

**Issue by atom0s** [cheat-engine/cheat-engine#201]
When adding special auto-assembler scripts with Lua functions in them, Lua stuff is called incorrectly at the wrong times. 

Here is a quick step by step to reproduce this bug: 

- Create a new table. 
- Create a new Lua script for the table. 
- In the script, define something such as: 

```lua
function TestFunction() 
    print('TestFunction was called.'); 
end 
```

- In the address list, create a new auto-assembler script. (CTRL+ALT+A) 
- In the auto-assembler script, enter: 

```lua
[ENABLE] 
{$LUA} 
TestFunction() 

[DISABLE] 
{$LUA} 
TestFunction() 
```
- Assign the script to the cheat table. 

At this point TestFunction will be called twice. Edit the script again, click OK. It will call the function twice again. Visually, this looks like the function will only be called when the script is toggled on and off. (Which does work in that way.) But, it is being called no matter what the context is or how the script is written. It will always call the function which is not ideal.

**Comment by FreeER** [comment]
> Assign the script to the cheat table.
> At this point TestFunction will be called twice. 

Isn't this simply due to the syntax check? Something like this shouldn't do that
```
[ENABLE]
{$LUA}
if syntaxcheck then return end
TestFunction()

[DISABLE]
{$LUA}
if syntaxcheck then return end
TestFunction()

```

**Comment by atom0s** [comment]
Wasn't aware of the **syntaxcheck** variable being a thing now, thanks for the heads up on that. Works as intended with that.
