### ISSUE TITLE
Windows detects that Cheat Engine is a unwanted app.

### ISSUE THREAD

**Issue by JoshuaMrtz11** [cheat-engine/cheat-engine#2017]
Hey there, I was trying to use cheat engine for to try it out, but then when I open the installer, it says that it's a unwanted app. Can you try to fix this so I can use Cheat Engine?

(here's the image showing that it's a unwanted app)
![image](https://user-images.githubusercontent.com/75928247/151089331-0c453fa9-0af0-4a55-8755-c2fbc12ce545.png)

**Comment by cheat-engine** [comment]
Ask microsoft if they'd be so nice to remove that tag

**Comment by fade2gray** [comment]
> Windows detects that Cheat Engine is a unwanted app.

The thing is, **_do YOU want the app_**? If you do, then follow this #1954.

**Comment by JoshuaMrtz11** [comment]
Okay I got it, thank you! :)
