### ISSUE TITLE
6.7 - Editor Preferences Do Not Save

### ISSUE THREAD

**Issue by atom0s** [cheat-engine/cheat-engine#202]
Open the auto-assembler window, Lua script window, etc. and change the editor preferences, such as disabling Smart Tabs. Close Cheat Engine and reopen it. The settings will reset to default and not carry over between launches.

**Comment by mgrinzPlayer** [comment]
It doesn't save "smart tabs" and "tabs to spaces" and "tab width". I'm making a patch.

**Comment by mgrinzPlayer** [comment]
AA Edit Prefs fix #203 pull request sent.

**Comment by mgrinzPlayer** [comment]
should be fixed. Test my custom build or wait for hotfix.
