### ISSUE TITLE
use ce to open chrome and change the speed, following error displayed

### ISSUE THREAD

**Issue by avboy1337** [cheat-engine/cheat-engine#2035]
![image](https://user-images.githubusercontent.com/5463104/151956581-9d2bfd46-2ab2-47a9-a454-d4fa61162bb9.png)

**Comment by cheat-engine** [comment]
have you compiled the latest tcc library files ?

**Comment by avboy1337** [comment]
> have you compiled the latest tcc library files ?

sorry ,i did not.
I am going to have a try.
