### ISSUE TITLE
Speedhack TCC Library Issue

### ISSUE THREAD

**Issue by valentine37** [cheat-engine/cheat-engine#2037]
![error](https://user-images.githubusercontent.com/98923861/152254015-35d27fa1-610e-4a87-9e2e-0529f8e23d29.PNG)
I'm getting this error when I try to enable Speedhack.

I've tried running compileTCCLib() in the Cheat Table Lua Script, but the issue persists.
I've attempted using different versions of CE and different games, but that has not solved the issue.
I've tried opening the game after CE and opening CE after the game; no fixes there either.
I also ran a Hello World, just to make sure the problem wasn't with executing scripts; that successfully printed, so that shouldn't be the issue.

**Comment by avboy1337** [comment]
bro ，plz may i know how to compile this  lib .
i encoutered this error also

**Comment by cheat-engine** [comment]
Have you compiled tcc gor both 32 and 64 bit?

**Comment by valentine37** [comment]
The builds I used were both self-compiled builds; one is my compile of the 7.4 zip, and the other is Symbai's compiled 7.3.2 build.
Both are x86_64 files, so I think they're both 64-bit programs.
I'm not sure how to compile tcc for both 32 and 64 bit.

**Comment by cheat-engine** [comment]
if the target is 32 bit you'll need to build tcc64-32.dll

**Comment by valentine37** [comment]
On a double check, the same error shows up for both 32-bit and 64-bit target programs.
I'm not sure how to build any tcc dll file; I am unable to find any specific documentation about this, besides the existence of compileTCCLib() in the celua.txt, which as noted has not worked.

**Comment by avboy1337** [comment]
there is a tcc.sln in D:\cheat-engine\Cheat Engine\tcclib\win32\tcc 
just use vs2022 to compile this lib is OK
and i tried , there is no error.

**Comment by viktorcpp** [comment]
Can confirm "Incorrect tcc library".

and after building tcc64-64.dll with VS2019 got this
![OtDdwWe](https://user-images.githubusercontent.com/1128037/155197312-3ac5a674-a3de-48f5-9626-5da0cc1471c4.png)

**Comment by valentine37** [comment]
Alright, just got it working, using VS2022 to build tcc.sln, as mentioned by avboy1337.

Bad instructions for the less tech-savvy, like myself:
1. Open tcc.sln with Visual Studio.
2. Under the Project menu tab, retarget the solution (I believe this makes it work with your new version of VS?)
3. Under the Build menu tab, open the Configuration manager.
4. Change your active solution configuration to "Output to 32 (Release)," and your active solution platform to Win32.
5. Under the Build menu tab, build the solution.
6. Repeat steps 4 and 5, but with the other 3 combinations of configurations 32 (Release) and 64 (Release), and platforms Win32 and x64, because if you aren't entirely sure how bits work (like me), you may as well make sure it'll work for everything.
7. There should no longer be issues with incorrect tcc libraries.

**Comment by OdshDays** [comment]
> Alright, just got it working, using VS2022 to build tcc.sln, as mentioned by avboy1337.
> 
> Bad instructions for the less tech-savvy, like myself:
> 
> 1. Open tcc.sln with Visual Studio.
> 2. Under the Project menu tab, retarget the solution (I believe this makes it work with your new version of VS?)
> 3. Under the Build menu tab, open the Configuration manager.
> 4. Change your active solution configuration to "Output to 32 (Release)," and your active solution platform to Win32.
> 5. Under the Build menu tab, build the solution.
> 6. Repeat steps 4 and 5, but with the other 3 combinations of configurations 32 (Release) and 64 (Release), and platforms Win32 and x64, because if you aren't entirely sure how bits work (like me), you may as well make sure it'll work for everything.
> 7. There should no longer be issues with incorrect tcc libraries.

Cant figure out how to retarget the solution

**Comment by fade2gray** [comment]
@cheat-engine 

If I self compile CE using Lazarus but don't build the tcc libraries as instructed above, I _**don't**_ get the above error when enabling Speedhack, and it works for the games I've tried it with.

So, under what circumstances might anyone get the error?

**Comment by cheat-engine** [comment]
if you don't compile the speedhack dll's (both 32 and 64-bit) CE will fallback on runtime compiling speedhack into the target process, and for that tcc is needed

**Comment by fade2gray** [comment]
Thanks for the heads-up.

**Comment by hello6798** [comment]
> Alright, just got it working, using VS2022 to build tcc.sln, as mentioned by avboy1337.
> 
> Bad instructions for the less tech-savvy, like myself:
> 
>     1. Open tcc.sln with Visual Studio.
> 
>     2. Under the Project menu tab, retarget the solution (I believe this makes it work with your new version of VS?)
> 
>     3. Under the Build menu tab, open the Configuration manager.
> 
>     4. Change your active solution configuration to "Output to 32 (Release)," and your active solution platform to Win32.
> 
>     5. Under the Build menu tab, build the solution.
> 
>     6. Repeat steps 4 and 5, but with the other 3 combinations of configurations 32 (Release) and 64 (Release), and platforms Win32 and x64, because if you aren't entirely sure how bits work (like me), you may as well make sure it'll work for everything.
> 
>     7. There should no longer be issues with incorrect tcc libraries.

i did this and still have the issue

**Comment by ToastInAMicrowave** [comment]
> Alright, just got it working, using VS2022 to build tcc.sln, as mentioned by avboy1337.
> 
> Bad instructions for the less tech-savvy, like myself:
> 
> 1. Open tcc.sln with Visual Studio.
> 2. Under the Project menu tab, retarget the solution (I believe this makes it work with your new version of VS?)
> 3. Under the Build menu tab, open the Configuration manager.
> 4. Change your active solution configuration to "Output to 32 (Release)," and your active solution platform to Win32.
> 5. Under the Build menu tab, build the solution.
> 6. Repeat steps 4 and 5, but with the other 3 combinations of configurations 32 (Release) and 64 (Release), and platforms Win32 and x64, because if you aren't entirely sure how bits work (like me), you may as well make sure it'll work for everything.
> 7. There should no longer be issues with incorrect tcc libraries.

sorry if this is a stupid question (im like a grandma when it comes to this type of stuff) but what do you mean by "the other 3 combinations of configurations 32 (Release) and 64 (Release), and platforms Win32 and x64"

**Comment by ForgotMyCode** [comment]
> > Alright, just got it working, using VS2022 to build tcc.sln, as mentioned by avboy1337.
> > Bad instructions for the less tech-savvy, like myself:
> > 
> > 1. Open tcc.sln with Visual Studio.
> > 2. Under the Project menu tab, retarget the solution (I believe this makes it work with your new version of VS?)
> > 3. Under the Build menu tab, open the Configuration manager.
> > 4. Change your active solution configuration to "Output to 32 (Release)," and your active solution platform to Win32.
> > 5. Under the Build menu tab, build the solution.
> > 6. Repeat steps 4 and 5, but with the other 3 combinations of configurations 32 (Release) and 64 (Release), and platforms Win32 and x64, because if you aren't entirely sure how bits work (like me), you may as well make sure it'll work for everything.
> > 7. There should no longer be issues with incorrect tcc libraries.
> 
> sorry if this is a stupid question (im like a grandma when it comes to this type of stuff) but what do you mean by "the other 3 combinations of configurations 32 (Release) and 64 (Release), and platforms Win32 and x64"

There are 4 combinations they talk about:
• Output to 32 (Release) + Win32 (builds tcc64-32.dll)
• Output to 32 (Release) + x64 (also builds tcc64-32.dll)
• Output to 64 (Release) + Win32 (builds tcc32-64.dll outside of /bin folder, I don't think this configuration really does anything)
**• Output to 64 (Release) + x64 (builds tcc64-64.dll <-- this is likely the only one you actually need)**
