### ISSUE TITLE
About the direct download installer

### ISSUE THREAD

**Issue by Stzx** [cheat-engine/cheat-engine#2038]
Hi,

Projects like `scoop` do not currently handle new downloader programs very well. Is it currently possible to provide a direct download link to the program?

**Comment by fade2gray** [comment]
Not unless you become a paying patron in order to support the development of CE - [Patreon](https://www.patreon.com/posts/cheat-engine-7-4-60641229)

**Comment by rashil2000** [comment]
> Not unless you become a paying patron in order to support the development of CE - [Patreon](https://www.patreon.com/posts/cheat-engine-7-4-60641229)

Is this officially confirmed by the Cheat Engines devs?

**Comment by fade2gray** [comment]
No, but I think you will find an official response by @cheat-engine will be very similar.

**Comment by Stzx** [comment]
Closed: https://github.com/ScoopInstaller/Extras/commit/62dff3fdc74bcca3453625ef6d4ba4711bca34c1
