### ISSUE TITLE
symbol+offset address resolving problem

### ISSUE THREAD

**Issue by mgrinzPlayer** [cheat-engine/cheat-engine#205]
Steps:

- I renamed autorun folder name to "donotautorun" to be perfectly sure this issue is not caused by Lua extensions

- open MemoryViewer and use "go to address" window

- paste the address (symbol+offset form) and click OK

CE sometimes goes to wrong place, examples:

- [NOT OK] the game is DungeonSiege and address is "DungeonSiege.Rules::ChangeMana+2B5". Memory Viewer will go to "DungeonSiege.exe+7ED17" instead of "DungeonSiege.exe+1AC43E"

- [OK] the game is Prey and address is "Prey.AK::Monitor::PostCode+15455F9". Memory Viewer will go to proper address "Prey.exe+1682599"

---

Other example:
```Lua
function giveModuleAndOffset(address)
  local modulesTable,size = enumModules(),0
  for i,v in pairs(modulesTable) do
    size = getModuleSize(v.Name)
    if address>=v.Address and address<=v.Address+size
      then return v.Name..'+'..string.format('%X',address-v.Address) end
  end
  return '0'
end

function CE_address_resolving_tester(address)
  print('Address: '..address)

  local addressInSymbolForm = getNameFromAddress(address)
  print('\r\n\r\nabove in getNameFromAddress gives: "'..addressInSymbolForm..'"')

  local addressAsNumber = getAddress(addressInSymbolForm)
  print('above in getAddress gives: '..string.format('%X',addressAsNumber))

  local fullCircle = giveModuleAndOffset(addressAsNumber)
  print('which is: '..fullCircle)

  if fullCircle:lower()==address:lower() then
    print('"'..fullCircle..'" is equal to initial "'..address..'", test is ok')
  else
    print('"'..fullCircle..'" is not equal to initial "'..address..'", test is NOT OK')
  end
end
```
---

Problematic DungeonSiege game and this
```
CE_address_resolving_tester('DungeonSiege.exe+1AC43E')
```
 will give
```
Address: DungeonSiege.exe+1AC43E


above in getNameFromAddress gives: "DungeonSiege.Rules::ChangeMana+2B5"
above in getAddress gives: 47ED17
which is: DungeonSiege.exe+7ED17
"DungeonSiege.exe+7ED17" is not equal to initial "DungeonSiege.exe+1AC43E", test is NOT OK 
```

---

This works as should. Prey game and this
```
CE_address_resolving_tester('Prey.exe+1682599')
```
 will give
```
Address: Prey.exe+1682599 


above in getNameFromAddress gives: "Prey.AK::Monitor::PostCode+15455F9" 
above in getAddress gives: 141682599 
which is: Prey.exe+1682599 
"Prey.exe+1682599" is equal to initial "Prey.exe+1682599", test is ok 
```

**Comment by mgrinzPlayer** [comment]
Build made on source from Jun 22, 2017 still has this bug.

**Comment by cheat-engine** [comment]
Perhaps dungeonsiege has defined ChangeMana twice and there is a conflict with the lookup

print(string.format('DungeonSiege.Rules::ChangeMana=%x'),getAddress('DungeonSiege.Rules::ChangeMana')
print(string.format('DungeonSiege.Rules::ChangeMana+2b5=%x'),getAddress('DungeonSiege.Rules::ChangeMana+2b5')

**Comment by mgrinzPlayer** [comment]
Dungeon Siege 1 on Steam

**Comment by mgrinzPlayer** [comment]
```Lua
print(string.format('DungeonSiege.Rules::ChangeMana=%x',getAddress('DungeonSiege.Rules::ChangeMana') or 0))
print(string.format('DungeonSiege.Rules::ChangeMana+2b5=%x',getAddress('DungeonSiege.Rules::ChangeMana+2b5') or 0))

DungeonSiege.Rules::ChangeMana=47ea62
DungeonSiege.Rules::ChangeMana+2b5=47ed17
```

**Comment by cheat-engine** [comment]
Looks valid yes, no calculation error, just getting a different address
Check out memview->view->enumerate dll's and search for Rules::ChangeMana
It's possible it's defined twice.  (check the memory at 47ea62, it may be a string)

**Comment by mgrinzPlayer** [comment]
It's defined twice.
