### ISSUE TITLE
ceserver connection error

### ISSUE THREAD

**Issue by Cmpote** [cheat-engine/cheat-engine#2050]
> Build with latest ceserver 

---

**Both arm and x86 architectures have been tried. Android emulator is used. I would like to know what is causing the connection not to work.**

![](https://s3.bmp.ovh/imgs/2022/02/4e7df66a1f43bde6.jpg)

**Comment by ds20211213** [comment]
The output suggests that the ceserver is not up to date.
The latest version gives the following output.

```
listening on port 52736
&s=0x7fd5160284
main=0x556e5c1854
sizeof(off_t)=8
sizeof(off64_t)=8
sizeof(uintptr_t)=8
sizeof(long)=8
CEServer. Waiting for client connection
IdentifierThread active
socket=5
successfully bound socket
Listening success
```

**Comment by Cmpote** [comment]
> 输出表明 ceserver 不是最新的。 最新版本提供以下输出。
> 
> ```
> listening on port 52736
> &s=0x7fd5160284
> main=0x556e5c1854
> sizeof(off_t)=8
> sizeof(off64_t)=8
> sizeof(uintptr_t)=8
> sizeof(long)=8
> CEServer. Waiting for client connection
> IdentifierThread active
> socket=5
> successfully bound socket
> Listening success
> ```



> The output suggests that the ceserver is not up to date. The latest version gives the following output.
> 
> ```
> listening on port 52736
> &s=0x7fd5160284
> main=0x556e5c1854
> sizeof(off_t)=8
> sizeof(off64_t)=8
> sizeof(uintptr_t)=8
> sizeof(long)=8
> CEServer. Waiting for client connection
> IdentifierThread active
> socket=5
> successfully bound socket
> Listening success
> ```

Downloading from the master branch has this problem. Downloading from tag does not have this problem, thank you. Problem solved.

**Comment by Cmpote** [comment]
> The output suggests that the ceserver is not up to date. The latest version gives the following output.
> 
> ```
> listening on port 52736
> &s=0x7fd5160284
> main=0x556e5c1854
> sizeof(off_t)=8
> sizeof(off64_t)=8
> sizeof(uintptr_t)=8
> sizeof(long)=8
> CEServer. Waiting for client connection
> IdentifierThread active
> socket=5
> successfully bound socket
> Listening success
> ```

Downloading from the master branch has this problem. Downloading from tag does not have this problem, thank you. Problem solved.

**Comment by send010** [comment]
> > 输出表明 ceserver 不是最新的。最新版本提供以下输出。
> > ```
> > listening on port 52736
> > &s=0x7fd5160284
> > main=0x556e5c1854
> > sizeof(off_t)=8
> > sizeof(off64_t)=8
> > sizeof(uintptr_t)=8
> > sizeof(long)=8
> > CEServer. Waiting for client connection
> > IdentifierThread active
> > socket=5
> > successfully bound socket
> > Listening success
> > ```
> 
> 从master分支下载有这个问题。从标签下载没有这个问题，谢谢。问题解决了。

兄弟~ ceserver从哪里下载，自己编译的吗？

**Comment by ds20211213** [comment]
https://github.com/cheat-engine/cheat-engine/tree/master/Cheat%20Engine/ceserver
ceserver is relatively easy to build.

https://github.com/ds20211213/frida-ceserver
If you don't use the debugger (android arm64 etc) you can also use my project frida-ceserver.

**Comment by Cmpote** [comment]
> > > 最新版本提供以下输出。
> > > ```
> > > listening on port 52736
> > > &s=0x7fd5160284
> > > main=0x556e5c1854
> > > sizeof(off_t)=8
> > > sizeof(off64_t)=8
> > > sizeof(uintptr_t)=8
> > > sizeof(long)=8
> > > CEServer. Waiting for client connection
> > > IdentifierThread active
> > > socket=5
> > > successfully bound socket
> > > Listening success
> > > ```
> > 
> > 
> > 从master分支下载有这个问题。从标签下载没有这个问题，谢谢。问题解决了。
> 
> 兄弟~ ceserver 从哪里下载，自己编译的吗？



> > > 输出表明 ceserver 不是最新的。最新版本提供以下输出。
> > > ```
> > > listening on port 52736
> > > &s=0x7fd5160284
> > > main=0x556e5c1854
> > > sizeof(off_t)=8
> > > sizeof(off64_t)=8
> > > sizeof(uintptr_t)=8
> > > sizeof(long)=8
> > > CEServer. Waiting for client connection
> > > IdentifierThread active
> > > socket=5
> > > successfully bound socket
> > > Listening success
> > > ```
> > 
> > 
> > 从master分支下载有这个问题。从标签下载没有这个问题，谢谢。问题解决了。
> 
> 兄弟~ ceserver从哪里下载，自己编译的吗？

是的

**Comment by Cmpote** [comment]
> https://github.com/cheat-engine/cheat-engine/tree/master/Cheat%20Engine/ceserver ceserver is relatively easy to build.
> 
> https://github.com/ds20211213/frida-ceserver If you don't use the debugger (android arm64 etc) you can also use my project frida-ceserver.

ok, thanks for the recommendation
