### ISSUE TITLE
can we get a better date format in the update message?

### ISSUE THREAD

**Issue by divinity76** [cheat-engine/cheat-engine#2057]
can we get a better date format? maybe the ISO8601/RFC3339 `2022-01-18`, or the cookie format (rfc2109) `18-Jan-2022`

![image](https://user-images.githubusercontent.com/1874996/154515289-52377ecf-0672-4177-b396-07cc810c9d27.png)

**Comment by divinity76** [comment]
>No, only little girls have an issue with that

how does {middle-numer}/{least-significant-number}/{most-significant-number} make any kind of sense? why would anyone use that format willingly? it seems specifically designed to cause confusion..

>with a packet editor

uhm that's going to be difficult, you'll either need to do MITM-attack with a self-signed certificate, or make a packet editor that hooks the tls decryption output :o

**Comment by Symbai** [comment]
> now you don't know if 01-02-2022 mean 2nd january or 1st february without context..

Its written in English, the program itself is English (there is your context). You can expect it's US time format. Month first, then day, then year. If that confuses you, you should stay away from technology and ride a pony instead.

**Comment by Frouk3** [comment]
> > Its written in English, the program itself is English (there is your context).
> 
> English has been used in Britain since ~500AD, [they use a day–month–year format](https://en.wikipedia.org/wiki/Calendar_date#Gregorian,_day%E2%80%93month%E2%80%93year_(DMY)) in Britain.. and Christopher Columbus first visited America in 1492AD.. meaning people spoke English for ~1000 years in a place they're using a sensible date format, prior to anyone speaking English in America, where they're presently using a nonsensical date format.
> 
> but why is America using a nonsensical date format? can anyone explain the logic behind MM/DD/YYYY?

and? nobody don't complain about this

**Comment by divinity76** [comment]
https://www.reddit.com/r/cheatengine/comments/suos5s/cheat_engine_is_up_to_date/
