### ISSUE TITLE
add a command line to directly attack to a process by id

### ISSUE THREAD

**Issue by mrexodia** [cheat-engine/cheat-engine#207]
hey, I'm interested in a very simple command line like `CheatEngine.exe -attach 1234` that will attempt to select the process with pid 1234 on startup. This can be used to integrate with x64dbg (or any other kind of tools) and just saves the tedious extra step when you want to open the process you are currently debugging with Cheat Engine.

Unfortunately my Delphi is really awful so I have no clue where to start.

**Comment by cheat-engine** [comment]
you can create a one time run lua file in the autorun folder which deletes itself after execution

**Comment by mrexodia** [comment]
Thanks a lot for the guidance! I wrote a simple tool called [CEAutoAttach](https://github.com/mrexodia/CEAutoAttach) that automatically does this.

![x64dbg](https://i.imgur.com/bJydNYU.gif)
