### ISSUE TITLE
Typo in the LUA binding for CreateMultiReadExclusiveWriteSynchronizer

### ISSUE THREAD

**Issue by juntalis** [cheat-engine/cheat-engine#208]
There's a trailing space in the global declaration on [this line](https://github.com/cheat-engine/cheat-engine/blob/master/Cheat%20Engine/LuaThread.pas#L497), so the only way to access this function currently is:

```lua
_G["createMultiReadExclusiveWriteSynchronizer "](...)
```

**Comment by cheat-engine** [comment]
should be fixed now
