### ISSUE TITLE
Some possible DBVM detections

### ISSUE THREAD

**Issue by Compiled-Code** [cheat-engine/cheat-engine#2089]
Incorrect TSC virtualization (not accounting vmexit times)
Incorrect APERF virtualization (this only timing execution time only but also need accounting timing exit times with aperf & accounting it)
Incorrect trap flag handling (https://howtohypervise.blogspot.com/2019/01/a-common-missight-in-most-hypervisors.html?m=1)
Incorrect injected exception (DBVM seem catch GP & UD for inject on vmexits)
Not cloning IDT/GDT/CR3 (DBVM seem do it)
Incorrect instruction emulation
Finding anonoly at control registers you editing for hypervisor that no match baremetal that not under hypervisor (https://secret.club/2020/04/13/how-anti-cheats-detect-system-emulation.html#crn-mask--vmx-availability)
Cpuid leafs & synthetic msrs ( https://secret.club/2020/04/13/how-anti-cheats-detect-system-emulation.html#cpuid-leaf-comparisons )( https://secret.club/2020/04/13/how-anti-cheats-detect-system-emulation.html#synthetic-msrs )

Just some basic ones
If u reading Intel manual you can finding much more

**Comment by Compiled-Code** [comment]
Some others: (not sure if CE virtualize LBR)

https://secret.club/2020/04/13/how-anti-cheats-detect-system-emulation.html#lbr-virtualization
https://secret.club/2020/04/13/how-anti-cheats-detect-system-emulation.html#lbr-virtualization
https://secret.club/2020/04/13/how-anti-cheats-detect-system-emulation.html#crn-access-exiting
https://secret.club/2020/04/13/how-anti-cheats-detect-system-emulation.html#wow64-descriptor-table (must setting respective 32 or 64 bit value)

**Comment by Compiled-Code** [comment]
Note sure if CE evade these
When doing my hypervisor am read these articles for assuring it written properly
Only thing that am forget was slight edit at trap flag (should check if branch)
Intel manual very good tool :)

**Comment by Compiled-Code** [comment]
http://standa-note.blogspot.com/2021/12/para-pass-through-hypervisors-and-their.html - very good read would never thinking this myself
If you can finding CE physical memory reliably can corrupting it

**Comment by Chordp** [comment]
[mash_hypervisor](https://github.com/huoji120/mash_hypervisor)
Share a cr3, host and guest

**Comment by DarkAsm** [comment]
@cheat-engine

**Comment by Compiled-Code** [comment]
> [mash_hypervisor](https://github.com/huoji120/mash_hypervisor) Share a cr3, host and guest

DBVM does not sharing same cr3 as guest.
