### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by ByDaviid19** [cheat-engine/cheat-engine#2101]
when i try to download the software, it says the softare its a virus, please help

**Comment by Kobra299** [comment]
sounds like you are having a false positive from your antivirus

**Comment by fade2gray** [comment]
@ByDaviid19 see #2099

**Comment by woctezuma** [comment]
https://www.virustotal.com/gui/file/6d0e14d66da69c163f824f8fa7d87de3eea41cdbd48c0973de296cf6d2d0fed3

**Comment by zhaoqin102** [comment]
it's a virus, not adware.  be careful

**Comment by ve3** [comment]
I see that all versions of Cheat Engine I have has been detected as virus, malware, trojan, riskware, etc on VirusTotal website. Not just adware.
Does the file from CE Patreon still contain virus?

**Comment by Dijosto** [comment]
> I see that all versions of Cheat Engine I have has been detected as virus, malware, trojan, riskware, etc on VirusTotal website. Not just adware. Does the file from CE Patreon still contain virus?

It's not lol
