### ISSUE TITLE
win10 build DBKKernel release error

### ISSUE THREAD

**Issue by HA-JD** [cheat-engine/cheat-engine#2106]
![image](https://user-images.githubusercontent.com/47666701/159136879-2bae19ba-672a-4c6d-9ba1-484175a21ce7.png)

**Comment by HA-JD** [comment]
DBKKernel.vcxproj -> C:\Users\HAJD\Desktop\Cheat Engine\bin\DBK64.sys
1>SIGNTASK : SignTool error : No file digest algorithm specified. Please specify the digest algorithm with the /fd flag. Using /fd SHA256 is recommended and more secure than SHA1. Calling signtool with /fd sha1 is equivalent to the previous behavior. In order to select the hash algorithm used in the signing certificate's signature, use the /fd certHash option.

**Comment by HA-JD** [comment]
![image](https://user-images.githubusercontent.com/47666701/159137838-a4acc62c-d75b-42e9-b5d9-b31a5fca9db0.png)

**Comment by cheat-engine** [comment]
the build was a success , it's just a post build issue
  You can remove the post build command

**Comment by HA-JD** [comment]
I don't know how to delete it

**Comment by cheat-engine** [comment]
project property pages build events

**Comment by HA-JD** [comment]
But it's still that mistake.So I won't do it.excuse me
