### ISSUE TITLE
Binding hotkeys to write values does not work properly

### ISSUE THREAD

**Issue by fangshun2004** [cheat-engine/cheat-engine#2119]
Bind hotkey Write value will only work once After pressing the hotkey again, the value will not be written.
Moreover, the "Restore to original on release" option in the hotkey configuration cannot save the configuration

**Comment by cheat-engine** [comment]
fixed now

**Comment by fangshun2004** [comment]
Binding hotkeys but not using the "Restore to original on release" function is just a separate write to the value work is still triggered only once
