### ISSUE TITLE
6.7 - Deactivate Children Group Option Bug

### ISSUE THREAD

**Issue by atom0s** [cheat-engine/cheat-engine#212]
Child scripts in a group fail to deactivate when you use the 'Deactivating this entry deactivates its children' if they are attempting to use a user defined symbol in the main parent script that was unregistered in the parents [DISABLE] block.

For example, I have a script that injects a cave at a given memory location, registers a few symbols that are part of the allocated cave that are toggled in child scripts of this parent script. The parent script looks something like this:

```asm
[ENABLE]
aobscanmodule(customItemFilter,...)
registersymbol(customItemFilter)
alloc(newmem,1024)
registersymbol(customFilters)
label(customFilters)
label(rethere)
label(filterout)
label(original)

newmem:
    // Code removed for bug report..
original:
    // Code removed for bug report..
    jmp rethere
filterout:
    // Item should be filtered..
    pop edi
    pop esi
    mov al, 01
    pop ebx
    ret 0004
customFilters:
    db 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

customItemFilter:
    jmp newmem
    nop
rethere:

[DISABLE]
customItemFilter:
    // Code removed for bug report..
dealloc(newmem)
unregistersymbol(customItemFilter)
unregistersymbol(customFilters)
```

Child scripts are simple toggles of customFilters object like so:
```asm
[ENABLE]
customFilters+3:
    db 1

[DISABLE]
customFilters+3:
    db 0
```
When the parent is deactivated, the symbol customFilters is destroyed and the children fail to deactivate.

**Comment by mgrinzPlayer** [comment]
Children memrecs are always deactivated after main script. There are two options:

- remove "unregistersymbol(customFilters)" line from parent memrec and create new children memrec, place it as last, name it 'unregistering symbol', with this script:
```
[ENABLE]
[DISABLE]
unregistersymbol(customFilters)
```
- do not use 'Deactivating this entry deactivates its children', paste this script in disable part of parent memrec:
```
//disable children first
{$Lua}
if syntaxcheck then return end

for i=memrec.Count-1,0,-1 do
  memrec[i].Active = false -- deactivate children
end
{$Asm}
```

**Comment by atom0s** [comment]
Perhaps adding an option to the Group Header list to deactivate children first when the 'Deactivating this entry deactivates its children' could be considered. I'd rather not mix Lua/ASM together for what I am working on.
