### ISSUE TITLE
April Fools Joke

### ISSUE THREAD

**Issue by xCENTx** [cheat-engine/cheat-engine#2125]
At least include an option to save the table before closing. This shit popped up for me while during my Elden Ring debug session and I instinctively closed the window because popups are just weird in 2022 joke or not. Lost all my work from the last 6-7 hours.

Happy april fools i guess

**Comment by xCENTx** [comment]
I was under the impression my PC was infected with some type of malware even with my better judgement on not downloading sketchy shit on the internet. So i just closed cheat engine and shut down my pc instinctively. 

Comparing that to shooting yourself in the leg is a bit excessive my guy. Regardless i became the solution to my own problem by forking the repository and patching my own branch without all the useless junk on special dates

**Comment by TempAccountNull** [comment]
> > Lost all my work from the last 6-7 hours.
> 
> If you close CE window you'll loose all your work. If you shoot yourself in your leg then it hurts. You could have also just closed the popup window, which doesn't close CE.
> 
> Here is an auto save plugin you can use: https://forum.cheatengine.org/viewtopic.php?p=5468951#5468951

Actually believe it or not, if a user clicks on the 'x' button on the 'ecoins window'.. Cheat engine will automatically close. Not sure that was intentional, but even with the latest source? This is what happens.

**Comment by Mordinel** [comment]
Hey, how do you fully disable this retarded easter egg so that it never occurs again?
