### ISSUE TITLE
6.7 - Add Address Manually Pointer Bug

### ISSUE THREAD

**Issue by atom0s** [cheat-engine/cheat-engine#214]
If you use any type of math within a pointer offset, the add address window will display the end result correctly. However, when you click OK and add it to the cheat table, the end result is invalid.

For example:

  - Click 'Add Address Manually'
  - Check 'Pointer' checkbox.
  - In the bottom enter a valid address or symbol.
  - In the first offset, use a valid offset and add onto it such as: 244+120
  - At the top, notice that the result address displayed is correct.
  - Click 'OK' to add this address to the table.

At this point, the address added in the table is incorrect now.

Example screenshot of whats happening:
http://i.imgur.com/xYaHkqb.png

The add address window displays the correct address at the top. The below two addresses are what's in the cheat table. 
The first one is the error, the second is directly pointing to 244+120 as 364 and shows the correct address. 

Edit - One thing to note, if you use hex entries by force ie, leading with 0x it works fine such as:
0x244+0x120

So it appears to be an issue parsing math based offsets that are not specifically starting with 0x to denote hex.

**Comment by cheat-engine** [comment]
that's already fixed

**Comment by wlix32hacker** [comment]
so.. we can close it?
