### ISSUE TITLE
No address showing on CheatEngine

### ISSUE THREAD

**Issue by WelcometoGitHubLetsbegintheadventure** [cheat-engine/cheat-engine#2158]
No addresses show when I type in my value status on CheatEngine 7.4. I am on a macOS system and I am using the free trial. 

Please feel free to give me solutions

**Comment by WelcometoGitHubLetsbegintheadventure** [comment]
Even trying different value types still won't give me an address.

**Comment by cheat-engine** [comment]
try 7.3 . 7.4 doesn't work on m1's

**Comment by WelcometoGitHubLetsbegintheadventure** [comment]
How do I download the 7.3 ersion? I am only able to find the 7.4 version.

**Comment by fade2gray** [comment]
https://github.com/cheat-engine/cheat-engine/releases/download/7.3/CheatEngine73.exe

**Comment by WelcometoGitHubLetsbegintheadventure** [comment]
I am on a macOS but I figured out a way to download it. Thanks.
