### ISSUE TITLE
Issue with double clicking in the gui.

### ISSUE THREAD

**Issue by handyTheLoser** [cheat-engine/cheat-engine#2162]
I don't know when it started but I have a Logitech g502 mouse where I use one of the buttons to double click. One day, cheat engine stopped registering the double click. I was on a lower version of cheat engine before today but decided to update today to see if that would fix the issue but I'm still having the same issue. I reset the settings and that didn't work. I'm not sure what could be going on. Like I said, it worked in the past but one day just randomly stopped registering.

**Comment by cheat-engine** [comment]
is the tool that converts the mousebuttonpress into a doubleclick running as admin?
If not, windows has pushed through some updates that prevent usermode applications from clicking inside admin running programs

**Comment by handyTheLoser** [comment]
Oh wow, I didn't know that. I just tried it and it worked. Thanks!
