### ISSUE TITLE
Bloatware

### ISSUE THREAD

**Issue by amezarashi97** [cheat-engine/cheat-engine#217]
<!> do not download this sh*t. <!>

**Comment by amezarashi97** [comment]
https://www.virustotal.com/en/file/a5fb2ca3db9fed8b369f16ca60dede4a1b08a109f2dbeea37efce5580995e8d4/analysis/1500213650/

**Comment by amezarashi97** [comment]
Virus!

**Comment by FreeER** [comment]
Duplicate (presumably) of https://github.com/cheat-engine/cheat-engine/issues/176 and https://github.com/cheat-engine/cheat-engine/issues/209

If you aren't even going to pay attention to the issues why bother creating yet another one? Go play with the other programs like artmoney and ollydbg or (linux) scanmem / PINCE if you don't like CE.

**Comment by amezarashi97** [comment]
http://i.imgur.com/kPw1OS4.png

**Comment by korcankaraokcu** [comment]
@amezarashi97 What did you expect from a software that's used to inject code, manipulate memory etc, y'know, the same stuff a virus can do. It's pretty normal for CE to get detected as a false-positive.

@FreeER I agree with you, but don't you think it's a bit rude to use verb "play" with ollydbg, scanmem or PINCE, especially ollydbg. They are not toys y'know, but legit tools.

**Comment by FreeER** [comment]
@amezarashi97  https://imgur.com/a/fd1l2 what's your point?

@korcankaraokcu I assumed it's someone who doesn't know what they are doing if they're complaining about CE without looking at the existing information and so the best they can do is "play" with these tools, not properly use them (which requires a certain level of understanding) :)

**Comment by Fironet** [comment]
Fwiw most of those detects appear to be due to the variety of installer adware that comes bundled with the program. Taking a look at the standalone archive that's available [the results](https://virustotal.com/en/file/a5d087a83a20c68e66db1130b94af9da5427a79e184a696bbd9bac499ba8151d/analysis/1500411018/) are a lot more reasonable.

**Comment by VasiliPupkin256** [comment]
@FreeER nothing is told about bundled bloatware in installer on github release page. Are you a contributor to an open source project or a partner receiving a share from advertising? Stop defending this shit. Binaries published on github shall be free from any third party malware.
