### ISSUE TITLE
X64 .net game doesn't work

### ISSUE THREAD

**Issue by Y-A-K-E** [cheat-engine/cheat-engine#2172]
win11+ CE7.4 

---

Click [. Net] -- > [. Net info] CE no response
Or show an error message "No .NET info found"

![20220430195117](https://user-images.githubusercontent.com/6988291/166104402-738041dd-30e3-4350-b981-dbc56060bdd3.jpg)

### working:
[32-bit] terraria 
[32-bit] rogue heroes: ruins of tasos
[32-bit] Axiom Verge

### not working:
[64-bit]  tModLoader (This community-made mod requires that you own Terraria.)
[64-bit] Stardew Valley  (win7 working)
[64-bit] CryoFall

**Comment by cheat-engine** [comment]
have you tried installing the older .net runtimes ? 

e.g. : https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows

**Comment by Y-A-K-E** [comment]
> have you tried installing the older .net runtimes ?
> 
> e.g. : https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows


---


Yes, I have installed it.


![2022-05-01 122118](https://user-images.githubusercontent.com/6988291/166132182-3f783c3b-16b7-412f-9ab0-b93d9806d17a.jpg)


---


### win10(vm) + ce 7.4  

#### not installed .net 3.5
**ce is working**

![2022-05-01 124200](https://user-images.githubusercontent.com/6988291/166132766-414d7202-7d44-4beb-a49f-7db070d159a2.jpg)

#### have installed
**ce is working**

![屏幕截图 2022-05-01 125425](https://user-images.githubusercontent.com/6988291/166132869-c0696350-d71d-4698-bb75-9d3adeeca1a5.jpg)




---

### My laptop (win11)

#### not installed .net 3.5

**ce is working**


![123456789](https://user-images.githubusercontent.com/6988291/166132936-8ed5cb35-8178-41e9-98f4-fbb84e15c280.png)



#### have installed
**ce is working**

![22222](https://user-images.githubusercontent.com/6988291/166133383-5145979c-4709-4a53-b1ca-0e03fe05dc7c.png)

**Comment by cheat-engine** [comment]
So you're saying that on your windows 11 laptop it is working, but on another system/vm it isn't ?

**Comment by Y-A-K-E** [comment]
I found something.



my laptop (win11)

### not install dotnet-sdk-6.0.202-win-x64

[dotnet-sdk-6.0.202-win-x64](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.202-windows-x64-installer)

[Stardew Valley](https://store.steampowered.com/app/413150) :   CE **working**
[CryoFall](https://store.steampowered.com/app/829590)  :  CE **not working**


---
### install dotnet-sdk-6.0.202-win-x64

Stardew Valley :  CE **not working**
CryoFall  :  CE **working**


---

### uninstall dotnet-sdk-6.0.202-win-x64


Stardew Valley :   CE **working**
CryoFall  :  CE **not working**


---
### reinstall dotnet-sdk-6.0.202-win-x64

Stardew Valley :   CE **not working**
CryoFall  :  CE **working**

**Comment by Y-A-K-E** [comment]
game download:

https://mega.nz/folder/bVkSVCDQ#vMVpPjsNBqjGOOVydzsWww

**Comment by Lewdcifer** [comment]
yea it is weird

**Comment by TheKvist** [comment]
I've had the exact same problem on my Windows 11 machine, also with Stardew Valley, after it had worked without problems on my Windows 10 machine. In my case, I found in the Windows software uninstaller that I had the ".NET Desktop Runtime 3.1.2" installed. Upon uninstalling it (and also the 6.0.6 Runtime I installed trying to fix the problem), symbols worked again with Stardew Valley and CE.

**Comment by Y-A-K-E** [comment]
### I have found a way. 

game:  tModLoader  (This community-made mod requires that you own **Terraria**.)

1.install .NET SDK 6.0.202
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.202-windows-x64-installer

3.Test .net Version
`dotnet.exe --info`

```
C:\Users\xjw11>dotnet.exe --info
.NET SDK (反映任何 global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.202\
```


2.Use .bat launch game
```
@echo off
cd %~dp0
dotnet tModLoader.dll
```

-----


game: Stardew Valley

1,install .NET SDK 6.0.202

2,Copy all the files in directory `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.6` and paste them into the game directory (overwrite is allowed)
