### ISSUE TITLE
6.7 Two monoscript.lua bugs

### ISSUE THREAD

**Issue by Schnitzelmaker** [cheat-engine/cheat-engine#218]
Bug 1: monoAA_GETMONOSTRUCT should exclude static fields.
When using GETMONOSTRUCT in aa it mixes static and non-static fields which sometimes result the struct contains the static field as offset instead of the non-static.

https://github.com/cheat-engine/cheat-engine/blob/master/Cheat%20Engine/bin/autorun/monoscript.lua#L2835 is required to change to:
```
for i=1, #fields do
  if fields[i].offset~=0 not fields[i].isStatic then
    offsets[fields[i].offset]=fields[i].name
  end
end
```

Bug 2: mono_findMethodByDesc only supports UnityEngine assembly
The function mono_findMethodByDesc uses harcoded 'UnityEngine' string instead of provided assembly name

https://github.com/cheat-engine/cheat-engine/blob/master/Cheat%20Engine/bin/autorun/monoscript.lua#L1027 required to change to:

```
if imagename == assemblyname then
        return mono_class_findMethodByDesc(image, methoddesc)
end
```

**Comment by cheat-engine** [comment]
should be fixed

**Comment by Schnitzelmaker** [comment]
Totally forgot not an bug, but a little bit annoying. There is an uncomment `print("Format 2")`.
https://github.com/cheat-engine/cheat-engine/blob/master/Cheat%20Engine/bin/autorun/monoscript.lua#L2794

Also missed the if check in the mono_class_findMethodByDesc because its running in a loop.
`if imagename == assemblyname then`
https://github.com/cheat-engine/cheat-engine/blob/master/Cheat%20Engine/bin/autorun/monoscript.lua#L1027
