### ISSUE TITLE
7.4 won't open

### ISSUE THREAD

**Issue by deadsk1n** [cheat-engine/cheat-engine#2183]
7.2 worked fine and I wanted to download 7.4, it installed successfully and shows up on taskmgr but ce window doesn't open.
I've uninstalled vanguard and disabled defender, restarted pc and it still doesn't open, idk what else to do :/

**Comment by fade2gray** [comment]
Look at some possible solutions here #2099.

If you find a solution that worked for you, please leave a comment saying what worked.

**Comment by fade2gray** [comment]
You mentioned that you uninstalled vanguard.
You could try opening a Windows command prompt and enter `Driverquery /fo list /v | findstr vanguard`.
If you see anything listed, it could mean that vanguard wasn't fully removed.
I imagine that uninstalling vanguard may need the same procedure as removing badlion, after uninstalling you MUST use Windows RESTART option, NOT shutdown followed by reboot.

**Comment by deadsk1n** [comment]
Thanks for the reply, ive tried most if not all of the solutions from #1310 and your #2099 guide. I checked driverquery after restarting and there weren't any traces of vanguard.

**Comment by deadsk1n** [comment]
uhh so I haven't changed anything since yesterday and it started working?? I don't understand xD
