### ISSUE TITLE
Starting a trace on a breakpoint with previously set condition breaks the condition

### ISSUE THREAD

**Issue by MerovingianByte** [cheat-engine/cheat-engine#219]
So if I have a breakpoint on instruction X with a condition, say "ESP == 0x0018e8f4". If I right-click X and click on "Break and Trace instructions", the trace won't work, because for the trace to work you can't have a previously set breakpoint on the starting instruction. Ok but that's not the problem yet. If I then close the trace window, I will find that my previously set breakpoint condition won't work anymore. It will be as if the condition wasn't there anymore. I need to remove the BP and the condition, then add the BP and condition back again to fix.

**Comment by MerovingianByte** [comment]
I was wrong about this. What happens it that if you have a breakpoint with a condition, you turn that breakpoint off and then on again, the condition won't work anymore. You will have to set the condition again. Not a bug, it's just that the condition you set before still appears on the textbox, but you need to click OK to activate it again.

**Comment by 7126** [comment]
I don't know how to use this app
