### ISSUE TITLE
Can't compile Cheat Enginer - addressparser.pas(126,111) Error: No default property available

### ISSUE THREAD

**Issue by Frisk0201** [cheat-engine/cheat-engine#2197]
my lazarus version
![image](https://user-images.githubusercontent.com/45967780/169976661-efd0e620-7a9d-4a79-a041-4a819411e8ae.png)

And my system is win11 64bit. 
Whether i install "cross-x86_64-win64" addon or not, it dosen't work.

I also tried to install 64bit lazarus, it would error like Issue#1748

**Comment by Frisk0201** [comment]
here is error message:
`addressparser.pas(126,111) Error: No default property available`

and the code:
`values[length(values)-1]:=pptruint(@c^.{$ifdef cpu64}FltSave.XmmRegisters[xregnr]{$else}ext.XMMRegisters[xregnr]{$endif})^;`

**Comment by fade2gray** [comment]
@cheat-engine I'm seeing the same issue

**Comment by IBinary6** [comment]
same issue ! compile 64 ok,but not 32!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by cheat-engine** [comment]
> the recommended Lazarus version is [2.0.10](https://github.com/cheat-engine/cheat-engine#build-instructions).
it's now 2.2.2

**Comment by fade2gray** [comment]
Fair enough, just that the links in the build instructions still point to 2.0.10.

**Comment by Frisk0201** [comment]
> > the recommended Lazarus version is [2.0.10](https://github.com/cheat-engine/cheat-engine#build-instructions).
> 
> it's now 2.2.2

It still can't compile even i installed lastest lazarus

**Comment by avboy1337** [comment]
the same error displayed , plz have a change if possible , plz plz

**Comment by Frisk0201** [comment]
> the same error displayed , plz have a change if possible , plz plz

![image](https://user-images.githubusercontent.com/45967780/173242550-6c51bce5-152a-4de2-ab85-82a7174b6995.png)
check compile version here.select the true one.
