### ISSUE TITLE
[Request] Support for other opcode maps.

### ISSUE THREAD

**Issue by SysVR** [cheat-engine/cheat-engine#2212]
Currently the cheat engine only supports the x86_64 opcode, but
We would like to be able to load other opcode maps.

The opcode map should be plain text, with
Byte array; opcode.

Example
x86_64.comf (Filename. Cheatengine Opcode Map File.)
6A xx;push xx

**Comment by cheat-engine** [comment]
you can register binutils for the specific cpu mode

**Comment by SysVR** [comment]
thank you.
