### ISSUE TITLE
The lua script could not get the symbolic address

### ISSUE THREAD

**Issue by fangshun2004** [cheat-engine/cheat-engine#2220]
For example in the following code code

```
[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat
{$lua}
autoAssemble([[
    aobscanmodule(itemadd,FF8_EN.exe,0B 0C 0D 0E 0F 02 10)
    registerSymbol(itemadd)]])
local StartAddr=getAddress("itemadd")+0x16
print("StartAddr is",StartAddr)
{$asm}
[DISABLE]
//code from here till the end of the code will be used to disable the cheat
```

Will be prompted by the "Lua error in the sript at line 4: Failure determining what itemadd means"

The script works correctly in the "ae607452d00ee1e4a68ad77d1c0eafe6fa05e182" compilation

**Comment by cheat-engine** [comment]
I can't reproduce this

**Comment by cheat-engine** [comment]
I can't reproduce it with the given script on the tutorial. It returns a proper address.  Are you sure you have the tutorial open when editing the script ?

try this aa script instead:
```
[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat
{$lua}
if syntaxcheck then return end
local r,r2=autoAssemble([[
    aobscanmodule(itemadd,Tutorial-x86_64.exe,29 83 F8 07 00 00)
    registerSymbol(itemadd)]])
local StartAddr=getAddress("itemadd")+0x16

if not r then
  print(r2)
else
  print("ok:")
  print(StartAddr)
end

{$asm}
[DISABLE]
```

**Comment by cheat-engine** [comment]
Are you running CE using the lazarus play button or manually by running the .exe ?
Is there a difference?  E.g if you don't launch lazarus with admin privileges then CE also won't run with admin rights.  And perhaps some other security on your system steps in and blocks memory reading then ?

**Comment by cheat-engine** [comment]
move `local StartAddr=getAddress("itemadd")+0x16` to the `else` part

**Comment by kitty8904** [comment]
https://github.com/cheat-engine/cheat-engine/issues/2210

Cheat engine latest source has auto assembler error Address value cannot be changed(lazarus 2.2.2 version)

**Comment by cheat-engine** [comment]
that's a different issue (globalalloc)

**Comment by cheat-engine** [comment]
should work better now
