### ISSUE TITLE
ce7.4 Built-in bundled software "rav vpn"

### ISSUE THREAD

**Issue by bakasine** [cheat-engine/cheat-engine#2221]
wtf i cant uninstall it????

**Comment by MineCreeper86** [comment]
the same problem, i installed CE and found out that an application called rav endpoint protection was installed

**Comment by Apocaly-pse** [comment]
i have a same situation.. and i uninstall **them** from 'microsoft apps and functions'.

**Comment by zhaoqin102** [comment]
the same problem,  why

**Comment by itsHenry35** [comment]
the save problem, try to use geek uninstaler to force remove it if the uninstaller of this *** application doesn't work

**Comment by Arkevorkhat1** [comment]
It was bundled by the maintainer because he decided he wasn't making enough money off of his FOSS.

**Comment by fade2gray** [comment]
@Arkevorkhat1 https://github.com/cheat-engine/cheat-engine/issues/2621#issuecomment-1606053810
