### ISSUE TITLE
[Request] How to change StructureFrm.MainStruct from lua?

### ISSUE THREAD

**Issue by ImmortalPony** [cheat-engine/cheat-engine#2222]
Thank you for great tool. I have an issue with StructureFrm lua-class.

Setting `StructureFrm.MainStruct` changes the structure name but doesn't update `tvStructureView`, nor calls `UpdateCurrentStructOptions`, nor calls `RefreshStructureList`, nor calls `InitializeFirstNode`.

It would be great if the user of StructureFrm could change MainStruct simply assigning new value.

Update:
I found a workaround:
```
StructureFrm.MainStruct = nil -- indirectly calls `InitializeFirstNode` and updates `tvStructureView`
StructureFrm.MainStruct = desired
StructureFrm.structChange() -- indirectly calls other updates
```

**Comment by cheat-engine** [comment]
structChange yes
