### ISSUE TITLE
[video]dbvm level flag check 

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#2235]
https://youtu.be/V2YZWvisEs0

globalalloc(checkcode,4096)
globalalloc(value,4096)
label(zfcheck)
checkcode:
mov rax,1
cmp rax,1
je zfcheck
mov [value],0
jmp checkcode
zfcheck:
mov [value],1
jmp checkcode

test source - fix setcontext not being called after handling a dbvmlevel breakpoint

dbvm level flag change error
dbvm level bp no check -> flag is not modified
dbvm level bp check -> flag is modified

**Comment by cheat-engine** [comment]
setcontext is called just fine, just that single stepping precedes changeregonbp, so changeregonbp is skipped

the only difference between the windows interface and dbvm, is that windows stops single stepping, and dbvm continues single stepping
