### ISSUE TITLE
'Operation did not complete successfully'

### ISSUE THREAD

**Issue by ActiveOak** [cheat-engine/cheat-engine#2253]
Every time is try to open and finish installing cheat engine is get hit with 'Operation did not complete successfully because the file contains a virus or potentially unwanted software' I've turned off my virus security

![Untitled](https://user-images.githubusercontent.com/108547712/176947644-af9e70f6-1444-437c-9319-586b6494d225.png)

**Comment by fade2gray** [comment]
See #2099 and #1954

**Comment by ActiveOak** [comment]
> See #2099 and #1954

Thanks, i managed to get it. it didnt save the changes
