### ISSUE TITLE
image index

### ISSUE THREAD

**Issue by Chassss** [cheat-engine/cheat-engine#2255]
i cant add the dll inject image index which should be as shown as this 
![image](https://user-images.githubusercontent.com/85374722/177018873-e4408dba-63ba-415d-aa50-4c7ba2e2a2fc.png)
but whenever you use that image index you get the paste image instead
![image](https://user-images.githubusercontent.com/85374722/177018889-99433198-b82f-44bf-95ad-2bd62006d200.png)
what would the image index of the dll inject picture on cheat engine 7.4 be

**Comment by cheat-engine** [comment]
The index is `getMemoryViewForm().InjectDLL1.ImageIndex`
