### ISSUE TITLE
Cancel dialog in memory viewer dump causes a jump to

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#226]
Select a byte in the middle of the hex view in memory viewer and press CTRL+G, press cancel. Enjoy how the hex view jumped to this address.

This bug was introduced lately. 
This bug does not happen in opcode view.

//edit: 
![ezgif com-optimize 1](https://user-images.githubusercontent.com/14368203/30039575-774bef4a-91d3-11e7-8c3a-7e984c7a3dee.gif)

**Comment by pinchyCZN** [comment]
Looks like this does affect the opcode view as well if you scroll the selected line out of view and cancel the dialog. sent a PR with fix

**Comment by Symbai** [comment]
Thanks, already thought this would remain unfixed. Closing then
