### ISSUE TITLE
Get a RSI from dbvm dbg

### ISSUE THREAD

**Issue by victor20010** [cheat-engine/cheat-engine#2265]
Hi,trying to get a RSI from dbvm dbg
im doing a breakpoint, its works fine but cant get logs
```

StartAddress =getAddress("PlayerAddress")
PA=dbk_getPhysicalAddress(StartAddress)
dbvm_traceonbp(PA, 2, StartAddress,{logStack=true})

print(dbvm_traceonbp_getstatus())
data=dbvm_traceonbp_retrievelog()
print("DATA",data)
print(dbvm_traceonbp_retrievelog())
```

and just get 

```
StartAddress =getAddress("PlayerAddress")
PA=dbk_getPhysicalAddress(StartAddress)
dbvm_traceonbp(PA, 2, StartAddress,{logStack=true})

print(dbvm_traceonbp_getstatus())
data=dbvm_traceonbp_retrievelog()
print("DATA",data)
print(dbvm_traceonbp_retrievelog())


1 0 2 
DATA  
 

print(dbvm_traceonbp_getstatus())
data=dbvm_traceonbp_retrievelog()
print("DATA",data)
print(dbvm_traceonbp_retrievelog())


1 0 2 
DATA  
 

print(dbvm_traceonbp_getstatus())
data=dbvm_traceonbp_retrievelog()
print("DATA",data)
print(dbvm_traceonbp_retrievelog())


3 2 2 
DATA  

```

im grabing the info from celua.txt

was trying to google it but didint se same questions, help pls =) 

https://i.zhyk.ru/images/2022/07/12/GdLGe.png

**Comment by cheat-engine** [comment]
you need to format the output yourself.  it's a table

tip: do a `return dbvm_traceonbp_retrievelog()` for a small view

**Comment by victor20010** [comment]
> you need to format the output yourself. it's a table
> 
> tip: do a `return dbvm_traceonbp_retrievelog()` for a small view

Ty för the answer DB , gonna try it at home 

return string.format(data)
Like i understud it's something like that.
There is a way to 
"Find out what addresses this code accesses" ? 
By Lua ? I was trying dbvm_watch_executes I'm on the right way ?))

**Comment by cheat-engine** [comment]
dbvm_watch_executes and use dbvm_watch_retrievelog(ID) to get the log

**Comment by cheat-engine** [comment]
it returns a table, not a string

**Comment by victor20010** [comment]
> 
had a 
return dbvm_watch_retrievelog(ID)
dbvm_watch_disable(ID)
so lua was getting error=) ty its works 

3:table
  [
     1 = table
     [
        FLAGS = 66050
        DR6 = 4294922224
        RBP = 249944205920
        RBX = 0
        RDX = 0
        DR2 = 0
        RDI = 0
        R15 = 1890386527552
        R12 = 249944207568
        DR0 = 0
     ...
     ]
  ]

but ther is no RSI or i need to formate self a table also?

**Comment by cheat-engine** [comment]
the RSI is in the `...` part
```
for i=1,#result do
  print(result[i].RSI)
end
```

**Comment by victor20010** [comment]
> the RSI is in the `...` part
> 
> ```
> for i=1,#result do
>   print(result[i].RSI)
> end
> ```

thanks you are the best of the best^^
