### ISSUE TITLE
Identifier not found: "FThreadHandle" in LuaHandler

### ISSUE THREAD

**Issue by tokotchd** [cheat-engine/cheat-engine#2267]
Following error while trying to follow build instructions
![image](https://user-images.githubusercontent.com/8561315/179257851-315a98e2-df69-4cbc-aa84-cd26bcbd022e.png)

Error is both with 32 bit and 64 Lazarus installs, building both respective native and cross-compiled projects/builds.

**Comment by flowerwOw0316** [comment]
me too  version 7.4.1 
![QQ截图20220715234511](https://user-images.githubusercontent.com/50901029/179259077-fd093717-982d-49f6-977e-7f9546ffa473.png)

**Comment by fade2gray** [comment]
Might be due to the Lazarus version you are using.

**Comment by flowerwOw0316** [comment]
I've solved it

**Comment by fade2gray** [comment]
It's nice to share solutions. ¯\\_(ツ)_/¯

**Comment by fade2gray** [comment]
Oh, you downloaded the zip, extracted it and tried to compile it, yes?

**Comment by flowerwOw0316** [comment]
> Oh, you downloaded the zip, extracted it and tried to compile it, yes?

yes I thought it was the same as the release

**Comment by fade2gray** [comment]
If you download the latest source.zip from the green CODE button, I think it will compile 64 bit using Lazarus 2.2.2, but errors out with 32 bit. The current release will compile both 32 & 64 bit using Lazarus 2.0.10.

**Comment by tokotchd** [comment]
Yep, I was in the same boat as @flowerwOw0316.  I tried to compile 7.4.1 (master) which didn't seem to work but latest release zip (7.4.0) works.
