### ISSUE TITLE
Mono injection error, DBVM or EAC???

### ISSUE THREAD

**Issue by victor20010** [cheat-engine/cheat-engine#2269]
Hi, i launched RUST and trying to inject MonoDataCollector64.dll but i get an error 
```
LaunchMonoDataCollector()
mono_OpenProcess(getOpenedProcessID())
mono_initialize()

Failure injecting the MonoDatacollector library:Force load module failed:Force load module failed:Unable to open file "KERNEL32.dll": Не удается найти указанный файл. 
Error:[string "LaunchMonoDataCollector()
..."]:2: attempt to call a nil value (global 'mono_OpenProcess')
Script Error

```
I get same error if i press "watch memmory allocation" or "Heaplist"
https://i.zhyk.ru/images/2022/07/16/G6NxU.png

Tryed also INJECT DLL

**Comment by cheat-engine** [comment]
If the game has EAC then normal dll injection won't work

**Comment by victor20010** [comment]
> If the game has EAC then normal dll injection won't work

ty for fast answer , tryed on non protected game and works
