### ISSUE TITLE
AA - Symbol is not registered

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#227]
Try this:

```
alloc(newmem,2048)
registersymbol(blablabla)
label(blablabla)
```

now try this:

```
alloc(newmem,2048)registersymbol(blablabla)
label(blablabla)
```

Both injects succesfully. But on second the symbol is not registered.

**Comment by mgrinzPlayer** [comment]
use {$STRICT}
http://forum.cheatengine.org/viewtopic.php?t=594776

**Comment by Symbai** [comment]
Nope

![ezgif com-optimize](https://user-images.githubusercontent.com/14368203/30039532-aa2ba79e-91d2-11e7-9af4-a3c6b413827d.gif)

**Comment by mgrinzPlayer** [comment]
I see, autoassembler module just ignores the rest. So, always use only one AA command per line
```Pascal
          //memory alloc
          if uppercase(copy(currentline,1,6))='ALLOC(' then
          begin
            //syntax: alloc(x,size)    x=variable name size=bytes
            //or
            //syntax: alloc(x,size,prefered region)    x=variable name size=bytes
            //allocate memory
            a:=pos('(',currentline);
            b:=pos(',',currentline);
            c:=PosEx(',',currentline,b+1);
            d:=pos(')',currentline);
```

**Comment by Symbai** [comment]
Shouldn't CE let the user know about that? I mean either prompt a script syntax error if there is something CE cannot handle or not ignore text after last bracket? 

I'm asking because this is what I would expect as CE does this in any other case.
