### ISSUE TITLE
animated title text/caption

### ISSUE THREAD

**Issue by pancibuntus** [cheat-engine/cheat-engine#2271]
is there any way to make CE title changes everytime ??

**Comment by pancibuntus** [comment]
https://streamable.com/9ilmic
like this

**Comment by pancibuntus** [comment]
thanks,, but how to change the button and the others string to random title ?? it only changes the cheat engine title

**Comment by pancibuntus** [comment]
how do I change this text to random numbers/text [https://ibb.co/51H40dM](url)

**Comment by fade2gray** [comment]
See #1068.

**Comment by pancibuntus** [comment]
> See #1068.

yep I tried that too but I didnt make random string like the code above.. how do I edit that code to be randomize string/text title ??

**Comment by pancibuntus** [comment]
> ```lua
> function renameComponents(c)
>     local i
>     if c.Component then
>         for i=0,c.ComponentCount-1 do
>             renameComponents(c.Component[i])
>         end
>     end
> 
>     if c.Caption then
>         c.Caption='WTF'
>     end
> end
> 
> for i=0,getFormCount()-1 do
>     local form = getForm(i)
>     for j=0,form.ControlCount-1 do
>         renameComponents(form)
>     end
>     -- form.Caption='Bla'
>     renamer=createTimer()
>     renamer.Interval=100
>     renamer.OnTimer=function(t)
>         MainForm.Caption=math.ceil(math.random()*100000)
>     end
> end
> 
> registerFormAddNotification(function(f)
>     f.registerCreateCallback(function(frm)
>         renameComponents(f)
>     end)
> end)
> ```

only works for title,, but still giving fixed string "WTF" for others 
https://ibb.co/M7z3F5F

**Comment by fade2gray** [comment]
In the image you provided, `56ij` is just a static string, the same as `WTF`.
