### ISSUE TITLE
loadpdb will crash ce

### ISSUE THREAD

**Issue by avboy1337** [cheat-engine/cheat-engine#2272]
when loading pdb file , ce will crash.

https://user-images.githubusercontent.com/5463104/179726388-90caea3f-0db3-4231-a061-89736dd2256a.mp4

**Comment by cheat-engine** [comment]
try some different versions of dbghlp dll in the win64 folder until you get one that does work for your situation

**Comment by avboy1337** [comment]
> try some different versions of dbghlp dll in the win64 folder until you get one that does work for your situation. Try the one used for that build

OK, Thanks a Lot!

**Comment by avboy1337** [comment]
> try some different versions of dbghlp dll in the win64 folder until you get one that does work for your situation. Try the one used for that build

···
0:019> g
(1a00.1714): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
*** WARNING: Unable to verify timestamp for C:\Users\Administrator\Desktop\bin\cheatengine-x86_64-SSE4-AVX2.exe
cheatengine_x86_64_SSE4_AVX2+0x8eec39:
00000000`00ceec39 027dff          add     bh,byte ptr [rbp-1] ss:00000000`145da81f=00
0:018> r
rax=0000000000ceec39 rbx=00000000145daa28 rcx=092e526dc1b10000
rdx=0000000000ceec38 rsi=0000000000000678 rdi=00007ffb73050000
rip=0000000000ceec39 rsp=00000000145da6a0 rbp=00000000145da820
 r8=000000000ed29120  r9=0000000000000001 r10=0000000000000003
r11=00000000145da670 r12=00000000000009a1 r13=0000000000000031
r14=0000000000000000 r15=0000000000000000
iopl=0         nv up ei pl nz na po nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010206
cheatengine_x86_64_SSE4_AVX2+0x8eec39:
00000000`00ceec39 027dff          add     bh,byte ptr [rbp-1] ss:00000000`145da81f=00
0:018> kb L7
 # RetAddr           : Args to Child                                                           : Call Site
00 00000000`145daa28 : 00000000`145da820 00000000`00000678 00007ffb`ab6ab3e1 00000000`145da81c : cheatengine_x86_64_SSE4_AVX2+0x8eec39
01 00000000`145da820 : 00000000`00000678 00007ffb`ab6ab3e1 00000000`145da81c 00000000`02560000 : 0x145daa28
02 00000000`00000678 : 00007ffb`ab6ab3e1 00000000`145da81c 00000000`02560000 00000000`145daa28 : 0x145da820
03 00007ffb`ab6ab3e1 : 00000000`145da81c 00000000`02560000 00000000`145daa28 00007ffb`73050000 : 0x678
04 00000000`00000000 : 00000000`00000000 00000000`09c65fd0 00000000`0f2b85a0 00000001`255c32b0 : ntdll!RtlFreeHeap+0x51
···

the bug maybe in ce.

**Comment by cheat-engine** [comment]
It looks like it's jumping to the address stored in rax.  Seems to be a random value/stack corruption. (That address ends up in non-executable data, not code)

**Comment by avboy1337** [comment]
> It looks like it's jumping to the address stored in rax. Seems to be a random value/stack corruption. (That address ends up in non-executable data, not code)

chrome pdb is huge , and i will go to have a debug.
really thanks for your reply.
if any info is comming ,i will post here as soon as possible.

**Comment by cheat-engine** [comment]
The most recent release of  the windbg dll in the windows SDK may work. But it will mess up 32-bit targets.  But if you only target 64-bit it should work
