### ISSUE TITLE
[wine] External exception 80000101 on right click / menu toolbar

### ISSUE THREAD

**Issue by GodSaveTheDoge** [cheat-engine/cheat-engine#2275]
When running cheat engine on wine right clicking shows the menu for a split second before a popup that says "External exception 80000101" is shown.

Cheat Engine version: `7.4` (from github)
Wine version: `wine-7.13` (clean WINEPREFIX)
Os: arch

https://user-images.githubusercontent.com/51802433/180082292-7397e478-579a-400d-85ef-95449491f4db.mp4

**Comment by cheat-engine** [comment]
get wine 7.10  ( https://bugs.winehq.org/show_bug.cgi?id=53189 )

**Comment by GodSaveTheDoge** [comment]
downgrading works
