### ISSUE TITLE
Mono Dissect - Lua Error

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#228]
Entered address, accept to auto create structure and received the following error:

![unbenannt](https://user-images.githubusercontent.com/14368203/30210755-1271a506-949e-11e7-9ea0-9909353ce362.png)

It's reproduceable and only happens on a specific game.

**Comment by FreeER** [comment]
well that's surely enough information for someone to pick out the one specific game where it happens to reproduce the error and determine why it's actually happening, even if it does happen for every structure and not just a specific one...

**Comment by Symbai** [comment]
CE has not provided more information. If you want to know something specific go ahead and ask instead of complain. I dont know what Dark Byte needs to know to fix that

**Comment by cheat-engine** [comment]
Does it show the structure name or does it crash before that ?

perhaps the mono connection broke. Go to the mono menu and make sure "activate mono features" is checked. If not, recheck and then try it again.

Alternatively, check out monoscript.lua and see if you can find out where mono_structureDissectOverrideCallback breaks

**Comment by Symbai** [comment]
It shows the structure name. Mono connection works fine until I use dissect structure on it. 
Game has been updated and since then, it stopped working. In DnSpy the assemblies don't look obfuscated.

![ezgif com-optimize](https://user-images.githubusercontent.com/14368203/30238356-4c83dfc2-9546-11e7-8b1f-3b3e5ccab421.gif)

**Comment by cheat-engine** [comment]
works now
