### ISSUE TITLE
DBVM UEFI loader did not load the DBVM properly

### ISSUE THREAD

**Issue by quantaX803t** [cheat-engine/cheat-engine#2283]
I use rEFInd run DBVMUEFI.EFI  after the screen output i selected Win boot option boot to Win.  But, CE did not find the loaded DBVM.

**Comment by quantaX803t** [comment]
Why?

**Comment by quantaX803t** [comment]
menuentry "DBVMUEFI Loader" {
    loader \EFI\refind\DBVMUEFI.EFI
    enable
}

**Comment by cheat-engine** [comment]
you mean the dbvm uefiloader doesn't show up?  Is it in the correct location?

**Comment by quantaX803t** [comment]
I mean, it doesn't look like it's working. I need to click "Your System Supports DBVM".

**Comment by cheat-engine** [comment]
did you launch DBVM uefi and afterwards the windows bootloader, or did you just run the windows bootloader assuming dbvm will load as well?

And did you compile CE yourself? You have to compile it in release mode else it's blind to DBVM

**Comment by quantaX803t** [comment]
Yes i launch DBVM uefi and afterwards the windows bootloader. And CE is release compile.

**Comment by quantaX803t** [comment]
DBVM gives a lot of text

**Comment by quantaX803t** [comment]
emmm It's not loaded.  I wrote the DBVM calls in reference to the DBVM call apis in the CE and DBK drivers, and they didn't work.

**Comment by quantaX803t** [comment]
Click on "Your System Supports DBVM"  it works

**Comment by cheat-engine** [comment]
When the windows bootloader is picked after dbvm has loaded, does it enter a reboot mode and then the windows loader starts, or does it instantly continue loading windows?

**Comment by quantaX803t** [comment]
it instantly continue loading windows.

**Comment by quantaX803t** [comment]
I tried to add the DBVM UEFI loader as the first boot item of UEFI. The situation was different, I saw the screen output each core finished loading DBVM in about one second, then went back to the UEFI boot menu and selected Windows Boot Manager. 

But DBVM is still not loaded.....

**Comment by quantaX803t** [comment]
The problem is currently unresolved, i colse it
