### ISSUE TITLE
Emulator x86_64 Segmentation fault

### ISSUE THREAD

**Issue by xiangkai3346** [cheat-engine/cheat-engine#2291]
process_vm_readv=0x7ffff7d41050
process_vm_writev=0x7ffff7d41070
listening on port 52736
---
&s=0x7fffffffe90c
main=0x555555561f30
sizeof(off_t)=8
sizeof(off64_t)=8
sizeof(uintptr_t)=8
sizeof(long)=8
ATTACH_TO_ACCESS_MEMORY=0
MEMORY_SEARCH_OPTION=2
CEServer. Waiting for client connection
socket=4
successfully bound socket
Listening success
IdentifierThread active
accept=5
OpenProcess(3781)
Getting processdata for TH32CS_SNAPFIRSTMODULE
Creating module list for process 3781
Adding /system/framework/x86_64/boot.oat as a module
Segmentation fault

**Comment by wh1t3-r0s3** [comment]
How did you fix this?? Running into exact same issue
