### ISSUE TITLE
Installer doesn't work whether it is marked as an exception or not

### ISSUE THREAD

**Issue by Speedrunner-doomguy** [cheat-engine/cheat-engine#2292]
Using the latest 7.4 installer on the website, I can get to the point of installation but it errors out with the error "virus or unwanted software detected" and "list out of bounds (19)". I tried fixing this by marking it as an exception in Windows Defender (I don't have any other anti-virus installed currently) only to then be met with the error "division by zero"

**Comment by fade2gray** [comment]
Installing CE is a multistep process.

1. Download the installer from the CE website.
2. Run the installer.
3. The installer connects to a second web address to download more files, after which the installation process continues.

Situations that might cause the problem you are experiencing.

- You have disconnected from the internet before step 2.
- You are using a VPN, proxy or a PiHole.
- Your ISP is blocking your connection to the second web address.

See #1954 and #2099. If you suspect your ISP, and your PC has wi-fi, try using a mobile hotspot to download and install.

**Comment by Speedrunner-doomguy** [comment]
1. I was connected to the internet the whole time
2. I'm currently not using a VPN, proxy, or PiHole
3. It might be my ISP but I don't use wi-fi
considering the process of elimination it's probably my isp but I can't do much since I don't use wifi, and I've looked at #1954 and #2099 a few times and tried a few things to no avail, at this point the most confusing thing is why marking it as an exception gives me a different error than when I don't

**Comment by fade2gray** [comment]
A couple of options...

- Wi-fi dongles are pretty cheap, providing your router/modem is wi-fi capable of course
- Try [building](https://github.com/cheat-engine/cheat-engine#basic-build-instructions) your own - a bit of a learning curve, but fun at the same time - if you do fancy having a go, take note of https://github.com/cheat-engine/cheat-engine/issues/2121#issuecomment-1196490667

Don't know what to say about the errors, except that others report similar, but different, errors that seem to get resolved with the same solution. ¯\\_(ツ)_/¯

**Comment by Speedrunner-doomguy** [comment]
fair enough I'll take a few looks and see if I can build it lol

**Comment by Speedrunner-doomguy** [comment]
built it and although my tcc lib is fucked imma rebuild that and some other stuff and it should work lol, I think it was just my windows install being a bitch but anyways with all of that outta the way thanks
