### ISSUE TITLE
Cheat Engine not opening

### ISSUE THREAD

**Issue by XECTRA-RAW** [cheat-engine/cheat-engine#2293]
I have uninstalled Vanguard and turn off anti viruses and still doesn't open! Lastest and older versions!

**Comment by cheat-engine** [comment]
restart windows (not shut down and back on)if vanguard was loaded in memory a simple unload+shutdown wont work.

**Comment by XECTRA-RAW** [comment]
> restart windows (not shut down and back on)if vanguard was loaded in memory a simple unload+shutdown wont work. 

I have restarted already sadly still not resolved

**Comment by cheat-engine** [comment]
any specific error or just not opening? 

Tey executing windowsrepair.exe and if that doesn't work try looking for other anti-cheats/anti-viruses that could block it

**Comment by XECTRA-RAW** [comment]
> any specific error or just not opening?
Not opening
> Try executing windowsrepair.exe and if that doesn't work try looking for other anti-cheats/anti-viruses that could block it
Will try this now

**Comment by XECTRA-RAW** [comment]
![image](https://user-images.githubusercontent.com/84267120/182474981-5cbaf85b-27c5-4118-b474-8b293364ba55.png)
This is the Error i get after the pop up for it being completed

**Comment by cheat-engine** [comment]
that looks like it's running in debug mode.  
Try building CE in release mode and run it from the desktop.  Don't press the play button.

Or, since you're compiling yourself anyhow, do compile it in Debug mode, and then press the play button and see if an error pops up. (Make sure that the debugger config is working)

**Comment by XECTRA-RAW** [comment]
> that looks like it's running in debug mode.  
> 
> Try building CE in release mode and run it from the desktop.  Don't press the play button.
> 
> 
> 
> Or, since you're compiling yourself anyhow, do compile it in Debug mode, and then press the play button and see if an error pops up. (Make sure that the debugger config is working)

Ran the play button for an error!

Error message 740 failed to execute 740

**Comment by cheat-engine** [comment]
Launch lazarus with administrator access

**Comment by XECTRA-RAW** [comment]
> Launch lazarus with administrator access

I have launched and rebuilt and still no luck!

**Comment by cheat-engine** [comment]
open a command prompt and do a `driverquery /v`
Check if there's no other anti cheat running.
Badlion
XIGNCODE
EAC
nprotect
BattlEye
EQU8
mhyprot
