### ISSUE TITLE
read_____Local issue

### ISSUE THREAD

**Issue by mgrinzPlayer** [cheat-engine/cheat-engine#230]
Since this commit https://github.com/cheat-engine/cheat-engine/commit/ca7965495ab5a2051392e14725e2946a85cd39a9 

this doesn't work (returns nil instead of 9460301):
```
a=readIntegerLocal("cheatengine-x86_64.exe")
return a
```

function lua_toaddress has missing one extra parameter. Should be:
```
function lua_toaddress(L: PLua_state; i: integer; processhandle: thandle)
```

**Comment by cheat-engine** [comment]
fixed

**Comment by mgrinzPlayer** [comment]
https://github.com/cheat-engine/cheat-engine/commit/e022c2a9b02c0a4795c9e0ee9416221573c09f2a#commitcomment-24384624
