### ISSUE TITLE
DBK error, can not start Ultimap, please help me

### ISSUE THREAD

**Issue by raviruia522** [cheat-engine/cheat-engine#2301]
when i start Ultimap, I get the following 3 messages. I don't know where the error is. please help me!
I haven't interfered with the exe file, all I do is download and build the projects cheatengine.lpi and DBKKernel.sln (release x64, can not build x86)
 Boot with unsigned driver support, can not install driver
![Screenshot 2022-08-10 085221](https://user-images.githubusercontent.com/44082224/183793296-5f61276a-8a5c-44b7-b038-bb12e8e31609.jpg)

I use windows 11 pro 64bit and set virtualization in bios = enabled.
If i use the generic version on the website it's perfectly fine but i want to create my own version.
![Screenshot 2022-08-10 080903](https://user-images.githubusercontent.com/44082224/183790197-b89cebf4-e8aa-4965-bd01-d1a38f271fa5.jpg)

![Screenshot 2022-08-10 080919](https://user-images.githubusercontent.com/44082224/183790225-12f19a71-344e-439f-8b26-af7a97242f0e.jpg)

![Screenshot 2022-08-10 080946](https://user-images.githubusercontent.com/44082224/183790235-89230125-e62d-46a1-82d8-1463fdea1aad.jpg)

**Comment by cheat-engine** [comment]
First: build "release no sig" mode , not Release 

And are you sure that you booted up with unsigned driver support ? (The 1st and 3th image are related to signing)
The 2nd one is if you build release mode instead of "release no sig"

**Comment by raviruia522** [comment]
release no sig is good
please tell me what to do nex
![Untitled](https://user-images.githubusercontent.com/44082224/183862109-a172774d-5834-4d9c-9091-7d7eb604eaf3.png)
t

**Comment by cheat-engine** [comment]
It's good. as it shows, DBK64 is properly loaded.
Your next issue is that DBVM isn't loading.

Do you have a working vmdisk.img file in the same folder as CE ?

**Comment by raviruia522** [comment]
I don't have the file vmdisk.img. where can i get it?

**Comment by cheat-engine** [comment]
When you compile DBVM it will generate a vmdisk.img 

but here's a version I made
[vmdisk.zip](https://github.com/cheat-engine/cheat-engine/files/9298666/vmdisk.zip)

**Comment by raviruia522** [comment]
thank you very much. it worked fine
