### ISSUE TITLE
Is there any x32 installer?

### ISSUE THREAD

**Issue by droslean** [cheat-engine/cheat-engine#2310]

**Comment by fade2gray** [comment]
The Cheat Engine installer is for both 32-bit and 64-bit processors.

**Comment by droslean** [comment]
@fade2gray Thanks for the response, but I can't run that binary in my x32 windows XP. Is there any workaround?

**Comment by fade2gray** [comment]
You might have to try an older version. On the main website download page, XP is mentioned in the fixes for version 7.2.

**Comment by droslean** [comment]
@fade2gray I will check the 7.2 version then... But it doesn't make any sense why the binary can't be run in XP

**Comment by droslean** [comment]
@fade2gray Can you share download links, because I can't find how to download 7.2 version.

**Comment by droslean** [comment]
@fade2gray All of them cannot be opened in windows XP. I getting the error that the binary is not a correct WIN32 application.

**Comment by fade2gray** [comment]
6.5 works on a 32-bit XP virtual machine.

**Comment by droslean** [comment]
@fade2gray ok I will try 6.5
