### ISSUE TITLE
Could not find byte array

### ISSUE THREAD

**Issue by romanholidaypancakes** [cheat-engine/cheat-engine#2311]
[![Watch the video](https://i.imgur.com/vKb2F1B.png)](https://user-images.githubusercontent.com/51652878/185741782-ed4f8326-bd54-4a65-a621-f1002e39de52.mp4)

I can find it using x64dbg

**Comment by cheat-engine** [comment]
Those bytes are in non-writable memory and might be copy-on-write as well

change the scan options accordingly,  or just mark them all grey (you can rightclick and choose all)
