### ISSUE TITLE
DVBM Suddenly not being compatible

### ISSUE THREAD

**Issue by Intoprelised** [cheat-engine/cheat-engine#2312]
In the past I have used the Ultimap feature in Cheat Engine 7.4 but now if I try to load it, Cheat Engine says my system does not support DVBM. It has worked before multiple times so I am not sure what the issue is now.

**Comment by cheat-engine** [comment]
Likely you're now running inside a virtual machine now.

Try exiting it and then check

(disable core isolation in windows)

**Comment by Intoprelised** [comment]
![image](https://user-images.githubusercontent.com/78622918/186719239-ac380d32-4eef-477f-8fa1-9a8f2a846119.png)
This is what mine looks like

**Comment by cheat-engine** [comment]
do you have a new AV like Avast? Some of them will run your system inside a virtual machine

**Comment by Intoprelised** [comment]
I use Bitdefender and I checked and my hyper v is disabled

**Comment by Intoprelised** [comment]
Should I have hyper v enabled?

**Comment by cheat-engine** [comment]
No, disabled

try executing `bcdedit /set hypervisorlaunchtype off` and restart windows

**Comment by Intoprelised** [comment]
Thank you I executed that command it works!

Thanks for your help
