### ISSUE TITLE
ceserver compile error 

### ISSUE THREAD

**Issue by avboy1337** [cheat-engine/cheat-engine#2313]
All of arm version are OK to compiled
the gcc version is not OK
the directory is  `cheat-engine/ceserver/gcc`

**Comment by avboy1337** [comment]
/usr/lib/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/arm-linux-androideabi/asm/ptrace.h:21:10: fatal error: 'asm/hwcap.h' file not found

**Comment by Elpersonn** [comment]
Same thing here

**Comment by fizzgig242** [comment]
Same error here on Linux Mint 21. Before it was compiling great.

The old build is working but for me the libceserver-extension.so is no longer found when using the old ceserver executable.

When trying to "make" ceserver I get this:
[make_error_ceserver.txt](https://github.com/cheat-engine/cheat-engine/files/9419022/make_error_ceserver.txt)

When trying to "make" extension I get this:
[make_error_extension.txt](https://github.com/cheat-engine/cheat-engine/files/9419040/make_error_extension.txt)

**Comment by fizzgig242** [comment]
OK. The make error for the extension was easy to fix.

I just had to install this:
sudo apt-get install zlib1g-dev

But when I use the old version (compiled on Mint 20) of ceserver with the newly compiled extension it says "Failure to load the extension".

**Comment by ninjakasav** [comment]
Same issue with Arch

**Comment by otuva** [comment]
still facing the same issue with arch

**Comment by avboy1337** [comment]
sudo apt-get install zlib1g-dev

**Comment by avboy1337** [comment]
compile in \ceserver\gcc when using make also facing this error 

system:Ubuntu
