### ISSUE TITLE
why is cheat engine installing malware

### ISSUE THREAD

**Issue by Apple9928** [cheat-engine/cheat-engine#2319]
windows defender popped up saying  a PUP had been installed called OfferCore

what do i do

**Comment by MatthieuHernandez** [comment]
You need to install the previous version of Cheat Engine. I have the same problem on version 7.4 but it work perfectly with version 7.3.

**Comment by Apple9928** [comment]
> You need to install the previous version of Cheat Engine. I have the same problem on version 7.4 but it work perfectly with version 7.3.

i just installed an alternative to cheatengine called squalr
