### ISSUE TITLE
ceserver compile error 

### ISSUE THREAD

**Issue by avboy1337** [cheat-engine/cheat-engine#2324]
sr/include/arm-linux-androideabi/asm/ptrace.h:21:10: fatal error: 'asm/hwcap.h' file not found
#include <asm/hwcap.h>

I really don't know how to solve this , plz help me or give me a tip

**Comment by DoranekoSystems** [comment]
Make sure to build Application.mk only for arm64.
Currently x86 and arm32 are difficult to get through the build.
```
APP_ABI := arm64-v8a
```

@cheat-engine 
Perhaps it should be changed as follows.

api.c
```
#ifdef __ANDROID__
#if defined (__arm__) || defined(__aarch64__)
#include <arm-linux-androideabi/asm/ptrace.h>
#endif
#endif
```
