### ISSUE TITLE
latest driver can not be loaded

### ISSUE THREAD

**Issue by avboy1337** [cheat-engine/cheat-engine#2328]
I dont know why but i compiled the latest driver but ce can not loaded it .
first , i added windows singnature to the driver

**Comment by cheat-engine** [comment]
try renaming it
(look into driver64.dat)

**Comment by avboy1337** [comment]
driver is success fully loaded , but ce also tips that : you need to load driver if wanna to use dbvm

the latest version compiled 3 minites elearier

**Comment by cheat-engine** [comment]
Are you sure that is the message it shows? Because normally the message is that you could try using DBVM to load the driver instead

**Comment by avboy1337** [comment]
I will try to reproduce it completely tomorrow

**Comment by avboy1337** [comment]
I will try to reproduce it completely tomorrow

**Comment by avboy1337** [comment]
> Are you sure that is the message it shows? Because normally the message is that you could try using DBVM to load the driver instead

sorry ,the tips is driver signing problem.
I am really sorry .
I changed language to English and eventlly tips not garbled code.
It is really garbled code when in Chinese

**Comment by cheat-engine** [comment]
try clesring your certificate revocation list.
It's possible a certain anti cheat has added ce's signature to that

**Comment by avboy1337** [comment]
> 

OK , i will try.
to be honest , I uninstalled windefender throughtly
