### ISSUE TITLE
Debugger can't be attached to Ground Zeroes

### ISSUE THREAD

**Issue by HalfWayLambda** [cheat-engine/cheat-engine#2334]
The cheat engine debugger fails to attach on MGSV Ground Zeroes, given how it's weirdly setup behind the scenes. It appears that when the game's launched, two handles are created, one that hardly takes up any memory that doesn't appear to do anything, and another one that takes up many gigabytes of memory. Attaching the debugger to the latter is what fails, and what's worth attaching to since the other one doesn't have any useful information inside it.
It's worth mentioning that Ground Zeroes has Steam DRM inside its executable, but even if you remove that via Steamless, the situation is the same.
I have tried using the `Create Process` button so that I can get the debugger from the very start, but it injects into the small handle that doesn't have any useful memory.

**Comment by cheat-engine** [comment]
which debugger interfaces have you tried? Only windows? If so, try vehdebug. And if that fails, and you're on intel or have an older AMD, try dbvm level debug

**Comment by HalfWayLambda** [comment]
Okay I forgot cheat engine has more debugger options. I tried the VHE one and it worked, thanks!
