### ISSUE TITLE
How to connect the mac m2 chip to the mobile phone to scan data

### ISSUE THREAD

**Issue by LarissaLycoris** [cheat-engine/cheat-engine#2337]
My computer is an m2 chip, after downloading ce, it can only scan Mac computer applications. How to download the "Server (For network scanning)" of the official website like windows and connect to the mobile phone later? Let the ce of the Mac also connect to the ios phone to scan the data?
thank.

![QQ截图20220910192842](https://user-images.githubusercontent.com/99528736/189481302-09788584-16f2-447f-aa33-727880035495.png)

**Comment by avboy1337** [comment]
I think brother may need to compile or buy the author's commercial version.

**Comment by LarissaLycoris** [comment]
> I think brother may need to compile or buy the author's commercial version.

How to buy the commercial version or where to compile it?

**Comment by cheat-engine** [comment]
the mac version currently doesn't have an interface to connect to ceserver.  Perhaps in the future

**Comment by LarissaLycoris** [comment]
> the mac version currently doesn't have an interface to connect to ceserver. Perhaps in the future

thank
