### ISSUE TITLE
Hotkeys trigger action you are not allowed to do

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#234]
Using hotkeys in grouped scan for changed/unchanged value hides the search field and makes it impossible to do anything with the scan results after hotkey has been pressed.

//edit: This seems to be a general issue as similar behavior appears on string search as well. It looks like the hotkeys are triggered even if you are not allowed to do the action.

**Comment by cheat-engine** [comment]
fixed
