### ISSUE TITLE
Cheat engine 7.1 installation not working

### ISSUE THREAD

**Issue by C0llyFl0wer** [cheat-engine/cheat-engine#2341]
Hey,

I am unable to install CE 7.1 for unknown reasons.
I have downloaded 7.1 successfully, however, when installing the installer wont even show up. Ill click the allow button. Then suddenly the installation box will vanish. 

Ive installed 7.4 successfully with zero issues. However I need 7.1 installed for my current needs and cannot use 7.4. Im not sure why I am unable to get to the installation process so any help is greatly appreciated. 
Ive done everything I can to disable my security/allow access & even uninstalled malware bites, still zero luck. 

As ive said in the above installing 7.4 with no issues. But for whatever reason I cant even get the 7.1 installer to pop up without it automatically disappearing. (Ive uninstalled 7.4 also to make sure I have no installed versions of CE).

**Comment by fade2gray** [comment]
It's possible you may have an AntiCheat program running in the background, installed along with some game or other.

See this https://github.com/cheat-engine/cheat-engine/issues/2293#issuecomment-1203258156

**Comment by C0llyFl0wer** [comment]
Hey,
Took a lengthy look unfortunately no anti cheats running listed in the comment you linked.

**Comment by cheat-engine** [comment]
what function of feature do you need in 7.1 that is missing or broken in 7.4 so I can fix it ?

**Comment by C0llyFl0wer** [comment]
To be honest I am not 100% sure. I googled the cheat table and on the main forum this text is present.

"The table was initially designed with CE 7.4 in mind, but I switched to CE 7.1. There are some issues with CE 7.4 trying to allocate near preferred image bases (or something like that, according to Dark Byte) which causes allocations in my [ Initialize ] script to fail intermittently. What that translates to: every 1-2 tries of my table with a new instance of the game, the script will fail. So you will have to kill game, restart it (which takes a while, given Denuvo start-up and logging in) and retry. With CE 7.1 this won't happen."

Hope that helps. If you need anything else I am happy to provide a link or anything else.

**Comment by cheat-engine** [comment]
Ah that. The person misunderstands what's going on.
In 7.1 if the nearby allocation fails, it allocates at a location that's not nearby, causing assembler instructions that reference the memory to be wrong and crash the game (it then uses 14 byte jmps instead of 5).  But the script does toggle

In 7.4 when the nearby allocation fails CE won't activate the script so the game won't crash. You'll have to manually close the game instead of crashing it

in either case, the game will have to restart when nearby allocation fails.

the table needs to be rewritten to not use nearby allocation and assume 14 byte jmps are needed

**Comment by C0llyFl0wer** [comment]
Ahh that's unfortunate as I don't see the table being updated. Is there anything else that can be done to try successfully install 7.1? Other users have said the table works perfectly fine with 7.1 no crashing or issues.

**Comment by avboy1337** [comment]
> 

uninstall 7.1 and run kernelmoduleunloader-i386.exe
then run windowsrepair.exe

after all the above , try going to install 7.1

**Comment by C0llyFl0wer** [comment]
> > 
> 
> uninstall 7.1 and run kernelmoduleunloader-i386.exe then run windowsrepair.exe
> 
> after all the above , try going to install 7.1

Hey, Sorry is it possible to link me where I can get these .exe files? thanks

**Comment by fade2gray** [comment]
All executables will be found in the Cheat Engine installation folder when it has successfully installed,
i.e. in `C:\Program Files\Cheat Engine`.

You would only need to run `kernelmoduleunloader-i386.exe` if you have run the kernelmode debugger.

![KernelDebugger](https://user-images.githubusercontent.com/1332009/190444140-67372eac-d53a-40f7-962b-b94f358f11a9.png)

**Comment by C0llyFl0wer** [comment]
Apologies for the late reply, haven't had much free time. I tried the above and it finally allowed me to install the earlier version of CE thank you for the help and support!
