### ISSUE TITLE
Compiling dbvm to specify the serial port causes the virtual machine to crash.

### ISSUE THREAD

**Issue by Chordp** [cheat-engine/cheat-engine#2345]
# Compiling dbvm to specify the serial port causes the virtual machine to crash.
### Compile command
`make clean cdimage SERIALPORT=0x3f8`
serial port `0x3f8`~`0x3ff`
putty has no output
### serial port 
---
![image](https://user-images.githubusercontent.com/26430679/191214148-1922494e-103e-4df4-9222-e3900d758ce4.png)
### VMware Setting
---
![image](https://user-images.githubusercontent.com/26430679/191214280-5823eb4f-f9c7-4638-9d5b-26ffb0324cdc.png)

**Comment by cheat-engine** [comment]
try editing the makefile instead and edit the serialport there

**Comment by Chordp** [comment]
```
#SERIALPORT is the port to communicate with the debugger, usually 0x3f8, on db's system it's 0xef00
#SERIALPORT=0 #release/no serialport build
#SERIALPORT=0 #bochs and jtagged gigabyte test system
#SERIALPORT=0xbf00 #intel
#SERIALPORT=0xec00 #amd
#SERIALPORT=0xd010 #16 core test system
#SERIALPORT=0xf010 #32 core test system
#SERIALPORT=0x2f8 #vmware test
SERIALPORT=0x3f8 #vmware

 
#DISPLAYDEBUG if DISPLAYDEBUG==1 it means that all serial output will be sent to the screen instead (useful for cases where dbvm won't load AT ALL, not so much when it does)
DISPLAYDEBUG=0
#SERIALPORT=0xf010 #32 core test system
 
all:
#	make -C vmm all SERIALPORT=${SERIALPORT} DISPLAYDEBUG=${DISPLAYDEBUG}
	make -C vmm -f mkx all SERIALPORT=${SERIALPORT} DISPLAYDEBUG=${DISPLAYDEBUG}
	make -C common all SERIALPORT=${SERIALPORT}
	make -C parsevmmmap all SERIALPORT=${SERIALPORT}
	parsevmmmap/parsevmmmap	
	make -C vmloader all SERIALPORT=${SERIALPORT}
	make -C parsevmloadermap all SERIALPORT=${SERIALPORT}
	parsevmloadermap/parsevmloadermap
	make -C bootsector all SERIALPORT=${SERIALPORT}
	make -C imagemaker all SERIALPORT=${SERIALPORT}

install: all
	imagemaker/imagemaker
	chmod 777 vmdisk.img
	chmod 777 vmdisk144.img
	sync
	
displaydebug: DISPLAYDEBUG=1
displaydebug: clean install
	
usb: install
	@if [ -b /dev/sdb ] ;\
	then \
		dd if=vmdisk.img of=/dev/sdb ;\
		sync ;\
	else \
		echo "/dev/sde does not exist. Did you just run this without understanding makefiles? This could have really fucked you up" ;\
		exit 1 ;\
	fi
	
efiusb: install
	cp vmdisk.img /media/eric/EC9B-5AFC/
	sync

qemu: install
	cp vmdisk.img /mntx
	sync
	@echo "copied files to /mntx"
		
disk: install
	dd if=vmdisk.img of=/dev/fd0
	sync

net: install
	-rm -f /mnt/cebin/vmdisk.img
	cp vmdisk.img /mnt/cebin
	sync

cdimage: install
	-mkdir iso
	-mkdir iso/boot  
	cp vmdisk144.img iso/boot
	cd iso
	mkisofs -r -b boot/vmdisk144.img -c boot/boot.catalog -o vmcd.iso iso/
	

	

release: clean install cdimage
	-rm -rf release	
	mkdir release	
	cp vmcd.iso release
	cp vmdisk.img release
	cp docs/readme.txt release
	cp vmm/docs/vmcall.txt release
	rar a dbvm.rar release/*
	@echo "Your release file is ready"

clean:
	@make -C imagemaker clean
	@make -C parsevmloadermap clean
	@make -C parsevmmmap clean
	@make -C bootsector clean
	@make -C vmloader clean
	@make -C vmm clean
	@make -C common clean
	@-rm -f *.bin
	@-rm -f *.img
	@-rm -f *.map
	@-rm -f *~
	@-rm -rf iso
	@-rm -rf release
	@-rm -f vmcd.iso
	@-rm -f dbvm.rar
	@-rm -f *.elf
```

Still crashing

**Comment by cheat-engine** [comment]
are you launching dbvm from a bootdisk, or using the runtime offloading in windows?

If bootdisk, is it the uefi boot method? If so, you may have to enable compatibility bios support as the bios may not have enabled the serial port

If runtime offloading, try running putty inside the virtual machine as well, and connect to the serial port.
then type in both clients to confirm it's working.  Then launch dbvm and just minimize the putty client on the vm side

**Comment by Chordp** [comment]
> are you launching dbvm from a bootdisk, or using the runtime offloading in windows?
> 
> If bootdisk, is it the uefi boot method? If so, you may have to enable compatibility bios support as the bios may not have enabled the serial port
> 
> If runtime offloading, try running putty inside the virtual machine as well, and connect to the serial port. then type in both clients to confirm it's working. Then launch dbvm and just minimize the putty client on the vm side

Thank you, according to your second suggestion debugging success

**Comment by picklover** [comment]
> are you launching dbvm from a bootdisk, or using the runtime offloading in windows?
> 
> If bootdisk, is it the uefi boot method? If so, you may have to enable compatibility bios support as the bios may not have enabled the serial port
> 
> If runtime offloading, try running putty inside the virtual machine as well, and connect to the serial port. then type in both clients to confirm it's working. Then launch dbvm and just minimize the putty client on the vm side

 I am confusing, why should keep the vm side's putty? I can only see serial port output when vm side's putty or pyserial library is connect, but the sendstring use 'out' directly, in my opinion, i should just keep one putty outside the virtual machine. Does there need some "init" part in windows serial driver?

**Comment by cheat-engine** [comment]
the serial interface seems to be unusable before putty has initialized it

**Comment by picklover** [comment]
> the serial interface seems to be unusable before putty has initialized it

thank you, and i am reversing the serial.sys!SerialFileCloseWorker to see what actually "close the uart".

**Comment by cheat-engine** [comment]
Probably acpi stuff
