### ISSUE TITLE
lua api signature mismatch between c# plugins CESDKLua and lapi.c

### ISSUE THREAD

**Issue by wolfoops** [cheat-engine/cheat-engine#2346]
In c# plugins CESDKLua.cs, lua_pcallk has 5 params:
```
...\cheat-engine\Cheat Engine\plugin\c# template\CEPluginLibrary\SDK\CESDKLua.cs 
 private delegate int dlua_pcallk(IntPtr state, int nargs, int nresults, IntPtr context, IntPtr k);
```
and in lapi.c, it has 6 params:
```
...\cheat-engine\Cheat Engine\lua53\lua53\src\lapi.c 
LUA_API int lua_pcallk (lua_State *L, int nargs, int nresults, int errfunc, lua_KContext ctx, lua_KFunction k) {

```
btw, how to tell the exact version of the Lua ce using, ie. 5.3.0 or 5.3.4???

**Comment by cheat-engine** [comment]
Thanks. I fixed it.
As for the version you could call the lua function getCEVersion() which will return a float holding the version number.  e.g 5.3.0 will be 5.30 and 5.3.4 would be 5.34

**Comment by wolfoops** [comment]
Thank you for the fix. 

But would you confirm which version is the correct one (that's in lua53-64.dll ce using)?  
The lua_pcallk in the lua53-64.dll seems has only 5 params.

And, getCEVersion() return ce version only, ie. return 7.3  instead of lua's 5.xx .

**Comment by cheat-engine** [comment]
lua_pcallk has 6 parameters but since it's cdecl it's not an issue that the parameter is forgotten even in 32-bit
as for the lua verison, just look up the global variable `_VERSION`

**Comment by wolfoops** [comment]
_VERSION return "Lua 5.3".

Want to know the ce using which lua 5.3.x because ce definitely using an older 5.3 version, for instance, it not support 'ipairs' metamethod, eg
```
local t = setmetatable({},{
__pairs =function()return pairs{'pairs'}end,
__ipairs =function()return ipairs{'ipairs'}end,
})
print'test ipairs'
for a,b in ipairs(t)do print(a,b)end
print'test pairs'
for a,b in pairs(t)do print(a,b)end
-- in ce,  ipairs iter in an empty table so no output, but pairs return '1 pairs'
-- in zerobrane editor, ipairs return '1 ipairs'
```
Anyway, this comment can be closed. Thank you~
