### ISSUE TITLE
Driver could't load.

### ISSUE THREAD

**Issue by marfixdev** [cheat-engine/cheat-engine#2351]
It says my system support dbvm but when I try to click green word and load driver it gives me error.

I disabled anti-virus etc.
I just downloaded recent version from cheatengine.org.
I didnt compiled anything or any driver. (Do I need ? My cheatengine folder have dbk32 and dbk64 in it.)
Enabled virtuliuze stuff from bios

still not loading driver.

![Screenshot_3](https://user-images.githubusercontent.com/52481203/192165768-acdf6895-b5e1-470e-879a-7f557dcbba1c.png)
![Screenshot_2](https://user-images.githubusercontent.com/52481203/192165771-cb32646f-e4af-408f-9d34-e2c613570bc2.png)
![Screenshot_1](https://user-images.githubusercontent.com/52481203/192165774-ca88a71e-7061-4631-9c64-34039b71b852.png)

**Comment by cheat-engine** [comment]
Open regedit

Navigate to HKLM\System\CurrentControlSet\Control\CI\Config\

Create a new DWORD named VulnerableDriverBlocklistEnable and set to 0

Reboot

**Comment by avboy1337** [comment]
At first I also encountered this problem, and then recompile a little to solve all

**Comment by marfixdev** [comment]
> Open regedit
> 
> Navigate to HKLM\System\CurrentControlSet\Control\CI\Config\
> 
> Create a new DWORD named VulnerableDriverBlocklistEnable and set to 0
> 
> Reboot

Wow now it works like a charm ! Thank you.
