### ISSUE TITLE
debugging dbvm with physical machine using ch340 usb to serial port how to fill SERIALPORT

### ISSUE THREAD

**Issue by Chordp** [cheat-engine/cheat-engine#2353]
I need two physical machines to debug dbvm 
Using ch340 usb to serial port There is no I/O range in the device manager
---
![image](https://user-images.githubusercontent.com/26430679/192216543-5ea89901-4122-46c6-aacb-c8c095d58b4f.png)

**Comment by cheat-engine** [comment]
USB serial port won't work.  You'll need a real serial port.
Look up `startech rs232 pci-express`
