### ISSUE TITLE
compile error, latest commit~

### ISSUE THREAD

**Issue by avboy1337** [cheat-engine/cheat-engine#2356]
tcclib.pas(1256,38) Warning: Local variable "module" does not seem to be initialized
debugeventhandler.pas(722,1) Warning: Function result variable does not seem to be initialized
debugeventhandler.pas(1231,3) Error: Identifier not found "hasSetInt1Back"
debugeventhandler.pas(1240,7) Error: Identifier not found "hasSetInt1Back"

**Comment by ftwftw0** [comment]
Hello @bb33bb ,

I'm actually facing the same issue when compiling CE 7.4 with Lazarus 2.2.2.
Do you remember how you fixed this ?
