### ISSUE TITLE
DBVM debugger crashed my Windows

### ISSUE THREAD

**Issue by danthespal** [cheat-engine/cheat-engine#2377]
Hi guys, I encounter this problem while trying to use DBVM debugger on windows 10

![IMG_20221024_223734](https://user-images.githubusercontent.com/55256796/197614371-6717001b-d92d-4439-a958-cd594cbf7425.jpg)

**Comment by cheat-engine** [comment]
try running without any games installed (so no anti cheat) and no virtual machines either

**Comment by danthespal** [comment]
I have a AMD Ryzen 5 3600X I did try to uninstall the battlenet and diablo and still the same... is there any issue with my cpu?

**Comment by danthespal** [comment]
You need to enable virtualization in BIOS, (SVM Mode).

**Comment by danthespal** [comment]
You need to enable virtualization in BIOS, (SVM Mode).
