### ISSUE TITLE
How to disable PDB file loading by Exe Trainer

### ISSUE THREAD

**Issue by Y-A-K-E** [cheat-engine/cheat-engine#2379]
2.8GB & 10% CPU....

![20221029010744](https://user-images.githubusercontent.com/6988291/198693760-45ff076f-845d-4abc-8bc2-4b88c1e0c118.png)

----

delete PDB file
167MB & 0.x% CPU

![20221029011506](https://user-images.githubusercontent.com/6988291/198695064-aafd6f2c-ad4b-4d8d-a912-fa93487a6e8c.png)

**Comment by cheat-engine** [comment]
```
waitForDotNet()
releaseDebugFiles()
```
