### ISSUE TITLE
FPU Registers mis-aligned

### ISSUE THREAD

**Issue by Fireboyd78** [cheat-engine/cheat-engine#238]
Not sure if it's CPU-related, but on my AMD FX6120 the FPU registers are all screwed up:
![](https://i.imgur.com/BP7PfNd.png)

You can see the problem here:
![](https://i.imgur.com/DgkF4Wn.png)

Notice how the number of bytes to the first float value is 6 bytes, which means float output appears garbled:
![](https://i.imgur.com/ijLw3CA.png)

Without knowing the cause of this bug, is it possible to add some kind of "offset" field that ignores the first _n_ bytes so output can appear correctly? This makes debugging FPU stuff pretty much impossible, and has been present since at least v6.5.

**Comment by cheat-engine** [comment]
Set your view to FPURegisters/Extended
By default(and I doubt it can be changed) the FPU memory block stores all floating point values using the Extended type (10 bytes long)

**Comment by Fireboyd78** [comment]
Thank you @cheat-engine! May I suggest adding in a label that suggests using the "Extended" display type to properly display values? Or remove the other types since they don't seem to work anyways.
