### ISSUE TITLE
add new feature of copy data ?

### ISSUE THREAD

**Issue by avboy1337** [cheat-engine/cheat-engine#2382]
![image](https://user-images.githubusercontent.com/5463104/198977760-8a04079a-1dc4-4938-9bc4-0b0750d0e093.png)
for the reason to show memory or to make powerpoints , Some times need to copy data as num1 ,some times need to copy as num2

And for the purpose of beauty , we have to change this and that .

Is there any possible to add a copy command to copy the original feature and layout of the text from CE?

**Comment by Skyrimfus** [comment]
Select the block you want to copy from, press CTRL+C.
Select the starting point where you want to copy to, press CTRL+V
![FMN04J1xoN](https://user-images.githubusercontent.com/78047947/200657888-cdd930ba-82d2-43d6-8b0f-413b8a36c66a.gif)
