### ISSUE TITLE
win compile error

### ISSUE THREAD

**Issue by avboy1337** [cheat-engine/cheat-engine#2383]
![image](https://user-images.githubusercontent.com/5463104/198994522-eb38ab4a-e3d7-4315-bba1-103875a262ca.png)

**Comment by a597407455** [comment]
There is no such sentence in the original document. Why do you have it?

**Comment by fade2gray** [comment]
@a597407455 https://github.com/cheat-engine/cheat-engine/blob/master/Cheat%20Engine/breakpointtypedef.pas

**Comment by a597407455** [comment]
Mine doesn't
I can't compile these four
-----
DirectXMess.sln
monodatacollector.sln
dotnetinvasivedatacollector.sln
cejvmti.sln
----
Can you help me out? thank you

> 最新的主数据源也有同样的错误，
> 
> ```
> Compile Project, Mode: Release 64-Bit O4 AVX2, Target: bin\cheatengine-x86_64-SSE4-AVX2.exe: Exit code 1, Errors: 2
> breakpointtypedef.pas(76,18) Error: Identifier not found "TRegisterModificationBPEx"
> breakpointtypedef.pas(76,43) Error: Error in type definition
> ```

**Comment by avboy1337** [comment]
Basically I compile it every time when there is a new commit, and the environment is same everytime. But this time, I don't know why compiling tips error.

**Comment by xhl8298** [comment]
clean project try

**Comment by avboy1337** [comment]
> clean project try

This did work, however, I deleted and recompiled them all
also error

**Comment by avboy1337** [comment]
patched！！

**Comment by a597407455** [comment]
The new version of your problem has been fixed, but the 32-bit program cannot be compiled. And I have been unable to compile 32-bit drivers, but I can compile 64 bit drivers. I am very confused!

**Comment by cheat-engine** [comment]
32-bit compilation is the lowest priority. i'll fix that when all the rest is done.

**Comment by a597407455** [comment]
> 32位编译是最低优先级。剩下的事我会修好的。

Thank you very much. You are a great writer. I have been studying how to compile those software, and I can compile other software.
