### ISSUE TITLE
android ceserver  arm64 attach will crash

### ISSUE THREAD

**Issue by c01ns** [cheat-engine/cheat-engine#2385]
![image](https://user-images.githubusercontent.com/44087084/199241876-38860ed4-b85a-4b62-82cc-d30db763f265.png)
![image](https://user-images.githubusercontent.com/44087084/199241916-3130a474-5018-4b55-91ab-7846d468339a.png)
I build android arm64 server . and use README run start server, attaching arm64 app will crash

**Comment by cheat-engine** [comment]
you also compiled cheat engine itself ?

**Comment by c01ns** [comment]
no .I only build ceserver.  I use 7.4 7.2 7.0 cheat engine All will Stuck

**Comment by c01ns** [comment]
my phone version is android12

**Comment by cheat-engine** [comment]
you need to use the cesourcecode that belongs to the ce version you use.  If you get it from the current github, you need the current github ce .  so 7.4.2 if you got it from github

**Comment by c01ns** [comment]
7.4.2 is working  thanks。
