### ISSUE TITLE
Speed hack not working on chrome tab

### ISSUE THREAD

**Issue by Intoprelised** [cheat-engine/cheat-engine#2387]
I have the latest version of cheat engine attached to a chrome tab and I am trying to use the speed hack but I am getting this error
![image](https://user-images.githubusercontent.com/78622918/200068436-538b4d7d-0b46-43a0-8d2f-18d657c66539.png)

I do not know how to fix this

**Comment by cheat-engine** [comment]
is autorun/alternateSpeedhack.lua present?
and is libtcc properly compiled for the chrome target ?

**Comment by Intoprelised** [comment]
How do I check those?

**Comment by Intoprelised** [comment]
![image](https://user-images.githubusercontent.com/78622918/200086328-e5488fd8-630b-4234-bd06-d57fe4064a20.png)
I searched in my ce filles for auto run

**Comment by cheat-engine** [comment]
Looks like it's not in 7.4, but I'm not sure support for it is in there or not

copy https://raw.githubusercontent.com/cheat-engine/cheat-engine/master/Cheat%20Engine/bin/autorun/alternateSpeedhack.LUA to your autorun folder (save as textfile) and then try the speedhack

**Comment by Intoprelised** [comment]
Thank you it worked!
