### ISSUE TITLE
Any way to make ceserver as a .so file?

### ISSUE THREAD

**Issue by hellidox** [cheat-engine/cheat-engine#2390]
This would allow rootless use of cheat engine on more protected devices like android where you can add this .so as a bundled dependency inside an apk, like you can with frida. If there's a way to do this with frida that'd also be amazing

**Comment by cheat-engine** [comment]
You can. But it's a lot easier to just use apktool to set the debuggable flag,  reinstall the apk, and then use run-as packagename and copy the ceserver and extensions to the homedir of the package and execute it there.  that way debugging will also work without issues

**Comment by cheat-engine** [comment]
that's the old version which has a symbol enum issue

you have to compile the latest ceserver from sourcecode and also need to use the latest ce sourcecode
next release i'll post some new binaries

**Comment by cheat-engine** [comment]
I use eclipse with CDT and the Android SDK
You will have to adjust the include paths inside the eclipse project to point to your SDK paths.

Some people use ndk-build but I heard it has some inconsistencies from the builds I make (they mess up debugging)

**Comment by cheat-engine** [comment]
I forgot to commit the last changes. should work better now

**Comment by cheat-engine** [comment]
ah, this is an error on compiling for i386 (I hardly ever try that one, not many devices use x86 32 bit these days)
I'll fix it.

As for compiling in eclipse-cdt, after opening the project you'll have to adjust the properties of the project and in c++ build/settings->tool settings at the includes adjust the path to one on your system.  (You may also need to change the --target parameter if you don't have the same android sdk . `--target=aarch64-linux-android31` )

**Comment by cheat-engine** [comment]
fixed the compilation

**Comment by cheat-engine** [comment]
did you redownload the sourcecode ? 
And which error do you get now?

e.g your original log says:
```/home/atrius/git/cheat-engine/CheatEngine/ceserver/ndk-build/EXECUTABLE/jni/../../../extensionloader.c:1011:39: error: use of undeclared identifier 'newregs'
    if ((ptrace(PTRACE_POKEDATA, pid, newregs.esp+0, returnaddress)!=0) ||```

but that code has been changed to use newstate instead of newregs , so it's impossible to give the exact same error

**Comment by cheat-engine** [comment]
i think the ndkbuild files need to be updated to include options.c in the compilation
