### ISSUE TITLE
 error: undefined symbol: handleGetOptions

### ISSUE THREAD

**Issue by avboy1337** [cheat-engine/cheat-engine#2395]
avboy@ubuntu:~/Desktop/cheat-engine/ceserver/ndk-build/EXECUTABLE$ ndk-build
Android NDK: APP_PLATFORM not set. Defaulting to minimum supported version android-16.
[x86] Executable     : ceserver
ld: error: undefined symbol: handleGetOptions
>>> referenced by ceserver.c:1275 (../../../ceserver.c:1275)
>>>               ./obj/local/x86/objs/ceserver/__/__/__/ceserver.o:(DispatchCommand)

ld: error: undefined symbol: handleSetOption
>>> referenced by ceserver.c:1287 (../../../ceserver.c:1287)
>>>               ./obj/local/x86/objs/ceserver/__/__/__/ceserver.o:(DispatchCommand)

ld: error: undefined symbol: handleGetOption
>>> referenced by ceserver.c:1281 (../../../ceserver.c:1281)
>>>               ./obj/local/x86/objs/ceserver/__/__/__/ceserver.o:(DispatchCommand)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/usr/lib/android-sdk/ndk-bundle/build/core/build-binary.mk:741: obj/local/x86/ceserver] Error 1
avboy@ubuntu:~/Desktop/cheat-engine/ceserver/ndk-build/EXECUTABLE$

**Comment by cheat-engine** [comment]
you'll have to update the ndkbuild stuff and add options.c 
I don't use ndk-build to compile ceserver (I also heard it breaks debugging) so not sure where

**Comment by foxhacker0000** [comment]
same problem

i got error on windows and linux

please release or send android ceserver file executable for me at email sir

best.fox.hacker@gmail.com
