### ISSUE TITLE
Compile error 'frmModifyRegistersUnit.pas(1053,36) Error: Identifier not found "doubletoextended"'

### ISSUE THREAD

**Issue by hollowharkov** [cheat-engine/cheat-engine#2404]
When I try to compile I get the following error `frmModifyRegistersUnit.pas(1053,36) Error: Identifier not found "doubletoextended"`

I already added laz.virtualtreeview_package as a requirement but that only fixed the first error, and now Cheat Engine refuses to compile with that errror.

**Comment by cheat-engine** [comment]
compile for 64 bit

**Comment by hollowharkov** [comment]
I tried both 64 bit and 32 bit compilation
