### ISSUE TITLE
VERY IMPORTANT!!!!!! Account hacking....

### ISSUE THREAD

**Issue by lucazandrade** [cheat-engine/cheat-engine#2405]
My wife had a problem downloading the Cheat Engine from the website: https://www.cheatengine.org/ we had our accounts hacked, and now Google accuses attempts
malicious app access, checked, the MD5 of the ".exe" file does not match, and it is described as being the same version, which is strange,
Is this website yours? Is it safe to download there? Another person I know had their account hacked too, and also used the website version,
and it was invaded almost at the same time...

**Comment by cheat-engine** [comment]
It is safe yes. But watch out which cheat tables you download. Those can be malicious

**Comment by vampireamorph** [comment]
No was invaded.

Em seg., 28 de nov. de 2022 às 23:08, lucazandrade ***@***.***>
escreveu:

**Comment by cxtal** [comment]
@lucazandrade your wife downloaded Cheat Engine and used it? Does she have a sister, maybe? Asking for a friend...
