### ISSUE TITLE
Driver signature expired

### ISSUE THREAD

**Issue by skrandy** [cheat-engine/cheat-engine#2422]
DBK.sys Driver signature expired
![image](https://user-images.githubusercontent.com/44647694/207534235-226d5919-8d94-4fe3-b3f5-e479da632094.png)

**Comment by cheat-engine** [comment]
Open regedit

Navigate to HKLM\System\CurrentControlSet\Control\CI\Config\

Create a new DWORD named VulnerableDriverBlocklistEnable and set to 0

Reboot
