### ISSUE TITLE
System Freeze when Enabling DBVM

### ISSUE THREAD

**Issue by marfixdev** [cheat-engine/cheat-engine#2423]
I'm having issue when loading DBVM. I click on "Your system supports DBVM" and i click on OK my system freeze and I can't do anything. ~~crash with bluescreen message "CLOCK_WATCHDOG_TIMEOUT"~~ . Hyper-V disabled already. I turned off SVM from bios(Is it reason?) I need to keep it off for some reason.

EDIT : I tried it again. It doesn't give bluescreen It just freeze my system

**Comment by cheat-engine** [comment]
Tried disabling any other virtual machine running on your system?

**Comment by Henuts** [comment]
**my computer info(in msinfo32 ):**
_Processor	13th Gen Intel(R) Core(TM) i7-13700KF, 3400 Mhz, 16 Core(s), 24 Logical Processor(s)
OS Name	        Microsoft Windows 11 Enterprise LTSC_


1. dbvm freeze my screen，when i Install the system try first.

2.it dump my computer to blue screen ,when i lock the number of processors to 1, in system configuration.
`stop code:SYSTEM_THREAD_EXCEPTION_NOT_HANDLED`

3. when i close hyper-v base on [microsoft](https://learn.microsoft.com/en-us/troubleshoot/windows-client/application-management/virtualization-apps-not-work-with-hyper-v),dbvm freeze screen too.

**dbvm can work normal ,when i try in VMware,the virtual machine os is same with my computer**.

**Comment by RVFET** [comment]
This issue still exists.
13th gen i9 (13900HX - 32 cores) on Windows 11, all windows hyper-v/virtualization based security is disabled, core isolation and whatnot is off. DBVM loads successfully but in a split second it freezes entire system. Manually giving few cores to DBVM (right clicking green text in about) does not work too, same issue yields no matter what I try.

**Comment by cheat-engine** [comment]
likely a new security feature in the cou that win 11 uses
Try telling windows not to use it (probably the stack verification thing) no idea how
