### ISSUE TITLE
tcclib windows compile?

### ISSUE THREAD

**Issue by qwer0123456** [cheat-engine/cheat-engine#2429]
tcclib.sln: Compile 32-32, 64-32 and 64-64 to add {$C} and {$CCODE} support in scripts

tcclib sln file is missing

How to compile on windows?

**Comment by cheat-engine** [comment]
https://github.com/cheat-engine/cheat-engine/tree/master/Cheat%20Engine/tcclib/win32/tcc

**Comment by qwer0123456** [comment]
> https://github.com/cheat-engine/cheat-engine/tree/master/Cheat%20Engine/tcclib/win32/tcc

I just found out it was inside a folder

thank you
