### ISSUE TITLE
ClOCK_WATCHDOG_TIMEOUT in windows 10 21h2 19044.2364

### ISSUE THREAD

**Issue by a52697261** [cheat-engine/cheat-engine#2432]
It seems triggered by patch guard, when patchguard change cr0.wp,dbvm crash.
This issue can be reproduced by using following code.
without dbvm it works fine.
After dbvm loading , Execute the following code will result into ClOCK_WATCHDOG_TIMEOUT BSOD
	```
__try
			{
				auto cr0Value= __readcr0();

				//LOG_DEBUG("write cr0\r\n");
				__writecr0(cr0Value& 0xFFFFFFFFFFFEFFFFui64);
                               //LOG_DEBUG("restore cr0\r\n");
				__writecr0(cr0Value);
			}
			__except (1)
			{
				//LOG_DEBUG("write cr0 exception!\r\n");
			};
```

**Comment by cheat-engine** [comment]
should work better now

**Comment by a52697261** [comment]
thank you!
