### ISSUE TITLE
Cheatengine shows misleading information for redirectional exports

### ISSUE THREAD

**Issue by DrP3pp3r** [cheat-engine/cheat-engine#244]
Clicking on an redirected export in the "Enumerate DLL's" view sets the the disassembly view to the address where the forwarder string sits and doesn't resolve the redirected export. 

![screenshot](https://user-images.githubusercontent.com/17963997/32420044-0dbf3392-c285-11e7-9531-32b524d7751e.PNG)

In my opinion CE should show when an export is redirected and lead to the actual 
function, not the forwarder string. For Example like this:

![example](https://user-images.githubusercontent.com/17963997/32420463-f5f2d3d0-c28a-11e7-9ac9-8fcdc30d4695.PNG)

**Comment by cheat-engine** [comment]
should work as expected now
