### ISSUE TITLE
I don't know what you did, you didn't crash, but you also didn't load DBVM.

### ISSUE THREAD

**Issue by jesionWang** [cheat-engine/cheat-engine#2442]
Hello, I encountered this prompt when running DBVM in CE compiled by myself, and Debug found such a prompt. I do not know how this problem occurs, hope to get help.

"I don't know what you did, you didn't crash, but you also didn't load DBVM."

![image](https://user-images.githubusercontent.com/54129641/210732997-bd5b7ed0-1c4c-43a8-b504-0bad8cdf0fa3.png)

![image](https://user-images.githubusercontent.com/54129641/210732889-34e5e249-99f1-4387-b6c7-2b735eddc516.png)

**Comment by jesionWang** [comment]
Yes, I compiled it with version 7.2 and compiled the driver with vs 2019. But I didn't understand what dbvm compilation meant because there was no dbvm compilation in the tutorial I looked at.

**Comment by jesionWang** [comment]
> Did you compile the driver and dbvm as well ?

Yes, I compiled it with version 7.2 and compiled the driver with vs 2019. But I didn't understand what dbvm compilation meant because there was no dbvm compilation in the tutorial I looked at.

**Comment by cheat-engine** [comment]
you'll need to build dbvm.  I use a linux system for that.  Yasm and Nasm need to be installed and I use gcc version 7.5.0

then in the dbvm folder do a `make clean install` and copy the vmdisk.img to your ce bin folder
You can also get the dbvm image from a normal ce release. Just make sure it's 7.2 or later then

**Comment by jesionWang** [comment]
OK, thank you for your support. I'll try.

**Comment by jesionWang** [comment]
> you'll need to build dbvm. I use a linux system for that. Yasm and Nasm need to be installed and I use gcc version 7.5.0
> 
> then in the dbvm folder do a `make clean install` and copy the vmdisk.img to your ce bin folder You can also get the dbvm image from a normal ce release. Just make sure it's 7.2 or later then

OK, thank you for your support. I'll try.
