### ISSUE TITLE
What should I do if win11 is not compatible with the sys driver file compiled from the DBKKernel file?

### ISSUE THREAD

**Issue by MaxSecurity** [cheat-engine/cheat-engine#2443]
How to solve it?

**Comment by cheat-engine** [comment]
disable the vulnerable driver blocklist
`
Open regedit

Navigate to HKLM\System\CurrentControlSet\Control\CI\Config\

Create a new DWORD named VulnerableDriverBlocklistEnable and set to 0

Reboot
`

**Comment by MaxSecurity** [comment]
> 禁用易受攻击的驱动程序黑名单
> 
> ```
> Open regedit
> 
> Navigate to HKLM\System\CurrentControlSet\Control\CI\Config\
> 
> Create a new DWORD named VulnerableDriverBlocklistEnable and set to 0
> 
> Reboot
> ```
> 
> 此外，禁用安全启动并使用您自己的代码签名证书对驱动程序进行签名。或启用测试签名并对驱动程序进行测试签名，或在启动时禁用签名要求

Hello, my regedit does not seem to have this directory HKLM\System\CurrentControlSet\Control\CI\Config\
![image](https://user-images.githubusercontent.com/16812469/210917025-39f81609-b265-43f8-b903-4cc11b6404d2.png)

**Comment by MaxSecurity** [comment]
Thank you very much, it has been solved perfectly

> 禁止使用易受攻击的驱动程序黑名单
> 
> ```
> Open regedit
> 
> Navigate to HKLM\System\CurrentControlSet\Control\CI\Config\
> 
> Create a new DWORD named VulnerableDriverBlocklistEnable and set to 0
> 
> Reboot
> ```
> 
> 此外此外禁用使用自己代码证书驱动程序进行签名。。或启用启用测试测试并并驱动驱动驱动程序程序进行进行进行测试测试

Thank you very much, it has been solved perfectly
