### ISSUE TITLE
No .NET info found (Cause & Solution)

### ISSUE THREAD

**Issue by Y-A-K-E** [cheat-engine/cheat-engine#2448]
### Cause 

If the target process is 64-bit .NET 
The .net version of dbgshim.dll needs the same .net version of the game. Different versions will pop up the error "No.NET info found".

![2023-01-11 195024](https://user-images.githubusercontent.com/6988291/211799314-eb7a0326-6667-45c0-be73-8331b73edb44.jpg)

#2172 

-----

target process .net version : 5.0
DotNetDataCollector64.exe LoadLibraryA("dbgshim.dll") version : 4.7  

![2023-01-11 200353](https://user-images.githubusercontent.com/6988291/211801783-e71dce39-9e01-4622-9920-65255a81f0e1.jpg)

![2023-01-11 200105](https://user-images.githubusercontent.com/6988291/211801898-80d985ba-8069-4bfe-87ed-8b049c5e192c.jpg)

-------

### Solution

If I add an environment variable and adjust it with the highest priority.

![2023-01-11 201115](https://user-images.githubusercontent.com/6988291/211803241-25c7ce23-ed10-48a1-abc9-061fdd9dffa8.jpg)

It works:

![2023-01-11 201634](https://user-images.githubusercontent.com/6988291/211804267-52dad07d-1364-4b4d-9886-5881ccfc9dbe.jpg)

-----

I have an idea:
OpenProcess(target process)-->is .net-->is 64bit-->enum all dll ---> get 'System.Runtime.dll' path 
(System.Runtime.dll & dbgshim.dll & mscoree.dll are always in the same folder)

DotNetDataCollector64.exe -> FileExists(path+dbgshim.dll) --> call LoadLibraryA

**Comment by cheat-engine** [comment]
you can also empty the searchpath and dotnetdatacollector will check the path of the game

**Comment by Y-A-K-E** [comment]
> you can also empty the searchpath and dotnetdatacollector will check the path of the game



the game path:
`E:\SteamLibrary\steamapps\common\tModLoader\`

dotnet.exe path:
`E:\SteamLibrary\steamapps\common\tModLoader\dotnet\6.0.0\dotnet.exe`

dbgshim.dll path (The searchpath does not include this):
`E:\SteamLibrary\steamapps\common\tModLoader\dotnet\6.0.0\shared\Microsoft.NETCore.App\6.0.0\dbgshim.dll`


game path:

![20230111234105](https://user-images.githubusercontent.com/6988291/211849830-f9cd06cd-a25b-4cdf-a32b-488158085e00.jpg)


command line:

![20230111234639](https://user-images.githubusercontent.com/6988291/211851570-f20f1a2e-7d1f-46ef-918b-f2a91aee00f0.jpg)

**Comment by cheat-engine** [comment]
this breaks on Barotrauma though so still needs the local gamepath as well
