### ISSUE TITLE
 exe trainer requires extra file win64/old/dbghelp.dll 

### ISSUE THREAD

**Issue by Y-A-K-E** [cheat-engine/cheat-engine#2451]
The trainer will exit abnormally after executing the command `LaunchMonoDataCollector()`.
Try to run the trainer again, and the trainer will exit abnormally (no exec LaunchMonoDataCollector() or other ).

If the trainer has the file win64/old/dbghelp.dll, is working.

**Comment by cheat-engine** [comment]
just means that the symbol data by the target process has something that makes some versions of dbghelp crash while enumerating the symbols

As you've figured out the solution is to try different windbg versions till you find one that gets the symbols 100%
