### ISSUE TITLE
Excuse me, when the DBVM and the Android emulator are turned on at the same time, the system directly freezes with a blue screen. Is there any way to solve it?

### ISSUE THREAD

**Issue by MaxSecurity** [cheat-engine/cheat-engine#2456]
Excuse me, when the DBVM and the Android emulator are turned on at the same time, the system directly freezes with a blue screen. Is there any way to solve it?

**Comment by cheat-engine** [comment]
Don't have any virtual machine running at the same time as dbvm. (dbvm won't work on it anyhow)

**Comment by MaxSecurity** [comment]
> 没有任何虚拟机与 dbvm 同时运行，因此在加载 dbvm 之前关闭它（无论如何 dbvm 都无法在其上运行）

Okay thank you
