### ISSUE TITLE
No .NET Info Found Revisted

### ISSUE THREAD

**Issue by Marcus101RR** [cheat-engine/cheat-engine#2457]
Reviving the Issue #2172

Windows 11
tModLoader and other Types of .NET

Original Terraria works fine, but the methods provided in the previous issue did not resolve it for either of them.

![image](https://user-images.githubusercontent.com/8344293/212619254-3210d503-cb59-468a-aaa7-5ca815c64f79.png)

**SOLUTION**
_1. Visit 32-bit or 64-bit Folder (C:\Program Files\dotnet\shared\Microsoft.NETCore.App)
2. Change 7.0.2 to "invalid 7.0.2" or related folder name
3. tModloader and other types of apps using this dotnet will now work with CE._

**Comment by Marcus101RR** [comment]
Solved, See Solution

**Comment by Y-A-K-E** [comment]
see #2449

git pull 
rebuild `DotNetDataCollector32.exe` and `DotNetDataCollector64.exe`
