### ISSUE TITLE
Error compiling: lua_isinteger not found

### ISSUE THREAD

**Issue by survivalizeed** [cheat-engine/cheat-engine#2459]
Error occurs in createTimerInternal function (l.45). Using latest master source and lazarus version

**Comment by fade2gray** [comment]
The latest Lazarus version is 2.2.4 - did you read the build instructions in the README.md for the required version?

**Comment by cheat-engine** [comment]
it's in lua/lua.pas

try build instead of compile

**Comment by survivalizeed** [comment]
The build for mac was checked and that caused the error for me. Fixed it now. Thanks for the help
