### ISSUE TITLE
The driver needs to be loaded to be able to use this function

### ISSUE THREAD

**Issue by ruirui1128** [cheat-engine/cheat-engine#2461]
![K8DHQ8YA83})J}0{$VO`0PQ](https://user-images.githubusercontent.com/21094220/212844407-a71291cb-23e6-4f13-99de-cf89049d2b6d.png)

PC             : wind11
CE version : 7.4
How can I solve it? Please help me, thank you

**Comment by cheat-engine** [comment]
I assume you got a different error message before that ?
Assuming it's a driver failed to load error:
```
Open regedit
Navigate to HKLM\System\CurrentControlSet\Control\CI\Config\
Create a new DWORD named VulnerableDriverBlocklistEnable and set to 0
Reboot
```

**Comment by ruirui1128** [comment]
thank you
