### ISSUE TITLE
What is the difference between Normal and Lite version?

### ISSUE THREAD

**Issue by oxou** [cheat-engine/cheat-engine#2468]
I've realized you ship 2 installations, 1st is "Normal" the 2nd is "Lite"

What difference does it make? And shouldn't the "Lite" version be smaller than the "Normal" version?

Or is it because "Lite" is more easily distributed locally i.e. offline?

Thanks

**Comment by cheat-engine** [comment]
2nd one.  It also misses the "dangerous" files like ceregreset, the 32-bit tutorial, standalone trainer maker files and the driver (as many AV's flag these files as dangerous)

**Comment by oxou** [comment]
That answers the question, thanks!
