### ISSUE TITLE
executable installed malware on my PC

### ISSUE THREAD

**Issue by ejje09** [cheat-engine/cheat-engine#2469]
The CheatEngine74.exe installed two antiviruses and turned off Windows Defender, despite the fact that the only permission it asked for during installation was for installing Opera browser, which I declined. I am now forced to wipe my entire PC, becuase I have no way of knowing what else the installer executed.

**Comment by cheat-engine** [comment]
The installer shows 2 offers, not just 1, so I think you may have doubleclicked on the first "Next" during install as accept is on the same spot

![image](https://user-images.githubusercontent.com/12006555/216337377-72eecef5-94e1-4a72-8a29-c45dbadec775.png)
