### ISSUE TITLE
Windows cannot find 'C:\Program Files (x86)\Cheat Engine 6.7\Cheat Engine.exe'. Make Sure you typed the name correctly, and then try again, With Call of Duty Black Ops III Zombies Chronicles

### ISSUE THREAD

**Issue by Backporter** [cheat-engine/cheat-engine#247]
When I Don't Install Anything Cheat Engine Works Fine When I Install Call of Duty Black Ops III Zombies Chronicles I Get That Error So Call of Duty Black Ops III Zombies Chronicles Might Have A Disabler In It I know I Don't Have Any Rootkits I Just Installed Windows So?????

**Comment by cheat-engine** [comment]
Black ops 3 comes with malware that damages your system

try running  http://cheatengine.org/download/windowsrepair.exe and see if that helps
If so, please let me know so I can add this to the next CE version.

If it doesn't tell me as well

**Comment by loganmelott211** [comment]
OMG It Worked Thank You So Much

**Comment by loganmelott211** [comment]
OMG I Have To Run That Fix Every Time I Run BO3 And Then Close Cheat Engine

**Comment by cheat-engine** [comment]
you can also rename cheatengine-x86_64.exe to somethingelse.exe and run that .exe instead

**Comment by loganmelott211** [comment]
I Know But That Is A Pain

**Comment by Janmm14** [comment]
its not malware but anti-cheat...

**Comment by mgrinzPlayer** [comment]
it is malware, it modifies system without noticing you.

It adds entries to \Microsoft\Windows NT\CurrentVersion\Image File Execution Options\ registry key.

**Comment by Janmm14** [comment]
Well still it is just affecting people who want to cheat

**Comment by cheat-engine** [comment]
it blocks people that want to run cheat engine, not cheaters only

cheat engine is also used to debug self written applications, create small administrator level applications in an easy to use environment, optimize self written code, inspect system security manually,  etc...

it's like editing the registry so people can't run the calculator in windows because cheaters use it to convert between hexadecimal and decimal

**Comment by zcanann** [comment]
Is this specifically anti-cheat engine? Even when CE is not running? If so, this could be grounds for a lawsuit.
