### ISSUE TITLE
Can't build latest git version from source

### ISSUE THREAD

**Issue by podstanar0** [cheat-engine/cheat-engine#2471]
Fallowed main page build instructions, after installing Lazarus and opening **cheatengine.lpi** project, trying to build throws this error:

`MainUnit.pas(3630,30) Error: Incompatible types: got "EmptyWorkingSet(QWord):LongBool; StdCall;" expected "Int64"`

This is the code around it:

```
procedure TMainForm.miClearWorkingSetClick(Sender: TObject);
begin
  if assigned(EmptyWorkingSet) then
  begin
    if messagedlg(rsClearingMeansSlowness, mtInformation, [mbyes, mbno], 0)=
      mryes then
      EmptyWorkingSet(processhandle);
  end;
end;
```

**Comment by fade2gray** [comment]
Confirmed.

**Comment by podstanar0** [comment]
It's the latest commit: [182b0d5](https://github.com/cheat-engine/cheat-engine/commit/182b0d59e7271cfcf4f623961fdcaa69c5dc6faa)

**Comment by fade2gray** [comment]
Fixed with latest commits.
