### ISSUE TITLE
So, is there any way I can install the damn thing that DOESN'T involve the chance of installing adware and fake antiviruses?

### ISSUE THREAD

**Issue by CricetoYT** [cheat-engine/cheat-engine#2472]
I was looking at using this for some Metal Gear Rising mods that require it but if it involves risking getting my PC infected, no thanks.

**Comment by cheat-engine** [comment]
join the CE patreon and you can get a version without any adware

**Comment by cvionis** [comment]
You can also just follow the steps under "Basic Build Instructions" in the readme. Building from source removes the risk of installing any third-party software alongside Cheat Engine's files.

**Comment by CricetoYT** [comment]
> join the CE patreon and you can get a version without any adware

Excuse me? I have to pay just to get binaries without adware bundled in them? What the hell.

**Comment by zzitaiyo** [comment]
> join the CE patreon and you can get a version without any adware

nah, that's shitty from you. shame on you.
