### ISSUE TITLE
keeps throwing me this error, Iiterally dont know what to do..........

### ISSUE THREAD

**Issue by GabyS24** [cheat-engine/cheat-engine#2473]
![Captura de pantalla 2023-02-03 204537](https://user-images.githubusercontent.com/124414699/216742486-61708d9e-6320-499d-a3b1-c16ce0a39189.png)

**Comment by GabyS24** [comment]
i found that downloading lazarus 2.0.10 fixes everything XDDD im dumb lol, ignore this post for my own sake XD

**Comment by fade2gray** [comment]
Just an FYI, if you open the README.md file within the source that you downloaded, it will state in the build instructions which version of Lazarus to use.
