### ISSUE TITLE
Cant use on a linux flatpak

### ISSUE THREAD

**Issue by jon-bit** [cheat-engine/cheat-engine#2494]
I don't know why but when I run ceserver on Linux (where steam is installed by a flatpak) it "works" but I cant get my game to connect. I select the exe and it still does not find the values. (persona 5 royal BTW)

here is an out put of ceserver. 
```
&s=0x7ffcca0ce980
main=0x55a12660cb4b
sizeof(off_t)=8
sizeof(off64_t)=8
sizeof(uintptr_t)=8
sizeof(long)=8
CESERVERPATH=/home/jon/Downloads/ceserver75/
MEMORY_SEARCH_OPTION=2
ATTACH_TO_ACCESS_MEMORY=0
ATTACH_TO_WRITE_MEMORY=1
process_vm_readv==NULL, so MEMORY_SEARCH_OPTION can not be 2. Setting it to 0
MEMORY_SEARCH_OPTION=0
CEServer. Waiting for client connection
IdentifierThread active
socket=3
IdentifierThread: setting SO_BROADCAST returned 0
successfully bound socket
Listening success
IdentifierThread: Calling recvfrom size 6
accept=5
CMD_GETARCHITECTURE
(0)=255
OpenProcess(27342)
Opening memory access
Getting processdata for TH32CS_SNAPFIRSTMODULE
Creating module list for process 27342
Adding /home/jon/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Proton - Experimental/files/bin/wine64 as a module
The opened process is 64-bit
processhandle=1
CMD_GETARCHITECTURE
(1)=1
accept=6
handleGetOptions
Error: recv returned 0
Peer has disconnected
accept=8
Error: recv returned 0
Peer has disconnected
```

I guess it's also worth mentioning every time I select the process I get
```
CMD_GETARCHITECTURE
(0)=255
OpenProcess(27342)
Opening memory access
Getting processdata for TH32CS_SNAPFIRSTMODULE
Creating module list for process 27342
Adding /home/jon/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Proton - Experimental/files/bin/wine64 as a module
The opened process is 64-bit
processhandle=1
CMD_GETARCHITECTURE
(1)=1
accept=6
handleGetOptions
Error: recv returned 0
Peer has disconnected
accept=8
Error: recv returned 0
Peer has disconnected
```

I'm trying to figure this out but it is not easy and I'm kinda new to this tool (and yes I know I'm on Linux so their is no native support) but I hope someone can help me. Thanks in advance :)

**Comment by jon-bit** [comment]
Oh also here is the cheat table I'm using https://fearlessrevolution.com/viewtopic.php?t=21800

**Comment by cheat-engine** [comment]
no need for ceserver here. just launch cheat engine in the same proton environment as this game under the same appid

**Comment by jon-bit** [comment]
Sorry but as I have said I'm new to this. How would I do that on a flatpak? I'm honestly not to sure.

**Comment by jon-bit** [comment]
I just killed ceserver and don't see any processes.

**Comment by cheat-engine** [comment]
Try https://cheatengine.org/download/CEProtonLauncher.zip  (extract and execute it as a binary)
copy the cheat engine install folder to your linux home, and configure the path to the CE exe

You may miss a few dependencies. Do you know how to install those ?

**Comment by jon-bit** [comment]
I know how to install packages on linux. I don't know what they are however. Are they all available for fedora (and what are they)?

**Comment by jon-bit** [comment]
I think I got ir working but on the fact I'm using a flatpak what is the "Steam Folder"

**Comment by jon-bit** [comment]
OK never mind I found it, Now how do I select the process?

**Comment by cheat-engine** [comment]
select p5r.exe

**Comment by cheat-engine** [comment]
did you launch CE using the proton launcher and the persona 5 game icon launch button ?

**Comment by jon-bit** [comment]
Yes I did but I don't see P5R.exe

**Comment by cheat-engine** [comment]
are you in the process list?  So not application or window list

and is the game running?

**Comment by jon-bit** [comment]
Yes I don not see it in the proccess list and it is 100% running.

**Comment by jon-bit** [comment]
O just rebooted and not it won't even launch cheat engine

**Comment by jon-bit** [comment]
Never mine I have no clue what I did but it is starting cheat engine now (but I still don't see "P5R.exe")

**Comment by VoiDZaCk** [comment]
> Try https://cheatengine.org/download/CEProtonLauncher.zip (extract and execute it as a binary) copy the cheat engine install folder to your linux home, and configure the path to the CE exe
> 
> You may miss a few dependencies. Do you know how to install those ?

im new about this..sorry.. already try a few way to run ce in steam deck..but the ce open n the game didnt run...

can teach me how to get the correct way to make it work...thx

**Comment by cheat-engine** [comment]
first launch the game
then run and configure CEprotonlauncher (configure the propet steampath and ce path)

the running game logo should appear with a launch button

clicking that should start CE in the same environment as the game

**Comment by VoiDZaCk** [comment]
I'm sorry coz I didn't know how to configure it...

I download the file then unzip it ...

Then double click...
Some window pop up...
Dolphin
What do u wish to do with this file?
Execute or cancel

Any idea how to hook it direct to protonup-qt?

**Comment by C0rn3j** [comment]
I can't figure out how to get this running either, but for me the detection part is what fails.

I run flatpak version of Steam on Arch Linux, freshly downloaded CEProtonLauncher pointed to a CE 7.5 installer EXE.

Tried with two different Windows-only games, neither shows up.

![image](https://github.com/cheat-engine/cheat-engine/assets/1641362/68882b63-b3a2-46b5-b14d-3ed1d8c16315)

**Comment by Legion495** [comment]
I have the same issue on Fedora on native Steam.
But I use a different hard drive for all Steamgames and Proton versions.
The game is not detected.

**Comment by jon-bit** [comment]
I'm now having the same problem as @C0rn3j . I have made the switch to mint and is now dping the same thing.

**Comment by RomeuG** [comment]
I have the same issue as @Legion495

**Comment by jon-bit** [comment]
I don't know if this is the "PERFECT" approach I used this tool:

https://github.com/89luca89/distrobox 

and then used this tool with a arch box:

https://github.com/jcnils/protonhax

And it worked OK(with wine). If anyone thinks it as good as it will get let me know.

**Comment by jon-bit** [comment]
I'm going to close this because I found #2725 and it is super easy to use. If you think I should reopen let me know but at the time this is to easy (even on flatpak). Regardless thank you everyone who tried to help in the past year(ish) and happy holidays :-D
