### ISSUE TITLE
dbvm compile error

### ISSUE THREAD

**Issue by avboy1337** [cheat-engine/cheat-engine#2497]
```
ld: ./distorm64/distorm.o:/media/avboy/bak/cheat-engine/dbvm/vmm/distorm64/../common.h:332: multiple definition of `currentdisplayline'; main.o:/media/avboy/bak/cheat-engine/dbvm/vmm/common.h:332: first defined here
ld: ./distorm64/distorm.o:/media/avboy/bak/cheat-engine/dbvm/vmm/distorm64/../common.h:333: multiple definition of `currentdisplayrow'; main.o:/media/avboy/bak/cheat-engine/dbvm/vmm/common.h:333: first defined here
ld: ./distorm64/distorm.o:/media/avboy/bak/cheat-engine/dbvm/vmm/distorm64/../common.h:710: multiple definition of `errno'; main.o:/media/avboy/bak/cheat-engine/dbvm/vmm/common.h:710: first defined here
make[1]: *** [mkx:72: all] Error 1
make[1]: Leaving directory '/media/avboy/bak/cheat-engine/dbvm/vmm'
make: *** [Makefile:17: all] Error 2

```

**Comment by fade2gray** [comment]
Compiles for me using Ubuntu server 18.04.6 LTS.

**Comment by AitNev** [comment]
Ive tried in ArchLinux and Ubuntu desktop 22.04.2 LTS in both gave that same error on that Ubuntu server 18.04.6 LTS it did work.

For new people  using a virtual machine a git clone using http on this repository will transfer the files for the compilation
For transferring the image back to windows you just need to find your ubuntu server ip and from the windows powershell you can use this command
scp ubuntu@<Ubuntu Server IP>:<Path to .../vmdisk.img> C:\Users\Your-username\Desktop\

**Comment by NorthShad0w** [comment]
For those people want to compile it using the latest linux machine.

modify the `/dbvm/vmm/mkx` file 

```
6   LDFLAGS = -static -z muldefs --no-warn-rwx-segments  -T vmm.lnk -Map vmm.map 
```

**Comment by uniquadev** [comment]
Brief introduction to compile dbvm 17
### Setup
```sh
sudo apt install yasm nasm genisoimage rar
```
### Update
1  `cheat-engine/dbvm/vmm/mkx`
```
...
6 LDFLAGS = -static -z muldefs --no-warn-rwx-segments  -T vmm.lnk -Map vmm.map
...
```
2. `cheat-engine/dbvm/vmloader/Makefile`
```
...
5  LDFLAGS = -z muldefs --no-warn-rwx-segments -T kernel.lnk
...
```
### Compile 
`make clean; make release`

> TESTED on Ubuntu 24.10
