### ISSUE TITLE
compile error enumSymbolsFromFile

### ISSUE THREAD

**Issue by qwer0123456** [cheat-engine/cheat-engine#2506]
symbolhandler.pas(2968,103) Error: Wrong number of parameters specified for call to "enumSymbolsFromFile"
networkInterface.pas(2003,24) Error: Found declaration: enumSymbolsFromFile(AnsiString;QWord;TNetworkEnumSymCallback):Boolean;

latest source enumSymbolsFromFile function build error

**Comment by fade2gray** [comment]
https://github.com/cheat-engine/cheat-engine/commit/3d972a4e98ad7a69cb1b78a52907ccb6015fd440

```
Compile Project, Mode: Release 64-Bit, Target: bin\cheatengine-x86_64.exe: Exit code 1, Errors: 2, Warnings: 25
symbolhandler.pas(2968,103) Error: Wrong number of parameters specified for call to "enumSymbolsFromFile"
networkInterface.pas(2003,24) Error: Found declaration: enumSymbolsFromFile(AnsiString;QWord;TNetworkEnumSymCallback):Boolean;
```

```
Compile Project, Mode: Release 64-Bit O4 AVX2, Target: bin\cheatengine-x86_64-SSE4-AVX2.exe: Exit code 1, Errors: 1
guisafecriticalsection.pas(66,107) Error: Identifier not found "GetThreadName"
```

```
Compile Project, Mode: Release 32-Bit, OS: win32, CPU: i386, Target: bin\cheatengine-i386.exe: Exit code 1, Errors: 1
guisafecriticalsection.pas(66,107) Error: Identifier not found "GetThreadName"
```

**Comment by Localhost2011** [comment]
so what is the solution to this problem?? 
`guisafecriticalsection.pas(66,107) Error: Identifier not found "GetThreadName"`

**Comment by fade2gray** [comment]
@Localhost2011
Until @cheat-engine fixes it, as a workaround, undo the changes made to `guisafecriticalsection.pas`.
https://github.com/cheat-engine/cheat-engine/commit/cde81cf17b3412d041d2be0e7d67a4e5c519f77c#diff-bcc2e0cd3f398129757dbac2e0a3383c0146809dfa3f232fa9c322490ac62133
