### ISSUE TITLE
MonoDataCollector dll build error

### ISSUE THREAD

**Issue by qwer0123456** [cheat-engine/cheat-engine#2507]
LNK2019	"public: __thiscall CMemStream::~CMemStream(void)" (??1CMemStream@@QAE@XZ)"private: void __thiscall CPipeServer::EnumClassesInImageEx(void)" (?EnumClassesInImageEx@CPipeServer@@AAEXXZ) Unresolved external symbol referenced in a function	MonoDataCollector	C:\Users\Administrator\Desktop\cheat-engine-master (4)\cheat-engine-master\Cheat Engine\MonoDataCollector\MonoDataCollector\PipeServer.obj	1	
LNK2019	"public: unsigned int __thiscall CMemStream::GetSize(void)" (?GetSize@CMemStream@@QAEIXZ)"private: void __thiscall CPipeServer::EnumClassesInImageEx(void)" (?EnumClassesInImageEx@CPipeServer@@AAEXXZ) Unresolved external symbol referenced in a function	MonoDataCollector	C:\Users\Administrator\Desktop\cheat-engine-master (4)\cheat-engine-master\Cheat Engine\MonoDataCollector\MonoDataCollector\PipeServer.obj	1	
LNK2019	"public: void * __thiscall CMemStream::GetMemory(void)" (?GetMemory@CMemStream@@QAEPAXXZ)"private: void __thiscall CPipeServer::EnumClassesInImageEx(void)" (?EnumClassesInImageEx@CPipeServer@@AAEXXZ) Unresolved external symbol referenced in a function	MonoDataCollector	C:\Users\Administrator\Desktop\cheat-engine-master (4)\cheat-engine-master\Cheat Engine\MonoDataCollector\MonoDataCollector\PipeServer.obj	1	
LNK2019	"public: void __thiscall CMemStream::Write(void *,unsigned int)" (?Write@CMemStream@@QAEXPAXI@Z)"private: void __thiscall CPipeServer::EnumClassesInImageEx(void)" (?EnumClassesInImageEx@CPipeServer@@AAEXXZ) Unresolved external symbol referenced in a function	MonoDataCollector	C:\Users\Administrator\Desktop\cheat-engine-master (4)\cheat-engine-master\Cheat Engine\MonoDataCollector\MonoDataCollector\PipeServer.obj	1	
LNK2019	"public: void __thiscall CMemStream::WriteDword(unsigned long)" (?WriteDword@CMemStream@@QAEXK@Z)"private: void __thiscall CPipeServer::EnumClassesInImageEx(void)" (?EnumClassesInImageEx@CPipeServer@@AAEXXZ) Unresolved external symbol referenced in a function	MonoDataCollector	C:\Users\Administrator\Desktop\cheat-engine-master (4)\cheat-engine-master\Cheat Engine\MonoDataCollector\MonoDataCollector\PipeServer.obj	1	
LNK2019	"public: void __thiscall CMemStream::WriteQword(unsigned __int64)" (?WriteQword@CMemStream@@QAEX_K@Z)"private: void __thiscall CPipeServer::EnumClassesInImageEx(void)" (?EnumClassesInImageEx@CPipeServer@@AAEXXZ) Unresolved external symbol referenced in a function	MonoDataCollector	C:\Users\Administrator\Desktop\cheat-engine-master (4)\cheat-engine-master\Cheat Engine\MonoDataCollector\MonoDataCollector\PipeServer.obj	1	
LNK2019	"public: void __thiscall CMemStream::WriteWord(unsigned short)" (?WriteWord@CMemStream@@QAEXG@Z)"private: void __thiscall CPipeServer::EnumClassesInImageEx(void)" (?EnumClassesInImageEx@CPipeServer@@AAEXXZ) Unresolved external symbol referenced in a function	MonoDataCollector	C:\Users\Administrator\Desktop\cheat-engine-master (4)\cheat-engine-master\Cheat Engine\MonoDataCollector\MonoDataCollector\PipeServer.obj	1	
LNK2019	"public: __thiscall CMemStream::CMemStream(void)" (??0CMemStream@@QAE@XZ)"private: void __thiscall CPipeServer::EnumClassesInImageEx(void)" (?EnumClassesInImageEx@CPipeServer@@AAEXXZ) Unresolved external symbol referenced in a function	MonoDataCollector	C:\Users\Administrator\Desktop\cheat-engine-master (4)\cheat-engine-master\Cheat Engine\MonoDataCollector\MonoDataCollector\PipeServer.obj	1	

Unreferenced link error when building with Visual Studio 2022 
(LNK2019 ERROR)

**Comment by fade2gray** [comment]
@qwer0123456 How did you resolve this?
