### ISSUE TITLE
ExAllocatePool  Compilation error C4996 in build DBKKernel

### ISSUE THREAD

**Issue by SuFIND** [cheat-engine/cheat-engine#2508]
When I try to build solution for DBKKernel, I got the error like:
![image](https://user-images.githubusercontent.com/30424839/224318695-baebbae0-92ac-404b-84c4-23c6ed8b6d01.png)

search in google. I got the [page](https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/updating-deprecated-exallocatepool-calls).
Doc said the ExAllocatePool has been replace by ExAllocatePool2. And I try. But it's got the other error "ExAllocatePool2|“ return int.
How can I do it?

**Comment by SuFIND** [comment]
Using building method "release with release with no sig" can solve it.

**Comment by victor20010** [comment]
[CODE]1>------ Сбо ка начата: п оект: DBKKernel, Конфигу ация: Release without sig x64 ------
1>Building 'DBKKernel' with toolset 'WindowsKernelModeDriver10.0' and the 'Desktop' target platform.
1>Stamping x64\Releasewithoutsig\DBK64.inf
1>Stamping [Version] section with DriverVer=08/22/2023,18.22.1.436
1>C:\Users\Админист ато \Downloads\DBKKernel\DBK64.inf(5-5): warning 1324: [Version] section should specify PnpLockdown=1 to prevent external apps from modifying installed driver files.
1>DBKDrvr.c
1>C:\Users\Админист ато \Downloads\DBKKernel\DBKDrvr.c(222,22): error C2220: следующее п едуп еждение  ассмат ивается как ошибка
1>C:\Users\Админист ато \Downloads\DBKKernel\DBKDrvr.c(222,22): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\DBKDrvr.c(223,22): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\DBKDrvr.c(224,28): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\DBKDrvr.c(225,27): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>DBKFunc.c
1>C:\Users\Админист ато \Downloads\DBKKernel\DBKFunc.c(103,8): error C2220: следующее п едуп еждение  ассмат ивается как ошибка
1>C:\Users\Админист ато \Downloads\DBKKernel\DBKFunc.c(103,8): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\DBKFunc.c(137,6): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\DBKFunc.c(197,8): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>debugger.c
1>C:\Users\Админист ато \Downloads\DBKKernel\debugger.c(208,25): error C2220: следующее п едуп еждение  ассмат ивается как ошибка
1>C:\Users\Админист ато \Downloads\DBKKernel\debugger.c(208,25): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\debugger.c(214,28): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\debugger.c(251,29): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\debugger.c(260,33): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>deepkernel.c
1>interruptHook.c
1>IOPLDispatcher.c
1>C:\Users\Админист ато \Downloads\DBKKernel\IOPLDispatcher.c(93,9): error C2220: следующее п едуп еждение  ассмат ивается как ошибка
1>C:\Users\Админист ато \Downloads\DBKKernel\IOPLDispatcher.c(93,9): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\IOPLDispatcher.c(138,9): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\IOPLDispatcher.c(287,9): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\IOPLDispatcher.c(1308,13): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\IOPLDispatcher.c(2458,11): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\IOPLDispatcher.c(2461,18): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>memscan.c
1>C:\Users\Админист ато \Downloads\DBKKernel\memscan.c(813,8): error C2220: следующее п едуп еждение  ассмат ивается как ошибка
1>C:\Users\Админист ато \Downloads\DBKKernel\memscan.c(813,8): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>noexceptions.c
1>C:\Users\Админист ато \Downloads\DBKKernel\noexceptions.c(48,15): error C2220: следующее п едуп еждение  ассмат ивается как ошибка
1>C:\Users\Админист ато \Downloads\DBKKernel\noexceptions.c(48,15): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\noexceptions.c(55,42): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>processlist.c
1>C:\Users\Админист ато \Downloads\DBKKernel\processlist.c(34,10): error C2220: следующее п едуп еждение  ассмат ивается как ошибка
1>C:\Users\Админист ато \Downloads\DBKKernel\processlist.c(34,10): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\processlist.c(199,28): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\processlist.c(274,25): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>threads.c
1>ultimap.c
1>C:\Users\Админист ато \Downloads\DBKKernel\ultimap.c(148,13): error C2220: следующее п едуп еждение  ассмат ивается как ошибка
1>C:\Users\Админист ато \Downloads\DBKKernel\ultimap.c(148,13): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\ultimap.c(254,8): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\ultimap.c(521,20): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\ultimap.c(696,12): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\ultimap.c(697,23): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>ultimap2.c
1>C:\Users\Админист ато \Downloads\DBKKernel\ultimap2.c(198,15): error C2220: следующее п едуп еждение  ассмат ивается как ошибка
1>C:\Users\Админист ато \Downloads\DBKKernel\ultimap2.c(198,15): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\ultimap2.c(1003,9): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\ultimap2.c(1154,7): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\ultimap2.c(1169,19): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\ultimap2.c(1176,7): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\ultimap2.c(1189,6): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\ultimap2.c(1377,20): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\ultimap2.c(1459,10): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\ultimap2.c(1460,23): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\ultimap2.c(1476,14): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>apic.c
1>vmxhelper.c
1>C:\Users\Админист ато \Downloads\DBKKernel\vmxhelper.c(712,32): error C2220: следующее п едуп еждение  ассмат ивается как ошибка
1>C:\Users\Админист ато \Downloads\DBKKernel\vmxhelper.c(712,32): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>vmxoffload.c
1>C:\Users\Админист ато \Downloads\DBKKernel\vmxoffload.c(520,29): error C2220: следующее п едуп еждение  ассмат ивается как ошибка
1>C:\Users\Админист ато \Downloads\DBKKernel\vmxoffload.c(520,29): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\vmxoffload.c(625,22): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\vmxoffload.c(979,28): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.
1>C:\Users\Админист ато \Downloads\DBKKernel\vmxoffload.c(985,14): warning C4996: 'ExAllocatePool': ExAllocatePool is deprecated, use ExAllocatePool2.[/CODE]
some one soloved??  tryed Release without sig , Release , 10.0.19041.0  , 10.0.22000.0, sdk/wdk almos all wdk sdk [IMG]https://i.imgur.com/WVKoA65.png[/IMG]

**Comment by cheat-engine** [comment]
use an older development kit, or do as it says, use ExAllocatePool2
