### ISSUE TITLE
Cheat Engine not open error .dll file how to fix ?

### ISSUE THREAD

**Issue by F5LAYD** [cheat-engine/cheat-engine#2510]
![tnXlapv9Fo](https://user-images.githubusercontent.com/73395630/224547691-c9637d95-df76-457f-afa8-b0b09fc9275d.png)

**Comment by F5LAYD** [comment]
Cheat Engine stopped working after update...

**Comment by F5LAYD** [comment]
Cheat Engine stopped working after update...

**Comment by fade2gray** [comment]
Try Google [search](https://www.google.co.uk/search?q=api-ms-win-downlevel-kernel32-l2-1-0.dll+location&newwindow=1&source=hp&ei=yNgNZNafFYaFhbIP6-yOoAk&iflsig=AK50M_UAAAAAZA3m2FabT5eQspAYW70KICUuDlmSfVD6&oq=api-ms-win-downlevel&gs_lcp=Cgdnd3Mtd2l6EAEYAzIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQ6EQguEIAEELEDEIMBEMcBENEDOgsIABCABBCxAxCDAToUCC4QgAQQsQMQgwEQxwEQ0QMQ1AI6CwguEIAEELEDEIMBOhEILhDHARDUAhCxAxDRAxCABDoICAAQgAQQsQM6CAguELEDEIMBOgUILhCABDoICAAQsQMQgwFQAFj1U2D7zwFoAHAAeACAAWOIAZkMkgECMjCYAQCgAQE&sclient=gws-wiz)

**Comment by cheat-engine** [comment]
delete dbghelp32.dll from the win64 folder
