### ISSUE TITLE
Font alignment optimization

### ISSUE THREAD

**Issue by avboy1337** [cheat-engine/cheat-engine#2511]
The fonts in disassembly have been aligned, can the fonts in the memory view interface also be set to be the same as in disassembly? In Ubuntu, the fonts in disassembly are aligned, but the numbers in the memory view are not aligned. CE can run perfectly with wine, which is really comfortable! As shown in the figure below:

![image](https://user-images.githubusercontent.com/5463104/224914421-24a241b8-99fe-461d-94ba-0bc65558e58a.png)

**Comment by cheat-engine** [comment]
I don't think the disassrmbler fonts are aligned either

**Comment by fade2gray** [comment]
![224914421-24a241b8-99fe-461d-94ba-0bc65558e58a](https://user-images.githubusercontent.com/1332009/224992180-54c97fbe-8c9d-4bbc-b6a8-bf6d5cc5a0cd.png)

**Comment by cheat-engine** [comment]
anyhow,  go to memview->view->preferences, and click on the hexview font, and pick one of the fonts that are there.  It should only show monotype fonts

**Comment by avboy1337** [comment]
> anyhow, go to memview->view->preferences, and click on the hexview font, and pick one of the fonts that are there. It should only show monotype fonts which should fix all alignment issues (assuming wine implements that)

OK, thanks a lot!!

**Comment by avboy1337** [comment]
> ![224914421-24a241b8-99fe-461d-94ba-0bc65558e58a](https://user-images.githubusercontent.com/1332009/224992180-54c97fbe-8c9d-4bbc-b6a8-bf6d5cc5a0cd.png)

You are really meticulous/careful!
