### ISSUE TITLE
latest ce conect to ceserver, after open process , error will occured.

### ISSUE THREAD

**Issue by avboy1337** [cheat-engine/cheat-engine#2519]
Peer has disconnected
CMD_GETSYMBOLLISTFROMFILE with fileoffset=2c000
symbolpath=/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2.1
GetSymbolListFromFile(/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2.1, 2c000)
Segmentation fault

**Comment by cheat-engine** [comment]
upload a full /proc/<pid>/maps and the file /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2.1
