### ISSUE TITLE
"The program can't start because

### ISSUE THREAD

**Issue by 60fpshacksrock** [cheat-engine/cheat-engine#2540]
api-ms-win-downlevel-kernel32-l2-1-0.dll is missing from your
computer. Try reinstalling the program to fix this problem."

I finally got it to install properly without the other joke files but now I get this above.

**Comment by cheat-engine** [comment]
delete the dbghelp dll in the win64 folder

**Comment by 60fpshacksrock** [comment]
Windows 7 x64.

Thanks again.

**Comment by Theo1996** [comment]
Same issue on win 7 thx
