### ISSUE TITLE
ceserver ndk compile error

### ISSUE THREAD

**Issue by avboy1337** [cheat-engine/cheat-engine#2548]
is it the reason I used ubuntu22?

3 warnings generated.
[x86] Compile        : ceserver <= extensionfunctions.c
[x86] Compile        : ceserver <= extensionloader.c
/home/xxxxx/Desktop/cheat-engine/ceserver/ndk-build/SHARED_LIBRARY/jni/../../../extensionloader.c:774:48: error: no member named 'rsp' in 'struct user_regs_struct'; did you mean 'esp'?
      if (ptrace(PTRACE_POKEDATA, pid, newregs.rsp+12, p->dlopencaller)!=0)

**Comment by ascorbic-acid** [comment]
how did you solve this, will be any effect if we just change rsp to esp

**Comment by cheat-engine** [comment]
i havn't tested x86 as that's becomming a rarity, but yeah, i figure rsp to esp should work
