### ISSUE TITLE
Cheat Engine running in Background

### ISSUE THREAD

**Issue by GTAGTAGTAGAming** [cheat-engine/cheat-engine#2552]
when i compiled my ce it ran on the background on my pc but ran completely fine on my laptop
![Screenshot (6)](https://user-images.githubusercontent.com/130921550/232326657-801d30f3-5a56-41e8-b052-43308f7ba6f0.png)

**Comment by GTAGTAGTAGAming** [comment]
Please Help

**Comment by cheat-engine** [comment]
check your anti virus 
and delete the .dbg files

**Comment by GTAGTAGTAGAming** [comment]
i have no anti-virus and now it is just not opening at all

**Comment by cheat-engine** [comment]
execute ceregreset and see if that makes a difference

**Comment by GTAGTAGTAGAming** [comment]
there is no ceregreset.exe

**Comment by fade2gray** [comment]
> there is no ceregreset.exe

You won't see it if you didn't compile the ceregreset executable - you'll need to delete this from your registry `HKEY_CURRENT_USER\SOFTWARE\Cheat Engine`

**Comment by GTAGTAGTAGAming** [comment]
thanks done
