### ISSUE TITLE
CE 7.5 is dangerous!!!

### ISSUE THREAD

**Issue by LEnumaT** [cheat-engine/cheat-engine#2564]
so despite all warning I installed CE 7.5 (and yes I declined both AVG and MC or whatever they called during installation process) and still got infected, immediately after installation on first run of CE, some files from my system32 were infected and started to stand out like, eating insane amount of CPU's (10-20% per system process P.S most of them didn't go above 1% before) and that is insane for high end PC... 

So if anyone else were wondering if this is safe it is definitely not...

Dev's of Cheat Engine have no shame and shouldn't be trusted...

And now Thanks to them, I have to do full OS reinstall/Factory reset on my PC...

**Comment by cheat-engine** [comment]
Yeah no. you likely got something else or more likely your anti virus is just acting up and making all the processes it's hooked into eat cpu power while it's inspecting CE's behaviour

**Comment by MasterMarius** [comment]
Could I compile the master.zip file and obtain a portable version of it? 
How to do it?

**Comment by ANTONIOPSD** [comment]
Here's the link to the full installer captured from the crappy downloader:

https://d2oq4dwfbh6gxl.cloudfront.net/f/CheatEngine/1032/CheatEngine75.exe

**Comment by MasterMarius** [comment]
Thanks, works great!

**Comment by XBOX360VERSUCHONE** [comment]
MasterMarius ***@***.***> schrieb am Mi., 3. Mai 2023, 10:46:
