### ISSUE TITLE
 Is it possible to use write access in ceserver for android?

### ISSUE THREAD

**Issue by WithoutCoffeeBr** [cheat-engine/cheat-engine#2569]
I would really like to use the write access option for android in the arm architecture, but for some reason the game crashes. I would like to know if the Cheat Engine can get the register values.

**Comment by cheat-engine** [comment]
It's possible yes. but the game must not have anti ptrace code as that is needed for write access

**Comment by cheat-engine** [comment]
it's possible but use android 9 or later

**Comment by WithoutCoffeeBr** [comment]
I'm trying it on the emulator with libceserver.so included in the apk.
I still researched and saw that it doesn't work very well in an emulator.

**Comment by WithoutCoffeeBr** [comment]
Every time I get a message saying that the debuggers are exhausted.

**Comment by cheat-engine** [comment]
androids like nox and bluestacks aren't arm, they are x86, so you'll need to use the x86 ceserver  
Also, use the 7.5 ceserver and ce client

(And as mentioned, android 9, the default of bluestacks and nox are 7, but there are configs with 9)
