### ISSUE TITLE
Malware

### ISSUE THREAD

**Issue by Haxnstuff** [cheat-engine/cheat-engine#2579]
This is a virus...

The file contains spyware, malware, adware and probably others as well, I'm still gonna use it cus I don't really care if someone watches me play Banana Shooter, but I still wanna let everyone know.

**Comment by cu-m** [comment]
It's not, the source code is right there. If anything its the ads in the installer (at least the old installer, idk if the newer ones have ads) that gave u spyware.

**Comment by Banaanae** [comment]
If you're on windows go to `Add or Remove Programs` and delete any of the unwanted programs the installer downloaded downloaded

If you update it make sure in the installer you press decline or untick the the box saying press next will download this

**Comment by Username69992872** [comment]
you should not partner up with ads delivering malware. There always are people who missclick. Cheatengine builds on people trusting it.

**Comment by Dijosto** [comment]
They're not.

**Comment by Banaanae** [comment]
> you should not partner up with ads delivering malware. There always are people who missclick. Cheatengine builds on people trusting it.

Once again if misclicking is a problem you can always build from the source, it's right here and there's instructions on the readme
