### ISSUE TITLE
Is there a way to use this on linux?

### ISSUE THREAD

**Issue by lhwe** [cheat-engine/cheat-engine#2580]
Specifically debian. I just dont want to have to find another since CE works so well. but ig it prob doesnt work the same as windows CE, so that may be it. If anyone has alternatives for linux, please tell me.

**Comment by Banaanae** [comment]
You will need to build it yourself
Maybe [this](https://wiki.debian.org/HowToPackageForDebian) helps (not sure if it works with pascal + I don't use linux very often)
If you can't anything [PINCE](https://github.com/korcankaraokcu/PINCE) might work

**Comment by avboy1337** [comment]
use wine and ceserver
in linux ceserver and cheatengine works well

**Comment by Gvaz** [comment]
Can someone explain it like I'm 5?

Basically what do I copypaste in terminal to set up the above

thanks

**Comment by lhwe** [comment]
thank you all, got it working. forgot to thank you!
