### ISSUE TITLE
CE closes itself when I click on the "select a process to open" icon

### ISSUE THREAD

**Issue by Zodiarche** [cheat-engine/cheat-engine#2591]
It's all in the title, and I've tried several things on the net, nothing has changed, I'm on the latest public version.

**Comment by PollutionPotential** [comment]
Did you compile vehdebug?
You'll need the debugger available to CE if you use it as a debugger.
Just tried it on AM2R, with CheatEngine {Github} [18f93c5] (2023-05-19), and it worked fine.

**Comment by cheat-engine** [comment]
CE still shouldn't close itself.
This is more likely an anti virus bugging out or malware trying to protect itself

**Comment by Zodiarche** [comment]
To try to write how I got around

So, with version 7.5, I have the above problem

So I downloaded version 7.3, and this time I had the access violation problem, but I was still able to change what I wanted

But I'd rather have no problems and be on the latest version

**Comment by fade2gray** [comment]
@Zodiarche 
I asked ChatGPT for you.
<details>

<summary>Click here to read ChatGPT's reply</summary>

If Cheat Engine closes itself when you try to select a process to open, it is possible that the game or application you are trying to target with Cheat Engine has implemented some form of protection to prevent cheating. Some games employ various anti-cheat measures to detect and block cheating tools like Cheat Engine.

Here are a few possible reasons why Cheat Engine is closing itself:

1. Anticheat Software: The game or application you are trying to target may have an anticheat system installed. These anticheat systems actively monitor running processes and can detect and block known cheating tools like Cheat Engine. If the game has a strong anticheat system in place, Cheat Engine may automatically close to prevent it from being used.

2. Administrative Privileges: Cheat Engine requires administrative privileges to access and modify the memory of other processes. If you are running Cheat Engine without administrative privileges, it may close itself when you try to select a process to open. Try running Cheat Engine as an administrator by right-clicking the Cheat Engine executable and selecting "Run as administrator" from the context menu.

3. Compatibility Issues: Cheat Engine may encounter compatibility issues with certain games or applications. Make sure you are using the latest version of Cheat Engine and check the Cheat Engine forums or website for any known compatibility issues or workarounds specific to the game or application you are targeting.

4. Detection by the Game/Application: Some games or applications have built-in mechanisms to detect Cheat Engine or similar tools. They may actively scan for Cheat Engine's presence and close it automatically to prevent cheating. In such cases, it may be difficult to use Cheat Engine with that specific game or application.

If Cheat Engine continues to close itself despite trying the above solutions, it is likely that the game or application you are trying to modify has implemented strong protection measures against cheating, making it challenging to use Cheat Engine. Keep in mind that using cheating tools can violate the terms of service of games and applications, potentially leading to penalties or account suspensions. It is important to respect the rules and guidelines set by game developers and application providers.

</details>

**Comment by Zodiarche** [comment]
Since it "works" via a previous version, I don't think it's from an anti-cheat, especially since I only have Vanguard and it's disabled outside Valorant. But I am also concerned about the issue of Violation.

For the administrator rights, well, it's my personal computer so it would be surprising, especially since at the time (1/2 years) I had no problem

And for the last two points, well, since 7.3 works I guess it's not that either :(

**Comment by fade2gray** [comment]
Well, I have no issues with the current 7.5 release on Windows 10 with Windows Defender.

You say Vanguard is disabled, but maybe you could check to see if the kernel mode driver has been disabled.

From a command prompt, enter `sc query type= driver | findstr -i vgk` and `sc query type= driver | findstr -i vanguard`, if you see a result for either, it's likely not to be completely disabled.

**Comment by Zodiarche** [comment]
> Could compile the debug build and see what is causing the issue

Sorry, what I have to do exactly ?

**Comment by PollutionPotential** [comment]
Open Cheatengine.lpi
That should open it in Lazarus
In the top menu, you'll see Run
Compile many modes
Select Debug 64 bit, and debug 32 bit.
Run the debug build and it should make a log of the issue which may better help the Dev "Dark Byte" help solve the issue.

**Comment by fade2gray** [comment]
@PollutionPotential 
![Capture](https://github.com/cheat-engine/cheat-engine/assets/1332009/db910d16-3407-4f75-9cad-8374e216f307)

**Comment by PollutionPotential** [comment]
Yes, a false positive.
Extracted
[x64.exe](https://www.virustotal.com/gui/file/f6d55854c94f4886513242dcac317348fb12e38c5f1be5b6329a9fac14cd555d)
[x64.dbg](https://www.virustotal.com/gui/file/fa3847e323189bd0e9fba42f0a7c74c00774eb0a8d0c62dbda1d284d41a566b3)
[i386.dbg](https://www.virustotal.com/gui/file/21e5b8d2343c24310e138544d82dddf46b68001ee19fadf1efe1e14303dd8bdf)
[i386.exe](https://www.virustotal.com/gui/file/c1561afb13e5e9f755026d7af05b64e0a505038b6fc05a1e136d338f6a377d5e)
So, it has a problem with the 32bit exe.
