### ISSUE TITLE
Issue with Cheatengine72.exe being filed as "dangerous" by Windows Security.

### ISSUE THREAD

**Issue by JoeBambaIsTaken** [cheat-engine/cheat-engine#2594]
Hi!

I have a friend who has had a problem starting from yesterday, where every game he would try to open would come with weird error messages like "Your graphics hardware does not support all features (CSM) needed to run this game)
He later found out that Windows Security has flagged a file named Cheatengine72.exe that does not exist on his computer as "dangerous". Now his PC is running really slow and both browser and low-end games like even Stumble Guys run at snail pace. Has anyone had this kind of issue before?

**Comment by cheat-engine** [comment]
windows security logging a file as dangerous is normal. A long time ago he might have downloaded CE7.2 and windows deleted it for him
That's what the log says. It's not a list of current things, but all the things it has seen

as for his issues, try reinstalling the graphics drivers

**Comment by JoeBambaIsTaken** [comment]
He already tried reinstalling drivers and it didn't work but we just came to the conclusion of resetting his pc. This has seemed to work and Windows is no longer pinning the file as dangerous 👍
