### ISSUE TITLE
Some optimization suggestions for mac Cheat Engine 7.4

### ISSUE THREAD

**Issue by LarissaLycoris** [cheat-engine/cheat-engine#2595]
I am using the 7.4 version of ce, the window version of the pointer scan, click the base address or offset0~6 can be sorted, as shown below. This page in the mac version cannot be sorted. This function is very useful. Can you update it to the ce function of the mac version, thank you!

![P)}R@VGN0OQPJ3RDI)@LOZ2](https://github.com/cheat-engine/cheat-engine/assets/99528736/c324fbd1-d464-43b5-a6e9-5ce08ddff44e)

**Comment by cheat-engine** [comment]
alright. i'll see about adding that

**Comment by LarissaLycoris** [comment]
> 好吧。我会考虑添加那个

Thank you, you can close the question

**Comment by LarissaLycoris** [comment]
Hello, are you considering adding the function for me to make suggestions? I recently discovered a new problem. When the blocksize setting in the group settings is greater than 100, ce will freeze and become unresponsive when searching. The default value of 50 is the least likely to cause problems. Is there any solution? The latest ce of mac version
