### ISSUE TITLE
help. how do i use cheat engine and not have it break my entire script i grabbed from nexus?

### ISSUE THREAD

**Issue by pancakes111213123432453254235** [cheat-engine/cheat-engine#2600]

**Comment by pancakes111213123432453254235** [comment]
at first it seemed to work fine, but after changing one thing the entire engine broke the script and is now completely broken. i have even gone ahead and reinstalled it and tried again with no success. this thing is utterly shit to even try to use as a beginner

**Comment by cheat-engine** [comment]
ask the script author
