### ISSUE TITLE
Downloading cheat-engine (not from here) gave me a malware named PUADIManager Win32/InstallCore

### ISSUE THREAD

**Issue by ShrekTheRealOne** [cheat-engine/cheat-engine#2606]
This was a long time ago, and the virus was deleted after i used Tron, im just wondering if cheat engine is really secure or did i just visit another fishy site.
PLEASE GIVE PROOF.

**Comment by ShrekTheRealOne** [comment]
Proof that cheat engine isnt actually any kind of ware (i've been told it is adware, spyware and malware)

**Comment by Dijosto** [comment]
Dont download anything from unofficial sites.

**Comment by cheat-engine** [comment]
The cheat engine soft**ware** is mostly free**ware** but the public installer does provide advertisements for third party soft**ware** so it is classified as ad**ware**

**Comment by ShrekTheRealOne** [comment]
> The cheat engine soft**ware** is mostly free**ware** but the public installer does provide declinable advertisements for third party soft**ware** so it is classified as ad**ware**
here's the scan result in virustotal, why is it marked as a trojan?
https://www.virustotal.com/gui/file/e2e15826b69778e381f25ac8f2b109a377b23f7cf79b5f482e81f4d28c30f95e

**Comment by ShrekTheRealOne** [comment]
@cheat-engine can you answer?

**Comment by cheat-engine** [comment]
It's not marked as a Trojan. It's marked as a pua/pup which is means  "potentially unwanted application/program"
notice the word potentially.  It means that if you read properly it won't do anything.  Only if you click next/accept without reading you will get the advertised software

anyhow, join the patreon and you'll get a 100% guaranteed PUP free download (I do not guarantee your AV will falsly detect it as such anyhow)

**Comment by ShrekTheRealOne** [comment]
@cheat-engine 
![image](https://github.com/cheat-engine/cheat-engine/assets/97811650/d1551aee-605e-48c7-84c2-75a45462f125)

**Comment by ShrekTheRealOne** [comment]
@Dijosto i downloaded it from the official website, cheatengine.org

**Comment by cheat-engine** [comment]
likely because some unknown av's like drweb and maxsecure that add that tag

but here's the patreon result: https://www.virustotal.com/gui/file/bc37bba7efe232feebe23a7152f8a7407e5f868e771a46bf67106e70f295cbc4/detection

**Comment by ShrekTheRealOne** [comment]
where's the patreon?

**Comment by cheat-engine** [comment]
https://www.patreon.com/cheatengine

**Comment by ShrekTheRealOne** [comment]
but whats the difference between downloading it from the patreon and from cheatengine.org or from here?

**Comment by cheat-engine** [comment]
The public one shows during install an advertised application,  and the patreon does not

**Comment by ShrekTheRealOne** [comment]
some guy just posted an issue abt still getting those apps even after declining them, u know anything abt that?
BTW why is ur tool always called a trojan, what did u do to make them claim that

**Comment by cheat-engine** [comment]
That person very likely doubleclicked the first next, or he got it from something else and assumes it was CE(Often people that find CE are looking for hacks, and before they find CE they try other hacks that do contain malware that AV's do not detect), or he's in denisl thst he did click accept (notice he mentions unchecking but there are no checkboxes) or he's talking about the number of files that are detected after install that come up as trojan 

Cheat Engine comes with a driver that lets you do whatever you want on your system .  It also runs with admin rights and can execute any code you wish it to execute.  Including code that deleted all files.
It also has a .exe trainer generator and some people have used the trainer generator to create .exe files that do contain malware.  And parts of the trainer stub is detected by some AV's

**Comment by ShrekTheRealOne** [comment]
the thing that im worried about is what is this PUADImmanager thingy, i downloaded it from your website (.org), what is it and what do you know abt it

**Comment by cheat-engine** [comment]
It's a download manager that shows sponsored applications and then downloads and installs Cheat Engine

**Comment by ShrekTheRealOne** [comment]
and why is it detected as a trojan too?

**Comment by cheat-engine** [comment]
you have to ask drweb and maxsecure that add that tag, but it's just a PUP/PUA, not trojan

**Comment by ShrekTheRealOne** [comment]
ok man hope what ur saying is true, imma use it thx

**Comment by ThePerfectBoy94** [comment]
Tu peu l'utiliser sans problème ce n'est pas un virus, Windows defender detecte faussement cette application comme cela, car Windows ne veuille pas qu'on utilise des triches.
