### ISSUE TITLE
The bloatware really needs to fuck off, i checked it off and i still got 3 new apps 

### ISSUE THREAD

**Issue by RedBloodCat** [cheat-engine/cheat-engine#2610]
Really

**Comment by Dijosto** [comment]
If you clicked decline on the offers, then the installer wouldn't have installed anytbing.

**Comment by Banaanae** [comment]
Also friendly reminder if you don't like the installer you can build the source yourself

**Comment by ZezakTeQelbur** [comment]
> Also friendly reminder if you don't like the installer you can build the source yourself

guide?

**Comment by sakiodre** [comment]
@ZezakTeQelbur it's literally in the [front page of the repo](https://github.com/cheat-engine/cheat-engine#basic-build-instructions), and it's really easy to build, not like you'll get tons of errors.

**Comment by Banaanae** [comment]
@ZezakTeQelbur the searching it up on YouTube found two guides if you need more help
https://youtu.be/fdtOd6UClvc
https://youtu.be/oA6Uv7pyMY8

Please note I haven't tested these videos, follow along the steps with the ones on readme and make sure they're the same

**Comment by fade2gray** [comment]
@darealdemayo Get your facts straight - there is no "malware or other malicious software" in the repo's source code, and you don't download the installer from the repo - just what is there to report to GitHub?
