### ISSUE TITLE
instruction different

### ISSUE THREAD

**Issue by avboy1337** [cheat-engine/cheat-engine#2616]
![Screenshot from 2023-06-18 15-34-32](https://github.com/cheat-engine/cheat-engine/assets/136570640/739d450f-1606-441f-b441-ede4bbda4822)
if i wanna to input 
cmp bx, 0x4550

x64dbg and ce7.5 output different. just like the picture.

**Comment by cheat-engine** [comment]
input `cmp bx,4550` not `cmp bx,0x4550`

**Comment by avboy1337** [comment]
> input `cmp bx,4550` not `cmp bx,0x4550`

OK, I am going to try
