### ISSUE TITLE
the address is not seen 

### ISSUE THREAD

**Issue by avboy1337** [cheat-engine/cheat-engine#2618]
![Screenshot from 2023-06-22 11-38-34](https://github.com/cheat-engine/cheat-engine/assets/136570640/337bd275-1b66-4652-90dd-26e1b2e28126)

is any body got this ?

**Comment by cheat-engine** [comment]
Tried resizing CE?

**Comment by avboy1337** [comment]
> Tried resizing CE?

sorry I think i can make sure that it is true.
In the last release version of 7.5, it is OK and gui is OK
I click the max button , still can not show the full address.
[Screencast from 23-06-2023 18:20:08.webm](https://github.com/cheat-engine/cheat-engine/assets/136570640/5ccc2079-c519-49be-9b0c-cc9c6d259ebd)

**Comment by avboy1337** [comment]
Patched and close this issue.
