### ISSUE TITLE
[Question] Symbol file outdated

### ISSUE THREAD

**Issue by KsaNL** [cheat-engine/cheat-engine#2620]
I'm using Microsoft symbol server and I want to assign the symbol file, how to do this automatically?
Such as kernel32 user32 I think CE load them in memory not file, I'm not sure about that.
Now I have to bring the Microsoft symbol to every app path for load that.

**Comment by cheat-engine** [comment]
which windows version do you use? Normally it shouldn't load if the version doesn't match. Did you delete dbghelp? As I know some versions of it give wrong offsets (though usually just in 32-bit)

Anyhow, the symbol files are stored on disk in `%temp%\Cheat Engine Symbols\` you can delete the old file there, or replace it with a new one

**Comment by KsaNL** [comment]
> Plantform: Win11 build 22621 
> Cheat Engine 7.5 latest build .

I wanna known how CE load the kernel32 symbol? 
The symbol it load was not as complete as Microsoft symbol services

Load before
![image](https://github.com/cheat-engine/cheat-engine/assets/73447685/c7b30627-9014-42ca-8df5-6dc989a30cc4)

Loaded
![image](https://github.com/cheat-engine/cheat-engine/assets/73447685/25c2ebb2-730f-4c2d-9f76-03c75a988405)

**Comment by cheat-engine** [comment]
In memoryview click file->use windows debug symbols
it should then download the debug symbols that suit your system

**Comment by KsaNL** [comment]
Perfect, my version changed the lable name to `Ultimap`, that caused me missed this option.
