### ISSUE TITLE
Malware and Bloatware

### ISSUE THREAD

**Issue by L-udo** [cheat-engine/cheat-engine#2631]
**How are you still operating, your software is a virus
and has installed a variety of bloatware like safe browsing
var VPN, file zilla server
ReasonLabs**

**Comment by cheat-engine** [comment]
You likely clicked accept instead of decline when the offer to install showed.
The installed applications qre very easily uninstallable from the remove software control panel in windows (unless you manually deleted files)

**Comment by L-udo** [comment]
1. I hit decline but it still installed
2. The software is NOT easy to uninstall and persisted when restoring to a previous restore point.
3. The software installed does NOT appear in control panel or settings add/remove software
