### ISSUE TITLE
How to call CE functions using C++?

### ISSUE THREAD

**Issue by eternal2056** [cheat-engine/cheat-engine#2634]
Dear Comrade Author,

I must clarify that everything I'm about to say is based on my limited knowledge of CE, so please bear with me.

I have a requirement where I want to develop a C++ program that utilizes some APIs or entry points of CE. I'd like to inquire whether such an interface exists.

I want to use these APIs to call First Scan, retrieve data from a specific memory address, or communicate with CE server. Yes, my ultimate goal is to communicate with ceserver, but I find it challenging to understand the Pascal source code since it's not familiar to me.

I've heard about Lua scripts, but it seems that they don't directly invoke the desired functionality; instead, they simulate the sensation of human clicks. Hence, I'm not particularly fond of that approach.

If there is no direct interface available, how can I fulfill my requirement? Which source file should I refer to, and what steps should I take?

I would greatly appreciate it if the esteemed author could provide some answers or point me in the right direction. Thank you!

Sincerely,

**Comment by DoranekoSystems** [comment]
ceserver does not support native process memory search.

I have recently developed a native memory search tool in the form of a rest api, which is also available for Windows.

I think my several projects will help you in your endeavors.

**Comment by eternal2056** [comment]
> ceserver does not support native process memory search.
> 
> I have recently developed a native memory search tool in the form of a rest api, which is also available for Windows.
> 
> I think my several projects will help you in your endeavors.

Thank you for your suggestion. I truly want to understand the memory search mechanism, and you have provided me with an enlightening path.

I have placed ceserver inside an Android emulator and established communication with it through a port using CE on Windows. However, relying solely on the buttons in the CE interface seems less sophisticated. Therefore, I want to use my own code to invoke these commands, enabling automation and other possibilities.

**Comment by cheat-engine** [comment]
Lua scripts for memscan don't invoke button clicks

You can create a memscan object, fill in the object fields for scanning (vartype and value) and then invoke the firstscan command

**Comment by eternal2056** [comment]
> 



> Lua scripts for memscan don't invoke button clicks but have direct access to the memscan interface inside CE
> 
> You can create a memscan object, fill in the object fields for scanning (vartype and value) and then invoke the firstscan command
> 
> The scan will then run in the background. There are events to notify you when the scan is done but you can also choose to just wait actively for it to finish
> 
> then using a foundlist object you can read out the results

Thank you for your reply, Comrade Author. I just looked into the CE Lua documentation and found it quite impressive. I have now considered Lua as my alternative option.

Returning to the original question: Is it not possible to call CE functions directly from C++? Can we utilize C++ to call Lua, and then use Lua to invoke CE?

I am very keen on using C++ to call CE. Please forgive my persistence.

**Comment by cheat-engine** [comment]
You can write a CE plugin in C++ and theb invoke lua low level commands to invoke lua functions

**Comment by eternal2056** [comment]
> You can write a CE plugin in C++ and theb invoke lua low level commands to invoke lua functions

Thank you, Comrade Dark Byte, for your clear guidance! I now have a clear research direction.

I will delve into my studies for a while, and if I encounter any issues, I will open a new issue instead of continuing with this one.

Salutations to the great Comrade Dark Byte!
