### ISSUE TITLE
MonoDataCollector Android

### ISSUE THREAD

**Issue by Gersten** [cheat-engine/cheat-engine#2647]
This feature is really something, and i would like to see it in action, but to be honest its not a good idea to just drop these projects inside a folder without any informations, excpacially when you never used these kind of IDEs.

![image](https://github.com/cheat-engine/cheat-engine/assets/13367627/4a4d049c-fab5-4310-8399-11d449b3a063)

can anyone tell me whats is wrong here.

trying to build the MonoDataCollector like the boss said.

https://github.com/cheat-engine/cheat-engine/issues/1144

**Comment by cheat-engine** [comment]
Is the android ndk installed and are the paths setup properly?

**Comment by cheat-engine** [comment]
I think your main issue is you'll need to setup the paths to point to the crosscompiler for android (mingw is not needed, at all)
For mono I use clang++ as compiler and linker. The path to it is /home/<user>/Android/Sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/linux-x86_64/bin

perhaps there's something similar in the ndk on windows

**Comment by cheat-engine** [comment]
arm compiles as well.
![Linux Mint 19-2023-08-02-09-37-05](https://github.com/cheat-engine/cheat-engine/assets/12006555/a2fe30e1-2b0c-4899-9d0b-2ca0b0a91ed3)
![Linux Mint 19-2023-08-02-09-37-42](https://github.com/cheat-engine/cheat-engine/assets/12006555/35267ff6-aaa7-47ec-b6cd-ab8213df390d)
![Linux Mint 19-2023-08-02-09-37-49](https://github.com/cheat-engine/cheat-engine/assets/12006555/0c69abc6-edf0-43aa-979f-6ee3068a9a99)
