### ISSUE TITLE
process crashed when use memory regin function

### ISSUE THREAD

**Issue by bb33bb** [cheat-engine/cheat-engine#2657]
ceserver will crash and out put is like the following:

Failed to open [vdso]
accept=7
Error: recv returned 0
Peer has disconnected
accept=8
Failed to open [vdso]
Error: recv returned 0
Peer has disconnected
Failed to open [vdso]
CMD_GETSYMBOLLISTFROMFILE with fileoffset=27000
symbolpath=/usr/lib/ld-linux-x86-64.so.2
GetSymbolListFromFile(/usr/lib/ld-linux-x86-64.so.2, 27000)
b[0..3]=7f 45 4c 46
Not a string table

Warning: Program '/usr/bin/sudo' crashed.

**Comment by bb33bb** [comment]
may be code issue is here :
```
    if (fileoffset)
      debug_log("b[0..3]=%.2x %.2x %.2x %.2x\n", b[0],b[1],b[2],b[3]);
```
is there any need to check whether there is symbol , and then if symbol exist  , we are going to read the string?

**Comment by cheat-engine** [comment]
upload the `/proc/targetpid/maps` file and `/usr/lib/ld-linux-x86-64.so.2` and i'll check it out

**Comment by bb33bb** [comment]
[upload.tar.gz](https://github.com/cheat-engine/cheat-engine/files/12331132/upload.tar.gz)

**Comment by cheat-engine** [comment]
should work better now

**Comment by bb33bb** [comment]
3Q!
really thanks much!!
