### ISSUE TITLE
ceserver invalid program header entry size (0)

### ISSUE THREAD

**Issue by iamtoaster** [cheat-engine/cheat-engine#2663]
Hello! I tried to use ceserver on arch linux and got the error in the title. Here is the full log - http://0x0.st/HLTK.txt

It happens when I try to attach to any process on my system. When it happens both the server and the client freeze until I kill the server with Ctrl-C.

I do not have SELinux nor AppArmor installed on my system, the server is run as root. The CE client is run under wine

```
-> % uname -r
6.4.10-zen2-1-zen
```
```
-> % wine --version
wine-8.13 (Staging)
```

**Comment by cheat-engine** [comment]
did you also compile the latest cheat engine sourcecode?

**Comment by iamtoaster** [comment]
No, I didn't. I just tried, and it gave me an error - LuaByteTable.pas(319,45) Error: Identifier not found "offset"

I made sure to use Lazarus 2.2.2
```
-> % ./lazarus-qt5 --version
2.2.2 Revision: Unknown
```
With fpc 3.2.2
```
-> % ppcross386 -v
Free Pascal Compiler version 3.2.2 [2023/08/17] for i386
Copyright (c) 1993-2021 by Florian Klaempfl and others
```

**Comment by iamtoaster** [comment]
Alright, I applied a workaround from https://github.com/cheat-engine/cheat-engine/issues/2626#issuecomment-1646851142 and managed to compile cheat engine. Now it can connect to ceserver, even attach to a process. However, when I try to search for anything all I get is a "No readable memory found" error. Here is the server log - https://0x0.st/HLMB.txt

The ceserver was run as root, of course.

**Comment by cheat-engine** [comment]
compile the 64 bit CE

**Comment by iamtoaster** [comment]
After compiling and running the 64-bit cheat engine, everything seems to work fine now. Thank you for your help.
