### ISSUE TITLE
Where is the “cheatengine.lpi” file in the latest release (v7.5)?

### ISSUE THREAD

**Issue by LLLKZY** [cheat-engine/cheat-engine#2669]
The "cheatengine.lpi" file is missing.
I unzipped cheat engine 7.5.zip into a folder called CE.
![image](https://github.com/cheat-engine/cheat-engine/assets/109969200/d50a4171-5365-490a-a5ca-08f1b69cb2c5)
But there is no cheatengine.lpi file in the cheatengine folder. Below is the interface of the Lazarus program:
![image](https://github.com/cheat-engine/cheat-engine/assets/109969200/5547b38a-fb82-4f38-9d69-7123d969711e)
There are no files with the suffix .lpi in the CheatEngine folder except for folders

**Comment by LLLKZY** [comment]
My System Language is Chinese.
But it's okay,don't pay attention.

**Comment by LLLKZY** [comment]
Chinese translation:工程->project
文件名->filename
文件夹->folder
文件->file
在...中搜索->In Search in

**Comment by fade2gray** [comment]
https://github.com/cheat-engine/cheat-engine/assets/1332009/3dd7259d-0ccd-47fa-b1b7-25c5317db0bb

**Comment by LLLKZY** [comment]
> 2023-08-21_16-37-38.mp4

Oh what?
How can you do it?
