### ISSUE TITLE
[Error]Build Error:cesupport.pas(194,115) Error: Identifier not found "ExtractFileNameWithoutExt"

### ISSUE THREAD

**Issue by LLLKZY** [cheat-engine/cheat-engine#2671]
When I was building cheatengine, Lazarus reported an error cessupport. pas (194, 115) Error: Identifier not found "ExtractFileNameWithoutExt"
![image](https://github.com/cheat-engine/cheat-engine/assets/109969200/3e65d47e-83ce-4064-b08a-50b95cfe3463)
cessupport.pas:
![image](https://github.com/cheat-engine/cheat-engine/assets/109969200/bf91e2b0-d709-457e-b72e-31b663cdfb57)
How to solve this problem?

**Comment by fade2gray** [comment]
https://github.com/cheat-engine/cheat-engine/issues/2640#issuecomment-1657215341
