### ISSUE TITLE
Cant Open Cheat Engine

### ISSUE THREAD

**Issue by HanneyBall** [cheat-engine/cheat-engine#2673]
Hi, i checked other topics and i tried to solve this problem with those solutions but didn't happen anything. I couldn't figure out what is the problem. So, i will upload bla.txt to show you my programs which runs on my pc. Help me please, thanks!

https://filebin.net/6yj70vujofe5un6d

**Comment by cheat-engine** [comment]
xhunter1.sys is an anti cheat that blocks CE from loading

**Comment by HanneyBall** [comment]
i deleted it, it doesnt show up now in my bla.txt. After that, restarted my computer and reinstalled cheat engine but it didn't solve my problem, still doesnt happen anything when i try to open the program.

**Comment by cheat-engine** [comment]
is the file still gone or did it get repaired by windows?

**Comment by HanneyBall** [comment]
I used this command in CMD: "sc delete xhunter1". I think the file gone and i can't see now in my bla.txt

**Comment by HanneyBall** [comment]
okey i solved the problem after 3 weeks, the problem was easy anti cheat. I unistalled EA program and it works :)
