### ISSUE TITLE
Is the download link down?

### ISSUE THREAD

**Issue by Vilianexe** [cheat-engine/cheat-engine#2674]
the link https://d1vdn3r1396bak.cloudfront.net/installer/15086067/296520301219 gave me this
![image](https://github.com/cheat-engine/cheat-engine/assets/72302817/f8fccd8d-1ba0-470c-ad75-35ad068b5b9c)
![image](https://github.com/cheat-engine/cheat-engine/assets/72302817/9e19927f-9c6f-4f7c-bd1a-5e3451584949)

i'm using firefox, i trying entering the site in the troubleshoot mode(where my extensions, theme, etc are disabled) and here is the about:support info [firefox_info.txt](https://github.com/cheat-engine/cheat-engine/files/12448363/firefox_info.txt)

i'm using Fedora Linux if that matter

**Comment by fade2gray** [comment]
That cloudfront link works for me. Are you using the official Cheat Engine [website](https://cheatengine.org/) for the initial download?

**Comment by Vilianexe** [comment]
> That cloudfront link works for me. Are you using the official Cheat Engine [website](https://cheatengine.org/) for the initial download?

 it's working, now weird, but thank you!

**Comment by ABMR123** [comment]
same for me
