### ISSUE TITLE
Did you add the laughing effect in the Cheat Engine software? I thought I got a virus.

### ISSUE THREAD

**Issue by maskelihileci** [cheat-engine/cheat-engine#2678]
"While trying version 7.5.1, my antivirus software said Cheat Engine requested audio access, so I granted access, and suddenly a laughing effect appeared. Did you provide this effect?"

**Comment by cheat-engine** [comment]
where did you download 7.5.1 ?

**Comment by maskelihileci** [comment]
Are you serious? 
I'm deleting it right away!

**Comment by maskelihileci** [comment]
I'm bothering you again, but there is no 7.5.1 on your site?

**Comment by glowmoss** [comment]
That's because it's on the patreon only atm

**Comment by maskelihileci** [comment]
Okay, I understand now.
