### ISSUE TITLE
How does CE allocates memory?

### ISSUE THREAD

**Issue by RomanRemez** [cheat-engine/cheat-engine#2679]
Hello, guys!
Can you point me to location where CE allocates memory in an external process.
Searching particularly for memory allocation for injection with 5 byte jump into 64 bit windows process.

**Comment by cheat-engine** [comment]
https://github.com/cheat-engine/cheat-engine/blob/0b61293efe58c4bbb10aa2ee72ab70f6892cd71e/Cheat%20Engine/autoassembler.pas#L3374

**Comment by RomanRemez** [comment]
Thank you!
