### ISSUE TITLE
mono net info error

### ISSUE THREAD

**Issue by qwer0123456** [cheat-engine/cheat-engine#2685]
7.5.1 latest source code

find -> find field click
find -> find Method click

Error:...-engine-master\Cheat Engine\bin\autorun\dotnetsearch.lua:26: attempt to index a nil value (field 'lbClasses')
stack traceback:
	...-engine-master\Cheat Engine\bin\autorun\dotnetsearch.lua:26: in function 'spawnDotNetSearchDialog'
	...at-engine-master\Cheat Engine\bin\autorun\dotnetinfo.lua:2262: in function <...at-engine-master\Cheat Engine\bin\autorun\dotnetinfo.lua:2262>

Error:...-engine-master\Cheat Engine\bin\autorun\dotnetsearch.lua:31: attempt to index a nil value (field 'lbClasses')
stack traceback:
	...-engine-master\Cheat Engine\bin\autorun\dotnetsearch.lua:31: in function 'spawnDotNetSearchDialog'
	...at-engine-master\Cheat Engine\bin\autorun\dotnetinfo.lua:2263: in function <...at-engine-master\Cheat Engine\bin\autorun\dotnetinfo.lua:2263>

spawnDotNetSearchDialog Error

**Comment by fade2gray** [comment]
> 7.5.1 latest source code

7.5.1???

**Comment by qwer0123456** [comment]
> > 7.5.1 latest source code
> 
> 7.5.1 ❓

7.5.1

**Comment by fade2gray** [comment]
Yep, would help if I actually downloaded the latest source. ¯\_(ツ)_/¯

**Comment by qwer0123456** [comment]
> Yep, would help if I actually downloaded the latest source. ¯\_(ツ)_/¯

Commits on Sep 1, 2023 I built it from the latest sources

Try it yourself

mono net.info Find method search function does not work

**Comment by fade2gray** [comment]
I don't doubt that you are seeing these errors, I was just surprised that the version is now 7.5.1.

**Comment by fade2gray** [comment]
Shouldn't the title read, "dot net info error"?

If you need the Class, Field and Method search fields to all work, you need to download the code from an older commit [here](https://github.com/cheat-engine/cheat-engine/tree/882b6f41fa9408db15d0a2aa3ab3c6c989e018a0). 

I don't have any idea how to fix it, perhaps @cheat-engine will sort it out.

![DotNetMenu](https://github.com/cheat-engine/cheat-engine/assets/1332009/7bc30b5e-270b-4b3c-ab45-7616e405c0bc)

**Comment by fade2gray** [comment]
@qwer0123456 Did you find a fix or did you compile the source from the earlier commit?
