### ISSUE TITLE
Bugg on the Driver Build

### ISSUE THREAD

**Issue by hxm-cpp** [cheat-engine/cheat-engine#2688]
![image](https://github.com/cheat-engine/cheat-engine/assets/116516702/303c8c4f-84da-4cb4-8e07-e793a4989e6d)

i think this is a visual studio problem, but it tries to sign it even if i'm disabling it ?

**Comment by fade2gray** [comment]
See this https://github.com/cheat-engine/cheat-engine/issues/2544#issuecomment-1532861795
