### ISSUE TITLE
Ultimap 2 

### ISSUE THREAD

**Issue by WillSmoka** [cheat-engine/cheat-engine#2689]
It works "fine", but it only displays instructions that are constantly being accessed; those that are not constantly accessed are not shown. I've tested it on several processes, and the same thing happens.

My settings:
![cheatengine-x86_64-SSE4-AVX2_0WyRdcKpNf](https://github.com/cheat-engine/cheat-engine/assets/28076099/30e8c37e-3834-4bbd-8b42-bc0132123dce)

**Comment by cheat-engine** [comment]
Add some ranges for code you're interested in.
Windows built-in ipt trace does not support pausing the process when the buffer is almost full and instead will just overwrite the buffer.
By limiting the range the chance for dataloss will decrease

or try without the built-in ipt trace. But you do need DBVM to hide that you use it, else windows will BSOD you
