### ISSUE TITLE
6.7 Copying group (header+children) will not rename children

### ISSUE THREAD

**Issue by phlnx** [cheat-engine/cheat-engine#269]
OS: Windows 10 FCU
Cheat Engine Version: 6.7

Steps to reproduce:

1. Create address manually, memory address is irrelevant, choose label "test address"
2. Right click on table, choose "Create Header" and name it "test"
3. Drag "test address" onto "test" so that "test address" becomes a child of "test"
4. Right click on "test", select Copy
5. Right click on table, select Paste
6. At the requester pop up, for "Text to find:" type "test", for "Replace with:", type "foo"
7. **Expected result: I have a new group labeled "foo" with a child labeled "foo address"**
8. **Actual result: I have a new group labeled "foo" with a child labeled "test address"**

If this is Actually Not A Bug, But A Feature™, then this message becomes a kind request for an addition of this feature (possibly flag-driven under Settings if the developers prefer to keep the current behaviour for compatibility concerns). 

Thank you for your attention and have a nice day.

**Comment by destrofer** [comment]
I would also like to add that field "Adjust address by" is ignored. As a result copied addresses have to be adjusted manually.

**Comment by phlnx** [comment]
@destrofer: in my experience, the "Adjust address by" feature only applies to the selected item and not to their children. Which may or may not be the intended behaviour, I'll let the developers address this.

**Comment by cheat-engine** [comment]
fixed
