### ISSUE TITLE
Cheat Engine won't install/start on linux Fedora

### ISSUE THREAD

**Issue by azarok** [cheat-engine/cheat-engine#2694]
I've been attempting to use wine to install and run cheatengine 7.5 (as well as 7.2, 7.3, and 7.4) on Linux. I started a conversation on a wine forum, and multiple people advised me to raise a new issue on GitHub. On my current machine, which is running Fedora 38, I launched the application using wine-8.14 staging (I also tested on Ubuntu).
The installation of the application is halted by a black window, therefore it never completes. I also installed Cheat Engine on a Windows 10 computer and copy the contents to Fedora, but the outcome was the same. 
The terminal's "log" can be found below.

`wine CheatEngine75.exe 
002c:fixme:winediag:LdrInitializeThunk wine-staging 8.14 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0114:fixme:thread:GetThreadUILanguage : stub, returning default language.
0114:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 005CD97C, 00000000 005CD9A4
0114:fixme:nls:get_dummy_preferred_ui_language (0x38 0x809 005CD97C 00000000 005CD9A4) returning a dummy value (current locale)
0114:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 005CD97C, 01C619B0 005CD9A4
0114:fixme:nls:get_dummy_preferred_ui_language (0x38 0x809 005CD97C 01C619B0 005CD9A4) returning a dummy value (current locale)
011c:fixme:thread:GetThreadUILanguage : stub, returning default language.
011c:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 007ED9C8, 00000000 007ED9F0
011c:fixme:nls:get_dummy_preferred_ui_language (0x38 0x809 007ED9C8 00000000 007ED9F0) returning a dummy value (current locale)
011c:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 007ED9C8, 01E7A680 007ED9F0
011c:fixme:nls:get_dummy_preferred_ui_language (0x38 0x809 007ED9C8 01E7A680 007ED9F0) returning a dummy value (current locale)
011c:fixme:wtsapi:WTSRegisterSessionNotification Stub 0001009E 0x00000000
011c:fixme:uxtheme:BufferedPaintInit Stub ()
011c:fixme:win:DisableProcessWindowsGhosting : stub
011c:fixme:graphics:ShutdownBlockReasonDestroy (0001009E): stub
011c:fixme:graphics:ShutdownBlockReasonCreate (0001009E, L"Installing"): stub
011c:fixme:msg:ChangeWindowMessageFilterEx 000100B2 c052 1 00000000
011c:fixme:msg:ChangeWindowMessageFilterEx 000200B2 c052 1 00000000
011c:fixme:rstrtmgr:RmStartSession 006D5768, 0, 006D576C stub!
011c:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 007EF3B0, 007EF3C0 007EF3B4
011c:fixme:nls:get_dummy_preferred_ui_language (0x38 0x809 007EF3B0 007EF3C0 007EF3B4) returning a dummy value (current locale)
011c:fixme:graphics:ShutdownBlockReasonDestroy (0001009E): stub
011c:fixme:graphics:ShutdownBlockReasonCreate (0001009E, L"Installing \a4daheatEngine."): stub
011c:fixme:system:EnableNonClientDpiScaling (000300B2): stub
011c:fixme:msg:ChangeWindowMessageFilterEx 000300B2 c052 1 00000000
011c:fixme:system:EnableNonClientDpiScaling (000400B2): stub
011c:fixme:msg:ChangeWindowMessageFilterEx 000400B2 c052 1 00000000
011c:fixme:msg:ChangeWindowMessageFilterEx 000200C2 c052 1 00000000
011c:fixme:msg:ChangeWindowMessageFilterEx 000300C2 c052 1 00000000
011c:fixme:shell:SHAutoComplete stub
0120:fixme:winhttp:request_set_option 0 (null) (null)
0120:fixme:winhttp:request_set_option 0 (null) (null)
011c:fixme:msg:ChangeWindowMessageFilterEx 000400C2 c052 1 00000000
011c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0128:fixme:winhttp:request_set_option 0 (null) (null)
0120:fixme:winhttp:request_set_option 0 (null) (null)
0128:fixme:winhttp:request_set_option 0 (null) (null)
`
At the moment, Cheatengine is the only application that doesn't work with wine on my machine.
Thank you in advance for your help.

**Comment by cheat-engine** [comment]
I think they meant to report it to the wine bug tracker 
A few versions back CE was working fine in wine
But do copy the contents of the installed package from windows to your system. I don't know about the installer

**Comment by azarok** [comment]
I appreciate the response. My plan B was to copy the installed packages and use wine to run them, but the result remained the same.
In the wine forum, they directed me here (with the link :) ).
Any other advice?

**Comment by cheat-engine** [comment]
I just booted up my linux VM, and in wine-staging 8.5 it was still working
![image](https://github.com/cheat-engine/cheat-engine/assets/12006555/08b8328f-a2d3-46c2-b820-ca96c6c88e89)

Do launch the x86-64.exe

and make sure you copy the whole folder and subfolders

**Comment by azarok** [comment]
I appreciate your response (and screenshot :))

The issue still exists even after I copied the folder and its subfolders to my Fedora computer.
The output from the terminal is attached below.

`
[guest@fedora Cheat Engine 7.5]$ wine cheatengine-x86_64.exe 
002c:fixme:winediag:LdrInitializeThunk wine-staging 8.14 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0114:fixme:msg:ChangeWindowMessageFilter 49 00000001
0114:fixme:msg:ChangeWindowMessageFilter 233 00000001
0114:fixme:process:GetProcessWorkingSetSizeEx (00000000000000E8,000000000251FB58,000000000251FB50,0000000000000000): stub
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"Z:\\home\\guest\\Applications\\Cheat Engine 7.5\\cheatengine-x86_64.exe"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\ntdll.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
0114:fixme:ntdll:NtQuerySystemInformation (0x000000c4,0x251faf4,0x00000004,0x251faf0) stub
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\kernel32.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\kernelbase.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\oleaut32.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\advapi32.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\msvcrt.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\sechost.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\ucrtbase.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\gdi32.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\user32.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"Z:\\usr\\x86_64-w64-mingw32\\sys-root\\mingw\\bin\\libpng16-16.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"Z:\\usr\\x86_64-w64-mingw32\\sys-root\\mingw\\bin\\zlib1.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"Z:\\usr\\x86_64-w64-mingw32\\sys-root\\mingw\\bin\\libssp-0.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\version.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\win32u.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\ole32.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\combase.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\rpcrt4.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\shell32.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\aclui.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\winsxs\\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef\\comctl32.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\imm32.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\shlwapi.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\shcore.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\opengl32.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\comdlg32.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\winspool.drv"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\compstui.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\ws2_32.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\wsock32.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\iphlpapi.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\dnsapi.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\nsi.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\uxtheme.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\psapi.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\hhctrl.ocx"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\winmm.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\msacm32.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"Z:\\home\\guest\\Applications\\Cheat Engine 7.5\\lua53-64.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\wininet.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\mpr.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\winex11.drv"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\msimg32.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\explorerframe.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\glu32.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"Z:\\home\\guest\\Applications\\Cheat Engine 7.5\\tcc64-32.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"Z:\\home\\guest\\Applications\\Cheat Engine 7.5\\tcc64-64.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"Z:\\home\\guest\\Applications\\Cheat Engine 7.5\\win64\\dbghelp.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\Xinput1_4.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\hid.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:SymLoadModuleExW Unsupported Flags 00000004 for L"C:\\windows\\system32\\setupapi.dll"
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:dbghelp:elf_search_auxv can't find symbol in module
011c:fixme:file:NtLockFile I/O completion on lock not implemented yet
`

**Comment by cheat-engine** [comment]
try deleting the dbghelp dll from the win32 and win64 subfolders

**Comment by azarok** [comment]
same result
![image](https://github.com/cheat-engine/cheat-engine/assets/6631587/dabd0c46-096a-41c3-a8b3-396b63ce1012)

**Comment by azarok** [comment]
and same output from the terminal

**Comment by azarok** [comment]
Hey, I used Mint on a virtual machine, and everything went smoothly. I need to figure out where is the problem on my computer...

**Comment by cheat-engine** [comment]
maybe the graphics driver, or perhaps dark mode was used on the computer and CE detected it. In which case it uses some undocumented windows API's to render in dark mode.

**Comment by azarok** [comment]
I tried removing all themes from winecfg, but it had no effect. Is there a setting file for CE that I can look at to see whether it is selecting the dark theme?

**Comment by azarok** [comment]
The regedit adjustments worked. I had to restart the computer, but now I can run CE.
Many thanks for your help.
![image](https://github.com/cheat-engine/cheat-engine/assets/6631587/2175c506-0463-40f7-ba9a-eae49f074939)
