### ISSUE TITLE
new feture request 

### ISSUE THREAD

**Issue by bb33bb** [cheat-engine/cheat-engine#2696]
is there any possible for ceserver to monitor the data of kernel mod in linux?
when doing linux kernel memory work , there is really no software can be used quickly.

![image](https://github.com/cheat-engine/cheat-engine/assets/5463104/81bda189-d18a-484a-8629-3547f2e18149)

I mean the ablity to monitor the above addresses

**Comment by cheat-engine** [comment]
not for ceserver
bit maybe gdbserver on a vm in the future (working on a gdbserver interface atm)
or maybe if the systems is running dbvm (using q dbvm bootdisk and then boot linux, and then use wine to run CE to control DBVM

**Comment by bb33bb** [comment]
> not for ceserver bit maybe gdbserver on a vm in the future (working on a gdbserver interface atm) or maybe if the systems is running dbvm (using a dbvm bootdisk and then boot linux, and then use wine to run CE to control DBVM

Any how thanks for your work!!
