### ISSUE TITLE
Download link on homepage

### ISSUE THREAD

**Issue by Chocobo1** [cheat-engine/cheat-engine#270]
I'm trying to download the newest version from homepage (http://cheatengine.org/) and this is what I get:
```
http://www.berylbisonbana.party/GwUv4KWYqyFUcebTbztHJwnbwv3gXJIPHSUByM_Dmy7nFv5HsP8FDN0w1KJdWVFoZ8lZ4TUauhK0PkCTG_lmufaDbOoqXIv+m5pIkslJjQv8WRUGSCtRR5vYmPeu+UdZTyXhMbPy6cAyHhYE3YQnjol4klSEeAEiNVADx+qet5552XxcqaN_igNohMUmumdBWiWQz47ux9vmxGMSdDfzOoicdi4WCJG+2NTT6S3SqB3D2uqcywlJKqAQIldkXrCpn8htjWPf8e3TKF3XIBgaVQpJO4eNzXCHlRi8zKQUf7V0qPudPcOql0b+_fVmfeR5eYupR4_H5GV3zcr0ohDJgOvL2tWyAIbETtbZZV08VS10Vh4sByE=-G1MAAEQ3F5OuKV1MRZD7dvgOd8qBQ4vS1jzADnbwkBVVtdmDqEOeSZy1Oa9QcEQxhf0x2XLROzB1REypMdf+DQ==-e
```

Weird isn't it, who chooses a name "berylbisonbana.party" for a domain and as a primary download link?

Furthermore, I download it and compared with the one on github/releases:
```
    File: CheatEngine67_VFhLAE.exe  (from berylbisonbana.party)
     MD5: 60bc92a679c5864ff88c777855242eff
   SHA-1: f9af39a0983b5878451d9d365da2ec8d51572e54
 SHA-256: a4676e3fb1d1514d631e1ccb0a82d374068a43c43bf5d4ebf48c5be1f46c7b0e

    File: CheatEngine67.exe  (from https://github.com/cheat-engine/cheat-engine/releases)
     MD5: a1bf011028db014edabdd7783c1ae34a
   SHA-1: 0818be9df711ceb94ccc721f89e8b6fba72d8109
 SHA-256: 9f498954b628b7cd9989a4ee2339601cfcbb58c8a32bfa2d0c8bc2adbd1d90ae
```

Files doesn't match, care to explain? hope its not a malicious link.

For OSS projects there are better places to put your binaries, to name a few: github/releases, bintray, fosshub...

**Comment by Chocobo1** [comment]
And virustotal scan doesn't looks good: https://www.virustotal.com/zh-tw/file/a4676e3fb1d1514d631e1ccb0a82d374068a43c43bf5d4ebf48c5be1f46c7b0e/analysis/1511825938/

Or consider hosting your website on github pages or Netlify.

**Comment by cheat-engine** [comment]
the one on the site has a tag stating it came from the website and the other one that it came from github.  (a way to track which exe gets downloaded/copied around more)
that's why they are different

as for the link, it's a random generated domain for file uploads, it's ok

**Comment by Chocobo1** [comment]
Thanks for the clarification! 
But even if the file names are different (you mentioned tag), their contents (thus their hash) should be the same, seems it's not here.
Also don't know what's the idea behind random download locations, however, a fixed download link is more comfortable (at least for me knowing file not compromised).
