### ISSUE TITLE
7.5 mono_invoke_method 

### ISSUE THREAD

**Issue by Y-A-K-E** [cheat-engine/cheat-engine#2702]
use .net helper form(not working):

![Screenshot 2023-09-26 004020](https://github.com/cheat-engine/cheat-engine/assets/6988291/5307d449-24b4-4659-8042-c3e8a8a96801)

use lua code (is working):
```
local pp = getAddressSafe('[pp]')
local val =tonumber(CETrainer.CEEdit9.Text)

if (pp ~=nil and pp~= 0) then
  mono_invoke_method(mono_enumDomains()[1],mono_findMethod('','PlayerController', 'SetAllSkills'), pp,{{type=vtDword,value=val}})
end

```

**Comment by cheat-engine** [comment]
replace `mifinfo.mif.show()` with `mifinfo.mid.show()`
