### ISSUE TITLE
7.5 Trainer.Checkbox use 'error()'

### ISSUE THREAD

**Issue by Y-A-K-E** [cheat-engine/cheat-engine#2703]
```
function CETrainer_CECheckbox1Change(sender)
  if _G['init'] ~=nil and _G['init']== 1 then
     print("ok")
  else
     print("no init")
     error()   --Don't change Checked, 7.4 is working , 7.5 not working.
  end
end

```

7.5 print
```
no init 
error:nil
stack traceback:
	[C]: in function 'error'
	[string "
..."]:6: in function 'CETrainer_CECheckbox1Change'
```

**Comment by cheat-engine** [comment]
7.4 had a bug where unhandled exceptions aren't reported.

that is fixed in 7.5

**Comment by Y-A-K-E** [comment]
if use 'return' or set null function  'onLuaError' ,
CETrainer.CECheckbox1.Checked will change.

If _G['init'] ==nil or _G['init'] == 0  
I don't want to change CETrainer.CECheckbox1.Checked 

-----
like 

https://forum.cheatengine.org/viewtopic.php?t=618412&sid=6f7924d3480b722b3cbe55d036fe971b

**Comment by cheat-engine** [comment]
the error('no') works in memory records because the exception there is properly handled, but this is direct GUI library callback which doesn't expect an unhandled exception in that part (which will lead to some minor memoryleaks each click)

what you can do is:
```lua
  local oldOnChange=sender.OnChange
  sender.OnChange=nil
  sender.Checked=not sender.Checked
  sender.OnChange=oldOnChange
```

**Comment by Y-A-K-E** [comment]
> the error('no') works in memory records because the exception there is properly handled, but this is direct GUI library callback which doesn't expect an unhandled exception in that part (which will lead to some minor memoryleaks each click)
> 
> what you can do is:
> 
> ```lua
>   local oldOnChange=sender.OnChange --might not be necessary, but I prefer this as then i'm sure there's no infinite loop
>   sender.OnChange=nil               -- ^
>   sender.Checked=not sender.Checked
>   sender.OnChange=oldOnChange       --^
> ```

ok
