### ISSUE TITLE
[Lua] deAlloc will set page to NO_ACCESS

### ISSUE THREAD

**Issue by Lioncky** [cheat-engine/cheat-engine#2706]
Check it with address list view(Ctrl+R), 
my solution: refree the memory with `NtFreeVirtualMemory(hProc, &sAddr, &szAddr, MEM_RELEASE)`,
I think it's a bug need fix becasue 'Lua:allocateMemory' won't work again

**Comment by cheat-engine** [comment]
I can not reproduce. Make sure you're on ce 7.5 or later

```lua
if z then
  deAlloc(z)
end
z=allocateMemory(8192,0x200000000)

printf("z=%x",z)
```

returns 200000000 each time (assuming that 200000000 was unallocated memory)

**Comment by Lioncky** [comment]
I'm sure the bug appeared bacause I really fix it by refree in my software and then it work again
```
// here is my code
[ENABLE]
{$lua}
os = {}
rf = 0
mk = enumModules()[1].Address
hk = allocateMemory(0x10000,mk-0x10000,false)

{$asm}
[DISABLE]
deAlloc(hk)
```

**Comment by cheat-engine** [comment]
that dealloc isn't a lua dealloc so it's going to be ignored

**Comment by Lioncky** [comment]
Var 'hk' and etc... had been registered and ASM can directly use.
I mean CE can't alloc memory on a NO_ACCESS page sometimes.

**Comment by cheat-engine** [comment]
change `hk = allocateMemory(0x10000,mk-0x10000,false)` into `hk = allocateMemory(0x10000,mk-0x10000)` as false (0) is not a proper protection (page no_access)

**Comment by Lioncky** [comment]
Emm, this bool param makes me confusion.
Problem solved, thanks a lot!
