### ISSUE TITLE
[Enhancement] Mono related

### ISSUE THREAD

**Issue by DKingCN** [cheat-engine/cheat-engine#271]
The current result window of "Instance of CLASS" would be nice if it's copiable. A textbox will be good enough and better than a uncopiable list. I checked the code of monoscript.lua, it's in function mono_class_findInstancesOfClass or its callback OnScanDone, please consider changing it to textbox.

Thanks for the great work. Looking forward to commit my part when i got time to have a look at the great project.

**Comment by cheat-engine** [comment]
it's actually a treeview in the current source so not as easy to convert to a textbox.  But you could add a popup menu option for copy to clipboard

**Comment by DKingCN** [comment]
Yes it's form related. I dont even have a lua IDE. 
And Im a bit freaked out on seeing the whole project mixing with multiple languages. Maybe later when Im not in panic.
