### ISSUE TITLE
seems compiled error

### ISSUE THREAD

**Issue by bb33bb** [cheat-engine/cheat-engine#2712]
seems compiled error

**Comment by fade2gray** [comment]
What error?

**Comment by bb33bb** [comment]
I'm going to have a new try and if still error ,i will post it

> What error?

**Comment by bb33bb** [comment]
> What error?

sorry , i compiled again and this time OK
use 2.2.6 lazarus

**Comment by fade2gray** [comment]
Which version of Lazarus was causing the error? The build instructions tell you to use Lazarus 2.2.2.

**Comment by bb33bb** [comment]
> Which version of Lazarus was causing the error? The [build instructions](https://github.com/cheat-engine/cheat-engine#basic-build-instructions) tell you to use Lazarus 2.2.2.

sorry , compiled OK , no ERROR
