### ISSUE TITLE
on linux to use ceserver to change page protection can not function.

### ISSUE THREAD

**Issue by bb33bb** [cheat-engine/cheat-engine#2718]
![image](https://github.com/cheat-engine/cheat-engine/assets/5463104/b307a566-2ac7-4ea7-9a71-3a28bbcf1612)

**Comment by cheat-engine** [comment]
is the ceserver extension properly injected and working?

**Comment by bb33bb** [comment]
I am going to try  it ,and really thanks for your ans.
I will close this issue later.
