### ISSUE TITLE
[Bug] mono_invoke_method triggers OnTimeout

### ISSUE THREAD

**Issue by DKingCN** [cheat-engine/cheat-engine#272]
When mono_invoke_method is called, monopipe.OnTimeout(monoscript.lua Ln.186) is always triggered in less than a second tho the timeout seems to be set to 5000. Please check the reason.

My solution is to temporarily remove the timeout callback before it's fixed.

**Comment by DKingCN** [comment]
Besides, setting a break point seems to be deactiving mono too. I have not checked whether it's the same reason.

**Comment by cheat-engine** [comment]
another reason the monotimeout code gets called is when the mono server thread running in the target process crashes. (the pipe handle disappears so it won't have to wait for the timeout, it's gone)


setting a breakpoint shouldn't cause the timeout to happen though. actually hitting it will, as the 'address to name lookup' will timeout on the breakpoint handling

**Comment by DKingCN** [comment]
I will try again and see whether monoserver is gone. feedback later.
( actually, running a batch of mono_invoke_method after callback of timeout being disabled seemed to be working. will check that again.)

**Comment by DKingCN** [comment]
Confused about how mono works. Giving up that game. Sorry man. The information you provided is helpful tho.
