### ISSUE TITLE
Can't use {$LUACODE}

### ISSUE THREAD

**Issue by Y-A-K-E** [cheat-engine/cheat-engine#2721]
64bit not working. 
32bit not working.

![Screenshot 2023-10-18 202955](https://github.com/cheat-engine/cheat-engine/assets/6988291/f0a9f541-2497-478e-8776-3617b8af53cd)

https://github.com/cheat-engine/cheat-engine/commit/4478e0cdde563cd2748e005269f2cc7daa8d4945

roll back code
`inc(i,3); `

rebuild.

Can work, but can only be activated once.
Activate script (working) ->Deactivate (working) ->Activate script (not working)

32bit AA code

```
define(address,Engine.GAME::Engine::RemoveLog)
[ENABLE]

alloc(newmem,$1000)

label(code)
label(return)

newmem:
{$LUACODE testparam=ecx}
--There is no code here
{$asm}
code:
  push ebp
  mov ebp,esp
  push esi
  mov esi,ecx
  jmp return

address:
  jmp newmem
  nop
return:

[DISABLE]

address:
   push ebp
   mov ebp,esp
   push esi
   mov esi,ecx

dealloc(newmem)
```

64-bit AA code
```define(address,Engine.GAME::Engine::RemoveLog)
[ENABLE]


alloc(newmem,$1000,Engine.GAME::Engine::RemoveLog)

label(code)
label(return)

newmem:
{$luacode testparam=rcx}
--There is no code here
{$asm}
code:
  push rbx
  sub rsp,20
  jmp return

address:
  jmp newmem
  nop
return:

[DISABLE]

address:
   push rbx
   sub rsp,20

dealloc(newmem)
```

**Comment by cheat-engine** [comment]
should be fixed now
