### ISSUE TITLE
VEH.dll couldnt load.

### ISSUE THREAD

**Issue by Theo1996** [cheat-engine/cheat-engine#2735]
I built my CE7.5 but when I try to use the veh debugger to see what accesses/writes something it pops a message that it couldnt load the VEH.dll , before that it was saying that it didnt understand what the load vehdebugger meant as an error message so I built the vehdebug.sli and threw it in the CE folder,that fixed it(I think...), but its this one now, the VEH.dll.
win7 64-bit.

**Comment by cheat-engine** [comment]
build both 32 and 64 bit

**Comment by Theo1996** [comment]
After 2 hours I finally understood what you meant, I had to go in to Lazarus and select many build mode for the vehdebug.lpi , select 32-bit and 64-bit, for some reason when I pressed simply "build" it only made the 32bit version of vehdebugger. At first I thought I had to build CE as 32bit and 64bit.
Thank you.
