### ISSUE TITLE
Any possible to suport bt?

### ISSUE THREAD

**Issue by bb33bb** [cheat-engine/cheat-engine#2736]
![image](https://github.com/cheat-engine/cheat-engine/assets/5463104/580fa5fc-e8a9-464b-85bf-1417ba54a945)

**Comment by cheat-engine** [comment]
not sure what you mean with bt. (bluetooth?)  
But if you mean backtrace rightclick and choose stacktrace

**Comment by bb33bb** [comment]
> not sure what you mean with bt. (bluetooth?) But if you mean backtrace rightclick and choose stacktrace

OK, I got it !!
Thanks for your quick ans!!
Yes i need the backtrace!!
Thanks for your attention!!

> not sure what you mean with bt. (bluetooth?) But if you mean backtrace rightclick and choose stacktrace. If it doesn't work, it just means the function you're currently in isn't supported / has an unsupported stackframe setup
