### ISSUE TITLE
Enabling any Extra option Crashes.

### ISSUE THREAD

**Issue by Rikimaruaxu** [cheat-engine/cheat-engine#274]
I'm trying to enable the extra options for cheat engine for a table I have. But as soon as I enable anything and press Okay the entire computer BSoD's with a Worker_Thread_Returned_at_bad_irql error. I don't know how to fix it, I reinstalled cheat engine. I'm using Windows 10 update 1709, I have an AMD FX-8350, 16 gigs of Ram and a GTX 1060.

**Comment by cheat-engine** [comment]
Make sure you have no games running and check that secure boot is disabled in the bios
