### ISSUE TITLE
compile error 

### ISSUE THREAD

**Issue by bb33bb** [cheat-engine/cheat-engine#2747]
![image](https://github.com/cheat-engine/cheat-engine/assets/5463104/3c4a25fb-b85f-4e21-bcb9-29bc15412425)
gdbserverdebuggerinterface.pas(2888,7) Error: Identifier not found "FpClose"

**Comment by FeronFae** [comment]
Having the same issue when compiling straight from source.

**Comment by FeronFae** [comment]
Having the same issue when trying to compile.

Compiler: _Lazarus v2.2.2 (win64) with win32-win64 cross-compile add-ons_

**Comment by bb33bb** [comment]
> Having the same issue when trying to compile.
> 
> 
> 
> Compiler: _Lazarus v2.2.2 (win64) with win32-win64 cross-compile add-ons_

2.2.6 also error

**Comment by AquaNot** [comment]
Having the same issue too

Compiler: Lazarus v2.2.6 (win64) with win32-win64 cross-compile add-ons

**Comment by winkado** [comment]
Also experiencing this issue

Compiler: Lazarus v2.2.2 (win64) with win32-win64 cross-compile add-ons

**Comment by etapic** [comment]
download&compile from https://github.com/cheat-engine/cheat-engine/releases  , NOT from github repo -> download and zip

**Comment by Albedios** [comment]
Compiler: Lazarus v2.2.2 (win64) with win32-win64 cross-compile add-ons
Helped downloading .tar archive from releases, dont know exactly why

**Comment by bb33bb** [comment]
01-Fpclose can change to closesocket or some other function else, then compile ok this position.
02- other places error, not only one position
eventually give up
and waiting for author release the compiled OK source code.

**Comment by bb33bb** [comment]
compiled OK for x86 and x64 as following patch, windows:


diff --git a/Cheat Engine/MainUnit.pas b/Cheat Engine/MainUnit.pas
index 1575a2b0..e61c6104 100755
--- a/Cheat Engine/MainUnit.pas	
+++ b/Cheat Engine/MainUnit.pas	
@@ -2463,6 +2463,7 @@ procedure TMainForm.exceptionhandler(Sender: TObject; E: Exception);
 var
   s: string;
   op: string;
+  AccessViolationException: EAccessViolation;
 begin
   //unhandled exeption. Also clean lua stack
   s:={$ifdef THREADNAMESUPPORT}GetThreadName+': '+{$endif}'Unhandled exception: '+e.message+' (Exception class '+ e.ClassName+')';
@@ -2471,14 +2472,15 @@ begin
   {$ifdef windows}
   if e is EAccessViolation then
   begin
-    case EAccessViolation(e).ExceptionRecord.ExceptionInformation[0] of
+    AccessViolationException := EAccessViolation(e); // 强制类型转换
+    case AccessViolationException.ExceptionRecord^.ExceptionInformation[0] of
       0: op:='read';
       1: op:='write to';
       8: op:='execute';
       else op:='do something weird with';
     end;
 
-    s:=s+' (tried to '+op+' address '+inttohex(qword(EAccessViolation(e).ExceptionRecord.ExceptionInformation[1]),8)+')';
+    s:=s+' (tried to '+op+' address '+inttohex(qword(AccessViolationException.ExceptionRecord^.ExceptionInformation[1]),8)+')';
   end;
   {$endif}
 
@@ -7753,7 +7755,7 @@ begin
   {$ifdef windows}
   try
 
-    if @DebugActiveProcessStop <> @DebugActiveProcessStopProstitute then
+    if Pointer(@DebugActiveProcessStop) <> Pointer(@DebugActiveProcessStopProstitute) then
     begin
       //detach the debugger
       //hide;
diff --git a/Cheat Engine/gdbserverdebuggerinterface.pas b/Cheat Engine/gdbserverdebuggerinterface.pas
index 7ad7e5ed..4f6e230f 100644
--- a/Cheat Engine/gdbserverdebuggerinterface.pas	
+++ b/Cheat Engine/gdbserverdebuggerinterface.pas	
@@ -2618,7 +2618,7 @@ begin
   ReleaseLock;
   OutputDebugString('released lock');
 
-  fpclose(socket);
+  closesocket(socket);
   if gdbserverExecutor<>nil then
   begin
     OutputDebugString('terminating gdbserverExecutor');
@@ -2896,7 +2896,7 @@ begin
 
       if (connectresult=0) or (gettickcount64>starttime+10000) then break;
 
-      FpClose(socket);
+      closesocket(socket);
       socket:=INVALID_SOCKET;
       sleep(10);
     end;
diff --git a/Cheat Engine/symbolsync.pas b/Cheat Engine/symbolsync.pas
index 7d6f87f3..ccea5f24 100644
--- a/Cheat Engine/symbolsync.pas	
+++ b/Cheat Engine/symbolsync.pas	
@@ -477,7 +477,7 @@ begin
     fs.Size:=0;
     fs.free;
 
-    DeleteFile(symbolfilepath+'.lock');
+    DeleteFile(PChar(symbolfilepath+'.lock'));
 
     if pidlookup<>nil then
     begin
diff --git a/Cheat Engine/tcclib.pas b/Cheat Engine/tcclib.pas
index 7e82b9d4..a88e083b 100644
--- a/Cheat Engine/tcclib.pas	
+++ b/Cheat Engine/tcclib.pas	
@@ -1245,7 +1245,7 @@ begin
       p:='';
   end;
   if p<>'' then
-    module:=loadlibrary(p);
+    module:=loadlibrary(PChar(p));
 
   if module=0 then
     notworkingreason:=p+' could not be found';

**Comment by bb33bb** [comment]
> compiled OK for x86 and x64 as following patch, windows:
> 
> ```
> diff --git a/Cheat Engine/MainUnit.pas b/Cheat Engine/MainUnit.pas
> index 1575a2b0..e61c6104 100755
> --- a/Cheat Engine/MainUnit.pas	
> +++ b/Cheat Engine/MainUnit.pas	
> @@ -2463,6 +2463,7 @@ procedure TMainForm.exceptionhandler(Sender: TObject; E: Exception);
>  var
>    s: string;
>    op: string;
> +  AccessViolationException: EAccessViolation;
>  begin
>    //unhandled exeption. Also clean lua stack
>    s:={$ifdef THREADNAMESUPPORT}GetThreadName+': '+{$endif}'Unhandled exception: '+e.message+' (Exception class '+ e.ClassName+')';
> @@ -2471,14 +2472,15 @@ begin
>    {$ifdef windows}
>    if e is EAccessViolation then
>    begin
> -    case EAccessViolation(e).ExceptionRecord.ExceptionInformation[0] of
> +    AccessViolationException := EAccessViolation(e); // 强制类型转换
> +    case AccessViolationException.ExceptionRecord^.ExceptionInformation[0] of
>        0: op:='read';
>        1: op:='write to';
>        8: op:='execute';
>        else op:='do something weird with';
>      end;
>  
> -    s:=s+' (tried to '+op+' address '+inttohex(qword(EAccessViolation(e).ExceptionRecord.ExceptionInformation[1]),8)+')';
> +    s:=s+' (tried to '+op+' address '+inttohex(qword(AccessViolationException.ExceptionRecord^.ExceptionInformation[1]),8)+')';
>    end;
>    {$endif}
>  
> @@ -7753,7 +7755,7 @@ begin
>    {$ifdef windows}
>    try
>  
> -    if @DebugActiveProcessStop <> @DebugActiveProcessStopProstitute then
> +    if Pointer(@DebugActiveProcessStop) <> Pointer(@DebugActiveProcessStopProstitute) then
>      begin
>        //detach the debugger
>        //hide;
> diff --git a/Cheat Engine/gdbserverdebuggerinterface.pas b/Cheat Engine/gdbserverdebuggerinterface.pas
> index 7ad7e5ed..4f6e230f 100644
> --- a/Cheat Engine/gdbserverdebuggerinterface.pas	
> +++ b/Cheat Engine/gdbserverdebuggerinterface.pas	
> @@ -2618,7 +2618,7 @@ begin
>    ReleaseLock;
>    OutputDebugString('released lock');
>  
> -  fpclose(socket);
> +  closesocket(socket);
>    if gdbserverExecutor<>nil then
>    begin
>      OutputDebugString('terminating gdbserverExecutor');
> @@ -2896,7 +2896,7 @@ begin
>  
>        if (connectresult=0) or (gettickcount64>starttime+10000) then break;
>  
> -      FpClose(socket);
> +      closesocket(socket);
>        socket:=INVALID_SOCKET;
>        sleep(10);
>      end;
> diff --git a/Cheat Engine/symbolsync.pas b/Cheat Engine/symbolsync.pas
> index 7d6f87f3..ccea5f24 100644
> --- a/Cheat Engine/symbolsync.pas	
> +++ b/Cheat Engine/symbolsync.pas	
> @@ -477,7 +477,7 @@ begin
>      fs.Size:=0;
>      fs.free;
>  
> -    DeleteFile(symbolfilepath+'.lock');
> +    DeleteFile(PChar(symbolfilepath+'.lock'));
>  
>      if pidlookup<>nil then
>      begin
> diff --git a/Cheat Engine/tcclib.pas b/Cheat Engine/tcclib.pas
> index 7e82b9d4..a88e083b 100644
> --- a/Cheat Engine/tcclib.pas	
> +++ b/Cheat Engine/tcclib.pas	
> @@ -1245,7 +1245,7 @@ begin
>        p:='';
>    end;
>    if p<>'' then
> -    module:=loadlibrary(p);
> +    module:=loadlibrary(PChar(p));
>  
>    if module=0 then
>      notworkingreason:=p+' could not be found';
> ```

addtional info:

i don't know lazarus , just patched by gpt4
