### ISSUE TITLE
ceserver createthread issue

### ISSUE THREAD

**Issue by 23cku0r** [cheat-engine/cheat-engine#2749]
createthread does nothing or crashes the application.

Video with steps to reproduce
https://www.youtube.com/watch?v=yhdK0blnGyc

Emulator: Windows Subsystem for Android
OS: Android 13 x86_64
Cheat Engine and ceserver built from one source. [Oct 27, 2023]

**Comment by cheat-engine** [comment]
It looks more like the debugger isn't working on newly created threads

**Comment by 23cku0r** [comment]
Now i'm getting this error 
![Screenshot 2023-11-18 120417](https://github.com/cheat-engine/cheat-engine/assets/69985987/8e4ed658-af51-4d29-9444-b0cf2b1c0c91)
[cedebug.txt](https://github.com/cheat-engine/cheat-engine/files/13401005/cedebug.txt)

**Comment by cheat-engine** [comment]
look at 7a81b76065f0 (or whatever rax is after that error) to see the error why the extension .so didn't load

**Comment by 23cku0r** [comment]
I really don't know what happened and why alloc doesn't work anymore. I literally tried to look at RAX in Memory View but didn't see anything.
I also tried to rebuild ceserver/CE or reinstall WSA. But error still persists.

Before alloc:
![image](https://github.com/cheat-engine/cheat-engine/assets/69985987/4ce0340b-cbe5-46fe-a99e-e3f9aebef3cf)

After:
![image](https://github.com/cheat-engine/cheat-engine/assets/69985987/31df1c5f-4ac4-4fb1-86a2-07adec7a591b)

**Comment by cheat-engine** [comment]
in hexview.
anyhow, is "/data/cheatengine/libceserver-extension_x86_64.so" readable for the target process? Is the folder /data/cheatengine readable and executable for everyone?  And is libceserver-extension_x86_64.so readable and executable for everyone as well ?

**Comment by 23cku0r** [comment]
Yes thanks. I fixed that by placing the executables in /data/data/<target application>. I don't know why, but it didn't work even with 777 permissions on the folder and files.
And yes, debugger isn't work on newly created threads. Sorry.
