### ISSUE TITLE
Compile Instructions?

### ISSUE THREAD

**Issue by stillunt1tled** [cheat-engine/cheat-engine#275]
I'm having trouble figuring out how to compile this program for my computer (Ubuntu Desktop, 16.04.x LTS)

May I have some help (or maybe someone commit a makefile in root)

**Comment by remizovm** [comment]
@stillunt1tled Hello! I've successfully compiled Cheat Engine using the latest [Lazarus](https://www.lazarus-ide.org/) IDE both under Windows and macOS. I do beleive that Cheat Engine (for now) is not suited to be run under *NIX.

**Comment by stillunt1tled** [comment]
@remizovm OK, thanks.
