### ISSUE TITLE
Cheat Engine's Tutorial does not run.

### ISSUE THREAD

**Issue by Hrudai-Devain** [cheat-engine/cheat-engine#2752]

**Comment by cheat-engine** [comment]
either an anti virus or anti cheat

**Comment by Hrudai-Devain** [comment]
I turned my windows security off but it still did not work.

**Comment by fade2gray** [comment]
If you compiled CE yourself, you would need to compile the tutorials as a separate process.

**Comment by Hrudai-Devain** [comment]
How do I do that exactly?

**Comment by fade2gray** [comment]
Did you compile Cheat Engine yourself, or did you use the installer?

**Comment by Hrudai-Devain** [comment]
I compiled it using lazurus so myself.

**Comment by fade2gray** [comment]
To compile the basic tutorial; compile `...\Cheat Engine\Tutorial\tutorial.lpi`.

To compile the mini-game tutorial; compile `...\Cheat Engine\Tutorial\graphical\project1.lpi`.
Once you have compiled `project1.lpi`, you will need to copy the `...\Cheat Engine\Tutorial\graphical\badassets` folder to the `...\Cheat Engine\bin` folder.

**Comment by Hrudai-Devain** [comment]
When I did a test it said this: newvirtualstringtree.pas(8,32) Fatal: Cannot find laz.VirtualTrees used by newvirtualstringtree. Check if package laz.virtualtreeview_package is in the dependencies.

**Comment by fade2gray** [comment]
See https://github.com/cheat-engine/cheat-engine/issues/2397#issuecomment-1330894238

**Comment by Hrudai-Devain** [comment]
I did the steps, but it did not work. I may be an absolute idiot and forgot to do something.

**Comment by Hrudai-Devain** [comment]
Yeah I am an idiot.
