### ISSUE TITLE
[Bug] Swapping tabs does not relinquish control back to the original tab when searching.

### ISSUE THREAD

**Issue by gir489returns** [cheat-engine/cheat-engine#2754]
When using tabs to search, if you swap tabs while the search is occurring, the original tab that the search was conducted on no longer will function, if the search completes on another tab.

Replication steps:

1: On Scan 1, search for an arbitrary value.
2: While the scan is occurring, switch to or create a new tab (Scan 2).
3: Wait for the scan to complete.
4: After the scan is completed, switch back to Scan 1.
5: Bug occurs. (Scan 1 is disabled)

**Comment by cheat-engine** [comment]
fixed
