### ISSUE TITLE
[Bug] Script(Lua/AASM) being turned into an address type

### ISSUE THREAD

**Issue by Rixef** [cheat-engine/cheat-engine#2756]
### Steps to reproduce:

1. Open Auto Assemble scripting window
2. File > Assign to current cheat table
3. Select the script in the cheat table and press Ctrl+Alt+Enter
4. Click OK
5. The script is no longer a script. It's an address. RIP script. :')

I freaked out a bit in devistation when it happened 'cause I thought it just deleted the whole script but fortunately I'm savvy enough to right click the .CT file > Open with Notepad/Notepad++ and then search the description there and was able to recover the script that way. 

### Possible/Suggested Solution:

- Don't allow Ctrl+Alt+Enter hotkey combo for <script> type in cheat tables.
- Or make it so Ctrl+Alt+Enter does something else for <script> type in cheat tables.
- Or when you double click the Type to change it(not sure why anyone *would* do this with a script other than by accident but 🤷‍♂️); add Script to the dropdown list of types to change to so you can change it back.

**Comment by cheat-engine** [comment]
fixed for next version
