### ISSUE TITLE
TControl.ChangeBounds loop detected

### ISSUE THREAD

**Issue by pinchyCZN** [cheat-engine/cheat-engine#276]
An error box appears when you try to load a CT file from the wrong menu option (file->open file) instead of file -> load.

The error is: "TControl.ChangeBounds loop detected :TCheckBox Left=0,Top=1000,Width=121,Height=17 NewLeft=0,NewTop=1001,NewWidth=121,NewHeight=17"

I was able to fix it from the mainunit form editor by setting panel6 Autosize to false.

**Comment by mgrinzPlayer** [comment]
This is not CE bug. It is Lazarus bug.

**Comment by cheat-engine** [comment]
I can't reproduce. Does this happen in the released version of 6.7 or only on your own build ? 
you may need to patch lazarus, or you've made some gui changes somewhere else that eventually caused a issue there  (e.g adding an onResize event somewhere completely unrelated)

**Comment by pinchyCZN** [comment]
This occurs with the master branch including commits up to 2017-11-21
The last commit I tested against is
SHA d95160e0a0bc68ce936766fc68b3dba4e65ab0c0
