### ISSUE TITLE
Marked as a virus, and won't let me open it.

### ISSUE THREAD

**Issue by StatusZer0** [cheat-engine/cheat-engine#2760]
I tried everything! I read the forums and
- Disabled reputation-based protection
- Disabled real-time (just for installation)
- Disabled everything antivirus-based

It never worked! Any help here?
![image_2023-11-26_195537486](https://github.com/cheat-engine/cheat-engine/assets/148401532/4fc97c5a-5226-4fd2-a60b-1a67dcb3a5f1)

**Comment by cheat-engine** [comment]
You're sure they are still off?  They have the tendecy to turn themselves back on (e.g clicking to discard the notification that defender is disabled reactivates it)

**Comment by StatusZer0** [comment]
I just disabled them all together a quickly opened it, and now it works! Thanks!
