### ISSUE TITLE
Telstra blocks the download website, anyway to fix that? 

### ISSUE THREAD

**Issue by Kuran206** [cheat-engine/cheat-engine#2776]
Telstra is my service provider, and well... as says, it blocks the download website, saying that it's dangerous, anyway can I fix that problem or is it just not possible to get it this way?

**Comment by fade2gray** [comment]
Never heard of anyone's ISP blocking CE's download before. Just a shot in the dark, try using [Tor Browser](https://www.torproject.org/).

**Comment by Kuran206** [comment]
Thanks for the suggestion but no needed, figured it out, just needed to change some DNS settings then it worked, strange but oh well
