### ISSUE TITLE
So what version of windows 10 is ideal for KM+ DBVM?

### ISSUE THREAD

**Issue by githubsearcher11** [cheat-engine/cheat-engine#2792]
While I do understand debugging every windows build's kernel internals isn't realistic and horrendous for their notorious PG and "security measures" , but I think you need to be clear about what versions of windows are truly supported by KM + DBVM debugging.

I'm bit irritated to get BSOD'd every single time when I attempts to debug (especially when hitting BP and resuming execution) the game, that's why I'm asking for this.
What build of windows 10 is stable for KM + DBVM debugging?

**Comment by cheat-engine** [comment]
windows 10 1900 or earlier might have some functional kernelmode debug 

But i suggest moving on to dbvm level debug as kernelmode debug is marked obsolete

Also, don't set breakpoints in irql's higher than 0 as that means the GUI will never update.  And while the debugger can prevent some of thise cases there's always the chance for q deadlock even when in irql0 as the kernel might do a lock on a resource in the GUI and thus never return as the GUI can't resume

**Comment by githubsearcher11** [comment]
thanks for answering. 18xx build sounds to be safe for KM + DBVM then as im currently on 1903 and it bsod a lot.

should i understand that kernelmode debugging isn't useable for somewhat modern systems (starting from 19xx ~ w11) then?
i dont get last part. while debugging UM application with KM driver how can i avoid setting BP at irql 0? is this situation is avoidable by CE users? sounds like pure timing gamble to me.

**Comment by cheat-engine** [comment]
If you're just debugging usermode apps you should be fine but I recommend disabling the "kernelmode breaks"

Also, DBVM level doesn't really need a km driver.  You can even load DBVM from an USB stick at boot and then load windows and you can use dbvm level debug without the need for a driver (of course, using the CE driver to load DBVM at runtime is easier)

**Comment by githubsearcher11** [comment]
Okay, Thanks!

**Comment by fade2gray** [comment]
@githubsearcher11 and anyone else finding this post, I have a created a custom build that 'works' on...
Windows 10 22H2 19045.3930 and Windows 11 22H2 22621.3007
Both the DBVM-level and Kernel mode debuggers appear to work, but they haven't been tested extensively (lack of experience).

![DBVM Test Build](https://github.com/cheat-engine/cheat-engine/assets/1332009/ed139d07-74d0-42ef-b64c-f510151a1965)
