### ISSUE TITLE
Remove spooky laughting noise from CE

### ISSUE THREAD

**Issue by githubsearcher11** [cheat-engine/cheat-engine#2793]
I do understand you dont like people who doesn't properly install CE, that's fair. but you shouldn't make this triggered when manually compiled from source.

**Comment by cheat-engine** [comment]
The laughing sound isn't in the sourcecode.

**Comment by githubsearcher11** [comment]
huh, weird. maybe i got mixed up folders then. sorry for misopening issue.

**Comment by Ra2-IFV** [comment]
Yeah, but can't explain you are shipping the malicious lua scripts and laugh to your real, official installer.
**You are doing things same as XZ BACKDOOR incident.**
You can't just say go fucking build by yourself, it's nonsense for normal users, injecting malicious things in your installers is still the truth.
I admit your works, but you are fucking denying the facts and preventing ppl from talking about it.
In terms of that, you motherfucker son of bitch go eat shit and fucking die
I won't donate anymore. Go fuck yourself.
