### ISSUE TITLE
dbvm cloak gets extreamly slow with intel CPU.

### ISSUE THREAD

**Issue by githubsearcher11** [cheat-engine/cheat-engine#2794]
Hello. Currently I'm using DBVM cloak to modify somewhat fucky protected game (but UM only, no KM protection).
I do understand that EPT hooking isn't viable for AMD, but even with Intel, my FPS gets tanked 200 to 1 fps.

For now I'm using Kernalmode debugger with global debug routines (else game detects debuggin and crashes), nothing else has modified from default CE settings.

Is there any ways to boost up DBVM Cloak excution speed? also seems like  lag doesnt go away, even after disabling dbvm cloaking. untill restarts game itself it gets lagged forever.

**Comment by cheat-engine** [comment]
Does the page you're cloaking contain data that is read or written often? 
Try closing the memview window and scan the memory of the process a few tikes to force all lost caches to load again 

does the speed return after doing the lua command: `dbvm_ept_reset()` ?

**Comment by githubsearcher11** [comment]
I'm confident that target area isn't getting written as it's marked as read and excuteable only. and yes. im not running this on VM. running directly on my machine with windows.

Speed does not return even excuting that lua command, unfortunatly. the second trick also didn't work out :(
Is there anything can be done on my side to pinpoint the reason of this slowdown?

**Comment by cheat-engine** [comment]
You're using CE 7.5 and the dbvm version that came with that one?

Does just cloaking and not changing anything also slow down?

Which specific CPU do you use (e.g core i9 13900K etc...)

**Comment by githubsearcher11** [comment]
Happens with 7.5.1, using default DBVM and DBK

Yes, just enabling cloak also slows down. yet again decloaking -> calling dbvm_ept_reset() in lua console doesn't make differences. it still gets slowed to hell

I'm using Intel i7-11800H.

**Comment by cheat-engine** [comment]
If you enable cloak in another process. Is it still slow then ?

**Comment by githubsearcher11** [comment]
In case of first question, No. so I'm also suspecting that if DBVM Cloak's placed on frequently executed area, it will slow down to hell, but still the amount of slowdown is too much and that shouldn't happen.

For second, i have placed DBVM Cloak on troublesome area, please let me know if you wants me to test on non-laggy memory area.

`//Before DBVM Cloak
0: 1 
1: 0 
2: 0 
3: 0 
4: 0 
5: 0 
6: 0 
7: 0 
8: 0 
9: 0 
10: 424 
11: 0 
12: 0 
13: 0 
14: 0 
15: 0 
16: 0 
17: 0 
18: 1 
19: 0 
20: 0 
21: 0 
22: 0 
23: 0 
24: 0 
25: 0 
26: 0 
27: 0 
28: 0 
29: 0 
30: 0 
31: 0 
32: 0 
33: 0 
34: 0 
35: 0 
36: 0 
37: 0 
38: 0 
39: 0 
40: 0 
41: 0 
42: 0 
43: 0 
44: 0 
45: 0 
46: 0 
47: 0 
48: 4 
49: 0 
50: 0 
51: 0 
52: 0 
53: 0 
54: 0 
55: 0 

//After DBVM Cloak
0: 0 
1: 0 
2: 0 
3: 0 
4: 0 
5: 0 
6: 0 
7: 0 
8: 0 
9: 0 
10: 3940 
11: 0 
12: 0 
13: 0 
14: 0 
15: 0 
16: 0 
17: 0 
18: 1 
19: 0 
20: 0 
21: 0 
22: 0 
23: 0 
24: 0 
25: 0 
26: 0 
27: 0 
28: 0 
29: 0 
30: 0 
31: 0 
32: 0 
33: 0 
34: 0 
35: 0 
36: 0 
37: 32599 
38: 0 
39: 0 
40: 0 
41: 0 
42: 0 
43: 0 
44: 0 
45: 0 
46: 0 
47: 0 
48: 33488 
49: 0 
50: 0 
51: 0 
52: 0 
53: 0 
54: 0 
55: 0 

//After 15 mins
0: 0 
1: 0 
2: 0 
3: 0 
4: 0 
5: 0 
6: 0 
7: 0 
8: 0 
9: 0 
10: 824 
11: 0 
12: 0 
13: 0 
14: 0 
15: 0 
16: 0 
17: 0 
18: 1 
19: 0 
20: 0 
21: 0 
22: 0 
23: 0 
24: 0 
25: 0 
26: 0 
27: 0 
28: 0 
29: 0 
30: 0 
31: 0 
32: 0 
33: 0 
34: 0 
35: 0 
36: 0 
37: 32691 
38: 0 
39: 0 
40: 0 
41: 0 
42: 0 
43: 0 
44: 0 
45: 0 
46: 0 
47: 0 
48: 32691 
49: 0 
50: 0 
51: 0 
52: 0 
53: 0 
54: 0 
55: 0 

// After 30mins
0: 0 
1: 0 
2: 0 
3: 0 
4: 0 
5: 0 
6: 0 
7: 0 
8: 0 
9: 0 
10: 500 
11: 0 
12: 0 
13: 0 
14: 0 
15: 0 
16: 0 
17: 0 
18: 1 
19: 0 
20: 0 
21: 0 
22: 0 
23: 0 
24: 0 
25: 0 
26: 0 
27: 0 
28: 0 
29: 0 
30: 0 
31: 0 
32: 0 
33: 0 
34: 0 
35: 0 
36: 0 
37: 32686 
38: 0 
39: 0 
40: 0 
41: 0 
42: 0 
43: 0 
44: 0 
45: 0 
46: 0 
47: 0 
48: 32686 
49: 0 
50: 0 
51: 0 
52: 0 
53: 0 
54: 0 
55: 0 `

**Comment by cheat-engine** [comment]
i forgotvto mention that after cloak you need to close CE and then restart CE but don't qttach to the game. That way it won't be recording the reads of CE's memory

Also, try doing a "dbvm find what access" on the code you cloak and see if it happens a lot or not (maybe even a pagesize watch) as the integrity check routine may take a lot of cputime

**Comment by githubsearcher11** [comment]
of course, i actually recorded it while measuring that, but i'm quite unsure if you want me to test again with restarting CE method you mentioned above.

anyways, here's the result i captured together with above result:
```
//After disabling cloak
0: 0 
1: 0 
2: 0 
3: 0 
4: 0 
5: 0 
6: 0 
7: 0 
8: 0 
9: 0 
10: 0 
11: 0 
12: 0 
13: 0 
14: 0 
15: 0 
16: 0 
17: 0 
18: 1 
19: 0 
20: 0 
21: 0 
22: 0 
23: 0 
24: 0 
25: 0 
26: 0 
27: 0 
28: 0 
29: 0 
30: 0 
31: 0 
32: 0 
33: 0 
34: 0 
35: 0 
36: 0 
37: 0 
38: 0 
39: 0 
40: 0 
41: 0 
42: 0 
43: 0 
44: 0 
45: 0 
46: 0 
47: 0 
48: 0 
49: 0 
50: 0 
51: 0 
52: 0 
53: 0 
54: 0 
55: 0 

//After disabling -> dbvm_ept_reset()
0: 0 
1: 0 
2: 0 
3: 0 
4: 0 
5: 0 
6: 0 
7: 0 
8: 0 
9: 0 
10: 1856 
11: 0 
12: 0 
13: 0 
14: 0 
15: 0 
16: 0 
17: 0 
18: 1 
19: 0 
20: 0 
21: 0 
22: 0 
23: 0 
24: 0 
25: 0 
26: 0 
27: 0 
28: 0 
29: 0 
30: 0 
31: 0 
32: 0 
33: 0 
34: 0 
35: 0 
36: 0 
37: 0 
38: 0 
39: 0 
40: 0 
41: 0 
42: 0 
43: 0 
44: 0 
45: 0 
46: 0 
47: 0 
48: 0 
49: 0 
50: 0 
51: 0 
52: 0 
53: 0 
54: 0 
55: 0 

```

**Comment by githubsearcher11** [comment]
Oh man, you are right. the assembly line that i target to patch does not has any read/write attempts, but some other part in same page gets read very frequently. is there any ways to use DBVM in such scenarios, through? or am i doomed now?

**Comment by cheat-engine** [comment]
pick a different part to hook and see if you can work from there, or patch the code that reads those pages so it reads from a copy that isn't cloaked  (it's read only anyhow)

**Comment by githubsearcher11** [comment]
alright, thank you so much for helping. i still don't understand why dbvm_ept_reset() doesn't work out through but this isn't dbvm's fault at all anyways. sorry for misopening the issue.
