### ISSUE TITLE
i can not run cheat engine due to windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access this item

### ISSUE THREAD

**Issue by KCHELPS** [cheat-engine/cheat-engine#2797]
everytime i open it it says can not run cheat engine due to windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access this item

**Comment by cheat-engine** [comment]
That is either reputation based protection OR windows defender  (they are not the same thing)

**Comment by KCHELPS** [comment]
ok thank u i fix it
