### ISSUE TITLE
CUDA pointerscan

### ISSUE THREAD

**Issue by gafask** [cheat-engine/cheat-engine#2799]
**Good afternoon**, I noticed in the source code CE - "**CUDA pointerscan**" and I was very interested , it turns out that you can use the GPU to search for a pointer ? I tried to compile the project, but of course I got a bunch of errors, since most likely I do not have enough dependencies and what dependencies are needed is also not known to me personally, could you tell me in more detail whether "CUDA pointerscan" is working at the moment, could you tell me which dependencies I should download in order to compile it successfully on my PC or just provide ( if possible ) already compiled files for use , searching for pointers using the GPU was very interesting to me since I saw a similar question on the CE forum back in 2010+- and there the answer was negative , because at that time people did not have good enough equipment and video cards did not have at least 12 GB of memory on board , but now it 's 2024 and video cards have 20-30 GB on board , and ideally now searching for pointers through the GPU should be a working and fast way by alignment with CPU usage . I will be very grateful for your answers, thank you. I'll be waiting) Here is a link to the github if someone came in for the sake of interest to look at the answers - "https://github.com/cheat-engine/cheat-engine/tree/5f6d7464e73ac1e37d0ff7ad1a6b379dfc277560/Cheat%20Engine/CUDA%20pointerscan" . This is an official repository, I just copied the permanent path and that's it. Sorry for my not very good English.
![image](https://github.com/cheat-engine/cheat-engine/assets/58403278/b938944f-1b9c-45c6-88e8-4070c589d7fb)
![image](https://github.com/cheat-engine/cheat-engine/assets/58403278/af7aad10-6aa0-491e-ad3d-0ebcf5516c86)

**Comment by cheat-engine** [comment]
I did look into this again but on the card i have and after a lot of optimizing/rewriting the throughput is about 200 million paths/second which is very slow for a system that normally does 1500 million paths/seconds on the CPU, and that's even without writing any results

**Comment by gafask** [comment]
> I did look into this again but on the card i have and after a lot of optimizing/rewriting the throughput is about 200 million paths/second which is very slow for a system that normally does 1500 million paths/seconds on the CPU, and that's even without writing any results

Got it, thanks for the answer. 2024, but the CPU is outpacing the GPU pointer search speed . Although this is how it should logically be, since the CPU is good at calculations, but on the other hand, AI calculations are also performed on the GPU. And the plus is the cost of downloading information to the GPU and then uploading it to the CPU . We are waiting for 2034, maybe we will have capacity there). But at the time when I asked the question, there was a firm statement in my head that the GPU would be faster. Thanks again.

**Comment by cheat-engine** [comment]
GPU's are faster depending on the workload.  if it's just a list of sequential calculations on floats they're really fast, But things like branches (if/else) and memory access to global memory slows it down quite a bit

and pointerscans don't really use calculations much, just read memory over and over
