### ISSUE TITLE
Cheat engine missing driver

### ISSUE THREAD

**Issue by DexTheRat** [cheat-engine/cheat-engine#2806]
After following the steps in the undetected ce tutorial. Opening the modified ce pops an error saying i am missing the driver.
![mai1](https://github.com/cheat-engine/cheat-engine/assets/156778478/529f2525-c851-47b2-b202-d0235fd844a9)
![mai2](https://github.com/cheat-engine/cheat-engine/assets/156778478/1a82eb3d-ccdc-410d-90b7-ba74e72d6fb5)
I did the visual studio driver setup successfully but i was getting this message since starting it after compile cheat engine part of the tutorial.

**Comment by cheat-engine** [comment]
Is the sys file in the same folder as ce's exe ?

**Comment by DexTheRat** [comment]
the sys got created in a different folder i dragged it over and it worked now all thats left is to sign it. thanks for your help
