### ISSUE TITLE
Cheat Engine won't launch

### ISSUE THREAD

**Issue by Falcon5077** [cheat-engine/cheat-engine#2808]
![image](https://github.com/cheat-engine/cheat-engine/assets/32628758/8063eb9d-5243-41d4-9251-69899e8c3f3e)

I've been using it well, but suddenly it doesn't work.
so I have any clue and don't know what should I do. 

How can I fix it?

(Any anti-program dosen't running.)

------------------------------------------------

I've been writing and realized that I haven't tried reinstalling it. 

How can I delete an issue? I'm sorry.

**Comment by Banaanae** [comment]
Just closing it is good enough
