### ISSUE TITLE
Installation fails if controlled folder access is enabled

### ISSUE THREAD

**Issue by svengo** [cheat-engine/cheat-engine#281]
I have [controlled folder access](https://support.microsoft.com/en-us/help/4046851/windows-10-controlled-folder-access-windows-defender-security-center) enabled. The setup fails with an error:
<img width="388" alt="2018-01-05 cheat-engine1" src="https://user-images.githubusercontent.com/2502366/34619762-87d66d10-f243-11e7-932b-c504637ec513.PNG">

...and the following message (sorry, only in German):
<img width="296" alt="2018-01-05 cheat-engine2" src="https://user-images.githubusercontent.com/2502366/34619778-9ebcce98-f243-11e7-9a9b-caea022b8dc8.PNG">

The error is produced by a temporary file so I cannot whitelist it.

**Comment by avboy1337** [comment]
I usually install and test in a virtual machine. It is highly recommended to uninstall Windows defender every time.
