### ISSUE TITLE
ceserver CreateToolHelp32SnapshotEx partially implemented

### ISSUE THREAD

**Issue by ferib** [cheat-engine/cheat-engine#2826]
I see that `CMD_CREATETOOLHELP32SNAPSHOTEX` was added in ceserver version 4?

Looking at the implementation of this handler in [ceserver.c](https://github.com/cheat-engine/cheat-engine/blob/master/Cheat%20Engine/ceserver/ceserver.c#L661), I see that Module and Module32 aren't implemented, yet my CE (version 7.5) is firing `0x18` at me, which I assume is [defined here as Module & Moduel32](https://github.com/cheat-engine/cheat-engine/blob/master/Cheat%20Engine/unixporthelper.pas#L154).

I am looking at my custom implementation for ceserver on Windows, can I find any way to implement these missing handlers? or am I doing something completely wrong here?

**Comment by cheat-engine** [comment]
https://github.com/cheat-engine/cheat-engine/blob/3c35fab43eb86718f6cbd852d8115d65f1b35881/Cheat%20Engine/ceserver/api.c#L4378
