### ISSUE TITLE
Detecting by anticheat software

### ISSUE THREAD

**Issue by Krzhub** [cheat-engine/cheat-engine#283]
Could you advise what to do to avoid detection by anticheat? Form name, process description in not enough. 

thank you,
Krzhub

**Comment by zcanann** [comment]
This is (usually) illegal, you won't find advice here

**Comment by Krzhub** [comment]
well, was worth a try.

thanks,
Krzhub

**Comment by abdulaziz7** [comment]
i guess the file names need to be changed
