### ISSUE TITLE
Unable to Add Plugins on Mac version 6.2

### ISSUE THREAD

**Issue by msull54** [cheat-engine/cheat-engine#284]
When I click the button to add plugins, nothing happens. I assume there is supposed to be a pop-up, but it never appears. Is there a fix or workaround for this? Thanks!

**Comment by cheat-engine** [comment]
it's not implemented in that version yet perhaps next version. 

do keep in mind that if it is implemented it will NOT be able to load plugins that where written for the windows version (only lua extentions will work, with a few exceptions)
