### ISSUE TITLE
DBKKernel project update

### ISSUE THREAD

**Issue by DKingCN** [cheat-engine/cheat-engine#285]
I managed to revive DBKKernel in VS2017 , Win10 ver1709 and WDK here [DBKKernel](https://github.com/DKingCN/DBKKernel)
(Dont just pull back, some files are simply deleted)

I think the update make sense and have intention to contribute back but I can't make sure how to meet your standard.
Could you please provide me the standard when dealing with these things, for example, How I deal with CETC (deleted or some kind of post procedure)

I am willing to do the same to the other subprojects including dbvm, dbvm UEFI. What else should I know?

**Comment by cheat-engine** [comment]
I only have visual studio 2013 so not sure if I can make use of it, but i'll check it out

**Comment by DKingCN** [comment]
Maybe you would like to `git diff` these files to see what I do to the sources

It's simply install WDK, then
* create a driver project in VS, add files in
* update DBK.inf
* update some structure usages,
* Project Configure to i386/amd64 noexceptions.asm
* Turn off "regarding warning as error"

I think VS2013 will be better than VS2017 due to compatibility. But .vcproj in the original project is way too far from reality. No one would like to get a WinServer 2000 and install VS2008+DDK on it.

If you got time maybe you can do it yourself, without spending time on a document for me.

**Comment by DKingCN** [comment]
Issue closed since DBKKernel is updated in commit: [Now using visual studio 2017 to compile the driver](https://github.com/cheat-engine/cheat-engine/commit/d2dc1a62358c2b753e25ae4808a44e7e5d683a22)
