### ISSUE TITLE
Portable ZIP release

### ISSUE THREAD

**Issue by ZehCastro** [cheat-engine/cheat-engine#286]
Why must we endure an installer?
Why not make a portable zip only release?

**Comment by cheat-engine** [comment]
check the download page on the main website

**Comment by ZehCastro** [comment]
You are right, there is a download link for a RAR there that does not need the installer. I had looked there already before, but it is a really small, and somewhat hidden, link. It also has some scary caveats about registry and permissions talk that will surely fright a regular user. 

A truly portable release would have big, visible links here on github and on the main site and none of the caveats.

**Comment by eadmaster** [comment]
please reconsider a portable release storing settings into an ini file instead of the registry.

**Comment by Skip75** [comment]
I can't find anymore the portable ZIP file. Can someone share it for latest version please ?

**Comment by Skip75** [comment]
Ah finally found it in a hiden link named "[here](https://www.cheatengine.org/download/CheatEngine7.0_MissingSetup.rar)"^^

**Comment by AnnanFay** [comment]
The above is returning "403 - Forbidden" for me.

**Comment by Skip75** [comment]
https://www.cheatengine.org/downloads.php
"here" link in the page : https://www.cheatengine.org/download/CheatEngine7.1_MissingSetup.rar

**Comment by mgrinzPlayer** [comment]
Download will only work with correct "Referer" inside Get Header.

Here, Lua script which will download rar file to your desktop:
```Lua
int  =  getInternet()

int.Header = [[Referer: https://www.cheatengine.org/downloads.php]]

response = int.getURL([[https://www.cheatengine.org/download/CheatEngine7.1_MissingSetup.rar]])

ms = createMemoryStream()

for b in response:gmatch('.') do
  ms.writeByte(b:byte())
end

ms.saveToFile(os.getenv('userprofile')..[[\Desktop\CheatEngine7.1_MissingSetup.rar]])

ms.destroy()
int.destroy()
```
😜
