### ISSUE TITLE
[DBVM] The instruction is accessed by itself

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#2869]
Using dbvm-level debugger when I try to figure out what accesses the instruction it shows me: the instruction accesses the instruction:

![image](https://github.com/cheat-engine/cheat-engine/assets/14368203/aed04d41-590c-444d-8725-f047d448635e)

I dont have this behavior when using VEH debugger and its freezing my game (obviously). I have AMD processor. How can I solve this?

**Comment by cheat-engine** [comment]
instead of the normal(dbvm level) find out what accesses try the dbvm find what accesses.  That one shouldn't interrupt the target process

**Comment by Symbai** [comment]
If you're talking about this one: 
![image](https://github.com/cheat-engine/cheat-engine/assets/14368203/d976cbe2-e223-4960-8954-12a4d82fbbaa)

That doesn't work either, still shows me the same instruction. Or do you mean I should change from dbvm level to dbvm kernel debugger in CE options? Note a friend of mine has an Intel CPU and said he has "access type" options for the DBVM Watch Config dialog. I don't have these, could that be the reason? Like I said im having an AMD processor.

**Comment by cheat-engine** [comment]
Like in the picture yes

got a screenshot of the dialog that shows when you use that option?

**Comment by Symbai** [comment]
![image](https://github.com/cheat-engine/cheat-engine/assets/14368203/4c0a8b4a-faa1-417f-b964-8274b28507f3)
Value in the screenshot below rapidly changes, if I go to 73FFDCC8 I see memory which also rapidly changes. But I dont see the instruction which accesses the `xor rbx,[rcx]`
![image](https://github.com/cheat-engine/cheat-engine/assets/14368203/8466be1e-1eca-4bf9-a601-a6c3e14ad43d)

**Comment by cheat-engine** [comment]
ah I didn't see it correctly. I meant "dbvm find out what writes or accesses this address"  which is accessible from the addresslist on the main window
just add the address of the instruction to the list and then use that function on it. the access type should be visible there

**Comment by Symbai** [comment]
Ah ok, didnt know. Thank you
