### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by ZehCastro** [cheat-engine/cheat-engine#287]
Where can I find the build instructions for the supported platforms?

**Comment by ZehCastro** [comment]
Is [this](http://forum.cheatengine.org/viewtopic.php?t=7149) still valid?

**Comment by cheat-engine** [comment]
it's a bit outdated. Right now I use lazarus 1.6.4 with some custom patches.

1.8 came out recently but I havn't tested that one yet
