### ISSUE TITLE
disassemblerview_setSelectedAddress cannot be executed normally.

### ISSUE THREAD

**Issue by wbaby** [cheat-engine/cheat-engine#2884]
memoryView=getMemoryViewForm();
disassemblerview=memoryview_getDisassemblerView(memoryView);
getresukt=disassemblerview_getSelectedAddress(disassemblerview);
print(getresukt);
disassemblerview_setSelectedAddress(disassemblerview, 0x00BEB000);

disassemblerview always select 0 address.

**Comment by cheat-engine** [comment]
`disassemblerview_setSelectedAddress` is obsolete and shouldn't be used anymore 

instead use something like:
```
memoryView=getMemoryViewForm();
getresukt=memoryView.DisassemblerView.SelectedAddress
printf("%x", getresukt)
memoryView.DisassemblerView.SelectedAddress=0x00BEB000
```

**Comment by wbaby** [comment]
Thx
