### ISSUE TITLE
Symbol "DBG_CONTINUE_SINGLESTEP" not found

### ISSUE THREAD

**Issue by hacbit** [cheat-engine/cheat-engine#2886]
i use lazarus 2.2.2 to compile ce, and report this error msg:
`dbvmdebuggerinterface.pas(311,25) Error: Identifier not found "DBG_CONTINUE_SINGLESTEP"`

this is the function where the error is reported:
```
function TDBVMDebugInterface.ContinueDebugEvent(dwProcessId: DWORD; dwThreadId: DWORD; dwContinueStatus: DWORD): BOOL;
var step: boolean;
begin
  try
    lastfrozenID:=currentFrozenID;
    if dwContinueStatus=DBG_CONTINUE_SINGLESTEP then
    begin
      OutputDebugString('TDBVMDebugInterface.ContinueDebugEvent returning single step');
      //single step
      lastContinueWasAStep:=true;
      dbvm_bp_resumeBrokenThread(currentFrozenID, 1); //step
    end
    else
    begin
      //run
      OutputDebugString('TDBVMDebugInterface.ContinueDebugEvent returning normal run');
      lastContinueWasAStep:=false;
      dbvm_bp_resumeBrokenThread(currentFrozenID, 2); //run
    end;

    result:=true;
  except
    result:=false;
  end;

end;   
```

**Comment by fade2gray** [comment]
What source are you compiling?

**Comment by hacbit** [comment]
> What source are you compiling?

the latest version of cheatengine source

**Comment by fade2gray** [comment]
Did you install `lazarus-2.2.2-fpc-3.2.2-win64.exe` ***and*** `lazarus-2.2.2-fpc-3.2.2-cross-i386-win32-win64.exe`?

**Comment by hacbit** [comment]
i installed `lazarus-2.2.2-fpc-3.2.2-win64.exe` but not `lazarus-2.2.2-fpc-3.2.2-cross-i386-win32-win64.exe`

**Comment by fade2gray** [comment]
https://github.com/cheat-engine/cheat-engine#basic-build-instructions

**Comment by hacbit** [comment]
> Did you install `lazarus-2.2.2-fpc-3.2.2-win64.exe` _**and**_ `lazarus-2.2.2-fpc-3.2.2-cross-i386-win32-win64.exe`?

tks, i forgot to install `lazarus-2.2.2-fpc-3.2.2-cross-i386-win32-win64.exe` earlier. and now it's successful
