### ISSUE TITLE
Window cycling

### ISSUE THREAD

**Issue by alansley** [cheat-engine/cheat-engine#289]
Hello,

I've written some software to assist people who may be visually impaired to play videogames by adding sonification to them (https://github.com/FedUni/SoniFight). In essence, you find a pointer chain to a value of interest and then it makes a sound when it matches some criteria. There's an example of how it works here: https://www.youtube.com/watch?v=qHvcVv_BdmE

However, when Cheat Engine is open and you do a pointer scan it opens up a window with the results of that scan - but there's no way to change window focus between the main CE window and the scan results window without actually clicking on the results window. As you might imagine, for blind users this is troublesome.

Would it be possible to implement a hotkey to cycle the 'subwindows' of Cheat Engine, for example by using "Alt+~" or such to change window focus within the app's windows? This would be a massive boon to visually impaired users who might then be able to use CE to help 'crowd-source' sonification of games.

**Comment by cheat-engine** [comment]
Save this code as a .LUA file in your CE autorun folder
```
function nextForm()
  local i

  --first find the current form (should always be 0 but just to be sure)
  for i=0, getFormCount()-1 do
    if getForm(i).isForegroundWindow() then
      --find the oldest visible form (should be at the back)
      local j
      for j=getFormCount()-1,0,-1 do

        if (j~=i) and getForm(j).Visible then
          getForm(j).show() --brings it to front
          return
        end
      end
    end
  end

  --no foreground window in CE
  --comment this out if you don't want CE to show when not visible
  local mf=getMainForm()
  mf.formStyle='fsSystemStayOnTop'
  mf.show()
  mf.formStyle='fsNormal'
end

if (nextformhotkey) then
  nextformhotkey.destroy()
  nextformhotkey=nil
end

VK_OEM_3=0xc0 --`/~ key
nextformhotkey=createHotkey(nextForm,VK_LMENU,VK_OEM_3)
```

**Comment by alansley** [comment]
That's fantastic - thank you so much! =D
