### ISSUE TITLE
CE w/ CEServer running on WINE crashes on attempt to do pointerscan (pointermaps work fine tho)

### ISSUE THREAD

**Issue by JosiahCSharp** [cheat-engine/cheat-engine#2891]
As is in the title.
Running Latest Version of WINE.
Not sure if y'all cover this or if yall will fix this since im running this on WINE. (Arch Based Distro)
I assume it has something to do with there not being a way to do pointer scans on Linux yet.
If this is implementable I would love to know how to do so or learn how to do so. 
I only know a bit of python and c# and stuff like that but I understand stuff like adresses, hexadecimal, stuff like that.
It does a graphical glitch on opening the pointerscan option.
Was really bummed cause I thought it would be a better solution than GameConqueror or PINCE or ScanMem.

**Comment by cheat-engine** [comment]
Best report it to wine.  Have you tried an earlier version of WINE ?

**Comment by JosiahCSharp** [comment]
I was using an earlier version of wine 8.4 or so i believe. I then updated wine to see if that was the issue to 9.x (I’m not at my pc right now) but it still doesn’t work :/

**Comment by cheat-engine** [comment]
go to settings and disable dark mode support and restart CE. See if that makes it work

**Comment by JosiahCSharp** [comment]
huh. That fixed it. Thank you so much! I don't know why that had broke it in the first place but you are a lifesaver!
