### ISSUE TITLE
fc 24 trainer problem 

### ISSUE THREAD

**Issue by 4sm2t** [cheat-engine/cheat-engine#2897]
![Ekran görüntüsü 2024-05-05 142719](https://github.com/cheat-engine/cheat-engine/assets/168968197/5cd52def-7775-4bff-bdaa-08603c7527ef)

**Comment by cheat-engine** [comment]
Ask the person who made the table.  For some reason TraitsTab is nil, so likely it failed finding something, which is often due to game updates that change things
