### ISSUE TITLE
installer not opening.

### ISSUE THREAD

**Issue by trowingaway4cheatengine** [cheat-engine/cheat-engine#2902]
heres the bla.txt file that i saw i had to post.
[bla.txt](https://github.com/cheat-engine/cheat-engine/files/15288716/bla.txt)
it should save some time for yall.

**Comment by cheat-engine** [comment]
xhunter1.sys

**Comment by trowingaway4cheatengine** [comment]
xhunter1.sys? how do i delete that?

**Comment by trowingaway4cheatengine** [comment]
nvm i deleted it but its still not opening

**Comment by cheat-engine** [comment]
don't forget to restart windows

**Comment by fade2gray** [comment]
Might be of help - https://www.youtube.com/watch?v=XciQ7LdFmzk

**Comment by trowingaway4cheatengine** [comment]
> don't forget to restart windows (and make sure the file is gone afterwards. The drivers folder sometimes 'repairs' itself

i did, still not working

**Comment by trowingaway4cheatengine** [comment]
man whatever im making a better post describing my situation now
