### ISSUE TITLE
cheatengine75.exe not even installing, no loading bar, no nothing

### ISSUE THREAD

**Issue by trowingaway4cheatengine** [cheat-engine/cheat-engine#2904]
https://github.com/cheat-engine/cheat-engine/assets/169628999/723bb500-927f-40e0-b9e5-6d848cc0786d

antivirus is off, vpn is off, proxy isnt installed, heres my bla.txt 
[bla.txt](https://github.com/cheat-engine/cheat-engine/files/15328629/bla.txt)

**Comment by cheat-engine** [comment]
Is reputation based protection and PUP protection also disabled ?

**Comment by trowingaway4cheatengine** [comment]
> Is reputation based protection and PUP protection also disabled ?

yes it is

**Comment by cheat-engine** [comment]
your driverlist still shows that webroot is running.  Webroot is known to stop CE from executing, especially when you close the GUI part, but not the kernel part

**Comment by trowingaway4cheatengine** [comment]
> your driverlist shows that webroot is still running. Webroot is known to stop CE from executing, especially when you close the GUI part, but not the kernel part, causing all notifications to be thrown away, while it just blocks whatever if doesn't like

how do i stop that from happening?

**Comment by trowingaway4cheatengine** [comment]
> your driverlist shows that webroot is still running. Webroot is known to stop CE from executing, especially when you close the GUI part, but not the kernel part, causing all notifications to be thrown away, while it just blocks whatever if doesn't like

ok thanks! uninstalled webroot and it worked ty!

**Comment by fade2gray** [comment]
@trowingaway4cheatengine 
https://answers.webroot.com/webroot/ukp.aspx?pid=17&app=vw&vw=1&solutionid=25

**Comment by loogielv** [comment]
wow...just...wow.
