### ISSUE TITLE
Virus installed

### ISSUE THREAD

**Issue by asulwer** [cheat-engine/cheat-engine#2905]
general warning is that we should ignore when windows complains there is a virus included.  should have listened to windows because there is.  McAfee and RAV garbage was installed despite me clicking no do not install

**Comment by cheat-engine** [comment]
The installer does not install that unless you click accept.

You either got it from somewhere else, or you misclicked the decline button

**Comment by asulwer** [comment]
i specifically chose NOT to install anything but it still did.  sounds like something is wrong with the installer or the choice does nothing.  something to look into.  i can post a video of the install process in a vm so you can see how incorrect your statement is?

**Comment by cheat-engine** [comment]
You can.  I also just installed it on both my main system and a vm and nothing extra got installed

make sure you download from cheatengine.org  and not some other site

**Comment by Eronana** [comment]
agree, it is totally fucking virus. You have tied the virus to profit, you should be ashamed.
