### ISSUE TITLE
Tutorial doesn't open

### ISSUE THREAD

**Issue by Void9r** [cheat-engine/cheat-engine#2906]

**Comment by Banaanae** [comment]
Please provide steps to make the issue occur, error messages etc
Also try running the following (assuming you're on windows and have v7.5 downloaded)
```
C:\Program Files\Cheat Engine 7.5\Tutorial-i386.exe
C:\Program Files\Cheat Engine 7.5\Tutorial-x86_64.exe
```

**Comment by Void9r** [comment]
There are no error messages, nothing happens when I press the tutorial button. I used this guide to download it however, could this be the issue? https://www.youtube.com/watch?v=oA6Uv7pyMY8&t=90s

**Comment by Banaanae** [comment]
Likely the tutorial wasn't compiled, while I'm not too familiar with this, I believe you need to compile [tutorial.lpi](https://github.com/cheat-engine/cheat-engine/blob/master/Cheat%20Engine/Tutorial/tutorial.lpi)

**Comment by Void9r** [comment]
That makes sense. Thanks!
