### ISSUE TITLE
MemoryRecord's DropDownValue and DropDownDescription always return nil

### ISSUE THREAD

**Issue by FreeER** [cheat-engine/cheat-engine#292]
these always returned nil in CE 6.7, presumably they need to be added in LuaMemoryRecord.pas like Offset and Child...

    property DropDownValue[index:integer]: string read getDropDownValue;
    property DropDownDescription[index:integer]: string read getDropDownDescription;

**Comment by cheat-engine** [comment]
should be fixed now
