### ISSUE TITLE
why different file size from different download sites?

### ISSUE THREAD

**Issue by Sopor-** [cheat-engine/cheat-engine#293]
If i download [CheatEngine67.exe](http://cheatengine.org/downloads.php) i get a file size of `12 136 192 bytes` but if i download [CheatEngine67.exe](https://github.com/cheat-engine/cheat-engine/releases) i get a file size of `12 024 624 bytes`. As you can see it is not the same file. The properties of the file will both show 6.7.0.0.

**Comment by cheat-engine** [comment]
The installers are slightly different. On github it contains the 'GitHub' tag, while on cheatengine.org it contains the 'CheatEngine' tag.
also, the cheatengine.org one has a slightly more up to date install dll
But after the install the files you have should be 100% the same

**Comment by Sopor-** [comment]
Thanks for clarifying the difference.

I'm only curious. Why don't you use the github version and link it from the cheatengine.org instead of having two versions?
