### ISSUE TITLE
windows (10 pro.) rejects program after EVERY solution

### ISSUE THREAD

**Issue by Nickz443** [cheat-engine/cheat-engine#2938]
when i try everything in my power to try to stop the, "wE cAn'T aCcEsS tHe pAtH bEcUaSe jhGVuyUJHguyliyhGuyjuhGVuBGY" i need help. 
here is everything i tried:
1.Disabling Windows Firewall
2.Reinstalling
thats it

**Comment by cheat-engine** [comment]
disable windows PUP protection

**Comment by Nickz443** [comment]
oh thx

**Comment by Nickz443** [comment]
*close*
