### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [cheat-engine/cheat-engine#294]
Hi,
I'm small translator & i want translate this program into Arabic for free 
just to make program easy to use from Arab people who's not know English
thx

**Comment by cheat-engine** [comment]
Ok, find the language create a languages folder for your CE install dir.
In there, create a new folder with the language name you like.
Then copy the .po files to there (if you used a normal windows install CE, you may want to give the normal user write access to that folder, else use copy/paste of files each time you wish to test)

In that folder I recommend creating a file named "name.txt" and write the full description in there. (e.g "Arabic by Esmail") 

From that point on you can open CE and see in the settings a new languages tab, in there you can select your language to test.

To translate you need to edit the .PO files, there are some po editing tools but you can also do it by hand:
msgid contains the original string and msgstr contains the translated string.
If msgstr is empty the original string will be shown

(So do NOT change the msgid part)

Certain strings are not present in the cheatengine.po file, but are present in lclstrconsts.po
The lclstrconsts.po file belongs to the LCL that the Cheat Engine GUI is build upon

**Comment by EsmailELBoBDev2** [comment]
somethings happen(ed) with me so sorry i can't translate it :(

**Comment by EsmailELBoBDev2** [comment]
poedit say remove spaces & i did that & it's still say same words so i removed it

**Comment by EsmailELBoBDev2** [comment]
Too late sorry buddy @cheat-engine but yeah i can not translate this app (not feel i wanna to do also iam linux user now so yeah & your app is BIG xd) sorry!
