### ISSUE TITLE
Memory View BUG

### ISSUE THREAD

**Issue by hhuiwang** [cheat-engine/cheat-engine#2948]
why?
![11](https://github.com/cheat-engine/cheat-engine/assets/33827101/7f1adb7e-41b1-4882-8695-2db86037f556)

Sorry, my English is not good, so I can only present this problem in the simplest way.

**Comment by cheat-engine** [comment]
It only changes the memview addresses of the disassembler and hexview to the start of .data and EntryPoint when it has never been changed before.  Changing it on opening a process when it has been initialized is not something most people want
