### ISSUE TITLE
DropDownList few bugs

### ISSUE THREAD

**Issue by mgrinzPlayer** [cheat-engine/cheat-engine#295]
First bug. CE hangs when DropDownListLink points to other MemoryRecord which points to the first MemoryRecord. Copy below XML block into CE.
<details>
 <summary>XML code - click to expand</summary>

```xml
<?xml version="1.0" encoding="utf-8"?>
<CheatTable CheatEngineTableVersion="26">
  <CheatEntries>
    <CheatEntry>
      <ID>1</ID>
      <Description>"First"</Description>
      <DropDownListLink>Second</DropDownListLink>
      <VariableType>4 Bytes</VariableType>
      <Address>400500</Address>
    </CheatEntry>
    <CheatEntry>
      <ID>2</ID>
      <Description>"Second"</Description>
      <DropDownListLink>First</DropDownListLink>
      <VariableType>4 Bytes</VariableType>
      <Address>400510</Address>
    </CheatEntry>
  </CheatEntries>
  <UserdefinedSymbols/>
</CheatTable>
```
</details>

---
Second bug. Create three memory records, first one should have normal DropDownList, other two are linked to the first one. Now set OnDestroy method for first one, for example
```Lua
AddressList[0].OnDestroy = function() print'destroyed' end
```

Now you can do:
a) destroy third and second memrec, then destroy the first one, OnDestroy doesn't execute
b) destroy the first one, OnDestroy is executed, but, you will get endless "Access Violation" pop-up message

<details>
 <summary>image - click to expand</summary>

![obraz](https://user-images.githubusercontent.com/9157726/35197566-691ca934-fee1-11e7-839e-549c06c6156d.png)
</details>

**Comment by cheat-engine** [comment]
hmm, i don't like having a global var for something very object oriented

first bug should be fixed by not allowing that to be set (follow all links and see if it ends up the same and then deny or don't follow links ever in the implementation)

the second error is an issue with the destroy order. i'll check it out when i have time

**Comment by mgrinzPlayer** [comment]
I made something similar to AutoAssemblerPrologues in autoassembler, it is also a global var.
OK, I will remove above suggested patch from comment. Thank you.

**Comment by mgrinzPlayer** [comment]
Third bug is that field linkedDropDownMemrec is set only once. Changing DropDownLinkedMemrec via GUI or Lua doesn't refresh it. We have to save and then load CT file. Or cut and paste the memrec.

(if anyone interested, here's the [patch](https://github.com/cheat-engine/cheat-engine/compare/master...mgrinzPlayer:fixFewDDLbugs_SmallChanges?expand=1))

**Comment by mgrinzPlayer** [comment]
Slightly different idea.

Maybe a global counter: **MemRecsDestroyedCounter** which is increased by TMemoryRecord.destroy destructor
```
inc(MemRecsDestroyedCounter);
```
and every memrec linked to other memrec will have **SnapshotOfMemRecsDestroyedCounter**.


Loop detection would be something like this:
```Pascal
function TMemoryRecord.getlinkedDropDownMemrec_LoopDetected: boolean;
var mr_slow,mr_fast: TMemoryRecord;
begin
  result:=false;

  mr_slow:=linkedDropDownMemrec;
  mr_fast:=linkedDropDownMemrec;

  // Floyd’s Cycle-Finding Algorithm
  while (mr_slow<>nil) and (mr_fast<>nil) and (mr_fast.getlinkedDropDownMemrec<>nil) do
  begin
    mr_slow:=mr_slow.getlinkedDropDownMemrec;
    mr_fast:=mr_fast.getlinkedDropDownMemrec;
    mr_fast:=mr_fast.getlinkedDropDownMemrec;
    if mr_slow=mr_fast then exit(true);
  end;
end;
```

getlinkedDropDownMemrec will be like this one:
```Pascal
function TMemoryRecord.getlinkedDropDownMemrec: TMemoryRecord;
begin
  if (linkedDropDownMemrec=nil) or (MemRecsDestroyedCounter <> SnapshotOfMemRecsDestroyedCounter) then
  begin
    linkedDropDownMemrec:=TAddresslist(fOwner).getRecordWithDescription(fDropDownLinkedMemrec);
    if (linkedDropDownMemrec<>nil) and
       (linkedDropDownMemrec.getlinkedDropDownMemrec_LoopDetected=false) then
      SnapshotOfMemRecsDestroyedCounter:=MemRecsDestroyedCounter
    else
      linkedDropDownMemrec:=nil;
  end;

  result:=linkedDropDownMemrec;
end;
```

Full diff here:
https://github.com/cheat-engine/cheat-engine/compare/master...mgrinzPlayer:fixFewDDLbugs_SmallChangesV2?expand=1
