### ISSUE TITLE
Loading DBK64 twice causes BSOD on Windows 10

### ISSUE THREAD

**Issue by Andoryuuta** [cheat-engine/cheat-engine#296]
_(Originally [posted on the old mantis tracker](http://cheatengine.org/mantis/view.php?id=541), copied to here once I realized nobody has used the old tracker in a couple of months.)_

If you enable ~~any options~~ "Enable Use of the Process Watcher" under Settings->Extra (which causes DBK64 to load on CE startup), then try to start two instances of CE, it causes a BSOD.

**Steps to reproduce:**
Enable ~~something~~ "Enable Use of the Process Watcher" in Settings->Extra.
Close all instances of CE.
Open 1st instance of CE (Will load fine and display the "DBK64 LOADED" text).
Open 2nd instance of CE (Will quickly flash "DBK64 LOADED" before BSOD happens).

**Version information:**
Cheat Engine version: 6.7 release from website (Not custom build from source)
OS: Windows 10 Pro x64
OS Version: 1709/Fall Creators Update
OS Build: 16299.192

And here is the [crash minidump](https://github.com/cheat-engine/cheat-engine/files/1677468/minidump.zip) if you're into that sort of thing..

**Comment by cheat-engine** [comment]
anything specific you enable in settings? Or just kernelmode openprocess ?

**Comment by Andoryuuta** [comment]
Oops, I thought this happened with any of the options under Settings->Extra, but it actually only causes a BSOD with "Enable the use of Process Watcher" checked. The other options do not seem to effect it at.

**Comment by cheat-engine** [comment]
should be fixed
