### ISSUE TITLE
 Compilation Error

### ISSUE THREAD

**Issue by codeXXjs** [cheat-engine/cheat-engine#2976]
Description:
I am encountering a compilation error when trying to build the project. The program cannot be compiled due to the following error message. I followed the instruction guide. Chose the targeted build and also many compile top 3.

    OS: Windows 10
    Version: 22H2

![Capture](https://github.com/user-attachments/assets/2547f913-4a09-488c-ad67-ccbe15b01fef)

**Comment by fade2gray** [comment]
You are using the incorrect version of Lazarus - try reading the build instructions again.

https://github.com/cheat-engine/cheat-engine#basic-build-instructions

![Screenshot 2024-01-18 164529](https://github.com/cheat-engine/cheat-engine/assets/1332009/f15d44a8-1c6c-49c6-ad29-f8c614b35afe)

**Use Lazarus 2.2.2 or Lazarus 2.2.6.**

**Comment by codeXXjs** [comment]
> You are using the incorrect version of Lazarus - try reading the build instructions again.
> 
> https://github.com/cheat-engine/cheat-engine#basic-build-instructions
> 
> ![Screenshot 2024-01-18 164529](https://private-user-images.githubusercontent.com/1332009/297819081-f15d44a8-1c6c-49c6-ad29-f8c614b35afe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MDkyMTcsIm5iZiI6MTcyMzQwODkxNywicGF0aCI6Ii8xMzMyMDA5LzI5NzgxOTA4MS1mMTVkNDRhOC0xYzZjLTQ5YzYtYWQyOS1mOGM2MTRiMzVhZmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTFUMjA0MTU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTZmMmQ0OGNmYTRlMDkzNzgxNWU0ZDY2NzkzMDcyOGE0YWM5YWVjN2EwNmZmNGIxNDQ1YTBhZGE1YTM4MTdlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.l2EDAhNVfxzDcFx3xR7uOghF5d9yUdqOn2XW8PpqIXg)
> 
> **Use Lazarus 2.2.2 or Lazarus 2.2.6.**

Awesome. It works flawless. You were right, I download the wrong x64 file. Thanks for the headsup
