### ISSUE TITLE
cepluginsdk.h CEP_PLUGINTYPE6ONPOUP is given pointer as first argument but defined as ULONG.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [cheat-engine/cheat-engine#298]
The current definition for the selectedAddress is not a pointer, however ```TPluginHandler.handledisassemblerContextPopup(address: ptruint)``` in plugin.pas provides a pointer to this call.
```
typedef BOOL (__stdcall *CEP_PLUGINTYPE6ONPOPUP)(ULONG selectedAddress, char **addressofname, BOOL *show);
```
```CEP_PLUGINTYPE6``` callback has ```ULONG * selectedAddress```
```CEP_PLUGINTYPE7``` has ```ULONG address```

Should these be made more consistent with each other?

Why a pointer and not just the address value, is there other data to access there or over-write?

**Comment by cheat-engine** [comment]
those should be UINT_PTR
