### ISSUE TITLE
I Can't Find The Right Process To Edit

### ISSUE THREAD

**Issue by Choices-Dark** [cheat-engine/cheat-engine#2980]
I was playing an Easy Anti Cheat Game Called "My Hero Ultra Rumble", Which Has Garbage Security System, But Every time I go try to select a process/Window/Application It won't just appear, I selected ALL in the scan option and searched for any random value to check if it worked, i tried "1", nothing did appear in the memory address, which was weird since the cheat engine i used is undetected and compiled by lazarus (Cheat Engine 7.5 86_64-SSE4-(Something here) ) and it worked with any other normal .exe file, Thanks In Advance

**Comment by cheat-engine** [comment]
you have to disable easy anti cheat

**Comment by Choices-Dark** [comment]
> you have to disable easy anti cheat

It doesn't detect that i am using cheat engine at all so i don't see the need of that, What i mean by my issue is that I can't find the memory of the game since there are 3 different processes to choose from, And none of them work as just search for value and it works, sorry for the inconvenience

**Comment by cheat-engine** [comment]
enable kernelmode openproces and ReadProcessMemory 

i assume you've also compiled an undetected dbk64 and codesigned it with your own certificate?

**Comment by Choices-Dark** [comment]
Yeah I did, I Changed It to something Very Different than Cheat engine, But Since I am Kinda New To This Cheating Process And All That Where To Enable Exactly Kernelmode openproces and readprocessmemory? I know they're in settings but where exactly? thanks in advance
![image](https://github.com/user-attachments/assets/7583c199-da9e-4521-b8f3-1bd026d7f00d)

**Comment by cheat-engine** [comment]
settins-extra

**Comment by Sencaid** [comment]
> settins-extra

WHY DONT YOU ANSWER ME!? @cheat-engine

**Comment by Choices-Dark** [comment]
> settins-extra

So Everything Was Supposed To Work Fine, "Supposed To", Everytime I did Kernelmode Debugger it just said I miss the driver, Which is actually weird, I have the latest version of CE, It is kinda weird from now on, Should I just re-build/re-compile another version of cheat engine or what?
Note:Read/Write Process Memory Helped a bit, The Cheat Engine was so close to Achieve the expected results but sadly enough, nothing did appear.
![image](https://github.com/user-attachments/assets/790c798d-ca29-42d4-8460-826de4c37b0e)

**Comment by Choices-Dark** [comment]
Update: It appears that i had to do some settings to ACTUALLY bypass the Easy anti cheat, Furthermore into my research, It worked just fine! I found all of the addresses that were in the game,
Anyone reading this to fix the same issue, here's a simple guide:
1.Go to your myheroultrarumble's steam dictionary and then to a folder in it named "Easy Anti Cheat"
2.Open Settings.json Using Notepad/Notepad++
3.Change the 2nd, 3rd and 4th value by adding any random number/letter. Example:It is (Not actually in settings.json) 2547b, Just add any number/letter so it becomes (Not the same, Just add anything) 23547b and so on.
4.run cheat engine AFTER you run MHUR
5.Select Mhur [Application] In the process manager
6.Search for the value
7.Done! Congratulations on your simple work!
