### ISSUE TITLE
aborted

### ISSUE THREAD

**Issue by xunni1000** [cheat-engine/cheat-engine#299]
1,select a process (any)
2, [menu] file -- generate ... table
3, select output --- Script only  (Modify 'EXE' to 'Script only')
4, click button [Generate trainer ] 
5, click button  [Execute script] ,  auto make  a CEtrainer  window
6, click 'CEtrainer'  close button.
7, cheat engine.exe aborted.(It has not been saved yet)

**Comment by FreeER** [comment]
so don't execute code that can close CE and then do something that causes that code to close CE?

The form editor ("Design userinterface manually") does use a stub function that prevents CE from closing but CE doesn't use a special way of executing the code when you generate the script; So when you click execute all it knows is you gave it some code you wanted to run and in that case it shouldn't be messing around with the code you gave it...

**Comment by mgrinzPlayer** [comment]
Why do you even do step 5? Just close this window (instead of clicking "execute script").
Then close "trainer generator" window. Then save as CT file.
