### ISSUE TITLE
your cpu must be able to run dbvm to use this function

### ISSUE THREAD

**Issue by supundhanujaya** [cheat-engine/cheat-engine#2995]
I compiled the dbk64 driver and the cheat engine. Now when I open cheat engine it says dbk64 loaded in the corner of the screen but when I check about it says “your cpu must be able to run dbvm to use this function”

I have core isolation turned off and also Hyper-V 
Then I run a lua script in cheat engine someone gave to another one to execute. So I copied and executed it. Right now I didn’t remember the script but the result was in my case “Dbvm should work” 

please help me to solve this problem

another thing I have to address is when I install the official cheat engine by the given installer everything works fine.. the issue is in my custom build as I think. I hope you guys will help me to overcome this issue..

**Comment by cheat-engine** [comment]
compile cheat engine in release mode, not debug as that compiled without dbvm support

**Comment by fade2gray** [comment]
Try compiling without selecting - "Release mac, Release, Debug". I don't have issues with running CE with a custom driver when just compiling the first three.

**Comment by supundhanujaya** [comment]
The problem solved. Thank you guys very much. love you!
