### ISSUE TITLE
Address number to string conversion treated as hex instead of decimal

### ISSUE THREAD

**Issue by FreeER** [cheat-engine/cheat-engine#300]
`mr.Address = 0x6F` or `mr.Address = 111` will treat it as if you gave mr.Address = '111' , not '6F'

This means that passing the result of getAddress back to getAddress will probably result in a different address (0-9 will work though lol)...

```lua
local result = getAddress(getAddress('6F'))
print(('%X'):format(result))
```

Should result in `6F` but actually results in `111`.

**Comment by cheat-engine** [comment]
getAddress expects a string, so it converts any input it gets to a string and then processes it.

But it's being filtered now. Also, in the meantime you can do:
```
local originalGA=getAddress
function getAddress(v)
  if type(v)=='number' then
    return v
  else
    return originalGA(v)
  end
end
```

**Comment by cheat-engine** [comment]
the bug is using getAddress for a memoryrecord's interpretable address string, but i'll also add a check for int for setting the memrec address string using an integer
