### ISSUE TITLE
http://www.cheatengine.org/ DL links hijacked

### ISSUE THREAD

**Issue by huntergregal** [cheat-engine/cheat-engine#301]
^^^

**Comment by cheat-engine** [comment]
it's ok

**Comment by BetaLeaf** [comment]
Bull fucking shit. How is it ok to have your main download hijacked?

**Comment by mgrinzPlayer** [comment]
https://github.com/cheat-engine/cheat-engine/issues/108
https://github.com/cheat-engine/cheat-engine/issues/217
https://github.com/cheat-engine/cheat-engine/issues/270
https://github.com/cheat-engine/cheat-engine/issues/293
