### ISSUE TITLE
memory block symbol

### ISSUE THREAD

**Issue by DeHby** [cheat-engine/cheat-engine#3013]
![image](https://github.com/user-attachments/assets/41b2caf8-76ba-424d-b25d-a3861fbcd35c)
## Hello, I have a suggestion. Why can't I register a memory block symbol? Similar to registerModule(name,address,size), I am reversing some dynamically loaded modules. They use PEB break links to hide their symbol information. If I use (registerModule), I can solve these problems.

**Comment by cheat-engine** [comment]
```lua
local sl=createSymbolList()
sl.addModule('bla.dll',"c:\\bla.dll", 0x10000,65536,true)
sl.addSymbol('bla.dll','test',0x10010,8)
sl.register()
```

now look at address 10010

**Comment by DeHby** [comment]
> ```lua
> local sl=createSymbolList()
> sl.addModule('bla.dll',"c:\\bla.dll", 0x10000,65536,true)
> sl.addSymbol('bla.dll','test',0x10010,8)
> sl.register()
> ```
> 
> now look at address 10010

I tried it and it worked great, thank you very much.
