### ISSUE TITLE
A BIT OF HELP

### ISSUE THREAD

**Issue by Aleejoh13wpepperysalt** [cheat-engine/cheat-engine#3019]
Is this safe and if so how do i install it

**Comment by Banaanae** [comment]
Yes, but your antivirus may say it is, this is a false positive
https://cheatengine.org/downloads.php - When you run the installer make your you press decline on all optional offers

**Comment by Aleejoh13wpepperysalt** [comment]
So could you run me through the steps as I don’t really understand how to download from this but I heard this is safer than the website
