### ISSUE TITLE
Cheat Engine problem in BO 3

### ISSUE THREAD

**Issue by Kalifek** [cheat-engine/cheat-engine#303]
Hi, I have a problem. 
When I start the game, next I run Cheat Engine when CE is working my game was closed.
I dont know what i must do with this. I was looking for any guid to fix this and  I did not find.
PLs Help me

**Comment by JasonGoemaat** [comment]
This might be better discussed on [the forum](http://forum.cheatengine.org/viewforum.php?f=1), I'm sure you'll need to provide more information...  If it happens as soon as you open CE then it may be detecting CE and closing?  What if you start CE first and try to start the game?
