### ISSUE TITLE
latest source dbvm native trace error

### ISSUE THREAD

**Issue by qwer0123456** [cheat-engine/cheat-engine#3031]
<img width="172" alt="dbvm native trace" src="https://github.com/user-attachments/assets/64d0c385-fc69-4080-9c87-a20d9cfaa4d5">

DBVM Native Break and Trace throws an error when built from the latest sources

Unnamed: Unhandled exception: Access violation (Exception class EAccessViolation) (tried to write to address 00000000)
The current table has been saved to ExceptionAutoSave_TestFile.ct

ct is automatically saved with an error message that the address cannot be referenced.

There is no problem with version 7.5

The latest version(source build dbk,vmdisk,gui) is on the source date of October 21, 2024.

**Comment by qwer0123456** [comment]
add a gdbserver interface

[68e0399a4df51d8aac7a9698aab3fb2aef73a1d2](https://github.com/cheat-engine/cheat-engine/tree/68e0399a4df51d8aac7a9698aab3fb2aef73a1d2)

doesn't work after adding gdb interface DBVM Native Trace Crash

check Darkbyte

**Comment by qwer0123456** [comment]
next ce version fix?

dbvm native trace check -> Waiting for trace to start -> target process data fix -> Access violation write to address 00000000)

dbvm native trace no check -> Waiting for trace to start -> target process data fix -> trace result success

gdbserver interface add -> crash vm trace

**Comment by qwer0123456** [comment]
lazarus debug mode check

maybe type casting error?

var
c: _CONTEXT;-> add

my fix 
d.context := @c; -> add type casting
PContext(d.context)^.P1Home:=basic^.FSBASE; //just using these field for storage
PContext(d.context)^.p2home:=basic^.GSBASE;
PContext(d.context)^.p3home:=basic^.CR3;

vm trace no error

**Comment by qwer0123456** [comment]
but close trace

destructor TTraceDebugInfo.destroy;
begin
 if context<>nil then
   freememandnil(context); -> context pointer remove errror
end;

**Comment by cheat-engine** [comment]
```pascal
...
          d:=TTraceDebugInfo.Create;
//add this code
          d.context:=getmem(sizeof(TContext)+64);
          {$ifdef cpu64}
          d.contexthandler:=ContextInfo_X86_64;
          {$else}
          d.contexthandler:=ContextInfo_X86_64;
          {$endif}
//^^

          d.instructionsize:=a-basic^.RIP;     
...
```
