### ISSUE TITLE
ceserver not working 3

### ISSUE THREAD

**Issue by 1392-github** [cheat-engine/cheat-engine#3039]
#3037
1 - You have granted the necessary permissions
2 - The device is not rooted
3 - It worked fine on Nox (not rooted)
4 - I'm using Android 8

**Comment by 1392-github** [comment]
5 - all app not working

**Comment by cheat-engine** [comment]
it's something specific on your phone or something you do as even ping fails in the run-as environment 

can you upgrade your phone to android 9 ?

**Comment by 1392-github** [comment]
I upgraded to Android 9 and it was resolved

**Comment by 1392-github** [comment]
Why Can't use Android 8?

**Comment by cheat-engine** [comment]
no idea. could have been a bug in android 8.  All I know is that android 7 works a little, but not that good.  I never tried android 8, but android 9 tends to work for most things
