### ISSUE TITLE
out of memory?

### ISSUE THREAD

**Issue by QwertyCoolMT** [cheat-engine/cheat-engine#304]
having this error pop up when trying to scan a larger game. 

is this just not possible? what should i do?

![ce problem](https://user-images.githubusercontent.com/21363668/36435881-d3a5ccd4-1630-11e8-873a-af0185fbe075.png)

came across this thread http://www.cheatengine.org/forum/viewtopic.php?t=492656&sid=1248de227f2a8862dd36dceeac5df970 but increading virtual memory to 9kmb didnt help. maybe i need more?

**Comment by cheat-engine** [comment]
setup your pagefile so it can grow.  normally the pagefile is in c: so make sure there is still a lot of free space (you may need to reboot a few times)

how much RAM does your system have ?

**Comment by QwertyCoolMT** [comment]
not sure what fixed it, but i added 10kmb to 20kmb to the paging file and after a couple restarts and playing around in cheat engine /windows settings it worked.
