### ISSUE TITLE
[Version] section should specify PnpLockdown=1 to prevent externaI apps from modifying installed driver files

### ISSUE THREAD

**Issue by sd685-hue** [cheat-engine/cheat-engine#3056]
how to handle this , when i  compile dbk driver  !  thank you!
it`s log:
TAutoSizeCtrlData.FixControlProperties :TCECheckBox a=akTop old=:TEdit new=nil
Exception I don't know what you did, you didn't crash, but you also didn't load DBVM
  Stack trace:
  $00000000004BA434  LOADDBVMIFNEEDED,  line 1626 of NewKernelHandler.pas
  $00000000005240C9  LBLDBVMCLICK,  line 214 of aboutunit.pas
  $00000000004434AF  MOUSEDOWN,  line 4514 of include/control.inc
  $000000000043D953  DOMOUSEDOWN,  line 2327 of include/control.inc
  $000000000043E049  WMLBUTTONDOWN,  line 2506 of include/control.inc
  $0000000000411451
  $000000000043D84F  WNDPROC,  line 2287 of include/control.inc
  $000000000043C178  PERFORM,  line 1617 of include/control.inc
  $000000000042F5F3  ISCONTROLMOUSEMSG,  line 4772 of include/wincontrol.inc
  $0000000000430D0A  WNDPROC,  line 5394 of include/wincontrol.inc
  $00000000009950E3  DELIVERMESSAGE,  line 112 of lclmessageglue.pas
  $0000000000832351  DOWINDOWPROC,  line 2607 of win32callback.inc
  $0000000000832B58  WINDOWPROC,  line 2772 of win32callback.inc
  $00000000009894D4  GROUPBOXWINDOWPROC,  line 616 of win32wsstdctrls.pp
  $00007FF9CB668241
  $00007FF9CB667D01
  $0000000000833DE4  APPPROCESSMESSAGES,  line 415 of win32object.inc
[TWin32WidgetSet.Destroy] WARNING: There are 2 TimerInfo structures left, I'll free them

**Comment by cheat-engine** [comment]
did you compile the driver using the nosig build?
and is cheatengine compiled in release mode ?

and is vmdisk.img compiled and present in the bin folder of ce ?

**Comment by sd685-hue** [comment]
thank you！ i forget vmdisk.img
