### ISSUE TITLE
Fix AA Templates jumping to 'newmem' instead of 'code' label

### ISSUE THREAD

**Issue by JasonGoemaat** [cheat-engine/cheat-engine#306]
A couple of the autoassembly templates have had a bug introduced somewhere between 6.5 and 6.7 where the injection jumps to the 'newmem' label instead of the 'code' label.  They are separate like this so you can put some data before your code if you wish and use the existing 'newmem' label, and have it be aligned at the start of the memory allocation (4k aligned) automatically.  I've noticed since 6.7 that if I put data there it crashes the game because the default jmp now jumps to it instead of the code label.

**Comment by FreeER** [comment]
it used to jmp to code? I just thought that was intentional so you can put a cmp before the original code to skip it and therefore put data _after_ the code (where it never has a chance of being run unless you didn't return or jumped somewhere outside code anyways) lol

**Comment by JasonGoemaat** [comment]
Ah, I see how that would work too...  The original templates just used to have newmem until I added the code label for the aob and full injection templates so you would have to create your own label for jumping anyway.  

I just figured using newmem for data was handy because it is at the start of the block it will always be aligned (required for some SSE instructions and always faster to access aligned data) and you could either just use `[newmem]` or put your data there:

```
newmem:
  dd (float)100.0

code:
  movss xmm0,[newmem]
  movss Game.exe+019381f1,xmm0 // original code
  jmp return
```

Versus using a later address and assuming your code wont' get long enough to reach it:
```
newmem:
  movss xmm0,[newmem+400]
code:
  movss Game.exe+019381f1,xmm0 // original code
  jmp return

newmem+400:
  dd (float)100.0
```

On the other hand I don't usually add a memory address to enable/disable the cheat, I just enable or disable the script...  I think you're talking about something like this:

```
label(enableCheat)
label(skipCheat)
registerSymbol(enableCheat)
newmem:
  dd (float)100.0
enableCheat:
  dd 0

code:
  cmp [enableCheat],1
  jne skipCheat
  movss xmm0,[newmem]
skipCheat:
  movss Game.exe+019381f1,xmm0 // original code
  jmp return
```

versus
```
label(skip)
label(enableCheat)
registerSymbol(enableCheat)

newmem:
  cmp [enableCheat],1
  jne code
  movss xmm0,[newmem+400]
code:
  movss Game.exe+019381f1,xmm0 // original code
  jmp return

newmem+400:
  dd (float)100.0
enableCheat:
  dd 0
```

If people are more used to the jmp to newmem that's fine, but what do you think about changing the 'code' label to something like 'original_code' or `relocated_code` and maybe putting a comment after `newmem:` like `// injection will jump here`?  Maybe add a `data` label and maybe comment too?

```
newmem+800:
data:
  // put data here
```

**Comment by FreeER** [comment]
"Versus using a later address and assuming your code wont' get long enough to reach it:" I always used a label so that was never an issue, CE'd automatically put it after the code that way. I haven't have had an issue with alignment but there is the `align` instruction which should work when it does matter.

The check it could be used for just player vs enemy compares eg. godmode.

As for how it should be, any of those are fine to me, I think the most... explicit would be

```
newmem:
code:
  // original code
  <hooked code>

align 10 // aligns data to 16 bytes
data:
  // put data (like doubles you have to load from a memory address) here

address:
  jmp code
  <nops>
```

leaving it as code rather than original code because it is pretty common for it to be changed and then "originalcode" wouldn't apply but many people probably wouldn't bother changing the name.

**Comment by JasonGoemaat** [comment]
Ah, didn't know about `align`, that makes it easier.  Sounds like you like it the way it is so I'll close the issue.
