### ISSUE TITLE
Making DBVM More stable?

### ISSUE THREAD

**Issue by QwertyCoolMT** [cheat-engine/cheat-engine#311]
Is there anything I can do to get DBVM working more stable on win10 with a core i7 intel CPU 6 cores?

Ive seen people using this before without problems but i haven't been able to get it running even once.

I've done evrything on this page except for reducing # cores http://wiki.cheatengine.org/index.php?title=DBVM

any other advice?

**Comment by cheat-engine** [comment]
uninstall all updates after (and including) KB4056891 
or get an older windows version like 7

**Comment by cheat-engine** [comment]
get ce 6.8
