### ISSUE TITLE
DBVM run BlueScreen

### ISSUE THREAD

**Issue by ghost** [cheat-engine/cheat-engine#312]
i'm download new cheat engine source (Because update DBVM 11) and build dbvm and get vmdisk.img and build driver then get dbk.sys and build cheat engine and Enable DBVM Click then box showing the blue screen...
  BCCode:	101
  BCP1:	0000000000000031
  BCP2:	0000000000000000
  BCP3:	FFFFF880009EF180
  BCP4:	0000000000000001
  OS Version:	6_1_7601
  Service Pack:	1_0
  Product:	256_1

what can i do?

(I am not good at English because I am Korean.)

**Comment by cheat-engine** [comment]
That means it froze.

did you make sure you unloaded any previous driver before compiling? Try rebooting before build as well
and copy dbk.sys to dbk64.sys

besides that if you don't have a serial port or jtag capability on your system there's not much you can do except run this code and post the results: (Assuming you have an intel cpu.  DBVM 11 will likely not work with AMD at this time)
```
dbk_initialize()
IA32_VMX_BASIC=dbk_readMSR(0x480)
IA32_VMX_PINBASED_CTLS=dbk_readMSR(0x481)
IA32_VMX_PROCBASED_CTLS=dbk_readMSR(0x482)
IA32_VMX_EXIT_CTLS=dbk_readMSR(0x483)
IA32_VMX_ENTRY_CTLS=dbk_readMSR(0x484)
IA32_VMX_ENTRY_MISC=dbk_readMSR(0x485)
IA32_VMX_CR0_FIXED0=dbk_readMSR(0x486)
IA32_VMX_CR0_FIXED1=dbk_readMSR(0x487)
IA32_VMX_CR4_FIXED0=dbk_readMSR(0x488)
IA32_VMX_CR4_FIXED1=dbk_readMSR(0x489)

print(string.format("IA32_VMX_BASIC=%.16x",IA32_VMX_BASIC))
print(string.format("IA32_VMX_PINBASED_CTLS=%.16x",IA32_VMX_PINBASED_CTLS))
print(string.format("IA32_VMX_PROCBASED_CTLS=%.16x",IA32_VMX_PROCBASED_CTLS))
print(string.format("IA32_VMX_EXIT_CTLS=%.16x",IA32_VMX_EXIT_CTLS))
print(string.format("IA32_VMX_ENTRY_CTLS=%.16x",IA32_VMX_ENTRY_CTLS))
print(string.format("IA32_VMX_CR0_FIXED0=%.16x",IA32_VMX_CR0_FIXED0))
print(string.format("IA32_VMX_CR0_FIXED1=%.16x",IA32_VMX_CR0_FIXED1))
print(string.format("IA32_VMX_CR4_FIXED0=%.16x",IA32_VMX_CR4_FIXED0))
print(string.format("IA32_VMX_CR4_FIXED1=%.16x",IA32_VMX_CR4_FIXED1))

if (IA32_VMX_PROCBASED_CTLS & (1<<63))~=0 then
  IA32_VMX_PROCBASED_CTLS2=dbk_readMSR(0x48b)
  print(string.format("IA32_VMX_PROCBASED_CTLS2=%.16x",IA32_VMX_PROCBASED_CTLS2))

  if ((IA32_VMX_PROCBASED_CTLS2 & (1<<33))~=0) or ((IA32_VMX_PROCBASED_CTLS2 & (1<<37))~=0) then
    IA32_VMX_EPT_VPID_CAP=dbk_readMSR(0x48c)
    print(string.format("IA32_VMX_EPT_VPID_CAP=%.16x",IA32_VMX_EPT_VPID_CAP))
  end
end

if (IA32_VMX_BASIC & (1<<55))~=0 then
  IA32_VMX_TRUE_PINBASED_CTLS=dbk_readMSR(0x48d)
  IA32_VMX_TRUE_PROCBASED_CTLS=dbk_readMSR(0x48e)
  IA32_VMX_TRUE_EXIT_CTLS=dbk_readMSR(0x48f)
  IA32_VMX_TRUE_ENTRY_CTLS=dbk_readMSR(0x490)
  print(string.format("IA32_VMX_TRUE_PINBASED_CTLS=%.16x",IA32_VMX_TRUE_PINBASED_CTLS))
  print(string.format("IA32_VMX_TRUE_PROCBASED_CTLS=%.16x",IA32_VMX_TRUE_PROCBASED_CTLS))
  print(string.format("IA32_VMX_TRUE_EXIT_CTLS=%.16x",IA32_VMX_TRUE_EXIT_CTLS))
  print(string.format("IA32_VMX_TRUE_ENTRY_CTLS=%.16x",IA32_VMX_TRUE_ENTRY_CTLS))
end
```

**Comment by cheat-engine** [comment]
what is the output of that script I posted

**Comment by komjun** [comment]
IA32_VMX_BASIC=00da040000000012 
IA32_VMX_PINBASED_CTLS=0000007f00000016 
IA32_VMX_PROCBASED_CTLS=fff9fffe0401e172 
IA32_VMX_EXIT_CTLS=007fffff00036dff 
IA32_VMX_ENTRY_CTLS=0000ffff000011ff 
IA32_VMX_CR0_FIXED0=0000000080000021 
IA32_VMX_CR0_FIXED1=00000000ffffffff 
IA32_VMX_CR4_FIXED0=0000000000002000 
IA32_VMX_CR4_FIXED1=00000000001767ff 
IA32_VMX_PROCBASED_CTLS2=00007cff00000000 
IA32_VMX_EPT_VPID_CAP=00000f0106334141 
IA32_VMX_TRUE_PINBASED_CTLS=0000007f00000016 
IA32_VMX_TRUE_PROCBASED_CTLS=fff9fffe04006172 
IA32_VMX_TRUE_EXIT_CTLS=007fffff00036dfb 
IA32_VMX_TRUE_ENTRY_CTLS=0000ffff000011fb

**Comment by cheat-engine** [comment]
hmm, can't really see much different except your system doesn't support xsave in vm mode, but I assume that is because the cpu doesn't support it

but yeah, if you wish to pinpoint what goes wrong you'll need a serial port

**Comment by komjun** [comment]
Okay. I'll use a different version while I try to get it fixed.
and my cpu is I5-4590

**Comment by cheat-engine** [comment]
what could work is running dbvm from boot and check what the display shows. you just need to low level write vmdisk.img to a usb disk and then boot of it

**Comment by komjun** [comment]
umm... i'm boot vm with vmdisk.img and showing it

![image](https://user-images.githubusercontent.com/26819203/36759434-b82a2c9a-1c5a-11e8-8d8c-38f560bc59cb.png)

**Comment by komjun** [comment]
anyway where i can see the siggen.exe? it's not include in opensource 

buildsigs.bat
..\..\dbkkernel\siggen\siggen.exe kernelmoduleunloader-i386.exe
..\..\dbkkernel\siggen\siggen.exe cheatengine-i386.exe
..\..\dbkkernel\siggen\siggen.exe cheatengine-x86_64.exe
..\..\dbkkernel\siggen\siggen.exe vmdisk.img

**Comment by cheat-engine** [comment]
press 0 to launch DBVM

as for siggen you don't need that. You should use ce.bat to compile, not ces

**Comment by komjun** [comment]
Since that is a VM,i couldn''t launch DBVM
I will try another computer when I have time.

**Comment by komjun** [comment]
IA32 FEATURE CONTROL=0000000000000005
IA32_FEATURE_CONTROL is locked (value=0000000000000005). (Disabled in bios?) 
revision id=18
IA32_FEATURE_CONTROL=0000000000000005
IA32_VMX_CRO_FIXEDO=0000000080000021 IA32 VMX CRO FIXED1=00000000ffffffff
IA32_UMX CR4_FIXEDO=0000000000002000 IA32 VMX_CR4_FIXED1=00000000001767ff
CRO=0000000080010031 (Should be 0000000080010031)
CR4=0000000000002230 (Should be 0000000000002230) Vmxon_region=00000000dd4d0000
0:Checks successfull. Going to call Vmxon
0: Vmxon success
0: calling Vmclear
0: calling Vmptrld
0: Vmptrld successful. Calling setupVMX
IA32 UMX_BASIC=00da040000000012
IA32 UMX_PINBASED_CTLS=0000007F O0000016 IA32 UMX_PROCBASED_CTLS=fff9fffe0401e172
IA32 UMX_SECONDARY PROCBASED_CTLS=00007cff00000000
IA32 UMX_EXIT_CTLS=007fffffO0036dff
IA32 UMX_ENTRY CTLS=0000ffff000011f
IA32 UMX_MISC=00000000300481e5
0: Virtual Machine configuration successful. Launching …
Calling Vmax loop with currentcpu info=0000001000000000
Last display before entering Vmx

**Comment by cheat-engine** [comment]
thanks.
it shows it doesn't even get to the clearscreen routine, and no spontaneous reboot, so the emulated system never runs a single instruction.

that means the guest/host or system config is wrong (likely setting bits that should have been 0)
i'll go through this, and will write a config that shows more on the screen with pagebreaks
(in common.h you can define DISPLAYDEBUG , but right now it won't pause when the screen is full, but you could try that as well)

**Comment by komjun** [comment]
then what can i do?

**Comment by cheat-engine** [comment]
the github souce currently contains a version that you can compile using `make displaydebug`
It will send the info it would normally send to the serial to the display, and also accepts keypressed

I do recommend taking pictures instead of typing it over, there is a LOT of data
(The important part is the stuff after : `Last display before entering Vmx`)
