### ISSUE TITLE
Cheat Engine installs malware/crapware without consent

### ISSUE THREAD

**Issue by Moltresrider** [cheat-engine/cheat-engine#322]
Cheat Engine 6.7 installs malware and junkware onto my system without notifying me, nor giving me any option to opt out of this install. It silently installed Chromanium, silently changed my browser settings, and there was NOTHING about this during setup

**Comment by FreeER** [comment]
yes there was, see the other half dozen people who didn't bother the read the installer instructions and then went blaming other people in githubs issues.

**Comment by gundz** [comment]
Well, i just installed on osx and same here, i DID uncheck all the boxes and still silently installed mackeeper.

**Comment by mgrinzPlayer** [comment]
"uncheck all the boxes" is not enough 🗡

http://forum.cheatengine.org/viewtopic.php?t=604626

**Comment by shinodem** [comment]
Now they implement this thing https://www.virustotal.com/ru/file/f4d13a9d3e12c4c1524e87d369ff8e1e9a1c4f82c72211bd05fa0283640702d1/analysis/1552230811/
what is blocking with avira

**Comment by pedro2555** [comment]
@FreeER what a piece of shit, that is what that is.

**Comment by Melvasul** [comment]
Segurazo is still into the installer and the way to not install it is not clear, change this installer.

**Comment by pedro2555** [comment]
What stupid discussion, this a freaking elephant in the room. The installer has malware, stop with smoke screen.

The installer has malware. Is it hard to understand?
