### ISSUE TITLE
Ultimap no branch targets.

### ISSUE THREAD

**Issue by entiproski** [cheat-engine/cheat-engine#323]
hi, im using ultimap on cheat engine 6.7 I am trying to look for functions in a game but for some reason it just stays at zero, I have a 4790k 28gb of ram, and im dual booting windows 10 1709 and windows 7 ultimate sp1, which is what im currently using to use dbvm v10, any suggestions or reasons? ill be willing to try them. also, branch is spelt wrong in ultimap.

**Comment by cheat-engine** [comment]
Try running the target process as an administrator (I'm not sure if windows 7 has gotten the same shadow KVA patch as windows 10 did, but if it did, you may have to undo that patch)
