### ISSUE TITLE
Ultimap2 sometimes make BSOD

### ISSUE THREAD

**Issue by BlackLuny** [cheat-engine/cheat-engine#325]
My Windows version: WIN 10 Home 1709, have packed Specture &Meltdown patches. I am use the last version of CE and dbk64.sys(Compiled with VS 2017,You just added).But When I use Ultimap2, Sometime it's OK!But sometimes it will BSOD with PROFILER CONFIGURATION ILLEGAL error code.In a game,It will do BSOD after some secondes while recording.But on other game, It not, or sometime will BSOD with the same   Code.Could you have a look at it? Thx.

**Comment by cheat-engine** [comment]
do you also use the current CE build ? if not the new 'nopmi' flag may be set to a random value.

also, in that windows build you can not use ranges unless you disable PMI's, or attach a kernelmode debugger to the system.

**Comment by BlackLuny** [comment]
I also build the ce with the same git node.because if I use 6.7 you released,it will notify version mismatch. And I didn’t use the ranges list. But I use the filter out not in range.i think it will not the key reason.

**Comment by cheat-engine** [comment]
tick the option for no interrupts in ranges

**Comment by cheat-engine** [comment]
set it to write to file and no processing. or optionally suspend the process while processing.
and set ce's process to realtime priority

**Comment by BlackLuny** [comment]
I always use the ‘write to file’ and ‘no processing’,if the only way to flush trace data to file is the button ‘pause/recording’ if I tick the option nopmi?

**Comment by cheat-engine** [comment]
No, when writing to disk the flushing happens every few milliseconds

**Comment by BlackLuny** [comment]
The button is used to trigger writing to disk?

**Comment by cheat-engine** [comment]
pause/record (just like any of the other filter buttons) also triggers a write to disk, but then starts processing the data it wrote to disk (that's the % counter)

**Comment by BlackLuny** [comment]
Thx!I will look the code later. There is another problem,when I finish the ultimap2 for A process,and then attach ce to another process B, the ultimap2 can’t work anymore,the log in dbgview shows that the physical memory is zero,when I check the code I think maybe the look up in generatic table failed.

**Comment by cheat-engine** [comment]
The current version in this git now has some fixes, but not sure it it'll affect your 'illegal profiler config' issue.
On my windows build 1709 (16299.371) I can trigger as many PMI's and not BSOD, as long as I keep the "Ranges:" list empty.
Make sure you restart your system(unload won't work), as Ultimap2 can not rehook the PMI handler in windows

**Comment by BlackLuny** [comment]
When I tick the nopmi ,ultimap2 did’t work,because the ‘r’ in ‘setup ultimap2 ‘ function will keep the init value unsuccess_status,so can’t run the setup dpc procedure.

**Comment by cheat-engine** [comment]
r is completely ignored when NoPMI is used, so it should have no effect at all
