### ISSUE TITLE
Bsod  Windows 10

### ISSUE THREAD

**Issue by bilum** [cheat-engine/cheat-engine#326]
Hi,  used cheatengine for years with no issues. 

Tried to use it with submautuca many months ago and started getting random crashes whether or was running or not.  Can't remember if uninstalling worked or whether I had to clean install bit of forgotten about it until earlier. 

Reinstalled today to run alongside assassins creed origins.  Id played 20 hours of the game without issues.  No issues in general.  Within 45 mins of installing CE bald. Uninstalled. Just bsod again.  Definitely something not right in the software.

**Comment by cheat-engine** [comment]
make windows to generate a log when a BSOD happens and upload it somewhere.

Have you enabled any settings in settings->Extra?

Also, make sure you don't run any games with anti cheats installed, some of them are quite buggy and may bsod you they detects traces of CE
