### ISSUE TITLE
[feature request] Select process like MS Spy++'s finder tool does

### ISSUE THREAD

**Issue by hdnshare** [cheat-engine/cheat-engine#327]
Hi guys,

When using Cheat Engine, everybody have to select the game process first, so I think: why not make this as quick as possible?
You can see in MS Spy++ (A tool come with Visual Studio), we just need to drag the cursor to the window, and that it, no need to look through the exe huge list. And the way to code it is already there:
https://www.codeproject.com/Articles/1698/MS-Spy-style-Window-Finder
https://stackoverflow.com/q/1330074/4608491

Thanks.

**Comment by GenericDM** [comment]
You can autoattach in the settings or do it with `openProcess(processname.exe)` in a LUA script
