### ISSUE TITLE
Hotkeys are triggered if they shouldn't

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#328]
I've set Numpad+ as hotkey to start a new unknown scan. If I press CTRL+Numpad+ cheatengine performs a new unknown scan but it shouldn't.

**Comment by cheat-engine** [comment]
it's designed to do that. you can activate multiple hotkeys at the same time.
all keys are equal, just ctrl as a hotkey is valid as well

**Comment by cheat-engine** [comment]
Correct, use more complex hotkeys, or do not overlap hotkeys

example:
alt+numpad+=Unknown search 
ctrl+numbad+ = increased.
