### ISSUE TITLE
FFREEP not supported

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#329]
I've searched for a way to clear the floating registers and found FFREEP instruction but CE doesn't like it. Is it not support (yet) or just written differently?

**Comment by zcanann** [comment]
A quick Google search shows that the FFREEP instruction is not a documented/widely supported instruction

Maybe you'd have luck with http://www.felixcloutier.com/x86/FFREE.html followed by a fstp st(0), assuming I'm understanding these instructions correctly

**Comment by cheat-engine** [comment]
```
ffree st(0)
ffree st(1)
ffree st(2)
...
```
