### ISSUE TITLE
i cant ctrl+a help!

### ISSUE THREAD

**Issue by fuckingdamnass** [cheat-engine/cheat-engine#330]
i cant select all and im on win 7 someone help?
cheat engine 6.7

**Comment by JasonGoemaat** [comment]
What screen are you on?  Are you trying to select all table entries, text in the AA window, somewhere else?

**Comment by cheat-engine** [comment]
My assumption is that he wants to select all results from a scan using ctrl+a, but that his found count is larger than 5000.  (CE does not allow that, as it's too stupid)
