### ISSUE TITLE
[feathre request] text-encoding add codepage view support!

### ISSUE THREAD

**Issue by weituotian** [cheat-engine/cheat-engine#331]
![qq 20180429124534](https://user-images.githubusercontent.com/7270968/39403314-47792e76-4bab-11e8-81e8-9477349d3d4c.png)

it would be helpeful!

thanks!

**Comment by cheat-engine** [comment]
it's in 6.8

**Comment by cheat-engine** [comment]
change your local system codepage to that

**Comment by weituotian** [comment]
@cheat-engine if it is possiable, may cheat-engine add an feature to select codepage?

like winhex, it is powerful and useful:
![q -20180610184350](https://user-images.githubusercontent.com/7270968/41200818-63064e7c-6cde-11e8-88e9-e5cf2c711d13.png)
