### ISSUE TITLE
SaveSession can't work properly for CheatEngine 6.7

### ISSUE THREAD

**Issue by aabbcczz** [cheat-engine/cheat-engine#333]
Repro step:
0. Open cheat engine 6.7
1. attach to process
2. set scan type to "unknown initial value"
3. click "first scan"
4. click "Save scan session" in "File" menu to save the scan session data.
5. close cheat engine
6. open cheat engine 6.7
7. attach to process
8. click "load scan session" in "File" menu to load previously saved scan session data
9. set scan type to "unchanged value"
10. click "next scan" button.
11. An error dialog (screenshot is attached) pops up: scan error:controller:Access Violation

![capture](https://user-images.githubusercontent.com/7569318/39664197-36ffb00e-50b2-11e8-8c05-40cb697bfcd9.JPG)

**Comment by cheat-engine** [comment]
Fixed. Added a check to prevent saving unknown initial value scans
