### ISSUE TITLE
How can i compile a dbk with a visual studio?

### ISSUE THREAD

**Issue by hsac1313** [cheat-engine/cheat-engine#335]
'Now using visual studio 2017 to compile the driver' message is written in dbk source's changelog.
But when i tried to compile it, visual studio always make errors.
I also tried vs2017, vs2013, wdk 8, wdk10. How can i compile the dbk??

**Comment by cheat-engine** [comment]
https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk
I recommend building using the debug build

**Comment by hsac1313** [comment]
Thanks. :)

**Comment by fredddii** [comment]
I am closing this ticket as I assume it has been resolved, to avoid clutter in the open ticket list. If this was not the case, please let me know or just re-open the ticket with a follow up.

**Comment by hsac1313** [comment]
I can compile this with wdk 8.
