### ISSUE TITLE
eg) dbvm break point lua

### ISSUE THREAD

**Issue by xylitol1234** [cheat-engine/cheat-engine#336]
What's new in DBVM?

dbvm_cloak_activate(physicalbase, virtualbase OPTIONAL): 
dbvm_cloak_deactivate(physicalbase): Disables the cloak and restores the executable memory to what dbvm_cloak_readOriginal(physicalbase): Reads the memory that will get executed.  On success returns a dbvm_cloak_writeOriginal(physicalbase, bytetable[4096]): Writes the memory that will get executed. 
dbvm_changeregonbp(physicaladdress, changereginfo, virtualaddress OPTIONAL)

I do not know how to use 5 functions

dbvm_changeregonbp -> Is this breakpoint of 4 or more unlimited?
(softbreak point int3 unlimited)
(hard break point limited max 4)

dbvm_changeregonbp(0xFFFFFFFF(physicaladdress??),neweip(??),0x12345678(virtualaddress?) <- e.g plz

dbvm_cloak_activate -> Hide memory information? , Bypass CRC memory check?
(I do not know what it is)

I'm curious to see an example of a new feature

**Comment by cheat-engine** [comment]
Most of these you use in conjunction with dbk_getPhysicalAddress(address) and optionally first dbk_lockmemory() so windows doesn't swap the physical address during runtime

dbvm_changeregonbp will cloak the memory, and set a BP in the unreadable execute shadow which wiull then do a changereg handling
e.g
```
dbvm_changeregonbp(dbk_getPhysicalAddress(0x12345678), {newRIP=0x12345680})
```
will set a software breakpoint at 0x12345678 and change RIP to 0x12345680 when it hits (it cloaks the region first so the software breakpoint is not readable)

dbvm_cloak_activate will split up a physical page into two. A executable page, and a read/write page.  On execute the execute page is executed, and on read/write the read/write page is used.  This is useful to hide your code from prying eyes
