### ISSUE TITLE
Dump decrypted Dll from the Mono view?

### ISSUE THREAD

**Issue by hammackj** [cheat-engine/cheat-engine#337]
Is there a way to dump a module/dll that can be see in the mono dissector view to disk? It is a Unity Assembly-CSharp.dll.

Thanks

**Comment by cheat-engine** [comment]
you can find the module address by going to the hexadecimal address shown in front of the image +8  (in 32-bit, probably +10 in 64-bit but untested)
the 4(/8) bytes there point to the start of the module
And then just use the pe header info to get the size and then dump that using the file->save memory region (turn off the header)

**Comment by joshfreitas1984** [comment]
Were you able to figure out what he meant @hammackj? I couldnt :(
