### ISSUE TITLE
system bugcheck when clicking some label on the about page

### ISSUE THREAD

**Issue by yangbowen** [cheat-engine/cheat-engine#341]
When I clicked the "Your system DOES NOT support DBVM" label on the about page, my system generated a bugcheck with the code "WORKER_THREAD_RETURNED_AT_BAD_IRQL". I restarted the machine (after the dumping finished) and retried clicking that label and the system generated a bugcheck again with the same code.

Here's the minidump file in a ZIP archive:
[060718-12593-01.zip](https://github.com/cheat-engine/cheat-engine/files/2079133/060718-12593-01.zip)

**Comment by yangbowen** [comment]
I use Windows 10 Pro 17682.rs_prerelease

**Comment by yangbowen** [comment]
@cheat-engine It's CE 6.7. I downloaded the binary from the official site.
I tried the following combinations of options and they all result in a BSOD when I clicked "OK":
Open Process
Enable use of the Process Watcher
all options on

**Comment by cheat-engine** [comment]
should be fixed with https://github.com/cheat-engine/cheat-engine/issues/296
