### ISSUE TITLE
Release roadmap?

### ISSUE THREAD

**Issue by fredddii** [cheat-engine/cheat-engine#343]
While I do not wish to stress this free project, I was wondering when 6.8 would be pushed? Or perhaps as a beta?

I am looking forward to finally getting DBVM to work on the latest Windows 10.

**Comment by cheat-engine** [comment]
Oh alright, because you asked i'll release it tonight

**Comment by cheat-engine** [comment]
check the releases tab on github or the ce website

**Comment by fredddii** [comment]
Thank you kindly for the quick response!
