### ISSUE TITLE
Crash CE when using commonality compare

### ISSUE THREAD

**Issue by partoftheworlD** [cheat-engine/cheat-engine#345]
Most often happens when you try to open the structure for comparison, and sometimes every second launch of CE when using commonality compare

**Comment by cheat-engine** [comment]
so whole ce closes ?

**Comment by partoftheworlD** [comment]
Yes, without errors or any messages just closes.

**Comment by cheat-engine** [comment]
redownload CE. Then hold ctrl down and click on help.  Click on generate errorlogs

Then next time CE crashes it 'should' generate a cheatengine-x86_64.exe.debug.log in the ce install dir

**Comment by partoftheworlD** [comment]
No, only one display.
