### ISSUE TITLE
CC6.8: Starting Ultimap 1 on any application results in the application crashing

### ISSUE THREAD

**Issue by fredddii** [cheat-engine/cheat-engine#347]
Tested initially on a game and then on something simple like Windows Notepad, both result in a crash shortly after start is pressed.

Please let me know if more debug information is needed if the issue can not be replicated.

Faulting application name: notepad.exe, version: 10.0.17134.1, time stamp: 0x9d4727c2
Faulting module name: ntdll.dll, version: 10.0.17134.1, time stamp: 0x207580e2
Exception code: 0xc0000005
Fault offset: 0x000000000009dcd0
Faulting process ID: 0x1fbc
Faulting application start time: 0x01d3ff72ad234994
Faulting application path: C:\Windows\system32\notepad.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report ID: ac7500fe-7182-4291-9f5c-4599675f81d3
Faulting package full name: 
Faulting package-relative application ID:

**Comment by fredddii** [comment]
Thanks for the reply. This setting was already on. I have also enabled all the settings in the last tab of the options window.

**Comment by cheat-engine** [comment]
Redownload CE, it should work now

**Comment by fredddii** [comment]
It does. Thank you very much.
