### ISSUE TITLE
worker_thread_returned_at_bad_irql upon cheat engine launch

### ISSUE THREAD

**Issue by TheK0tYaRa** [cheat-engine/cheat-engine#348]
BSODing at every launch. Windows fix didn't help. Only resetting CE settings helped. BTW, CE v6.8, Windows 10 Pro Workstation edition, last stable update of it (is the same that Pro is, but has infinite HyperV VMs)

**Comment by TheK0tYaRa** [comment]
It could have happened because of i used DBVM before and didn't reset settings upon new version installation, now on the DBVM debugger choie there is "enable possibility" choice.

**Comment by TheK0tYaRa** [comment]
Also checked recovered old settings - extra was all enabled. Is the solution to me - not enabling them.

**Comment by cheat-engine** [comment]
redownload CE 6.8.  Enable something in settings-extra (NOT processwatcher) .
and if it bsod's then get the crash dump and upload it somewhere (it's usually in c:\windows\memory.dmp , but you can change that and the kind of dump in the windows settings)

**Comment by TheK0tYaRa** [comment]
DPC watchdog violation just got catched by me on "enable ability of DBVM" button + some seconds

**Comment by cheat-engine** [comment]
This dump only shows that something unloaded inside ntoskrnl
Do you get to see the DBK64 loaded screen on the top left for a few seconds ?

Disable everything related to hyper-V
And do you have any kind of anti virus running ? (It could have tried to unload ce's driver and failed miserably at that)

**Comment by TheK0tYaRa** [comment]
Well, i have the standart one antivirus. Had to enable HyperV because of mtproto running in it. And - yeah, saw "DBK64 LOADED" rainbowie sign
