### ISSUE TITLE
Lua error when dissecting structs of a game upgraded to Unity 2018.1

### ISSUE THREAD

**Issue by gotoel** [cheat-engine/cheat-engine#350]
Attempting to dissect the structs produces the following errors:

> Error:...gram Files (x86)\Cheat Engine 6.8\autorun\monoscript.lua:553: attempt to index a nil value (global 'monopipe')
Error:...gram Files (x86)\Cheat Engine 6.8\autorun\monoscript.lua:553: attempt to index a nil value (global 'monopipe')
Error:...gram Files (x86)\Cheat Engine 6.8\autorun\monoscript.lua:553: attempt to index a nil value (global 'monopipe')
Error:...gram Files (x86)\Cheat Engine 6.8\autorun\monoscript.lua:553: attempt to index a nil value (global 'monopipe')

Is the latest mono version (that's contained in Unity 2018.1) not supported?

Let me know if more info is needed.

**Comment by cheat-engine** [comment]
perhaps the address you're looking at is not a proper mono object, or a 'generic' type

if you know the type you can try looking it up in structure in the dissect mono window

**Comment by gotoel** [comment]
Fixed in #359 .
