### ISSUE TITLE
Values do not change to what is actually entered

### ISSUE THREAD

**Issue by Moltresrider** [cheat-engine/cheat-engine#351]
When I search a value and find the right address to that value, and I change the value in Cheat Engine, the value that cheat engine assigns to the address is NOT what I actually entered. Say I enter 75000 as a value, the maximum amount this one particular game reads for that value. Cheat Engine changes it to 9464 instead EVEN THOUGH I typed 75000!

This problem has been present in ALL versions of Cheat Engine but it does not always do this. I just downloaded the latest version June 2018 and this problem is present.

This problem can happen on any byte type or on any address I try to search. Sometimes it works properly and other times it inputs an entirely different value than what I typed in.

**Comment by cheat-engine** [comment]
That is normal when you use 2 byte types
75000 is in bytes: f8 24 01
but since that doesn't fit in 2 bytes, it turns into f8 24, which is 0x24f8 which is 9464
