### ISSUE TITLE
Cheat Engine no longer works with emulators

### ISSUE THREAD

**Issue by Moltresrider** [cheat-engine/cheat-engine#352]
This post from 2009 is no longer valid. https://forum.cheatengine.org/viewtopic.php?t=477605 I tried it with 27 different games across nine different emulators and eight different systems. The results are all the same, it either does not find a value "0 results" upon second scan, or the values just simply do not change despite changing them in Cheat Engine. 

Apparently this worked in 2009, but since then, something has changed in Cheat Engine that makes this tutorial no longer valid.

**Comment by dsasmblr** [comment]
Cheat Engine works just fine with emulators, but it's not a straightforward
process like that tutorial suggests. Some things to note:

1. In Edit -> Settings -> Scan Settings, make sure MEM_MAPPED is checked.
If it's not already, this could be your problem.

2. Don't rely on that tutorial. It's nowhere near reliable across the
landscape of all emulators out there today.

3. Use changed/unchanged scans. Don't rely on increased/decreased, nor on
exact value scans.

4. You may need to scan physical memory, depending on the emulator you're
using. Consider setting up CE as described in this tutorial:
https://www.youtube.com/watch?v=Xo20nvppGm0

5. Again, don't rely so much on the information from that 2009 tutorial.
And don't rely on your values being how you see them represented in the
game. Endianness (read: https://en.wikipedia.org/wiki/Endianness) is
typically something you need to consider with emulators.

**Comment by Moltresrider** [comment]
MEM_MAPPED is already checked. There is no option to scan for changed/unchanged values. The only options are: exact value, bigger than, smaller than, value between, and unknown initial value. There is no option for changed/unchanged values

**Comment by dsasmblr** [comment]
You have to do a scan first before you can scan for a value that's either
changed or unchanged. So, start with an unknown initial value scan, then
the other options become available to you.

**Comment by Moltresrider** [comment]
Why do you people HAVE to give me the runaround? I did an unknown initial value and after spending 30 GP, I did a "deceased by" and entered 30. ONLY results with single digits with MANY decimal paces values showed up! there were NO 270 values ANYWHERE!!! 

Just fix the bug and quit giving me the runaround!!!

**Comment by dsasmblr** [comment]
Because it's not a bug, just like the last time you came around here
yammering about something that was also the result of your ignorance.

You're far too much of a newbie to think you're finding bugs with something
as simple as scanning and Endianness as related to emulators. And it's fine
to be a newbie, but try being reasonable for once instead of coming around
here and acting like a dickhead to people who are trying to help you.

Learn how to use Google, too. There are plenty of articles/videos out there
to show newbies like you how to use Cheat Engine with ZSNES, as well as
other emulators.

You're a message or two away from no one ever helping you again through
here, so choose your responses carefully from here on out.

**Comment by Moltresrider** [comment]
FYI, the post a couple months ago regarding Kitty Glitter WAS a bug! It worked fine on another computer doing the SAME exact thing as I said did not find anything on my laptop. Funny it worked just fine last week on a Windows XP machine and yet the same thing does not work on a Windows 7 based laptop. There is obviously something preventing Cheat Engine from finding it using a Windows 7 based machine.

**Comment by dot-beep** [comment]
you might just be retarded
