### ISSUE TITLE
[Help/Bug?] Unable to call a Windows application's about window with Auto Assembler

### ISSUE THREAD

**Issue by fredddii** [cheat-engine/cheat-engine#353]
Trying to call Notepad's about window as instructed per this video:
https://www.youtube.com/watch?v=T5sXoEEPFBQ

I can do everything fine and I can find the two calls with Ultimap. However, they are not preceded with pushes like in the video, most likely because the individual is using 32-bit instead of 64-bit. When I do try to mess around in Auto Assembler all I can do is make Notepad crash.

I also tried to ask help on the forum to no avail:
https://forum.cheatengine.org/viewtopic.php?t=607771

I am not sure if Auto Assembler is broken, or if I am doing something wrong. **Can somebody please try to call Notepad's about window with auto assembler and tell me how they have done it?**

**Comment by FreeER** [comment]
here's some lua code to do it in the x64 version of Notepad using the windows api... shouldn't be all that hard to do it in pure asm if you wanted to. I have AMD cpu so no ultimap for me, no idea otherwise how to find the actual function the program uses to handle sending the WM_COMMAND with... (maybe look for where SendMessage/PostMessage is called and look for the WM_COMMAND hex...)

```
function getSubMenu(menu, pos)
  -- executeCode only handles a single param, so create wrapper function to handle more
  if not autoAssemble[[
  globalalloc(GetSubMenuWrap, $1000)
  GetSubMenuWrap:
    sub rsp, 28 // shadow space and alignment
    mov edx, [rcx]
    mov rcx, [rcx+4]
    call GetSubMenu
    add rsp, 28
    ret
  ]] then return 0 end

  local mem = allocateMemory(12)
  writeInteger(mem, pos)
  writePointer(mem+4, menu)
  local res = executeCode('GetSubMenuWrap', mem)
  deAlloc(mem)
  return res
end
-- near duplicate of getSubMenu, same params after all
function getMenuItemID(menu, pos)
  if not autoAssemble[[
  globalalloc(getMenuItemIDWrap, $1000)
  getMenuItemIDWrap:
    sub rsp, 28
    mov edx, [rcx]
    mov rcx, [rcx+4]
    call getMenuItemID
    add rsp, 28
    ret
  ]] then return 0 end

  local mem = allocateMemory(12)
  writeInteger(mem, pos)
  writePointer(mem+4, menu)
  local res = executeCode('getMenuItemIDWrap', mem)
  deAlloc(mem)
  return res
end

local hwnd = findWindow(nil, 'Untitled - Notepad')
local hmenu = executeCode('GetMenu', hwnd)
local help = getSubMenu(hmenu, 4)
local about = getMenuItemID(help, 2) -- view, separator, about
local WM_COMMAND = 0x0111
return sendMessage(hwnd, WM_COMMAND, about, 0)
```
