### ISSUE TITLE
Running DBVM with a modified CE executable

### ISSUE THREAD

**Issue by Exaphis** [cheat-engine/cheat-engine#357]
I've come across this problem while using CE on Windows 7. While using the unsigned dbk64.sys you provided on your forum, I get ```The driver that is currently loaded belongs to a different version of CE. Please unload this driver or reboot.``` 

When I try to use my own compiled driver, CE successfully starts but I am unable to load DBVM, showing the error message ```I don't know what you did, you didn't crash, but you also didn't load DBVM.``` I am compiling the driver with VS2017 and WDK 10. I am also using a driver64.dat to rename the driver.

 I can start DBVM with the official install, but it doesn't show as started under my modified CE. Any help would be appreciated.

**Comment by cheat-engine** [comment]
That means you've compiled CE in the debug build mode.  In debug mode it won't touch native DBVM code, which includes detection of DBVM. Compile it in release mode and it should work better

**Comment by Exaphis** [comment]
Same issue occurs if I compile in release without sig mode. It is not detecting an existing DBVM and does not crash or load DBVM either.

I also can't seem to compile in release mode, ending up with ```Could not find file: (omitted)\DBKKernel\\dbk64.ddf``` and ```The command "cd (omitted)\DBKKernel\..\Cheat Engine\bin\DDKKernel\``` in the error list. If I use the .sys file produced with CE, I get ```The driver couldn't be opened! It's not loaded or responding. I recommend to reboot your system and try again```.

Thank you so much for the help so far!

**Comment by cheat-engine** [comment]
you need to compile cheat engine, NOT the driver in release mode

**Comment by Exaphis** [comment]
Thanks, Cheat Engine successfully detects DBVM if it is started. However, I am getting the same error message when I am trying to load DBVM from the modified CE executable. 

I also have to unload the original CE's driver in order to start mine. If I don't, I get ```The driver couldn''t be opened! It''s not loaded or not responding. Luckely you are running dbvm so it's not a total waste. Do you wish to force load the driver?``` but I am unable to force load the driver. Is my modified CE still able to utilize DBVM?

**Comment by cheat-engine** [comment]
you need to unload the driver then restart your system (not shutdown and back on, windows fakes that) and then. ompile the ce driver in debug build

**Comment by Exaphis** [comment]
Issue fixed, thanks.
