### ISSUE TITLE
[Request] Mono dissector support for mono 2.0

### ISSUE THREAD

**Issue by mrfreaky123** [cheat-engine/cheat-engine#359]
The mono dissector throws an error when trying to use it on games that use mono 2.0.

Error:...gram Files (x86)\Cheat Engine 6.7\autorun\monoscript.lua:471: attempt to index a nil value (global 'monopipe')
Error:...gram Files (x86)\Cheat Engine 6.7\autorun\monoscript.lua:775: attempt to index a nil value (global 'monopipe')
Error:...gram Files (x86)\Cheat Engine 6.7\autorun\monoscript.lua:744: attempt to index a nil value (global 'monopipe')

**Comment by mrfreaky123** [comment]
I'm sure it's an issue with CE itself since I'm able to use it flawlessly on games that use mono.dll rather than mono-2.0-bdwgc.dll.

https://i.imgur.com/ve5aqVy.png (ce throws an error)
https://i.imgur.com/QQNEj6h.png (ce throws an error)
https://i.imgur.com/NJI9OPO.png (mono dissector works as expected)

**Comment by cheat-engine** [comment]
replace the mono dll with one where it works

**Comment by mrfreaky123** [comment]
the game doesn't open at all after doing that

**Comment by cheat-engine** [comment]
In CE go to the address of "mono_thread_attach"

If it can't find it, that's why

**Comment by cheat-engine** [comment]
I did a small test, and in the mono screen go to settings and on there disable "show method parameters"

**Comment by cheat-engine** [comment]
should be fixed in the github now

**Comment by mrfreaky123** [comment]
yup working fine now, cheers
