### ISSUE TITLE
vm detect?

### ISSUE THREAD

**Issue by xylitol1234** [cheat-engine/cheat-engine#361]
https://github.com/a0rtega/pafish

https://github.com/a0rtega/pafish/blob/184b3fc3d5431e7334485a1eb33f30d3be125dc3/pafish/cpu.c

dbvm detect bypass Question

cpu_rdtsc_force_vmexit

vmcall password edit -> Detected

rdtsc vmexit timestamp 

static inline unsigned long long rdtsc_diff_vmexit() {
	unsigned long long ret, ret2;
	unsigned eax, edx;
	__asm__ volatile("rdtsc" : "=a" (eax), "=d" (edx));
	ret  = ((unsigned long long)eax) | (((unsigned long long)edx) << 32);
	/* vm exit forced here. it uses: eax = 0; cpuid; */
	__asm__ volatile("cpuid" : /* no output */ : "a"(0x00));
	/**/
	__asm__ volatile("rdtsc" : "=a" (eax), "=d" (edx));
	ret2  = ((unsigned long long)eax) | (((unsigned long long)edx) << 32);
	return ret2 - ret;
}

int cpu_rdtsc_force_vmexit() {
	int i;
	unsigned long long avg = 0;
	for (i = 0; i < 10; i++) {
		avg = avg + rdtsc_diff_vmexit();
		Sleep(500);
	}
	avg = avg / 10;
	return (avg < 1000 && avg > 0) ? FALSE : TRUE;
}

I am curious about dbvm virtualization detection bypass

If you do not mind, can you tell me how?

**Comment by xylitol1234** [comment]
More recently, DBVM detection
I am very curious as to what to detect.

**Comment by xylitol1234** [comment]
![bvbv](https://user-images.githubusercontent.com/39520432/41509497-aa3e6890-728f-11e8-86aa-a6b5698ada5d.png)

upload image 

driver load check -> detect

Kernelmoduleunloader -> driver unload check -> detect

dbvm hypervisor Load Check && Kernel Memory Fix Detect??

**Comment by xylitol1234** [comment]
time delay check?

kernel CR memory ? 

kernel Msr memory?

Recently, there are many ways to detect virtualization, so I wonder how to detour
I do not know where to fix it.

**Comment by cheat-engine** [comment]
should be fixed now

**Comment by JordanBoulan** [comment]
@cheat-engine 

Hi I was hoping you could explain the logic of the fix, I am doing some analysis with xen and was thinking about implementing this.

I see you set lowestTSC in set in setVM_CR3 function but rdtsc is also seen other places in the exit handler code file.

In handle_rdtsc funciton itself it seems like you are not using the speedhack if statement and instead using adjustTimestampCounter based on the initial settings.

I'm just not really understanding what your approach is and what is going on in the code and was hoping you could explain at least just the theory/process behind what's going on to bypass this check.

For example here in hande_rdtsc of vmeventhandler.c on line 3998 you have


``
 int off=20+(realtime & 0xf);
 t=currentcpuinfo->lowestTSC+off;

'''

I don't understand where you are getting the offset from and what it means. Below that at 4062 for intel VMX you have:

```
 vmwrite(vm_guest_rip,vmread(vm_guest_rip)+vmread(vm_exit_instructionlength));

  RFLAGS flags;
  flags.value=vmread(vm_guest_rflags);

  if (flags.TF==1)
    vmwrite(vm_pending_debug_exceptions,0x4000);

```

This makes sense to me, your are setting the guest time to the current guest time + how long the vmexit takes. My question is how are you calculating the vmexit time when there are so many different vmexit scenarios.

Also what is the point of the debug_exceptions flag?

I am familiar with virtualization code and have written a custom VMX hypervisor before. This is just a particularly tricky thing to handle and it is hard to tell what is going on.

Didn't know how else to contact you. If you would like to speak in private let me know how. Just trying to learn more than anything.

**Comment by cheat-engine** [comment]
It's just a very blunt rdtsc detection bypass.  It doesn't do an accurate emulation of time.

It's based on the assumption that when 2 clock readouts happen within a very short time (e.g within 4000 cycles or so) that it's likely a vm detection mechanism and in that case just return a random small value of 20+ difference

**Comment by JordanBoulan** [comment]
Ahh thank you very much.
