### ISSUE TITLE
Scanning works only part of the time for given value

### ISSUE THREAD

**Issue by Moltresrider** [cheat-engine/cheat-engine#362]
When I scan my money amount on Kitty Glitter by Big Fish Games, it does not find anything at all. Regardless if it finds zero results on first scan or second. However, I can close Cheat Engine and/or restart my computer, search those same values and save value type and voila, it finds them no problem and I can edit them.

Same for Vegas Stakes for SNES on ZSNES. The first time I searched my money amount, and the changed value, it found it and I changed it. It showed up as a 4 bytes number. However, if I do that again, it cannot find the value I searched on second scan even with "all" selected.

Sometimes it finds the correct value, say 1000, it changes to 940, there is 940 in the column, but searching 940 says "0 results" despite that there was a 940 in the left hand column. It does not always do this. Again, sometimes it works, sometimes it does not.

**Comment by cheat-engine** [comment]
in zsnes values are never 4 byte.
try 2 byte

**Comment by Moltresrider** [comment]
That is where you are wrong. I restart my computer and did an "all" scan for 1000 then 900 what came up was a 4 byte number and I was able to change my money to 9900000. This does not always work like I said in my OP

**Comment by cheat-engine** [comment]
is fast scan off ?

**Comment by dsasmblr** [comment]
I already explained why you're having your issue with ZSNES in relation to "Vegas Stakes" [in this comment](https://github.com/cheat-engine/cheat-engine/issues/356#issuecomment-397309611).
