### ISSUE TITLE
Cannot search pointers in a file

### ISSUE THREAD

**Issue by Monotek18** [cheat-engine/cheat-engine#363]
The pointer searcher work with process, but not with the files.

**Comment by cheat-engine** [comment]
Very likely that is because the file offset starts at 0

**Comment by cheat-engine** [comment]
have you disabled the option (advanced options) that it has to find a static address (because there are no static addresses in a file)

**Comment by Monotek18** [comment]
nvm it worked when I adjusted the options, thanks for this awesome tool.
