### ISSUE TITLE
wrong address in compiled assembly

### ISSUE THREAD

**Issue by mjohnson771** [cheat-engine/cheat-engine#366]
hello, im new to cheat engine, there is a chance im doing somethign wrong, but let me explain the issue:

**steps to reproduce**

1. go to tools -> auto assemble
2. write following assembly code in the script: "cmp rdi, 0xB5BD35C810"
3. save and enable the script (for example use the full injection themplate)
4. observe that it compiled to assembly instruction "cmp rdi,FFFFFFFFBD35C810", which is wrong

am i doing something wrong, or is this a bug?

im not sure, but to me it seems that this is some kind of overflow (or underflow), but i have no iddea why it happens. if this is a bug, is there any workaround?

thanks

**Comment by cheat-engine** [comment]
the x86_64 instruction set does not have a cmp version that takes 64-bit values

what you can do instead is first load the value in a register, and then compare against that.  The instruction to load a value into registers (mov) does have a 64-bit variant, so you can do something like:
```
push rax
mov rax,B5BD35C810
cmp rdi,rax
pop rax
...
```

**Comment by mjohnson771** [comment]
thank you my friend

it seems that you are right, cmp has no 64 support unfortunately, i also found it after google search. but, your workaround helped me fix the problem
