### ISSUE TITLE
old issue code page view

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#367]
https://github.com/cheat-engine/cheat-engine/issues/198

![qwer](https://user-images.githubusercontent.com/18622105/41710398-87327b04-7580-11e8-8a99-fa6c067171c6.png)

Cheat engine  6.8 -> Codepage support in hexview update

C7 D1 B1 DB = 한 글

Codepage View -> Not View

FoundList -> View

and why Code Page String 6byte?

C7 D1 B1 DB = 4byte

**Comment by cheat-engine** [comment]
Try looking at 04749e78 and check the bytes there, perhaps they are different from what you expect

Also, I can't really fix this as it's impossible for me to reproduce(and copy/paste won't work properly), so feel free to send small pull requests with these things fixed.

**Comment by kitty8904** [comment]
[files.zip](https://github.com/cheat-engine/cheat-engine/files/2123609/files.zip)

file and ct 
40B65C = C0 FA C0 E5 C7 CF B1 E2

C0 FA = 저
C0 E5 = 장
C7 CF = 하
B1 E2 = 기

**Comment by cheat-engine** [comment]
As I said, I can not reproduce this in any useful way
none of my systems is capable of interpreting codepage

**Comment by kitty8904** [comment]
hmm

    if CharEncoding=ceCodepage then
    begin
      s:=UTF8ToWinCP(wkey);

      WriteProcessMemory(processhandle, pointer(selected), @s[1],length(s), bw);
      inc(Selected);
    end 

how fix?

I try to fix it on my computer. What should I do?

Characters are displayed correctly on the search list

Memory View codepage error

**Comment by kitty8904** [comment]
Did I misunderstand?

Is there no way at all?

If there is no solution, I will not mention it anymore.
