### ISSUE TITLE
Executing step-over creates unintended new breakpoints

### ISSUE THREAD

**Issue by advanced-developer** [cheat-engine/cheat-engine#369]
### Steps to reproduce the problem

1. Open CheatEngine
2. Set a breakpoint on a `call` instruction
3. Execute the step-over command

### What is the expected behavior?

The program should resume, then call the given function and pause again on the first instruction after the `call` instruction.

### What went wrong?

CheatEngine creates a new breakpoint on the instruction after the `call` instruction and succeeding step-overs doesn't do anything (the program remains paused until all breakpoints are removed and the thread is unpaused).

### Additional details

[test-case.zip](https://github.com/cheat-engine/cheat-engine/files/2124719/test-case.zip)
[screencast.mp4](https://www.youtube.com/watch?v=tKXFy__BHM8)

**Comment by cheat-engine** [comment]
should be fixed in the git now

**Comment by advanced-developer** [comment]
Thanks. I suppose [this](https://github.com/cheat-engine/cheat-engine/commit/ba71040552a44065eb3af19c1d9dff173ec62d76) is the commit you're talking about. I'm not set up for compiling CheatEngine right now, so I would leave this open until the next release.

**Comment by cheat-engine** [comment]
should be fixed in the 6.8.1 release

**Comment by advanced-developer** [comment]
Awesome, thanks!
