### ISSUE TITLE
Word spacing issue in Tutorial

### ISSUE THREAD

**Issue by DavidMetcalfe** [cheat-engine/cheat-engine#37]
When the application is first opened, the tutorial that is displayed has a word spacing issue with "you renamed" as shown in the screenshot and highlighted. Seems to pull from the `Unit1.pas` file, but I can't spot anything obvious with spacing.

![cheat engine tutorial word spacing](https://cloud.githubusercontent.com/assets/80915/11555303/199d1cbc-9954-11e5-9c9c-bc668f2bc02b.jpg)

**Comment by remizovm** [comment]
I guess that this one is already fixed, right? @DavidMetcalfe, could you please check it yourself (I tried v6.7 a minute ago and couldn't find the typo from your screenshot)? Thank you.
