### ISSUE TITLE
My PC slow, after enable DBVM

### ISSUE THREAD

**Issue by CRC32EX** [cheat-engine/cheat-engine#370]
# Steps to reproduce this issue
1. turn on DBVM
![image](https://user-images.githubusercontent.com/25629617/41745798-2e94ed84-75e3-11e8-9468-63ab9136975d.png)

After enable DBVM, my PC is slow.
For example, opening some folder with explorer.exe, it tooks about 2 seconds.
Game FPS rate also dropdown.

DBVM is works fine in my environment.

# Possible solution
- reboot a PC
In this result, my PC works faster again.
But, i want to more faster while using DBVM.

This is Bug or DBVM specification?

# My Environment
|||
|---|---|
|OS|Windows 10 Pro 1709 64bit|
|CPU|Intel i7 8700K|
|RAM|16GB|
|SSD|950 PRO 256GB|
|CheatEngine|Version 6.8|

**Comment by cheat-engine** [comment]
dbvm 11 is generally  slower as it emulates system memory as well.
what can be a contributing factor on the slowdown is if you also have the spectre mitigation code running on your system. go to settings-debug settings and see if there is a button with the text "make possible " next to kernelmode.
if so click it to turn of that protection (and reboot)

**Comment by CRC32EX** [comment]
Thank you for very quick reply.

I already clicked "make possible" button.
I'm using kernel mode debugger already.
Because the game detect memory editing.
DBVM & this lua code can bypass it.

```lua
addressOfEnemyHPFunction = 0x03A315EC

function debugger_onBreakpoint()
  if (EIP == addressOfEnemyHPFunction) then
    -- set enemy HP to 0
    writeInteger(EAX, 0)
  end

  return 1
end

debug_setBreakpoint(addressOfEnemyHPFunction)
```

> dbvm 11 is generally slower as it emulates system memory as well.

Can i setting faster option?
or can i contribute for implement faster option?

I can write C/C++ a little, but i don't know about kernel side.

This is my current all Cheat Engine settings.
https://imgur.com/a/I0kDNnY

**Comment by cheat-engine** [comment]
Try this dbvm build
[dbvmnoept.zip](https://github.com/cheat-engine/cheat-engine/files/2126703/dbvmnoept.zip)

It has disabled EPT.
But do keep in mind that will also mean that any memory based functions won't work anymore.  
So,
no dbvm based find what access without using debug registers
no dbvm_cloak
no unlimited dbvm_changeregonbp breakpoints
no realmode execution support

**Comment by CRC32EX** [comment]
Thank you!!!
It became very smooth.
(donated with Bitcoin.)

**Comment by cheat-engine** [comment]
which versions have you tried ? just noept or the fixed ones?

**Comment by CRC32EX** [comment]
- dbvmnoept.zip
This is the best.
very smooth.
as same as DBVM off.

- dbvm-lockfix.zip
This is better than Cheat Engine 6.8 original `vmdisk.img` and `vmdisk.img.sig` i think.
But, almost same original.
very little difference i think.

- dbvmlockfixfulloptimization.zip
This is almost same to `dbvm-lockfix.zip`.
I do not know the difference.
