### ISSUE TITLE
6.8.1 getCheatEngineFileVersion is the same for 32 and 64 bit

### ISSUE THREAD

**Issue by FreeER** [cheat-engine/cheat-engine#372]
One of my extensions was relying on this being different to get the offset to the list of Table Files in CE so as to iterate through them, not sure if that's something I should continue relying on or if I should also start using CheatEngineIs64Bit() (<- this is what I'm doing currently so I can get it working)...

Obviously for any one thing like this I could request that an official lua API be added but this approach would still be valid for all CE versions prior to a new update being released with the API (which can sometimes be a significant period of time).

**Comment by cheat-engine** [comment]
not a bug really. more by design.  
but yeah, do use version AND check if CE is 64 bit.
or perhaps there is a workaround for the thing you're using version/arch specific stuff for
