### ISSUE TITLE
Core 0 loading freezes PC (no BSOD in half an hour after)

### ISSUE THREAD

**Issue by TheK0tYaRa** [cheat-engine/cheat-engine#373]
Hyper-V disabled, antivirus may be the cause - currently trying to solve by disabling it. Not much success (none)

**Comment by TheK0tYaRa** [comment]
Standart "all cores" loading does the same with antivirus offline.

**Comment by TheK0tYaRa** [comment]
by the way, cpu is AMD a6 6400k 2-core

**Comment by TheK0tYaRa** [comment]
Turbo mode bay be the cause. Will investigate further

**Comment by TheK0tYaRa** [comment]
Tried loading CPU1 with turbo offline - PC freezed for 5 seconds, then force-rebooted somehow.

**Comment by TheK0tYaRa** [comment]
Also almost forgot to write that "DBK64 LOADED" shows up with the grey tone beneath

**Comment by cheat-engine** [comment]
dbvm 11 currently doesn't support AMD
but if your system did work with 6.7 (the loading dbvm 10 part that is) then you can still use 6.7 to load dbvm. 
that combined with the 6.8 registry fix to disable spectre protection should make kerneldebug work

**Comment by TheK0tYaRa** [comment]
Will test a bit later
