### ISSUE TITLE
ring0 bp detect?

### ISSUE THREAD

**Issue by xylitol1234** [cheat-engine/cheat-engine#375]
dbvm breakpoint detect

how fix?

dbvm load -> Detect Process Run -> NoDetect

dbvm load  ->Ring0 Start breakpoint(any process) ->Detect Process Run -> Detect

dbvm load ->Ring0 Start breakpoint ->Kernelmoduleunloader.exe ->Detect Process Run -> NoDetect
(globaldebug check ,abillty to kernel code check)

1. DBVM Password Change ->  Not a detection area
2. DBVM virtualization Load -> Not a detection area
3. cheat engine sys Load ->  Not a detection area
3. DBVM Breakpoint First Start Hook? Start Hooking address? -> Detect

Once you start a breakpoint, you can continue to detect it after that.

dbk sys source -> debugger.c ? setvalue(0x400,0xf0401,0xffff0ff,flag tf,rf?)

dbvm source ->  ?

Not Detected When Drive Is Unloaded

I do not know what it detects.

I will close the question if it violates the forum

**Comment by cheat-engine** [comment]
how do you set the breakpoints?

using dbvm_ functions or normal debug functions?

**Comment by xylitol1234** [comment]
![qwer](https://user-images.githubusercontent.com/39520432/41964448-f8e0e296-7a34-11e8-81ed-e2e12073d063.png)

dbvm ept breakpoint -> no

dbvm global debug anything process breakpoint first check -> detect

I unload sys and initialize the breakpoint, and the detection seems to be deleted. I do not know where it is.

Once a breakpoint is loaded, it is still detected. Until the drive is unloaded

EPT is not a breakpoint

Hardware breakpoint (global debug) <-Detect

**Comment by cheat-engine** [comment]
ok so it's the dbk debug (not dbvm) thatbis detected.

what you can do is find out what is detected. perhaps a debug register state. (e.g perhaps the readout with globaldebug isn't 100% correct and there might be a bug there)
or perhaps it's the issue where all breakpoints are used up in the target thread.
or it's not handling specific states properly.

before you start the target first set and remove a kernelmode breakpoint in another process (globaldebug will be set then) and then launch the target.
if it still detects it with no active breakpoint then it's detecting the GD. (there are some ways to detect that)

alternatively, modify dbvm and implement a  dbvm level breakpoint. register for debug register access exits and set it when cr3 is what it should be and fake out reads (and set it when cr3 changes to what you are targeting)

**Comment by xylitol1234** [comment]
Setting a breakpoint in another process will detect it

Detection program does not need to set breakpoints

so 
(if it still detects it with no active breakpoint then it's detecting the GD. (there are some ways to detect that)

Global debug detection?

dbvm ept hooks are not detected

Is there any way to modify the detection method of GD?

**Comment by xylitol1234** [comment]
-BUG BSOD -
And there is a dbvm ept kernel bug

eg



1. ept break point PA(0x25252525)
2. ept break point PA(0x25252525)
3.dbvm_removechangeregonbp(0x25252525))

If you double-break the breakpoint at the same address, you will get a blue screen when debugging is canceled
