### ISSUE TITLE
dbk compile error?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#376]
MSB8020	The build tools for WindowsKernelModeDriver10.0 (Platform Toolset = 'WindowsKernelModeDriver10.0') cannot be found. To build using the WindowsKernelModeDriver10.0 build tools, please install WindowsKernelModeDriver10.0 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".	DBKKernel	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets	57	

visual 2015 setup 

wdk 10.0.17134.1 setup

wdk7600 compile -> fail(Is wdk7600 compilation no longer supported?)

visualstudio compile -> MSB8020 WindowsKernelModeDriver10.0 error?

wdk setup link
https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk

https://go.microsoft.com/fwlink/?linkid=873060

Platform tool set -> WindowsKernelModeDriver10.0(Not installed)??

**Comment by cheat-engine** [comment]
Did you recently install a new SDK?  Because that will break driver compiling.
You need to redownload the latest version of the WDK and compile it with that.

If that doesn't work or isn't the cause, then revert the git changes to the project files to where it does work

**Comment by kitty8904** [comment]
Inf2Cat Tool Output:
Processing directory (C:\Users\Administrator\Desktop\cheat-engine-master\cheat-engine-master\Cheat Engine\bin\DBKKernel\) file (dbk64.inf)
Processing directory (C:\Users\Administrator\Desktop\cheat-engine-master\cheat-engine-master\Cheat Engine\bin\DBKKernel\) file (dbk64.sys)
Processing directory (C:\Users\Administrator\Desktop\cheat-engine-master\cheat-engine-master\Cheat Engine\bin\DBKKernel\) file (wdfcoinstaller01009.dll)
Parsing INF: C:\Users\Administrator\Desktop\cheat-engine-master\cheat-engine-master\Cheat Engine\bin\DBKKernel\dbk64.inf
Finished parsing INFs
Processing INF: C:\Users\Administrator\Desktop\cheat-engine-master\cheat-engine-master\Cheat Engine\bin\DBKKernel\dbk64.inf
Finished processing INFs
Testing driver package...
Testing driver package...
Testing driver package...
Testing driver package...
Testing driver package...
Testing driver package...
Testing driver package...
Testing driver package...
Testing driver package...
Testing driver package...
Testing driver package...
Testing driver package...
Testing driver package...
Testing driver package...
Testing driver package...
Testing driver package...
Testing driver package...
Testing driver package...

Signability test failed.

Errors:
22.9.7: DriverVer set to a date in the future (postdated DriverVer not allowed) in DBKKernel\dbk64.inf.

Warnings:
None

![ewew](https://user-images.githubusercontent.com/18622105/41994273-e2c123f0-7a88-11e8-9944-2ae807a117c1.png)

test driver sign delete option?

**Comment by kitty8904** [comment]
ok sign delete 

Last inf2 cat Error?

Inf2Cat, signability test failed." Double click to see the tool output.	DBKKernel	C:\Users\Administrator\Desktop\cheat-engine-master\cheat-engine-master\DBKKernel\x64\Debug\inf2catOutput.log	1

**Comment by kitty8904** [comment]
run inf2cat option check -> no 

thank you close issue
