### ISSUE TITLE
function string error?

### ISSUE THREAD

**Issue by xylitol1234** [cheat-engine/cheat-engine#378]
libipt.pas 

pt_qry_event:=GetProcAddress(hLibIPT, 'pt_qry_event');
pt_qry_cond_branch:=GetProcAddress(hLibIPT, 'pt_qry_event');

pt_qry_cond_branch:=GetProcAddress(hLibIPT, 'pt_qry_cond_branch'); <-fix?

Are the two functions the same name error?

**Comment by cheat-engine** [comment]
that's a bug yes (though it has no effect in CE as that function is not used).  It's fixed in git now
