### ISSUE TITLE
6.8.1 Auto Assembler Bug: Instruction Compilation Error

### ISSUE THREAD

**Issue by dsasmblr** [cheat-engine/cheat-engine#381]
Per this screenshot, which was taken after creating an auto assembler script from the following instruction and immediately trying to save in the same way it was disassembled:

![instruction-compilation-error](https://user-images.githubusercontent.com/22781064/42189478-635f2a70-7e26-11e8-8ed9-83e3202358be.png)

Within the brackets, the module base is being referenced in the center instead of on the left (which I guess is a problem per how CE interprets the base address for the module name).

**Does not compile**: `lea ecx,[edx*2+FF6.exe+105C9D4]`

And as a matter of testing:

**Does compile if modified accordingly (1)**: `lea ecx,[FF6.exe+105C9D4+edx*2]`
**Does compile if modified accordingly (2)**: `lea ecx,[FF6.exe+edx*2+105C9D4]`

**Comment by dsasmblr** [comment]
Just checking in to see if this ticket has made any progress or is on a list of to-dos or something. Would like to go through and close any finished/addressed tickets that I still have open.

**Comment by cheat-engine** [comment]
Still in the todo list. The order of modulenames is a known issue for the assembler.  I should probably change the disassembler to show it as ff6.exe+105c9d4+edx*2

**Comment by cheat-engine** [comment]
Should be fixed now 

and another workaround, is using 
`lea ecx,[edx*2+FF6.exe+105C9D4]`
