### ISSUE TITLE
Mono stability issues when attaching debugger

### ISSUE THREAD

**Issue by dsasmblr** [cheat-engine/cheat-engine#385]
There appears to be a Mono stability issue in 6.8.1 when attaching the debugger. Assume the following scenario:

**Debugger Option Used**: VEH

**Steps to Replicate**:

1. Fresh launch of game and Cheat Engine, then open game process with CE.
2. Click Mono -> Activate mono features
3. Enable script that references addresses via Mono-related symbol names instead of ModuleBase+offset or AOB. (Purpose of the script: To create my own pointer to the base of a player camera structure.)
4. With values now populating inside of addresses that depend on the script, right click on a value of interest to see what accesses/writes the value.
5. Game crashes.

I know some wonkiness can occur when attempting to attach the debugger after activating Mono features, but I seem to recall at least somewhat graceful disabling of Mono features before the debugger attached. Now I see results instantly when attaching the debugger, but within 5-7 seconds of doing so, the game crashes.

**Comment by cheat-engine** [comment]
does this happen in every game or just one specific game?

**Comment by dsasmblr** [comment]
I'll try a couple of other Mono-based games tonight and get back to you on that.

**Comment by dsasmblr** [comment]
Alright. So far, it seems to be just this one game. It's called "Super Kinky", if interested. (NSFW Doom-like game that just came out a couple of days ago.) Or I can do some tests for you if you'd like.

**Comment by cheat-engine** [comment]
in memory view go to view and disable all symbol lookup options there and see if it still happens.

it could be that one of the codes it finds has an issue with address to symbol lookup.

or turn of mono, then find what writes, turn it back on, and look at each gound result in the disassembler one by one till it crashes

**Comment by dsasmblr** [comment]
Okay, I disabled all symbol options and it still crashes. As for turning off Mono...how do I do that? I looked for a Lua method to no avail, and tried toggling the "Activate mono features" menu item, but no dice. I've been under the impression up until now that you were stuck with Mono being enabled after you activate it, lol.

**Comment by dsasmblr** [comment]
Also to note, doing a break/trace will run through completion. The game doesn't crash until about 3-5 seconds afterward.

**Comment by cheat-engine** [comment]
does it also crash without that script running ?

does that script use timers to get data or threads?
any ce lua calls from inside the game to ce ?
does the script use variables called "monopipe"

**Comment by dsasmblr** [comment]
I've completely done away with the script variable in this equation. I've narrowed it down to the following process:

1. Launch the game
2. Launch CE
3. Open the game process
4. From the Mono menu in the main CE window, launch mono dissector.
5. Find a method and JIT it.
6. Run a break/trace.

Result is as noted in my previous reply.

It's just in this game, though, of the few I've tried. It's definitely developed in Unity, but I noticed the Mono dll has no property information--almost as if it was stripped for some reason. I can attach a copy of it if you think it would do you any good to dig through.
