### ISSUE TITLE
Where is the script engine 

### ISSUE THREAD

**Issue by Solodye** [cheat-engine/cheat-engine#389]
I cannot find the script engine,in the memory viewer i tried ctrl+alt+a ,but only get the auto assemble window.

so i cannot inject c code into it.

without script engine,how can i inject c code?

**Comment by trvsapjiac** [comment]
> so i cannot inject c code into it.

CE uses lua, not c.
And c is not a scripting language.

**Comment by cheat-engine** [comment]
Compile your C code using whatever c compiler you like, gcc, visual studion, and make it output a DLL
then let CE inject that DLL
