### ISSUE TITLE
NULL index?

### ISSUE THREAD

**Issue by xylitol1234** [cheat-engine/cheat-engine#390]
disassembler.pas

function TDisassembler.SIB(memory:PByteArray; sibbyte: integer; var last: dword; addresssize: integer=0): string;  

  case index of
    0: indexstring:='eax';
    1: indexstring:='ecx';
    2: indexstring:='edx';
    3: indexstring:='ebx';
    4: indexstring:='';//'esp';
    5: indexstring:='ebp';
    6: indexstring:='esi';
    7: indexstring:='edi';
    8: indexstring:='r8';
    9: indexstring:='r9';
   10: indexstring:='r10';
   11: indexstring:='r11';
   12: indexstring:='r12';
   13: indexstring:='r13';
   14: indexstring:='r14';
   15: indexstring:='r15';
   else
     indexstring:='';
  end;

number4 index NULL ESP?

esp only one place is empty

Is it a code mistake? Intended?

**Comment by cheat-engine** [comment]
intended.  esp is not a valid register in the sib field as index 4 has a special different meaning then

**Comment by xylitol1234** [comment]
close
