### ISSUE TITLE
calling saveTable resets Form Object Inspector

### ISSUE THREAD

**Issue by FreeER** [cheat-engine/cheat-engine#391]
Now, normally that probably wouldn't be an issue but I have an autorun timer that saves fairly often since there doesn't appear to be any way to tell when the table has changed like the lua engine script, I do use md5file to check if it's changed from before so that it doesn't constantly create a new file and waste space.

While it's relatively easy to recursively loop through and save whatever is multiselected and reset them, the scroll bar for the properties still moves to the top and I'm not sure how to do anything about that...

For now, I've simply added an option to not save whenever the Form Designer is open and exposed the timer so it can be disabled/enabled at will.

**Comment by cheat-engine** [comment]
Fixed it.  if you want the old behavior call saveTable(filename, false, false)
