### ISSUE TITLE
Cheat Engine Windows 10 only needs to be created separately.

### ISSUE THREAD

**Issue by FIoat** [cheat-engine/cheat-engine#392]
Cheat Engine Windows 10 only needs to be created separately.
Windows 10 support made Sys compilation too difficult.
I would really appreciate it if you just uploaded the Sys source to Windows 7 support.

**Comment by cheat-engine** [comment]
just fix the small issues that the old source compiler has.
e.g the old wdk didn't have ntifs.h so you need to get that one separately 

also, what is complicated about pressing the build project option in visual studio?

**Comment by FIoat** [comment]
why can't I use Driver64.dat?

**Comment by FIoat** [comment]
https://software.naver.com/software/summary.nhn?softwareId=MFS_104443

Simple I have compiled the SYS file with the Windows Driver Kit tool. Sorry.
