### ISSUE TITLE
Auto Assembler Lua scripts are autorunning when first added to address list

### ISSUE THREAD

**Issue by dsasmblr** [cheat-engine/cheat-engine#393]
When creating a Lua script in the Auto Assembler and then first adding it to the address list, the script runs as if the user enabled it. The same behavior happens when modifying an already-added script and then clicking OK. The script's "Active" box in the address list does not change state with these occurrences.

Assuming I have a parent AA script enabled that acquires the base address of a player's coordinate structure, here is a sample script:

```
{$lua}
[ENABLE]
--// Manually write coordinates to player XYZ:
writeFloat("[player]+30", -172.5501709)
writeFloat("[player]+34", 0.8000000715 + 1.5)
writeFloat("[player]+38", -956.9194336)

[DISABLE]
```

If I were to have written that from scratch in a new AA window, it would run when added to the address list. Then if I go to modify it and click OK, it runs. The behavior is persistent. I also tried moving ```{$lua}``` to inside the ```[ENABLE]``` section, but that didn't make a difference.

**Comment by FreeER** [comment]
Running the lua code is Intended behavior for syntax checking, after all you can return AA code to run in it's place and you may want that checked for syntax mistakes
use `if syntaxcheck then return end` or some variation on it depending on what you're doing.

**Comment by dsasmblr** [comment]
Ah, I see. I've seen that in scripts before but never thought to look up what it does. Mystery solved. =)
