### ISSUE TITLE
Disassembler displays comment bytes in opcode column for SHUFPS instruction

### ISSUE THREAD

**Issue by dsasmblr** [cheat-engine/cheat-engine#394]
Per the following screenshot:

![shufps-disassembler](https://user-images.githubusercontent.com/22781064/42708856-83759a36-86ac-11e8-8975-8d0183f13b20.png)

This carries over into the Tracer as well:

![shufps-tracer](https://user-images.githubusercontent.com/22781064/42708857-83897b6e-86ac-11e8-880c-f2ba012b9513.png)

**Comment by dsasmblr** [comment]
Upon closer observation, I see it's just missing a comma after the second register, where the IMM8 value follows [per the instruction's convention](https://c9x.me/x86/html/file_module_x86_id_294.html).

**Comment by cheat-engine** [comment]
should be fixed on the git now

**Comment by dsasmblr** [comment]
Will test that fix when I get a hold of a newer build. I was just futzing around in a different game and noticed another instruction (movmskps) lacking a comma. Your `shufps` fix might have fixed this one, too, but just in case:

![movmskps](https://user-images.githubusercontent.com/22781064/43049714-6850ff96-8dca-11e8-9571-6c13740df3c8.png)

**Comment by dsasmblr** [comment]
Just ran across another two instructions with issues: `pslld` and `psrld`

![pslld-and-psrld](https://user-images.githubusercontent.com/22781064/43681963-6e4bb942-9831-11e8-93d6-8f9394b8f5da.png)

**Comment by dsasmblr** [comment]
Is there a repo somewhere for nightly builds or more recent compiles such that I can test fixes for things like what you noted as ready for checking, DB?

**Comment by cheat-engine** [comment]
No, there's no nightly build at the moment.  Also not much new as I have been working on some side projects for the meantime (and just waiting for the todo list to get long enough)

This is just a simple fix in the disassembler.pas and should be fixed in the git now
