### ISSUE TITLE
rdtsc patch?

### ISSUE THREAD

**Issue by xylitol1234** [cheat-engine/cheat-engine#395]
https://github.com/LordNoteworthy/al-khaser/issues/77

https://github.com/cheat-engine/cheat-engine/issues/361

https://blog.badtrace.com/post/rdtsc-x86-instruction-to-detect-vms/

=comment=
Thanks +1 IMHO, you need to measure the overhead of a VM-Exit on your hypervisor and you need to trap RDTSC (there is a field in the VMCS to make it trap) and set the TSC accordingly by subtracting the extra cycles in your VM-Exit handler.

Also, as far as I am concerned, RDTSC + an instruction which causes a VM-Exit unconditionally + RDTSC is probably something which raises a red flag.

==============================
dbvm load rdtsc time difference?

vmexit handler?

I do not know how to modify dbvm

Bypass rdtsc time difference check

In recent years, there has been a lot of hypervisor detection and kernel detection.

So I wonder how to detect and circumvent this.

**Comment by xylitol1234** [comment]
https://github.com/LordNoteworthy/al-khaser

### Timing Attacks [Anti-Sandbox]
- RDTSC (with CPUID to force a VM Exit)
- RDTSC (Locky version with GetProcessHeap & CloseHandle)
[Sun Jul 15 04:15:51 2018] [*] Checking RDTSC Locky trick:  -> 1
[Sun Jul 15 04:15:51 2018] [*] Checking RDTSC which force a VM Exit (cpuid):  -> 1

dbvmload ->rdtsc delay check detect

It is not an exact detection method, but it is detected.

**Comment by cheat-engine** [comment]
If it's really important I can of course add it(or you could write a DBVM plugin), but it will slow down the system slightly as the timer will need to be emulated then

Also, the more common cause for detection is the driver, so load DBVM, and then run the kernelmodule unloader and see if it's still picked up
