### ISSUE TITLE
Structure Compare - Laggy

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#399]
When using new structure compare tool with 1 vs >200 entries CE becomes laggy till unusable, after scan is done and the tool is only displaying the results. My guess is that CE tries to refresh all values? In this case I couldn't find a toggle to pause refreshing or similar.

**Comment by cheat-engine** [comment]
yeah, i did not expect people to use it with 200 entries lol.  i'll see about adding a limit for the value display

**Comment by cheat-engine** [comment]
should be better now
