### ISSUE TITLE
eventview ULTIMAP2 file error log

### ISSUE THREAD

**Issue by xylitol1234** [cheat-engine/cheat-engine#401]
![event](https://user-images.githubusercontent.com/39520432/43033343-d2433724-8d03-11e8-9b98-6cd9b5d6f20d.png)

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Service Control Manager" Guid="{555908d1-a6d7-4695-8e1e-26931d2012f4}" EventSourceName="Service Control Manager" /> 
  <EventID Qualifiers="49152">7000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8080000000000000</Keywords> 
  <TimeCreated SystemTime="2018-07-21T07:10:14.028948600Z" /> 
  <EventRecordID>54075</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="700" ThreadID="4160" /> 
  <Channel>System</Channel> 
  <Computer></Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data Name="param1">ULTIMAP2</Data> 
  <Data Name="param2">%%2</Data> 
  </EventData>
  </Event>

1. Cheat Engine 6.8.1 Run

2 .EventLog Ultimap2 Not File Error Service number 7000 create

Non-normal logs are continuously accumulated because there are no files

**Comment by cheat-engine** [comment]
It now won't create a service for ultimap2 if that driver isn't present
