### ISSUE TITLE
dbvm find what access size crash

### ISSUE THREAD

**Issue by xylitol1234** [cheat-engine/cheat-engine#402]
![size](https://user-images.githubusercontent.com/39520432/43043441-fdfc2d96-8dce-11e8-9a9f-10848554203b.png)

Max buffersize => 32 ->BSOD

Max buffersize => 128 -> NO BSOD

Starting with an initial size of 32, you will get a blue screen

Buffer size problem If you change to 128, blue screen does not

TEST OS
OS  -   Windows7
CPU-   intel xeon e3-1231

**Comment by cheat-engine** [comment]
Can you reproduce this with the tutorial or does it only happen with a specific game ?
