### ISSUE TITLE
double call trace crash bug

### ISSUE THREAD

**Issue by xylitol1234** [cheat-engine/cheat-engine#404]
![callbug](https://user-images.githubusercontent.com/39520432/43046802-5e99488e-8e09-11e8-8f8b-03fbdb1f6c7b.gif)

stack Trace 
Call 1234
Call 1234

Double Call F8 Trace Crash Bug

At the end of the second function call, the trace is killed and released

F8 traces do not work if there are consecutive calls

Tracing thread is forced to stop tracing

**Comment by cheat-engine** [comment]
The current github version should work (might have been fixed a while ago)
