### ISSUE TITLE
How to build Cheat Engine 6.8.1 sys?

### ISSUE THREAD

**Issue by JustRanker** [cheat-engine/cheat-engine#405]
I installed Visual Studio Community 2017 and I installed WDK 1803. My Window OS is 7. However, when DBKKernel.sln was opened and built, there was an error.
Error messages include
WDK 1803 : MSB3721    ""D:\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\HostX86\arm\armasm.exe" -coff_thumb2_only -o ARM\Debug\dbkfunca.obj ARM\Debug\dbkfunca.i"Command terminated (code:1).    DBKKernel    C:\Program Files (x86)\Windows Kits\10\build\windowsdriver.Masm.targets    49

WDK 1709 : MSB6004 The location of the specified job executable file "\ stampinf.exe" is invalid. DBKKernel C: \ Program Files (x86) \ Windows Kits \ 10 \ build \ WindowsDriver.common.targets 460

I have re-installed it, and yet I get this error. Visual Studio Community 2017 has been installed on the D drive.

**Comment by cheat-engine** [comment]
it might be a problem with wdk 1803 (i had to revert back to the version before that one myself)

but assuming you're not going to attest sign your driver by microsoft, you can disable timestamping in the configuration of the project you're building

**Comment by JustRanker** [comment]
So what am I supposed to do now? I want to build a CE 6.8.1 sys.

**Comment by cheat-engine** [comment]
in the project settings disable timestamping and catalog file generation

**Comment by JustRanker** [comment]
Which version should I use, WDK 1803 or 1709?

**Comment by cheat-engine** [comment]
1709 works best on win 7

and change the configuration to debug and platform 64 bit x86

**Comment by JustRanker** [comment]
Do I need to change to Windows 10? Errors still occur. The WDK version is 1709 and the solution configuration was built after changing Debug, solution platform to x64.

Error Message : MSB6004 The location of the specified job executable file "\ stampinf.exe" is invalid. DBKKernel C: \ Program Files (x86) \ Windows Kits \ 10 \ build \ WindowsDriver.common.targets 460

**Comment by JustRanker** [comment]
This really hurts my head... XD

**Comment by cheat-engine** [comment]
go to properties.  change the config to debug x64 in the config screen.  it may bug out, but just close snd reopen

then find the catalog generation and stamping config somewhere and turn that off

**Comment by JustRanker** [comment]
I have now solved the compilation problem. With WDK 1803, he succeeded in Windows 7. However, you can become DBVM in Windows 10 1803, but when you use EIP you get an error. DBVM is functioning normally. How do you solve this?
