### ISSUE TITLE
Assembler/Disassembler error

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#406]
Auto generated AA from memory viewer without changing a line of code, no idea if its either an assembler or disassembler error.

![grafik](https://user-images.githubusercontent.com/14368203/43184334-c93cb412-8fd7-11e8-85da-1da72b8cd1eb.png)

**Comment by cheat-engine** [comment]
assembler error. the multibyte nop isn't 
implemented there yet

**Comment by Symbai** [comment]
I see it has been implemented now so I'm closing this issue
