### ISSUE TITLE
Problem with value type: All - Not finding anything [Solved]

### ISSUE THREAD

**Issue by humam2104** [cheat-engine/cheat-engine#408]
the picture shows it all, I was playing monopoly when looking for the value of my money I couldn't find it on the latest version of cheat engine but yet I could on an older version..
I tried other processes and found the same problem only when I select (All), one more thing to mention is that I can verify that these types are working:
Byte and 2 Byte and 4 Byte and Float
![image](https://user-images.githubusercontent.com/41898465/43389719-77ff29d4-93fd-11e8-92e8-a6d900abaffb.png)

**Comment by cheat-engine** [comment]
go to settings-scan settings and tick the types you want with the all type

**Comment by humam2104** [comment]
thanks .. it worked!

**Comment by bawgrobin** [comment]
i ran into the same problem, shouldn't "all" include _all_ types possible?

**Comment by humam2104** [comment]
it should, but apparently they removed that feature for some reason and now you have to add it yourself
