### ISSUE TITLE
CE failed to find a pointer

### ISSUE THREAD

**Issue by Monotek18** [cheat-engine/cheat-engine#409]
Cheat Engine failed to find a pointer in 2 ram dumps (files)
Link to the dumps: (filename = address)
https://transfer.sh/9r60O/ram%20dump.7z

My config for the 1st pointer:
![config](https://user-images.githubusercontent.com/20025273/43396217-2e422234-9401-11e8-9ab1-6999eb699bdd.png)

My config for the scan of the 2nd dump:
![config2](https://user-images.githubusercontent.com/20025273/43396233-40e6901e-9401-11e8-96a5-6a80dbd09e30.png)

And the result:
![result](https://user-images.githubusercontent.com/20025273/43396245-4816eb18-9401-11e8-8caf-3c5082687018.png)

There is one problem because CE wasn't able to find this pointer:
[[0x1778244C] + 0x1BEC] + 0x3C

Is there anything I should fix in my configs ?

**Comment by cheat-engine** [comment]
might be a bug in the scanner.

**Comment by Monotek18** [comment]
where should I enter that ? 

And also do you have an idea for #410 ? 
My others RAM dump use 64bit pointers so it shouldn't be a problem as for this issue. 
But one problem: my dump start at 0x20DEFC400, how am I supposed to change that in CE ?
CE think it start at 0x00000000 so I can't find anything.

**Comment by cheat-engine** [comment]
in the lua engine window. press ctrl+alt+l in the main ce window

as for the base address nothing you can do right now
