### ISSUE TITLE
Error while generating the pointermap

### ISSUE THREAD

**Issue by Monotek18** [cheat-engine/cheat-engine#412]
When I try to search a pointer with a file, I get this:
![image](https://user-images.githubusercontent.com/20025273/43513857-2493a80a-957f-11e8-9ec1-b6e29ebf0ff4.png)

It doesn't happens everytime, but it happens a lot.

**Comment by cheat-engine** [comment]
I assume this is when doing a filescan ?

Do you have enough RAM free to load the whole binary file 3 times in memory ?

**Comment by Monotek18** [comment]
yes, (8GB, and the file I want to scan weight around 700mb) then I get this after this message:
![image](https://user-images.githubusercontent.com/20025273/43514264-1ca4727c-9580-11e8-9095-7fc114e24afe.png)

Apparently it can't access the file ?

**Comment by Monotek18** [comment]
My config:
![image](https://user-images.githubusercontent.com/20025273/43514877-6e920238-9581-11e8-8b43-b032dd80993b.png)

**Comment by Monotek18** [comment]
Hmm now I get that everytime, dunno what's wrong

**Comment by Monotek18** [comment]
A reboot fixed it

**Comment by Monotek18** [comment]
Edit: Still happening

**Comment by Monotek18** [comment]
What I noticed: (sorry for the spam)

The size of the file I'd like to scan is 0x2EA31000, and I get an error.

I trim the file to 0x2E000000, and now it works.

The difference is around ~10mb.

The config doesn't matter.

![image](https://user-images.githubusercontent.com/20025273/43584426-a151435a-9662-11e8-9d9c-48682bee6b57.png)
I always get this error when the progress bar is there, do you maybe know why ? @cheat-engine
