### ISSUE TITLE
Create Process bug.

### ISSUE THREAD

**Issue by Woitek1993** [cheat-engine/cheat-engine#413]
I noticed there is a bug with Create Process. It can raise exception at 2 random parts of code or print one error. it's completely random. This bug appears after first, second or third attemp of running the same exe(You could use any exe for test, it even happens in notepad.exe).

![image](https://user-images.githubusercontent.com/26350423/43543095-3007298c-95cf-11e8-9af9-b71039d04d3b.png)

and two code breaks:
![image](https://user-images.githubusercontent.com/26350423/43543291-dc195d30-95cf-11e8-9574-5b31f411e603.png)

![image](https://user-images.githubusercontent.com/26350423/43543658-fe66b92c-95d0-11e8-9e1c-758e30fc0863.png)

**Comment by cheat-engine** [comment]
I haven't been able to reproduce it yet
