### ISSUE TITLE
In Windows 10 1803, DBVM works, but EIP does not.

### ISSUE THREAD

**Issue by JustRanker** [cheat-engine/cheat-engine#414]
In Windows 10 1803, DBVM works, but EIP does not. Is it impossible at the moment? How can we fix it?

**Comment by cheat-engine** [comment]
define what you think is EIP

**Comment by JustRanker** [comment]
like this
![Uploading 캡처_2018_08_02_07_01_48_15.png…]()

**Comment by cheat-engine** [comment]
ok, but what is it. what does it do? How is it related to DBVM?  Is it even related to DBVM?

**Comment by JustRanker** [comment]
DBVM can bypass the security of Overwatch. That is WidowMaker AutoShot and Glow ESP. You can shoot the enemy automatically and find out where they are.

**Comment by JustRanker** [comment]
Auto EIP using Lua script does not work.
