### ISSUE TITLE
Don't Work With Windows Pro Build 18214

### ISSUE THREAD

**Issue by XCopper1** [cheat-engine/cheat-engine#419]
When trying to run either the 32bit or the 64bit program, I get a Green Screen and a humming noise. Then it shows an IRQ conflict. This is the Windows 10 Pro Insider Skip Ahead Version but Cheat Engine USED TO RUN on previous versions. Did MS do something to not allow this to run? Can you guys FIX IT? Many thanks... I am new here too.

**Comment by cheat-engine** [comment]
As a beta tester of their OS you need to report this to Microsoft
