### ISSUE TITLE
Scan for increased or decreased value by xx% messed up

### ISSUE THREAD

**Issue by fade2gray** [cheat-engine/cheat-engine#420]
Cheat Engine 6.8.1, on Windows 7 64Bit (also on Windows XP 32Bit VM)

When trying to scan for an increased or decreased value by xx% the two fields for the x% and y% values do not appear - just remains as a single field. This wasn't an issue with the previous 6.3 version that I had been using.

This video might better show what I'm trying to explain - https://youtu.be/Z6clgh9xSgM

**Comment by cheat-engine** [comment]
should be fixed now
