### ISSUE TITLE
TTreenode index 11 out of bounds 0...10

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#423]
![grafik](https://user-images.githubusercontent.com/14368203/44310364-0e156200-a3c4-11e8-9a73-1e838fba4fc1.png)

Trying to add a note to a structure (game uses mono) and I cannot as i gives me the error above. Its not a one time error as it happens all the time now when I try to add a node. I have to restart game and CE and start from scratch.

**Comment by cheat-engine** [comment]
what game and give a step by step instruction to reproduce it

**Comment by Symbai** [comment]
It has happened on Graveyard Keeper in structures that points to items in lists or dictionaries like this one:

![grafik](https://user-images.githubusercontent.com/14368203/44466690-722c6600-a610-11e8-9cb3-a9c510dc2dce.png)

There ain't step by step instructions as it's not reproduceable by a new structure. Its only reproduce for the current structure, when it has happened. But I got it twice from working on this game now in two days.
