### ISSUE TITLE
Assembler error on: jmp [xxx]

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#427]
The disassembler has the following opcode
`jmp qword ptr [7FF817918688]`
but memory viewer gives me an assembler error:
`I don't understand what you mean with jmp qword ptr [7FF817918688]`
in CE script it works fine. Whats the workaround for memory viewer?

**Comment by cheat-engine** [comment]
the address of that code must be within a 2GB range of 7FF817918688

**Comment by Symbai** [comment]
Thanks, I figured out. Online assemblers also only accept it with relative offset (but CE does not). Do you plan to add support for it so we can enter something like
`jmp [rip+12345] `

**Comment by cheat-engine** [comment]
Not unless you give a useful reason to do that. 

If you want to copy a block of memory, use readmem in AA or copyMemory in Lua
But you still won't be able to assemble `jmp qword ptr [7FF817918688]` from a start location outside of the 2GB region of 7FF817918688 (rip relative only does 32-bit signed offsets, so `jmp qword ptr [rip+87654321]` is impossible

at best you can re-code this into:
`
push rax
mov rax,[7FF817918688]
mov [newaddress],rax
pop rax
jmp [newaddress]

newaddress:
dq 0
`
