### ISSUE TITLE
Issue with quotation marks

### ISSUE THREAD

**Issue by osmin1** [cheat-engine/cheat-engine#432]
Cheatengine seems to have a problem with remembering addresses that are "nullified" with "Replace with code that does nothing".
Screenshot regarding this problem:
![cheatengine-problem-1](https://user-images.githubusercontent.com/41232777/44909146-7ea27400-ad1e-11e8-8546-257c8d637e1e.png)
I think that problem lies in that when "Replacing code" CE remembers it with quotation marks - in example on a screenshot "eu4.exe+2A3EAB" instead of eu4.exe+2A3EAB. 
![cheatengine-problem-1a](https://user-images.githubusercontent.com/41232777/44909325-38014980-ad1f-11e8-9367-fe2c47af54c6.png)
But when saving cheat table to a file quotation marks disappear.
Such error may cause entries in "Code list:" window to appear multiple times.

**Comment by cheat-engine** [comment]
should work better now
