### ISSUE TITLE
CE 6.8.1 : new tab message

### ISSUE THREAD

**Issue by trzustka** [cheat-engine/cheat-engine#433]
When opening new tab in search, there is poping out a new window with text : 
1232
with only controls : <OK> and <X>(close)
after closing ( no matter is it via OK or X ) new tab is opened

**Comment by cheat-engine** [comment]
Redownload CE, you may have the old day 1 release which had this, but it got fixed after this

Lua code to test:
```
if getCheatEngineFileVersion()<1688884220073442 then print("old version") end
```

**Comment by trzustka** [comment]
did that today and problem persists

note:
i downloaded "no setup " version from cheatengine.org ( https://cheatengine.org/download/CheatEngine6.8.1_MissingSetup.rar )

**Comment by cheat-engine** [comment]
yeah, the nosetup is slightly outdated on what part (still works, just has that ctrl+t debug message)

**Comment by trzustka** [comment]
:) decided to build from source (6.8.1) ...
and it still have those messeges

is there a switch in source to prevent showing debug messages 
( or maybe there could even be an option in CE settings )
