### ISSUE TITLE
Disassembler - Pointer values in comments column

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#435]
In previous CE versions values inside pointers were automatically shown. Now it only shows the decimal value of a value in the instruction. Example:

![grafik](https://user-images.githubusercontent.com/14368203/45596386-b4945900-b9aa-11e8-9d59-471bdc89f08b.png)

In previous CE it wouldn' show 10. But the (byte) value in 7FF718EA004F instead. So comment field was something like "[1]" if byte value at 7FF718EA004F  is 1.  This was a much better behavior as it instantly shows what will happen / what happens. Can this be changed / fixed / improved?

**Comment by cheat-engine** [comment]
should look better now

**Comment by Symbai** [comment]
Thanks
