### ISSUE TITLE
Can't change dialogue boxes with any cheat script

### ISSUE THREAD

**Issue by SerraraFluttershy** [cheat-engine/cheat-engine#436]
On Windows 10 & CE 6.81 whenever I load a cheat script, the dialogue boxes that pop up whenever to change something in a loaded cheat script instantly break Cheat Engine and cause it to become unresponsive. Every time, I'm forced to kill Cheat Engine, and don't know a cause.

What could it be?

[GIF of bug](https://i.imgur.com/saEPlOZ.gifv)

**Comment by cheat-engine** [comment]
Do you have any window manipulation tools installed ? E.g translation tools or help tools for visually  impaired people ?

**Comment by SerraraFluttershy** [comment]
None other than the ones which come preinstalled with Windows.
