### ISSUE TITLE
This is CE's huge BUG that has not been solved for many years.

### ISSUE THREAD

**Issue by lenct** [cheat-engine/cheat-engine#441]
Save the CETRAINER format source file to get a good encryption, but after loading into the CE program can open a CE program to attach the original CE program, the decrypted text string will be mercilessly exposed in memory, the memory address of the string can not be released.

**Comment by cheat-engine** [comment]
Not a bug. it's a feature.
Just encode the textstrings in any way you like yourself

Or use enableDRM in combination of closeRemoteHandle and a plugin that externally checks if enableDRM works as it should on an interval and that no remote handles are open

**Comment by Symbai** [comment]
There are many ways of defeating CE trainer protection including an automatic CE table dumper. Just deal with the fact or don't use it at all. No matter how many protection you put on top of it, it still can easily be defeated with a simple writeprocessmemory hook.

Accept the fact and spend your time on quality rather on protection.

**Comment by lenct** [comment]
Thank you very much for your kind reply, foreign friend.I love the CEAA scripting features and often post some of them online, but I don't like to expose my script source code.So protection is written, but this obviously doesn't work, because memory often exposes script strings.This is my first time to communicate with foreign friends. Although I can only use the translator, it feels like my first love, which makes people excited and blush, heart rate.Today is a happy day!

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Dark Byte <notifications@github.com>
发送时间: Monday, October 15, 2018 12:54:16 AM
收件人: cheat-engine/cheat-engine
抄送: lenct; Author
主题: Re: [cheat-engine/cheat-engine] This is CE's huge BUG that has not been solved for many years. (#441)


Not a bug. it's a feature.
Just encode the textstrings in any way you like yourself

Or use enableDRM in combination of closeRemoteHandle and a plugin that externally checks if enableDRM works as it should on an interval and that no remote handles are open

―
