### ISSUE TITLE
[Suggestion] Add negative pointers in pointer search

### ISSUE THREAD

**Issue by JustForNothing** [cheat-engine/cheat-engine#444]
In the advanced options of the pointer searcher: Add "pointer can be negative" checkbox.

For example:
[[0x48055DE0] + 0xF58] + 0x550 (without negative search)
[0x480544F0] - 0x550 (with negative search)

**Comment by cheat-engine** [comment]
Why would you use negative offsets? Which object oriented programming language uses inverse structures ?

**Comment by JustForNothing** [comment]
c++ I think, I found a negative pointer with a different pointer searching tool so I thought it would be useful. (ARM32)

**Comment by cheat-engine** [comment]
I've added negative offset scans, though not sure how useful it will be

**Comment by JustForNothing** [comment]
Thanks, I will take a look

**Comment by JustForNothing** [comment]
I get the following message during the compilation:
Error: Duplicate resource: Type = 24, Name = 1, Lang ID = 0000

**Comment by cheat-engine** [comment]
in project settings turn of the use of manifests

**Comment by JustForNothing** [comment]
looks like it's working
