### ISSUE TITLE
Speed Hack Not Working In Firefox Quantum.

### ISSUE THREAD

**Issue by alifunterz** [cheat-engine/cheat-engine#446]
Hi Cheat Engine/Dark Byte,

I used Cheat Engine in Flash Games (Web-Based). It was working fine before Firefox Quantum but now I can't use Speedhack when I try It says 
" Failure enabling speedhack. (DLL injection failed): Unknown error during injection " 
Please help fix this issue, I am still using the older version of Firefox for hacking in Flash Games. I really want to use the latest version all the time. Thanks in Advance.

**Comment by cheat-engine** [comment]
See if you can find a parameter or config option in firefox to allow injection.  (e.g disable sandbox mode, run as admin, etc...)

**Comment by cheat-engine** [comment]
have you tried 6.8.2 which falls back to manual mapping ?

**Comment by kusalux** [comment]
Hey, I did try it with ff 65.0.2 and CE 6.8.3 on Win 10 17763.316 testing https://www.w3schools.com/graphics/game_intro.asp in a single window and it did not work. (It does work elsewhere, just to check it's not some general problem. Also other Browsers, Opera 58.0.3135.68 OK, Edge 44.17763.1.0 had already 5 processes though 1 Window, on 4 nothing changed, 5th CE would crash, Vivaldi 2.3.1440 Somewhat working, 0,0 Speed stops it, but after reenable instant crash against wall, other speeds seem useless)

**Comment by alifunterz** [comment]
Hello,

First of all sorry for the late reply, I was really busy in my exams. cheat-engine, I downloaded the latest version 6.8.3 and now I am facing another issue with the Speedhack that can be enable or disable but not working. Same like the old version but the only change is that this one is not giving any error and I can enable Speedhack and can change it but not working on Flash Games. Hope you understand, Sorry for the bad English.
