### ISSUE TITLE
Cheat Table copy and paste bug

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#447]
1. Select an item which is not a script
2. Press return key which opens the inline editor for the value
3. Select value with shift and arrow keys
4. Press CTRL+C

It copies nothing to clipboard instead of value.

**Comment by fade2gray** [comment]
I've always double clicked the value - following your example doesn't copy anything to the clipboard for me using 6.8.1

**Comment by Symbai** [comment]
You are correct, it copies nothing to clipboard. Still a bug as its expected to copy the selection (selected value) to clipboard. That you can also edit the value via double click is irrelevant for this bug.

**Comment by cheat-engine** [comment]
I can not reproduce this.
By default the text is already selected and moving the cursor and then use shift+cursor followed by ctrl+c works for me

**Comment by Symbai** [comment]
Nevermind, read your post again and noticed it automatically selected the value by default which is not clear to me as its not really visible but just pressing return and then copy+c copies the whole value into clipboard.
