### ISSUE TITLE
help bypass blue screen 

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#451]
MiProcessLoadEntry

DriverSection Delete Bypass Success

http://daaxr.blogspot.com/2017/09/hiding-drivers-without-triggering.html

memscan.c

BOOLEAN ReadProcessMemory(DWORD PID, PEPROCESS PEProcess, PVOID Address, DWORD Size, PVOID Buffer)

if ((loadedbydbvm) || ((UINT_PTR)source < 0x8000000000000000ULL))
{
RtlCopyMemory(target, source, Size); <Here 
ntStatus = STATUS_SUCCESS;
}

A blue screen occurs when you run the engine and open the process

Exception occurred in readprocessmemory
(RTLCOPYMEMORY)

This is a bypassed driver that does not have a non-normal driver section

I would like to bypass the blue screen when opening the process

Thank you

**Comment by kitty8904** [comment]
RtlCopyMemory -> NoExceptions_CopyMemory(target, source, Size);

Changing to NoExceptions_CopyMemory will not cause a blue screen

But Virtual Alloc Memory View Not Zero

00 00 00 00 -> 28 30 28 30 28 30

00 00 00 00  -> 51 51 51 51 51 51

![bbb](https://user-images.githubusercontent.com/18622105/48409122-5c958b00-e77e-11e8-9cdd-352b93ac9356.png)

Strange garbage values are displayed when empty space addresses are created

Where can I fix it in the NoExceptions_CopyMemory function? I'm curious I have a problem with reading

===================================================
This is not a normal driver

You have deleted the driver section with MiProcessLoadEntry

I want to solve the memory view problem. I do not know how to solve it

**Comment by cheat-engine** [comment]
It's possible that the memory allocation failed (or succeeded in the wrong process)
Can you read other memory regions properly ?

Have you already disabled the spectre protection on your system ?  (The one that splits up kernelmode from usermode)

**Comment by kitty8904** [comment]
If a memory area contains even a single byte, it will be read

Only strange bytes or unallocated addresses show strange addresses in memory segments that are not allocated anything

ex) cheat engine.exe +1000 = Posssible Memory

virtual alloc -> 5475000 = Error Read Memory

and intel Specter is also disabled

If a byte is modified in the memory window that is displayed as an error, it is read normally again


![gkgk](https://user-images.githubusercontent.com/18622105/48418265-2c5ae600-e798-11e8-9a55-8576a554a883.png)


mmsecurevirtualmemory?

When I search Google, it is implemented as a function called mmsecurevirtualmemory for reading and writing. Is this solving the problem?

If you need the miprocessloadentry function, you can email me. I do not know how to solve the read memory

**Comment by cheat-engine** [comment]
ah yes, I forgot that freshly allocated memory hasn't been assigned physical memory yet(Or not initialized at least). Therefore accessing it will trigger a page exception. 
To make it available you need to use a windows level (with exceptions) access to it so it gets assigned physical memory

As for the crash on start, it's likely that CE tries to access unreadable memory, and from what i've seen when a driver is hidden(e.g loaded by dbvm), try/except stops working, so in case of a hidden driver youy need to protect yourself against that.  When the loadedbydbvm flag is set it usually makes the code take a safer and slower route

(also, that `if ((loadedbydbvm) || ((UINT_PTR)source < 0x8000000000000000ULL))` should probably be a `if ((UINT_PTR)source < 0x8000000000000000ULL)) && (!loadedbydbvm) ` )

**Comment by kitty8904** [comment]
//if ((loadedbydbvm) || ((UINT_PTR)source < 0x8000000000000000ULL))

FIX
if ((!loadedbydbvm) && ((UINT_PTR)source < 0x8000000000000000ULL))
{
NoExceptions_CopyMemory(target, source, Size)
ntStatus = STATUS_SUCCESS;
}

Changing the above will result in an empty space access read error. I do not know how to deal with error handling

![test](https://user-images.githubusercontent.com/18622105/48420852-a5f5d280-e79e-11e8-956c-9d104acea8db.gif)

**Comment by cheat-engine** [comment]
Stop testing with allocated memory.  It doesn't have any physical memory associated so NoExceptions_CopyMemory will fail (Your code doesn't check the result).  Just write to memory you have allocated using normal write operations (NOT NoExceptions) and hope it did allocate properly

**Comment by kitty8904** [comment]
if (((UINT_PTR)source < 0x8000000000000000ULL) && (!loadedbydbvm))
				{
					RtlCopyMemory(target, source, Size);
					ntStatus = STATUS_SUCCESS;
				}
				else
				{
					i = NoExceptions_CopyMemory(target, source, Size);
					if (i != (int)Size)
						ntStatus = STATUS_UNSUCCESSFUL;
					else
						ntStatus = STATUS_SUCCESS;
				}


![test2](https://user-images.githubusercontent.com/18622105/48422127-549b1280-e7a1-11e8-8fc4-8c6957805fe0.gif)

Blue screen does not occur, but empty space address is displayed as ?? ??

**Comment by cheat-engine** [comment]
That's to be expected, because as I mentioned, the empty space has no RAM associated to it.

You can of course let the allocation code fill the memory with something first so it gets RAM allocated

**Comment by kitty8904** [comment]
I want to solve it

I did not know how to solve the problem for a few days, so I contacted you. What should I do?

Memory read error I do not know how to fix it

Temporarily, only need to write once, but this is not a smart way to do it.

I want to use it like a normal cheat engine view

**Comment by cheat-engine** [comment]
Try mapping the memory in a way that does NOT trigger anything that can raise an exception that you need to use try/except for 

Perhaps mmsecurevirtualmemory can be used without is bsod'ing too often
