### ISSUE TITLE
cheat engine memory view dissembler dead

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#454]
81 FF FF 48 03 F8 49 BE 00 00 00 00 80 ED FF FF 48 89 7D 50 49 BD 00 00 00 00 00 00 00

memory view-> Dissembler View -> Crash Memory View 

--memory view dead assembler --
alloc(crash,1024)
registersymbol(crash)
crash:
db 81 FF FF 48 03 F8 49 BE 00 00 00 00 80 ED FF FF 48 89 7D 50 49 BD 00 00 00 00 00 00 00

dissembler view open crash

There is HEX data that terminates in assembler view

**Comment by cheat-engine** [comment]
Describe the crash.  What error occurs ?

**Comment by kitty8904** [comment]
no hidden driver, click the OK button to apply the script memory view dissembler window crash

**Comment by kitty8904** [comment]
windows 10 redstone 5 1809 version

**Comment by kitty8904** [comment]
script data 

alloc(crash,1024)
registersymbol(crash)
crash:
db 40 55 53 56 57 41 55 41 56 41 57 48 8B EC 48 83 EC 50 48 8B DA 48 8B F9 33 D2 48 8D 4D D0 44 8D 42 28 E8 49 2A 1C 00 48 F7 C3 FF 0F 00 00 BE 00 00 00 00 48 B8 F8 FF FF FF 7F 00 00 00 40 0F 95 C6 48 C1 EB 0C 48 03 F3 48 C1 EF 09 48 89 75 48 48 23 F8 48 89 75 D0 48 89 75 E8 48 B8 00 00 00 00 80 F9 FF FF 48 03 F8 49 BE 00 00 00 00 00 93 FF FF 48 89 7D 50 49 BD 00 00 00 00 00 00 00 80

**Comment by kitty8904** [comment]
ex ) script start address 8080000 -> dissembler memory view -> mouse down drag -> 8080068 ~80800XX address engine crash down

**Comment by kitty8904** [comment]
windows 10 redstone 5

dbk64.sys driver load -> crash

dbk64.sys driver no load -> not crash

**Comment by kitty8904** [comment]
And does DBVM not work right now? DBVM does not load the latest source

**Comment by kitty8904** [comment]
gif image 
![2018_11_19_23_14_56_916](https://user-images.githubusercontent.com/18622105/48712442-1c884980-ec51-11e8-8ef1-0b4a8ff72d29.gif)

**Comment by cheat-engine** [comment]
I am unable to reproduce this.  Undo ALL your changes (get a git snapshot) and try with that

**Comment by kitty8904** [comment]
> I am unable to reproduce this. Undo ALL your changes (get a git snapshot) and try with that

Tested on Windows 10 Redstone 5(winver 1809)

Stops only when the driver is loaded

I do not know what part is wrong

thank you

**Comment by kitty8904** [comment]
I do not know why the disassembler crashes during the analysis.

maybe  48 03 F8  -> 49 BE 00 00 00 00 <- 49 BE or 93 FF ?? 

49 BE ??

**Comment by kitty8904** [comment]
I do not know why the error disappeared after reinstalling Windows

The issue is resolved and closed
