### ISSUE TITLE
'Fill Memory' tool does not accept 64bit addresses

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#458]
Memory Viewer -> Tools -> Fill Memory

First address does not allow 64bit addresses. It cuts off at 8 chars, where the 'to' field accepts 64bit addresses (addresses contains more than 8 chars).

![image](https://user-images.githubusercontent.com/14368203/48972488-5bd4e280-f023-11e8-9e71-c2fa4c00cd2c.png)

**Comment by cheat-engine** [comment]
should be fixed now

**Comment by Symbai** [comment]
It now accepts 64bit addresses but it doesn't work:
![64](https://user-images.githubusercontent.com/14368203/49648752-f15a7400-fa1e-11e8-9822-4a2a732cac19.gif)

where in 32bit it works:
![32](https://user-images.githubusercontent.com/14368203/49648762-f61f2800-fa1e-11e8-9453-b57d80108bcc.gif)

**Comment by cheat-engine** [comment]
should work now
