### ISSUE TITLE
delphi xe10 use cepluginsdk

### ISSUE THREAD

**Issue by xunni1000** [cheat-engine/cheat-engine#459]
function InitializePlugin(ExportedFunctions: PExportedFunctions; pluginid: dword):BOOL; stdcall;
var init: TFunction5;
begin
  ce_exported:=ExportedFunctions^;
  init.name:='test';
  init.shortcut:='Ctrl+Alt+P';
  init.callbackroutine:=@InjectPacketEditor;
  ce_exported.registerfunction(pluginid, ptMainMenu, @init);
  result:=true;
end;

Menu names only show the first char & '   C'  
what should I do?

![2018-11-26 224414](https://user-images.githubusercontent.com/6988291/49021424-8bbfe980-f1cd-11e8-98c7-2ee0358ae344.jpg)

**Comment by cheat-engine** [comment]
looks like you're giving it widestrings instead of utf8/ascii strings

**Comment by xunni1000** [comment]
thanks,
   use utf8string is work.    


function GetVersion(var PluginVersion:TpluginVersion; sizeofpluginversion:integer):BOOL; stdcall;
var s:PansiChar;
begin
  result:=false;
  if sizeofpluginversion<>sizeof(TPluginVersion) then exit;

  s:=PansiChar(utf8String('中文测试 : chinese test'));
  getmem(versionname,length(s));
  copymemory(versionname,@s[0],length(s));
  versionname[length(s)]:=#0;

  PluginVersion.version:=PluginVersionSDK;
  PluginVersion.pluginname:=VersionName;


  result:=true;
end;
