### ISSUE TITLE
Change opcode gets overriden by breakpoint hit

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#460]
Double click an opcode to open the window that lets you change it. When you now change it and press ok but meanwhile a breakpoint got hit, it overrides the instruction of the current breakpoint address.

This is problematic for two reasons:
1. Its not the expected behavior. Double clicking a specific instruction lets you think you change THIS instruction only and not whatever the memory viewer does in background.
2. You normally cannot change the instruction of the current debugging address. But when this bug occurs and you accidentally modified it, you cannot restore the changed instruction yourself without doing a step through.

I think CE does not temporarily saves the address when the change opcode window opens and changes the instruction of the current selected address when the user clicks ok. But when selected address gets changed by BP hit or anything else the bug above occurs.

**Comment by Symbai** [comment]
![ezgif-4-d445165e6b29](https://user-images.githubusercontent.com/14368203/49648221-de46a480-fa1c-11e8-8782-63be81aa85c8.gif)

**Comment by cheat-engine** [comment]
shouldn't happen anymore (it now remembers the address you're editing)
