### ISSUE TITLE
Script fails to inject without error

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#462]
Minor bug, when readmem contains a symbol which is not declared the script fails to inject but no error message is given. Perhaps it might be useful to give an error for this too like else where when a symbol is unknown. Example script

```
[ENABLE]
aobscanmodule(INJECT,KERNEL32.DLL,B8 01 4C CD 21)
alloc(newmem,$1000,"KERNEL32.DLL"+49)
label(code)
label(return)

newmem:
db CC
readmem(nonexisting+4, 4) //invalid but doesn't produce an error


code:
  mov eax,21CD4C01
  jmp return

INJECT:
  jmp newmem
return:
registersymbol(INJECT)

[DISABLE]

INJECT:
  db B8 01 4C CD 21

unregistersymbol(INJECT)
dealloc(newmem)
```

**Comment by cheat-engine** [comment]
I can't reproduce this. When I execute the script I get the error: "Error in line 11 (readmem(nonexisting+4, 4)) :Invalid address for ReadMem"

**Comment by Symbai** [comment]
@cheat-engine Add this to the cheat table first and then try to activate the it. Don't press "Execute" button in script editor.

**Comment by cheat-engine** [comment]
That is normal behavior.  CE never gives any errors when activating a script by the checkbox

**Comment by Symbai** [comment]
@cheat-engine Ok but a syntax check is performed when adding it to the cheat table, like it complaints when a module does not exist in attached process or an address is invalid. Why does readmem not gives an error there?

**Comment by cheat-engine** [comment]
Same reason why  this also works:
```
[enable]
unknownaddress:
nop
nop
nop

[disable]
```

(I know it's not 100% the same all the time, but it's a syntax check, not a script check)

**Comment by Symbai** [comment]
When it only checks the syntax and not the script, I don't understand why this for example raises an error when trying to add it to the table, syntax is valid:

Raises "Failure to determine what 'unknownModule.dll+13BD54' is", but syntax is valid
```
[ENABLE]
alloc(newmem,2048,unknownModule.dll+13BD54)
 
[DISABLE]
dealloc(newmem)
```

or this raises an "This address specifier is not valid" exception, but syntax is valid:
```
[ENABLE]
unknownModule+12:
db 0

 [DISABLE]
```

Your example fails too but only when you run it in strict mode, again the syntax is valid:

```
{$strict}
[enable]
unknownaddress:
nop
nop
nop

[disable]
```
