### ISSUE TITLE
ReadProcessMemory error address

### ISSUE THREAD

**Issue by InvisibleLeVen** [cheat-engine/cheat-engine#463]
![image](https://user-images.githubusercontent.com/24772156/49695686-bf414180-fbd9-11e8-9dc4-be43fb59f238.png)

**Comment by InvisibleLeVen** [comment]
I can't figure out why it ReadAddress is ff9a0000

**Comment by cheat-engine** [comment]
why not ? What are you even trying to do ?

**Comment by InvisibleLeVen** [comment]
I'm trying to hook ReadProcessMemory. let my driver return data to this function, when I hooked 
 it ,cheatengine can not work normally.I debug it find this. as you can see.The previous address is correct  400000 400001 .... but the latter address is always ff9a0000. Obviously this is not the address it should read.

**Comment by cheat-engine** [comment]
why not? CE interprets disassembles instructions and reads the bytes they point at as well
