### ISSUE TITLE
Get cheatengine installation folder

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#467]
Would be nice to store CE installation folder in registry so it can be determined by external software.

**Comment by FreeER** [comment]
Isn't it just always installed in program files which has an environment
var? At least if it's actually installed and not the zip

**Comment by Symbai** [comment]
No, you can set the path yourself during installation. There are workaround by checking the icon or .CT extension in registry to obtain the path but as CE already stores settings in registry, it would be nice to just have the installed path included in Software\Cheat Engine\.

**Comment by cheat-engine** [comment]
I'm not sure that it should be a default thing in CE to set the install folder, and not to mention that there are people that don't use the installer

But for people that want the install folder in their settings, just run this lua code:
`getSettings().Value['CELocation']=getCheatEngineDir()`

**Comment by Symbai** [comment]
I think the best would be if you just let the installer add a registry key. This way there will be a standard way for others to determine if and where CE is installed and for portable version there is no sense to have it anyway (portable != installed). 

Running a lua code in CE to set the installation folder is not what this request was about. It was mean to determine the installation folder in general. For example I wrote a launcher and would like to integrate running CE but I don't know if the person using this launcher has installed CE and if this person has, then where its being installed.

**Comment by cheat-engine** [comment]
cheat engine's installer registers the .ct file extension
Root: HKCR; Subkey: "CheatEngine\shell\open\command"
