### ISSUE TITLE
recent disassembler changes cause 'Illegal character' error

### ISSUE THREAD

**Issue by mgrinzPlayer** [cheat-engine/cheat-engine#474]
Launch  CE 64bit 6.8.2.5700
Attach CE to itself
Go to address 00403FBD

Create autoassemble script at this address, use "AOB Injection" template. Assign to table.
Save table as CT file

You will see:
![obraz](https://user-images.githubusercontent.com/9157726/50386047-d4d95f80-06df-11e9-8d06-dfc3d169250c.png)

Alternatively, execute this Lua script:
```Lua
if sl==nil then sl=createStringlist() end
sl.clear()
generateAOBInjectionScript(sl,'test','00403FBD')
print(sl.Text)
```
output text will be cut at this line:
```Asm
call qword ptr [rax+00000228]
```

CE 6.8.1 doesn't have this bug.
Probably something with commas in disassembler unit.

**Comment by cheat-engine** [comment]
I can't reproduce this with 6.8.2.5700 that has been released on github

Do you have any plugins or lua scripts that add disasssembler information ?

**Comment by mgrinzPlayer** [comment]
Fresh CE install, removed autorun folder, removed registry keys.

Lua script:
```Lua
if sl==nil then sl=createStringlist() end
sl.clear()
generateAOBInjectionScript(sl,'test','00403FBD')
print(sl.Text)
```

Should print whole autogenerated AA with AOB.

**Comment by mgrinzPlayer** [comment]
Thank you
