### ISSUE TITLE
Stop on release in 8.2.1

### ISSUE THREAD

**Issue by Hexogenx** [cheat-engine/cheat-engine#495]
Related to issue #346 

The bug is back again. Holding a stop on release hotkey toggles the speedhack on and off while the key is held

**Comment by cheat-engine** [comment]
In 1.8.1 it did work ?

**Comment by cheat-engine** [comment]
should be fixed now

**Comment by Hexogenx** [comment]
Yep, have tested a bit with a build from today. Issue is fixed.

**Comment by yammahatom** [comment]
it come back again, keep turn on-off while i press key

**Comment by aimismyname** [comment]
can confirm as of 29 Dec 2025, bug is back.

**Comment by fade2gray** [comment]
Hasn't worked since 7.6 was first released to the public in Feb '25. Works in the Patreon version though, so you may have to wait for 7.7 to be released.
