### ISSUE TITLE
Feature request: Remote PC scan support

### ISSUE THREAD

**Issue by wixyer** [cheat-engine/cheat-engine#497]
Idea: Make CE support remote PC memory scanning (via driver possibly).

For example:
A target computer `X` would run a background process (implemented using a driver) which would allow another computer on (LAN) network to scan processes' memory. This could be done using socket/TCP for communicating between computers.

In my opinion, this is very cool feature, because it would also hide the presence of Cheat Engine (UI) windows, commonly searched by some game anti-cheats.

**Comment by cheat-engine** [comment]
Feel free to port over ceserver to use the windows API

Also, you can use translation files and/or lua to change window captions
