### ISSUE TITLE
Code review: debug_setBreakpoint (parameter handling)

### ISSUE THREAD

**Issue by Raijinili** [cheat-engine/cheat-engine#50]
I think there are some problems in the [`debug_setBreakpoint`](https://github.com/cheat-engine/cheat-engine/blob/21393be5766a4787ea6d58a9240820212dd4e944/Cheat%20Engine/LuaHandler.pas#L2498) function. This is my first time looking at Pascal code and I'm not too versed on Cheat Engine, so I'm not sure if these are bugs or features.
1. [This](https://github.com/cheat-engine/cheat-engine/blob/21393be5766a4787ea6d58a9240820212dd4e944/Cheat%20Engine/LuaHandler.pas#L2488) seems wrong. The error message from getting 0 args will never be reached, and you just [pop the stack](https://github.com/cheat-engine/cheat-engine/blob/21393be5766a4787ea6d58a9240820212dd4e944/Cheat%20Engine/LuaHandler.pas#L2596). (Should you pop the stack even if you raise an exception?)
   
   ```
   if parameters>=1 then
   begin
     if parameters>=1 then
     begin
       <process address>
     end else raise exception.create('debug_setBreakpoint needs at least an address');
   <rest>
   end
   ```
2. If args are `(address, function)`, size isn't set to the default of 1.
3. The argument tuple `(address, size, function)` isn't allowed. The third parameter will always be parsed as `trigger`.

I've submitted pull request  #49 to address these.

Also, why do some functions use

```
lua_isstring(L, -1) 
```

and others use

```
lua_isstring(L, 1)
```

?

**Comment by Raijinili** [comment]
If I understand correctly, `(address, size)` and `(address, size, function)` don't make much sense, because `size` is ignored if `trigger` isn't set to read or write. It would be simple to refactor it to always grab `size` and `trigger` together, but maybe it's better to allow `size` without `trigger` and document that it will be ignored. Or, if possible, maybe make it so that an execute breakpoint with a size parameter covers the whole region.

(Shouldn't `trigger` have been provided before `size`, then? And it also means that `size` doesn't need to default to 1, because if `trigger` isn't provided, `size` will be ignored anyway.)

**Comment by cheat-engine** [comment]
if trigger is ignored, it's an execute breakpoint, and those have no size.

The -1 and 1 thing is a thing from before I fully understood the lua stack but ultimately won't cause issues
