### ISSUE TITLE
Access Violation when trying to make an AOB injection template

### ISSUE THREAD

**Issue by PonyWarrior** [cheat-engine/cheat-engine#504]
![ce_error](https://user-images.githubusercontent.com/22421356/51571741-608f0900-1ea3-11e9-87eb-e328def449f0.gif)

When I do this I get an access violation error, at first I thought it was because I changed the file name of the executable and other stuff, but even after discarding all my changes and pulling the latest commit the error is still there. 

The strangest thing is when I did this with the cheat engine version available on the website there was no such error. I also checked, its not specific to one program, I can't make an AOB injection template for any program. Besides, I get this access violation error occasionaly while using my compiled CE, although it is rare for it to happen I've noticed some of the previous issues mentioning it.

**Comment by PonyWarrior** [comment]
![screen shot 01-23-19 at 12 32 am](https://user-images.githubusercontent.com/22421356/51572679-91247200-1ea6-11e9-9942-0a2ddb4f89ca.PNG)

I don't understand, I am using the latest git version, up to the latest commit two days ago, as can be seen in the screenshot. If I missed something please do tell me, and thank you for responding so fast.

**Comment by cheat-engine** [comment]
run it under the debugger in debug mode (64 bit no mp)  build and see where it happens.

**Comment by PonyWarrior** [comment]
![screen shot 01-23-19 at 11 52 am](https://user-images.githubusercontent.com/22421356/51601691-5c93d300-1f05-11e9-95a1-e69c55616571.PNG)

I am trying to debug (jan9 version) but the debugger is locked on this line, as if stuck in a loop; I've clicked a thousand times on continue (green execute arrow) but it is stuck on this line. I've tried all the configurations for the project but all of them have this issue. I'm gonna try with lazarus 1.6 (currently 1.8.4) and see if it works.

**Comment by cheat-engine** [comment]
view the stacktrace in lazarus (it's under view-debug)

**Comment by cheat-engine** [comment]
it's a bug in lazarus 1.8 (i think setting index to -1 does that)

**Comment by PonyWarrior** [comment]
![ce_error3](https://user-images.githubusercontent.com/22421356/51605751-3f183680-1f10-11e9-8850-43f67e74c535.gif)

I am building for 64 bits (I already tried building every other configurations) and have this issue on lazarus 1.6. Did this with both January 9 git version and the latest git version to no avail.

Back on lazarus 1.8 I do not know where this index is, it doesnt seem to be located in the project options? I have never used lazarus before please excuse my lack of knownledge.

**Comment by PonyWarrior** [comment]
I have tried both ways but it didn't help (still on lazarus 1.6). Perhaps the index thing on 1.8 would work, but I don't know what it is or how to modify it.

**Comment by mgrinzPlayer** [comment]
I get the same thing with official Lazarus 1.8.4
