### ISSUE TITLE
getHandleList?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#505]
getHandleList?

getHandleList How do I use the LUA function?

How do I check the handle table list information?

<img width="354" alt="1" src="https://user-images.githubusercontent.com/18622105/51701886-bdcabc00-2055-11e9-888a-37c267d8b596.png">

      lua_pushstring(L, 'ProcessID');
      lua_pushinteger(L, shi.list[i].ProcessId );
      lua_settable(L,-3);

      lua_pushstring(L, 'ObjectTypeIndex');
      lua_pushinteger(L, shi.list[i].ObjectTypeIndex );
      lua_settable(L,-3);

      lua_pushstring(L, 'HandleAttributes');
      lua_pushinteger(L, shi.list[i].HandleAttributes );
      lua_settable(L,-3);

      lua_pushstring(L, 'HandleValue');
      lua_pushinteger(L, shi.list[i].HandleValue );
      lua_settable(L,-3);

      lua_pushstring(L, 'Object');
      lua_pushinteger(L, ptruint(shi.list[i].obj));
      lua_settable(L,-3);

      lua_pushstring(L, 'GrantedAccess');
      lua_pushinteger(L, shi.list[i].GrantedAccess );
      lua_settable(L,-3);

      lua_settable(L,1);

I wonder how to check table output information

**Comment by cheat-engine** [comment]
it returns an indexed table

tip: do 
return getHandleList(2)

**Comment by kitty8904** [comment]
> it returns an indexed table
> 
> tip: do
> return getHandleList(2)

thank you
