### ISSUE TITLE
(Auto) Assembler bug

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#508]
AA:
`cmp rax,00000000F0000000`
gets assembled as
![image](https://user-images.githubusercontent.com/14368203/51802631-e7e1d100-2243-11e9-920a-f077bdcad999.png)

Which makes this compare fails when RAX is 00000000F0000000.

**Comment by cheat-engine** [comment]
cmp can only handle 32-bit values, but because you give a 64-bit register it gets sign extended (the most significant bit in the 32-bit value gets duplicated till the end)

you need to use:
```
push rbx
mov rbx,00000000F0000000
cmp rax,rbx
pop rbx
```

**Comment by Symbai** [comment]
Oh... okay, thanks!
