### ISSUE TITLE
Code review: debug_removeBreakpoint mishandles bad address

### ISSUE THREAD

**Issue by Raijinili** [cheat-engine/cheat-engine#51]
Source code: https://github.com/cheat-engine/cheat-engine/blob/master/Cheat%20Engine/LuaHandler.pas#L2610

```
if lua_isstring(L, -1) then
begin
  e:=false;
  address:=symhandler.getAddressFromNameL(lua_tostring(L, -1));
  if e then //unrecognizable address
  begin
    lua_pop(L, lua_gettop(L));
    exit;
  end;
end
```

The function checks a local variable (which can't change by calling another function). It also exits on error.

The [`getAddressFromNameL`](https://github.com/FastFrench/cheat-engine/blob/45fa0407dfd9452eb97108eb215869caa8507399/Cheat%20Engine/symbolhandler.pas#L2237) function returns 0 on a bad address (or throws an exception, if that flag is set).

Also, should `debug_removeBreakpoint` return `result:=1` on failure instead?

**Comment by cheat-engine** [comment]
should be fixed by now. Closing
