### ISSUE TITLE
Disassembler error

### ISSUE THREAD

**Issue by wonderzdh** [cheat-engine/cheat-engine#510]
windbg
000007fe`e065c8c0 c5fb102d88e80800 vmovsd  xmm5,qword ptr [ucrtbased!__Lsinarray+0x50 (000007fe`e06eb150)]

cheat engine
ucrtbased.sin+3D0 - C5 FB                 - lds edi,ebx
ucrtbased.sin+3D2 - 10 2D 88E80800        - adc [ucrtbased.wctype+1F030],ch { [F9A43BB8] }

**Comment by cheat-engine** [comment]
Make sure you're using CE 6.8.2

**Comment by wonderzdh** [comment]
sorry i used CE 6.5
