### ISSUE TITLE
my intel i9 9900k vmdisk bsod?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#511]
i9 9900k

8core 16thread 

DBVM Load Break Point -> 1~2min

CLOCK_WATCHDOG_TIMEOUT BSOD

https://wiki.cheatengine.org/index.php?title=DBVM

Specter function was OFF

Reducing the number of CPUs will not result in a blue screen?

Test Windows 10 1809 x64

**Comment by kitty8904** [comment]
<img width="373" alt="1" src="https://user-images.githubusercontent.com/18622105/51927984-35bf2a80-2438-11e9-9fa2-f20d2fd6a23c.png">

16core 32thread load

Freezing occurs when DBVM is fully loaded and breakpoint is applied

Loading DBVM slows down your computer

it because of too many cores causing breakpoints to stop and watch time blue screens in five minutes?

**Comment by kitty8904** [comment]
<img width="331" alt="2" src="https://user-images.githubusercontent.com/18622105/51928207-b41bcc80-2438-11e9-92ab-d195565ff33d.png">

The Specter function is off Windows 10 1809

Loading DBVM slows down my computer

I had a problem with too many cores in my knowledge

I do not know how to solve DBVM currently available

**Comment by kitty8904** [comment]
Could it be a RAM size issue? 32GB

**Comment by cheat-engine** [comment]
Is this 'find what accesses" or 'dbvm find what accesses" ?

**Comment by kitty8904** [comment]
find what accesses

**Comment by cheat-engine** [comment]
try dbvm find what accesses and see if that crashes the same way

it could be a spectre thing (interrupt hooking won't work with different cr3's for usermode and kernelmode)

**Comment by kitty8904** [comment]
dbvm find out what access -> No BSOD

**Comment by kitty8904** [comment]
Memory Management Option Disabled 

Do I need to remove another Specter Option other than the Specter function with the registry change?
