### ISSUE TITLE
Pointerscan resume: "Error during scan: StaticScanner:invalid data:16"

### ISSUE THREAD

**Issue by mgrinzPlayer** [cheat-engine/cheat-engine#512]
![obraz](https://user-images.githubusercontent.com/9157726/51985295-d431a700-249d-11e9-98d6-203683e3efe0.png)

While debugging in Lazarus/gdb:
![obraz](https://user-images.githubusercontent.com/9157726/51986121-d3017980-249f-11e9-8e99-ee9c65763096.png)
https://github.com/cheat-engine/cheat-engine/blob/c595362dabd2f92b0d9d5f925eb923ca2f5cf5ae/Cheat%20Engine/pointerscancontroller.pas#L1114-L1131

Scan settings (64bit CE, 64bit target):
![obraz](https://user-images.githubusercontent.com/9157726/51986324-46a38680-24a0-11e9-97eb-85db7e43611f.png)

**Comment by cheat-engine** [comment]
i'll check it out.
can you reproduce it with 1 thread? 
Debug build or release build ?

If it works with 1 thread it also helps to have those two scandata files

**Comment by mgrinzPlayer** [comment]
Initial 1-threadscan and 1-threadscan-resume, still shows this bug.

CE from 20 Dec 2018 and current commit ebc549abfdaf5d7217f19e30566f3d7d7add36ef

**Comment by mgrinzPlayer** [comment]
I will post PTR files too (with config and queue files).

Here:
[ptrfiles.zip](https://github.com/cheat-engine/cheat-engine/files/2814230/ptrfiles.zip)

**Comment by cheat-engine** [comment]
should work now.  Though suspending a resumed scan is still wonky

**Comment by mgrinzPlayer** [comment]
> suspending a resumed scan is still wonky
Looks like you can safely suspend/stop when number in this window:
![obraz](https://user-images.githubusercontent.com/9157726/52015139-93f41800-24e1-11e9-9426-f897dc5308cf.png)

is bigger than pointers found previously. Not 100% sure...

**Comment by mgrinzPlayer** [comment]
> I was more talking about when the debugger is attached (likely a handle being closed that's invalid) but normal is ok yes.

Got it. But, when I tried this (both scandata files above, no process attached):
1) stop scanning
2) when it stops, resume it
3) after really short time, like second or two, stop scanning again
4) repeat step 2-3, CE will crash sooner or later (endless loop with windows beep/alert sound).

If you do like this:
1) stop scanning
2) when it stops, resume it
3) wait a little longer, stop scanning again
4) repeat 2-3, at some point CE will finish without any issues.
