### ISSUE TITLE
Lua Engine Access Violation

### ISSUE THREAD

**Issue by dsasmblr** [cheat-engine/cheat-engine#514]
**Problem**: In Cheat Engine 6.8.2, in the `Memory Viewer`, clicking `Tools` -> `Lua Engine` for the first time results in an _"Access violation"_ error. If attempting again, the following error displays:

![lua-error](https://user-images.githubusercontent.com/22781064/52161473-43242100-2693-11e9-9297-d3cd925e5126.PNG)

This issue happened after I opened CE, clicked `Table` -> `Show Cheat Table Lua Script`, entered a few lines of Lua, then went to open Lua Engine to test some functions. I don't see why that would have been the cause, but that's when it happened. Now I'm unable to open Lua Engine at all as this new error persists. I've tried restarting my system and checking a few things in CE, but to no avail. The only thing I haven't tried on my own accord at this point is completely resetting CE's settings and/or reinstalling CE.

Just a heads-up in case the issue is worth mentioning.

**Comment by mgrinzPlayer** [comment]
Rename autorun folder (and other lua files inside CheatEngineDir). And try again.

**Comment by dsasmblr** [comment]
Yep! It must be the font size. I DID do that as well (forgot I did that...lol).

**Comment by dsasmblr** [comment]
Out of curiosity, is there any sort of fix I can apply on my end at the moment that allows me to maintain my custom font settings?

**Comment by cheat-engine** [comment]
Besides compiling CE from the sourcecode on git not really. (or go back to 6.8.1 perhaps)
You can also disable DPI aware, that usually makes things a bit bigger as well so you don't have to use font overrides

**Comment by dsasmblr** [comment]
Cool, I'll just roll with one of those for now. I just need to get some bigger font rolling for videos so mobile viewers can watch along as well. Would you like me to go ahead and close the ticket, or do you want me to keep it open for the actual issue?

**Comment by mgrinzPlayer** [comment]
> Out of curiosity, is there any sort of fix I can apply on my end at the moment that allows me to maintain my custom font settings?

Extract to autorun folder:
[FIX_SynBaseCompletionForm_FontChanged.zip](https://github.com/cheat-engine/cheat-engine/files/2825022/FIX_SynBaseCompletionForm_FontChanged.zip)


Fix only works with 64bit CE released on 20 Dec 2018


Script:
```Lua
autoAssemble([[
define(address1,"cheatengine-x86_64.exe"+691C8B)
define(bytes1,E8 00 C3 9A FF)
assert(address1,bytes1)

address1:
db 90 90 90 90 90


define(address2,"cheatengine-x86_64.exe"+690AD5)
define(bytes2,48 8B 45 F8 48 8B B0 B0 07 00 00)
assert(address2,bytes2)

address2:
db EB 48
]], true)
```
