### ISSUE TITLE
find what accesses bsod fix?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#515]
I inquired about it last time, but I'm curious to find out how to solve blue screen

win10 1809 redstone 5

find what accesses -> CR3? Specter?

Specter register fix -> off

I turn off all Specter functions, but after debugging and terminating the targeted process, I get a Watchdog error a while back(BSOD)

Windows 7? Do I need to roll back to an earlier version of Windows 10? I can not figure out how to fix it

DBVM_find what accesses -> NO BSOD (But Memory View DBVM Debug Option -> X)

Windows 10 find what accesses & F5 Debug & F8 Debug Trace BSOD Help

I've looked all the way for a few days but can not fix it. Version 6.8.2

**Comment by Symbai** [comment]
dbvm never worked for me. I also always get a bluescreen on breakpoints, CE claims that my system supports it and loading the driver itself works.

At the time when I tried people on CE forum says its because my processor has more than 4 logical cores and CE wouldn't work with that. I believe there was also some people saying Intel's hyperthreading is not supported either by CE. I don't know if anything has changed meanwhile, but you are not alone with this problem. In my case it didn't even worked before the spectre bug was announced and I've tried it on Windows 7 and Windows 8.

**Comment by kitty8904** [comment]
Does it work when I turn off Hyper-Threading on my motherboard? I'll test it once.

**Comment by cheat-engine** [comment]
get windows 7 without patches 
as for symbai havd you tried the 6.8 build if dbvm ?

**Comment by kitty8904** [comment]
<img width="339" alt="1" src="https://user-images.githubusercontent.com/18622105/52169737-ae97ec80-2780-11e9-8a7d-64888557eb66.png">

I will try the test.

Load DBVM first and wait for 1~3 hours

I will wait without debugging

I can not test Windows 7 right away

**Comment by kitty8904** [comment]
Blue screen does not  when DBVM is loaded and not debugged

Loading DBVM slows down computer?(maybe)

Conclusion If you do not attach the debug, the Watchdog blue screen does not occur

**Comment by kitty8904** [comment]
https://www.digitaltrends.com/computing/intel-9-series-cpu-spectre/

Can hardware cpu specter patches affect DBVM?

**Comment by kitty8904** [comment]
Intel hyperthreading OFF Reducing the number of CPU cores and so on. Blue screen can not be solved by all means. And loading DBVM slows down the computer (i9 9900)

**Comment by cheat-engine** [comment]
have you tried with global debug disabled ?

**Comment by kitty8904** [comment]
> have you tried with global debug disabled ?

Global Debug is not in the OFF state Is it a global debug issue?

**Comment by cheat-engine** [comment]
Not sure. Try with globaldebug off and debug something simple.  Perhaps there is an issue with handling debug events when inside kernelmode (and globaldebug triggers a lot of kernelmode breaks)

**Comment by kitty8904** [comment]
Why does DBVM slow down my computer when I load it?

Turning off global debug turns off the watchdog blue screen in about an hour 
(you have to test it several times)

I am unhappy because I do not know the cause

**Comment by cheat-engine** [comment]
DBVM slowdown is normal

**Comment by cheat-engine** [comment]
[vmdisk02142019.zip](https://github.com/cheat-engine/cheat-engine/files/2862645/vmdisk02142019.zip)
See if this version is faster (It will still BSOD with globaldebug)

**Comment by tokovik** [comment]
> [vmdisk02142019.zip](https://github.com/cheat-engine/cheat-engine/files/2862645/vmdisk02142019.zip)
> See if this version is faster (It will still BSOD with globaldebug)



> I inquired about it last time, but I'm curious to find out how to solve blue screen
> 
> win10 1809 redstone 5
> 
> find what accesses -> CR3? Specter?
> 
> Specter register fix -> off
> 
> I turn off all Specter functions, but after debugging and terminating the targeted process, I get a Watchdog error a while back(BSOD)
> 
> Windows 7? Do I need to roll back to an earlier version of Windows 10? I can not figure out how to fix it
> 
> DBVM_find what accesses -> NO BSOD (But Memory View DBVM Debug Option -> X)
> 
> Windows 10 find what accesses & F5 Debug & F8 Debug Trace BSOD Help
> 
> I've looked all the way for a few days but can not fix it. Version 6.8.2

did you solve this problem?
