### ISSUE TITLE
Feature Request: View static addresses in found list as module+offset.

### ISSUE THREAD

**Issue by dsasmblr** [cheat-engine/cheat-engine#517]
I'm not sure if this would be popular enough to merit more than a personal Lua script, but there are many occasions where I want to scan all modules for static addresses. Naturally, it's common for a ton of results to be returned. Well, instead of seeing `dereferenced/calculated` addresses in green, it would be really handy to have the option to view static addresses as `module+offset`.

This does away with the problem of having to add an address to the address list first, then double-clicking it to see which module it belongs to. And then after that, trying to discern the memory range of that particular module, and guessing at which other range might play host to one or more modules I'm interested in seeing.

I've no idea if it would be more process-intensive to add a right-click option like `"View static addresses by module name"`, or maybe to add a `new optional column called "Module"` that will display module+offset name (where applicable) next to the Address column.

The latter would perhaps be a bit more handy so as to immediately have both in view. I've been trying to create my own Lua extension to do this, but I'm currently getting hung up on how to target `FoundList3` so as to add a new column and then populate it with `module+offset`.

This brings up a related question: is there a way that, through Lua Engine, I can view all members/properties of a form? If I have something like `foundList = getMainForm().Foundlist3`, I know I then have members/properties like `.PopupMenu`. Up to this point, I've been digging through Lazarus to see what things are named and trying to target therefrom, but that's a lot more cumbersome than being able to do something like, say, `print(members(foundList))` or something of that nature.

Thanks for any help/ideas/etc.!

**Comment by cheat-engine** [comment]
```
local original=MainForm.FoundList3.OnData
MainForm.FoundList3.OnData=function(sender,item)
  original(sender,item)
  --item.Caption="Entry "..item.index
  local addressstring=getCurrentMemscan().FoundList[item.index]
  local address=getAddressSafe(addressstring)
  if address then
    item.Caption=getNameFromAddress(address,true,false) --change to true,true if you also want symbols
  end
end
```

As for getting a property list and childcontrols, you can use component.Component[0..component.ComponentCount-1] to get a list of available controls
And besides that you can use `getmetatable(component)` to get 'specialized' functions and properties not exposed by the compiler's published functions

And in 6.8.2 if you press the . (dot) after a control you will get a list of all available controls

**Comment by dsasmblr** [comment]
This is absolute gold, @cheat-engine! Thank you so much for such a detailed response. I've really begun focusing on Lua lately and how to make the most of it with creating modifications for CE, so you've boosted my troubleshooting and learning efforts immensely here. Thank you!
