### ISSUE TITLE
Speedhack Not Working on New Version of Chrome/Chromium using Windows 8/8.1

### ISSUE THREAD

**Issue by miketagz** [cheat-engine/cheat-engine#518]
Hello Admin,

Can you identify how to fix this bug when applying enable speedhack on updated version of chrome, it is not working and the worse thing is hangs up everytime you browse websites and appear recaptcha for security check. Hope there's someone to help me with. Thanks.

**Comment by cheat-engine** [comment]
I've tried https://www.w3schools.com/graphics/game_intro.asp with the latest chrome on windows 7 and it worked.  Later when home i'll try windows 10

**Comment by miketagz** [comment]
I'm using different version and still not working.
Anyway my OS Version is Windows 8.1

I do not use any sandbox software or any virtual operating system, I mean normal operations.

The issue was the recaptcha by google, it hangs.
I always tried to browse any website but I encounter recaptcha, and I want to speed it up using Cheat Engine but it is buggy on Chrome and Chromium, sometimes it doesn't work.
