### ISSUE TITLE
memory scan option view bug?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#519]
<img width="586" alt="1" src="https://user-images.githubusercontent.com/18622105/52369651-8bc54b00-2a94-11e9-85e3-ffad9352bcce.png">

Compile Lazarus 1.8.4

Two memory scan options overlap

**Comment by kitty8904** [comment]
<img width="324" alt="2" src="https://user-images.githubusercontent.com/18622105/52370347-004cb980-2a96-11e9-90e1-53419cd79e60.png">

Memory selection bar is delete?

**Comment by cheat-engine** [comment]
Try lazarus 1.6.4

**Comment by kitty8904** [comment]
> Try lazarus 1.6.4

1.6.4 -> no problem -> close
