### ISSUE TITLE
Apk，please

### ISSUE THREAD

**Issue by Crystal-RainSlide** [cheat-engine/cheat-engine#52]
Android use apk to install apps,but where is the apk file?
Or it should be made by the end-users?

**Comment by Inndy** [comment]
Android uses linux kernel which makes it possible to run ELF format executable binary file.

Here is instructions to run cheat-engine server on your Android mobile device:

1. get your mobile [rooted](http://lmgtfy.com/?q=android+root)
2. get [adb](http://developer.android.com/intl/zh-tw/tools/help/adb.html) or [terminal emulator](http://lmgtfy.com/?q=android+terminal+emulator)
3. download [cheat-engine server](http://cheatengine.org/downloads.php) to your mobile
4. copy ELF to `/data/local/tmp` and [give it executable permission](http://lmgtfy.com/?q=linux+make+file+executable), finally run it [with root permission](http://lmgtfy.com/?q=android+su+run+command)
