### ISSUE TITLE
cheatengine-x86_64.po 6.8.2 vs cheatengine-x86_64.po 6.8.3

### ISSUE THREAD

**Issue by rzndsa** [cheat-engine/cheat-engine#520]
Hello.

Size of cheatengine-x86_64.po from 6.8.2 = 455429 bytes
from 6.8.3 = 353649 bytes
(Trash strings on the top removed from both files)

difference = -101780 bytes (it's bigger because new cheatengine-x86_64.po have additional new strings).
[https://prnt.sc/mi2pwy](https://prnt.sc/mi2pwy)

Plus many strings have changed their location which makes it difficult to find newly added lines
[https://prnt.sc/mi2qrs](https://prnt.sc/mi2qrs)

So many deletions or compiler joke?

**Comment by cheat-engine** [comment]
There appears to be an issue with the .po files.  I'll see if I can fix it (likely rebuild from scratch...)

**Comment by cheat-engine** [comment]
Try this .po file : 
[cheatengine-x86_64.zip](https://github.com/cheat-engine/cheat-engine/files/2849097/cheatengine-x86_64.zip)
