### ISSUE TITLE
When switching tabs mid-scan, the controls of the current view are used for the logic in other tab scan.

### ISSUE THREAD

**Issue by grasmanek94** [cheat-engine/cheat-engine#529]
Reproduction step:

1. Open CE
2. Attach
3. Open new scan tab (Tab 2)
4. Go to Tab 1
5. Start a long scan (e.g. searching for value 0, single byte)
6. Go to Tab 2
7. Wait until scan in Tab 1 completes
8. Go to Tab 1
9. Controls for Tab 1 are disabled

**Comment by TheK0tYaRa** [comment]
The easy fix is:
1. Don't do stuff that is not intended.

**Comment by grasmanek94** [comment]
That's no fix, not even a workaround, what if someone wants to start 2 simultanious long scans?

**Comment by TheK0tYaRa** [comment]
Well, there is an axual fix: update your CE. The last one doesn't allow switching tabs mid-scan. And 2 simultaneous scans won't go faster than one by one scans.
