### ISSUE TITLE
changeregbp delphi type casting?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#530]
<img width="508" alt="7" src="https://user-images.githubusercontent.com/18622105/52823338-ed6e6080-30f7-11e9-83f0-9c080108fb83.png">

var
PhysicalAddress : int64;
changeregonbpinfo: TChangeRegOnBPInfo;
startaddress:QWORD;
hookaddress:QWORD;
begin
  startaddress:=$401000;
  hookaddress:=$402000;
  GetPhysicalAddress(processhandle,pointer(startaddress),PhysicalAddress);
  dbvm_cloak_changeregonbp(PhysicalAddress,changeregonbpinfo.newRIP,hookaddress);
end;  

Error: Call by var for arg no. 2 has to match exactly: Got "QWord" expected "TChangeRegOnBPInfo"

How do I put a test RIP in a Lazarus source?

**Comment by kitty8904** [comment]
<img width="232" alt="78" src="https://user-images.githubusercontent.com/18622105/52829492-5e217700-3110-11e9-85cf-12de3f2762f9.png">

function testeip():Boolean;
var
PhysicalAddress : int64;
changeregonbpinfo: TChangeRegOnBPInfo;
startaddress:qword;
hookaddress:qword;
r:boolean;
begin
  PhysicalAddress:=0;
  startaddress:=$4023CD;
  hookaddress:=$4023D3;
  GetPhysicalAddress(processhandle,pointer(startaddress),PhysicalAddress);
  changeregonbpinfo.newRIP:=hookaddress;
  changeregonbpinfo.Flags.changeRIP:=1;
  r:=dbvm_cloak_changeregonbp(PhysicalAddress, changeregonbpinfo, hookaddress)= 0;
  result:=r;
end;  

check a button works but an access violation occurs. What is the reason?

**Comment by cheat-engine** [comment]
Why is your startaddress different from your hookaddress?

dbvm_cloak_changeregonbp sets the breakpoint at the given physical address and then does it's thing based on the changeregonbp information. The virtual address is just a helper for CE's GUI (Not that it matters though, but just making sure that the BP address you want to set is at 4023CD and not 4023D3)

As for the access violation, try setting hookaddress to 0

**Comment by kitty8904** [comment]
I just tested NOP in one line of assembly

mov eax,[esi+1234] -> nop

hookaddress -> 0 -> No Access violation

Is there a coding problem? It works properly

////////////////////

function testeip():Boolean;
var
PhysicalAddress : int64;
changeregonbpinfo: TChangeRegOnBPInfo;
startaddress:qword;
hookaddress,hookaddress2:qword;
r:boolean;
begin
  PhysicalAddress:=0;
  startaddress:=$4023CD;
  hookaddress:=$4023D3;
  GetPhysicalAddress(processhandle,pointer(startaddress),PhysicalAddress);
  changeregonbpinfo.newRIP:=hookaddress;
  changeregonbpinfo.Flags.changeRIP:=1;
  r:=dbvm_cloak_changeregonbp(PhysicalAddress,changeregonbpinfo,0)= 0;
  result:=r;
end;

**Comment by cheat-engine** [comment]
there was an coding issue yes. if you provide a virtual address it'll mess up a critical section.  (fixed in github)
