### ISSUE TITLE
Results only in first scan

### ISSUE THREAD

**Issue by stefan5641** [cheat-engine/cheat-engine#531]
Can't find a simple money/score value in a flash game, even though it used to work normally.

Edit* I have tried restarting my pc and I have tried Running it as admin but still nothing.

**Comment by cheat-engine** [comment]
Have you reverted your browser, flash plugin and the website of that game to when it was working ?

**Comment by stefan5641** [comment]
I reset my windows 2 weeks ago the problem might have been before or after that point. I don't think I have the possibility to revert it. But I tried multiple browsers, chrome, firefox, edge and Internet Explorer with no luck.
