### ISSUE TITLE
Can't open (2/27/19) still need help

### ISSUE THREAD

**Issue by ARandomSqueaker** [cheat-engine/cheat-engine#533]
So I tried to open Cheat Engine and it didn't work, so I installed the latest version, and it still wouldn't open. I need help.
I ran it as admin, restarted my pc, and reinstalled. None of it worked.
Whenever i open it, nothing comes up/nothing happens. please help. btw i turned off all of my anti viruses

**Comment by cheat-engine** [comment]
Restart your system after turning off your AV's (actual restart, so not turn off and back on, windows 10 fakes that)

**Comment by ARandomSqueaker** [comment]
??? I turned off my anti-viruses, restarted my pc, and it still doesn't work.

**Comment by cheat-engine** [comment]
Have you tried renaming cheatengine-x86_64.exe to goat.exe and run that instead ?

**Comment by ARandomSqueaker** [comment]
I just tried that, and it doesnt work.

**Comment by cheat-engine** [comment]
what windows version do you run?  Run winver and give the version and os build

**Comment by 32Savage** [comment]
I've had the same problem as @ARandomSqueaker as well and I can't seem to find the fix to this. I've just been looking through google trying to find a fix and nothing works. The same things you have mentioned to him I have done too, and it didn't work. I am running windows 10 and my os build is 17134.590

**Comment by 32Savage** [comment]
There has to be some sort of error with either the cheatengine-x86_64.exe or that lua53-64.dll because I move every other file out of the folder that I installed it in and those are the only 2 files that that make the cheat engine attempt to run. Without either one, an error message pops up. Also, When I try running cheat engine, 2 extra backgrounds processes appear for about 5 seconds, and then disappear. The background process is called COM Surrogate, if that means anything.

**Comment by cheat-engine** [comment]
Try executing this file as administrator after placing it in the same folder as CE
[noenv.zip](https://github.com/cheat-engine/cheat-engine/files/2883739/noenv.zip)

**Comment by 32Savage** [comment]
When I execute that .bat in the ce folder this message pops up. https://gyazo.com/9428d976a4295dabb483f9d18f6df97f 

I've also tried running that windowsrepair and then reopening ce but that didn't work either. If you think   explaining how to hardcode the path using windows shell would work could you tell me how?

**Comment by cheat-engine** [comment]
replace cheatengine-x86_64.exe in that .bat file with the full path to it

Or open a cmd prompt in admin mode and go to the ce folder and run it there

**Comment by ARandomSqueaker** [comment]
How do you do that?

**Comment by ARandomSqueaker** [comment]
help pls. I still haven't gotten it fixed.

**Comment by cheat-engine** [comment]
if clearing the environment has no effect then no idea 
I recommend reinstall windows from scratch and then one by one reinstall your games and apps till ce stops working. Then you know which game messes up your system

**Comment by ARandomSqueaker** [comment]
well. how do i clear the environment? I stil havent been able to do this thing yet. can u explain in further detail so I could understand it?
 |
 |
V
replace cheatengine-x86_64.exe in that .bat file with the full path to it

Or open a cmd prompt in admin mode and go to the ce folder and run it there
Or make a shortcut to that bat file, and then in properties->advanced tick run as administrator

**Comment by cheat-engine** [comment]
open a command prompt running as admin
in there go to the folder your CE install is and run noenv.bat

example if it's installed in c:\program files (x86)\Cheat Engine 6.8.3
```
c:
cd c:\program files (x86)\Cheat Engine 6.8.3
noenv.bat
```

**Comment by ARandomSqueaker** [comment]
http://prntscr.com/msn1u0 doesn't recognize the command. Is there a DDL I have to download or something like that?

**Comment by cheat-engine** [comment]
install ce to c:\ce
and afterwards instead of
cd c:\program files (x86)\Cheat Engine 6.8.3
do
cd c:\ce

**Comment by cheat-engine** [comment]
Extract the noenv.bat file from inside that .zip file i posted above to the ce install folder

**Comment by NessDiscord** [comment]
I have the same problem and i need Cheat Engine, i have Windows 10, build 1607

**Comment by NessDiscord** [comment]
I have tried the renaming of "cheatengine-x86_64" to "goat", didn't work. Tried the noenv.bat, asked me for administrator permission but it didn't open.

**Comment by cheat-engine** [comment]
reinstall windows and then install your games one by one until it stops working again
then tell us the program that causes it

**Comment by ARandomSqueaker** [comment]
Ness, if you manage to fix the problem, please tell me how.

**Comment by ARandomSqueaker** [comment]
Oh. I updated cheat engine to 6.8.3 and this happened when i ran
c:
cd c:\program files (x86)\Cheat Engine 6.8.3
noenv.bat

http://prntscr.com/mspzyr
http://prntscr.com/msq03w
http://prntscr.com/msq08g
http://prntscr.com/msq0d9

**Comment by ARandomSqueaker** [comment]
still cant open it tho

**Comment by NessDiscord** [comment]
@cheat-engine i dont know if that has something to do.

**Comment by cheat-engine** [comment]
A fully updated windows install without any other software installed installs and runs CE just fine, so I am inclined to say it's something on your computer. (likely a backdoor trojan that tries to hide it's presence by closing things that can detect it, like CE)

anyhow, what CPU do you have? Because I've only tested on intel systems atm

**Comment by NessDiscord** [comment]
I have a Intel Core i5-4300 @ 1.90GHz

**Comment by cheat-engine** [comment]
all i can say right now is either reinstall windows or get lazarus 1.6.4 and build ce and then debug it to find the issue

**Comment by OmarAhmed04** [comment]
I'm not too sure but I think the game Apex Legends breaks cheat engine

**Comment by cheat-engine** [comment]
execute this in a cmdlist (in a dir with write access)
`driverquery /V > driverlist.txt`

and then upload the driverlist

**Comment by NessDiscord** [comment]
I already did the driverlist.txt thing and some parts are in Spanish because my Windows 10 is in Spanish and with the Windows Defender thing i edited a regedit value to keep it unabled

**Comment by ARandomSqueaker** [comment]
Question, should I disbale Windows Firewall and try to open?

**Comment by NessDiscord** [comment]
Windows Firewall affects mainly on the download of the installer, and it can't modify or delete the cheat engine files

**Comment by NessDiscord** [comment]
The one who deletes files and it happened to me, is Windows Defender

**Comment by cheat-engine** [comment]
Perhaps if you guys would provide driverlists ,servicelists and a list of installed programs, it'd be possible to figure out what causes it by matching commonoalities between your systems and discarding those of unaffected systems

**Comment by ARandomSqueaker** [comment]
Idk if this is related, but I have a logitech g203 prodigy mouse and if u use the logitech software, you can make macros, but for some reason, after I finish creating the macros, and I click the bind, it doesn't work.

**Comment by ARandomSqueaker** [comment]
Btw i tried out a program and the keybinds/macros didnt work and the dev told me this.
"Its somthing to do with getasynckeystate i dont have time to solve it im sorry"

**Comment by ARandomSqueaker** [comment]
Accidently closed it

**Comment by ARandomSqueaker** [comment]
So have you found a fix?

**Comment by cheat-engine** [comment]
No, I can't do anything unless I have full lists of applications, services and drivers by all people affected

For now all I can suggest is reinstall windows

**Comment by cheat-engine** [comment]
Which anti viruses have you used in the past or are you still using?
Some of them will block CE without giving notifications, even after disabling or uninstalling them

**Comment by NessDiscord** [comment]
I've had no antiviruses installed

**Comment by NessDiscord** [comment]
Except WDefender that is now disabled

**Comment by Zewia** [comment]
I had the same issue until I removed the Badlion minecraft client from my PC, if you have this program installed make sure to delete it.

**Comment by NessDiscord** [comment]
Oh it's the Badlion Client? I have that

**Comment by NessDiscord** [comment]
Should i deinstall it?

**Comment by ARandomSqueaker** [comment]
Oh yea i have badlion client too

**Comment by ARandomSqueaker** [comment]
Well we have something in common. Ness, can you uninstall and tell me if cheat engine works without Badlion Client?

**Comment by ARandomSqueaker** [comment]
If thats the problem, can the devs try to make it so cheat engine works with badlion client?

**Comment by ARandomSqueaker** [comment]
NessDiscord, I don't need u to test anymore. I can confirm that Badlion Client was the reason why Cheat Engine didn't work, but now I can't use Badlion Client. Cheat Engine, please make it so they are compatible.
http://prntscr.com/mx3mom

**Comment by ARandomSqueaker** [comment]
uhh discord doesnt open now.

**Comment by ARandomSqueaker** [comment]
oh and also cant redownload badlion client

**Comment by ARandomSqueaker** [comment]
nvm. im able to redownload badlion client, but i still cant open discord

**Comment by ARandomSqueaker** [comment]
badlion client works. loaded it up and its working fine. discord still isnt working though

**Comment by ARandomSqueaker** [comment]
fixed my discord. just redownlaoded

**Comment by OmarAhmed04** [comment]
Yeah uninstalling Badlion Client worked

**Comment by ARandomSqueaker** [comment]
yea, but discord still doesnt work

**Comment by ARandomSqueaker** [comment]
restarted pc and discord works

**Comment by ARandomSqueaker** [comment]
soo. when i do the badlion client update, it makes it so cheat engine doesnt open anymore.

**Comment by aguywhoisongithub** [comment]
I know this is late but i uninstalled badlion and tried everything (i couldnt find noenv.bat) help?

**Comment by cheat-engine** [comment]
Tried rebooting? (not shutdown and then back on)
