### ISSUE TITLE
Can't find frmsymboleventtakinglongunit.lrs file when compiling CheatEngine

### ISSUE THREAD

**Issue by jingj5** [cheat-engine/cheat-engine#535]
Compile Project, Mode: Release 64-Bit, Target: bin\cheatengine-x86_64.exe: Exit code 1, Errors: 1
frmsymboleventtakinglongunit.pas(61,4) Fatal: Cannot open include file "frmsymboleventtakinglongunit.lrs"

**Comment by cheat-engine** [comment]
try a build instead of compile
and add frmsymboleventtakinglongunit.pas to the project

**Comment by jingj5** [comment]
This error is present to frmsymboleventtakinglongunit.pas file, this file is already added  to the project.
this file include file "frmsymboleventtakinglongunit.lrs" can't find in the project.

**Comment by jingj5** [comment]
the complie dir, \Cheat Engine\lib\x86_64-win64, can't find this file frmsymboleventtakinglongunit.lrs.

**Comment by jingj5** [comment]
Thanks a lot, add frmsymboleventtakinglongunit.pas to the project, it's done. : )
