### ISSUE TITLE
Cant open v2

### ISSUE THREAD

**Issue by ARandomSqueaker** [cheat-engine/cheat-engine#539]
So I tried to open Cheat Engine and it didn't work, so I installed the latest version, and it still wouldn't open. I need help.
I ran it as admin, restarted my pc, and reinstalled. None of it worked.
Whenever i open it, nothing comes up/nothing happens. please help. btw i turned off all of my anti viruses

then somebody told me
Restart your system after turning off your AV's (actual restart, so not turn off and back on, windows 10 fakes that)

I tried that and it still doesnt work. please help.

**Comment by remizovm** [comment]
Hello, @ARandomSqueaker !

Please, don't duplicate your issues - it won't speed up anything. Instead, provide some details in your original issue - for example, the OS version, CPU model and so on. Thanks!
