### ISSUE TITLE
fidiv qword assembler/disassembler

### ISSUE THREAD

**Issue by mgrinzPlayer** [cheat-engine/cheat-engine#54]
fidiv qword ptr [address]
fidiv qword ptr [rax]

**Comment by cheat-engine** [comment]
my documentation says nothing about the existence of a qword ptr version of fidiv. Only dword ptr and word ptr.

But if you mean "fidiv word ptr [rax]" isn't being disassembled properly, yes, that is a bug

**Comment by mgrinzPlayer** [comment]
http://www.jaist.ac.jp/iscenter-new/mpc/altix/altixdata/opt/intel/vtune/doc/users_guide/mergedProjects/analyzer_ec/mergedProjects/reference_olh/mergedProjects/instructions/instruct32_hh/vc93.htm


last line in table says:
DE /6	**FIDIV** m16int	Divide ST(0) by **m64int** and store result in ST(0)


Hmm, m16int or m64int. A typo maybe.
