### ISSUE TITLE
CreateToolhelp32Snapshot detected 

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#540]
procedure GetProcessList(ProcessList: TStrings; NoPID: boolean=false; noProcessInfo: boolean=false);

SNAPHandle:=CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS,0);

CreateToolhelp32Snapshot handle? Is detected

Is it possible to print the list without using the API?

Should I chaged to the kernel? Are there any APIs that can be replaced?

**Comment by cheat-engine** [comment]
dbvm has a CR3 list, you could probably use that to fill a processlist (assuming you know how to get the PID from just memory)

Also, how does it detect it ? Does it have a hook in place somewhere? What happens when you remove that hook ?
And are you sure it's CreateToolhelp32Snapshot, and not when CE invades the process to get the icon ?

**Comment by kitty8904** [comment]
procedure TProcessWindow.RefreshList;
var
    i: integer;
    oldselectionindex: integer;
    oldselection: string;
    found: boolean;

begin
  processlist.Items.BeginUpdate;
  try
    oldselectionindex:=processlist.ItemIndex;

    if oldselectionindex<>-1 then
      oldselection:=processlist.Items[oldselectionIndex];

    case TabHeader.TabIndex of
      0:
      begin
        getwindowlist2(processlist.Items);
        miSkipSystemProcesses.enabled:=true;
      end;

      1:
      begin
        getprocesslist(processlist.items);

        miSkipSystemProcesses.enabled:=true;
      end;

      2:
      begin
        GetWindowList(processlist.Items, miShowInvisibleItems.Checked);
        miSkipSystemProcesses.enabled:=false;
        processlist.ItemIndex:=processlist.Items.Count-1;
      end;
    end;    

Process List Button Click -> Detect -> Run Cheat Engine Exit
case 0 = application  = getwindowlist2(processlist.Items);= detect
case 1 = processes  = getprocesslist(processlist.items);= detect
case 2 = windows = GetWindowList -> No Detect 

//SNAPHandle:=CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS,0);  
Process32First?
process32next?

Click the process list button to detect the handle or what

GetWindowList function does not detect(case2)

**Comment by kitty8904** [comment]
Target PID? handle? If you do not use CreateToolhelp32Snapshot, it will not be detected

CreateToolhelp32Snapshot The calling API is not detected if the process is a lsass, gamepid, winlogin.exe system, or an administrator PID

I wonder if there is an alternative way to CreateToolhelp32Snapshot

**Comment by cheat-engine** [comment]
perhaps the patchscanner here can be of use: https://forum.cheatengine.org/viewtopic.php?p=5746520#5746520

Attach to CE itself and then see it something has hooked any of the API's

**Comment by kitty8904** [comment]
Detection is in the kernel 

obprecallbacks handle create list check

1. Obtain access handle PID not gamepid, csrss, winlogin

2.If not the allowed PID, call ntterminateprocess to force terminate

3.Does the CreateToolhelp32Snapshot API also generate handles? Probably detected in the kernel when generating handles?

4.Because it is processed by the kernel, it can be bypassed by deleting the kernel routine

5.I have solved it, but I was wondering about the API method not being detected

**Comment by cheat-engine** [comment]
check out the privatebuild typoedef in newkernelhandler for some ways to deal with that as well

**Comment by kitty8904** [comment]
google search maybe anti cheat callbacks source

OB_PREOP_CALLBACK_STATUS PreCallback(PVOID RegistrationContext, POB_PRE_OPERATION_INFORMATION OperationInformation)
{
	UNREFERENCED_PARAMETER(RegistrationContext);
 
	PEPROCESS OpenedProcess = (PEPROCESS)OperationInformation->Object,
		CurrentProcess = PsGetCurrentProcess();
 
	PsLookupProcessByProcessId(ProtectedProcess, &ProtectedProcessProcess); // Getting the PEPROCESS using the PID 
	PsLookupProcessByProcessId(Lsass, &LsassProcess); // Getting the PEPROCESS using the PID 
	PsLookupProcessByProcessId(Csrss1, &Csrss1Process); // Getting the PEPROCESS using the PID 
	PsLookupProcessByProcessId(Csrss2, &Csrss2Process); // Getting the PEPROCESS using the PID 
 
 
	if (OpenedProcess == Csrss1Process) // Making sure to not strip csrss's Handle, will cause BSOD
		return OB_PREOP_SUCCESS;
 
	if (OpenedProcess == Csrss2Process) // Making sure to not strip csrss's Handle, will cause BSOD
		return OB_PREOP_SUCCESS;
 
	if (OpenedProcess == CurrentProcess) // make sure the driver isnt getting stripped ( even though we have a second check )
		return OB_PREOP_SUCCESS;
 
	if (OpenedProcess == ProtectedProcess) // Making sure that the game can open a process handle to itself
		return OB_PREOP_SUCCESS;
 
	if (OperationInformation->KernelHandle) // allow drivers to get a handle
		return OB_PREOP_SUCCESS;
 
 
	// PsGetProcessId((PEPROCESS)OperationInformation->Object) equals to the created handle's PID, so if the created Handle equals to the protected process's PID, strip
	if (PsGetProcessId((PEPROCESS)OperationInformation->Object) == ProtectedProcess)
	{
 
		if (OperationInformation->Operation == OB_OPERATION_HANDLE_CREATE) // striping handle 
		{
			OperationInformation->Parameters->CreateHandleInformation.DesiredAccess = (SYNCHRONIZE | PROCESS_QUERY_LIMITED_INFORMATION);
ntterminateprocess call?!!
		}
		else
		{
			OperationInformation->Parameters->DuplicateHandleInformation.DesiredAccess = (SYNCHRONIZE | PROCESS_QUERY_LIMITED_INFORMATION);
		}
                ntterminateprocess call?!!
		return OB_PREOP_SUCCESS;
	}
}

**Comment by kitty8904** [comment]
pivatebuild knows it does not create a handle but it does not create a read write thread if it does not have a handle
