### ISSUE TITLE
pointer is not fixing

### ISSUE THREAD

**Issue by june9713** [cheat-engine/cheat-engine#542]
[](https://www.youtube.com/watch?v=knmQBsVKBHs&feature=youtu.be)
https://www.youtube.com/watch?v=knmQBsVKBHs&feature=youtu.be

I'm currenty stuck in Tutorial#6 pointer.

Please see my youtube video.

I found address pointer has saved.

So I fix that address by "activate check"

But pointer is still changing.

I ran Cheat Engine as Administrator.

My Laptop and 2 desktop has same situation.

I reinstalled cheat engine. 6.8 , 6.7 , 6.6 , 6.5 m 6.4 

but still has same problem.

Please help me to solve this. 

Thansk!

**Comment by cheat-engine** [comment]
Why do you do a hexadecimal scan for 017ad530 ?
You first need to find out what accesses it so you know the offset you have to subtract from that

**Comment by june9713** [comment]
> Why do you do a hexadecimal scan for 017ad530 ?
> You first need to find out what accesses it so you know the offset you have to subtract from that

Oh, you are right! I'v got it!  Thanks!!!
