### ISSUE TITLE
dbvm find what access kernel address

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#543]
<img width="923" alt="77" src="https://user-images.githubusercontent.com/18622105/53147857-29b82a00-35ec-11e9-9b78-aead00426a90.png">

<img width="234" alt="777" src="https://user-images.githubusercontent.com/18622105/53148137-135e9e00-35ed-11e9-8ca4-d178a3d25b70.png">

dbvm find what access kernel address

dbvm 11 -> kernel address dbvm what access -> Result!

dbvm 12 -> kernel address dbvm what access -> Result Fail!

Debugging kernel addresses with DBVM12 will not get access values
(DBVM11 -> OK , DBVM12 = NO)

Using DBVM when debugging kernel addresses is convenient but does not work with DBVM12

Picture is DBVM11 DBVM12 does not show result

**Comment by kitty8904** [comment]
[vmdisk.zip](https://github.com/cheat-engine/cheat-engine/files/2887978/vmdisk.zip)

vmdisk11(6.8.1)-> Kernel address Access -> Result OK

vmdisk11(6.8.3)-> Kernel address Access -> No Result 

vmdisk12(6.8.3)-> Kernel address Access -> No Result

What is the difference? I do not know where the source is

**Comment by kitty8904** [comment]
vmdisk is not a problem?

vmware test cheat engine 6.8.2 -> kernel address debug result ok

vmware test cheat engine 6.8.3 -> kernel address debug result fail

**Comment by kitty8904** [comment]
<img width="903" alt="6 8 2" src="https://user-images.githubusercontent.com/18622105/53149890-6f77f100-35f2-11e9-943a-5a20f94bc1a1.png">
<img width="908" alt="6 8 3" src="https://user-images.githubusercontent.com/18622105/53149892-6f77f100-35f2-11e9-8658-265bead38494.png">

6.8.2 -> Result OK

6.8.3 -> Result Fail

**Comment by cheat-engine** [comment]
Are you sure that the code that accesses that address has actually been executed ?

**Comment by kitty8904** [comment]
The code that you access actually executes

The uploaded file does not work

The test code is the kernel code that is read when you use the wmic command

**Comment by kitty8904** [comment]
[KMDFDriver.zip](https://github.com/cheat-engine/cheat-engine/files/2891459/KMDFDriver.zip)

sample file

DevicePointer::fffffa806150a6e0

<img width="946" alt="test" src="https://user-images.githubusercontent.com/18622105/53204624-6842f880-366f-11e9-9791-320ee0da11cc.png">

wmic get diskdrive

result ok-> 0x60 found code

result fail -> not debug address

windows7 x64 vmware

vmware vmx add disk.EnableUUID="true" to your VMware .vmx file to enable

**Comment by kitty8904** [comment]
<img width="812" alt="bug" src="https://user-images.githubusercontent.com/18622105/53240702-c1983f80-36e2-11e9-8c74-b211853f9cfc.png">

DBVM debug seems to not work at all User mode address does not read breakpoint
