### ISSUE TITLE
Failed install CE 6.8.3 with dealing "Install Additional Software"

### ISSUE THREAD

**Issue by Neutron3529** [cheat-engine/cheat-engine#544]
I know it is SO STRANGE but I have no idea how to deal with such questions:
While installing, I click like this:
![default](https://user-images.githubusercontent.com/26130174/53180066-dbc51580-362f-11e9-9605-837a9466c160.png)
this
![default](https://user-images.githubusercontent.com/26130174/53180083-e7184100-362f-11e9-8ea2-442cc3200110.png)
this
![default](https://user-images.githubusercontent.com/26130174/53180129-fb5c3e00-362f-11e9-84b2-efb57a56a5e7.png)
and this
![default](https://user-images.githubusercontent.com/26130174/53180163-08792d00-3630-11e9-9aea-17ed5ab3fbfa.png)
after such selections I got a very strange status:
![default](https://user-images.githubusercontent.com/26130174/53180339-5a21b780-3630-11e9-9736-eda3a31e98fb.png)

Here, click `Next` button does not work, so I could not goto next page.

**Comment by cheat-engine** [comment]
Have you tried waiting 5 minutes ?

**Comment by Neutron3529** [comment]
Wait for 10+ hours.
Then click for 1 minute
neither works.

Maybe there are something wrong with the internet connection. 
maybe it is the Great FireWall that broken such connection

**Comment by Neutron3529** [comment]
> 
> 
> Have you tried waiting 5 minutes ?

Could you please provide another .zip package?
I do not even know which website that would provides additional software. It is really hard for me to install the latest version of cheat engine.
Thanks.
