### ISSUE TITLE
no handle 32bit or 64bit check

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#545]
<img width="1128" alt="777" src="https://user-images.githubusercontent.com/18622105/53285458-09cb6680-37a4-11e9-9c3c-6799031af2e2.png">

private build mode no handle options

Disassembly output mode bug

target process 64 bit select -> Recognized as 32-bit

When there is no handle, the assembly recognition or modification is 32 bits

I would like to make the selected process recognized as 64-bit without a handle so that I can view and modify it to 64-bit

**Comment by cheat-engine** [comment]
without a handle it won't be able to detect that, but you can always use lua to specify it

```
setPointerSize(8)
setAssemblerMode(1)
```
