### ISSUE TITLE
DBVM Find What access No Debug 6.8.3

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#547]
<img width="998" alt="dbvm" src="https://user-images.githubusercontent.com/18622105/53286838-a0ede980-37b7-11e9-87d8-82e633e9a49e.png">
[release.zip](https://github.com/cheat-engine/cheat-engine/files/2896822/release.zip)

vmdisk new compile 2019-02-22

cheat engine 6.8.3 2019-02-23

dbk64.sys 2019-02-23

Compiled to all latest versions

DBVM access read-write debugging does not work 6.8.3

In 6.8.2, what works normally

**Comment by cheat-engine** [comment]
and 6.8.2 with that dbvm version works fine ?

**Comment by kitty8904** [comment]
<img width="1097" alt="dbdb" src="https://user-images.githubusercontent.com/18622105/53287744-f16b4400-37c3-11e9-9de4-af888139c29b.png">

[CheatEngine682_MissingSetup_.zip](https://github.com/cheat-engine/cheat-engine/files/2896887/CheatEngine682_MissingSetup_.zip)

6.8.2 Version Work

Real Hareware Test win10 1809(redstone5)

(No Vmware)

**Comment by cheat-engine** [comment]
so 6.8.2 with dbvm 12 (so not the one in CheatEngine682_MissingSetup) works fine ?

**Comment by kitty8904** [comment]
<img width="1089" alt="awaw" src="https://user-images.githubusercontent.com/18622105/53288014-e2d25c00-37c6-11e9-9bf2-e0a20d80c3b1.png">

6.8.2 + DBVM 11 = Work
6.8.3 + DBVM 12 = No Work
6.8.3 + DBVM 12 = No Work

**Comment by cheat-engine** [comment]
in vmeventhandler.c in function handleVMEvent ( https://github.com/cheat-engine/cheat-engine/blob/5765bbfa409d9cf4b752d186c3adec98aeebfbc4/dbvm/vmm/vmeventhandler.c#L3637  )
change this code change
```
  if ((hasVPIDSupport) && (currentcpuinfo->eptUpdated==1))
  {
	  INVEPTDESCRIPTOR eptd;

	  eptd.Zero=0;
	  eptd.EPTPointer=currentcpuinfo->EPTPML4;
	  currentcpuinfo->eptUpdated=0;
	  _invept(2, &eptd);
  }
```
to
```
  if (currentcpuinfo->eptUpdated==1)
  {
	  INVEPTDESCRIPTOR eptd;

	  eptd.Zero=0;
	  eptd.EPTPointer=currentcpuinfo->EPTPML4;
	  currentcpuinfo->eptUpdated=0;
	  _invept(2, &eptd);
          _invept(1, &eptd);

	  {
		  INVVPIDDESCRIPTOR vpidd;
		  vpidd.zero=0;
		  vpidd.LinearAddress=0;
		  vpidd.VPID=1;

		  _invvpid(2, &vpidd);
                  _invvpid(1, &vpidd);
                  _invvpid(0, &vpidd);
	  }
  }
```

and see if it works better

**Comment by kitty8904** [comment]
#ifdef STATISTICS
  if (exit_reason<=55)
    currentcpuinfo->eventcounter[exit_reason]++;
#endif

  if (currentcpuinfo->eptUpdated==1)
  {
	  INVEPTDESCRIPTOR eptd;

	  eptd.Zero=0;
	  eptd.EPTPointer=currentcpuinfo->EPTPML4;
	  currentcpuinfo->eptUpdated=0;
	  _invept(2, &eptd);
          _invept(1, &eptd);

	  {
		  INVVPIDDESCRIPTOR vpidd;
		  vpidd.zero=0;
		  vpidd.LinearAddress=0;
		  vpidd.VPID=1;

		  _invvpid(2, &vpidd);
                  _invvpid(1, &vpidd);
                  _invvpid(0, &vpidd);
	  }
  }

  
[vmdisk.zip](https://github.com/cheat-engine/cheat-engine/files/2897338/vmdisk.zip)

make clean cdimage compile

It does not work

Dark Byte Does your computer work properly?

What I'm going to do today is to download the source from version 6.8.2 to version 6.8.3 and compile it

I do not know where the error is ... 

So I have to look at all the changed sources

**Comment by cheat-engine** [comment]
On my tests, like the tutorial of CE step 2, write access and read/write access both find kernelmode and usermode access

**Comment by kitty8904** [comment]
https://github.com/cheat-engine/cheat-engine/tree/0d82bb7dfad5bace90605e466890da2cc595ced3

6.8.3 + 0d82bb7dfad5bace90605e466890da2cc595ced3 DBVM source -> Work

There seems to be a problem with the update after this

0d82bb7dfad5bace90605e466890da2cc595ced3 Outputs normally when the compile image is loaded

**Comment by cheat-engine** [comment]
change
`if (currentcpuinfo->eptUpdated==1)`
to
`if (1)`

and see if that has an effect

**Comment by kitty8904** [comment]
<img width="736" alt="888" src="https://user-images.githubusercontent.com/18622105/53292845-b2adac00-380c-11e9-969e-7f59e74577b4.png">

Good Work

if (1) -> Debug Result OK

6.8.3+DBVM12

**Comment by cheat-engine** [comment]
No, it just means that the cache flush isn't happening for you when it should
this patch basically negates the cache speed gain from vpid support by flushing the cache every single time

run this lua code and post the results  (It gets the flush capabilities of your cpu)
`print(string.format("%x", dbk_readMSR(0x48c)))`

**Comment by kitty8904** [comment]
<img width="382" alt="888" src="https://user-images.githubusercontent.com/18622105/53292912-d32a3600-380d-11e9-90c3-c2545756fbc5.png">

windows7 Vmware
print(string.format("%x", dbk_readMSR(0x48c)))

f0106714141 

Windows 10 No Vmware
print(string.format("%x", dbk_readMSR(0x48c)))

f0106734141

**Comment by kitty8904** [comment]
<img width="645" alt="888" src="https://user-images.githubusercontent.com/18622105/53292963-cfe37a00-380e-11e9-94ec-e6e57aa4dce5.png">

remove all
{
             _invvpid(2, &vpidd);
              _invvpid(1, &vpidd);
              _invvpid(0, &vpidd);
}

remove invvpid -> Debug Result OK

Deleting _invvpid will still output debug result

**Comment by cheat-engine** [comment]
I've updated a new build of dbvm which adds some extra cache flushing when the physical memory protection is changed 
Perhaps it works better, if not, I'll try some more aggressive flushing
[vmdisk.zip](https://github.com/cheat-engine/cheat-engine/files/2897427/vmdisk.zip)

**Comment by kitty8904** [comment]
<img width="662" alt="888" src="https://user-images.githubusercontent.com/18622105/53293350-b42fa200-3815-11e9-93b2-e6bd74bf4608.png">

The latest build vmdisk image works

Thank you for fixing the bug
