### ISSUE TITLE
After some use I can't open heavy tables

### ISSUE THREAD

**Issue by Rogus** [cheat-engine/cheat-engine#549]
hey @cheat-engine After using CE tables with 6.8.3 it takes ages to open a single yet compiled table for Tales of  Vesperia Definitive Edition and it says not responding and takes pretty much time to recover from that white screen of not responding and also on the confirmation of keep current address tab yes or  no it also says this not responding so what should I do?

**Comment by cheat-engine** [comment]
check with help->check for new version if you're on the latest 6.8.3

**Comment by Rogus** [comment]
Here it's the 6.8.3 version on the website it says February 7 2019 and in the print screen with snipping tool says 11/02/2019 or February 11 2019
![ce same version different dates](https://user-images.githubusercontent.com/39033733/53441928-b4cb6280-39e6-11e9-843a-b209aa799d9f.PNG)

**Comment by cheat-engine** [comment]
Get the new versionn it fixes the slow load

**Comment by Rogus** [comment]
Well it's the same at least visually but it fixes the slow load. Can you update the website? Since some people can't see the differences between 6.8.3 and 6.8.3.1.

**Comment by Rogus** [comment]
Thanks for the big help @cheat-engine .
