### ISSUE TITLE
Autoattach does not disable Auto Assemble scripts

### ISSUE THREAD

**Issue by AGlezB** [cheat-engine/cheat-engine#550]
### CE Version
6.8.3

### Description
When set to ```Automatically attach to processes``` and ```Even autoattach when another process has already been selected``` is checked CE does not disable scripts after attaching.

### Steps to reproduce
1. Add ```calc.exe``` to to autoattach and check ```Even...```.
2. Open ```calc.exe``` and create any script with the ```[ENABLE]``` and ```[DISABLE]``` framework code.
3. Enable the script.
4. Close and reopen  ```calc.exe```.

### Result
Script stays enabled.

### Expected result
Script is disabled or at least CE asks the user to ```disable the script without executing the disable part``` just like when the process is attached manually.

### Proposed solution
Add a setting auto autodisable scripts with options ```[Yes, No, Ask]``` and use it also when attaching manually.

**Comment by cheat-engine** [comment]
autoattach now disables entries
