### ISSUE TITLE
breakpoint list loop

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#551]
<img width="778" alt="77" src="https://user-images.githubusercontent.com/18622105/53423578-f4b13a80-3a24-11e9-9815-ca5ffd37620e.png">

dbvm break point list infinite?

disassembler int3 hook view?(dbvm ept view)

procedure TfrmModifyRegisters.Button1Click(Sender: TObject);  

pa:=strtoint64(edtPA.text); -> pa:=strtoint64('$'+edtPA.text); 

'$' <- add

**Comment by cheat-engine** [comment]
yeah, I haven't tested that code so it's likely to have some bugs.
Should work slightly better now (still untested)

**Comment by kitty8904** [comment]
<img width="337" alt="88" src="https://user-images.githubusercontent.com/18622105/53426006-828f2480-3a29-11e9-96af-2f4d3832490b.png">

breakpoint list delete -> green color(ept hook) no delete

Font color remains green even if breakpoint list is deleted

**Comment by cheat-engine** [comment]
that's because changeregonbp is 2 things, memorycloak and a BP
Deleting the BP doesn't disable the cloak (i'll add a function for that later)
