### ISSUE TITLE
Move driver address

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#552]
<img width="982" alt="ff" src="https://user-images.githubusercontent.com/18622105/53429466-149a2b80-3a30-11e9-875f-a87121b184b9.png">

1.double click -> memory view move

2.go to address kernel driver name&symbol move

3.dbk64.sys kernel symbol drivername & module name view

4.autoassembler driver name & symbol read

dbk64.sys:
ret

**Comment by cheat-engine** [comment]
check view->show kernel symbols

**Comment by kitty8904** [comment]
thank you

1.Driver name Start address Address Double click No moved?

2.Driver module name goto address No?
ex) ntoskrnl_pssuspendprocess

3.) thank you(Kernel symbol view available Not displayed in the past)

4. Can the autoassembler read the kernel symbol module or driver name?

ntoskrnl_pssuspendprocess:
ret

dbk64.sys:
ret

**Comment by cheat-engine** [comment]
2:
if you double click an symbol there you will go to it

4: if kernelsymbol is on, yes ntoskrnl.PsSuspendProcess

you can use lua to force that on (gui access)

or else you can always use this code here https://forum.cheatengine.org/viewtopic.php?t=609565

**Comment by kitty8904** [comment]
<img width="302" alt="99" src="https://user-images.githubusercontent.com/18622105/53486359-d94d3a80-3acb-11e9-8bab-0e7c81e4f52f.png">

--4--
yeah kernel symbol on -> ntoskrnl.PsSuspendProcess -> possible

but no symbol driver name move possible?

go to address: ntoskrnl.PsSuspendProcess autoassembler,goto address possible

go to address :dbk64.sys ntoskrnl.exe srv.sys 

When the kernel symbol is ON, the internal extended address can be moved or read

Can not find address by driver name
