### ISSUE TITLE
private build enumerate dll list  no possible

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#557]
<img width="631" alt="zzz" src="https://user-images.githubusercontent.com/18622105/53685000-1c234280-3d58-11e9-928e-90a1b9dc4d94.png">

<img width="562" alt="999" src="https://user-images.githubusercontent.com/18622105/53685057-f77b9a80-3d58-11e9-936c-396e8aea303b.png">

private build

no handle option check on

cheat engine x64 bit version
windows7 enumerate dll list x86 x64  ->possible

windows10 enumerate dll list x64  -> possible & no possible ??
windows10 enumerate dll list x86  ->no possible

kernel peb & ntqueryinformation? fix?

nohandle windwos 7 x86x64 process name possible

nohandle windows 10 x32 bit process name no possible
nohandle windows 10 x64 bit process name possible & no possible ??

windows 7 -> possible

windows 10 -> no possible

**Comment by kitty8904** [comment]
Does 32-bit process force module information to be readable?

setPointerSize(8)
setAssemblerMode(1)

Module list option does not change even if you force two commands

**Comment by kitty8904** [comment]
func:=GetProcAddress(NTDLLHandle,'NtOpenProcess');   //NtOpenProcess
generateAPIHookScript(nthookscript,IntToHex(ptruint(func),8),IntToHex(ptruint(@NOP),8),IntToHex(ptruint(@@oldNtOpenProcess),8),'0',true);

Unlocking this function hook will get 32 bit module information

But then you can not get process information protected by obcallbacks

Size and PID seem to be strange when hooking NOP?


1.If you do not hook NOP, you can get 32-bit 64-bit module information

2.However, if you do not hook, you will not get protected process module information

3.If you do NOP hooking, can not get module information if you 32-bit target process

If you look at the debug log, you will continue to call NOP(openprocess) somewhere?

I do not know what to do. I do not know how to fix it.

**Comment by kitty8904** [comment]
![bb](https://user-images.githubusercontent.com/18622105/53692516-d0fb4500-3dd4-11e9-9550-a0b3faf18a5b.gif)

gif image

**Comment by cheat-engine** [comment]
I don't know.  Perhaps the ntqueryinformation hook needs some adjustments so it tells CE it's 32-bit Or some other API needs to be updated to deal with the fake handle.  Try figuring out the path normally taken by windows when querying a 32-bit process modules

**Comment by kitty8904** [comment]
my kernel iswow64 patch but failed

const IOCTL_CE_IsWow64Check           = (IOCTL_UNKNOWN_BASE shl 16) or ($0862 shl 2) or (METHOD_BUFFERED ) or (FILE_RW_ACCESS shl 14);

function KernelIsWow64Check(var iswow:boolean):boolean;
var
input: record
pid: DWORD;
end;

var
output: record
   ResultProtect :DWORD;
end;

KernelWow64Check : DWORD = 0;

x,res,cc:dword;

begin
   input.pid:=globalPID;

   if hdevice<>INVALID_HANDLE_VALUE then
   begin
    cc:=IOCTL_CE_IsWow64Check;
    if deviceiocontrol(hdevice,cc,@input,sizeof(input),@output,4,x,nil) then
    begin
     //showmessage(inttostr(output.ResultProtect));
     KernelWow64Check:=output.ResultProtect;

     if KernelWow64Check = 0 then
       begin
       //processhandler.overridePointerSize(4);
       //processhandler.is64Bit:=false;
       iswow:=false;
       result:=false;
       end
       else
       begin
       //processhandler.overridePointerSize(8);
       //processhandler.is64Bit:=true;
       iswow:=true;
       result:=true;
       end;
     end;
   end;
end;


unit ProcessHandlerUnit;  

procedure TProcessHandler.setProcessHandle(processhandle: THandle); 
var
 iswow :boolean; 
...

fSystemArchitecture:=archX86;  
 KernelIsWow64Check(iswow);
 setIs64Bit(iswow);
//setIs64Bit(newkernelhandler.Is64BitProcess(fProcessHandle));

///kernel///

			case IOCTL_CE_IsWow64Check:
				{
					struct
					{
						ULONG ProcessID;
					} *InputBuf = Irp->AssociatedIrp.SystemBuffer;

					struct
					{
						ULONG ResultIsWow64;
					} *OutputBuf = Irp->AssociatedIrp.SystemBuffer;

					PEPROCESS selectedprocess = NULL;

					DWORD PID = InputBuf->ProcessID;

					ULONG_PTR iswow64 = 0;

					DbgPrint("ProcessID: %llx\n", PID);

					__try
					{
						if (PsLookupProcessByProcessId((PVOID)(UINT_PTR)(PID), &selectedprocess) == STATUS_SUCCESS)
						{
							KeAttachProcess((PVOID)selectedprocess); //local process is much more fun!!!!

							if (ZwQueryInformationProcess(ZwCurrentProcess(), ProcessWow64Information, &iswow64, sizeof(iswow64), NULL) == STATUS_SUCCESS)
							{
								if (iswow64)
								{
									DbgPrint("WOW64 32Bit Process");
									OutputBuf->ResultIsWow64 = (DWORD)0;
									
								}
								else
								{
									DbgPrint("WOW64 64Bit Process");
									OutputBuf->ResultIsWow64 = (DWORD)1;
							STATUS_SUCCESS); 
								}
							}
						}

					}
					__finally
					{
						KeDetachProcess();
					}

					if (selectedprocess)
					{
						ObDereferenceObject(selectedprocess);
					}

					//ZwTerminateProcess
				
					ntStatus = STATUS_SUCCESS;

					break;
}


I made the kernel,

I do not know where to divide module information into 32 bits and 64 bits

I do not know the size or boolean that I need to fix in the cheat engine.

**Comment by kitty8904** [comment]
The following two options work normally

I do not know where to compare module information

setPointerSize(8)
setAssemblerMode(1)

**Comment by cheat-engine** [comment]
Have you also hooked kernelbase.iswow64process to execute your kernel version? (Or whatever CreateToolhelp32Snapshot uses to figure out if the target is 32-bit)

**Comment by kitty8904** [comment]
type TIsWow64Process=function (processhandle: THandle; var isWow: BOOL): BOOL; stdcall;

if not assigned(oldIsWow64Process) then
begin
      nthookscript.clear;
      Kernel:=LoadLibrary('KERNELBASE.dll');
      func:=GetProcAddress(Kernel,'IsWow64Process');
      generateAPIHookScript(nthookscript,IntToHex(ptruint(func),8),IntToHex(ptruint(@KernelIsWow64Check),8),IntToHex(ptruint(@@oldIsWow64Process),8),'0',true);
      autoassemble(nthookscript, false, true, false, true);
end; 

i did it this way, but it failed.

I do not know how to fix

**Comment by cheat-engine** [comment]
open the CE memory and go to IsWow64Process to confirm your hook is there, also, it's possible it uses a different API completely to figure out if it's 64-bit. Or it's even unrelated

**Comment by kitty8904** [comment]
<img width="1128" alt="9889" src="https://user-images.githubusercontent.com/18622105/53693241-fd1cc300-3de0-11e9-9eaf-546b8148bf93.png">

api hooking yes, but I do not know

I do not have a handle, so I think I wrote something strangely

function KernelIsWow64Check(processhandle: THandle; var iswow:BOOL):BOOL;
var
input: record
pid: DWORD;
end;

var
output: record
   ResultProtect :DWORD;
end;

KernelWow64Check : DWORD = 0;

x,res,cc:dword;

begin
   input.pid:=globalPID;

   if hdevice<>INVALID_HANDLE_VALUE then
   begin
    cc:=IOCTL_CE_IsWow64Check;
    if deviceiocontrol(hdevice,cc,@input,sizeof(input),@output,4,x,nil) then
    begin
     //showmessage(inttostr(output.ResultProtect));
     KernelWow64Check:=output.ResultProtect;

     if KernelWow64Check = 0 then
       begin
       //processhandler.overridePointerSize(4);
       //processhandler.is64Bit:=false;
       iswow:=false;
       //result:=false;
       result:=oldIsWow64Process(processhandle,iswow);
       end
       else
       begin
       //processhandler.overridePointerSize(8);
       //processhandler.is64Bit:=true;
       iswow:=true;
       //result:=true;
       result:=oldIsWow64Process(processhandle,iswow);
       end;
     end;
   end;
end;

**Comment by kitty8904** [comment]
Is it an issue not related to wow64? I do not know the solution

**Comment by cheat-engine** [comment]
In lazarus place a breakpoint before the call to createtoolhelp32snapshot (in symbolhandler.pas) and when hit set a breakpoint at your implementation of iswow64process. 
See if it's even called.
And if it is called, make sure it returns true

If it's not called, it may be using a different API.  Perhaps you can try stepping through the call of createtoolhelp32snapshot itself (using CE or another debugger) and see if you can figure out how it gets the modulelist and why it fails

**Comment by kitty8904** [comment]
I do not know how to fix it

Sorry

I've seen and analyzed the source for two days, but it's not enough.

Please take a look at the next time you have time

I do not know what the API is or what the error is

Problems that can not be solved with my IQ

Stupid

**Comment by cheat-engine** [comment]
did you fix your iswow64 implementation ? because the one you posted returns false if 32 bit or calls the original function overwriting your true statement

**Comment by kitty8904** [comment]
if not alreadyInTheList then
   begin
  showmessage('222222222222222222222');
 if newmodulelistpos+1>=length(newmodulelist) then 

If it is a 32 bit target, it will not go down under alreadyInTheList function

**Comment by kitty8904** [comment]
function KernelIsWow64Check(processhandle: THandle; var iswow:BOOL):BOOL;
var
input: record
pid: DWORD;
end;

var
output: record
   ResultProtect :BOOL;
end;

KernelWow64Check : BOOL;//: DWORD = 0;

x,res,cc:dword;

begin
   input.pid:=globalPID;
   //showmessage(inttostr(processhandle));

   if hdevice<>INVALID_HANDLE_VALUE then
   begin
    cc:=IOCTL_CE_IsWow64Check;
    if deviceiocontrol(hdevice,cc,@input,sizeof(input),@output,4,x,nil) then
    begin
     //showmessage(inttostr(output.ResultProtect));
     KernelWow64Check:=output.ResultProtect;

     if KernelWow64Check then
       begin
       showmessage('32bit');
       //processhandler.overridePointerSize(4);
       //processhandler.is64Bit:=false;
       iswow:=true;
       //result:=false;
       result:=oldIsWow64Process(getcurrentprocess,iswow);
       end
       else
       begin
       showmessage('64bit');
       //processhandler.overridePointerSize(8);
       //processhandler.is64Bit:=true;
       iswow:=false;
       //result:=true;
       result:=oldIsWow64Process(getcurrentprocess,iswow);
       end;
     end;
   end;
end;


///////////////////////////////////////////////////////////////////////

oldIsWow64Process(getcurrentprocess,iswow);

oldIsWow64Process(????nohandle????,iswow)

1 return on the coding has been modified

I do not have a handle-> what the handle input?

**Comment by cheat-engine** [comment]
IsWow64Process returns true if the function is implemented in the system , the processhandle is valid, and the address of the iswow variable is valid
(So best always return true)

In nohandle mode, the handle given is a fake handle, that needs to be converted to a structure you can use to get the PID
Look at DBK_NtReadVirtualMemory .
```
  handlemapMREW.Beginread;
  validhandle:=handlemap.GetData(ProcessHandle, l);
  handlemapMREW.Endread;

  if validhandle then
  begin   
```   
It uses that code to convert a fake handle to a PID and than passes it off to the kernelmode driver

you can do that for your KernelIsWow64Check function as well.


------
Anyhow, for the time being, this code forces everything to show as 32-bit so you can at least test if that's your problem (it WILL break 64-bit targets)
[code]
function KernelIsWow64Check(processhandle: THandle; var iswow:BOOL):BOOL;
begin
  result:=true;
  iswow:=processhandle<>-1;
end;
[/code]

**Comment by kitty8904** [comment]
function KernelIsWow64Check(processhandle: THandle; var iswow:BOOL):BOOL;
begin
  result:=true;
  iswow:=processhandle<>-1;
end;

symbolhandler,pas??
function TSymhandler.loadmodulelist: boolean; <-??
begin
...
end

 it will be recognized as 32bit unconditionally, but the module list will not be obtained

Problem with symbolhandler.pas?

**Comment by cheat-engine** [comment]
could be it's using IsWow64Process2

**Comment by kitty8904** [comment]
> could be it's using IsWow64Process2

IsWow64Process2 breakpoint -> No access break point

IsWow64Process breakpoint and command
reinitializeSymbolhandler(true)  -> no break point
reinitializeSelfSymbolhandler(true)->no break point

////////////////////////////////////////////
![fff](https://user-images.githubusercontent.com/18622105/53695618-22212e00-3e01-11e9-9962-9f1613efbaea.gif)


1.handle uncheck 

2.handle check 

3.nop hook disable


Module information test photos in real time

Made a 32 bit target

The cause is hardly known except this one.

NOP HOOKING? I do not know why

**Comment by kitty8904** [comment]
<img width="853" alt="1" src="https://user-images.githubusercontent.com/18622105/53699725-cb324d80-3e2e-11e9-81f3-dff4a92a866d.png">
<img width="840" alt="2" src="https://user-images.githubusercontent.com/18622105/53699726-cb324d80-3e2e-11e9-9966-b5b6070203ab.png">

ntopenproess hooking 
mov rax , 00000000C00000E5 -> x32 bit process memory module view x
mov rax, 0 -> x32 & x64 bit process memory module view ok

ntopenprocess Something happens when I hook up the stack or return value. I know what I need to fix is reversing, but not at source.

I need to modify it in the source code. I do not know where it is.
