### ISSUE TITLE
Disassembler exception

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#558]
![image](https://user-images.githubusercontent.com/14368203/53685136-daba7500-3d0e-11e9-846f-7bede166d989.png)

![image](https://user-images.githubusercontent.com/14368203/53685141-e443dd00-3d0e-11e9-90ed-5c0104782e89.png)

**Comment by cheat-engine** [comment]
thanks i'll check this out.
Also, is this a selfcompiled CE or a release? Running under a debugger ?(80000003 is a breakpoint got hit)  If you do help->check latest version, does it say you're up to date ?

**Comment by Symbai** [comment]
Official 6.8.3, happened while debugging a .NET game (not unity). There were also plenty of "Waiting for symbol loader" windows popping up after the BP got hit, which was very annoying but not part of this bug report. I think the symbol handler changes aren't a good idea for these games.

**Comment by Symbai** [comment]
I can reproduce this on a different game. It doesn't matter which bytes there are, it rather seems that symbolhandler changes you introduce broke debugging a .NET game completely. @cheat-engine You need to test this on a .NET game. Steps:

1. Launch a .NET game
2. Launch CE and attach, open memory viewer
3. Enjoy "symbolhandler lookup taking long" message, after 5 minutes or earlier click on "Cancel". It never really finishes
4. Go to a .NET function and attach debugger in any way. Set BP or right click and "Find out what" on an instruction
5. Enjoy more "symbolhandler lookup taking long" messages, click on Cancel again
6. Disassembler crashed.

![image](https://user-images.githubusercontent.com/14368203/53736790-a962b600-3e82-11e9-966c-53225075afd2.png)

![image](https://user-images.githubusercontent.com/14368203/53736950-0eb6a700-3e83-11e9-9cc9-aadf48bfeaaf.png)

**Comment by cheat-engine** [comment]
it's an issue with the dialog.
anyhow, what happens when you clock ok?

**Comment by Symbai** [comment]
The dialog closes and I can continue using CE. But the problem comes back on next breakpoint hit or whenever the debugger makes the symbol handler to refresh I dont know what happens internally.
