### ISSUE TITLE
About  "Code Filter"

### ISSUE THREAD

**Issue by lenct** [cheat-engine/cheat-engine#559]
![tim 20190303135859](https://user-images.githubusercontent.com/44138520/53691624-b1f0b900-3dbc-11e9-8624-3d1173150c5d.png)
During filtering, a click on the button "Has been executed" causes the target process to crash and become unrecoverable

**Comment by cheat-engine** [comment]
the bug is that you must first click start.  Those buttons should not start off as enabled

**Comment by lenct** [comment]
All work is done normally, by filtering out code that is not executed, and then filtering out code that is already executed, the target process gets stuck

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Dark Byte <notifications@github.com>
发送时间: Sunday, March 3, 2019 4:16:44 PM
收件人: cheat-engine/cheat-engine
抄送: lenct; Author
主题: Re: [cheat-engine/cheat-engine] About "Code Filter" (#559)


the bug is that you must first click start. Those buttons should not start off as enabled

―

**Comment by lenct** [comment]
![tim 20190303162930](https://user-images.githubusercontent.com/44138520/53692836-90e69300-3dd1-11e9-99dd-99a0e8fbcee4.png)
Upon execution of the button "has been executed", the target process is executed

**Comment by cheat-engine** [comment]
attach the debugger to it
then go to "debug->break on unexpected exceptions and set that to always

then try this.  Perhaps the crash can give an idea where or why it happens (Perhaps the addresslist itself has an address at a wrong location)

**Comment by lenct** [comment]
![tim 20190303164201](https://user-images.githubusercontent.com/44138520/53692948-6bf31f80-3dd3-11e9-9dcf-4d8f9b6e8fe2.png)
The problem was found. The filter removed the breakpoint after filtering out unwanted addresses, but did not restore its source code

**Comment by cheat-engine** [comment]
that is weird though. Does the addresslist contain duplicates?  (In case it's restoring the byte to the original state of one that has already had a breakpoint set)

**Comment by lenct** [comment]
The breakpoint in the address table is still there, and the exception is the unused address that has been filtered out and that the filter has not recovered from

**Comment by lenct** [comment]
The breakpoint in the address table is still there, and the exception is the unused address that has been filtered out and that the filter has not recovered from
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Dark Byte <notifications@github.com>
发送时间: Sunday, March 3, 2019 4:49:50 PM
收件人: cheat-engine/cheat-engine
抄送: lenct; Author
主题: Re: [cheat-engine/cheat-engine] About "Code Filter" (#559)


that is weird though. Does the addresslist contain duplicates? (In case it's restoring the byte to the original state of one that has already had a breakpoint set)

―

**Comment by lenct** [comment]
Where "INT 3" is, the filter has filtered out the unwanted addresses

**Comment by cheat-engine** [comment]
"has been executed" always sets the breakpoint back

**Comment by cheat-engine** [comment]
[ce03032019.zip](https://github.com/cheat-engine/cheat-engine/files/2923092/ce03032019.zip)

should be fixed now

**Comment by lenct** [comment]
Yeah, now this is perfect. Thank you very much, Dark byte
