### ISSUE TITLE
About "set break condition"

### ISSUE THREAD

**Issue by lenct** [cheat-engine/cheat-engine#560]
![tim 20190303140735](https://user-images.githubusercontent.com/44138520/53691673-c97c7180-3dbd-11e9-9d49-848725d5c7d3.png)
How do I know if the pointer is not equal to?

![tim 20190303140745](https://user-images.githubusercontent.com/44138520/53691680-eb75f400-3dbd-11e9-9ae1-a4d54c95a7cf.png)
Could you please give an example about "complex"? Thanks for the author and the team's update. We will fully support you

**Comment by cheat-engine** [comment]
It's lua syntax there, so you need to use ~ instead of ! for the not-operator
readInteger(ESP+4)~=0x6

As for complex it's basically the same as easy, but allows multiple lines, and you have to manually "return" true/false

**Comment by lenct** [comment]
Thank you very much for your "Dark Byte", which solved my doubts!I'm really excited

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Dark Byte <notifications@github.com>
发送时间: Sunday, March 3, 2019 4:20:02 PM
收件人: cheat-engine/cheat-engine
抄送: lenct; Author
主题: Re: [cheat-engine/cheat-engine] Aboat "set break condition" (#560)


It's lua syntax there, so you need to use ~ instead of ! for the not-operator
readInteger(ESP+4)~=0x6

As for complex it's basically the same as easy, but allows multiple lines, and you have to manually "return" true/false

―
