### ISSUE TITLE
DBVM boot failed. Intel i9-7980XE

### ISSUE THREAD

**Issue by pyj2323** [cheat-engine/cheat-engine#561]
![20190303_172951](https://user-images.githubusercontent.com/32794121/53692889-cf348000-3dda-11e9-98d9-e43d624a1e2f.jpg)
![20190303_173038](https://user-images.githubusercontent.com/32794121/53692893-d491ca80-3dda-11e9-9671-050d4950886d.jpg)

My computer stopped when cpu enter vmx.

I used rufus to copy img file to my USB
cpu : i9-7980XE
motherboard : x299 aorus gaming 3 pro
I reduced cpu core (18 -> 4) before booting but did not work.

I tested at other computer(i7-7700HQ) and booting was succeded.
Why cannot i9-7980XE cpu run dbvm boot?

**Comment by cheat-engine** [comment]
check with a serial port, or if you don't have one, compile with DISPLAYDEBUG enabled.
The absense of screen clearing and no text at the top saying BOOT or aarg means the virtualization completely fails to start

Perhaps EFI boot might work better as that uses the same offload technique as in windows

**Comment by pyj2323** [comment]
how can I boot with EFI method?
I compiled with linux eclipse so got DBVMUEFI.EFI but i don't know next step.

**Comment by cheat-engine** [comment]
First find an efi bootloader (rEFInd works well https://sourceforge.net/projects/refind/files/0.11.4/ )
then create a EFI partition on your usb stick and setup rEFInd on that

Once you havea functioning EFI bootloader, test it. See if you can use it to boot up your windows system (big chance it won't find it if your system isn't currently using EFI and has to use bios tricks to load)

If it does work, copy DBVMUEFI.EFI and vmdisk.img to the root of the USB disk and boot off it.
Then select DBVMUEFI as bootoption , press enter when it asks to type something, and dbvm should get loaded and you'll return to the bootmenu as if nothing happened 
Then try to boot up window
