### ISSUE TITLE
ntopenprocess hooking crash data

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#563]
<img width="690" alt="x0" src="https://user-images.githubusercontent.com/18622105/53711159-1f1b5180-3e84-11e9-8fcf-fd6c4199b610.png">
<img width="683" alt="x1" src="https://user-images.githubusercontent.com/18622105/53711160-1f1b5180-3e84-11e9-8d5b-85a453600908.png">
<img width="830" alt="x2" src="https://user-images.githubusercontent.com/18622105/53711161-1f1b5180-3e84-11e9-940a-d77da5eaadb8.png">

windows 10 x64 redstone 5

ntdll.RtlWow64GetProcessMachines

return 00000000C0000008

js flag-> jump -> mov eax,C00000E5 -> return eax ->C00000E5 crash

x32bit module image breakpoint trace result

Size problem or something wrong after NOP hooking occurs when data is read from a 32-bit module

Solution not found in source

**Comment by kitty8904** [comment]
msdn result

0xC0000008 STATUS_INVALID_HANDLE | An invalid HANDLE was specified.

msdn trace results in an incorrect handle

It seems to happen when reading module information without a handle

A solution to bypass fake handles or handles?

**Comment by kitty8904** [comment]
<img width="823" alt="v1" src="https://user-images.githubusercontent.com/18622105/53712574-c8fddc80-3e8a-11e9-8c66-ca89f3307361.png">
<img width="841" alt="v2" src="https://user-images.githubusercontent.com/18622105/53712575-c8fddc80-3e8a-11e9-8867-5130a7900944.png">

Final result

0xC0000008 STATUS_INVALID_HANDLE | An invalid HANDLE was specified.
0xC000000D STATUS_INVALID_PARAMETER | An invalid parameter was passed to a service or function.





call ntdll.RtlWow64GetProcessMachines-->call ntdll.ZwQuerySystemInformationEx
rax 0xC0000008 -> fix rax 0

call ntdll.RtlReplaceSystemDirectoryInPath->rax 0xC000000D -> fix rax 0

<img width="758" alt="ok" src="https://user-images.githubusercontent.com/18622105/53712705-5e00d580-3e8b-11e9-9dee-a8d90a1e7538.png">

If you do this, all 32-bit modules will be visible again. I do not know how to fix this as a source

**Comment by cheat-engine** [comment]
Can you write an AA script that can make this function?
If so, you can do that in the source with a call to autoassemble as well
(have you tried hooking just ZwQuerySystemInformationEx because the rtl functions can not see if a handle is valid until they pass it of to kernelmode, usually by calling a nt* function)

**Comment by kitty8904** [comment]
Creating an AA script is easy
(For example, the beginning of a function
function:
(mov rax,0)
(ret)

Can not you handle it technically?

NextPseudoHandle: integer=integer(dword($ce000000));

Is there a problem because the handle is a fake handle but not in the kernel?

It may be a problem that no one cares about, but the Cheet engine without a handle is powerful. I wonder if there is a technological solution

**Comment by kitty8904** [comment]
handle ok -> orininal module list image
<img width="930" alt="original" src="https://user-images.githubusercontent.com/18622105/53736350-cfad4380-3ecc-11e9-80ad-857a47d7fd8a.png">

no handle ->ZwQuerySystemInformationEx, RtlWow64GetProcessMachines hook  module list image

<img width="930" alt="nohandle" src="https://user-images.githubusercontent.com/18622105/53736398-f4092000-3ecc-11e9-88ae-f2907cddf9d3.png">

no handle moudle image address Calculation error

kernel32.sleep
original -76901810
no handle -768fb3f0(error calculation)

If the module is obtained by forcibly changing the return value, the address value is abnormal

It's really hard to solve something without a handle
