### ISSUE TITLE
New update error

### ISSUE THREAD

**Issue by xXSilentHazeXx** [cheat-engine/cheat-engine#565]
When i downloaded the update i keep getting an access denied message did i do something wrong when i downloaded the new update 
![ce](https://user-images.githubusercontent.com/48228250/53772388-dd060600-3eab-11e9-9fdd-99ec2dfab54f.png)

**Comment by lenct** [comment]
Open the installation directory of CE, find the corresponding EXE file and then right click on the properties, to the properties interface to select compatibility and check the option to run in administrator mode click apply, I believe this can solve your problem.
![qq 20190306133500](https://user-images.githubusercontent.com/44138520/53858410-0c845200-4015-11e9-9620-1a7fb3d76f94.png)

**Comment by lenct** [comment]
You may think this is unnecessary, but it needs to be.

**Comment by xXSilentHazeXx** [comment]
Still didn't fix the problem

**Comment by lenct** [comment]
![tim 20190307192035](https://user-images.githubusercontent.com/44138520/53953368-20f84580-410e-11e9-89bd-3c5fb5b0bac6.png)
Let's set these two up
And if it doesn't, try turning off "window servise.
