### ISSUE TITLE
Assembler - mov qword ptr

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#567]
Why does mov qword ptr doesn't work, but fld qword ptr works? I.e. it claims it cannot compile it.

```
newmem:
mov qword ptr [eax+4],0

code:
fld qword ptr [eax+4]
```

**Comment by mgrinzPlayer** [comment]
For 32bit processes, it is normal.

**Comment by lenct** [comment]
You could write it like this-> mov [eax+4],0   
This can also write four bytes

**Comment by Symbai** [comment]
> 
> 
> You could write it like this-> mov [eax+4],0
> This can also write four bytes

I know but I wanted to write 8 bytes, not 4.

@mgrinzPlayer 
 Is there another operator than mov who can do this on x86 arichtecture? Preferrably single line, otherwise I could also write
```
mov [eax+4],0
mov [eax+8],0
```

**Comment by lenct** [comment]
For a 32-bit register you can't write 8 bytes at a time and you need to know that
16-bit register ->2 bytes
32-bit register ->4 bytes
64-bit register ->8 bytes

**Comment by lenct** [comment]
You can try writing:
cld 
mov esi,address1
mov edi,address2
mov ecx,8
rep  movsb

**Comment by Symbai** [comment]
Thanks but in this case I rather use this which is shorter:

```
mov [eax+4],0
mov [eax+8],0
```
