### ISSUE TITLE
Searching for ranges with first number > second number doesn't throw an error, finds weird stuff

### ISSUE THREAD

**Issue by RubinXnibu** [cheat-engine/cheat-engine#568]
I was trying to maximize faction reputation in Grim Dawn, which is floats.  Searching for negative reputation -6264 with "value between" of -6263 and -6265, and CheatEngine finds -9.043239303E31 -514264.4062 -35773.96875 etc, it finds all negative values, ignoring the range.   This was my mistake, I should have done -6265 to -6263.   However, the CheatEngine could catch this mistake and throw an error.

It's also an issue in integer searches, searching for negative 4-byte values with "value between" ranged search for -3 to -99999999 ended up getting 0, 27, 4294967295, etc.   

Finally, I tried an integer search between -1 and "walrus" ... it also works (though badly).   

So I am less of a dumb user than I was yesterday, but my suggestion is to add some input validation to CE to help other dumb users.

**Comment by cheat-engine** [comment]
should error out now

**Comment by RubinXnibu** [comment]
Thank you for your work!!
