### ISSUE TITLE
cheat engine won't open

### ISSUE THREAD

**Issue by NanuKKovar** [cheat-engine/cheat-engine#571]
Hello admin , 

I have a problem , when open cheat break so it does not open 

srry for me english

**Comment by cheat-engine** [comment]
https://github.com/cheat-engine/cheat-engine/issues/533

**Comment by Olympi4** [comment]
Do you guys mean badlion like the minecraft client badlion. Or is this some other kind of badlion.

**Comment by supercoolgamer35** [comment]
> 
> 
> Do you guys mean badlion like the minecraft client badlion. Or is this some other kind of badlion.

yes, he means badlion client

**Comment by ObergineCode** [comment]
even if i remove badlion client it wont start

**Comment by cheat-engine** [comment]
Uninstall the badlion client (don't delete random files you think are related), it infects some other locations on your harddisk like your windows folder and windows will autorepair those files there

after that restart, do NOT shutdown as that will make windows fake a shutdown

**Comment by Merith-TK** [comment]
wait so badlion acts like a maleware that infects itself onto your PC?!

**Comment by cheat-engine** [comment]
looks like it indeed

**Comment by Merith-TK** [comment]
That's pure bullshit. Just why?! I understand if badlion is even running, but while it isn't?

**Comment by fade2gray** [comment]
@Merith-TK [read this](https://www.badlion.net/forum/thread/225773)

**Comment by 0-x-2-2** [comment]
make sure the esea/badlion driver is not running after you uninstall
