### ISSUE TITLE
Error in the last two Updates

### ISSUE THREAD

**Issue by Sergiocubano1** [cheat-engine/cheat-engine#572]
In the last two updates you can not change the data in some games, such as metro exodus and some more, correct that please, I still stay in version 6.8.1

**Comment by cheat-engine** [comment]
what happens when you try to change the data ?
And what windows version ?

**Comment by Sergiocubano1** [comment]
Hello, the version of windows 10, and what happens is that in the version of cheat engine 6.8.1 you will see two data when you give to search to change them, however when you search with version 6.8.3 you will see a single data and when you change the value it does not work, while in version 6.8.1 if it works since it is two data that you change the value
