### ISSUE TITLE
Driver Load?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#573]
type
UNICODE_STRING = record
Length: Word;
MaximumLength: Word;
Buffer: PWideChar;
end;

PUNICODE_STRING = ^UNICODE_STRING;  

procedure RtlInitUnicodeString(DestinationString : PUNICODE_STRING;SourceString : LPCWSTR); stdcall; {$IFNDEF RTDL}external ntdll;{$ENDIF}

type ZwLoadDriver = function(DriverServiceName: PUNICODE_STRING): NTStatus; stdcall;

procedure NTLoadDriver;
var
LoadDriver:ZwLoadDriver;
UNIString : PUNICODE_STRING;
begin
      reg:=tregistry.Create;
      reg.RootKey:=HKEY_LOCAL_MACHINE;
      if reg.OpenKey('\SYSTEM\CurrentControlSet\Services\123456',true) then
      begin
      reg.WriteInteger('Start',3);
      reg.WriteInteger('Type',1);
      reg.WriteInteger('ErrorControl',1);
      reg.WriteString('DisplayName','123456');
      reg.WriteExpandString('ImagePath','\??\C:\123456.sys');
      reg.WriteString('A','\Device\'+'123456');
      reg.WriteString('B','\DosDevices\'+'123456');
      reg.WriteString('C','\BaseNamedObjects\'+'123456');
      reg.WriteString('D','\BaseNamedObjects\'+'123456');
      reg.CloseKey;
      reg.Free; 

     RtlInitUnicodeString(UNIString,'\Registry\Machine\SYSTEM\CurrentControlSet\Services\123456');
     LoadDriver:=GetProcAddress(GetModuleHandle('ntdll.dll'),'ZwLoadDriver');
     LoadDriver(UNIString); // <-failed?

     end;
end;

I want to load the drive with the ZwLoadDriver function

Why does not the cheat engine driver load? I wonder what's wrong

**Comment by kitty8904** [comment]
function  ZwLoadDriver(DriverServiceName: PUNICODE_STRING): NTSTATUS; stdcall; external ntdll;

UNIString : UNICODE_STRING;

 UNIString.Buffer:='\Registry\Machine\SYSTEM\CurrentControlSet\Services\12345678';
 UNIString.Length:=48;
 UNIString.MaximumLength:=50;

 ZwLoadDriver(@UNIString);

Debugging information seems to call properly but the driver will not load

why?

**Comment by cheat-engine** [comment]
0xC0000034 is "object name not found"

are you sure imagepath is ??\  and not \??\

besides that no idea, i never used that function

**Comment by kitty8904** [comment]
yes no debug view print

I know it works well if I start with a service

I wanted to use the zwloaddriver implementation

https://github.com/GitMirar/DriverLoader/blob/master/DriverLoader/DriverLoader.cpp

delphi zwloaddriver

Eraser ->  / ?? / does not load driver

function  ZwLoadDriver(DriverServiceName: PUNICODE_STRING): NTSTATUS; stdcall; external ntdll;

procedure TForm1.Button1Click(Sender: TObject);
var
UNIString : UNICODE_STRING;
reg: tregistry;
begin
reg:=tregistry.Create;
reg.RootKey:=HKEY_LOCAL_MACHINE;
if reg.OpenKey('\SYSTEM\CurrentControlSet\Services\123456',true) then
begin
reg.WriteInteger('Start',3);
reg.WriteInteger('Type',1);
reg.WriteInteger('ErrorControl',1);
reg.WriteString('DisplayName','123456');
reg.WriteExpandString('ImagePath','\??\C:\123456.sys');
reg.WriteString('A','\Device\'+'123456');
reg.WriteString('B','\DosDevices\'+'123456');
reg.WriteString('C','\BaseNamedObjects\'+'123456');
reg.WriteString('D','\BaseNamedObjects\'+'123456');
reg.CloseKey;
reg.Free;
UNIString.Buffer:='\Registry\Machine\System\CurrentControlSet\Services\123456';
UNIString.Length:=58;
UNIString.MaximumLength:=60;
ZwLoadDriver(@UNIString);    
end;
end;

What is the problem?

**Comment by kitty8904** [comment]
<img width="568" alt="nt" src="https://user-images.githubusercontent.com/18622105/54258055-be3afa00-45a4-11e9-96d7-5206a1f91f99.png">

[DriverLoader.zip](https://github.com/cheat-engine/cheat-engine/files/2960032/DriverLoader.zip)

**Comment by kitty8904** [comment]
procedure RtlInitUnicodeString(DestinationString : PUNICODE_STRING; SourceString : PWideChar); stdcall; external ntdll;

function  ZwLoadDriver(DriverServiceName: PUNICODE_STRING): NTSTATUS; stdcall; external ntdll;

procedure TForm1.Button1Click(Sender: TObject);
//var
//LoadDriver: @ZwLoadDriver;

//NTDLLHandle: THandle;
//NTDLLHandle2: pointer;
//wstring : PUNICODE_STRING;

var
UNIString : UNICODE_STRING;
reg: tregistry;
begin
reg:=tregistry.Create;
reg.RootKey:=HKEY_LOCAL_MACHINE;
if reg.OpenKey('\SYSTEM\CurrentControlSet\Services\1234',true) then
begin
reg.WriteInteger('Start',3);
reg.WriteInteger('Type',1);
reg.WriteInteger('ErrorControl',1);
reg.WriteString('DisplayName','1234');
//reg.WriteExpandString('ImagePath','\??\C:\1234.sys');
reg.WriteString('ImagePath','\??\C:\1234.sys');
reg.WriteString('A','\Device\'+'1234');
reg.WriteString('B','\DosDevices\'+'1234');
reg.WriteString('C','\BaseNamedObjects\'+'1234');
reg.WriteString('D','\BaseNamedObjects\'+'1234');
reg.CloseKey;
reg.Free;
//UNIString.Buffer:='\Registry\Machine\System\CurrentControlSet\Services\1234';
UNIString.Buffer:='\Registry\Machine\System\CurrentControlSet\Services\1234';
UNIString.Length:=$70;
UNIString.MaximumLength:=$72;
ZwLoadDriver(@UNIString);

 //RtlInitUnicodeString(;
// NTDLLHandle:=LoadLibrary('ntdll.dll');

///NTDLLHandle2:= @ZwLoadDriver;
// NTDLLHandle2 := GetProcAddress(GetModuleHandle('ntdll.dll'),'ZwLoadDriver');
// LoadDriver:= NTDLLHandle2;
 //LoadDriver(UNIString); // <-failed?

 end;
end;

procedure TForm1.FormCreate(Sender: TObject);
var
ownprocesshandle: THandle;
tokenhandle: thandle;
tp: TTokenPrivileges;
prev: TTokenPrivileges;
ReturnLength: dword = 0;

begin
ownprocesshandle := OpenProcess(PROCESS_ALL_ACCESS, True, GetCurrentProcessId);
tokenhandle := 0;
if ownprocesshandle <> 0 then
begin
  if OpenProcessToken(ownprocesshandle, TOKEN_QUERY or TOKEN_ADJUST_PRIVILEGES,tokenhandle) then
  begin
    ZeroMemory(@tp, sizeof(tp));
    ZeroMemory(@prev, sizeof(prev));

    if lookupPrivilegeValue(nil,'SeLoadDriverPrivilege', tp.Privileges[0].Luid) then
    begin
      tp.Privileges[0].Attributes := SE_PRIVILEGE_ENABLED;
      tp.PrivilegeCount := 1; // One privilege to set
      AdjustTokenPrivileges(tokenhandle, False, tp, sizeof(tp), prev, returnlength);
    end;
end;

end;

end;

////////////////////////////////////////////////////////////////////

Resolved

Unicode variable declaration and SeLoadDriverPrivilege permissions issue
