### ISSUE TITLE
Tracer Incorrectly Shows Error Message on Trace Save/Open

### ISSUE THREAD

**Issue by dsasmblr** [cheat-engine/cheat-engine#574]
![error](https://user-images.githubusercontent.com/22781064/54242773-38637400-44fc-11e9-80c4-1581022910c0.png)

In the Tracer, when saving/opening a trace, the "Stream write error" message is display even though the trace saves and opens just fine (from what I've verified here, at least).

**Comment by cheat-engine** [comment]
any special options used to generate the trace ? e.g stack snapshots ?
and does loading it back really work? Check the last entry in the list and verify it has registers set
