### ISSUE TITLE
Add translations options ?

### ISSUE THREAD

**Issue by Anonymous-any** [cheat-engine/cheat-engine#575]
Hello, like the picture show I'm unable to found the text in the "type box" if you can add in future version :)
![1](https://user-images.githubusercontent.com/25174503/54320048-f580c980-45eb-11e9-8e2f-0b73007bcde3.jpg)

Br

**Comment by cheat-engine** [comment]
Added these to the translation list

**Comment by Anonymous-any** [comment]
Grt ! thanks
