### ISSUE TITLE
dbvm 13 bluescreen

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#576]
vmware dbvm 13 load -> BSOD

**Comment by kitty8904** [comment]
and 32bit build error 

hasEPTSupport

{$ifndef CPUX86_64 and ifndef CPUi386}

function isIntel: boolean;
begin
  result:=false;
end;

function isAMD: boolean;
begin
  result:=false;
end;

function isDBVMCapable: boolean;
begin
  result:=false;
end;

function hasEPTSupport: boolean;
begin
  result:=false;
end;

{$else}

        {$ifdef cpu64}
        changereginfo.Flags.changeR8:=ifthen(tempregedit.change_r8,1,0);
        changereginfo.Flags.changeR9:=ifthen(tempregedit.change_r9,1,0);
        changereginfo.Flags.changeR10:=ifthen(tempregedit.change_r10,1,0);
        changereginfo.Flags.changeR11:=ifthen(tempregedit.change_r11,1,0);
        changereginfo.Flags.changeR12:=ifthen(tempregedit.change_r12,1,0);
        changereginfo.Flags.changeR13:=ifthen(tempregedit.change_r13,1,0);
        changereginfo.Flags.changeR14:=ifthen(tempregedit.change_r14,1,0);
        changereginfo.Flags.changeR15:=ifthen(tempregedit.change_r15,1,0);
        {$endif}  


        {$ifdef cpu64}
        changereginfo.newR8:=tempregedit.new_r8;
        changereginfo.newR9:=tempregedit.new_r9;
        changereginfo.newR10:=tempregedit.new_r10;
        changereginfo.newR11:=tempregedit.new_r11;
        changereginfo.newR12:=tempregedit.new_r12;
        changereginfo.newR13:=tempregedit.new_r13;
        changereginfo.newR14:=tempregedit.new_r14;
        changereginfo.newR15:=tempregedit.new_r15;

        {$endif}

**Comment by cheat-engine** [comment]
for the BSOD , Is your vmware configured to emulate the performance counter ? You may wish to change that and see if it has a difference

and remove #define TSCHOOK from common.h in vmm if you can't get it to work, it's not designed to work in an emulated environment
