### ISSUE TITLE
Problem with color addresses

### ISSUE THREAD

**Issue by Anonymous-any** [cheat-engine/cheat-engine#577]
I don't know where to talk about this but I cannot get back my "black" addresses color pointer's  like 6.2 version cause I updated to the latest. I searched in windows registry with no success.
Can I have any information's about that please on how I can change em ?

I'm a bit daltonian for explain... :/ and newbie plus on CE

**Comment by cheat-engine** [comment]
Sorry, I missed this question when it got posted.  But what do you mean with "Black" addresses color pointer ?

**Comment by Anonymous-any** [comment]
Hi thank for reply, then I show you a screen so what I say is in the 6.2 version the one I have before I update to 6.8.3 ^^The color pointer address was black ! in the screenshot I put the red arrow on it because I cannot say you what color it is but it's not black it was on 6.2 version (I know this is stupid for you) but I would like to know where I can change this for get it back black you know ?
![1](https://user-images.githubusercontent.com/25174503/56451784-bef64700-632d-11e9-96dd-7239d73a6b24.jpg)
Regard

**Comment by cheat-engine** [comment]
it can be customized now

**Comment by Anonymous-any** [comment]
Many thank can you say more path where we can found it to customize files/registry/parameters ?
Br

**Comment by cheat-engine** [comment]
in the next version (or git selfbuilt) rightclick the list and you can choose preferences there

**Comment by Anonymous-any** [comment]
thanks
