### ISSUE TITLE
how to study about virtual machine(dbvm) coding?

### ISSUE THREAD

**Issue by pyj2323** [cheat-engine/cheat-engine#578]
Recently, I spend a lot of time reviewing dbvm source code. but It's very hard to understand that because I am noobie about virtual machine.

Do you know a website or book that will teach virtual machine coding from the ground up? 
How to debug with dbvm? My computer doesn't have serial port.

**Comment by cheat-engine** [comment]
**Everything** in https://software.intel.com/sites/default/files/managed/39/c5/325462-sdm-vol-1-2abcd-3abcd.pdf

But more specifically volume 2 chapter 23 to 33

As for debugging, do you have an old non-updated gigabyte mainboard (100/200 gen) ? If so you could try intel DCI (Just a 'standard' A<>A cable) and intel system debugger.   
You still won't be able to see the logs, but debugging is easier.
e.g:
![intel system studio attached to my other system](https://user-images.githubusercontent.com/12006555/54471862-36313c00-47c0-11e9-8a9e-8ebf7965525b.png)

**Comment by pyj2323** [comment]
that pdf is too big and difficult.......
when you were begginer at hypervisor, what was your ABC book?

**Comment by cheat-engine** [comment]
Literally that book. (well, volume 3) I had it in actual book format
