### ISSUE TITLE
how to build protject dbvm in cheatengine6.4 src

### ISSUE THREAD

**Issue by nobita0811** [cheat-engine/cheat-engine#580]
i use mingw gcc 4.7.2 to build makefile in project dbmv  .
i get  this error. 
i need help to build dbvm in win7 64bit
![image](https://user-images.githubusercontent.com/25197944/54485125-eb89ef80-48a5-11e9-9959-7c3511c48636.png)

this makefile

![image](https://user-images.githubusercontent.com/25197944/54485161-79fe7100-48a6-11e9-8bc2-46859a014c35.png)

**Comment by nobita0811** [comment]
after learn in google i complie some file but get this error

![image](https://user-images.githubusercontent.com/25197944/54489235-d4b2bf80-48dc-11e9-94aa-c346092c63f7.png)


at code in makefile 
![image](https://user-images.githubusercontent.com/25197944/54489251-eeec9d80-48dc-11e9-8e5a-7065c5a0347b.png)

**Comment by cheat-engine** [comment]
you need to compile it as a linux ELF, not PE

**Comment by nobita0811** [comment]
@cheat-engine  i'm noob, now  can i complie it in linux with VMWare ?

**Comment by cheat-engine** [comment]
yes, a linux instyall in vmware will work.

Also, why do you even try the 6.4 source? Most likely this version will just freeze/bsod you

**Comment by nobita0811** [comment]
CE 6.83 do not load driver if my window enable driver signature enforcement. i have problem with EAC an BattleEye
