### ISSUE TITLE
address calculation?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#584]
<img width="614" alt="qq" src="https://user-images.githubusercontent.com/18622105/54848299-4b5c1c80-4d24-11e9-8840-7969b855ef30.png">

FFFFF80003699BB5 - 8B 05 2599D9FF        - mov eax,[FFFFF800034334E0] { 54736096 }

FFFFF80003699BB5 + FFD99925 + 6 -> FFFFF801034334E0

why FFFFF801034334E0 ?

cheat engine -> FFFFF800034334E0

Address calculation is strange What is wrong?

The cheat engine is accurate I do not know how to calculate the address

**Comment by cheat-engine** [comment]
Offsets are signed values in 64-bit, so FFD99925 turns into FFFFFFFFFFD99925 
FFFFF80003699BB5 + FFFFFFFFFFD99925 + 6= FFFFF800034334E0

**Comment by kitty8904** [comment]
UINT64 GetPspNEMAddress()
{
	//PspNotifyEnableMask ALL = 15(0xF) Disabled = 0
	ULONG64 i = 0;
	PUINT64 pAddrOfFnc = 0;
	UNICODE_STRING fncName;
	RtlInitUnicodeString(&fncName, L"PsSetLoadImageNotifyRoutine");
	UINT64 fncAddr = (UINT64)MmGetSystemRoutineAddress(&fncName);
	if (fncAddr)
	{
		fncAddr += 0x50;
		for (i = fncAddr; i < fncAddr + 0xFF; i++)
		{
			if (*(UCHAR*)i == 0x8B && *(UCHAR*)(i + 1) == 0x05)
			{
				DWORD OffsetAddr = 0;
				memcpy(&OffsetAddr, (UCHAR*)(i + 2), 4);
				DbgPrint("OffsetAddr:%llx\n", OffsetAddr);

				pAddrOfFnc = (UINT64*)(OffsetAddr + i + 0x6);
				DbgPrint("i:%llx\n", i);
				DbgPrint("pAddrOfFnc:%llx\n", pAddrOfFnc);

				//DbgPrint("NOTIFY: Breaki'n \n");
				break;
			}
		}
		return (UINT64)pAddrOfFnc;
	}
	return 0;
}

PspNotifyEnableMask Search how fix?

I tried to modify the PspNotifyEnableMask flag in the kernel. How do I fix the FF address calculation? Sorry, this is a source on the forum

**Comment by cheat-engine** [comment]
try replacing
`pAddrOfFnc = (UINT64*)(OffsetAddr + i + 0x6);`
with
`pAddrOfFnc = (UINT64*)(OffsetAddr + (LONG64)i + 0x6);`

Alternatively, in case you're using the current CE snapshot: view->kernelmode symbols, file->use windows debug symbols
then after a long time once all symbols are downloaded and parsed you can get the address of PspNotifyEnableMask from CE.  (Just go to hexview, goto address and type in `PspNotifyEnableMask` )

**Comment by kitty8904** [comment]
DWORD OffsetAddr = 0;  -> FIX -> LONG32 OffsetAddr = 0;
(Address value is normally obtained)

I changed to a signed ULONG and it is Today I learned one more Thank you
