### ISSUE TITLE
lua stringlist has some problem

### ISSUE THREAD

**Issue by k3v1n1990s** [cheat-engine/cheat-engine#588]
if code like this:
igdumdim32.dll+DF650 - 55                    - push ebp
igdumdim32.dll+DF651 - 8B EC                 - mov ebp,esp
igdumdim32.dll+DF653 - FF 75 14              - push [ebp+14]
in autoassemble - Template - Code injection 
this works good
but the 'push [ebp+14]' in autoassemble code will be join a ' ' text behind the 'push [ebp+14]'
it causes the lua engine bug:
"script = createStringList()
generateCodeInjectionScript(script,'igdumdim32.dll+DF650')
print(script.Text)"

the script.Text will be truncated in the line behind 'push [ebp+14] '
i think the problem is in the source code 'frmautoinjectunit.pas' 
line 778 'originalcode[length(originalcode)-1]:=copy(originalcode[length(originalcode)-1],i+2,length(originalcode[length(originalcode)-1]));'

**Comment by k3v1n1990s** [comment]
fix： originalcode[length(originalcode)-1]:=disassemble(c,x).Replace(chr(0),' ');

**Comment by k3v1n1990s** [comment]
@cheat-engine

**Comment by cheat-engine** [comment]
I can not reproduce your bug. Make sure you are on the current github sourcecode (So not on 6.8.2 or older)

**Comment by k3v1n1990s** [comment]
sorry,6.8.2 has this problem,6.8.3 resolved
