### ISSUE TITLE
Properies of TCEEdit are not backward compatible

### ISSUE THREAD

**Issue by xAranaktu** [cheat-engine/cheat-engine#596]
I noticed that if you save form that contains 'TCEEdit' components in CE 6.8.3 you will not be able to open this form in CE 6.8.1 because of added 'TextHintFontColor' and 'TextHintFontStyle' properties.
Dunno if it's intended or not (I couldn't find any info about that in changelog), so I've decited to open an issue.

![](https://i.imgur.com/NJwV8xY.png)

**Comment by cheat-engine** [comment]
yes, it is possible older versions won't be able to load tables by newer versions. 

e.g the advanced options list also can't be loaded by 6.8.1

i think the older version user will get a notification stating that not all items will load properly
