### ISSUE TITLE
"Cheat Engine.exe" 6.8.3 is not signed by the same certificate as other executable

### ISSUE THREAD

**Issue by zypA13510** [cheat-engine/cheat-engine#601]
![image](https://user-images.githubusercontent.com/8077540/55338460-5d338180-54d3-11e9-958b-7f38d3c66d1e.png)

As you can see from the screenshot above, `Cheat Engine.exe` is signed with a self-issued certificate, unlike `cheatengine-i386.exe` and `cheatengine-x86_64.exe`, resulting in a yellow "unknown publisher" warning in UAC prompt. I don't remember seeing this when running 6.8.1, which I just upgraded from.

**Comment by crypt1cx** [comment]
Same issue. Also with the new installer, there is something odd, it tries to connect to rp.ginihehen.com,
I never had this before.

**Comment by abvgeej** [comment]
Looks fine on my side
[ce.zip](https://github.com/cheat-engine/cheat-engine/files/3169455/ce.zip)

Cheat Engine.exe
MD5: 55E7252D2A44D53C25BECF391D23AA17
SHA256: 98C7788A997DF3C4D012BCFEF4E252EC388B6052427FF6BDB3893AA88066D3AC

cheatengine-i386.exe
MD5: 7B695BB75465A01F52712FC68DB740CF
SHA256: 9154AB9DE70CB4F68D15283B282F804826466DE5B8A45D503E8DA6180DF85063

cheatengine-x86_64.exe
MD5: 07DD6163D84ED70969EA55A2CECD7F86
SHA256: AF08280B4BD8489666BCADD2C9489B7A176C52A5FDA2BF1EF515C9882F35731C

**Comment by zypA13510** [comment]
Yeah, looks like it's being fixed. I'm going to close this issue.
