### ISSUE TITLE
Nosetup download link (windows) is broken

### ISSUE THREAD

**Issue by B3bomber** [cheat-engine/cheat-engine#604]
https://cheatengine.org/download/CheatEngine68.3_MissingSetup.rar

From the main site. Result: 403 - Forbidden

**Comment by cheat-engine** [comment]
that link only works on the ce website
go to https://cheatengine.org/downloads.php and click on the link there

**Comment by B3bomber** [comment]
That is where I found it and clicked it from. I had someone else test it too.
