### ISSUE TITLE
CE is inconsitent when placing "Advanced Options" window.

### ISSUE THREAD

**Issue by osmin1** [cheat-engine/cheat-engine#612]
Cheatengine remembers last position of many windows, including "Advanced settings" window. I like that behaviour; unfortunately it breaks when one opens CE table - then CE resets position of "Advanced options" window. The only way to avoid this that I found, is to generate lot of HDD activity and making lots of mouse presses outside CE (for example while loading a game for the first time and generating mouse press events inside game window while loading - https://www.youtube.com/watch?v=BRWGiHDL_lY); during such load CE "forgets" to reposition our window.
Unfortunately when one tries to load a game for the second time, HDD activity is to low and window once again is moved: https://www.youtube.com/watch?v=Dz6vIT2g08U

I think "Advanced settings" window shouldn't be moved or at least it's behaviour should be consistent - under stress or not.

**Comment by cheat-engine** [comment]
it won't move anymore after the initial positioning
