### ISSUE TITLE
pdb suggestion

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#614]
<img width="218" alt="pdb" src="https://user-images.githubusercontent.com/18622105/55870118-d8c3bb80-5bc2-11e9-946a-da6a4e496298.png">

<img width="418" alt="pdb2" src="https://user-images.githubusercontent.com/18622105/55871148-01e54b80-5bc5-11e9-9bda-d80e1f5d0671.png">

C:\Users\Administrator\AppData\Local\Temp\Cheat Engine Symbols

1. PDB file download complete status

2. Kernel Mode symbol check

3. But the detailed kernel PDB information is not read

4. User Windows Debug Symbol Click -> PDB information is read ok

If you have a PDB file, suggest that you read it immediately if you click on the kernel mode symbol

Do I have to click the Windows Debug symbol again to load the details?

=====================================================

If the PDB file is in a folder, it should be changed to read immediately

eg.test windows ntoskrnl.exe PspNotifyEnableMask read

==========================================

And does Windows 7 x64 PDB reading work well?

ntoskrnl.exe PDB file can not be downloaded from Windows7 vmware
(service pack1 ntoskrnl.exe version 6.1.7601.17514)

Is my computer a VMware issue? PDB Windows 7 x64 file can not be downloaded
(ntkrnlmp.pdb)

**Comment by cheat-engine** [comment]
on my windows 7 system (SP1)  it also doesn't download ntoskrnl.exe, but it does get ntknlmp.pdb which does contain the information for ntoskrnl
![win7sym](https://user-images.githubusercontent.com/12006555/55886116-7612f580-5bab-11e9-8032-2856615a0b78.png)
