### ISSUE TITLE
v6.8.3 Ctrl+S (Save) not working

### ISSUE THREAD

**Issue by bunalz** [cheat-engine/cheat-engine#620]
Freshly downloaded on Win7 SP1.

For some reason, I couldn't do a Save action, either by keyboard or via the menu--nothing happened; if I try to exit, saving reminder pops up.

Save As (Ctrl+Alt+S) works fine.

**Comment by cheat-engine** [comment]
can't reproduce

**Comment by bunalz** [comment]
Sorry about this late reply.
I fixed it somehow after I uninstalled my 6.3 version (something to do with the colour files or something).
