### ISSUE TITLE
debugger freezes 

### ISSUE THREAD

**Issue by Karaulov** [cheat-engine/cheat-engine#621]
Game without protection. I tried enable option "wait gui" but didn't help.

Debugger freezes after ALT+TAB to CE from game.

**Comment by cheat-engine** [comment]
which debugger interface?

**Comment by Karaulov** [comment]
Windows

**Comment by Karaulov** [comment]
Cheat Engine 6.4 works but with installer install adware kaspersky found virus. Fusion.dll
