### ISSUE TITLE
X86 build fail!

### ISSUE THREAD

**Issue by dtamade** [cheat-engine/cheat-engine#623]
Registers code

**Comment by editgames-owner** [comment]
Lazarus 2.0.0
> (3104) Compiling frmModifyRegistersUnit.pas
> C:\Users\Name\Documents\GitHub\cheat-engine\Cheat Engine\frmModifyRegistersUnit.pas(288,56) Error: (5038) identifier idents no member "change_r8"
> C:\Users\Name\Documents\GitHub\cheat-engine\Cheat Engine\frmModifyRegistersUnit.pas(289,56) Error: (5038) identifier idents no member "change_r9"
> C:\Users\Name\Documents\GitHub\cheat-engine\Cheat Engine\frmModifyRegistersUnit.pas(290,57) Error: (5038) identifier idents no member "change_r10"
> C:\Users\Name\Documents\GitHub\cheat-engine\Cheat Engine\frmModifyRegistersUnit.pas(291,57) Error: (5038) identifier idents no member "change_r11"
> C:\Users\Name\Documents\GitHub\cheat-engine\Cheat Engine\frmModifyRegistersUnit.pas(292,57) Error: (5038) identifier idents no member "change_r12"
> C:\Users\Name\Documents\GitHub\cheat-engine\Cheat Engine\frmModifyRegistersUnit.pas(293,57) Error: (5038) identifier idents no member "change_r13"
> C:\Users\Name\Documents\GitHub\cheat-engine\Cheat Engine\frmModifyRegistersUnit.pas(294,57) Error: (5038) identifier idents no member "change_r14"
> C:\Users\Name\Documents\GitHub\cheat-engine\Cheat Engine\frmModifyRegistersUnit.pas(295,57) Error: (5038) identifier idents no member "change_r15"
> C:\Users\Name\Documents\GitHub\cheat-engine\Cheat Engine\frmModifyRegistersUnit.pas(319,40) Error: (5038) identifier idents no member "new_r8"
> C:\Users\Name\Documents\GitHub\cheat-engine\Cheat Engine\frmModifyRegistersUnit.pas(320,40) Error: (5038) identifier idents no member "new_r9"
> C:\Users\Name\Documents\GitHub\cheat-engine\Cheat Engine\frmModifyRegistersUnit.pas(321,41) Error: (5038) identifier idents no member "new_r10"
> C:\Users\Name\Documents\GitHub\cheat-engine\Cheat Engine\frmModifyRegistersUnit.pas(322,41) Error: (5038) identifier idents no member "new_r11"
> C:\Users\Name\Documents\GitHub\cheat-engine\Cheat Engine\frmModifyRegistersUnit.pas(323,41) Error: (5038) identifier idents no member "new_r12"
> C:\Users\Name\Documents\GitHub\cheat-engine\Cheat Engine\frmModifyRegistersUnit.pas(324,41) Error: (5038) identifier idents no member "new_r13"
> C:\Users\Name\Documents\GitHub\cheat-engine\Cheat Engine\frmModifyRegistersUnit.pas(325,41) Error: (5038) identifier idents no member "new_r14"
> C:\Users\Name\Documents\GitHub\cheat-engine\Cheat Engine\frmModifyRegistersUnit.pas(326,41) Error: (5038) identifier idents no member "new_r15"
> frmModifyRegistersUnit.pas(432) Fatal: (10026) There were 16 errors compiling module, stopping
> Fatal: (1018) Compilation aborted
> Error: C:\lazarus\fpc\3.0.4\bin\x86_64-win64\ppc386.exe returned an error exitcode
