### ISSUE TITLE
Fast AND Select PDB LOAD

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#626]
I want to load and select PDB

ntoskrnl.exe I want to load only the kernel part fast, but I am now reading the entire PDB list

If the PDB file exists, it suggests selectively loading the PDB

**Comment by cheat-engine** [comment]
try
```
searchPDBWhileLoading(true)
```
then when a process has opened and pdb scanning has started (after waitforDotNet() returns)
you can use symbolnames like "ntoskrnl.PsOpenProcess"  which will speed up the scan by telling the pdb  scanner to search ntoskrnl only

e.g:
```
searchPDBWhileLoading(true)
waitforDotNet()
sleep(100) --just making sure
a=getAddressSafe('ntoskrnl.PsOpenProcess')
if a then
  print(string.format("%x", a))
else
  print("not found")
end
```
