### ISSUE TITLE
F8 cause CE freeze

### ISSUE THREAD

**Issue by Karaulov** [cheat-engine/cheat-engine#627]
I tried enable 'wait for gui' but it didn't help.

![BP1x8Vg 1](https://user-images.githubusercontent.com/6445336/56269240-efef3580-60fb-11e9-9494-e43bed93a7d5.png)

**Comment by cheat-engine** [comment]
try using the menu system only instead of the f8 hotkey and see if that works better

**Comment by Karaulov** [comment]
strange...i can't reproduce this issue)))

**Comment by cheat-engine** [comment]
is this 6.8.3 or your own build from this github? (it should be fixed on github)

**Comment by Karaulov** [comment]
No. This build downloaded from website https://cheatengine.org
You can add autobuild bot( as appveyor )? for download latest nightbuilds))
