### ISSUE TITLE
Pointer Searcher Bug

### ISSUE THREAD

**Issue by Sc0tiine** [cheat-engine/cheat-engine#632]
Pointer searcher doesn't work for me but it work for my friend, do I need a specific Windows configuration?
I did everything like he did but the pointer search shows "0 result"

**Comment by cheat-engine** [comment]
don't put your results in a folder with non ascii characters

**Comment by Sc0tiine** [comment]
I did this, but it doesn't work (the path where I saved the pointer file is clean)

**Comment by cheat-engine** [comment]
Open the correct process
set the level and structsize high enough
and perhaps increase max number of nodes or disable that

**Comment by Sc0tiine** [comment]
Cheat engine scan the file for pointers, not a process.
this is my configuration:
![Sans titre](https://user-images.githubusercontent.com/37966589/56419407-717cca00-629a-11e9-84e0-4be914d71610.jpg)

**Comment by cheat-engine** [comment]
Did you load the file at the correct start address ? Is the bitness set correct?
Does address 15871050 even exist ?
try level 10

Do you use ce 6.8.3 or older ?

**Comment by Sc0tiine** [comment]
My bad, it work for 32bit files but not for 64 bit.
File characteristics:
64bit
Size: 282Mo
Base Address: 2120B6E000

0 results for me, unlike my friend who have results

**Comment by Sc0tiine** [comment]
Forgot: I use Cheat Engine 6.8.3

**Comment by cheat-engine** [comment]
if the base address is set at 2120B6E000 then there are two issues
1: address 15871050  does not exist
2: pointerpath may only be inside this region excludes that region

**Comment by Sc0tiine** [comment]
Sorry, fixed

**Comment by dbsxdbsx** [comment]
@Sc0tiine ,so how did you fixed.  I used the same version. But the first time I can got result, but no after relaunch my game.
