### ISSUE TITLE
dbvm 13 blue screen

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#633]
[vmdisk13.zip](https://github.com/cheat-engine/cheat-engine/files/3098192/vmdisk13.zip)

Loading the latest source vmdisk13 version causes pc suspend

The version of vmdisk12 is OK

13 version TSC HOOK issue

I do not know the solution

i9 9900k

win10 x64 17763.437(rs5)

no vmware

main pc test

**Comment by cheat-engine** [comment]
remove the line
`#define TSCHOOK`
( https://github.com/cheat-engine/cheat-engine/blob/master/dbvm/vmm/common.h#L8 )

and see if it still crashes

**Comment by kitty8904** [comment]
[vmdisknotsc.zip](https://github.com/cheat-engine/cheat-engine/files/3098219/vmdisknotsc.zip)

okay remove tschook

Normal operation without blue screen

Is the TSC HOOK function error?

**Comment by cheat-engine** [comment]
probably. it's more a test.  Perhaps the time calculation is off for your cpu, or goes negative.
Also, what BSOD did you get ?

**Comment by kitty8904** [comment]
no error message 

Computer freezing pc suspend

The computer is freezing and forced to reboot

**Comment by cheat-engine** [comment]
ok, no blue screen, but just freeze. That means DBVM entered a state it can't emulate. Which can be an invalid vm state (tsc exiting not supported) or the system entered into an instantaneous reboot, but without serial port, or jtag that'll be difficult to figure out which one

change handle_rdtsc https://github.com/cheat-engine/cheat-engine/blob/5a8cf16fe65e8b4a812bbfa1abaca82dfbcbfeab/dbvm/vmm/vmeventhandler.c#L3637

into:
```
int handle_rdtsc(pcpuinfo currentcpuinfo, VMRegisters *vmregisters)
{
  QWORD realtime=_rdtsc();
  vmregisters->rax=realtime & 0xffffffff;
  vmregisters->rdx=realtime >> 32;
  vmwrite(vm_guest_rip,vmread(vm_guest_rip)+vmread(vm_exit_instructionlength));

  RFLAGS flags;
  flags.value=vmread(vm_guest_rflags);

  if (flags.TF==1)
    vmwrite(vm_pending_debug_exceptions,0x4000);
}
```

and see if it still crashes (Do put the `#define TSCHOOK` line back)

**Comment by kitty8904** [comment]
[vmdiskpatch.zip](https://github.com/cheat-engine/cheat-engine/files/3098285/vmdiskpatch.zip)

okay 

int handle_rdtsc(pcpuinfo currentcpuinfo, VMRegisters *vmregisters)
{
  QWORD realtime=_rdtsc();
  vmregisters->rax=realtime & 0xffffffff;
  vmregisters->rdx=realtime >> 32;
  vmwrite(vm_guest_rip,vmread(vm_guest_rip)+vmread(vm_exit_instructionlength));

  RFLAGS flags;
  flags.value=vmread(vm_guest_rflags);

  if (flags.TF==1)
    vmwrite(vm_pending_debug_exceptions,0x4000);
}

DBVM is loaded without the pc stopping

DBVM loaded -> No Suspend PC

**Comment by cheat-engine** [comment]
Ok, undo that change and then try just removing the writeMSR line at https://github.com/cheat-engine/cheat-engine/blob/5a8cf16fe65e8b4a812bbfa1abaca82dfbcbfeab/dbvm/vmm/vmeventhandler.c#L3672

**Comment by kitty8904** [comment]
[vmdiskRemoveMSR.zip](https://github.com/cheat-engine/cheat-engine/files/3098295/vmdiskRemoveMSR.zip)

//writeMSR(0x838, readMSR(0x838));

OK writeMSR DELETE

DBVM LOAD -> NO SUSPEND PC

**Comment by cheat-engine** [comment]
ok, that was some testcode but not necessary
