### ISSUE TITLE
Global Debug question

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#637]
int debugger_stopDebugging(void)
{	
	if (DebuggerState.globalDebug)
	{
        forEachCpuPassive(debugger_touchDebugRegister, 0);
	}
}

forEachCpuPassive(debugger_touchDebugRegister, 0);  //Clean

1. Enable global debug check

2. Break pointer break at any address

3. AntiCheat Game Process Slow Loading

4.Driver Unload(forEachCpuPassive Call) -> Fast Game 

Using global debug slows you down somewhere

I do not know where to fix it

Something seems to be detecting or crashing

/////////////////////////////////////////////////////////

Or is it a global debug issue?

Unloading the drive will work quickly again

DBVM breakpoints are not slow

Only the global breakpoint is causing the problem

In all breakpoint access functions

Global Debug Breakpoints Only Slow
(Game Loading Slow)

**Comment by cheat-engine** [comment]
globaldebug will raise an interrupt every time a debugregister is accessed. That includes cpu context switches , so yes, can be a little slow

**Comment by kitty8904** [comment]
It's very slow

Debug Break Pointer is not hanging

1. Breakpoint access any process(No game ,Any Process)

2.Delete Breakpoint

3. Game Run -> Very slow loading(maybe anti cheat driver crash?)

4.Driver Unload -> Fast Load

////////////////////////////////////

You are not constantly hanging the breakpoint

Global debugging is very slow when loaded once

If you do not remove the global debug hooks, it is consistently slow

It's slow even without debugging. Something strange

**Comment by cheat-engine** [comment]
As I said, it's kinda normal.  When global debug is activated the driver will be doing what I call 'threadsurfing' , basically every time a threadcontextswitch happens, or the debug registers are accessed, it interrupts the CPU and goes to CE's interrupt1 handler, and code that sets all 6 debugregisters to 0 will run that handler 6 times, and that in combination with DBVM's interrupt1 hook as well, can likely cause a slowdown

Deleting a breakpoint doesn't stop the threadsurfing, it just tells it to stop setting the breakpoint when it encounters the target process while surfing. Only when the driver is unloaded it will force it to stop

**Comment by kitty8904** [comment]
Is there any solution?

DBVM breakpoint access is not slow

Global debugging fails to use F5 ~ F8 Trace function

Is there a solution?

It was so slow that I could not execute , so I asked

**Comment by cheat-engine** [comment]
DBVM breakpoints aren't slow, because they also don't send an interrupt or touch any debug register, they are memory based (even changeregonbp just uses a cloaked int3 bp)
They just collect data and continue, and no suspending of the target

I guess I could make these dbvm breakpoints emit an interrupt and then let ce's driver freeze them

**Comment by kitty8904** [comment]
If so, is it impossible to stop without unloading the drive?

DBKDebug_StopDebugging?

If debugging is not accessed, can pools be left in a stopped state to prevent slowdowns?

What about trying to stop threadsurfing when global debug is working and not debugging?

/////////////////////////////////////////////////////////////////////////////////////////////////////////////

What if you do not unload the drive and constantly read where it is called only at the time of the event?
(threadsurfing??)

**Comment by cheat-engine** [comment]
it is possible, butbthere is always a small chance of crashing when it gets disabled

also what addresses are you setting breakpoints on? because kernelmode addresses just won't break most of the time by design because the debugger can use that code as well and just freeze

**Comment by kitty8904** [comment]
Do not debug kernel-mode addresses

UserMode Client.exe Breakpoint Access

Used for F5 trace analysis or some pointer tracking

////////////////////////////////////////////////////////////

Or can you speed up with global debug source modification?

Modify the source of the kernel dbk driver debugger.c side?

I do not know

**Comment by kitty8904** [comment]
https://github.com/cheat-engine/cheat-engine/blob/master/DBKKernel/debugger.c#L1500

DebuggerState.FakedDebugRegisterState[cpunr()].inEpilogue=0;
DebuggerState.FakedDebugRegisterState[cpunr()].DR0 =  0;
DebuggerState.FakedDebugRegisterState[cpunr()].DR1 =  0;
DebuggerState.FakedDebugRegisterState[cpunr()].DR2 =  0;
DebuggerState.FakedDebugRegisterState[cpunr()].DR3 =  0;
DebuggerState.FakedDebugRegisterState[cpunr()].DR6 =  0;
DebuggerState.FakedDebugRegisterState[cpunr()].DR7 =  0;

Something is wrong, but initializing the value makes the anti-cheat process game load faster(?)

////////////////////////////

//DebuggerState.FakedDebugRegisterState[cpunr()].inEpilogue=0;
//if (!DebuggerState.stoppingTheDebugger)
//debugger_dr7_setGD(DebuggerState.globalDebug); //set it back to 1, if not unloading

Or is the code related to global debug persistence?

Debugger.c Deleting the code will speed up the game loading. Do you read anything in Anti cheat? Or optimization?

I'm sad not knowing much about the kernel

**Comment by cheat-engine** [comment]
perhaps https://github.com/cheat-engine/cheat-engine/blob/3d4ad6ab32f741de448ac9be14486f3624358af1/DBKKernel/debugger.c#L956
it's possible it changes a bit that can't be changed mormslly

**Comment by kitty8904** [comment]
gpvalue = 0;//f0401;

That's right. There's anti-cheat + themida VM Packer detects it.

If you set the address to 0, you can bypass anti-cheat

anti cheat detected gpvalue values

/////////////////////////////////////////////////////////////////////////////////////

There is also a that slows down regardless of its value correction
(game loading speed)

Compared, games without anti-cheat are not Very slow

Game with anti-cheat loading very slow

**Comment by cheat-engine** [comment]
0x23 is the write instruction, it's where ce gets the original value to show 

anyhow try uncommenting 
https://github.com/cheat-engine/cheat-engine/blob/3d4ad6ab32f741de448ac9be14486f3624358af1/DBKKernel/debugger.c#L813

perhaps the dr6 value messed up

**Comment by kitty8904** [comment]
dr6 value?

debugger_dr6_setValue(*(UINT_PTR *)&_dr6); -> //debugger_dr6_setValue(*(UINT_PTR *)&_dr6);

uncommenting -> apc index mismatch BSOD

Everything else is uncommenting

It is still slow

I want to solve it, but I'm sad because I do not know programming.

**Comment by cheat-engine** [comment]
you have the line
//DebuggerState.FakedDebugRegisterState[cpunr()].DR6=*(UINT_PTR *)&_dr6; 

change it to
DebuggerState.FakedDebugRegisterState[cpunr()].DR6=*(UINT_PTR *)&_dr6;

**Comment by kitty8904** [comment]
There is no speed up

I want to tell you the name of the game, but it's illegal, so it's hard to ask

Apparently somewhere detect

If there is no anti-cheat, the speed difference will not slow down significantly

I want to fix it myself, but it's difficult

**Comment by cheat-engine** [comment]
perhaps it uses a driver to access debug registers in a very long loop.
when gd is set this will cause it to take very long. (500+ instructions per access instead of just 1) so that loop will take 500 times longer than normal

it's likely similar to how rdtsc could be used to detect dbvm before ver 13
problen is that this debug implementation is not inside dbvm

**Comment by kitty8904** [comment]
void debugger_dr0_setValue(UINT_PTR value)
{
	__writedr(0, 0);
	//__writedr(0, value);
}

UINT_PTR debugger_dr0_getValue(void)
{
	return __readdr(0);
}

void debugger_dr1_setValue(UINT_PTR value)
{
	__writedr(1, 0);
}

UINT_PTR debugger_dr1_getValue(void)
{
	return __readdr(1);
}

void debugger_dr2_setValue(UINT_PTR value)
{
	__writedr(2, 0);
}

UINT_PTR debugger_dr2_getValue(void)
{
	return __readdr(2);
}

void debugger_dr3_setValue(UINT_PTR value)
{
	__writedr(3, 0);
}

UINT_PTR debugger_dr3_getValue(void)
{
	return __readdr(3);
}

void debugger_dr6_setValue(UINT_PTR value)
{
	__writedr(6, 0);
}

void debugger_dr7_setValue(DebugReg7 value)
{
	UINT_PTR temp = *(UINT_PTR *)&value;
	__writedr(7, temp);
	//__writedr(7, 0);
}

void debugger_dr7_setValueDword(UINT_PTR value)
{
	__writedr(7, 0);
}


my test flag detect crash

dr7

https://github.com/cheat-engine/cheat-engine/blob/master/DBKKernel/debugger.c#L138


__writedr(7, temp); -> __writedr(7, 0);

The global debug deceleration cause flag is DR7

If DR7 value is set to 0, no debug value is output, but there is no speed deceleration

What does DR7 have on global debugging?

If DR7 value is set to 0, no speed deceleration will occur

**Comment by cheat-engine** [comment]
dr7 contains the GD (global debug) flag.
Once set every single access to any DR flag will cause a debug interrupt. 

if you set it to 0 no interrupts happen when something accesses it

**Comment by kitty8904** [comment]
DR7 value

0xF0401
0xF2401
0x400
0x2400
0x0

Can not be modified with global debugable values?

Is it useless to modify the values?

I do not know..

**Comment by cheat-engine** [comment]
I have no idea what you mean with those values, but if you set gpvalue to gpvalue=(gpvalue | 0x400) & (~(1<<13));  instead of 0 everything should look ok
