### ISSUE TITLE
AA generates unwanted multibyte NOPs

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#640]
Compiled latest source and noticed AA now generates multibyte NOPs instead of single. Is this supposed to happen? 

![image](https://user-images.githubusercontent.com/14368203/56469709-b59fd400-642c-11e9-848e-1ece9c78b9fb.png)

**Comment by cheat-engine** [comment]
it's supposed to happen like that yes.  It creates shorter/very slightly faster code

otherwise it would have created
```
jne 0fad001a
nop
nop
nop
nop
pop esi
ret 24
```
