### ISSUE TITLE
Check box saying "open" is not appearing

### ISSUE THREAD

**Issue by crispyrice758** [cheat-engine/cheat-engine#641]
Ive tried to download each version of the engine and none of them have the "open" with the check box. i would appreciate details and lots of help on figuring out what to do to fix the issue.

**Comment by cheat-engine** [comment]
we also need details.
like what are you trying to do ?

**Comment by crispyrice758** [comment]
![image](https://user-images.githubusercontent.com/49889277/56626351-f6534500-6606-11e9-9a63-dcd4af21bbae.png)

**Comment by crispyrice758** [comment]
normally when i open it up i see a checkbox in the "active" area and text saying "open" in the description area that opens up a range of stuff for ds3. but now there isn't. i don't know what to do or where to go to get the right one.

**Comment by cheat-engine** [comment]
you need to load a cheattable first
