### ISSUE TITLE
Question about lua's registersymbol

### ISSUE THREAD

**Issue by KenjiroIchise** [cheat-engine/cheat-engine#649]
I think it would be useful if the results of analysis with static analysis tools such as ghidra could be mapped to CheatEngine. Although it is possible at present, using a lot of registerSymbol and setHeader will take time to process. Is it possible to speed up this?

**Comment by cheat-engine** [comment]
you can use registerSymbolLookupCallback and registerAddressLookupCallback to insert your own lookup code
