### ISSUE TITLE
Cheat-Engine working on earlier versions

### ISSUE THREAD

**Issue by LilLizardHD** [cheat-engine/cheat-engine#657]
Cheat Engine version 6.8.3  doesn't allow the program to start up, I've tried Cheat engine 6.4, 6.5 and they work fine, any up from that don't boot I've looked at Git hub for solutions but none work, it could be how its been coded, I don't know but earlier versions work the latest version doesn't.

**Comment by cheat-engine** [comment]
https://github.com/cheat-engine/cheat-engine/issues/571

get rid of badlion

**Comment by sammylongnose360** [comment]
> #571
> 
> get rid of badlion
> 
> and if that's not it then check your anti virus
what is get rid of badlion  explain it pls
