### ISSUE TITLE
cheat engine lazarus new version 1.6 fpc 3.0.0 compile error

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#66]
cheat engine source fpc 2.7.1 not error

but new lazarus 1.6 fpc 3.0.0 compile networkinterface compile error

lazarus fpc bug ? 

cheat engine source bug?

How do I fix a bug ?

![error](https://cloud.githubusercontent.com/assets/18622105/14755334/7c6e79ac-091c-11e6-83c2-4f29c1944105.png)

**Comment by mgrinzPlayer** [comment]
You need FPC revision 27759 and Lazarus revision 44997. Then compile CE with it.


Or change to:
```Pascal
  SockAddr.sin_Family := AF_INET;
  SockAddr.sin_Port := port;
  SockAddr.sin_Addr.s_addr := host.s_addr;
```

Note: lazarus 1.6 has ugly bug, you will see it in main CE window, foundlist will blink.

**Comment by kainpark7894** [comment]
thank you no problem resolve

CE foundlist will blink FPC bug?

or foundlist option change?

**Comment by kitty8904** [comment]
thankyou resolve

CE foundlist will blink bug lazarus 1.6bug  fpc 2.7.1 back?

foundlist option change?

**Comment by mgrinzPlayer** [comment]
I think this bug is Lazarus1.6 thing (not FPC thing).

**Comment by kitty8904** [comment]
lazarus 1.6 fix version not fpcup.exe?

cheat engine setting Found addess list update interval 100,50,10 interval speed ->Found list blink speed

How do I fix ?

Lazarus impossible to solve until update?

lazarus old version compile not bug 

new lazarus 1.7 version wait?

**Comment by kitty8904** [comment]
cheat engine blink bug solve

https://github.com/cheat-engine/cheat-engine/commit/10fc7d5dbe7cfa69f10a34c32fcaf33c0951780c

win32callback.zip change:

https://github.com/cheat-engine/cheat-engine/files/241598/win32callback.zip

close issues
