### ISSUE TITLE
Stealth Driver Support

### ISSUE THREAD

**Issue by DKingCN** [cheat-engine/cheat-engine#661]
Hi, recently I did some work about manual mapped driver support and shared mem I/O, and I am willing to port it to cheat engine. Is DB interested in this feature?

Basically it's to manual map the driver into kernel (i personally use blackbone to do that), and communicate via shared memory object.  This method can be hard to detect because no driver object is ever created except a stupid system thread running in the middle of nowhere of kernel space, with some extra global named objects (shared mem obj & events).

I havent look into the code of cheat engine communication part but I suppose it wont be of much work to integrate the new feature into original I/O handling.

**Comment by cheat-engine** [comment]
ce already has manual driver mapping. loadModule will load modules in kernelmode if it's a .sys extension

and dbk can be controlled using DispatchIoctlDBVM then

**Comment by DKingCN** [comment]
awesome. thanks for the great work.
