### ISSUE TITLE
PrivateBuild makes pointer 4byte

### ISSUE THREAD

**Issue by DKingCN** [cheat-engine/cheat-engine#668]
Hi, something in `privatebuild` section makes all pointer types in cheat engine 4bytes. (found by building with/without this option and try to read a 64bit pointer in CE). I searched this definition but the sources all looks fine(ptruint, 8). Any ideas?

**Comment by DKingCN** [comment]
when `privatebuild ` enabled, in `addresslist.pas`, `TAddresslist.addaddress`, 
```processhandler.is64Bit```
 is false for a 64bit process.

Its not only when add address, but also other ocassions like in structure window, pointer is also 8bytes.

**Comment by DKingCN** [comment]
Reason found(unsolved). I set the option `try not to obtain handles`, that makes `processhandler.is64Bit` returns FALSE.

**Comment by DKingCN** [comment]
well. I made a temp fix at NewKernelHandler.pas `Is64BitProcess`:
```
  {$ifdef privatebuild}
    if (processhandle=0) and DoNotOpenProcessHandles then
    begin    {we dont even have a handle, guess by CE's arch}
    {$ifdef cpu64}
      exit(true);
    {$else}
      exit(false);
    {$endif}
    end;
  {$endif}        
```
Inserted this at the very begining of `{$ifdef windows} ` section. Now it works great.

Feel free to close the issue when you done reading or patch it with the code.

**Comment by cheat-engine** [comment]
run this lua code after opening a process
[code]
setPointerSize(8)
setAssemblerMode(1)
[/code]
but only if you're sure the target is 64 bit

**Comment by DKingCN** [comment]
great to know. thanks.
