### ISSUE TITLE
Failure determining what XYZ means

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#669]
1. Attach to Explorer.exe
2. Open memory viewer and replace Explorer.exe+XXX with nothing (add to codelist)
3. Launch notepad.exe and attach to it
4. Open memory viewer and try to replace notepad.exe+XXX with nothing
5. Receive error

![ezgif com-optimize](https://user-images.githubusercontent.com/14368203/57256801-21965500-7047-11e9-952c-84ee70f8dd9f.gif)

**Comment by cheat-engine** [comment]
fixed
