### ISSUE TITLE
I cant open it in 6.8.3

### ISSUE THREAD

**Issue by sammylongnose360** [cheat-engine/cheat-engine#675]

**Comment by supMarco** [comment]
get rid of badlion / check your antivirus

**Comment by sammylongnose360** [comment]
what is get rid of badlion

**Comment by sammylongnose360** [comment]
and i closed my antivirus windows defender but not working

**Comment by sammylongnose360** [comment]
> get rid of badlion / check your antivirus

what is get rid of badlion

**Comment by cheat-engine** [comment]
Go to "Add or remove software" and in that list search for anything with the text badlion.
Then uninstall that and when all are gone, restart your computer (actual restart, not shut down and back on, windows 10 fakes that)
