### ISSUE TITLE
Not working in Windows 10 May update

### ISSUE THREAD

**Issue by sonphanusa** [cheat-engine/cheat-engine#676]
Not working in Windows 10 May update 1903 18362, can't enable scripts

**Comment by sammylongnose360** [comment]
what is get rid of badlion can you explain me

**Comment by cheat-engine** [comment]
Perhaps the game itself updated as well

**Comment by sonphanusa** [comment]
you're right it's the game, just happened the two i tried were both diff versions. try another older game and it worked. closing ticket
