### ISSUE TITLE
Late evaluation in address calculation

### ISSUE THREAD

**Issue by Neutron3529** [cheat-engine/cheat-engine#689]
I am struggled in a problem described below, I tried to use the CheatEntries below but it does not what I want. It may due to the (late?) evaluation.

CE version: 6.8.3
Note: The game, has its own value type, called AGE(<CustomType>AGE</CustomType>), but it may work fine with a normal 4 bytes type.

character skills in the game are stored in `[[[AGE_cn.exe+2D663C]+6A344]+479C54+character_ID*FA0+skill_ID*4]`, I want to store character's ID in `myoffset` so that I could modified it easily, and for each skill (about 100), I could list them seperately.
The question is, when I use such address:
```
      <Address>AGE_cn.exe+2D663C</Address>
      <Offsets>
        <Offset>479C54+[myoffset]*FA0+C</Offset>
        <Offset>6A344</Offset>
      </Offsets>
```
when I modified the value in `myoffset`, the address CE calculated does not change, only if I calculate the address manually(open it and confirm it) will the address change.

![图片](https://user-images.githubusercontent.com/26130174/57800599-595a7680-7784-11e9-945e-c4f9876405dc.png)
1: "myoffset"
2:the address I calculated manually
3:other address, the calculation of 2 and 3 is nearly the same(except the final offset related to skill ID)
I want to know what I could do to archieve a real-time address evaluation.
Thanks.

address calculation step:
1:open it
2:confirm
![图片](https://user-images.githubusercontent.com/26130174/57800903-177e0000-7785-11e9-83ce-a696e36ed5b0.png)
and we could see the address has really changed.
![图片](https://user-images.githubusercontent.com/26130174/57800920-2664b280-7785-11e9-8eae-6c37ff3cefd5.png)

Full CheatEntry is shown below:
```
<?xml version="1.0" encoding="utf-8"?>
<CheatTable>
  <CheatEntries>
    <CheatEntry>
      <ID>824</ID>
      <Description>"*chinese*"</Description>
      <LastState Value="0" RealAddress="3E48A850"/>
      <VariableType>Custom</VariableType>
      <CustomType>AGE</CustomType>
      <Address>AGE_cn.exe+2D663C</Address>
      <Offsets>
        <Offset>479C54+[myoffset]*FA0+C</Offset>
        <Offset>6A344</Offset>
      </Offsets>
    </CheatEntry>
  </CheatEntries>
</CheatTable>
```

**Comment by cheat-engine** [comment]
rightclick the offset with the [myoffset] code and choose an update method.  I recommend timer interval
