### ISSUE TITLE
Assembler error: vmaskmovps

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#696]
CE fails to assemble `vmaskmovps ymm1,ymm0,[rdi] // C4 E2 7D 2C 0F 00` but disassembles it

![image](https://user-images.githubusercontent.com/14368203/57932587-c49e6880-78aa-11e9-9171-5f935e436bc7.png)

**Comment by cheat-engine** [comment]
should be fixed

**Comment by Symbai** [comment]
Thanks, works now
