### ISSUE TITLE
Assemble generates wrong bytes

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#697]
In CE the following instruction
`vmaskmovps ymm1,ymm0,[rdi] `
generates
`C4 E2 FD 2C 0F 00`
but according to multiple online tools this is wrong (i.e. they cannot disassemble the byte array). Instead they generate this:
`C4 E2 7D 2C 0F`

Tried:
https://defuse.ca/online-x86-assembler.htm
https://onlinedisassembler.com/odaweb/

**Comment by cheat-engine** [comment]
should be fixed now
