### ISSUE TITLE
A new bug about createHotkey()

### ISSUE THREAD

**Issue by lenct** [cheat-engine/cheat-engine#701]
![image](https://user-images.githubusercontent.com/44138520/57978911-41b31480-7a48-11e9-8c33-706c288bc170.png)
A new bug about createHotkey()
Write such a Lua script into the automatic assembly script, but the CE gets stuck when you set the keys.

**Comment by lenct** [comment]
![image](https://user-images.githubusercontent.com/44138520/57978957-f77e6300-7a48-11e9-8672-12704f4df837.png)

Click OK and press HOME key CE without response

**Comment by wangyujie96** [comment]
insert “{$asm}” befor “[DISABLE]”.

**Comment by lenct** [comment]
> insert “{$asm}” befor “[DISABLE]”.


But this is not the main reason, the main reason is not in the "button" create new "buttons" message in the message

**Comment by cheat-engine** [comment]
should be fixed now
