### ISSUE TITLE
aboat new version spawn diagram

### ISSUE THREAD

**Issue by lenct** [cheat-engine/cheat-engine#702]
![image](https://user-images.githubusercontent.com/44138520/57980362-58179b00-7a5d-11e9-92ee-479a8bb8826f.png)
![image](https://user-images.githubusercontent.com/44138520/57980390-ab89e900-7a5d-11e9-9c27-7c47c562a780.png)

**Comment by supMarco** [comment]
yeah, that's still under under development :P (will push an update by end of day)

**Comment by lenct** [comment]
Okay, this function looks really great. It adds a lot of charm to CE.

**Comment by cheat-engine** [comment]
the function is mostly done. Now testing can begin
