### ISSUE TITLE
Error when building ceserver

### ISSUE THREAD

**Issue by KenjiroIchise** [cheat-engine/cheat-engine#706]
When I build ceserver in AndroidStudio, some errors appear. Is it possible to fix this?

(1)
jni / api.c: 2123: 21: error: fields must have a constant size: 'variable length array in structure' extension will never be supported
      unsigned char data [size]; // not sure if this works. need testing

Is it possible to build in Eclipse? Is it possible to not use VLAIS so that it can be build by Android Studio?

(2)
jni / api.c: 2643: error: undefined reference to 'index'
jni / api.c: 2653: error: undefined reference to 'index'
jni / api.c: 2658: error: undefined reference to 'index'
jni / api.c: 2653: error: undefined reference to 'index'

This seems like an essential mistake.

(3) The build also passes, but if it is not fixed as follows, it will crash at breakpoint setting.

jni / api.c; 1815-
IP = ptrace (PTRACE_PEEKUSER, p-> debuggedThreadEvent.threadid, offsetof (struct user, regs.eip), 0);
....

=>
IP = ptrace (PTRACE_PEEKUSER, (int) p-> debuggedThreadEvent.threadid, offsetof (struct user, regs.eip), 0);

Is this caused by a type mismatch caused by defining threadid with int64_t?

**Comment by cheat-engine** [comment]
1: It's valid in eclipse with the compiler used there
2: it's valid http://man7.org/linux/man-pages/man3/index.3.html  (include strings.h)
3: While you do compile ceserver to x86-bit, is the system you're debugging on x86?  Because if the target is in ARM and it's running ceserver in an x86 container, then the size of the debug information can be quite different)
and threadid being int64_t doesn't matter as it's a direct variable and not a reference var

**Comment by KenjiroIchise** [comment]
I want to be able to build AndroidStudio as it is.
1:Please do not use VLAIS. Perhaps clang does not allow VLAIS.
Is there a problem with the code below?

#pragma pack (1)
    struct
    {
      uint8_t command; // 1
      uint32_t pHandle; // 5
      uint64_t address; // 13
      uint32_t size; // 17
    } wpm;
#pragma pack ()
    unsigned char data [size];
 .....
      sendall (p-> debuggerClient, & wpm, sizeof (wpm), 0);
      sendall (p-> debuggerClient, & data, size, 0);

2:index => strchr
http://man7.org/linux/man-pages/man3/index.3.html
--------
recommending strchr (3) and
       strrchr (3) instead.

**Comment by oahzuw** [comment]
I want to know the build step for ceserver !

**Comment by KenjiroIchise** [comment]
It can be built by the usual build method of Android Studio.
