### ISSUE TITLE
x64 0F 0D OpCode Dissembler Error?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#71]
![view](https://cloud.githubusercontent.com/assets/18622105/15344982/2178617e-1ce6-11e6-915a-566905a4c389.png)

FFFFF8000207ED0E - 0F                    -  
FFFFF8000207ED0F - 0D 4B38488B           - or eax,8B48384B { -1958201269 }
FFFFF8000207ED14 - 43 38 48 83           - cmp [r8-7D],cl
FFFFF8000207ED18 - E0 FE                 - loopne FFFFF8000207ED18
FFFFF8000207ED1A - 48 8D 48 02           - lea rcx,[rax+02]
FFFFF8000207ED1E - F0 48 0FB1 4B 38      - cmpxchg [rbx+38],rcx
FFFFF8000207ED24 - 74 11                 - je FFFFF8000207ED37
FFFFF8000207ED26 - 48 8D 4B 38           - lea rcx,[rbx+38]
FFFFF8000207ED2A - E8 F545C7FF           - call FFFFF80001CF3324
FFFFF8000207ED2F - 84 C0                 - test al,al
FFFFF8000207ED31 - 0F84 18010000         - je FFFFF8000207EE4F
FFFFF8000207ED37 - 0F                    -  
FFFFF8000207ED38 - 0D 0E488B06           - or eax,68B480E { 109791246 }
FFFFF8000207ED3D - 48 8B C8              - mov rcx,rax
FFFFF8000207ED40 - 48 83 E1 F0           - and rcx,-10 { 240 }
FFFFF8000207ED44 - 48 83 F9 10           - cmp rcx,10 { 16 }
FFFFF8000207ED48 - 76 06                 - jna FFFFF8000207ED50
FFFFF8000207ED4A - 48 8D 48 F0           - lea rcx,[rax-10]
FFFFF8000207ED4E - EB 02                 - jmp FFFFF8000207ED52

x64 Memory View OF 0D 

OPCODE Dissembler View error?
FFFFF8000207ED37-3C or eax,68B480E

Go To the Address FFFFF8000207ED3A ->  mov rax,[rsi]

**Comment by Sn34kyMofo** [comment]
Something like this happened to me in a game the other day. The moment I
started scrolling through the disassembler, everything changed.
AutoAssembler noted something around the code snippet about adding a byte
for some reason (I don't quite recall). I can try to repro if need be.

**Comment by kitty8904** [comment]
![x64dbg](https://cloud.githubusercontent.com/assets/18622105/15345933/2e931dce-1cee-11e6-8b32-529144679a63.png)

x64dbg dissembler

prefetchw byte ptr [rax + 0x38] <-0F 0D 4B 38
mov rax, qword ptr [rbx + 0x38]

prefetchw byte ptr [rsi] <-0F 0D 0E
mov rax, qword ptr [rsi]
mov rcx, rax

prefetchw view dissembler code add?

**Comment by cheat-engine** [comment]
fixed
