### ISSUE TITLE
19H1 Kernel NOT ReadMemory 

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#710]
compile error
function diagramBlock_intersectsWithLine(L: PLua_state): integer; cdecl;

B1 No Class 
b1:=luaclass_getClassObject(L);

////////////////////////////////////////////////////////////////
//Kernel 19H1 Kernel Read BUG//

cpustate = ExAllocatePoolWithTag(NonPagedPool, MaxCPUCount*sizeof(CPUSTATE), 0);

cpustate = ExAllocatePool(NonPagedPool, MaxCPUCount * sizeof(CPUSTATE));

FIX ExAllocatePoolWithTag

/////////////////////////////////////////////////////////////////////////////////

Starting from Windows 19H1, if the pool tag is 0, it can not be read

If the pool tag value is 0, kernel memory read is not possible

**Comment by kitty8904** [comment]
Much of the cheat engine is zero (0) as shown below

ExAllocatePoolWithTag (NonPagedPool, Ultimap2CpuCount * sizeof (PProcessorInfo), 0);
Ultimap2_DataReady = ExAllocatePoolWithTag(NonPagedPool, Ultimap2CpuCount*sizeof(PVOID), 0);
PInfo[i] = ExAllocatePoolWithTag(NonPagedPool, sizeof(ProcessorInfo),0);
return ExAllocatePoolWithTag(NonPagedPool, ByteSize, 0);
r = ExAllocatePoolWithTag(NonPagedPool, 4096, 0);
*OutputBuffer = ExAllocatePoolWithTag(NonPagedPool, _BufferSize, 0);
r = ExAllocatePoolWithTag(NonPagedPool, getToPAHeaderSize(_BufferSize), 0);
*gt=ExAllocatePoolWithTag(NonPagedPool, sizeof(RTL_GENERIC_TABLE), 0);
Ultimap2Ranges = ExAllocatePoolWithTag(NonPagedPool, rangeCount*sizeof(URANGE), 0);

//////////////////////////////////////////////////////////////////////////////////////////////

Beginning with windows version 19H1, the pool tag zero value is not available

Do you need to modify all sections?

Zero tag impossible

ExAllocatePoolWithTag -> ExAllocatePool => ALLFIX?

ExFreePoolWithTag ->ExFreePool => ALLFIX?

and detect tag add?

You can add tags, but the tags are detected as full tag scans(anti cheat)

**Comment by cheat-engine** [comment]
Use ExAllocatePool instead

and wait till official releases. When many systems BSOD because of this they may add in compatibility for older drivers. So build and sign them now

**Comment by kitty8904** [comment]
19H1 is officially released at the end of May

Why did Microsoft disable tag zero

This is a bug in which you can patch compatibility but do not understand

ExAllocatePool and ExAllocatePoolwithtag 

Just the difference in tags?

There is no difference in function as far as I know

I will write again when the 19H1 is officially released
