### ISSUE TITLE
peinfo_is64bitfile ,There are some wrong results .

### ISSUE THREAD

**Issue by xunni1000** [cheat-engine/cheat-engine#711]
Hello,

I used your peinfo_is64bitfile function in Delphi ,There are some wrong results .

file:
https://github.com/2dust/v2rayN/releases/download/2.29/v2rayN.zip
Inside the v2rayN.exe file.

This is a 64-bit program file. 
It's also 64-bit in TaskMgr platform properties.

But the return by peinfo_is64bitfile is false.

ImageNTHeader^.FileHeader.Machine = $‭14C‬
NOT
ImageNTHeader^.FileHeader.Machine = $8664

This is a rare case, but it's very important to me. Please help me. Thank you.

**Comment by cheat-engine** [comment]
This is a .net file.
The launching stub is 32-bit but windows will load and compile it into the native system architecture

**Comment by xunni1000** [comment]
Thank you, I'm trying to use IsWow64Process now.
