### ISSUE TITLE
19H1 Release

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#712]
19H1 has been officially released

Currently the latest version is probably not the pooltag revision(ExAllocatePoolWithTag)

issue a patch from Microsoft?(ExAllocatePoolWithTag zero -> No Created alloc memory)

Do you just modify the source?

It's not a big problem

/////////////

Or is it something I know wrong?

Kernel memory viewer not validated(no readprocessmemory)

**Comment by cheat-engine** [comment]
Perhaps they just changed the wdk to give an error, but older wdks will be unaffected
