### ISSUE TITLE
driver hide Question

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#713]
Recently I learned the Driver ManualMap injection while studying the kernel

Cheat engine driver also succeeded in manual mapping injection

But blue screen occurs after 1HR ~ 3HR

======================================

event view log ->bug 109 (patchguard detect!)

1.PLOAD_IMAGE_NOTIFY_ROUTINE(Disable process watch function)
2.try except(ManualMap Driver No Support) -> MmCopyVirtualMemory Changed

pssetloadimagenotifyroutine

https://github.com/hfiref0x/UPGDSED/blob/master/src/tests/BadRkDemo/drv/dummy/main.c#L178

Allocate nonpaged executable pool and use it as LoadImageNotifyRoutine code

======================================

The Cheat Engine, however, did not use the LoadImageNotifyRoutine function(disabled process watch)

Do functions like the LoadImageNotifyRoutine function work in the Cheat Engine? Cause of patch guard
I do not know where

It is not a driver signing issue either(No dsefix)

I do not know the function that causes conflict with the patch guard in the cheat engine source

======================================

A simple source, not a cheat engine, does not have a blue screen

**Comment by kitty8904** [comment]
1.It is not a normal driver
2.No psloadedmodulelist (manualmap injection)

Patchguard detects manual mapping injected cheat engine driver

I do not know why

**Comment by cheat-engine** [comment]
what are the other fields of the bsod message?
 they indicate which field got modified

and have you tried loading ce's driver and not using it for anything and wait 3 hours also bsod?
how about the simple driver. did you wait 3 hours as well?

**Comment by kitty8904** [comment]
+ System 

  - Provider 

   [ Name]  Microsoft-Windows-WER-SystemErrorReporting 
   [ Guid]  {ABCE23E7-DE45-4366-8631-84FA6C525952} 
   [ EventSourceName]  BugCheck 
 
  - EventID 1001 

   [ Qualifiers]  16384 
 
   Version 0 
 
   Level 2 
 
   Task 0 
 
   Opcode 0 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2019-05-25T06:01:22.617174300Z 
 
   EventRecordID 12753 
 
   Correlation 
 
  - Execution 

   [ ProcessID]  0 
   [ ThreadID]  0 
 
   Channel System 
 
   Computer DESKTOP-UPS51S9 
 
   Security 
 

- EventData 

  param1 0x00000109 (0xa3a025dc8de1473d, 0xb3b73262e06376a5, 0xffffe6840318a080, 0x000000000000001b) 
  param2 C:\Windows\MEMORY.DMP 
  param3 1ad7ce2c-2b9d-4c4e-8dff-5c119720950c 


===============================================

Time is blue screen randomly within 2 ~ 5 hours

IoCreateDevice for simple drivers IoCreateSymbolicLink not used

For modulated cheat engines, create a new drive object

ntStatus = IoCreateDriver(&NULL_FakeDrv, &RealDriver_Initialize);

NTSTATUS RealDriver_Initialize(PDRIVER_OBJECT DriverObject, PUNICODE_STRING RegistryPath)
{
	NTSTATUS        ntStatus;
	PDEVICE_OBJECT  pDeviceObject = NULL;
	WORD this_cs, this_ss, this_ds, this_es, this_fs, this_gs;
	ULONG cr4reg;
	UNICODE_STRING	temp;
	HANDLE Ultimap2Handle;
	DbgPrint("RealDriver_Object=%p\n", DriverObject);

	char wbuf[100];

	KernelCodeStepping = 0;
	KernelWritesIgnoreWP = 0;
	
	this_cs = getCS();
	this_ss = getSS();
	this_ds = getDS();
	this_es = getES();
	this_fs = getFS();
	this_gs = getGS();

	temp.Buffer = (PWCH)wbuf;
	temp.Length = 0;
	temp.MaximumLength = 100;
	
	if (!loadedbydbvm)
	{
		// Point uszDriverString at the driver name
		// Create and initialize device object

		//DbgPrint("uszDriverString=%S\n", uszDriverString.Buffer);
		//DbgPrint("uszDeviceString=%S\n", uszDeviceString.Buffer);

		ntStatus = IoCreateDevice(DriverObject,0,&uszDriverString,FILE_DEVICE_UNKNOWN, FILE_DEVICE_SECURE_OPEN,FALSE,&pDeviceObject);

		if (ntStatus != STATUS_SUCCESS)
		{
			//DbgPrint("IoCreateDevice failed\n");
			
			//ExFreePool(BufDriverString);
			//ExFreePool(BufDeviceString);
			//ExFreePool(BufProcessEventString);
			//ExFreePool(BufThreadEventString);

			return ntStatus;
		}

		//RtlInitUnicodeString(&uszDeviceString, L"\\DosDevices\\1");

		// Create symbolic link to the user-visible name
		ntStatus = IoCreateSymbolicLink(&uszDeviceString, &uszDriverString);

		if (ntStatus != STATUS_SUCCESS)
		{
			//DbgPrint("IoCreateSymbolicLink failed: %x\n", ntStatus);
			
			//Delete device object if not successful
			IoDeleteDevice(pDeviceObject);

			//ExFreePool(BufDriverString);
			//ExFreePool(BufDeviceString);
			//ExFreePool(BufProcessEventString);
			//ExFreePool(BufThreadEventString);
			return ntStatus;
		}
	}

	//Load structure to point to IRP handlers...
	//DriverObject->DriverUnload = UnloadDriver;
	//DbgPrint("DriverObject=%p\n", DriverObject);

	DriverObject->MajorFunction[IRP_MJ_CREATE] = DispatchCreate;
	DriverObject->MajorFunction[IRP_MJ_CLOSE] = DispatchClose;

	if (loadedbydbvm)
	{
		DriverObject->MajorFunction[IRP_MJ_DEVICE_CONTROL] = (PDRIVER_DISPATCH)DispatchIoctlDBVM;
	}
	else
	{
		DriverObject->MajorFunction[IRP_MJ_DEVICE_CONTROL] = DispatchIoctl;
	}

	pDeviceObject->Flags |= DO_BUFFERED_IO;
	pDeviceObject->Flags &= ~DO_DEVICE_INITIALIZING;
}


===============================================

https://github.com/hfiref0x/TDL/blob/master/Source/DummyDrv2/dummy/main.c#L283


Changed driver structure by TDL load method

When loading TDL dummy driver -> No blue screen (wait for time)

Cheat Engine Modulation Driver Loading -> Blue Screen Occurs (wait for time)

**Comment by kitty8904** [comment]
Select Cheat Engine Self-Process and do nothing after 1 search

**Comment by kitty8904** [comment]
https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x109---critical-structure-corruption


0x1B | Type 4 process list corruption
-- | --


Why is the process list corrupted?

psloadedmodulelist ??

**Comment by kitty8904** [comment]
https://github.com/DarthTon/Blackbone/issues/351

Remove handle link -> Patch guard error (RS3 ~ 19H1)

Removing and testing the handle works fine(No Bsod kernel manual mappping driver)

However, some anti-cheats check the list of handle tables

Is there a way around this?
