### ISSUE TITLE
DBVM Not Supported on i9-7900X

### ISSUE THREAD

**Issue by rsk1588** [cheat-engine/cheat-engine#721]
Hi, 

I've disabled secure boot and driver signature enforcement, but DBVM refuses to work on my processor i9-7900X.

I've tried various things to get it working, re-enabling and disabling, checked and double checked bcdedit for integrity checks, BIOS tweaks, but I don't appear to be able to get it to work.

Is this processor supported?

R

**Comment by cheat-engine** [comment]
The cpu is supported, but what error message do you get when you try to launch dbvm ? Complete freeze? BSOD with clock timeout

**Comment by rsk1588** [comment]
"Your cpu must be able to run dbvm to use this function".

**Comment by rsk1588** [comment]
I'm using the official release 6.8.3, not a self compiled.
When I click on the red text, I get a BSOD
"The computer has rebooted from a bugcheck.  The bugcheck was: 0x000000e1"
WORKER_THREAD_RETURNED_AT_BAD_IRQL

**Comment by cheat-engine** [comment]
when you open the about screen, does it say "your system supports dbvm" in green or "your system does not support dbvm"

if the second, check your windows security settings and disable all features related virtualization and hypervisors

**Comment by Nightshades1** [comment]
@cheat-engine Hello my little poney :heart_eyes: , He also use Hyper-V which is the reason that in About->Help dbvm is not supported ?

**Comment by rsk1588** [comment]
Issue was caused by having Hyper-V windows feature installed.
