### ISSUE TITLE
ultimap2 cause BSOD on win10 1903

### ISSUE THREAD

**Issue by CIO-REMILIA** [cheat-engine/cheat-engine#722]
seems it can't be loaded after the new windows builds.

**Comment by cheat-engine** [comment]
post a memory.dmp or else a smaller crashdump so i can check it out

**Comment by CIO-REMILIA** [comment]
sorry, i have test for three times, but every time BSOD, the process stuck 0%. and there is no dmp file created.
in the ultimap2, press record button can cause BSOD.
![IMG_0080](https://user-images.githubusercontent.com/36498050/58473511-58114c80-817b-11e9-8be1-fd27c18d271c.JPG)

**Comment by cheat-engine** [comment]
my test systems can't seem to get this version yet. They always rollback with an error.

have you waited 2 hours? perhaps it's just extremely slow

**Comment by CIO-REMILIA** [comment]
i only wait for 3~5 minutes last time, it still in 0%. and no working noise, (its dead, fan speed very low)
normally bsod wont have this stuck, the first time i see.
i try to change the dump file type, but it still stuck in 0%.
![image](https://user-images.githubusercontent.com/36498050/58494296-5eb5b900-81a7-11e9-9ec5-1a989bb54f48.png)

**Comment by cheat-engine** [comment]
Should be fixed now

You'll currently have to build the driver AND Cheat Engine as well, as the parameter passing has changed for some new features

**Comment by CIO-REMILIA** [comment]
oh, it works now, thank you!
