### ISSUE TITLE
tableFile.saveToFile()

### ISSUE THREAD

**Issue by mgrinzPlayer** [cheat-engine/cheat-engine#73]
```Lua
os.execute('mkdir "'..extractfolder..'"')
findTableFile(filename1).saveToFile(extractfolder..'\\'..filename1)
```

In CE6.4 it extracts to _extractfolder_. Shows error when _extractfolder_ not exists (Unable to create file "path\filename.ext").

In CE6.5.1 it doesn't extract to _extractfolder_. Creates files next to _extractfolder_ .
The existence of the _extractfolder_ doesn't matter.

**Comment by cheat-engine** [comment]
should be fixed on git

**Comment by mgrinzPlayer** [comment]
Works. Thank you.
