### ISSUE TITLE
ExFreePoolWithTag

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#730]
ExFreePoolWithTag(Buffer, 0);
ExFreePoolWithTag(InternalProcessList, 0);
ExFreePoolWithTag(Buffer, 0);
ExFreePoolWithTag(*OutputBuffer,0);
ExFreePoolWithTag(*Header,0);
ExFreePoolWithTag(Ultimap2Ranges, 0);
ExFreePoolWithTag(PInfo[i]->ToPABuffer, 0);
ExFreePoolWithTag(PInfo[i]->ToPABuffer2, 0);
ExFreePoolWithTag(PInfo[i]->ToPAHeader, 0);
ExFreePoolWithTag(PInfo[i]->ToPAHeader2, 0);
ExFreePoolWithTag(PInfo[i]->ToPALookupTable,0);
ExFreePoolWithTag(PInfo[i]->ToPALookupTable2, 0);
ExFreePoolWithTag(PInfo[i], 0);
ExFreePoolWithTag(PInfo, 0);
ExFreePoolWithTag(Ultimap2_DataReady, 0);
ExFreePoolWithTag(Ultimap2Ranges, 0);

ExFreePoolWithTag -> ExFreePool??

Does ExFreePoolWithTag work without any changes?

**Comment by cheat-engine** [comment]
Seeing that ExFreePool is defined as:
```
#define ExFreePool(a) ExFreePoolWithTag (a,0)
```
it'll likely work

**Comment by kitty8904** [comment]
19H1 Windows, why did Microsoft fail to generate memory when the tag was 0? It was a strange bug
