### ISSUE TITLE
Can't Open Cheat Engine, Already Got Rid of badlion and turned off windows defender

### ISSUE THREAD

**Issue by Twighlight15** [cheat-engine/cheat-engine#732]
Heya! So i installed cheat breaker and found out that i couldn't open it, it'd open for a second in task manager and then disappear, searched around for a bit and found that badlion seemed to be a problem, so i got rid of it, i also checked windows defender, and firewall, as well as reinstalling several times and using "Windowrepair.exe", still does not want to open, heres a list of all of the programs on my computer.
![image](https://user-images.githubusercontent.com/29836241/58747282-e147ae00-841d-11e9-8b6f-0c375004fbae.png)
Hopefully it emails me when a reply appears 😅

**Comment by Twighlight15** [comment]
Also, i have restarted ( shut down and push the physical button AND restart, tried both ) several times between each step of my troubleshooting attempts.

**Comment by cheat-engine** [comment]
Have you restarted your computer using start menu->power->restart (make  sure you pick restart and not shutdown, else it will keep the badlion malware in memory)

**Comment by Twighlight15** [comment]
Just to make sure, this is suppose to spam command prompt  for a bit? it didn't open a .txt file, so ill copy it all and put it in a .txt and send it over, but i should be opening a file explorer page where.. what is exactly? just want to make sure i don't waste your time.

**Comment by cheat-engine** [comment]
I think you forgot the `> bla.txt part` 
but if you like you can also copy the output of the command prompt

as for the location
if the command prompt says 
`c:\users\db>`
and you then type the command so it end up looking like
`c:\users\db>driverquery /V > bla.txt`

then the file will be `c:\users\db\bla.txt'

**Comment by Twighlight15** [comment]
Hmm.. so i closed the earlier command prompt as i accidently did it twice and it was floaded, and now it wont rewrite what was earlier written in the other command prompt, tried deleting the spaces...
i think im being a bit stupid.

**Comment by Twighlight15** [comment]
![image](https://user-images.githubusercontent.com/29836241/58747473-ac892600-8420-11e9-900a-c5910610833f.png)

**Comment by cheat-engine** [comment]
upload c:\users\OwO\bla.txt

**Comment by Twighlight15** [comment]
Nothing, empty .txt
Both copy pasted that line into file explore and typed it myself

**Comment by cheat-engine** [comment]
then just type `driverquery /V` or 'driverquery' and post the contents of the command prompt here

**Comment by Twighlight15** [comment]
[Bla.txt](https://github.com/cheat-engine/cheat-engine/files/3243692/Bla.txt)

**Comment by cheat-engine** [comment]
`BadlionAntic BadlionAnticheat       BadlionAnticheat       Kernel        Disabled   Running    OK         TRUE        FALSE        4,096             1,794,048   0          2/19/2019 6:23:59 AM   \??\C:\Windows\system32\drivers\BadlionAnticheat 4,096`
It seems the badlion malware is still installed on your system

reboot (actual reboot, don't shutdown) and then check again

**Comment by Twighlight15** [comment]
Sorry, what do you mean by "Actual reboot"
is there a specific way to turn off my computer? i tried both shutting down and restarting it via window key >Power>shutdown/restart

**Comment by Twighlight15** [comment]
Also, when did badlion become malware? iirc it used to be a minecraft client a year ago or so

**Comment by cheat-engine** [comment]
badlion is hard to get rid of and interferes with the operation of your system by preventing programs from running withouy giving a choice, hence malware

anyhow, try restart and shutdown, or reinstall badlion and then properly uninstall

**Comment by Twighlight15** [comment]
Restarted, and it popped up. wonder why restarting it earlier didnt work... anyway thanks alot! now to just figure out how to use it... anyway sorry for wasting your time.
