### ISSUE TITLE
Some questions about ceserver.

### ISSUE THREAD

**Issue by KenjiroIchise** [cheat-engine/cheat-engine#735]
(1)About memory read option
I previously added the option to read memory with ptrace only.
What is a good way to make this configurable?

(2)About createtoolhelp32snapshot
It takes time to enumerate all modules of all processes.
Also, OpenProcess/ReadProcessMemory for all processes leads to instability of operation.
For example, is it possible to list the modules of only the selected process?

(3)About shared library of ceserver
I succeeded in making ceserver a shared library and operating it on a non-root device by invading the Android application.
This idea is originally based on the anti-debug trick.
It is possible to create a child process with fork, and analyze the parent application from that child process.
What do you think about this?

**Comment by cheat-engine** [comment]
1: likely same method as the compression parameter

2: the default operation IS only listing modules in use by the current process only

A single process just has a lot of dependenciesn like mono.so which is actually very helpful to know where it is

3: No idea. How do you get android to load a module in a target process without having root?

**Comment by KenjiroIchise** [comment]
(2)
If not set, createtoolhelp32snapshot will do OpenProcess / ReadProcesMemory for all processes, and in some cases, ceserver will stop.

api.c: 2535
pid_t pid = wait (& status);

If the target process does not stop, ceserver seems to stop at the above wait.
This behavior is very problematic depending on the environment and can not be attached in the first place.

(3)
Decompile the apk and modify smali to load libceserver.so with System.LoadLibrary.
This method works because child processes can attach parents even to non-root devices.
