### ISSUE TITLE
kernel memory createthread fix bug

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#74]
alloc(code,128)
registersymbol(code)
createthread(code)
code:
mov [FFFFFA80145B4000],1 //kernel memory 0 -> 1 fix thread dead
ret
======================
alloc(code,128)
registersymbol(code)
createthread(code)
code:
mov rax,FFFFF80005020400
mov [rax],1 // kernel memory 0 -> 1 fix thread dead
ret
======================

======================
and
createthread(FFFFFA80145B4000): <--address kernel memory possible?
FFFFFA80145B4000:
mov [FFFFFA80145B4100],1
ret

//autoassembler createthread kernelmemory address value not fix?

thank you

**Comment by kitty8904** [comment]
•Added kernelmode alloc and (un)mapping functionality 

kernelmode alloc registersymbol possible?

=====================
or lua kernelmode alloc 

code = allocateKernelMemory(1000)

print(code)

print(code) => -6046972709280 <> 60 F6 56 14 80 FA FF FF <> FFFFFA801456F660

print code hexadecimal view?

**Comment by cheat-engine** [comment]
If you compile the driver yourself you can use the lua command 
dbk_executeKernelMemory('code',0)
or
dbk_executeKernelMemory(0xFFFFFA80145B4000,0)

**Comment by kitty8904** [comment]
thank you dark byte first code execute success

why the code loop ? (autoassembler?, lua? not loop TT)

FFFFFA8013DF5000:
add [FFFFFA8013DF502A],1
mov rcx,#1000
call Sleep
jmp FFFFFA8013DF5000

dbk_executeKernelMemory(0xFFFFFA8013DF5000,0)

**Comment by kitty8904** [comment]
label(loopLabel)

FFFFFA8013E7B000:
mov rcx,#1000
cli
loopLabel:
inc [FFFFFA8013E7B021]
loop loopLabel
sti
ret

loop increase sucess but timer & time loop ?

label(loopLabel)

FFFFFA8013E7B000:
mov rcx,#1000
cli
loopLabel:
inc [FFFFFA8013E7B021]
loop loopLabel
sti
//jmp FFFFFA8013E7B000 <---- ?? why time loop?

**Comment by cheat-engine** [comment]
Sleep is an usermode only function.
check out kernel_KeDelayExecutionThread for a kernelmode equivalent ( https://msdn.microsoft.com/en-us/library/windows/hardware/ff551986%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396  a lot more complicated )

also, use createNativeThread(function) if you don't want to run it inside the main gui thread

**Comment by kainpark7894** [comment]
The constantly changing to try to modify the kernel pointer value

So the loop is needed

cheat engine It has been very helpful

http://forum.cheatengine.org/viewtopic.php?p=5547259&sid=9a3d99e2694ba3ae9239e33ddc60515d

thankyou dark byte ^^

**Comment by kitty8904** [comment]
The constantly changing to try to modify the kernel pointer value
So the loop is needed

cheat engine It has been very helpful

http://forum.cheatengine.org/viewtopic.php?p=5547259&sid=9a3d99e2694ba3ae9239e33ddc60515d

thankyou dark byte ^^
