### ISSUE TITLE
ceserver ptrace bug verification

### ISSUE THREAD

**Issue by KenjiroIchise** [cheat-engine/cheat-engine#743]
Android:x86
I built the second argument of ptrace into int type and int64_t type respectively and analyzed the binary.

ptrace (PTRACE_PEEKDATA, pid, 0x04000000, NULL);

int:
push 0
push 4000000h
push esi
push 2
call _ptrace

int64_t:
push 0
push 4000000h
push esi
push edi
push 2
call _ptrace

As mentioned above, when I build with int64_t type, a stack inconsistency occurs and memory reading actually fails.
Therefore, when building with AndroidStudio, it turned out that it is necessary to specify correctly.

**Comment by cheat-engine** [comment]
That behaviour looks like there is no headerfile defining ptrace and just passes it based on the parameters given

**Comment by KenjiroIchise** [comment]
I looked at the bionic libc implementation.

https://android.googlesource.com/platform/bionic/+/master/libc/bionic/ptrace.cpp

long ptrace (int req, ...)

Is a variable-length argument like this the cause of the problem?

**Comment by cheat-engine** [comment]
yes, declaring the function like that is like not declaring it at all

but the __ptrace is correctly defined.  So in case of android studio, use __ptrace

**Comment by KenjiroIchise** [comment]
How about implementing the following function and replacing all ptrace with safe_ptrace?

long safe_ptrace(int request, pid_t pid, void * addr, void * data){
    int result;
    errno = 0;
    result = ptrace(request, pid, addr, data);
    if(errno != 0){
        printf("ptrace error(%d)!\n",errno);
    }
    return result;
}

**Comment by cheat-engine** [comment]
perhaps, or an 
```
#ifdef __ptrace 
  #define ptrace __ptrace
```

**Comment by KenjiroIchise** [comment]
Thank you for telling me various things.
