### ISSUE TITLE
About singlestep on the ARM architecture.

### ISSUE THREAD

**Issue by KenjiroIchise** [cheat-engine/cheat-engine#748]
I connected ceserver with real machine Nexus 7 and verified the operation.
The breakpoint worked correctly but single step could not be performed.
According to the document, PTRACE_SINGLESTEP seems to have been deleted.
How does gdb etc support single step?

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=425fc47adb5bb69f76285be77a09a3341a30799e

CheatEngine is the latest build. On x86 single steps can be performed without problems.

**Comment by cheat-engine** [comment]
emulate it.
find the address of the next instruction and place a breakpoint there
