### ISSUE TITLE
DBK start Error 

### ISSUE THREAD

**Issue by Lafko** [cheat-engine/cheat-engine#749]
After compiling the driver startup error. 
I use the latest version downloaded from the repository
![Screenshot_1](https://user-images.githubusercontent.com/16429534/59022047-b9a97900-8855-11e9-83c5-15123dfc6f60.png)

**Comment by kitty8904** [comment]
https://github.com/cheat-engine/cheat-engine/blob/master/Cheat%20Engine/dbk32/DBK32functions.pas#L16

https://github.com/cheat-engine/cheat-engine/blob/master/DBKKernel/DBKDrvr.h

DBKDrvr.h -> 2000024 -> 2000025 Fix
