### ISSUE TITLE
DBKKernel solution and project mismatch

### ISSUE THREAD

**Issue by CreepGin** [cheat-engine/cheat-engine#75]
mykerneldriver.sln is currently referencing non-existent project file `mykerneldriver.vcxproj`

```
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "mykerneldriver", "mykerneldriver.vcxproj", "{A4B29F18-5AA7-466A-A658-4F886949BE32}"
```

This must be an error when you tried to upgrade from VS 2008 to 2013.

**Comment by cheat-engine** [comment]
Probably yes.
the sln is mostly used for code highlighting, auto completion and header file exploration.   So if you wish you can just create a new project with the files there.
(You can't use it to compile the driver)

**Comment by CreepGin** [comment]
> You can't use it to compile the driver

I'm assuming this is because it's using WDK 7.1? Anyway, thanks for the reply
