### ISSUE TITLE
CheatEngine doesn't open

### ISSUE THREAD

**Issue by CoTymb** [cheat-engine/cheat-engine#758]
I open the CheatEEngine and do nothing , i run with administrator nothing , i try an older version nothing , help me guys please
\

**Comment by cheat-engine** [comment]
https://github.com/cheat-engine/cheat-engine/issues/571
get rid of badlion and reboot

**Comment by RoWAidXD** [comment]
I have the same problem but I don't have badlion or reboot or any program for anti virus

**Comment by cheat-engine** [comment]
open a command prompt and execute
`driverquery /v > %HOMEPATH%\desktop\driverlist.txt`
then upload driverlist.txt here

**Comment by RoWAidXD** [comment]
Thanks, it worked!

**Comment by truckingMaro** [comment]
> open a command prompt and execute
> `driverquery /v > %HOMEPATH%\desktop\driverlist.txt`
> then upload driverlist.txt here

Wait where i do that please i think i got the same problem since i just dowload it and when i want to opent it just doesnt want it tells me like i dont have the autorisation

**Comment by cheat-engine** [comment]
No authorisation means it's windows defender/reputation based protection or your anti virus blocking you from executing CE
