### ISSUE TITLE
blue screen after changing settings

### ISSUE THREAD

**Issue by mkemmerz** [cheat-engine/cheat-engine#760]
Cheat Engine Version: 6.8.3, Windows 10 latest build

I just upgraded Cheat Engine from 6.8.1 to 6.8.3 on my PC.

1. Open with admin permission
2. Edit -> Settings -> Extra -> Enable "Query memory region routines" and "Read / Write Process memory"
3. Edit -> Scan Settings -> Enable "Don't scan memory that is protected with the No Cache option" and Enable "MEM_MAPPED: Memory that is mapped into the view of a section".

The crash itself seems to appear if I change "Extra" -> "Query memory region routines". The blue screen shows the error message: "WORKER_THREAD_RETURNED_AT_BAD_IRQL"

The goal is to use cheat engine in bluestacks for mobile games.

After hitting "Ok" I get a bluescreen and my whole system crashes. I would like to provide more information about this topic. Where do I find the logfiles for example or anything else that is useful to encounter this issue?

**Comment by cheat-engine** [comment]
c:\windows\memory.dmp or else one of the minidumps in the system event viewer

anyhown it's likely slready fixed for next version

**Comment by mkemmerz** [comment]
Ok then I will wait for now and give feedback about the next version if it is released.

**Comment by HansRandomizer** [comment]
Same thing happened to me with 7.5 today.
