### ISSUE TITLE
VEH debugger crash

### ISSUE THREAD

**Issue by clhhz** [cheat-engine/cheat-engine#767]
![1](https://user-images.githubusercontent.com/48997976/59456282-96c82780-8e48-11e9-935a-299a56c90023.PNG)
First Allocate memory 
![2](https://user-images.githubusercontent.com/48997976/59456284-9760be00-8e48-11e9-8f61-9bdc5b5ae9a5.PNG)
Write code like this.
![3](https://user-images.githubusercontent.com/48997976/59456285-9760be00-8e48-11e9-99a9-88a752204b97.PNG)
Run
![4](https://user-images.githubusercontent.com/48997976/59456286-9760be00-8e48-11e9-95ea-d112889310ee.PNG)
![5](https://user-images.githubusercontent.com/48997976/59456287-97f95480-8e48-11e9-8d68-01140a2d4f69.PNG)
![6](https://user-images.githubusercontent.com/48997976/59456289-97f95480-8e48-11e9-8dc8-20ebb27ac263.PNG)

**Comment by cheat-engine** [comment]
Do the exact same thing on tutorial-i386.exe and see if it crashes there as well so we can rule out it's test.exe which interferes with VEH

**Comment by clhhz** [comment]
> Do the exact same thing on tutorial-i386.exe and see if it crashes there as well so we can rule out it's test.exe which interferes with VEH

I wouldn't have had that problem when I restarted my computer.
But there's another way I can get him to crash.
Open Tutorial-i386.exe and come to Step 2.
Set breakpoints at 00424073, and then get the value of the ESP
![0](https://user-images.githubusercontent.com/48997976/59470414-2d591080-8e6a-11e9-8d8c-e82c1cce36d3.PNG)
![1](https://user-images.githubusercontent.com/48997976/59470623-d99af700-8e6a-11e9-8b6a-83744822b250.gif)

**Comment by Wheel-Of-Fate** [comment]
I Have been away from CE for quite long time and i'm not an expert but i can tell that CE 6.8.3 VEH Debugger got a serious issue.
it keeps crashing after attaching it to a game for sometime and in other games it crashes instantly
i tried it with old games and new games and i found out that CE 6.8.2 doesn't crash
i run windows 7 SP1.
this is an error i was able to reproduce with an old game.
![Untitled](https://user-images.githubusercontent.com/40186693/61674011-212a6380-acf2-11e9-8e8c-c3e351a28c33.png)
i couldn't reproduce the crash for the new games on my side it just give a box game.exe needs to close fault: stackhash

**Comment by cheat-engine** [comment]
reset CE's settings. Perhaps you have added the single step exception to the ignore list

**Comment by Wheel-Of-Fate** [comment]
> reset CE's settings. Perhaps you have added the single step exception to the ignore list
> 
> If you press print-screen, does the system hang for a minute?
> 
> Have you tried kerneldebug before trying vehdebug? That can interfere if still loaded

no i didn't add a single step exception to the ignore list. 
yea i tried everything fresh install and reset the settings it gives the same results.
i don't use print-screen key at all.
yea kerneldebug working but whenever i check the boxes in the debugger interface config it crash my whole PC i don't know if this is normal because i never used it before.

**Comment by Wheel-Of-Fate** [comment]
> reset CE's settings. Perhaps you have added the single step exception to the ignore list
> 
> If you press print-screen, does the system hang for a minute?
> 
> Have you tried kerneldebug before trying vehdebug? That can interfere if still loaded

no i didn't add a single step exception to the ignore list. 
yea i tried everything fresh install and reset the settings it gives the same results.
i don't use print-screen key at all.
yea kerneldebug crash too
![Untitled](https://user-images.githubusercontent.com/40186693/61811900-c81e1500-ae42-11e9-8d66-6d9178a10edd.png)
i guess i will stick to CE 6.8.2 for now.
