### ISSUE TITLE
Assembler error on: addsd xmm?,qword ptr [?]

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#770]
Disassembler can handle this instruction:
`F2 0F 58 41 40 - addsd xmm0,qword ptr [rcx+40]`
But assembler cannot:
![image](https://user-images.githubusercontent.com/14368203/59567666-fea48b00-905f-11e9-98b7-a8af397db0c2.png)

**Comment by cheat-engine** [comment]
fixed by changing the disassembler

**Comment by Symbai** [comment]
@cheat-engine I've trouble finding the commit that fixes it, which one is it?

**Comment by cheat-engine** [comment]
fixed a while ago. The disassembler now shows ut without the qword ptr

**Comment by Symbai** [comment]
Ah ok, thanks!
