### ISSUE TITLE
Table Opening Issues

### ISSUE THREAD

**Issue by SDKSerenity** [cheat-engine/cheat-engine#774]
When Editing Or Making A Xml Editor via C# or simply just editing it via text editor the file corrupts i suggest allowing a way to export from CT Format To Xml Or Something similar That Way Us Devs Can Make Programs To Sort Addresses Or Quick Edit Them Etc...

**Comment by cheat-engine** [comment]
perhaps your xml editor needs updating as a .ct is a pure .xml file
just don't use xml incompatible characters

**Comment by SDKSerenity** [comment]
i Had Notice it was Xml therefore i added up making a program witch i can add to my github if you would like to review it all it does it grabs the ct file and subtracts every offset by 4 then writes it to a new ct file the reason i subtract by 4 is because when using cheat engine you can't have a way to go back 4 bytes Example: (ITEM_WEAPON_0000) unless you manually do each one manually what i wanna grab is 4 bytes behind *ITEM_* so Basically 5850ITEM_  Any Solution Or Idea Would Be Great Thanks For your time and Effort!

**Comment by cheat-engine** [comment]
What do you wish to edit? The (base)address or one of the offsets of a pointer?

Also, you can do "ITEM_WEAPON_0000-4"  CE will interpret that as the address of ITEM_WEAPON_0000 minus 4

Besides that, just look at the ct file

You can also use ce's lua to quickly change that
```
local i
for i=0,AddressList.Count-1 do
  local a=getAddressSafe(AddressList[i].Address)
  if a then
    a=a-4
    AddressList[i].Address=getNameFromAddress(a)
  end

  --or just AddressList[i].Address=AddressList[i].Address..'-4'
end
```
(offsets can be accessed using OffsetCount and Offset[] )

**Comment by SDKSerenity** [comment]
This Should Help https://giphy.com/gifs/Wpx0Jci5XEVR4ZFR2k

**Comment by cheat-engine** [comment]
How about using a more up to date CE version?

**Comment by SDKSerenity** [comment]
Here You Go [CT Files.zip](https://github.com/cheat-engine/cheat-engine/files/3312397/CT.Files.zip)

**Comment by mgrinzPlayer** [comment]
Modified.CT has BOM header

![obraz](https://user-images.githubusercontent.com/9157726/59890405-09994b80-93d1-11e9-9b35-626d9b43f07e.png)

**Comment by SDKSerenity** [comment]
Thanks For Fixing My Issue and taking your time to help :)
