### ISSUE TITLE
Can't compile current release source (6.8.3)

### ISSUE THREAD

**Issue by reijin90** [cheat-engine/cheat-engine#778]
There seem to be several errors present:
```
ceguicomponents.pas(599,31) Error: No property found to override
ceguicomponents.pas(599,31) Error: This kind of property cannot be published
ceguicomponents.pas(599,31) Fatal: Syntax error, "READ" expected but ";" found
```

"fixed" by removing the two lines: 
```
    //property TextHintFontColor;
    //property TextHintFontStyle; 
```

then:
```
formdesignerunit.pas(592,30) Error: Variable identifier expected
formdesignerunit.pas(593,31) Error: Variable identifier expected

```
Sadly I'm not a Pascal programmer so I have no idea what the issue is here. Maybe someone could help please?

**Comment by cheat-engine** [comment]
are you using Lazarus 1.6.4 ? because that is what the release of 6.8.3 used

**Comment by reijin90** [comment]
> are you using Lazarus 1.6.4 ? because that is what the release of 6.8.3 used

thanks for the fast reply, no I use the 2.0.2 version. With the current source it builds fine. So I guess I should've tried the older Lazarus version. 

Btw: I'm trying to build a custom version in an effort to make CE less detectable, so I'm wondering: Is everything of CE open source? There is a bin-folder containing the hooks and some sln-files etc. What do I have to do to re-build every component? Is that even possible?
From the instructions in the readme it only builds the main binary.

**Comment by cheat-engine** [comment]
Yes, everything is open source, but you'll need to get visual studio and certain sdk's etc... to rebuild them which can be a pain especially the dx9 sdk which microsoft loves making hard to find
Also not all dll's are used by you so you can likely skip them(ce only needs the lua dll, nothing else is needed)

**Comment by reijin90** [comment]
> Yes, everything is open source, but you'll need to get visual studio and certain sdk's etc... to rebuild them which can be a pain especially the dx9 sdk which microsoft loves making hard to find
> Also not all dll's are used by you so you can likely skip them(ce only needs the lua dll, nothing else is needed)

Are there any details on what I need specifically or do I have to find the stuff myself?
