### ISSUE TITLE
how to open dbvm？

### ISSUE THREAD

**Issue by taotao-123** [cheat-engine/cheat-engine#779]
I want compile current release source 6.8.3，But I don't know how to open dbvm.

thanks.

![1](https://user-images.githubusercontent.com/26496694/59966105-d1694880-9549-11e9-989b-875a63dcf239.PNG)

**Comment by cheat-engine** [comment]
You could boot of dbvm using the efi or raw usb version
but else you need to compile dbk64.sys yourself (and boot with unsigned driver support, testsign mode, or sign the driver yourself with your own business class codesigning certificate)

**Comment by dujiangchuan** [comment]
Received  , thank you

**Comment by dujiangchuan** [comment]
Where can I download the latest usb version of dbvm?
