### ISSUE TITLE
setGlobalKeyPollInterval and setGlobalDelayBetweenHotkeyActivation are ignored when loading CT

### ISSUE THREAD

**Issue by mgrinzPlayer** [cheat-engine/cheat-engine#78]
```Lua
setGlobalKeyPollInterval(50)
setGlobalDelayBetweenHotkeyActivation(300)
```
Use above at the end or at the beginning of the Lua script. Save.
Then double click CT, allow Lua script. Doesn't work as it should.

Probably because **handleparameters** procedure executes Lua script indirectly with
`LoadTable(tabletoload,false);`

and then sets
`mainform.visible:=mainformvisible; // which is true for CT`

TMainForm.FormShow procedure loads settings from the registry with **LoadSettingsFromRegistry**. And it loads *interval* and *delay* from the OS registry.

Workaround will be:
- using a timer object
- or placing 'setGlobal....' lines inside **onOpenProcess** function.

Is it possible you can fix above issue by moving **LoadSettingsFromRegistry** to the beginning of **handleparameters**?
```Patch
Index: cheatengine.lpr
===================================================================
--- cheatengine.lpr	(wersja 2385)
+++ cheatengine.lpr	(kopia robocza)
@@ -111,7 +111,7 @@
   tabletoload:='';
   origin:='';
   mainformvisible:=true;
-
+  LoadSettingsFromRegistry;
   try
 
     for i:=1 to Paramcount do
Index: MainUnit.pas
===================================================================
--- MainUnit.pas	(wersja 2385)
+++ MainUnit.pas	(kopia robocza)
@@ -6980,7 +6980,7 @@
       rsLicenseExpired, mtWarning, [mbOK], 0);
 
 
-  LoadSettingsFromRegistry;
+  //LoadSettingsFromRegistry;
 
   //Load the table if one was suplied
   overridedebug := False;
```

**Comment by cheat-engine** [comment]
I'll check it out, but i think it may interfere with .cetrainer files which should never load the settings to begin with

Date: Fri, 10 Jun 2016 16:20:38 -0700

**Comment by mgrinzPlayer** [comment]
I see. Maybe this patch:


```Patch
Index: cheatengine.lpr
===================================================================
--- cheatengine.lpr	(wersja 2416)
+++ cheatengine.lpr	(kopia robocza)
@@ -163,6 +163,7 @@
 
       try
         try
+          if mainformvisible then LoadSettingsFromRegistry;
           LoadTable(tabletoload,false);
           MainForm.Savedialog1.FileName:=tabletoload;
         finally
@@ -176,7 +177,9 @@
           application.Terminate;
         end;
       end;
-    end;
+    end
+    else
+      LoadSettingsFromRegistry;
   except
   end;
 
Index: MainUnit.pas
===================================================================
--- MainUnit.pas	(wersja 2416)
+++ MainUnit.pas	(kopia robocza)
@@ -6989,7 +6989,7 @@
       rsLicenseExpired, mtWarning, [mbOK], 0);
 
 
-  LoadSettingsFromRegistry;
+  //LoadSettingsFromRegistry; // moved to HandleParameters
 
   //Load the table if one was suplied
   overridedebug := False;
```

**Comment by mgrinzPlayer** [comment]
I think above patch will be backward compatible. And it will fix:

- setGlobalKeyPollInterval and setGlobalDelayBetweenHotkeyActivation  for  CT files

- will also fix ("cetrainer files should never load the settings") special cetrainers. I meant those unprotected, with such Lua code somewhere in the script:
```Lua
do
  local timer=createTimer(nil,true)
  timer.Interval=1
  timer.OnTimer = function (t) t.destroy() getMainForm().Visible = true end
end
```

**Comment by mgrinzPlayer** [comment]
fixed
