### ISSUE TITLE
Can't debug if DoNotOpenProcessHandles is set

### ISSUE THREAD

**Issue by diejozef** [cheat-engine/cheat-engine#784]
Can't place HWBP if DoNotOpenProcessHandles (and therefore privatebuild as well) is set.
I'm using kernel debugging (DBVM). This renders the 'Find out what writes/accesses this address' feature unusable as well (same goes for DBVM version).

**Comment by cheat-engine** [comment]
If for some reason the physical address isn't filled in then type it in manually (You can get it from the hexadecimal view of memoryview)

**Comment by diejozef** [comment]
Thank you, enabling globaldebug solved the debugging issue, however, upon using 'Find out what writes' there's still a thread handle opened for the target process.

Also, when using the DBVM version of the above feature, I can't catch anything but some code from kernel address space, which seems like some sort of constant check. non-dbvm version shows everything correctly.

If I set a breakpoint in the somewhere in the function (where I'm expecting writing from) and run a bit later, then DBVM manages to catch the accessing instruction just fine but this only if a breakpoint was set beforehand.

**Comment by cheat-engine** [comment]
Find out where it opens the handle and remove it, it's not used with globaldebug (add it to the privatebuild define)

As for DBVM not finding it, not sure. The first result you see is CE reading the memory. But perhaps try a bigger buffer. And is your DBVM version self-compiled or the one from the ce release ?

**Comment by diejozef** [comment]
I'm not very familiar with CE source yet, but after investigating a bit, I noticed that the thread handle is opened with THREAD_ALL_ACCESS privileges, so I'm guessing [this line](https://github.com/cheat-engine/cheat-engine/blob/c7e69c7b4c21f0d057b66fd090a2b898c05520b3/Cheat%20Engine/KernelDebuggerInterface.pas#L403) and the one below that should be changed in order to skip opening a thread handle if globaldebug is on.

I'm using the original dbvm image that I copied from the latest CE release installation.

**Comment by cheat-engine** [comment]
That's it yes. in case if globaldebug and nohandle usage that won't be needed. You can change it to the least requirements or remove it completely 

also, is the sourcecode you use the latest version or the when 6.8.3 got released

**Comment by diejozef** [comment]
I'll try removing it and let you know if I had any luck. I'm using the latest source (pulled yesterday) with the latest release's (downloaded from the website) dbvm image.
