### ISSUE TITLE
Sorting by value is literally freezing CE

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#787]
I'm sorting by value by clicking on the value column. I got only 92 items in the address list. CE stays "frozen" for a couple of minutes now. This happens quite often that sorting by value takes ages although there are only a few items in the list. Most of the items aren't changing its value.

**Comment by cheat-engine** [comment]
Are you talking about the addresslist in the main window or somewhere else?
If the mainwindow, are custom types being used?

**Comment by Symbai** [comment]
Sorry. Yes I'm talking about the address list in the main window. No custom types. See gif below

![Untitled Project](https://user-images.githubusercontent.com/14368203/61110679-4f4caf80-a477-11e9-8f38-825df9c00150.gif)

**Comment by cheat-engine** [comment]
I can't reproduce.
Sure it freezes for 5 seconds on my 4GHz system but it doesn't freeze forever
