### ISSUE TITLE
dbvm breakpoint

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#789]
<img width="517" alt="11" src="https://user-images.githubusercontent.com/18622105/61256296-3d387d00-a7a7-11e9-844a-8c626355f4e4.png">

Indicates the current breakpoint type mark add?

Does setting the type and pressing F5 still work as a dbvm breakpoint?

///////////////////////////////////
and safe dbvm breakpoint add?
(dbvmbreakpoint is set to blue screen when dbvm is not loaded)

**Comment by kitty8904** [comment]
<img width="1091" alt="22" src="https://user-images.githubusercontent.com/18622105/61256821-2c890680-a7a9-11e9-91ec-aaf843a5c7d7.png">

1.dbvm breakpoint check
2.dbvm breakpoint remove
3.3.Change Register Use Dbvm Cloaked Bp's Not Check(BUG)
(NOT PA VALUE)

PA value is not getting automatically

////////////////////////

I do not see the PA bar when I try to manually add a PA value

**Comment by cheat-engine** [comment]
should look better now

**Comment by kitty8904** [comment]
> should look better now

<img width="1336" alt="33" src="https://user-images.githubusercontent.com/18622105/61414803-da232380-a929-11e9-9f87-0ca9330ef881.png">

debug breakpoint no execute register(bug)

1.dbvm breakpoint check
2.dbvm breakpoint remove
3.Change Register Debug Break Point No Execute
(dbvm ept breakpoints are not applied)
