### ISSUE TITLE
Cheat Engine is not showing up

### ISSUE THREAD

**Issue by Tristans-sky** [cheat-engine/cheat-engine#791]
Hey there,

before you say that I should uninstall Badlion. I never had Badlion and its not on my system.
Any other fix for this issue?

**Comment by cheat-engine** [comment]
uninstall your anti virus and reboot (not shutdown and back on, actual reboot)

also execute `driverquery /v` and post the results here

easier if you understand how filesystems work: (Believe me, there are some who don't)
`driverquery /v > bla.txt` and upload bla.txt
