### ISSUE TITLE
dbvm breakpoint error

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#792]
<img width="644" alt="55" src="https://user-images.githubusercontent.com/18622105/61421269-49584200-a941-11e9-97a0-2d2dfb456258.png">

test os :: win7 vmware

external exception error

dbvm breakpoint does not work

hare ware breakpoint work(f5)

dbvm breakpoint not work(ctrl+alt+f5)

**Comment by kitty8904** [comment]
<img width="644" alt="66" src="https://user-images.githubusercontent.com/18622105/61422125-3e071580-a945-11e9-8b1b-4fae0aca50b8.png">

change register clock bp(dbvm ept bp) not work

The ept breakpoint does not seem to work right now

**Comment by kitty8904** [comment]
<img width="1474" alt="88" src="https://user-images.githubusercontent.com/18622105/61443725-0ae47680-a985-11e9-963f-3255db7b2767.png">

dbvm breakpoint -> error -> unfinished?

**Comment by cheat-engine** [comment]
try on actual hardware. Perhaps vmware doesn't support the vmcall after interrupt

**Comment by cheat-engine** [comment]
Is globaldebug on or off ?

**Comment by kitty8904** [comment]
okay test result

Global Debug On -> crash
Global Debug OFF-> no crash(Enable breka point success)

**Comment by kitty8904** [comment]
<img width="634" alt="99" src="https://user-images.githubusercontent.com/18622105/61446632-6f560480-a98a-11e9-997a-e1e49fd36ea5.png">

new bug

1.process select
2.dbvm active clock
3.target process exit & crash(In case of error termination)
4.dbvm disable clock -> no information delete

If a dbvm breakpoint has been killed without deleting it

You can not remove the disabled ept memory view

**Comment by kitty8904** [comment]
Question

breakpoint type select -> dbvm break point select -> f5(break point -> dbvm break point??)

Select the breakpoint type and save?(F5 break point)

Or is f5 a hardware breakpoint(only hard ware break point??)
ctrl+alt+f5(dbvmbreakpoint??)

break point type save?? not save??(f5)

**Comment by kitty8904** [comment]
<img width="399" alt="aa" src="https://user-images.githubusercontent.com/18622105/61449847-c5c64180-a990-11e9-9d49-1386c1c9fe5f.png">

new bug2 or support kernel memory breakpoint?

Dbvm breakpoint does not work with kernel memory address(pc bsod)

Can kernel address dbvmbreakpoint be supported?

**Comment by cheat-engine** [comment]
F5 is the default breakpoint set in debugger settings (never DBVM breakpoint by default)

I haven't tested it yet. Does "DBVM find what access" work on it? (the non breaking version)
And is this with both global and non-global breakpoints?

**Comment by kitty8904** [comment]
dbvm find what access -> no bsod(global,noglobal)

Default hardware breakpoint -> precallbacks function does not cause blue screen

dbvm ept breakpoint -> precallbacks function breakpoint ->bsod

I hope you get a stable tracing breakpoint in the kernel

////////////////////////////////////////////

If you set the breakpoint type, you should save it to f5(suggestion)
(Not a required feature)

**Comment by cheat-engine** [comment]
I have only managed to create a BSOD once but was a clock timeout BSOD (DBVM error) but couldn't figure out what caused it, but the other tests where successful.  (I tested on win32kfull.NtUserPeekMessage since it's called often by many processes and no need to load pdb's as it's exported)

**Comment by kitty8904** [comment]
make stepping safer by also checking the irql(source)

latest source test

dbvm break point -> no bsod ok

I will test it several times. Currently there is no blue screen
