### ISSUE TITLE
The cheat engine is Do not run.

### ISSUE THREAD

**Issue by Lockkopkom** [cheat-engine/cheat-engine#793]
If i run the cheat engine but the cheat engine is not showing and I deleted badlion but i can't run

**Comment by cheat-engine** [comment]
use the badlion uninstaller, don't just blindly delete it as it has installed bad things into your windows setup

or run this code as admin:
```
net stop BadlionAnticheat
sc delete BadlionAnticheat

```

**Comment by Lockkopkom** [comment]
I also deleted badlion and I used that code as admin but cheat engine is not run hlp

**Comment by cheat-engine** [comment]
Did you run that code in a command prompt that was running as administrator?
And have you executed the uninstaller of badlion?

Reboot your system.  Do a restart, not shutdown and back on

**Comment by Lockkopkom** [comment]
I fixed Thank you

**Comment by Lockkopkom** [comment]
But If I scan this error is come
Scan error:controller:Cleanup:ResultsPrepare:Error while loading result
(C:\Users\my name\Appdata\Local\Temp\Cheat Engine\{08DDE6A8-A7EC-4C7B-8..\ADDRESSES.TMP
