### ISSUE TITLE
kernel memory range search bsod?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#796]
start
FFFF800000000000

end
FFFFFF0000000000

Search the kernel random address area

Query memory region routines check on

Windows 7 and 8 are OK(NO BSOD)

Windows 10 has a problem

I want to search for characters or variables stored at random start kernel addresses

There is a delay search somewhere in the kernel memory address and the computer freezes

Not available on Windows 10 only

Can it be modified?

**Comment by cheat-engine** [comment]
I can not reproduce this.
Using Query memory region of course will take a long time in that region because of a really big area there (that all point to the same physical address)
But no BSOD.
Can you provide a memory.dmp and dbk64.pdb you generated when compiling the driver ?

**Comment by kitty8904** [comment]
<img width="480" alt="77" src="https://user-images.githubusercontent.com/18622105/61532331-73eeeb80-aa64-11e9-9d45-eaa3e9130a58.png">

1. No DBVM Load
2. PC Freezes -> 30sec~1min -> bsod

Sometimes Random blue screen

**Comment by cheat-engine** [comment]
Might be a device driver that has mapped device memory at that region which reacts on reads and the driver doesn't know how to deal with it.  (AMD gpu tends to do that)
