### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#797]
PointerscanresultReader.pas(318,18) Error: Can't determine which overloaded function to call

frmStringMapUnit.pas(213,19) Error: Can't determine which overloaded function to call

frmStringMapUnit.pas(218,19) Error: Can't determine which overloaded function to call

lazarus new version update??

my lazrus 2.0.0 fpc fpc 3.0.4

**Comment by cheat-engine** [comment]
just testing out FPC 3.2.0 beta with lazarus 2.0.0. should compile now
