### ISSUE TITLE
DBVM find what accesses error

### ISSUE THREAD

**Issue by asdfghjtr** [cheat-engine/cheat-engine#799]
Can't use this feature on any program I get "dbvm_watch failed" is this just not working at the moment? Can use find what reads/writes with dbvm no issue just not able to use this feature.

**Comment by cheat-engine** [comment]
did you build the latest DBVM here on git?

**Comment by asdfghjtr** [comment]
No the one from the 6.8.3 release vmdisk. How would I build DBVM from windows never messed with a makefile before

**Comment by cheat-engine** [comment]
I really have no idea.  I always use my VM with linux to build it

**Comment by asdfghjtr** [comment]
thank you i'll need to install linux on a VM in the future
