### ISSUE TITLE
auto dbvm breakpoint bug?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#800]
<img width="1150" alt="33" src="https://user-images.githubusercontent.com/18622105/61631508-80be4a00-acc5-11e9-989f-fe5d1746e10d.png">

1.4023CD START
2.CALL Function F8 Step over 
3.Auto BreakPoint List On Hit Break(Bug?)

When you call function to F8 Step Over -> Auto BreakPoint List & Hit Add

The breakpoint is automatically applied after the call

hardware break point -> CAll Function -> F8 Step Over ->No Auto BreakPoint List Add
dbvm break point -> Call Function -> F8 Step Over ->Auto BreakPoint List Add

dbvm Break Point
ex ) 004023E5 -> F8 Step Over -> 004023EA Auto BreakPoint & BreakPoint List Add

**Comment by cheat-engine** [comment]
changing the prefered breakpoint type after choosing a DBVM breakpoint has the sideeffect that for stepover it also uses dbvm breakpoints. And those have an issue that the autodelete doesn't trigger because they end after the breakpoint and not on

I'm not sure if you want to use DBVM breakpoints for f8 stepping or wish to use normal breakpoints like debugregisters

**Comment by kitty8904** [comment]
![55](https://user-images.githubusercontent.com/18622105/61688196-5751fc80-ad5f-11e9-8098-d1aa7a3a3380.gif)

Add a photo gif

**Comment by cheat-engine** [comment]
yes I know, but in your previous request you wanted to use DBVM breakpoints after setting them one, so not sure if you want those for F8 breakpoints as well or not ?

**Comment by kitty8904** [comment]
don't use dbvm for f8(github)

The latest updated source is what I want thanks

/////////////////
but bug??
![99](https://user-images.githubusercontent.com/18622105/61690615-b6fed680-ad64-11e9-989b-4cd148df446e.gif)


hardwarebreakpoint 
4023c7(f5) -> f8 -> 4023cd

dbvm breakpoint
4023c7(f5) -> f8 -> 4023d3

dbvm is pushed one line at breakpoint?

**Comment by cheat-engine** [comment]
that is how it works. DBVM always breaks after the instruction, not on the instruction like a hardware breakpoint

That is why Page breakpooints and DBVM breakpoints have the (instruction +1) text behind them

**Comment by kitty8904** [comment]
I understand how it works

not bug +1 instruction = ok

thank you
