### ISSUE TITLE
CHeat engine wont open And yes i have uninstalled badlion client like 2 weeks ago

### ISSUE THREAD

**Issue by KingTarunjot** [cheat-engine/cheat-engine#804]
disabled trend micro just 2 be sure but ic ant find the problem. got any fix

**Comment by KingTarunjot** [comment]
NVM 
sc delete BadlionAnticheat 
worked :)

**Comment by asdfghjtr** [comment]
what a awful anti-cheat can't detect CE in the 100s ways they could so they block it on peoples PC 24/7 lol
