### ISSUE TITLE
Cannot compile: Cannot open include file "frmFoundlistPreferencesunit.lrs"

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#805]
I've downloaded latest source, commit of https://github.com/cheat-engine/cheat-engine/commit/ea4178ed4268ef4541239a2a595a90bd635b196c and tried to compile (Release 64 build) using Lazarus 2.0.2.

It fails with `frmfoundlistpreferencesunit.pas(222,4) Fatal: Cannot open include file "frmFoundlistPreferencesunit.lrs"`

What am I doing wrong?

**Comment by asdfghjtr** [comment]
that'll only happen when you change the source a fresh compile will work fine with newest lazarus. If you're changing a file name be sure to do it from lazarus and not from the folder click save as and the new name so you don't run into issues.

**Comment by Symbai** [comment]
I downloaded the source, extracted it. Opened the project in lazarus and did a run -> new compile (shift+F9). Still gave me this error. Unless I'm wrong, this should be a "fresh compile" shouldn't it?

I didn't changed a file name.

**Comment by asdfghjtr** [comment]
oh okay I just took a fresh source for the new version and got the same error changing to release to test solution -
1. after you change it to release 64-bit exit out but be sure you save when you do
2. then open it up again and try to compile again you'll get the error again probably
3. exit and safe again then open it up again and it'll work now, sorry for the bad answer the first time didn't get this error ever before when changing to release.

**Comment by Symbai** [comment]
I did what you said 3 times in a row but still it does not compile. For the 4th time I tried clean up and compile but still got the issue.

I've downloaded and compiled CE sources in the past without any issues. Only with the latest commit (or commits before, I'm always passing) I got this issue.

**Comment by Symbai** [comment]
I've noticed the frmFoundlistPreferences isn't in the project inspector. I've added it and now can compile the source. No idea if this is a mistake from Dark Byte or intended or something...

**Comment by asdfghjtr** [comment]
a recent commit was "fix high dpi on foundlist preferences" so was probably something from that.

**Comment by cheat-engine** [comment]
your .lpr is outdated from the current github version
