### ISSUE TITLE
breakpoint bug

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#810]
f5 find what access bug

1. global debug on

2. dbvm load

3. find what access break on  -> target memory change -> break point off

4. re find what access break -> memory change -> breakpoint off repeat

5. pc computer slow ~ ~ and mouse keyboard leak -> pc suspend

dbvm find what access(no)

hardware find what access break point -> repeat -> pc down!

test os win10 1903

intel i9 9900k

test source :: github original latest source

**Comment by cheat-engine** [comment]
I can't reproduce.
Is your version build in debug mode or release mode? And if in debug, was dbgview running? If so, that will slow it down a lot to almost freezing point
