### ISSUE TITLE
dbvm crash hide driver?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#817]
miprocessloaderentry call -> driver hide

hardware breakpoint(globaldebug on) -> bsod??
(After some time debugging, blue screen)

There was no blue screen in the past.

Something changed in recent sources?

**Comment by cheat-engine** [comment]
check for exceptions. thay's the usual culprit in hidden drivers 

tip: in windbg load the odb on the manuallybloaded address of the driver
it can help pinpoint where it happened

**Comment by kitty8904** [comment]
vmx_causedCurrentDebugBreak -> delete or how fix?
