### ISSUE TITLE
hardware breakpoint pc suspend

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#821]
[testfile.zip](https://github.com/cheat-engine/cheat-engine/files/3489476/testfile.zip)

no vmware

win10 19H1 pc

cpu intel i9 9900k

ce release buid

target memory usermode

no dbgview execute

original source [ no hide driver ]

miprocessloadeentry -> no 
(only cheat engine originalsource bsod)

1.test.exe run ->

2.40d7e8 -> f5 hardware breakpoint hit(global debug on)

3.game start game end loop

4.pc very slow mouse down and keyboard down

5.30sec~1min pc bsod

original cheat enigne source.driver,vmdisk test

Target memory breakpoints hit fast increase
(Why is the problem occurring? I can not know)
(Breakpoint count increases by several hundred per second)

//////////////////////////////////////////////////////////////

dbvm break point -> no bsod no error

hardware break point -> pc suspend -> pc bsod

**Comment by cheat-engine** [comment]
Try running test.exe and do 5 game loops
then do the f5 hardware breakpoint. See if it crashes then as well

**Comment by kitty8904** [comment]
5 game loop -> global debug on -> bsod
5 game loop -> global debug off -> bsod

nvm thread??(i don't know)

Is it a problem because the breakpoint count is fast?

Is it possible to solve?

**Comment by cheat-engine** [comment]
Currently I don't think there is a way to solve it without a complete redesign.

When CE takes long to handle the debug event, there is a chance for corruption and no idea where to look (it happens when the thread waits)

**Comment by kitty8904** [comment]
dbvm breakpoint does not cause bluescreen

///////////////////////////////
second pc test :: win7 i7, 7700k

hardware breakpoint

Why does Windows 10 only have problems?

No problem with Windows 7

Is it a cpu or os problem?

**Comment by cheat-engine** [comment]
dbvm find what accesses doesn't halt the process. It just records it inside DBVM RAM and lets the program return.

dbvm breakpoints like break on access do go through the same mechanism, but likely because they don't get hit often enough it's not overwriting the stackframe with garbage

**Comment by kitty8904** [comment]
Redesign hardwarebreakpoint -> Do you have a plan?

///////////////////////

If there is no plan I will use dbvmbreakpoint

//////////////////////

Extra Questions(anti cheat)

AntiCheat affects game execution speed when dbvm loads

Is it easy to detect dbvm?

Loading dbvm slows down the pc but makes anticheats very slow

I like debugging but lately it's hard because there's a lot of debug detection

thank you

**Comment by cheat-engine** [comment]
try running dbvm_setTSCAdjust(false,0) and see if it makes a difference
