### ISSUE TITLE
Disassembler incorrectly assembles '0F 5A D1'

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#823]
Bytes: `0F 5A D1`
Bitness: `x86`

Disassembler:
`0F5A D1               - vcvtps2pd xmm2,xmm1`

Assembler on `vcvtps2pd xmm2,xmm1`:
```
5A                    - pop edx
D1 00                 - rol [eax],1 //it just generates 5A D1, the 00 isn't part of it.
```

According to online disassembler `0F 5A D1` should be `cvtps2pd xmm2, xmm1`, which the assembler correctly assembles.

![Untitled Project](https://user-images.githubusercontent.com/14368203/62831652-6adfdd00-bc12-11e9-8065-7dcff6e6a0a3.gif)

**Comment by cheat-engine** [comment]
should be fixed now
