### ISSUE TITLE
Consultation about ceserver.

### ISSUE THREAD

**Issue by KenjiroIchise** [cheat-engine/cheat-engine#831]
I am currently creating a client(python) that operates ceserver without going through CheatEngine.
In making this, I referred to Dark Byte's ceservertest.c.
May I release this client on my github with MIT license etc.?

**Comment by cheat-engine** [comment]
Yes, you have my permission to publish a client/front-end for ceserver on github

**Comment by KenjiroIchise** [comment]
Thank you Dark Byte!
