### ISSUE TITLE
Prevent windows are out of screen

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#835]
I had this a few times where a game starts in a different resolution and not correctly resets the resolution on exit or on alt tab. Then all windows on the desktop are moved around. The CE windows often gets out of screen then and you cannot move them back. On top of that the window positions are saved so restarting CE won't fix this. I have to open the registry and delete the window position settings.

The best would be if CE checks if a window is out of screen and then moves it back into. Alternatively a "reset window positions" button in settings would be great.

**Comment by cheat-engine** [comment]
ce already does that. When a form is loaded back and it's completely out of the desktop work area, it will bring the whole form back in
example:
`getMemoryViewForm().Left=-2800` and close CE

when CE loads the form back it will put it within the screen

**Comment by Symbai** [comment]
Hm last time it happened for me it opened the memory viewer still out of screen. I've also hoped that clicking the memory viewer button would trigger the window check or close and open it again etc. but it doesn't. However if you say it shouldn't be the case I will close the issue then.

**Comment by nik0la-vr** [comment]
> On top of that the window positions are saved so restarting CE won't fix this. I have to open the registry and delete the window position settings.

Maybe you could write a reg script for that. Something along these lines. 

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Cheat Engine\Window Positions 6.0]
"MainForm Position"=-
```

Check what are exact names of keys and values in your registry. List other values in their own lines.

Paste that in a text editor and save as *script.reg* (make sure you don't save as *script.reg.txt*). When you run it, it should delete specified values. You might want to backup your registry before trying it out.
