### ISSUE TITLE
savesession.lua extra separator and missing icons

### ISSUE THREAD

**Issue by nik0la-vr** [cheat-engine/cheat-engine#837]
Left image is what I see with if I can't sign tables.
![Duplicated separator](https://user-images.githubusercontent.com/37928424/63229355-cb1ce300-c1ff-11e9-85ab-860a86631223.png)

```lua
SaveScanSession.miSaveScanSession.ImageIndex=39
SaveScanSession.miLoadScanSession.ImageIndex=38
```

Icons indexed 38 and 39 were added in 2f9decb, but removed in d4a082a.

![38](https://user-images.githubusercontent.com/37928424/63229383-fef80880-c1ff-11e9-8d4f-108ae9de7b45.png) ![39](https://user-images.githubusercontent.com/37928424/63229384-fef80880-c1ff-11e9-8ae4-19686e04815b.png)

**Comment by nik0la-vr** [comment]
7661a86e LuaCustomImageList missing from repo?

**Comment by cheat-engine** [comment]
yes.
fixed now

**Comment by nik0la-vr** [comment]
82cc92c
