### ISSUE TITLE
Add option to override main Window title

### ISSUE THREAD

**Issue by AraHaan** [cheat-engine/cheat-engine#84]
I know of the following that hinders making  / using Cheat Engine to create hacks because of Specifically GameGuard/other anti-hacking program as it detects Cheat Engine.
1. the `Cheat Engine x.x.x` Title they cant change to `blah blah blah`
2. the `speedhack` dll's

So, yeah a way to override the default main window title to what they specify in a setting (if set) that allows them to bypass detection of some sort would be nice.

I think there should be a option to disable use of the speedhack dlls as well. (AKA a way to separate it and never load it up if a setting is set?).

And yes the issue is specifically for online game clients. The hacks I can do with Cheat Engine (if I get it to work) should allow me to modify application controled values that can request it to a server therby making the hacks actually work.

got to sometimes love online games like that :stuck_out_tongue:.

Yes, granted they can get the source from here and change it, however not everyone has all of the tools to build Cheat Engine. I do not think Visual Studio supports building pascal.

**Comment by cheat-engine** [comment]
execute this lua code.  you can put it in the autorun folder of CE:
`
getMainForm().Caption='Something'
getApplication().Title='Whatever'
`

**Comment by AraHaan** [comment]
hmm nice :+1:

**Comment by AraHaan** [comment]
btw, you happen to know if I can change the window Class name of all of the Cheat Engine forms using Lua as well? as I got somethign that detects them because of the window class name being ``Window`` on all of the forms.
