### ISSUE TITLE
Suggestion: Disable DBVM find out what  if DBVM is not set as debugger

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#848]
Sometimes I accidently hit the DBVM find out what menu item in memory viewer context menu and it immediately starts up loading DBVM. I have set VEH to be the default debugger. It would be nice if the DBVM option is either hidden or disabled until the user has set DBVM to be the debugger.

**Comment by cheat-engine** [comment]
What you're seeing isn't dbvm but the helper driver used to get physical addresses.  DBVM comes when you click ok
