### ISSUE TITLE
DBK32.DLL Error on Cheat Engine x86 and x64 Versions ver Latest

### ISSUE THREAD

**Issue by AraHaan** [cheat-engine/cheat-engine#85]
This error happens when I set some settigns. I have the files but they are `Ssys` format. This is a issue with latest Cheat Engine the older ones are fine.

![403b3ca05ab701750353c368d72b2395](https://cloud.githubusercontent.com/assets/15173749/16654217/5fd7e9b6-441a-11e6-85af-05f98598ace7.png)

Fixed when You copy and paste the sys files and rename those copies to `dbk32.dll` and `dbk64.dll`.

After that rename it goes too:
![3593cd15be79e627c4e6100a7a64c03d](https://cloud.githubusercontent.com/assets/15173749/16660683/134ed59e-4435-11e6-8203-9d3b5b1fe48b.png)

**Comment by AraHaan** [comment]
Oh and it says this because of that above.
![c04a890f216f1bb9feaba037865bfb10](https://cloud.githubusercontent.com/assets/15173749/16655972/62c90594-4422-11e6-9c15-baefacabdc43.png)
And I do not see the file for it either.

**Comment by cheat-engine** [comment]
this means that the .sig file doesn't match the contents of the executable you're using. (if you just renamed cheatengine-x86_64.exe  then do not forget to rename cheatengine-x86_64.sig as well)

alternatively, compile the driver yourself as unsigned, and then sign it yourself (or run in testsigning or no signing requirement)  (compile using wdk 7600.16385.1)

that it says your system doesn't support DBVM might be because you either compiled CE in debug mode (default when you get it from the Git) or your cpu doesn't support it, or you're inside a virtual machine

for compiling DBVM I always use a 64-bit linux environment, but that's something you shouldn't concern yourself with for now.

and a tip for easily seeing if it's a 32 or 64-bit build, look at the address range.  8 digits is 32-bit, 16 digits is 64-bit

**Comment by rcg4u** [comment]
Most common mistake people make is if you are using the professional version of windows, enabling hyper-v in programs and features will cause this error as well. It makes your entire windows os as a virtual machine.

![ashampoo_snap_2016 07 07_09h37m37s_007_](https://cloud.githubusercontent.com/assets/211848/16661189/a0249d8c-4426-11e6-9453-5d3a4b88c59c.png)

**Comment by AraHaan** [comment]
hmm I wonder if I would have to regenerate the sigitures if I compressed the exe's and all of the dll's too?

**Comment by cheat-engine** [comment]
if the .exe contents change you need a new .sig yes, but you won't be able to generate that .sig. You need to recompile the driver yourself, as the one that comes with the CE release refuses to talk to .exe's that aren't made by me specifically (security thing so malware can't use ce's driver which has my signature on it)

**Comment by AraHaan** [comment]
ok now it is doing this when I try to build it and I know I have the following installled.
[x] Visual Studio
[x] WDK 7600.16385.1
[x] Windows SDK 7.1
[x] Cmake
[x] make
[x] g++
[x] NASM
[x] Yasm (with CygWin)

And yet this happens.
```cmd
'command' is not recognized as an internal or external command,
operable program or batch file.
        1 file(s) copied.
'build' is not recognized as an internal or external command,
operable program or batch file.

error. Check the compile log
Press any key to continue . . .```

**Comment by AraHaan** [comment]
Ah I had to change ``build -cZ`` to ``"E:\WinDDK\7600.16385.1\bin\x86\amd64\build" -cZ`` And get ``'command' is not recognized as an internal or external command,
operable program or batch file.
        1 file(s) copied.
environment variable NTMAKEENV or OTOOLS must be defined

error. Check the compile log
Press any key to continue . . .``

**Comment by cheat-engine** [comment]
you need to be in the windows 7 build environment (I usuaklly use the x654 checked one)
go to start->all programs->windows driver kits->wdk 7600.16385.1->Build environments->windows 7->x64 checked build environment
(If you're in windows 10 good luck with that as that OS will combine the build environments into one stupid line where you can only hope it picks the correct one, so mess with the actual startmenu directory then instead)

then go to the folder where ce is installed (make sure there are no spaces in the path, and no non-ascii characters)
and run ce.bat

**Comment by AraHaan** [comment]
Ok build worked but the ``command`` file is still marked as missing.

**Comment by cheat-engine** [comment]
Don't worry about the command line. That is normal

**Comment by AraHaan** [comment]
ah oh and I got this just now after building is this normal too?
![6c66ce1f4e9f613fff5c1e4919f89afe](https://cloud.githubusercontent.com/assets/15173749/16685075/2c0b3750-44ce-11e6-944a-b72fb3cfd140.png)

**Comment by cheat-engine** [comment]
that's just a warning. It still works in windows 10

**Comment by AraHaan** [comment]
ah ok oh I just seen this it says there are more secured versions of it to. https://msdn.microsoft.com/en-us/library/xdsywd25.aspx

**Comment by hew115** [comment]
how do i solve the DBK32 error cause i can't find anything that should be causing it

**Comment by cheat-engine** [comment]
disable secure boot in your bios
