### ISSUE TITLE
7.0 Warning message at start appears on all starts

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#855]
Although the message says it will remember the choice it does not. I click on yes then close CE then start CE again and this message appears again

![image](https://user-images.githubusercontent.com/14368203/63694474-1178d000-c806-11e9-8e48-a1a02c98ca6d.png)

**Comment by cheat-engine** [comment]
emurpm.lua needs to be updated

This message is just to let you know that the assemblercode isn't correct but that if you let CE guess it's going to change that 0000000080000000 into ffffffff80000000 every time it encounters an instruction that has wrong significant bits set

**Comment by Symbai** [comment]
Thanks I fixed the lines. Would have been great if the message box tells me that there was an issue in a file. I had no idea why it was showing up at all.
