### ISSUE TITLE
Mono Find instances of class Crash

### ISSUE THREAD

**Issue by nik0la-vr** [cheat-engine/cheat-engine#856]
I'm trying to find out instances of a `xxxScript` class inside *Assembly-UnityScript.dll* in some Unity game. CE 7.0 crashes, but 6.8.3 gives back results in no time.

![Annotation 2019-08-26 220820](https://user-images.githubusercontent.com/37928424/63719992-7c4df980-c84e-11e9-95a8-38ea69a49407.png)
![Annotation 2019-08-26 220811](https://user-images.githubusercontent.com/37928424/63719993-7ce69000-c84e-11e9-834a-220b92df93d2.png)
![Annotation 2019-08-26 220816](https://user-images.githubusercontent.com/37928424/63719994-7ce69000-c84e-11e9-8bff-ecf8bccf1ec1.png)

**Comment by cheat-engine** [comment]
was the one in the first screenshot a self compiled version or the release build ?
and have a stacktrace?

**Comment by cheat-engine** [comment]
Might be fixed now. And try the files at https://cheatengine.org/download/08272019t1.rar

**Comment by nik0la-vr** [comment]
> was the one in the first screenshot a self compiled version or the release build
CE installed using installer. Sometimes it just crashes, sometimes it only shows that dialog, and sometimes it shows the dialog and then crashes.

> Might be fixed now. And try the files at https://cheatengine.org/download/08272019t1.rar
Still not working.

> and have a stacktrace?
How do you get stacktrace in Lazarus? Somehow now I managed to get 'please send *cedebug.txt* to DB' message. It was empty earlier, don't know if this is related.

```
First log message: 27.8.2019.
TAutoSizeCtrlData.FixControlProperties :TCECheckBox a=akTop old=:TEdit new=nil
Exception Access violation
  Stack trace:
  $00007FF90DCFD33C
  $00007FF90DCFBA4B
  $00007FF90AF22E02
  $00007FF90AE60D33
  $00007FF90AE65159
  $00007FF90AE648CA
  $00007FF90AE703D2
  $00007FF90AE70411
  $00007FF90AE70411
  $00007FF90AE6F8C2
  $00007FF90AE74AAC
  $00007FF90AE72E23
  $00007FF90AE74AAC
  $00007FF90D555B3A
  $00007FF90D555935
  $00000000008E4D3E  SETUPVISTAFILEDIALOG,
```

I just downloaded some random Unity game from itch.io and it works. It might be game specific?

**Comment by cheat-engine** [comment]
should be fixed now (on github)

in the meantime if youy can't recompile:
https://github.com/cheat-engine/cheat-engine/blob/54d2063ed6d4ac4efa5f789521ca00864523cc4e/Cheat%20Engine/bin/autorun/monoscript.lua#L948
Change this line to `v=1`
