### ISSUE TITLE
Why can't add my own function to an event of a control ?

### ISSUE THREAD

**Issue by Mozkileo** [cheat-engine/cheat-engine#857]
Using v6.8 , I can add any function to an event of a control. But in v7.0, when I select a function, it just create a new function with the form's name as prefix. For example, in form UDF1, when I select its envent OnShow to my function ShowAndAttach, it just create an empty function UDF1_OnShow. Maybe it is a new feature, but it is not good when I need to select many controls' event to a same function.

**Comment by mgrinzPlayer** [comment]
This is a FormDesigner bug.

**Comment by mgrinzPlayer** [comment]
This commit:
https://github.com/cheat-engine/cheat-engine/commit/cbde73aa39d6a09eb41626ce9805ffe067ac304a

**Comment by mgrinzPlayer** [comment]
Quick patch. Looks like it does the job:
```patch
Index: formdesignerunit.pas
===================================================================
--- formdesignerunit.pas	(wersja 4397)
+++ formdesignerunit.pas	(kopia robocza)
@@ -909,7 +909,6 @@
   old: TMethod;
 
   pn: string;
-  i: integer;
 
   NeedsToBeCreated: boolean;
   header: tstringlist;
@@ -921,22 +920,18 @@
   ns:=name;
   ns:=TComponent(GlobalDesignHook.LookupRoot).name+'_'+copy(ns, RPos('.',ns)+1);
 
- // name:=ns;
+  NeedsToBeCreated:=false;
 
+  if methodlist.IndexOf(name)<>-1 then
+    ns:=name
+  else
+    NeedsToBeCreated:=methodlist.IndexOf(ns)=-1;
 
   f.luaroutine:=ns;
   f.owner:=APersistent;
 
   try
-    pn:=APropertyPath;
-    i:=pos('.',pn);
-    while i>0 do
-    begin
-      pn:=copy(pn,i+1, length(pn));
-      i:=pos('.',pn)
-    end;
-
-
+    pn:=copy(APropertyPath, RPos('.', APropertyPath)+1);
     old:=GetMethodProp(APersistent, pn);
     if (old.code<>nil) and (tobject(old.Data) is TLuaCaller) then
       TLuaCaller(old.data).free;
@@ -945,16 +940,13 @@
     //failed to get the propertyname
   end;
 
-  i:=methodlist.IndexOf(ns);
-  NeedsToBeCreated:=i=-1;
-
   header:=tstringlist.create;
   result:=luacaller_getFunctionHeaderAndMethodForType(ATypeInfo, f, ns, header);
 
   if NeedsToBeCreated then
   begin
+    header.add('');
     mainform.frmLuaTableScript.assemblescreen.Lines.AddStrings(header);
-    header.add('');
   end;
 
   header.free;
```

**Comment by mgrinzPlayer** [comment]
There's other FormDesigner issue.
TMainMenu cause access violation.
steps: add mainmenu, close FormDesigner, open FormDesigner

**Comment by Mozkileo** [comment]
I got one way to solve this problem temporarily: when needing to add your own function, just save the form as LFM file, then edit the LFM file. But this may cause access violation.

**Comment by mgrinzPlayer** [comment]
Yeah, I added this functionality some time ago (https://github.com/cheat-engine/cheat-engine/commit/ac507aba5dd86383e3fed05c5623af9e79b140ec). Useful for converting from "Graphically designed" to "Lua script designed" and other things.

Anyway, if you need a binary with fixed method lookup, here:
[customRelease.zip](https://github.com/cheat-engine/cheat-engine/files/3554899/customRelease.zip)
(there is still problem with TMainMenu)

**Comment by Mozkileo** [comment]
Thanks! This release solves my problem perfectly. It's worth mentioning that saving as LFM file is a very useful way to create lots of controls quickly.
