### ISSUE TITLE
ultimap2 cpu?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#86]
![cpu-z](https://cloud.githubusercontent.com/assets/18622105/16738188/9f11d458-47cf-11e6-86de-1328c006e2a8.png)

intel core i5 2500 

windows7 x64

ultimap 2 record/ pause

Sorry, but your CPU seems to be lacking the Intel Processor Trace feature which Ultimap2 makes use of

It is not supported i5 2500 cpu?(ultimap2)

Or is it not implemented ?

frmultimap2unit.pas
if (CPUID(7,0).ebx shr 25) and 1=0 then
        raise exception.create('Sorry, but your CPU seems to be lacking the Intel Processor Trace feature which Ultimap2 makes use of');

buy the latest Intel CPU?

**Comment by cheat-engine** [comment]
yup. as far as i know only intel 6xxx cpu's have the processor trace feature.

**Comment by kitty8904** [comment]
intel skylake i7 6700?

cpu-z instructions options?


I will be buying what products ?

**Comment by rzndsa** [comment]
ultimap 2 only for intel again?

**Comment by kitty8904** [comment]
amd cpu no support

https://github.com/cheat-engine/cheat-engine/blob/6f49b8e2ef524405133e17016d8b0bb25cf5fef1/Cheat%20Engine/frmUltimap2Unit.pas#L809

http://blogs.intel.com/blog/processor-tracing/


It seemed to be buying the latest CPU
