### ISSUE TITLE
MainForm GUI issue (related with "undo scan" button)

### ISSUE THREAD

**Issue by mgrinzPlayer** [cheat-engine/cheat-engine#864]
Removed all plugins and autorun scripts to be sure.

Steps to reproduce:

open ce
![obraz](https://user-images.githubusercontent.com/9157726/63879763-a0cfe000-c9cc-11e9-95da-b88025808efd.png)

resize it horizontally to make it bigger
![obraz](https://user-images.githubusercontent.com/9157726/63879780-aa594800-c9cc-11e9-9e8e-7d1ec9d450fa.png)

close it, open ce again, you will get
![obraz](https://user-images.githubusercontent.com/9157726/63879819-be9d4500-c9cc-11e9-8d38-3e78942b58a9.png)

resize it horizontally to make it smaller, foundlist gone
![obraz](https://user-images.githubusercontent.com/9157726/63879863-d96fb980-c9cc-11e9-8bf1-5e74145f98d7.png)

**Comment by cheat-engine** [comment]
I have not been able to reproduce yet

**Comment by mgrinzPlayer** [comment]
fixed

**Comment by mgrinzPlayer** [comment]
Nope, to reproduce it you have to untick "show undo button".

**Comment by mgrinzPlayer** [comment]
now, it's OK.
