### ISSUE TITLE
Random buggy behavior in Memory Viewer

### ISSUE THREAD

**Issue by dsasmblr** [cheat-engine/cheat-engine#869]
**STEPS TO REPRODUCE:**

**1.** Find an address of interest, then browse its memory region:

![1](https://user-images.githubusercontent.com/22781064/64058491-0ad9b800-cb7a-11e9-9a8b-e4592f2a6d70.png)

**2.** Double-click on the value in the Memory Viewer window, then click OK. (NOTE: I have my display type set to Float, if it matters.)

![2](https://user-images.githubusercontent.com/22781064/64058492-0b724e80-cb7a-11e9-9339-b57e890fab1a.png)

**Result:** The memory region view shifts, as demonstrated below:

![3](https://user-images.githubusercontent.com/22781064/64058493-0ad9b800-cb7a-11e9-8dd6-eeb155e26512.png)

**NOTE**: This behavior happens sporadically. I've been able to reproduce it in varying combinations of the steps above, and the following:

**-** Double-click on the value, change it, then click OK.

OR

**-** Double-click on the value, then click Cancel.

OR

**-** Double-click on the value, change it, then click Cancel.

**Comment by cheat-engine** [comment]
I haven't been able to reproduce this yet and I also don't see any code that could have changed the base address

Does it always end in an address with 3 0's  ?

No stuck keys like shift, ctrl or alt? 
It doesn't jump back to the instruction currently shown in the assembler (ctrl+space)

**Comment by dsasmblr** [comment]
I'm fairly certain it wasn't stuck keys. It would always jump back to three 0s first, and I could sometimes have the issue repeat and it would jump even more drastically to another address. That one was more sporadic, though.

Will close for now as I haven't had it happen again, but if it does, I'll save a recording of it and re-open.
