### ISSUE TITLE
Size Mismatch

### ISSUE THREAD

**Issue by GuardianMajor** [cheat-engine/cheat-engine#87]
I have been noticing for a while now, that when you search for a string, say something that is 44 characters long, and then you replace it with exactly 44 character long string, and then size changes from string[44] to string[46] or string[48], seemingly with no rhyme or reason.

![search](https://cloud.githubusercontent.com/assets/5274181/16791254/f482c60c-4871-11e6-926a-eee254bc637e.png)

![change](https://cloud.githubusercontent.com/assets/5274181/16791258/fa789258-4871-11e6-813c-5ddc60ab8690.png)

Anyone encounter this and know why? Is there a way to avoid this happening? Mainly the question is, why is it happening? TIA.

**Comment by cheat-engine** [comment]
Is the string set to unicode or not ?
what is the string you're replacing it with ? Does it contain non ascii characters ?
If it does contain nonascii characters, then it is possible that a string requires more bytes to encode it

**Comment by GuardianMajor** [comment]
No, Unicode is not checked.

No, they are identical in the sense that they are ONLY ALPHA and separated by _ (underscore) that's it. Same format for search/replace.

No, no non-ascii characters.

That's what I thought too but given the strings are encoded exactly the same, didn't see that as the problem.

**Comment by GuardianMajor** [comment]
If it helps, the first string is `original_string_positive_display_alpha_teams` and then being replaced by `updated_string_negative_redisplay_beta_teams` - let me know if you need more.

**Comment by GuardianMajor** [comment]
Also in response to your earlier question, here is what my settings are for the search

![settings](https://cloud.githubusercontent.com/assets/5274181/16825275/2693331e-4928-11e6-9171-2020f93b0fa8.png)

**Comment by cheat-engine** [comment]
ah ok. I see it's the length.
as a bypass for now:
when editing, resize the window so the text fits in one line

**Comment by GuardianMajor** [comment]
Thank you, glad you have an idea what's going on. I appreciate it.

I know this might sound really really dumb, but what do you mean by resize to make sure it fits on one line? I want to make sure I understand your suggestion, since as you can see in the screenshot, it is wide enough to cover the whole string, do you mean on the replace window inputbox?

Again, sorry, I am not trying to be dense, just want to make sure I get what you are suggesting correctly. TIA.

**Comment by GuardianMajor** [comment]
Ok got it, that's what i thought but wanted to be sure that's what you meant, will do.

While I can't remember off hand if that was the case or not, I am pretty sure the box was wide enough to get it on one line but I will make sure, thanks.

I'll let you know how it goes.

**Comment by mgrinzPlayer** [comment]
you can check my custom builds:
https://googledrive.com/host/0BwMAnE6mjogMTmpYMGstY1NPQnc/

files from July 14, 2016

**Comment by GuardianMajor** [comment]
Thank you, will take a look at it.
