### ISSUE TITLE
address list Active CheckBox Size Bug

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#873]
![62917193-46ccf900-bdd6-11e9-94c5-d3cf21b23d5d](https://user-images.githubusercontent.com/18622105/64073957-04655080-cce0-11e9-8d19-d4e0951988da.gif)
add address click

list address active check box size up

add address click box cancel -> active check box size down

**Comment by cheat-engine** [comment]
I can't reproduce

**Comment by kitty8904** [comment]
MY PC 4K monitor (3840 x 2160)

add address list click -> active check box size up

add address list checkbox cancel -> active check box size down
