### ISSUE TITLE
formSettings initial position calculation - SIGSEGV

### ISSUE THREAD

**Issue by mgrinzPlayer** [cheat-engine/cheat-engine#874]
1 set scaling to 175%
2 launch CE
3 click "Settings" button

gdb will show:
0x0000000000415b2a in _FPC_SysAllocateThreadVars ()

**Comment by cheat-engine** [comment]
which windows version is this?

**Comment by mgrinzPlayer** [comment]
It should be 175% of normal DPI, which is 168DPI. Sorry about that.

Tried compiled from SVN and official CE7.0 (from 29.08.19).

Steps:
- set scaling to 175% ()
- remove key "HKEY_CURRENT_USER\Software\Cheat Engine\Window Positions 168"
- launch CE
- click settings


Now the weird part.
CE 64 bit always crash.
If you launch CE 32bit, it will act weird, click settings, you will see 1-3 second freeze, then Settings will show up.
You can not click "cancel" button in "settings" window. Alt+F4 will close it. Main CE window will freeze, again you can close it with ALT+F4

**Comment by mgrinzPlayer** [comment]
OK. Sorry again. This is the easiest way to reproduce, forget about foreign DPI values.

Steps:
- remove key "HKEY_CURRENT_USER\Software\Cheat Engine\Window Positions 96"
- remove other keys "HKEY_CURRENT_USER\Software\Cheat Engine\Window Positions xxx" if you are using Windows scaling
- launch CE
- move main window up
- click settings
- 64bit CE will hang
- 32bit CE will act weird. you will get 1-3 second freeze, then Settings will show up. You can not click "cancel" button in "settings" window. Alt+F4 will close it. Main CE window will freeze, again you can close it with ALT+F4.

So, problem is when there is no saved "formSettings" position, and the main window is set like this
MainForm.Top = 19 -- can be less than 19 

MainForm.Top = 20 -- and above 20 works fine

**Comment by mgrinzPlayer** [comment]
For 32bitCE, profile "debug-nomt 32-bit", clean all and build
compiled on Lazarus "Debug IDE" profile
Windows scaling set to 100% (96DPI)

ExecuteBefore set to "remove saved positions.cmd"
cmd file content:
```
reg delete "HKCU\Software\Cheat Engine\Window Positions 96" /v "formSettings Position" /f
reg delete "HKCU\Software\Cheat Engine\Window Positions 96" /v "MainForm Position"     /f
exit 0
```

Result:
![obraz](https://user-images.githubusercontent.com/9157726/64103048-86518a00-cd71-11e9-8bc9-f95dbe757780.png)

**Comment by cheat-engine** [comment]
should be fixed now

**Comment by mgrinzPlayer** [comment]
fixed.
