### ISSUE TITLE
Memory Scan: more than 1 TAB freezes CE v.7.0

### ISSUE THREAD

**Issue by M-A-T-5** [cheat-engine/cheat-engine#878]
After I upgraded to CE v. 7 (one week ago) I´m not able to scan memory with more than one TAB.
When I change between tabs CE freezes.

I´m using Win10, 64 bits, 8Gb. RAM.

**Comment by cheat-engine** [comment]
might be fixed in the github now

**Comment by TheK0tYaRa** [comment]
Almost the same stuff with heavy scans on precompiled CE 7.0 (100000 results and up)

**Comment by cheat-engine** [comment]
Weird, it should be impossible to click on the tabbar while a scan is going on. 
I'll check

**Comment by TheK0tYaRa** [comment]
It IS impossible. The problem occurs upon switching while the scan doesn't run.

**Comment by cheat-engine** [comment]
fixed now

**Comment by M-A-T-5** [comment]
I downloaded the version available at "https://www.cheatengine.org/" and did a test yesterday.
The problem is just minimized. It still necessary wait for a long time after TAB change/swap to CE goes back working.

**Comment by cheat-engine** [comment]
ce 7.0: release date is August 20 2019

check the date this was posted

**Comment by M-A-T-5** [comment]
Ok. I´m a basic user of CE, I´m not a programmer either (saying this because I don´t have tools or knowlodge to compile a source code if it´ll be necessary).

I looked on GitHub but the version 7 available here is from August/2019 too. 
Where can I find the fixed version?
