### ISSUE TITLE
auto assembler nop bug

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#880]
<img width="821" alt="bug1" src="https://user-images.githubusercontent.com/18622105/64245177-696db000-cf45-11e9-939d-d7159ca5af4c.png">
<img width="598" alt="bug2" src="https://user-images.githubusercontent.com/18622105/64245178-696db000-cf45-11e9-8a88-cd35970c58f3.png">

autoassembler 

je jne -> nop add?? -> memory bug

nop [eax+00] add?? ->memory nop bug??

**Comment by mgrinzPlayer** [comment]
nop [eax+00]  those are "special" nops.

use short jumps, e.g.
je short check

**Comment by kitty8904** [comment]
Is it intended coding? Why did you suddenly add a NOP?

**Comment by mgrinzPlayer** [comment]
Yes intended. CE adds nops for a long time. Now it just adds different type of nops.

Maybe DD could add comments (except "nop a" and "nop b") like I did manually here: 
![obraz](https://user-images.githubusercontent.com/9157726/64246693-90a88b00-cf0d-11e9-80fa-39aa5e33437d.png)
