### ISSUE TITLE
Memory view - focus / copy & paste bug

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#882]
1. Open memory view and edit some bytes by typing
2. Paste byte string from clipboard via CTRL+V
3. It's inserted at wrong position (not at current caret position but at position of first click)

Demo:
![Untitled Project](https://user-images.githubusercontent.com/14368203/64289693-367ee880-cf54-11e9-8db8-5c80247144b4.gif)

**Comment by cheat-engine** [comment]
fixed
