### ISSUE TITLE
lua size_t delete compile error

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#885]
lua.pas 

size_t = Cardinal;  -> delete

lua_objlen function (size_t) -> ??

LuaStream.pas(219,16) Error: Can't determine which overloaded function to call

**Comment by mgrinzPlayer** [comment]
Are you using Lazarus 2.0.0 and FPC 3.2.0 revision 42444?

**Comment by kitty8904** [comment]
> Are you using Lazarus 2.0.0 and FPC 3.2.0 revision 42444?

No lazarus 2.0.4 , FPC 3.0.4 version

Do I need to update to 3.4.0?

  Not a lua.pas reference issue?

**Comment by mgrinzPlayer** [comment]
Just in case someone finds this issue (with keys: lua_objlen, determine, overloaded)
```diff
-count:=min(lua_objlen(L, 1), lua_tointeger(L, 2)) //prevent the length from exeeding the table
+count:=min(integer(lua_objlen(L, 1)), lua_tointeger(L, 2)) //prevent the length from exeeding the table
```

Read this: https://github.com/cheat-engine/cheat-engine/issues/918
