### ISSUE TITLE
CE opens and immediately closes.

### ISSUE THREAD

**Issue by Chris0x1337** [cheat-engine/cheat-engine#888]
I uninstalled badlion (all files and folder gone from installed directory) and rebooted, disabled av (even though it doesn't even flag ce as a virus) and all to no avail
help pls ;-;

**Comment by cheat-engine** [comment]
Are you sure you rebooted and didn't just shut down and back on? (windows 10 fakes that)

Try restarting again

**Comment by Chris0x1337** [comment]
I am currently reinstalling windows because of some unrelated driver issues, it should be fine when I get round to installing ce again. Thanks for the help anyway.

**Comment by cheat-engine** [comment]
Also use the badlion uninstaller next time as it copies itself to your system32 folder in windows
