### ISSUE TITLE
I can't install CE

### ISSUE THREAD

**Issue by Leonellusie** [cheat-engine/cheat-engine#889]
I can't install it. I installed the setup over 5 times and it didn't work. I deleted BadlionClient out of my pc and still can't open (and then rebooted my pc). What do I do? (I'm on Windows 7)

**Comment by cheat-engine** [comment]
Don't just delete badlion. Actually uninstall badlion as it infects your windows system32 folder as well

afterwards restart  (don't shut down and back on, actually restart)

**Comment by Leonellusie** [comment]
But I can't find badlion...

**Comment by Leonellusie** [comment]
Where do I find it? I cant find it in uninstall panel

**Comment by cheat-engine** [comment]
Open an admin command prompt and execute
'
net stop BadlionAnticheat
sc delete BadlionAnticheat
'

**Comment by Leonellusie** [comment]
I  tried with the administrator command prompt and it STILL sends out an error. The error says "The service name is invalid".

**Comment by cheat-engine** [comment]
ok so not error 5 access denied.
in that case try restarting now

**Comment by Leonellusie** [comment]
I restarted and nothing changed, it's still the same, ce is closing itself, EVEN THOUGH I did everything you told me. I don't know what to do next. :(

**Comment by cheat-engine** [comment]
execute
`driverquery /v > %HOMEPATH%\desktop\driverlist.txt` and then upload driverlist.txt here

**Comment by Leonellusie** [comment]
![picture](https://user-images.githubusercontent.com/55061246/64909309-3e3c4b00-d713-11e9-8d7e-aa84c2cc567b.png)
Did you mean this list?

**Comment by cheat-engine** [comment]
no, the driverlist.txt file that appears on your desktop after executing 
`driverquery /v > %HOMEPATH%\desktop\driverlist.txt`

**Comment by Leonellusie** [comment]
I executed that code but it for some reason didn't show up on my desktop.

**Comment by cheat-engine** [comment]
then inside an admin command prompt execute
`driverquery /v > c:\driverlist.txt` and upload c:\driverlist.txt here
(make sure you run as admin)

**Comment by Leonellusie** [comment]
Here is the driver list
[driverlist.txt](https://github.com/cheat-engine/cheat-engine/files/3613956/driverlist.txt)

**Comment by Leonellusie** [comment]
Why are you not responding?

**Comment by Leonellusie** [comment]
I'm still waiting for your respond.
