### ISSUE TITLE
Skipping tutorial levels

### ISSUE THREAD

**Issue by mehlon** [cheat-engine/cheat-engine#891]
Pressing the "Skip" button on a tutorial yields you a pop-up saying "BOO".
I feel like this is somewhat unnecessary, and annoying to the user.
What are your thoughts on this?

**Comment by FreeER** [comment]
its fine to me, I'm not skipping through it that often since it's not an actual game that I'm going to replay.
maybe have a registry key set when step 9 is successfully completed that disables it?

**Comment by cheat-engine** [comment]
Originally it said :"loser" but people cried like babies over that so i changed it to "Boo"

if you wish to skip a step use the password

**Comment by jordanbtucker** [comment]
> Originally it said :"loser" but people cried like babies over that so i changed it to "Boo"
> 
> if you wish to skip to a step use the password, or endure the traumatic experience of that popup

Are you able to provide a real reason to keep the BOO popup? I don't see a benefit of having it, and it just annoys users.
