### ISSUE TITLE
Cheat Engine 7.0 doesnt start

### ISSUE THREAD

**Issue by AysYT** [cheat-engine/cheat-engine#898]
i have uninstallt badlion client but i still doesn't work :/

**Comment by cheat-engine** [comment]
Restart your system.  Don't shutdown abd back on. Actual reboot

**Comment by SkylordBrebro** [comment]
https://gyazo.com/e42de03f7e3d816a67e01b1b8a97e5ce
For whatever reason it does not work for me. I've reinstalled, restarted and rebooted and nothing seems to work.

**Comment by mgrinzPlayer** [comment]
Did you launch windowsrepair.exe?
