### ISSUE TITLE
breakpoint bsod

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#906]
win10

i9 9900k

ram 32g

f5 hardware breakpoint bsod(dbvm load)

global debug on off Does not matter

Cheat Engine6.7 ~ 7.0 all version

f5 find read/write access breakpoint & f5 trace breakpoint ->bsod

nvm thread bug??

Blue screen frequently occurs while using the latest Windows 10(hardware breakpoint)

Is the hardware breakpoint problem unsolvable?

////////////////////////////////////////////////////////////

I currently have no problem with dbvm breakpoint
(hardware breakpoint -> bsod)

///////////////////////////////////////////////////////////

Why use hardware breakpoints -> stack view function 

I've been using a cheat engine for a long time, but the blue screen problem me sad

**Comment by cheat-engine** [comment]
Unsolveable on high speed hitting breakpoints. 

Also, never break in kernelmode, because if it happens when the gui is locked you won't be able to continue as it will wait for the gui to unlock the gui.  
Best solution is writing a display driver for DBVM
