### ISSUE TITLE
Find out what code this function has called

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#909]
I would appreciate a breakpoint method where when it breaks, it automatically continues until the code returns and then log this address.

This is useful if there a function which gets accessed all the time but I need to find out where its called from at a specific moment. I could see it in real time which new address gets logged at such a moment.

**Comment by cheat-engine** [comment]
Use 'find what addresses this code accesses' on the ret instruction

**Comment by Symbai** [comment]
Thanks this works
