### ISSUE TITLE
GUI bug with "Generate groupscan command" button in mainunit

### ISSUE THREAD

**Issue by rzndsa** [cheat-engine/cheat-engine#91]
https://youtu.be/IIFum5WAx0U

Previously this button appeared instead of "Scan Type". Now it prevents to choose the "Value Type".

**Comment by rzndsa** [comment]
dpiaware patch will be available only for mainform or for all CE forms in the future?

**Comment by cheat-engine** [comment]
fixed now.
as for dpiaware, no idea.
If I enable dpi aware it may cause severe issues for tables/trainers that don't expect it. (perhaps a separate manifest or exe with dpi enabled or not)

And windows 10 seems to do a decent job at dpi scaling as opposed to windows 7(really bad), so it's not that urgent yet.  (at least it looks usable in windows 7 with high dpi now, but still some annoyances like settings, etc...)
