### ISSUE TITLE
How to use debug_continueFromBreakpoint ?

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#911]
How to use "debug_continueFromBreakpoint" without CE throwing a message box "something happened" ? The following ways all throw the messagebox

```
function debugger_onBreakpoint()
  debug_continueFromBreakpoint(0)
end
```
```
function debugger_onBreakpoint()
  debug_continueFromBreakpoint(co_run)
end
```
```
function debugger_onBreakpoint()
  debug_continueFromBreakpoint("co_run")
end
```

**Comment by cheat-engine** [comment]
try `return 1` instead and see how that goes

**Comment by Symbai** [comment]
Works. Do you know how to access the XMM registers in this function or are they missing (and if they are, should I create a new issue about this?)

**Comment by cheat-engine** [comment]
debug_getContext(true)
that will set the XMM registers 
Keep in mind they are bytetables so you need to convert them to types you can understsnd

**Comment by Symbai** [comment]
Thank you
