### ISSUE TITLE
Copying Is Broken

### ISSUE THREAD

**Issue by exassasinx** [cheat-engine/cheat-engine#916]
Copying a script is not working due to some weird characters being added to the end of the script
![image](https://user-images.githubusercontent.com/20860039/65757892-9b3ff400-e14a-11e9-86c4-abb57384a4b9.png)

**Comment by cheat-engine** [comment]
Is already fixed in https://github.com/cheat-engine/cheat-engine/commit/9fa47fa53e52b8dea386b7d324a17c9731b581e6

**Comment by exassasinx** [comment]
> Is already fixed in [9fa47fa](https://github.com/cheat-engine/cheat-engine/commit/9fa47fa53e52b8dea386b7d324a17c9731b581e6)

okay thanks!
