### ISSUE TITLE
Can't search for value with pointermap

### ISSUE THREAD

**Issue by TheK0tYaRa** [cheat-engine/cheat-engine#917]
When i choose "Scan for adress with value" and check "use pointermap" it falls back to adress search

**Comment by cheat-engine** [comment]
how about compare to pointermap instead of use pointermap?

Because 'use pointermap' will scan using the pointermap only. Which means it won't touch the target process at all

**Comment by TheK0tYaRa** [comment]
Then i don't get how i got the pointers for all the other resources by making a pointermap at the beginning, but that still works, thanks!
