### ISSUE TITLE
No active searches, 2 tabs, lag upon switching, master branch

### ISSUE THREAD

**Issue by TheK0tYaRa** [cheat-engine/cheat-engine#919]
Switching to 612644 result tab results in CE "not responding" without even doubleclicking.

**Comment by cheat-engine** [comment]
yup

**Comment by TheK0tYaRa** [comment]
Sometimes it takes more than 10 minutes btw (mainly when there is more than 3M values)
For the fact - cpu is amd athlon x4 880k at 4.4GHz overclocked stable and ram is 1866 MHz  ddr3 not overclocked stable

**Comment by cheat-engine** [comment]
fixed now

**Comment by TheK0tYaRa** [comment]
It lagged again somewhy

**Comment by TheK0tYaRa** [comment]
Yes, while switching tabs. Laggy tab had 270k values and it didn't respond for 27 seconds

**Comment by cheat-engine** [comment]
Are you compiling using lazarus 2.0.0 ? (so not 2.0.2 or 2.0.4)
I have opened multiple tabs, scanned for 0 byte on each, and then switched between tabs each at a different selection and it works fine

**Comment by TheK0tYaRa** [comment]
Lazarus 2.0.4, will try switching

**Comment by cheat-engine** [comment]
Which precompiled version do you mean? the release of 7.0?  You have to wait for 7.1 for new fixes to be available

**Comment by TheK0tYaRa** [comment]
Understood

**Comment by TheK0tYaRa** [comment]
It works for now so i suppose it's fixed for good. Keep up the good work!
