### ISSUE TITLE
Default table name = name of first opened process

### ISSUE THREAD

**Issue by rzndsa** [cheat-engine/cheat-engine#92]
1) Open process1.exe
2) Open process2.exe
3) Try to save the table
The default name of table will be "process1.CT" (not process2.CT)

**Comment by mgrinzPlayer** [comment]
Do not open process1.exe at all?

**Comment by rzndsa** [comment]
https://youtu.be/4qLc8UQ6szo

**Comment by Yt-trium** [comment]
Copy of issue #29
