### ISSUE TITLE
Compiled a second ago version says "Update available"

### ISSUE THREAD

**Issue by TheK0tYaRa** [cheat-engine/cheat-engine#920]
Last pull was 8 minutes ago

**Comment by mgrinzPlayer** [comment]
You have to change it yourself Project options -> Version Info
Change build number 6008

**Comment by cheat-engine** [comment]
the versionnumber is stored in the lpi which is kinda annoying as it also contains files open and positions and lots of userdefined things which is troublesome for other people when that one gets updated (their view changes will get undone)

**Comment by TheK0tYaRa** [comment]
So i suppose this is lazarus saying "i won't change the file becuase i cached it", right? I suppose downloading precompiled one won't hurt.

**Comment by mgrinzPlayer** [comment]
@cheat-engine just an idea. Maybe you could do this:
![obraz](https://user-images.githubusercontent.com/9157726/65918490-13701900-e3da-11e9-8fa4-7cc5c82a4f8d.png)
then save project.

Then add cheatengine.lps to .gitignore, or all *.lps. Then commit new lpi  file with this setting.
