### ISSUE TITLE
Lua extension, 32bit CE , (self)symhandler, getAddressSafe, SIGSEGV

### ISSUE THREAD

**Issue by mgrinzPlayer** [cheat-engine/cheat-engine#924]
I have a Lua extension which doesn't work with 32bit CE. I narrowed it to just two lines:
```Lua
local CEProcName=enumModules(getCheatEngineProcessID())[1].Name
local start=getAddressSafe(CEProcName,true)
```

32bit CE doesn't launch. Lazarus shows SIGSEGV.

**Comment by cheat-engine** [comment]
the eventqueue for the symbolhandler was looking at the targeted process symbolhandler instead of the selfsymhandler

should be fixed now

**Comment by mgrinzPlayer** [comment]
Weird that 64bit CE already has that symbol loaded and 32bit doesn't and we have to "wait".

Tested. Fixed. Thank you.

**Comment by cheat-engine** [comment]
Might be faster or the freed memorybisn't reused that quickly
