### ISSUE TITLE
Lua print to background

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#925]
I'm using lua PRINT in a script but sadly it brings CE lua window to foreground (game is running in window mode) which is super annoying. Is there a way to print something without CE is bringing itself as foreground and focused application?

**Comment by Symbai** [comment]
Ok uncheck "show on print" did the trick

**Comment by mgrinzPlayer** [comment]
you can add this line after first PRINT in your Lua script:
```
getLuaEngine().cbShowOnPrint.Checked = false
```
