### ISSUE TITLE
Unable to build with Lazarus

### ISSUE THREAD

**Issue by pacapelep** [cheat-engine/cheat-engine#926]
Hi, I'm trying to build cheat engine in Lazarus but I'm getting some error messages and i can't get it to compile. I would just download it but the link looks shady lol. Can someone help please? :)

Here are two of them I'm not sure what others there might be.
tracerignore.pas(43,39) Error: Wrong number of parameters specified for call to "LoadFromFile"
Error: Found declaration: LoadFromFile(const AnsiString);

**Comment by frustreated** [comment]
closed issues should gave you answer，i compiled cheat engine by reading the closed issues， wish you sucess

**Comment by pacapelep** [comment]
okay thanks

**Comment by frustreated** [comment]
https://github.com/mgrinzPlayer/CheatEngineUpDeluxe
use this to compile ,but i tried ,there still have or may be have errors. 
用这个编译，不过我尝试了下，仍旧有报错
from my computer error as follows
我的如下报错

```
error, find this
Building project "CheatEngine 32bit"
系统找不到指定的路径。

Building project "CheatEngine 64bit"
系统找不到指定的路径。
请按任意键继续. . .
```
other files are compiled OK
其他的都正常编译
