### ISSUE TITLE
AccessViolation - errorlog.txt

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#929]
Where do I find this errorlog.txt CE wants me to send it to you on an accessviolation?

**Comment by cheat-engine** [comment]
In the CE exe folder.
But only if you have the debugsymbols gor that build

**Comment by Symbai** [comment]
Ah ok that explains why I couldnt find it. Maybe its worth shipping with official release then?

**Comment by cheat-engine** [comment]
It should have created that file when it gave the message(just close ce first)

also that message shows if you used the debug log option under the help menu

**Comment by mgrinzPlayer** [comment]
Just checked the source. There's no errorlog.txt. There's only cedebug.txt

**Comment by mgrinzPlayer** [comment]
@cheat-engine looks like currently GetDebugLogger log file sometimes is not complete, because it is not flushed after write.

can be fixed with
```
llf.CloseLogFileBetweenWrites:=true;
```

**Comment by Symbai** [comment]
@mgrinzPlayer Is correct. There is no error file but cedebug with the following content:

```
First log message: 06.10.2019
TAutoSizeCtrlData.FixControlProperties :TCECheckBox a=akTop old=:TEdit new=nil
TAutoSizeCtrlData.FixControlProperties :TShape a=akTop old=:TEdit new=nil
TAutoSizeCtrlData.FixControlProperties :TShape a=akLeft old=:TEdit new=nil
TAutoSizeCtrlData.FixControlProperties :TLabel a=akTop old=:TEdit new=nil
TAutoSizeCtrlData.FixControlProperties :TLabel a=akLeft old=:TEdit new=nil
TAutoSizeCtrlData.FixControlProperties :TShape a=akTop old=:TEdit new=nil
TAutoSizeCtrlData.FixControlProperties :TShape a=akLeft old=:TEdit new=nil
TAutoSizeCtrlData.FixControlProperties :TLabel a=akTop old=:TEdit new=nil
TAutoSizeCtrlData.FixControlProperties :TLabel a=akLeft old=:TEdit new=nil
TAutoSizeCtrlData.FixControlProperties :TShape a=akTop old=:TEdit new=nil
TAutoSizeCtrlData.FixControlProperties :TShape a=akLeft old=:TEdit new=nil
TAutoSizeCtrlData.FixControlProperties :TLabel a=akTop old=:TEdit new=nil
TAutoSizeCtrlData.FixControlProperties :TLabel a=akLeft old=:TEdit new=nil
TAutoSizeCtrlData.FixControlProperties :TShape a=akTop old=:TEdit new=nil
TAutoSizeCtrlData.FixControlProperties :TShape a=akLeft old=:TEdit new=nil
TAutoSizeCtrlData.FixControlProperties :TLabel a=akTop old=:TEdit new=nil
TAutoSizeCtrlData.FixControlProperties :TLabel a=akLeft old=:TEdit new=nil
TAutoSizeCtrlData.FixControlProperties :TShape a=akTop old=:TEdit new=nil
TAutoSizeCtrlData.FixControlProperties :TShape a=akLeft old=:TEdit new=nil
TAutoSizeCtrlData.FixControlProperties :TLabel a=akTop old=:TEdit new=nil
TAutoSizeCtrlData.FixControlProperties :TLabel a=akLeft old=:TEdit new=nil
```

**Comment by mgrinzPlayer** [comment]
@Symbai Do you have "Access Violation" but not have "Stack trace"?


I do not have "Access Violation" but I also get this in cedebug.txt:
First log message: 07.10.2019
TAutoSizeCtrlData.FixControlProperties :TCECheckBox a=akTop old=:TEdit new=nil

**Comment by cheat-engine** [comment]
the file gets overwritten when a new ce starts

**Comment by Symbai** [comment]
I think the issue can be closed since the original question has been answered. The errorlog is missing because of missing symbol files. Cedebug appears to be something unrelated.
