### ISSUE TITLE
Cant open Cheat engine

### ISSUE THREAD

**Issue by MrCookieDoo** [cheat-engine/cheat-engine#942]
I have tried everything to get Cheat engine 7.0 to open but nothing works.

**Comment by cheat-engine** [comment]
Have you uninstalled badlion and restarted your computer (not shutdown and back and back on, but actual retart)

And have you tried uninstalling your anti virus and reboot after that?

**Comment by MrCookieDoo** [comment]
Its a problem with badlion? the minecraft client?

**Comment by MrCookieDoo** [comment]
Wow that is actually stupid, i deleted badlion and it works. Thanks allot <3
