### ISSUE TITLE
RVA to VA

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#945]
I got a relative virtual address and offset and would like to retrieve the 64bit address in memory. Is this somehow possible?

**Comment by cheat-engine** [comment]
what kind of rva? Rva based on a pe header section or different?

Normally you can do modulename+rva to get the va, butbif it's a pe rva then modulename+pesectionprederedbase-modulename+rva

**Comment by Symbai** [comment]
PE RVA, a small converter utility would be nice.

**Comment by cheat-engine** [comment]
just open the peinfo screen in ce and load the module and find the sectionbyoir rva belongs ti
then decrease the rva you have with the prefered base address. The resulting address can be added to the modulebase (modulename in ce) to get the correct address

**Comment by Symbai** [comment]
Thanks, I missed the PE tool
