### ISSUE TITLE
TImageHint not visible [signed CT file]

### ISSUE THREAD

**Issue by mgrinzPlayer** [cheat-engine/cheat-engine#947]
https://github.com/cheat-engine/cheat-engine/blob/8ff94eba664c82cdf4a9417cfb2bad4fafe1b9de/Cheat%20Engine/OpenSave.pas#L754-L760

If imagepos is 7, "no image, text only, mouseenter pops up image, mouseleave hides it",
TImageHint doesn't show up

I checked p.x and p.y values and they are correct:
https://github.com/cheat-engine/cheat-engine/blob/8ff94eba664c82cdf4a9417cfb2bad4fafe1b9de/Cheat%20Engine/OpenSave.pas#L257-L263

**Comment by mgrinzPlayer** [comment]
CE6.8.3 - it works
CE7.0 - doesn't

Probably because Lazarus>=2.0.0

**Comment by cheat-engine** [comment]
fixed
