### ISSUE TITLE
CT file drop overwrites existing table

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#952]
1. Open table1.ct by double clicking on it
2. Drag and drop table2.ct on the cheat engine window

Result = table1 content is overwritten / gone
Expected = At least a message asking me if I want to merge or overwrite it

**Comment by mgrinzPlayer** [comment]
I tried and can not reproduce. To overwrite you need additional step, this one:
3. save (ctrl+s)

To fix this issue the patch would be this:
```diff
diff --git a/Cheat Engine/MainUnit.pas b/Cheat Engine/MainUnit.pas
index 5bf2d1d3c..aa0dd8c62 100644
--- a/Cheat Engine/MainUnit.pas	
+++ b/Cheat Engine/MainUnit.pas	
@@ -3091,6 +3091,8 @@ procedure TMainForm.FormDropFiles(Sender: TObject; const FileNames: array of str
     if CheckIfSaved then
     begin
       LoadTable(filenames[0], False);
+      Savedialog1.FileName := filenames[0];
+      Opendialog1.FileName := filenames[0];
       reinterpretaddresses;
     end;
   end;
```

**Comment by Symbai** [comment]
Proof that its reproducable:
![ezgif com-optimize](https://user-images.githubusercontent.com/14368203/67626108-75d00400-f836-11e9-9d0f-102735da686d.gif)

**Comment by mgrinzPlayer** [comment]
Weird. I can reproduce only with additional third step.
About that gif, no offense, I don't see sdg.ct is overwritten.

I searched for all instances of "savetable()" function in the CE source code:
- inside "TfrmExeTrainerGenerator.btnGenerateTrainerClick" procedure - not your case
- inside "TfrmTrainerGenerator.Button5Click" procedure - not your case

- inside "lua_saveTable" function - maybe you have some Lua extension which automatically autosaves CT. Try temporarily rename autorun folder.

for those you will have to click or press something, so, not your case:
- inside "TMainForm.Save1Click" procedure
- inside "TMainForm.miSaveClick" procedure 
- inside "TMainForm.actSaveExecute" procedure

**Comment by cheat-engine** [comment]
His issue is that dragging a file into the CE window doesn't show the question to merge and just opens

**Comment by mgrinzPlayer** [comment]
Now I got it. Lol. I will update my PR.

**Comment by Symbai** [comment]
Sorry talking about overwriting was misleading, my bad. Dark Byte is right, that was my issue 😊

**Comment by mgrinzPlayer** [comment]
Should be fixed in SVN.
