### ISSUE TITLE
high speed hitting breakpoints no fix?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#956]
1. hardware break point -> bsod

2. dbvm breakpoint -> Sometimes bsod

//////////////////////////////////////////////
msconfig -> cpu reduce cpu threads -> BSOD
msconfig -> ram size redude ->BSOD

cpu clock speed fix?? -> NO TEST

Breakpoint blue screen causes stress

It's impossible to solve by my ability

Is it difficult to solve enough to create breakpoint structure again?

**Comment by kitty8904** [comment]
cpu clock speed 4.5 GHZ -> BSOD
cpu clock speed 4.0 GHZ -> BSOD
cpu clock speed 3.5 GHZ -> BSOD
cpu clock speed 3.0 GHZ -> BSOD

Stop even if you lower the clock speed

Do you have a problem with Windows 10?

Windows 7 -> NO BSOD??

**Comment by cheat-engine** [comment]
Do you mean the find what access/break breakpoint or the actual breakpoint where execution stops

Anyhow, as i said in another of bugreport this can not be fixed  unless all the handling happens inside dbvm and no dbk is used at all

**Comment by kitty8904** [comment]
1 40d7e8 game inc value f5 read write breakpoint
2 maybe delay count add > speed control?
3 dbvm display add my  bad  skill

**Comment by kitty8904** [comment]
<img width="1739" alt="fix" src="https://user-images.githubusercontent.com/18622105/68015157-e2cf1800-fcd4-11e9-81fd-fd951714a0bb.png">

I found a cause for dark bytes.

I've tested on an additional SSD

Windows 8.1-> high spped break point-> NO BSOD

Windows 10 17763 ~ 18362-> BSOD

**Comment by kitty8904** [comment]
Does the SSD's read speed difference affect the blue screen? NVME SSD Windows 10 keeps freezing

**Comment by cheat-engine** [comment]
no, this is all an windows and cpu issue
If anything happens while the breakpoint has broken the stack gets corrupted so the return information is bad.

**Comment by kitty8904** [comment]
Is it a CPU issue of all OS?

Runs more reliably on Windows 8.1

I want to solve this problem but it's too hard

Thank you
