### ISSUE TITLE
Cheat Engine 7.0 Won't Start

### ISSUE THREAD

**Issue by WzyCampy** [cheat-engine/cheat-engine#958]
I don't have BadLion Client installed.
When I want to start cheat engine, it simply dosen't start. I can wait how much I want but it still dosen't start. pls helpp meeee

**Comment by cheat-engine** [comment]
Uninstall kaspersky and reboot

also, run driverquery /v to makebsure there is no badlion or kaspersky in that list

**Comment by WzyCampy** [comment]
I don't have kaspersky installed neither, but now I will reboot my pc to see if it works. btw I never had such of problems with cheat engine :/

**Comment by WzyCampy** [comment]
no, it still dosen't start

**Comment by TheK0tYaRa** [comment]
Have you tried looking into Task Manager? Does at least CheatEngine process start?

**Comment by cheat-engine** [comment]
are you starting the 64-bit CE build?
And try renaming the autorun folder in ce's folder to something else
also run `driverquery /v > bla.txt` and upload the bla.txt file here

**Comment by WzyCampy** [comment]
ummm, I tried es to run driverquery /v > bla.txt but nothing is happening, also cheat engine process dosen't start

**Comment by WzyCampy** [comment]
[bla.txt](https://github.com/cheat-engine/cheat-engine/files/3805759/bla.txt)
here is what I copyed, got all of it.

**Comment by WzyCampy** [comment]
I tried to change the folder name and still nothing :/

**Comment by cheat-engine** [comment]
`BadlionAntic BadlionAnticheat       BadlionAnticheat       Kernel        System     Running    OK         TRUE        FALSE        4.096             3.813.376   0          11.06.2019 14:54:22    \??\C:\WINDOWS\system32\drivers\BadlionAnticheat 4.096`

You need to run the badlion uninstaller and then restart your system.
Do not delete this file yourself, it will rebuild itself

**Comment by cheat-engine** [comment]
or open an admin command prompt and execute this
```
net stop BadlionAntic
net stop BadlionAnticheat
sc delete BadlionAntic
sc delete BadlionAnticheat
```
and don't forget to restart

**Comment by WzyCampy** [comment]
ok

**Comment by WzyCampy** [comment]
It worked!!!! Thank you sooooooooo much!!!!!
