### ISSUE TITLE
Execute service (android) on virtualspace

### ISSUE THREAD

**Issue by lahed** [cheat-engine/cheat-engine#960]
Hi, I wanted to know if it is possible to run the cheat engine (arm v7) service in a virtual space, without root (octopus, virtualxposed, etc)

Gameguardian does that, but I don't know how.

**Comment by frustreated** [comment]
maybe we could have a try. i tried to use ce to scan   vmware , indeed we could find data we wannt.  but we could not modify them, may be other process in vmware controling them.

**Comment by KenjiroIchise** [comment]
Build ceserver with a shared library and embed it in apk.
Works without rooting on the same principle as frida-gadget.

**Comment by lahed** [comment]
Thank you, fixed

**Comment by Enyby** [comment]
You can do this with [Cheat Engine server](https://gameguardian.net/forum/files/file/1975-cheat-engine-server/)
