### ISSUE TITLE
topmost lazarus bug?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#961]
<img width="283" alt="topmost" src="https://user-images.githubusercontent.com/18622105/68233785-3c23a800-0043-11ea-8b99-14000661dd1b.png">

1.SetWindowPos(handle, HWND_TOPMOST, 0, 0, 0, 0,0); self top most

2.Window := FindWindowA(nil,'Cheat Engine 7.0');

SetWindowPos(Window , HWND_TOPMOST, 0, 0, 0, 0,0);

Lazarus programs don't work with the top most

What options do you have?

Windows default program -> possible

lazarus exe program SetWindowPos api call  -> topmost no fix?? what??

**Comment by cheat-engine** [comment]
lua: `MainForm.FormStyle='fsSystemStayOnTop'`

**Comment by kitty8904** [comment]
> lua: `MainForm.FormStyle='fsSystemStayOnTop'`

It solved

But why can't I change it with the API?
