### ISSUE TITLE
cheat engine 7.0 does not work correctly

### ISSUE THREAD

**Issue by Atamg1994** [cheat-engine/cheat-engine#962]
Instructions in 7.0 take up more space than expected as a result of overwriting other memory regions in detail everything in the screenshots
![Screenshot_16](https://user-images.githubusercontent.com/57526178/68469616-2d93e700-0223-11ea-8386-a54c0cb6952d.png)
![Screenshot_17](https://user-images.githubusercontent.com/57526178/68469620-308ed780-0223-11ea-9f59-fecd2cfbcc56.png)
![Screenshot_18](https://user-images.githubusercontent.com/57526178/68469623-31c00480-0223-11ea-95b2-f1feb4c7c692.png)
![Screenshot_19](https://user-images.githubusercontent.com/57526178/68469625-3389c800-0223-11ea-9cb8-5fce4573b3aa.png)

but  6.8.3 version does not work search instructions that change the value at the address (veh debuger 64bit)
therefore, writing cheat on two versions at once is not convenient
waiting for fixing either
hint how to fix it yourself

7.0 due to the fact that replaces other regions leads to crash

ps - use google translator

**Comment by cheat-engine** [comment]
provide the 3th alloc parameter for allocation preference
e.g alloc(xxx,128,codevein-win64-shipping.exe)

that way the distance won't be bigger than 2GB, so it won't have to use 14 byte jmps

**Comment by Atamg1994** [comment]
so the problem is ... such a coh was automatically generated by an assembler

**Comment by Atamg1994** [comment]
aobscanmodule(RegenHpn,CodeVein-Win64-Shipping.exe,F3 0F 10 81 58 01 00 00) // should be unique
alloc(newmes,$1000,"CodeVein-Win64-Shipping.exe"+BEE31B0)

label(code)
label(big)
label(big1)
label(original)
label(return)

alloc(temp1NPC,$10)
alloc(minregenNPC,$10)
alloc(regenhpNPC,$10)
alloc(proc2NPC,$10)
alloc(xm14NPC,$10)
alloc(xm15NPC,$10)
registersymbol(temp1NPC)
registersymbol(minregenNPC)
registersymbol(regenhpNPC)
registersymbol(proc2NPC)
registersymbol(xm14NPC)
registersymbol(xm15NPC)

**Comment by Atamg1994** [comment]
I just wrote what I needed and now it works correctly in 6.8.3 and in 7.0 such problems

**Comment by Atamg1994** [comment]
thank you UTB help removed this part + BEE31B0

alloc (newmes, $ 1000, "CodeVein-Win64-Shipping.exe")

and everything began to work as needed very grateful
