### ISSUE TITLE
Right click activates script

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#966]
Using right click on the checkbox of a script activates the script but also opens the context menu for this item. Only one of it should be allowed I think.

**Comment by mgrinzPlayer** [comment]
Right click also:
- changes allowIncrease, allowDecrease on frozen entries
- expand/collapse

**Comment by Symbai** [comment]
@mgrinzPlayer Good catch, thanks for checking this. In my opinion it shouldn't do anything else than opening the context menu on right click.

**Comment by mgrinzPlayer** [comment]
It is easy to fix. It shouldn't break backward compatibility.

**Comment by Symbai** [comment]
Looks like @cheat-engine fixed it https://github.com/cheat-engine/cheat-engine/commit/d7aefcf64cc733ff6f729e8cb80de1bc3a59e5ea 

I haven't tested the fix but it looks like the fix skips the selection on right click. Wouldn't this cause a problem with the context menu? While I agree that check / collapse / expand should not be triggered by a right click, the item should still be selected. This seems to be more intuitive as its the same behavior else where like in memory viewer.

**Comment by mgrinzPlayer** [comment]
It doesn't skip the selection. You can close this issue.
