### ISSUE TITLE
cant open

### ISSUE THREAD

**Issue by tatby** [cheat-engine/cheat-engine#974]
i can not open cheat engine i deleted everythings even badlion and kasp nothing is happening
and  when i try to delete badlionanticheat.sys it says. this foler is in use and it says access denied 
even when i do it with the command propt

**Comment by TheGoldenCdr** [comment]
I'm having the same issue, please fix this.

**Comment by cheat-engine** [comment]
don't delete badlion, use their uninstaller else their malware will be left on your system 
and reboot your system afterwards (not shut down and back on actual reboot)

**Comment by TheGoldenCdr** [comment]
badlion malware?????????

**Comment by cheat-engine** [comment]
It runs all the time from the start of window till you turn off your systen without without your permission.
sees everything you execute
Prevents you from running applications you wish without your permission
and who knows what else it does, sees or sends back to it's developer

so yeah, malware is a valid classification
