### ISSUE TITLE
Dissect structure - Pointers should always be expandable

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#975]
Currently a pointer cannot be expanded if the selected column is an "invalid" address, even if all other items in this structure have a "valid" address at this offset. Selecting one of these items makes it expandable. In my opinion it should always be expandable

**Comment by cheat-engine** [comment]
Structure generation happens based on the selected structure.

Let's assume you have this state:
The currently selected column entry points to an unreadable address, and the colum left of it points to a wrong address because it got overwritten, and the column right of it points to a correct address?

How would you tell CE to use the right column instead of the left one ?

Also, if it is a pointer to a already defined structure then expanding does work, it's just the autogeneration of new local structures doesn't work in that case

**Comment by Symbai** [comment]
If I expand a pointer, all pointers on all columns at this offset get expanded. I would like exactly that behavior that already exist to work always. But it does not if the focused column points to an invalid address, which is weird because IT DOES get expanded if I focus another column with a valid pointer and expand again.

Take a look at this:
![image](https://user-images.githubusercontent.com/14368203/72096427-156b4180-3312-11ea-8cf5-4f2bc7f6f1b8.png)

I focus the first column and I can expand pointer at C0 which is declared as a pointer. If I do so all other columns get expanded too, even those who points to an invalid address (second column), great.

Now I focus the second column and expand pointer at C0, it won't. And that's what I was requesting. Invalid pointers get expanded anyway so there is nothing special to tell CE just do what it already does and ignore the current column.

So i am confused about your question or we misunderstand each other?

**Comment by cheat-engine** [comment]
Note that a pointer says "Pointer" before you expand it and "Pointer to Autocreated from xxxxx" after expanding.

CE can not autocreate if the addresss it's using to autocreate with is invalid, and it's not a good idea to pick any random address to autocreate with.

But once it has been created then next time you expand, or load a save, it won't need to create it anymore, so it will function even on invalid addresses

**Comment by Symbai** [comment]
Ah okay now I understand what you meant. You were talking about generating the offsets / value types. Yes it won't work on invalid structures. You would have to make them all 4 / 8 bytes which might not be that much useful in the end.
