### ISSUE TITLE
Dissect structure - Show current path

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#977]
Would be nice to show the current path in the bottom or top. Imaging we have lots of columns and expanded multi level pointers and probably even landed there by using the search, it is super hard to find the actual path to the current selection.

So once an item is selected it should show at bottom or top:

address -> offset -> offset -> offset -> ...

**Comment by cheat-engine** [comment]
now shows it as a pointernotation in the statusbar also showing how the base gets it's offset
