### ISSUE TITLE
breakpoint detect bypass?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#979]
There is a DBVM flag check during anti-security

Can you tell where the flag is?

void UnloadDriver(PDRIVER_OBJECT DriverObject)
{
	debugger_stopDebugging();

	//ultimap_disable();
	//DisableUltimap2();
	//UnregisterUltimapPMI();

	//clean_APIC_BASE();

	//NoExceptions_Cleanup();
	//

    IoDeleteDevice(DriverObject->DeviceObject);

	NTSTATUS r = IoDeleteSymbolicLink(&uszDeviceString);

	//DbgPrint("IoDeleteSymbolicLink: %x\n", r);

	//ExFreePool(BufDeviceString);

	//CleanProcessList();

	//ExDeleteResourceLite(&ProcesslistR);

	//RtlZeroMemory(&ProcesslistR, sizeof(ProcesslistR));

}

debugger_stopDebugging();

int debugger_stopDebugging(void)
{	
	int i;

	DbgPrint("Stopping the debugger if it is running\n");

	DebuggerState.stoppingTheDebugger=TRUE;	

	if (DebuggerState.globalDebug)
	{
		//touch the global debug for each debug processor
		DbgPrint("Touching the debug registers\n");
        forEachCpuPassive(debugger_touchDebugRegister, 0);
	}

	

        DebuggerState.globalDebug=FALSE; //stop when possible, saves speed
	DebuggerState.isDebugging=FALSE;	

	for (i=0; i<4; i++)
	DebuggerState.breakpoint[i].active=FALSE;

	//unhook all processors

	forEachCpuPassive(debugger_removeHookForCurrentCPU, 0);

	return TRUE;
}

1. DBVM breakpoint or hardwarebreakpoint LOAD

2. AnyProcess target F5 breakpoint hit(notepad.exe,calc.exe etc)
(memory viewer disassembler f5 breakpoint detect)

3 .Close Cheat Engine -> Anti Cheat Game Load

4. Cheat Engine debug detect Crash game

5. Cheat Engine driver Unload  

debugger_stopDebugging(); <- Here Debug Clear

6.Anti Cheat Game Load -> No Crash Game Load

what the debug flag?? detect??

If you access debug f5 once(memory brower disassbler debug)

The game cannot run until the drive is unloaded

bypass flag? code?

/////////////////////////////////////////////

dbvm find out what access memory -> no detect

memoryview -> f5 debug on -> detect!!

Only detected when memory view f5 is debugged

Is there any debug flag code loaded?

forEachCpuPassive 

inthook_UnhookInterrupt?

debugger_touchDebugRegister?

**Comment by kitty8904** [comment]
int inthook_HookInterrupt(unsigned char intnr, int newCS, ULONG_PTR newEIP, PJUMPBACK jumpback)

		switch (intnr)
		{
			case 1:
				vmx_redirect_interrupt1(virt_emulateInterrupt, 0, newCS, newEIP);
				break;

			case 3:
				//vmx_redirect_interrupt3(virt_emulateInterrupt, 0, newCS, newEIP);
				break;

			case 14:
				//vmx_redirect_interrupt14(virt_emulateInterrupt, 0, newCS, newEIP);
				break;
		}


int inthook_UnhookInterrupt(unsigned char intnr)


			if (intnr == 1)
			{
				vmx_redirect_interrupt1(virt_differentInterrupt, 1, 0, 0);
			}
			else if (intnr == 3)
			{
				//vmx_redirect_interrupt3(virt_differentInterrupt, 3, 0, 0);
			}
			else
			{
				//vmx_redirect_interrupt14(virt_differentInterrupt, 14, 0, 0);
			}


vmx_redirect_interrupt1(virt_differentInterrupt, 1, 0, 0);

vmx_redirect detected??

What flags do you get when hooking int1?

**Comment by kitty8904** [comment]
case VMCALL_REDIRECTINT1: //redirect int1
    {
      sendstring("VMCALL_REDIRECTINT1\n\r");
      if (vmcall_instruction[3] == 0)
      {
        int1redirection=vmcall_instruction[4];
        int1redirection_idtbypass=0;
        sendstringf("IDT1 redirection to int %d\n\r",int1redirection);
      }
      else
      {
        //rip
        int1redirection_idtbypass_cs = vmcall_instruction[7];  //cs
        int1redirection_idtbypass_rip = *(UINT64 *)&vmcall_instruction[5]; //rip
        int1redirection_idtbypass=1;

        sendstringf("IDT1 bypass to %x:%6\n\r",int1redirection_idtbypass_cs, int1redirection_idtbypass_rip);
      }

      if (isAMD)
      {
        //start intercepting
        if (vmcall_instruction[3] == 2) //2 is disable redirect alltogether
          currentcpuinfo->vmcb->InterceptExceptions&=~(1<<1); //unset bit 1 (int1 exception)
        else
          currentcpuinfo->vmcb->InterceptExceptions|=(1<<1); //set bit 1 (int1 exception)

        currentcpuinfo->vmcb->VMCB_CLEAN_BITS&=~(1 << 0); //the intercepts got changed
      }

      vmregisters->rax = 0;
      break; 

Or is there a flag in DBVM?

I wonder what is detected

**Comment by cheat-engine** [comment]
disable global debug if it's on

**Comment by kitty8904** [comment]
> disable global debug if it's on

Do you detect global debug?

Are not detected when global is turned off

But in miprocessloaderentry drive hidden state

f5breakpoint is detected

In drive hiding,

     dr7.DR7 = vmread (vm_guest_dr7);
     dr7.GD = 0;
     vmwrite (vm_guest_dr7, dr7.DR7);

Where should I put the code?

**Comment by cheat-engine** [comment]
is dbvm breakpoint detected when global debug is off?

**Comment by kitty8904** [comment]
global debug detect yes

original cheat engine driver 
1. global debug off -> dbvm breakpoint f5 -> no detect

hide fix driver
1.global debug off -> dbvm breakpoint f5  -> detect

And the security company seems to be detecting global debug.

Detect when global debug routine is ON
