### ISSUE TITLE
C#  API / Library

### ISSUE THREAD

**Issue by r89m** [cheat-engine/cheat-engine#98]
Hi there,

I am currently writing an application in C# to provide alternative game controls for disabled users. As part of this project there is a requirement to slow down the speed of the game, as at their default speed users are unable to send inputs fast enough to be successful at the game.

At the moment we are controlling the game speed manually using CheatEngine alongside our program. This works very well for many games but is less elegant than we would like.

Is there any means by which we would be able to control the game speed using Cheat Engine as the back end directly from C#, via something like a command line API or library?

I've had a look through the forum and existing issues and can't seem to find an answer, but please feel free to direct me to any existing discussions regarding this.

All the best,

Richard

**Comment by cheat-engine** [comment]
You can use ce's Lua interface to issue commands, like openProcess(processname) and speedhack_setSpeed(speed)

To launch the Lua interface for other apps to use, call openLuaServer("something") first. You can do that in the background by launching a .cetrainer file with that Lua command in it. When launched with a cetrainer, the main gui will not show up, but will run

more info and an example in C#
http://forum.cheatengine.org/viewtopic.php?p=5687454#5687454

Date: Mon, 15 Aug 2016 04:10:35 -0700

**Comment by r89m** [comment]
That sounds great. Thanks so much for taking the time to not only point me in the right direction but come up with a sample project!
