### ISSUE TITLE
TGroupData.compareblock_outoforder with customtype

### ISSUE THREAD

**Issue by mgrinzPlayer** [cheat-engine/cheat-engine#980]
TGroupData.CustomScan
https://github.com/cheat-engine/cheat-engine/blob/fa7f68569a9ee0f321cb31f774612d3497105615/Cheat%20Engine/memscan.pas#L1164

TGroupData.CustomScanFloat
https://github.com/cheat-engine/cheat-engine/blob/fa7f68569a9ee0f321cb31f774612d3497105615/Cheat%20Engine/memscan.pas#L1197

I think it should be
```Pascal
while i<(blocksize-(ct.bytesize-1)) do
```

------------
based on those
------------
TGroupData.SingleScan
(4-1)=3
https://github.com/cheat-engine/cheat-engine/blob/fa7f68569a9ee0f321cb31f774612d3497105615/Cheat%20Engine/memscan.pas#L1098

TGroupData.DoubleScan
(8-1)=7
https://github.com/cheat-engine/cheat-engine/blob/fa7f68569a9ee0f321cb31f774612d3497105615/Cheat%20Engine/memscan.pas#L1130

**Comment by cheat-engine** [comment]
Mathematically
`while i<(blocksize-ct.bytesize-1) do `
is the same as
`while i<(blocksize-(ct.bytesize-1)) do`

**Comment by cheat-engine** [comment]
Alright

**Comment by cheat-engine** [comment]
should be fixed now
