### ISSUE TITLE
Scan for mono class instances dont reset taskbar progress

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#985]
Scanning for a mono class instance never resets the taskbar icon progress. Even after scan the taskbar still shows a progress bar on the CE icon with a >90% progress:

![image](https://user-images.githubusercontent.com/14368203/68995643-e5f70600-0887-11ea-9efa-4f438be94f61.png)

**Comment by cheat-engine** [comment]
fixed
