### ISSUE TITLE
Hex viewer - Change value not respecting hex view + typo

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#986]
Set view to a hex decimal and then trying to change the value shows the value in decimal instead, which is annoying when we know the desired hex decimal value but not its decimal representation.

Also it likely shouldn't be titled "Change offset" but "Change value" instead?

![image](https://user-images.githubusercontent.com/14368203/68997804-5b6fd000-08a2-11ea-8668-59d4842a17e4.png)

**Comment by cheat-engine** [comment]
the editor window doesn't have a display type for 8 byte hex, but you can add the `0x` or `$`  in front and then followed by the hexadecimal value, ce will understand

and in this case it meant address, which offset is also ok

**Comment by Symbai** [comment]
Sure, but we would need to first type the value it displays which is annoying again. Why not just add a checkbox next to the combobox "As hex" and then show / read the textbox text as hex?

**Comment by cheat-engine** [comment]
should work better now for 2 byte and up

**Comment by yosaf055** [comment]
should work better now for 2 byte and up

**Comment by yosaf055** [comment]
> should work better now for 2 byte and up
