### ISSUE TITLE
not letting me download 

### ISSUE THREAD

**Issue by MinoaBaccus** [cheat-engine/cheat-engine#988]
look my anti-virus says that is is a virus look for your self pliz fix it hears a link to proof https://www.youtube.com/watch?v=SqmRjXT6ZX4

**Comment by MinoaBaccus** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa loooooooooooooooook https://www.youtube.com/watch?v=3a_bfbrROsY

**Comment by cheat-engine** [comment]
ignore the potentially unwanted program called fusioncore, it's ok as long as you read

and the searchbar you installed because you didn't close the window

**Comment by cheat-engine** [comment]
stop clicking add to chrome. Close that window instead

**Comment by JesperJofficial** [comment]
I have the same problem with downloading the exe. file. I'm trying to download the 6.8.1 version, but it just says 'downloading error' (i'm dutch so i dont know if thats the exact message in english). I hope you can help us with this.
