### ISSUE TITLE
Hex viewer - Unexpected jump when CTRL is pressed

### ISSUE THREAD

**Issue by Symbai** [cheat-engine/cheat-engine#999]
Pressing CTRL immediately jumps to last selection which is unexpected and unwanted in certain situations.

Repro:
1. Go to 00400000
2. Select first byte
3. Go to 7FF00000
4. Press CTRL

Demo:
![Untitled Project](https://user-images.githubusercontent.com/14368203/69497568-7364d680-0ed6-11ea-9bf2-dbd0373ee87e.gif)

**Comment by Symbai** [comment]
Unexpected and unwanted situation is when jumping to an address and then trying to change the display type which uses the hotkeys:

CTRL 1-9

but as soon as pressing CTRL it jumps back.

**Comment by cheat-engine** [comment]
fixed
